/* RN Ready — item bank v3j · part 10 (PN-specific depth).
   The bank reached the RN growth target at v3i, so this batch is the first
   PN-scope wave: every item is written from the practical/vocational nurse
   perspective — coordinated care under RN direction, reinforcement of teaching,
   data collection and reporting, stable and predictable clients in long-term
   care, home care, and clinic settings. Weighting follows the 2026 PN blueprint
   gaps in the shared pool (CC/MOC +8 · PSY +5 · BCC +4 · SIC +3 · PHA +3 ·
   HPM +2 · RRP +2 · PAA +3). Two items join existing variant groups
   (delegation-uap, hypoglycemia-15g).

   History: these items were originally tagged fam:"PN" when the bank served both
   NCLEX-RN and NCLEX-PN. The product is RN-only now, so the tags were dropped —
   the content itself is unchanged and remains fully usable.  */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Coordinated Care (PN 21%) ─────────────────────────────────────── */
{id:"MOC-049", t:"single", cn:"MOC", sys:"NEURO", topic:"Change-of-condition reporting", d:1, b:0.0, cj:"recognize", tags:["ltc","change-of-condition","escalation"],
 stem:"The practical nurse is making morning rounds in a long-term care facility. Which resident change should the nurse report to the supervising RN before completing the rest of the pass?",
 opts:["An 84-year-old who was oriented yesterday now cannot state the month and keeps calling for a parent",
  "A resident asks for extra blankets because the room feels cold this morning",
  "A resident requests that the television channel be changed to the news",
  "A family member asks when the care conference is scheduled to start"],
 ans:0,
 rat:{c:"New confusion in an older adult is a sentinel change-of-condition — possible delirium from infection, hypoxia, or medication effect — and requires immediate reporting so the RN and provider can evaluate. Comfort, preference, and scheduling requests are handled by the practical nurse directly.",
  o:["Correct — acute mental-status change is a report-now finding, not a wait-and-chart finding.",
    "Comfort requests are within the practical nurse's independent resolution.",
    "Preferences are part of routine care and resident choice.",
    "Scheduling questions are answered or routed to the unit clerk — no clinical escalation needed."],
  s:"Change-of-condition rule: new confusion, new falls, new incontinence, eating change, or behavior change = stop and report to the RN now."},
 ref:"Long-term care · change-of-condition reporting"},

{id:"MOC-050", t:"single", cn:"MOC", sys:"MSK", topic:"Delegation in home care", d:1, b:-0.05, cj:"generate", tags:["delegation","uap","home-care"], variantGroup:"delegation-uap",
 stem:"During a home-care visit, the practical nurse is preparing to leave and the family asks which helper tasks the home health aide may do for their mother this week. Which task is within the aide's role?",
 opts:["Assisting with a shower and reminding the client to use her walker in the hallway",
  "Changing the dressing on the client's heel ulcer before the next nurse visit",
  "Adjusting the client's insulin dose when her breakfast is small",
  "Deciding whether the client's blood pressure medicine can be skipped today"],
 ans:0,
 rat:{c:"Home health aides assist with activities of daily living, mobility, and reminders within an established plan — bathing with the walker is squarely in that role. Wound care, medication decisions, and any dose adjustment are licensed-nurse functions.",
  o:["Correct — ADL assistance plus a safety reminder is classic aide scope.",
    "Wound care is skilled nursing — not delegable to an aide.",
    "Insulin dosing decisions belong to licensed staff under orders.",
    "Deciding to hold medication is never an aide function."],
  s:"Aide scope = help with daily living and reminders. Anything sterile, anything medication, anything judgment = licensed nurse."},
 ref:"Home care · delegation to aides"},

{id:"MOC-051", t:"single", cn:"MOC", sys:"CV", topic:"Assignment within scope", d:2, b:0.2, cj:"analyze", tags:["assignment","scope","acuity"],
 stem:"The charge RN is making assignments on a skilled nursing unit. Which client is most appropriate for the practical nurse's assignment?",
 opts:["A client two days after hip replacement who is transferring with one assist and needs routine analgesia",
  "A client admitted an hour ago with uncontrolled atrial fibrillation and dropping blood pressure",
  "A client with a new chest tube placed this morning after a pleural effusion drainage",
  "A client receiving the first dose of a new chemotherapy regimen for oral mucositis"],
 ans:0,
 rat:{c:"The practical nurse cares for stable, predictable clients: the post-operative hip client with an established plan fits. The unstable new admission, the fresh chest tube, and initial chemotherapy (anaphylaxis risk, first-dose teaching) call for RN-level assessment and management.",
  o:["Correct — predictable trajectory, routine medications, established plan.",
    "Unstable dysrhythmia with hypotension = RN assessment and titration.",
    "New chest tubes require RN-level respiratory assessment and troubleshooting.",
    "First-dose chemo carries reaction risk and RN teaching requirements."],
  s:"Assignment math for the practical nurse: stable + predictable + established plan. New, unstable, or first-dose goes to the RN."},
 ref:"Assignment · practical nurse scope"},

{id:"MOC-052", t:"single", cn:"MOC", sys:"ENDO", topic:"Reinforcing RN teaching", d:1, b:0.05, cj:"evaluate", tags:["teaching","reinforcement","scope"],
 stem:"A client newly started on insulin asks the practical nurse in the clinic to explain how to draw up the doses for the first time. Which action is within the practical nurse's role?",
 opts:["Reinforce the RN's original teaching by observing a return demonstration and answering routine questions",
  "Provide the complete initial instruction independently since the client asked directly",
  "Tell the client to read the package insert and call back with questions",
  "Defer all insulin education until the next physician appointment in three months"],
 ans:0,
 rat:{c:"Initial teaching is an RN function, but practical nurses reinforce, observe return demonstrations, and answer routine questions — and they escalate gaps the RN needs to reteach. Refusing engagement or delaying months abandons the client's immediate safety need.",
  o:["Correct — reinforcement and return demonstration are squarely practical-nurse practice.",
    "Initial comprehensive instruction for a new therapy belongs to the RN who assessed learning needs.",
    "A pamphlet is a supplement, never the teaching plan.",
    "Three months of unreviewed insulin self-administration is unsafe."],
  s:"Teaching roles in one line: RN initiates and evaluates, practical nurse reinforces and reports gaps back."},
 ref:"Client education · role differentiation"},

{id:"MOC-053", t:"single", cn:"MOC", sys:"GI", topic:"Documentation correction", d:1, b:0.0, cj:"act", tags:["documentation","legal"],
 stem:"While reviewing notes before handoff, the practical nurse realizes yesterday's entry listed the wrong colostomy output amount. Which documentation practice is correct?",
 opts:["Draw a single line through the error, write “error,” initial and date it, then record the correct figure",
  "Erase the wrong figure completely and write the correct one over it",
  "Use correction fluid so the chart looks clean before the survey team arrives",
  "Leave the error in place and mention the correction verbally at shift report"],
 ans:0,
 rat:{c:"Legal medical records are never erased or obscured: a single line, the word “error,” initials, date, and the correct entry preserve the audit trail. Obliterating entries (erasures, fluid) suggests tampering, and verbal-only corrections vanish from the record.",
  o:["Correct — the single-line method keeps the original visible and the correction traceable.",
    "Erasure destroys the legal trail and implies concealment.",
    "Correction fluid is prohibited for the same reason — transparency over tidiness.",
    "Verbal corrections are lost; the chart must carry them."],
  s:"Chart correction recipe: one line, “error,” initial, date, correct entry. Never erase, never obliterate, never verbal-only."},
 ref:"Documentation · error correction"},

{id:"MOC-054", t:"single", cn:"MOC", sys:"GI", topic:"Consent witness role", d:2, b:0.15, cj:"recognize", tags:["consent","witness","scope"],
 stem:"A client scheduled for a colonoscopy asks the practical nurse to explain the procedure's risks because the RN is busy. Which response keeps the practical nurse within scope?",
 opts:["“The RN or the provider will review the risks with you — I can stay while they do, and I have signed that I saw you sign.”",
  "“I can go over the main risks with you right now since you seem ready to sign.”",
  "“Just sign it now and ask the doctor afterward in the procedure room.”",
  "“Nobody explains the risks; the form itself lists everything you need.”"],
 ans:0,
 rat:{c:"Explaining risks and benefits and obtaining informed consent is a provider-and-RN function; the practical nurse may WITNESS the signature and confirm voluntariness. Explaining risks independently, rushing a signature, or pointing only to fine print all breach the consent process.",
  o:["Correct — witness the signature, verify willingness, route the explanation to the right professional.",
    "Risk explanation by the practical nurse exceeds scope and voids the witness role.",
    "Signing before understanding is the opposite of informed consent.",
    "Consent is a conversation, not a formality."],
  s:"Practical nurse consent role = witness and verify voluntariness. The explanation itself belongs to the provider/RN."},
 ref:"Informed consent · witnessing"},

{id:"MOC-055", t:"drag", cn:"MOC", sys:"RESP", topic:"Home emergency escalation", d:2, b:0.25, cj:"prioritize", tags:["home-care","emergency","prioritization"],
 stem:"During a home visit, the client suddenly becomes severely short of breath with audible wheezing and cannot finish a sentence. Order the practical nurse's actions from FIRST to LAST.",
 drag:{targets:["1 — First","2","3","4 — Last"],
  opts:[
   "Stay with the client, sit them upright, and have the family call 911",
   "Check the client's oxygen saturation and prescribed rescue inhaler availability",
   "Administer the prescribed rescue inhaler per the standing home protocol",
   "Notify the supervising RN and agency of the event and actions taken"
  ],
  ans:[0,1,2,3]},
 rat:{c:"Emergencies at home follow the same hierarchy as anywhere: stay and position, activate 911, gather data and apply protocolized treatment, then loop in the supervising RN and document. Leaving to phone first abandons the client; documentation and supervisor notification follow stabilization, not precede it.",
  o:["Correct — never leave a gasping client; positioning and 911 activation come first.",
    "Correct — rapid data and rescue-medication check while help is en route.",
    "Correct — protocolized rescue inhaler use is within practical-nurse scope at home.",
    "Correct — supervisor notification and documentation complete the event trail."],
  s:"Home emergency order: stay + position + 911 → assess → protocol treatment → notify and document."},
 ref:"Home care · emergency response"},

{id:"MOC-056", t:"single", cn:"MOC", sys:"ENDO", topic:"Medication pass prioritization", d:1, b:0.05, cj:"prioritize", tags:["time-management","medications","insulin"],
 stem:"At 0730 the practical nurse is preparing medications for four home-bound clients visited in sequence. Which medication should be given at the earliest stop?",
 opts:["The 0730 pre-breakfast rapid-acting insulin for a client about to eat",
  "The 0800 once-daily multivitamin scheduled with breakfast",
  "The 0900 topical cortisone cream for a stable skin rash",
  "The 1000 transdermal patch change scheduled mid-morning"],
 ans:0,
 rat:{c:"Time-critical medications lead the pass: rapid-acting insulin must synchronize with food intake to prevent post-meal spikes or mismatch hypoglycemia. Vitamins, topical treatments, and mid-day patches hold flexibility of an hour or more.",
  o:["Correct — mealtime insulin is the time-critical dose in this set.",
    "Vitamins ride along with breakfast but tolerate shifts.",
    "A stable rash treatment is not time-critical.",
    "Mid-morning patches have wide administration windows."],
  s:"Sequence the pass by time-criticality: insulin with meals first; slow-window doses ride later stops."},
 ref:"Medication administration · time-critical doses"},

/* ── Safety & Infection Prevention and Control (PN 13%) ────────────── */
{id:"SIC-037", t:"single", cn:"SIC", sys:"GI", topic:"Outbreak precautions", d:1, b:0.1, cj:"act", tags:["norovirus","outbreak","ltc"],
 stem:"Norovirus is sweeping a long-term care unit. Which precaution practice should the practical nurse apply for affected residents?",
 opts:["Contact precautions with soap-and-water handwashing after caring for each resident with symptoms",
  "Contact precautions with alcohol-based rub, which is faster between rooms",
  "Droplet precautions with a standard surgical mask inside the room",
  "No special precautions because norovirus is already unit-wide"],
 ans:0,
 rat:{c:"Norovirus spreads by contact and vomitus aerosol, and alcohol rubs are poorly effective against it — soap-and-water washing plus contact precautions (gown/glove, dedicated equipment) is the outbreak standard. Droplet-only and no-precaution options ignore the fecal-oral and environmental spread.",
  o:["Correct — contact precautions plus soap and water, the norovirus-specific detail.",
    "Alcohol rub fails against norovirus — the classic exam discriminator.",
    "A mask alone misses the hands-and-environment highway.",
    "Unit-wide outbreaks argue for MORE rigor, not less."],
  s:"Norovirus mnemonic: soap beats sanitizer. Contact precautions, dedicated equipment, bleach-clean the environment."},
 ref:"Norovirus · long-term care outbreaks"},

{id:"SIC-038", t:"single", cn:"SIC", sys:"RESP", topic:"Home oxygen safety", d:1, b:-0.1, cj:"generate", tags:["oxygen-safety","home-care","teaching"],
 stem:"The practical nurse is reinforcing home-oxygen safety with a client starting continuous oxygen by concentrator. Which instruction is essential?",
 opts:["Keep tubing at least 10 feet away from open flames, and post no-smoking signs at the entrances",
  "Use the oxygen only at night so the concentrator does not overheat the apartment",
  "Apply petroleum-based ointment around the nose and lips to prevent drying",
  "Turn the flow rate up whenever shortness of breath worsens, ahead of calling anyone"],
 ans:0,
 rat:{c:"Oxygen feeds flames: no smoking within 10 feet, signs posted, tubing clear of stoves and candles. Petroleum products near the mask are a fire and skin-integrity hazard, and patients never self-titrate flow — worsening dyspnea is a call-the-clinic event.",
  o:["Correct — fire separation and signage are the first-line home-oxygen teaching.",
    "Concentrators run continuously by design; nighttime-only use is a prescriber decision.",
    "Petroleum near oxygen is flammable — water-based lubricants only.",
    "Self-titration is prohibited; symptom changes are reported, not treated by flow changes."],
  s:"Home oxygen trio: nothing burning within 10 feet, water-based moisture only, and the flow rate belongs to the prescriber."},
 ref:"Home oxygen therapy · safety teaching"},

{id:"SIC-039", t:"multi", cn:"SIC", sys:"INTG", topic:"Standard precautions at home", d:1, b:0.0, cj:"generate", tags:["standard-precautions","home-care","ppe"],
 stem:"The practical nurse is preparing to empty a client's colostomy pouch and change a soiled dressing during a home visit. Select every standard-precaution practice that applies.",
 opts:["Clean gloves for pouch emptying, changed before touching clean supplies",
  "Hand hygiene before and after every glove removal",
  "A gown when splashing of drainage is likely",
  "Double-gloving for all care regardless of task",
  "Keeping the drainage container below waist level during emptying"],
 ans:[0,1,2,4],
 rat:{c:"Standard precautions match barriers to exposure: gloves for drainage contact (changed between dirty and clean tasks), hand hygiene around glove use, a gown when splashes are likely, and gravity-friendly container position to limit spatter. Double-gloving for everything is not a standard-precaution requirement.",
  o:["Correct — gloves for exposure, changed before clean tasks to stop cross-contamination.",
    "Correct — hand hygiene is the anchor around every glove episode.",
    "Correct — anticipated splash = gown.",
    "Routine double-gloving is policy-specific, not a standard-precaution rule.",
    "Correct — below-waist emptying keeps drainage controlled and away from the face."],
  s:"Standard precautions are about matching barrier to exposure — gloves, hygiene, gown when wet, and physics (keep the dirty side low)."},
 ref:"Standard precautions · home visits"},

/* ── Health Promotion & Maintenance (PN 9%) ────────────────────────── */
{id:"HPM-027", t:"single", cn:"HPM", sys:"INF", topic:"Adult immunization reinforcement", d:1, b:-0.1, cj:"evaluate", tags:["immunization","tdap","reinforcement"],
 stem:"A 55-year-old clinic client cannot remember the last tetanus shot and reports stepping on a nail last week while gardening. Which guidance should the practical nurse reinforce after the provider's orders?",
 opts:["A tetanus-containing booster is given now if more than ten years have passed since the last dose",
  "No booster is needed because an adult tetanus series lasts for life",
  "Tetanus protection only matters for children whose boosters are due",
  "The wound itself provides immunity through natural exposure"],
 ans:0,
 rat:{c:"Td or Tdap boosters run every ten years, and a dirty wound with an unknown or overdue history means a booster now. Lifelong childhood immunity, adult exemption, and natural-exposure immunity are tetanus myths — the bacterium's toxin leaves no immune memory after disease.",
  o:["Correct — unknown history plus a contaminated wound = boost now.",
    "Ten-year coverage expires; it is not lifelong.",
    "Adults need decennial boosters and wound-driven catch-up.",
    "Tetanus disease does not confer immunity — the toxin dose is too small to immunize."],
  s:"Tetanus clock: booster every 10 years; a dirty wound plus an unknown clock reads zero."},
 ref:"Immunization · tetanus boosters"},

{id:"HPM-028", t:"single", cn:"HPM", sys:"GI", topic:"Cancer screening reinforcement", d:1, b:0.0, cj:"generate", tags:["screening","colorectal","clinic"],
 stem:"A 46-year-old with average colorectal cancer risk asks what screening is recommended after hearing a friend's diagnosis. Which reinforcement is accurate?",
 opts:["Screening begins at 45, with stool-based tests yearly or colonoscopy every ten years as options to discuss",
  "Screening starts only when symptoms such as bleeding or bowel changes appear",
  "Colonoscopy is the only acceptable method, required every two years from 45",
  "Average-risk screening begins at 60 unless a parent had polyps"],
 ans:0,
 rat:{c:"Average-risk colorectal screening starts at 45 with multiple accepted strategies — annual stool-based tests or colonoscopy every ten years among them — chosen with the provider. Symptom-triggered testing is diagnosis, not screening; two-year colonoscopies exceed any guideline; and 60 is two decades late.",
  o:["Correct — 45 start, options include annual stool testing or ten-year colonoscopy.",
    "Waiting for symptoms misses the entire point of screening.",
    "No guideline demands colonoscopy that often for average risk.",
    "Average-risk start is 45 — family history moves it earlier, not later."],
  s:"Colorectal screening: 45 and average risk, stool test yearly or scope every ten — choice belongs to client and provider."},
 ref:"Cancer screening · colorectal start age"},

/* ── Psychosocial Integrity (PN 12%) ───────────────────────────────── */
{id:"PSY-027", t:"single", cn:"PSY", sys:"NEURO", topic:"Dementia communication", d:1, b:0.05, cj:"act", tags:["dementia","validation","communication"],
 stem:"A resident with advanced dementia paces the hallway each evening saying, “I have to get home to cook dinner for the children.” Which response is most therapeutic?",
 opts:["“Your children are grown now. Let's look at these family photos together and get ready for bed.”",
  "“You tell me that every night — your children are nowhere nearby, remember?”",
  "“There's no cooking here. The kitchen closed at six and your family knows it.”",
  "“If you keep talking about leaving, I'll have to keep you in your room tonight.”"],
 ans:0,
 rat:{c:"Later-stage dementia calls for validation-plus-redirection: acknowledge the feeling's era gently, then redirect to a satisfying activity. Confrontational correction fuels agitation, factual debates land as rejection, and threatened confinement is both non-therapeutic and a rights violation.",
  o:["Correct — validate the emotional world, redirect to the present and a calming activity.",
    "Repetitive confrontation about reality escalates distress without adding orientation.",
    "Flat fact-and-rules answers dismiss the emotional need driving the behavior.",
    "Threatening confinement as behavior control is coercive and reportable."],
  s:"Late-dementia communication: join the feeling, then steer. Correcting the facts is for early stages; comfort outranks accuracy at this stage."},
 ref:"Dementia care · validation and redirection"},

{id:"PSY-028", t:"single", cn:"PSY", sys:"PSYCH", topic:"Family adjustment to placement", d:1, b:0.1, cj:"act", tags:["ltc","family","guilt","communication"],
 stem:"The daughter of a newly placed nursing-home resident says, “I promised Mom I'd never put her in a home. I feel like I failed her.” Which response by the nurse is most therapeutic?",
 opts:["“It sounds like this decision weighs heavily on you. Would you like to talk about what made placement necessary now?”",
  "“At least your mother is getting better care here than she would at home alone.”",
  "“Guilt is normal, but you'll get over it once you visit a few times.”",
  "“You did promise her — have you thought about taking her back home?”"],
 ans:0,
 rat:{c:"Placement grief is real: the therapeutic response names the weight and invites the story. Minimizing comparisons, prescribing recovery timelines, and inviting impulsive reversal all dismiss or complicate the daughter's process.",
  o:["Correct — reflect the feeling and open the narrative.",
    "Comparative comfort dismisses the loss being expressed.",
    "Timelines for someone else's grief are presumptuous and silencing.",
    "Stirring reversal guilt destabilizes a care decision already made for safety."],
  s:"Family placement guilt: name it, invite it, normalize it. Defend the decision later — after the feeling has room."},
 ref:"Long-term care · family transition"},

{id:"PSY-029", t:"matrix", cn:"PSY", sys:"NEURO", topic:"Delirium vs dementia vs depression", d:2, b:0.2, cj:"analyze", tags:["delirium","dementia","differentiation"],
 stem:"A home-health client's daughter asks whether her mother's confusion is “the start of dementia.” For each feature, decide whether it points to DELIRIUM or to DEMENTIA as the more typical pattern.",
 matrix:{cols:["Delirium","Dementia"], rows:[
  "Begins abruptly over hours to a few days",
  "Attention wanders wildly; the client cannot focus even briefly",
  "Symptoms are clearly worse in the evening hours",
  "Slowly progressive decline over two or more years",
  "Consciousness itself is clouded, with drowsiness or agitation"
 ], mode:"one", ans:[0,0,0,1,0]},
 rat:{c:"Delirium = acute onset, wrecked attention, fluctuation across the day (sundowning-style worsening), and clouded consciousness. Dementia = insidious years-long decline with relatively preserved attention early and clear consciousness until late. Evening worsening alone overlaps in both but is a delirium-fluctuation hallmark when it appears suddenly.",
  s:"Three D's in a line: Delirium = days + attention + fluctuation; Dementia = years + memory; Depression = mood first, concentration complaints, intact orientation."},
 ref:"Cognitive impairment · delirium versus dementia"},

{id:"PSY-030", t:"single", cn:"PSY", sys:"NEURO", topic:"Bath refusal in dementia", d:1, b:0.0, cj:"act", tags:["dementia","adl","approach"],
 stem:"A resident with moderate dementia refuses the scheduled shower, backing away and saying “no” loudly. Which approach should the nurse use?",
 opts:["Defer the shower, offer a relaxing alternative activity now, and retry later in the shift",
  "Proceed quickly with the shower anyway since it is the scheduled care time",
  "Tell the resident that family visits depend on being clean for them",
  "Document the refusal and skip hygiene entirely for the rest of the week"],
 ans:0,
 rat:{c:"Refusal in dementia is communication — meet it with flexibility: defer, soothe, retry when calm, or substitute a bed bath. Forcing care risks injury and trauma, coercing with family leverage is manipulative, and abandoning hygiene for a week creates skin-integrity risks.",
  o:["Correct — flexibility and timing solve most dementia care refusals.",
    "Forcing care escalates aggression and destroys trust.",
    "Conditional family visits turn hygiene into a threat.",
    "Total hygiene abandonment trades one problem for a worse one."],
  s:"Dementia refusals are timing problems, not authority problems: back off, regroup, retry — and keep cleanliness coming another way."},
 ref:"Dementia care · activities of daily living"},

{id:"PSY-031", t:"single", cn:"PSY", sys:"GI", topic:"Religious dietary needs", d:1, b:0.05, cj:"act", tags:["spirituality","cultural-care","advocacy"],
 stem:"A newly admitted resident keeps kosher, and the lunch tray delivered contains both meat and dairy items together. Which action by the nurse best meets the resident's needs?",
 opts:["Return the tray to dietary with a request for a kosher meal and inform the supervising RN of the mix-up",
  "Remove the dairy item from the tray and serve the rest to avoid delay",
  "Ask the resident whether removing the dairy item makes the rest acceptable for kosher practice",
  "Note the preference in the care plan and hope dietary adjusts by next week"],
 ans:0,
 rat:{c:"Kosher observance covers preparation and combination, not just the visible items — separating components on a non-kosher tray does not make it kosher. The right move is a corrected meal plus communication up the chain so the kitchen flag actually sticks.",
  o:["Correct — replace the whole tray and close the loop with the supervisor.",
    "Removing one component leaves a non-kosher meal — observance is not item-by-item.",
    "Shifting the adaptation burden onto the resident is not respectful care.",
    "A passive note leaves the resident hungry today and mis-fed tomorrow."],
  s:"Religious dietary needs are unit-level fixes: replace the meal, flag the kitchen, and tell the RN — never make the client assemble their own accommodation."},
 ref:"Cultural and spiritual care · dietary observance"},

/* ── Basic Care & Comfort (PN 10%) ─────────────────────────────────── */
{id:"BCC-027", t:"multi", cn:"BCC", sys:"GI", topic:"Dysphagia feeding", d:1, b:0.05, cj:"generate", tags:["dysphagia","feeding","aspiration"],
 stem:"The practical nurse is feeding a resident with documented dysphagia after a stroke. Select every practice that reduces aspiration risk.",
 opts:["Sitting the resident fully upright at 90 degrees during and 30 minutes after the meal",
  "Offering small bites with the chin slightly tucked for each swallow",
  "Thin liquids by straw because strays pace the flow better",
  "Checking the mouth for pocketed food after eating",
  "Talking through a television program while the resident eats"],
 ans:[0,1,3],
 rat:{c:"Aspiration precautions: upright 90° (held 30 minutes post-meal), small bites with chin-tuck swallowing, and a post-meal mouth check for pocketed food. Straws accelerate thin liquids toward the airway (the hardest consistency to control), and distraction during swallowing increases risk.",
  o:["Correct — gravity plus upright time is the backbone of safe feeding.",
    "Correct — small volume plus chin tuck protects the airway entrance.",
    "Straws flood the pharynx — thickened liquids and cup sips are safer.",
    "Correct — pocketed food can silently aspirate later.",
    "Distraction and swallowing do not mix; conversation pauses between bites."],
  s:"Dysphagia feeding: 90 up, small and slow, chin tucked, cheeks checked — and quiet attention, not entertainment."},
 ref:"Dysphagia · safe feeding practices"},

{id:"BCC-028", t:"single", cn:"BCC", sys:"GI", topic:"Ostomy diet advancement", d:1, b:-0.05, cj:"evaluate", tags:["colostomy","diet","teaching"],
 stem:"A client is six weeks past a sigmoid colostomy and asks about returning to normal meals. Which advice is accurate?",
 opts:["Reintroduce foods one at a time and note any that cause gas, odor, or blockage symptoms",
  "Stay on a permanent soft, low-fiber diet to protect the stoma",
  "Resume all foods immediately in full portions because healing is complete",
  "Follow a strict meat-free plan since fiber and meat both obstruct stomas"],
 ans:0,
 rat:{c:"Post-ostomy eating returns to a normal diet by trial: add one food at a time and observe output effects (gas, odor, thickening), chewing thoroughly — with special care reintroducing high-fiber stringy foods. Permanent restriction, instant full resumption, and meat elimination are all unsupported.",
  o:["Correct — systematic reintroduction with observation is the standard guidance.",
    "No permanent soft diet is required — restriction invites nutrition deficits.",
    "Full portions immediately ignore the trial-and-error the gut requires.",
    "Meat is not contraindicated; chewing well is the operative habit."],
  s:"Ostomy diets normalize by experiment: one new food at a time, watch the bag, chew thoroughly."},
 ref:"Colostomy · dietary progression"},

{id:"BCC-029", t:"single", cn:"BCC", sys:"MSK", topic:"Heat and cold therapy", d:1, b:0.0, cj:"generate", tags:["thermal-therapy","comfort","safety"],
 stem:"The practical nurse is applying a warm compress to a home client's shoulder per the care plan. Which practice keeps the application safe?",
 opts:["Barrier cloth between skin and heat, treatment no longer than 20 minutes, and skin checks during use",
  "Direct pack-to-skin contact for the fastest deep-muscle warming effect",
  "Continuous application for a full hour to break the muscle spasm",
  "Reapplying immediately after removal with no inspection interval"],
 ans:0,
 rat:{c:"Thermal therapy safety: a cloth barrier (never direct skin contact), a 15–20 minute ceiling, and periodic skin checks — especially for older adults, diabetics, and anyone with reduced sensation. Hour-long application and immediate reapplication invite burns and rebound tissue injury.",
  o:["Correct — barrier, time ceiling, and skin checks are the three safeguards.",
    "Direct contact concentrates heat and burns.",
    "Beyond 20 minutes the tissue risks the opposite of the intended effect.",
    "Inspection intervals exist to catch erythema before it becomes injury."],
  s:"Heat or cold: cloth between, twenty-minute clock, look at the skin. The extremes of contact and duration are how comfort therapy becomes injury."},
 ref:"Thermal therapy · safe application"},

{id:"BCC-030", t:"single", cn:"BCC", sys:"PSYCH", topic:"Sleep promotion in LTC", d:1, b:0.05, cj:"generate", tags:["sleep","ltc","nonpharmacologic"],
 stem:"A resident sleeps poorly at night and dozes through daytime activities. Which measure should the nurse try first to restore a normal sleep-wake cycle?",
 opts:["Increase daytime light exposure and structured activity, then cluster night care to protect a sleep block",
  "Request a standing sedative-hypnotic at bedtime from the provider",
  "Encourage long daytime naps so the resident is not overtired at night",
  "Serve coffee with dinner to build a stronger evening fatigue effect"],
 ans:0,
 rat:{c:"Nonpharmacologic sleep restoration comes first: bright daytime light, engagement, exercise, and clustered overnight care that protects an uninterrupted sleep window. Sedatives add fall and delirium risk in older adults, daytime napping reinforces cycle inversion, and dinner caffeine sabotages the goal.",
  o:["Correct — retiming the day is the root-cause treatment for cycle inversion.",
    "Sedative-hypnotics are last-resort, short-course options in older adults.",
    "Long naps deepen the inversion being treated.",
    "Evening caffeine delays sleep onset — the opposite of the plan."],
  s:"Fix night sleep by fixing the day: light, movement, engagement, and a protected sleep block — pills come last."},
 ref:"Sleep · long-term care promotion"},

/* ── Pharmacotherapy (PN 13%) ──────────────────────────────────────── */
{id:"PHA-053", t:"single", cn:"PHA", sys:"ENDO", topic:"Insulin storage", d:1, b:0.0, cj:"evaluate", tags:["insulin","storage","home-care"],
 stem:"During a home visit, the practical nurse finds the client storing every insulin pen in the freezer “to keep it fresh.” Which teaching is correct?",
 opts:["The in-use pen stays at room temperature up to 28 days; unopened pens live in the refrigerator — the freezer ruins insulin",
  "Freezing is ideal as long as the insulin thaws fully before each injection",
  "All pens stay in the freezer until the expiration date on the box",
  "Room-temperature storage works for every pen indefinitely once opened"],
 ans:0,
 rat:{c:"Insulin in use tolerates room temperature for about 28 days (product-specific); unopened stock is refrigerated — and freezing denatures insulin, making it unreliable. Frozen-then-thawed dosing and indefinite room storage both risk erratic glucose control.",
  o:["Correct — room-temperature in-use pen, refrigerated unopened stock, freezer never.",
    "Thawed frozen insulin is damaged goods — potency is unpredictable.",
    "The freezer destroys insulin regardless of expiration dating.",
    "In-use periods are finite — 28 days for most pens, then discard."],
  s:"Insulin storage split: open = room (≤28 days), sealed = fridge, frozen = trash."},
 ref:"Insulin therapy · storage rules"},

{id:"PHA-054", t:"single", cn:"PHA", sys:"ENDO", topic:"OTC-herbal interaction reporting", d:2, b:0.15, cj:"analyze", tags:["medication-reconciliation","herbals","reporting"],
 stem:"During a medication reconciliation at an assisted-living facility, a resident mentions taking St. John's wort daily “for mood” along with prescribed warfarin. Which action by the nurse is correct?",
 opts:["Report the combination to the supervising RN and pharmacist the same day for interaction review",
  "Reassure the resident that herbal products cannot interact with prescriptions",
  "Advise doubling the warfarin dose to overcome the herbal effect",
  "Document the supplement only if the resident reports bleeding gums"],
 ans:0,
 rat:{c:"St. John's wort induces liver enzymes and drops warfarin levels — a classic clot-risk interaction. The practical nurse's role is immediate reporting for professional review, not reassurance, dose self-help, or wait-for-symptoms documentation.",
  o:["Correct — flag herbals during reconciliation and route the review to RN and pharmacist.",
    "Herbals interact through the same enzymes as prescriptions — this one famously.",
    "Doubling anticoagulation on a guess is dangerous on every level.",
    "Waiting for bleeding gums means waiting on the wrong symptom — this interaction lowers INR."],
  s:"Every herbal is a drug at reconciliation. St. John's wort + warfarin = enzyme induction = clots. Report, don't reassure."},
 ref:"Medication safety · herbal interactions"},

{id:"PHA-055", t:"cloze", cn:"PHA", sys:"GI", topic:"PEG tube administration", d:2, b:0.2, cj:"generate", tags:["peg-tube","administration","safety"],
 stem:"Complete the safe-administration sequence for medications through a client's PEG tube.",
 cloze:{lines:[
  {pre:"Before giving anything, the nurse verifies tube placement by ", post:" per facility protocol.",
   opts:["checking marked insertion length and aspirating gastric contents","listening for bubbles after an air bolus alone","asking the client whether the tube feels normal","skipping checks once the tube is two weeks old"], ans:0},
  {pre:"Medications are given one at a time, each dissolved or liquid, with ", post:" between drugs.",
   opts:["a 15–30 mL water flush","a 15–30 mL juice flush","no flush to avoid fluid overload","a brisk shake of the bag"], ans:0},
  {pre:"Enteric-coated and extended-release tablets ", post:" because crushing dumps the full dose at once or destroys the drug.",
   opts:["are never crushed for tube giving","may be crushed if mixed into applesauce","are fine to crush when time is short","crush better after brief microwaving"], ans:0}
 ]},
 rat:{c:"PEG safety: verify placement (mark + aspirate) before anything enters the tube, flush 15–30 mL water between separately administered drugs, and never crush enteric-coated or extended-release forms — crushing destroys their design and dumps dosing.",
  o:["Correct — objective placement checks precede every administration window.","An air bolus alone cannot distinguish gastric from respiratory placement.","Subjective reports never verify placement.","Age of the tube does not retire the verification step.",
    "Correct — water flushes carry each drug through and prevent interactions in the lumen.","Juice can interact with drug chemistry.","Flushing prevents overload issues — 30 mL is trivial volume for most.","Agitation is not a substitute for sequencing.",
    "Correct — dosage-form integrity is a hard stop.","Applesauce does not un-crush an enteric coating.","Convenience never overrides dosage form.","Heat degrades drugs — and belongs nowhere near this decision."],
  s:"PEG trio: verify placement, flush between drugs, and treat dosage forms as sacred — coatings exist for a reason."},
 ref:"Enteral tubes · medication administration"},

/* ── Reduction of Risk Potential (PN 12%) ──────────────────────────── */
{id:"RRP-040", t:"single", cn:"RRP", sys:"ENDO", topic:"Diabetic foot screening", d:1, b:-0.05, cj:"recognize", tags:["diabetes","foot-exam","data-collection"],
 stem:"The practical nurse performs the quarterly diabetic foot check at a senior clinic. Which finding should be reported for same-day provider review?",
 opts:["A callus with a pinpoint dark center over the ball of the foot and reduced monofilament sensation in two toes",
  "Long-standing flat, painless corns on both little toes that the client has had for years",
  "Dry skin on the heels without breaks, improved since the last emollient teaching",
  "One ingrown toenail edge with mild surrounding redness in a client with intact sensation"],
 ans:0,
 rat:{c:"A pressure-point dark center suggests a pre-ulcerative hematoma or early ulcer, and monofilament loss marks protective-sensation loss — together these predict ulceration and demand same-day escalation. Stable corns, improving dry skin, and intact-sensation ingrown nails are routine findings for monitoring and clinic care.",
  o:["Correct — protective sensation loss plus a pressure-point lesion is the high-risk combination.",
    "Stable, unchanged corns are routine foot-care findings.",
    "Improving skin integrity documents success, not risk.",
    "Intact sensation lowers urgency; monitor and care for the nail per protocol."],
  s:"Diabetic foot triage: loss of protective sensation + a break or pressure mark = escalate today. Everything else monitors."},
 ref:"Diabetes · foot risk screening"},

{id:"RRP-041", t:"single", cn:"RRP", sys:"INTG", topic:"Wound dehiscence at home", d:2, b:0.25, cj:"act", tags:["wound","dehiscence","home-care","emergency"],
 stem:"During a home visit, the practical nurse finds a post-operative abdominal incision has opened along half its length with a small amount of serosanguineous drainage; no organs are visible. Which action is correct?",
 opts:["Cover the wound with a sterile moist dressing, keep the client still and NPO, and arrange emergency transport while notifying the supervising RN and surgeon",
  "Pack the wound edges tightly with dry gauze and apply an abdominal binder before leaving",
  "Close the gap with sterile strips from the visit bag and schedule a recheck in a week",
  "Irrigate the open wound with full-strength hydrogen peroxide and redress it"],
 ans:0,
 rat:{c:"Dehiscence without evisceration is still an emergency: protect the wound with a sterile moist dressing, minimize movement and oral intake in case surgical repair is needed, arrange transport, and alert the RN and surgeon. Tight packing, home closure attempts, and peroxide irrigation all damage exposed tissue and delay definitive care.",
  o:["Correct — moist protection, stillness, NPO, transport, and upstream notification.",
    "Tight packing crushes exposed tissue and hides the defect.",
    "Home re-closure of a dehisced incision is beyond any home-care scope.",
    "Full-strength peroxide cytotoxically damages new tissue — never on open wounds."],
  s:"Any dehiscence: moist sterile cover, still and NPO, transport, tell the surgeon. Evisceration only adds a saline-soaked cover and no food or drink by mouth."},
 ref:"Wound complications · dehiscence response"},

/* ── Physiological Adaptation (PN 10%) ─────────────────────────────── */
{id:"PAA-053", t:"single", cn:"PAA", sys:"RESP", topic:"COPD baseline monitoring", d:1, b:0.05, cj:"analyze", tags:["copd","home-care","reporting-thresholds"],
 stem:"A home client with severe COPD has a usual oxygen saturation of 88–90% on room air. Which reading should the practical nurse report promptly?",
 opts:["84% on room air with new confusion and a respiratory rate of 28/min",
  "89% on room air before the morning nebulizer, as usual",
  "92% after the scheduled pulmonary rehabilitation exercises",
  "90% during an afternoon nap without other symptoms"],
 ans:0,
 rat:{c:"COPD clients live at lower saturations — the alarm is a drop below the client's own baseline WITH symptoms: 84% plus new confusion and tachypnea signals CO2 retention or exacerbation and needs urgent reporting. Values within the documented baseline, post-exercise gains, and asymptomatic naps are expected patterns.",
  o:["Correct — below-baseline saturation with mental-status change is the report-now combination.",
    "Her documented baseline — routine, not reportable.",
    "Exercise-improved saturation is the desired direction.",
    "A stable asymptomatic nap reading matches her pattern."],
  s:"COPD monitoring runs against the client's OWN baseline: a real drop plus new symptoms = escalate; the textbook 'normal' does not apply."},
 ref:"COPD · home monitoring thresholds"},

{id:"PAA-054", t:"single", cn:"PAA", sys:"ENDO", topic:"Hypoglycemia home protocol", d:1, b:-0.1, cj:"act", tags:["hypoglycemia","15-15-rule","home-care"], variantGroup:"hypoglycemia-15g",
 stem:"A home client on insulin checks a glucose of 52 mg/dL during the afternoon visit. The client is alert but shaky and sweaty. Which action follows the standard home protocol?",
 opts:["Give 15 grams of fast-acting carbohydrate now and recheck the glucose in 15 minutes",
  "Give the next scheduled insulin dose early to stabilize the swings",
  "Have the client drink a glass of diet soda to avoid a glucose spike",
  "Wait 30 minutes and recheck, since the client is alert and talking"],
 ans:0,
 rat:{c:"Rule of 15: symptomatic hypoglycemia in an alert client = 15 g fast carbohydrate (juice, glucose tabs, regular soda), recheck at 15 minutes, repeat if still low, then a protein-containing snack. Insulin now would deepen the low, diet soda carries no carbohydrate at all, and waiting treats a correctable emergency as a spectator.",
  o:["Correct — treat with 15 grams, recheck at 15 minutes, repeat as needed.",
    "More insulin during hypoglycemia is the opposite of treatment.",
    "Diet beverages have no sugar — they cannot raise glucose.",
    "Alert hypoglycemia is treated now, not watched."],
  s:"Low and alert = 15 and 15: fifteen grams of sugar, fifteen minutes, recheck, repeat, then a real snack."},
 ref:"Hypoglycemia · rule of 15 at home"},

{id:"PAA-055", t:"single", cn:"PAA", sys:"MSK", topic:"Assistive device fitting", d:1, b:0.0, cj:"evaluate", tags:["walker","fitting","mobility"],
 stem:"The practical nurse checks a client's new rolling walker before a first home ambulation attempt. Which observation indicates a correct fit?",
 opts:["The handgrips sit level with the crease of the client's wrists when standing upright, elbows bending about 20–30 degrees",
  "The handgrips reach the client's mid-forearm so the arms fully straighten for pushing",
  "The walker's seat height matches the bed so transfers need no pivot",
  "The frame sits two steps ahead of the doorways it must pass through"],
 ans:0,
 rat:{c:"Walker fit: grips at wrist-crease height with 20–30 degrees of elbow flexion when standing — that transfers weight safely without shoulder strain. Mid-forearm grips are too high (straight arms cannot shift weight), and seat/doorframe dimensions are transfer-and-environment issues, not fit criteria.",
  o:["Correct — wrist-crease height with relaxed elbow bend is the fitting standard.",
    "Fully straight arms lock the shoulders and prevent weight-shifting.",
    "Seat height concerns sitting devices, not this walking frame.",
    "Doorway width is an environment check, not a client-fit check."],
  s:"Walker fit: stand tall, arms hanging — grips at the wrist crease, elbows softly bent. Everything else adjusts around that."},
 ref:"Mobility aids · walker fitting"}
);
