/* RN Ready — item bank v3e · part 5 (bank growth toward the 2026 blueprint).
   Weighted for the under-represented categories on both RN and PN plans:
   Coordinated/Management of Care 8 · Pharmacology 6 · Reduction of Risk 4 ·
   Basic Care & Comfort 4 · Safety 3 · Psychosocial 2 · Health Promotion 2 ·
   Physiological Adaptation 1. Three new variant groups extend the
   anti-memorization engine (warfarin-inr · hypoglycemia-15g · isolation-airborne). */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Management of Care / Coordinated Care ───────────────────────── */
{id:"MOC-016", t:"matrix", cn:"MOC", sys:"INF", topic:"Delegation / team members", d:2, b:0.15, cj:"generate", tags:["delegation","team"],
 stem:"For each task below, mark the team member to whom the RN may appropriately assign it on a stable medical unit. Select one cell per row.",
 matrix:{ mode:"radio", cols:["RN only","LPN/VN","UAP"],
   rows:[
     "Interpret a client's rising potassium level and adjust the plan of care",
     "Administer an oral antibiotic to a stable client",
     "Bathe and reposition a client who is stable after a stroke",
     "Reinforce teaching about a low-sodium diet started earlier by the RN"],
   ans:[0,1,2,1]},
 rat:{c:"Analysis and care-plan changes are non-delegatable RN work. LPNs/VNs may administer routine oral medications to stable clients and reinforce prior teaching; UAPs perform routine hygiene and repositioning for stable clients.",
  s:"Sort by judgment: anything requiring nursing judgment or initial teaching/assessment stays with the RN; routine, standardized, stable-client tasks move down the chain."},
 ref:"Delegation & assignment · scope by team member"},

{id:"MOC-017", t:"single", cn:"MOC", sys:"CV", topic:"Assignment / acuity", d:2, b:0.5, cj:"prioritize", tags:["assignment","prioritize"],
 stem:"The charge RN on a telemetry unit is assigning four clients to a float RN who is unfamiliar with the unit. Which assignment is most appropriate?",
 opts:["A client admitted 2 hours ago with chest pain on a nitroglycerin drip, still titrating",
  "A client 1 day post-cardiac catheterization with stable vital signs",
  "A client with a new-onset heart block receiving external pacing",
  "A client in acute pulmonary edema on high-flow oxygen and IV diuretics"],
 ans:1,
 rat:{c:"The stable post-catheterization client has predictable, routine care — the safest match for a float RN who does not know the unit's protocols. Unstable, titrating, or rapidly changing clients belong to the unit's own staff.",
  o:["Titration of vasoactive drips requires unit familiarity and continuous reassessment — not a first choice for a float.",
     "Correct — stable, predictable, routine post-procedure care suits an unfamiliar nurse.",
     "New heart block with pacing is high-acuity and can deteriorate rapidly.",
     "Acute pulmonary edema is an emergency requiring an experienced, unit-based team."],
  s:"For float/agency staff, assign the MOST stable, MOST routine clients; keep titrations, pacing, and emergencies with unit staff."},
 ref:"Assignment by acuity · float staff"},

{id:"MOC-018", t:"single", cn:"MOC", sys:"MSK", topic:"Delegation", d:1, b:-0.25, cj:"act", tags:["delegation"], variantGroup:"delegation-uap",
 stem:"A UAP reports that a client who is 2 days post hip replacement “seems confused and keeps trying to climb out of bed.” What is the RN's best action?",
 opts:["Tell the UAP to reorient the client and stay with them",
  "Assess the client personally now, then update the plan of care",
  "Ask the UAP to apply a bed alarm and check back in an hour",
  "Document the report and reassess the client at the next scheduled rounds"],
 ans:1,
 rat:{c:"A new change in mental status after surgery is an assessment red flag (possible delirium, hypoxia, infection). The RN must personally assess — assessment cannot be delegated — and revise the plan.",
  o:["Delegating ongoing care of an acute mental-status change delays RN assessment.",
     "Correct — new confusion is an RN-level assessment trigger; the RN evaluates now.",
     "A bed alarm may be part of the later plan but does not replace RN assessment.",
     "Waiting for scheduled rounds is unsafe with an acute change."],
  s:"Any NEW finding — especially mental status after surgery — triggers personal RN assessment before task delegation."},
 ref:"Delegation · when the RN must assess"},

{id:"MOC-019", t:"single", cn:"MOC", sys:"GI", topic:"Advocacy / client rights", d:1, b:-0.1, cj:"act", tags:["advocacy","ethics"],
 stem:"A client scheduled for a colonoscopy says, “I changed my mind — I don't want the procedure today.” What is the nurse's priority action?",
 opts:["Notify the provider so the consent can be revisited with the client",
  "Remind the client the bowel prep is already completed",
  "Encourage the client to proceed since the procedure is important",
  "Cancel the procedure and document the refusal immediately"],
 ans:0,
 rat:{c:"A client may withdraw consent at any time. The nurse's role is to notify the provider, who must address the client's concerns — the decision is then documented. Pressure to proceed violates autonomy.",
  o:["Correct — withdrawing consent triggers provider notification and a fresh consent conversation.",
     "Sunk-cost framing (the prep is done) pressures the client — not advocacy.",
     "Encouraging continuation minimizes the client's right to refuse.",
     "The nurse does not unilaterally cancel; the provider and client revisit the decision first."],
  s:"Consent can be withdrawn any time: notify the provider, support the client's autonomy, then document."},
 ref:"Informed consent · right to refuse"},

{id:"MOC-020", t:"single", cn:"MOC", sys:"NEURO", topic:"Informed consent", d:2, b:0.35, cj:"act", tags:["consent","legal"],
 stem:"A client with expressive aphasia after a stroke needs a feeding tube placement. The provider has explained the procedure. Who signs the consent if the client can indicate choices by pointing to a yes/no board?",
 opts:["The client, after the nurse confirms understanding through yes/no responses",
  "The spouse, because aphasia makes the client incapable of consent",
  "The oldest adult child with documented power of attorney",
  "Two providers together, citing the client's inability to communicate"],
 ans:0,
 rat:{c:"Aphasia affects expression, not necessarily comprehension or decision-making capacity. If the client can reliably communicate choices, the client consents — capacity is decision-specific and assumed absent evidence otherwise.",
  o:["Correct — capacity is decision-specific; reliable alternative communication preserves the client's right to consent.",
     "Speech difficulty alone does not transfer consent to a surrogate.",
     "A healthcare proxy signs only when the client lacks capacity.",
     "Provider consent substitution is not a mechanism; surrogates or the client decide."],
  s:"Don't confuse communication barriers with incapacity — adapt communication and assess capacity before defaulting to a surrogate."},
 ref:"Consent · capacity vs communication barriers"},

{id:"MOC-021", t:"multi", cn:"MOC", sys:"ENDO", topic:"Continuity of care", d:2, b:0.25, cj:"generate", tags:["discharge","care-coordination"],
 stem:"A client with newly diagnosed type 2 diabetes is being discharged home on metformin. Which discharge actions are essential? Select all that apply.",
 opts:["Schedule follow-up lab work including renal function and A1c",
  "Teach the client to stop metformin before any contrast imaging study",
  "Advise the client that hypoglycemia is the most common metformin side effect",
  "Confirm the client can state the signs of lactic acidosis and when to call",
  "Instruct the client to take metformin on an empty stomach at bedtime"],
 ans:[0,1,3],
 rat:{c:"Metformin requires renal-function monitoring, must be held around iodinated contrast (acute kidney injury risk), and rare lactic acidosis warrants teaching. Alone it rarely causes hypoglycemia, and it is taken with meals to reduce GI upset.",
  o:["Correct — baseline and periodic renal function and A1c guide safe continuation.",
     "Correct — holding metformin at contrast time prevents accumulation and acidosis risk.",
     "Metformin monotherapy rarely causes hypoglycemia — this teaching point is wrong.",
     "Correct — malaise with rapid breathing, muscle pain, or drowsiness warrants an urgent call.",
     "Metformin is taken with meals to limit GI upset — bedtime fasting dosing is incorrect."],
  s:"For metformin discharge teaching, anchor on three safety points: kidneys, contrast, lactic acidosis."},
 ref:"Discharge planning · metformin safety"},

{id:"MOC-022", t:"single", cn:"MOC", sys:"INF", topic:"Quality improvement", d:2, b:0.4, cj:"analyze", tags:["quality-improvement","safety"],
 stem:"After a client received a medication intended for another patient, the unit's quality council maps each step of the process to find where the system failed. Which QI approach is being used?",
 opts:["Root cause analysis",
  "Failure mode and effects analysis",
  "Plan-Do-Study-Act cycle",
  "Benchmarking against peer units"],
 ans:0,
 rat:{c:"Root cause analysis (RCA) retrospectively examines an event that already occurred, mapping the chain of contributing system factors. FMEA is prospective; PDSA tests change; benchmarking compares performance.",
  o:["Correct — retrospective chain analysis of an actual event is RCA.",
     "FMEA imagines possible failures BEFORE an event happens.",
     "PDSA is a rapid-cycle method for testing an improvement idea.",
     "Benchmarking compares metrics across units, not event chains."],
  s:"RCA looks back at what happened; FMEA looks forward at what could happen."},
 ref:"Quality improvement methods"},

{id:"MOC-023", t:"single", cn:"MOC", sys:"MSK", topic:"Negligence / malpractice", d:2, b:0.3, cj:"analyze", tags:["legal"],
 stem:"A nurse fails to perform scheduled turning on a immobile client over an entire shift; a stage 2 pressure injury develops and is documented the next day. Which element of malpractice is the documented injury?",
 opts:["Duty of care",
  "Breach of duty",
  "Causation",
  "Damages"],
 ans:3,
 rat:{c:"The four elements: duty (owed care), breach (failure to meet the standard), causation (link between breach and harm), and damages — the actual harm suffered. The pressure injury is the damages.",
  o:["Duty is the nurse–client relationship and standard owed, not the injury.",
     "Breach is the omitted turning, not the resulting injury.",
     "Causation connects the omission to the injury.",
     "Correct — the injury itself is the damages element."],
  s:"Memorize the chain: Duty → Breach → Causation → Damages; match each fact to its element."},
 ref:"Malpractice elements"},

/* ── Pharmacological Therapies ─────────────────────────────────── */
{id:"PHA-031", t:"single", cn:"PHA", sys:"ENDO", topic:"Hypoglycemia", d:1, b:-0.2, cj:"act", tags:["hypoglycemia","emergency"], variantGroup:"hypoglycemia-15g",
 stem:"A client with type 1 diabetes becomes sweaty, shaky, and irritable 90 minutes after lunch. The glucometer reads 52 mg/dL and the client is awake and can swallow. What does the nurse do first?",
 opts:["Give 4 oz (120 mL) of fruit juice and recheck in 15 minutes",
  "Administer the prescribed glucagon injection",
  "Call the provider for a stat insulin adjustment",
  "Give a peanut butter sandwich and recheck in 1 hour"],
 ans:0,
 rat:{c:"Awake + able to swallow = mild-to-moderate hypoglycemia: 15 g fast-acting carbohydrate (4 oz juice), then recheck in 15 minutes. Glucagon is for the unconscious/unable-to-swallow client; fat-laden snacks delay absorption.",
  o:["Correct — 15 g fast carbs, recheck at 15 minutes, repeat if still <70.",
     "Glucagon is reserved for severe hypoglycemia when the client cannot safely swallow.",
     "Insulin adjustment is irrelevant acutely — the client needs sugar now.",
     "Fat + protein slows glucose rise — wrong tool for an acute low."],
  s:"Rule of 15s: 15 g fast sugar → 15-minute recheck → repeat. Fat delays rescue."},
 ref:"Hypoglycemia rescue ladder (variant presentation)"},

{id:"PHA-032", t:"single", cn:"PHA", sys:"HEME", topic:"Anticoagulation", d:2, b:0.45, cj:"prioritize", tags:["anticoagulation","drug-interaction"], variantGroup:"warfarin-inr",
 stem:"A client taking warfarin for a mechanical heart valve is prescribed a 7-day course of trimethoprim-sulfamethoxazole for a urinary infection. Today the INR is 4.8 with gum bleeding. Which provider order should the RN anticipate first?",
 opts:["Hold warfarin and monitor — the antibiotic potentiates warfarin",
  "Administer vitamin K 10 mg IV push immediately",
  "Continue warfarin at the same dose and recheck INR weekly",
  "Switch the antibiotic to a course of ciprofloxacin"],
 ans:0,
 rat:{c:"TMP-SMX inhibits warfarin metabolism, raising INR; with bleeding at INR 4.8, the first move is holding warfarin and monitoring closely. High-dose IV vitamin K and reversal agents are reserved for major bleeding.",
  o:["Correct — hold, monitor, treat the interaction; anticipate bridging decisions from the provider.",
     "IV vitamin K 10 mg is for major/life-threatening bleeding — this is minor gum oozing.",
     "Continuing at the same dose deepens supratherapeutic anticoagulation.",
     "Ciprofloxacin ALSO potentiates warfarin — switching to it repeats the problem."],
  s:"When INR climbs on a new antibiotic, think interaction: hold anticoagulant, monitor, expect the antibiotic choice to be revisited."},
 ref:"Warfarin drug interactions (variant presentation)"},

{id:"PHA-033", t:"single", cn:"PHA", sys:"INF", topic:"Aminoglycoside toxicity", d:2, b:0.55, cj:"evaluate", tags:["antibiotics","monitoring"],
 stem:"A client has been on gentamicin for 6 days. Which new finding most warrants the RN holding the next dose and notifying the provider?",
 opts:["Serum creatinine rising from 0.9 to 1.8 mg/dL",
  "Gentamicin trough level of 1 mcg/mL",
  "Oral temperature of 99.1 °F (37.3 °C)",
  "Mild nausea without vomiting"],
 ans:0,
 rat:{c:"Aminoglycosides are nephrotoxic and ototoxic; a doubling creatinine signals kidney injury — hold the dose and notify. The next dose decision belongs to the provider with fresh levels.",
  o:["Correct — acute kidney injury on gentamicin = stop-and-call.",
     "A trough of 1 is within the typical trough range (<2) — not toxic.",
     "Low-grade temperature is not a toxicity sign.",
     "GI upset alone is not the priority toxicity marker."],
  s:"Aminoglycoside safety = kidneys and ears: watch creatinine, urine output, hearing/ringing; hold on new injury."},
 ref:"Aminoglycosides · nephrotoxicity monitoring"},

{id:"PHA-034", t:"multi", cn:"PHA", sys:"NEURO", topic:"Opioid safety", d:2, b:0.2, cj:"act", tags:["opioid","emergency","monitoring"],
 stem:"The nurse is caring for a client receiving a morphine patient-controlled analgesia (PCA) pump. Which actions reduce the risk of opioid-induced respiratory depression? Select all that apply.",
 opts:["Continuous pulse oximetry with alarm limits",
  "Teaching the family to press the button when the client sleeps",
  "Sedation scoring before each PCA dose escalation",
  "Keeping naloxone immediately available on the unit",
  "Running a baseline capnography check on every client"],
 ans:[0,2,3],
 rat:{c:"Monitoring (oximetry), structured sedation assessment, and naloxone readiness are the standard defense layers. Proxy dosing — anyone but the client pressing the button — defeats PCA safety; routine capnography is for high-risk settings, not every client.",
  o:["Correct — oximetry with alarms catches desaturation early.",
     "Proxy button-pressing during sleep is a known cause of overdoses — never allowed.",
     "Correct — sedation precedes respiratory depression; score it often.",
     "Correct — naloxone must be immediately available and staff familiar with it.",
     "Capnography is reserved for high-risk clients (OSA, high doses), not routine for all."],
  s:"PCA safety trio: monitor oxygen, score sedation, keep naloxone close — and only the CLIENT presses the button."},
 ref:"PCA safety · respiratory depression prevention"},

{id:"PHA-035", t:"single", cn:"PHA", sys:"CV", topic:"Antihypertensives", d:1, b:-0.15, cj:"recognize", tags:["antihypertensive","side-effects"],
 stem:"A client started on lisinopril 3 weeks ago reports a persistent dry, hacking cough. Vital signs are stable. What is the nurse's best response?",
 opts:["Explain that ACE inhibitors can cause this cough and report it for a possible medication change",
  "Reassure the client the cough will resolve once a toler develops",
  "Advise stopping the medication until the cough disappears",
  "Suggest an over-the-counter cough suppressant with dextromethorphan"],
 ans:0,
 rat:{c:"Dry cough is a classic, bradykinin-related ACE-inhibitor effect that usually does NOT resolve; the standard path is reporting for a switch (commonly to an ARB). Clients should never stop antihypertensives on their own.",
  o:["Correct — recognize, report, expect a class switch such as an ARB.",
     "The cough rarely resolves with time — waiting is poor advice.",
     "Unsupervised stopping risks uncontrolled hypertension.",
     "Masking the symptom ignores the cause and delays the switch."],
  s:"ACE inhibitor + dry cough = bradykinin effect: report for a possible ARB switch."},
 ref:"ACE inhibitors · bradykinin cough"},

{id:"PHA-036", t:"single", cn:"PHA", sys:"PSYCH", topic:"Mood stabilizers", d:2, b:0.5, cj:"act", tags:["lithium","toxicity"],
 stem:"A client on lithium for bipolar disorder calls the clinic with tremors, mild confusion, and vomiting after starting a new diuretic for ankle swelling. What is the nurse's priority instruction?",
 opts:["Hold the next lithium dose and come in now for a lithium level and renal check",
  "Take the lithium with food and drink a liter of water before bed",
  "Skip the diuretic but continue lithium as prescribed",
  "Use the dose as normal; these are common starting side effects"],
 ans:0,
 rat:{c:"Thiazide diuretics reduce lithium clearance — tremor, confusion, and vomiting indicate rising toxicity. Lithium is held and levels/renal function are checked urgently.",
  o:["Correct — suspected toxicity: hold, urgent level, provider review.",
     "Hydration alone does not fix a drug-clearance interaction.",
     "Self-adjusting the diuretic without assessment delays diagnosis.",
     "These symptoms are NOT benign start-up effects once a diuretic entered the picture."],
  s:"Sodium/water balance controls lithium: new diuretic + neuro/GI symptoms = toxicity until proven otherwise."},
 ref:"Lithium · diuretic interaction"},

/* ── Reduction of Risk Potential ───────────────────────────────── */
{id:"RRP-022", t:"single", cn:"RRP", sys:"REN", topic:"Laboratory interpretation", d:2, b:0.35, cj:"act", tags:["potassium","labs"],
 stem:"A client with chronic kidney disease has a potassium level of 6.1 mEq/L. Which nursing action is the priority?",
 opts:["Place the client on a continuous cardiac monitor and notify the provider",
  "Encourage potassium-rich foods to be spread across meals",
  "Recheck the level in 8 hours before intervening",
  "Increase the IV fluid rate to dilute the serum potassium"],
 ans:0,
 rat:{c:"K+ above 6.0 risks life-threatening dysrhythmias — monitor the heart continuously and treat promptly (calcium, insulin/dextrose, etc. via provider orders).",
  o:["Correct — cardiac monitoring plus immediate notification address the lethal risk.",
     "More potassium is the last thing this client needs.",
     "Waiting 8 hours on K+ 6.1 invites dysrhythmias.",
     "Dilution does not remove potassium from the body — and fluids may be restricted in CKD."],
  s:"K+ ≥6: think ECG first — the heart kills before the kidneys complain."},
 ref:"Hyperkalemia · cardiac risk"},

{id:"RRP-023", t:"single", cn:"RRP", sys:"CV", topic:"Thrombolytic monitoring", d:2, b:0.4, cj:"evaluate", tags:["thrombolytic","bleeding"],
 stem:"A client received alteplase 45 minutes ago for an ischemic stroke. Which assessment finding requires the most immediate provider notification?",
 opts:["Blood pressure 158/92 mm Hg",
  "New oozing from the IV site and a drop in hematocrit",
  "Headache reported as 3/10 without neurologic change",
  "Heart rate of 104/min, regular"],
 ans:1,
 rat:{c:"Active bleeding with falling hematocrit during thrombolytic therapy signals systemic hemorrhage — the therapy's most feared complication — and demands immediate notification and reversal planning. BP 158/92 matters but is a treatment-target adjustment; isolated mild headache and mild tachycardia are common.",
  o:["Above-target BP needs treatment per protocol, but bleeding outranks it.",
     "Correct — bleeding with hematocrit drop is the emergency during thrombolysis.",
     "Mild headache without neuro change is monitored, not alarmed.",
     "Mild sinus tachycardia alone is not the priority."],
  s:"During thrombolysis, BLEEDING is the clock that runs fastest — report it first, always."},
 ref:"Thrombolytic therapy · hemorrhagic complications"},

{id:"RRP-024", t:"single", cn:"RRP", sys:"RESP", topic:"Chest tube assessment", d:2, b:0.3, cj:"evaluate", tags:["chest-tube","respiratory"],
 stem:"A client's chest tube attached to a water-seal drainage system suddenly stops bubbling in the water-seal chamber, and the client's breathing is unlabored. How does the nurse interpret this?",
 opts:["The lung may have re-expanded — notify the provider for evaluation",
  "The system has an air leak requiring immediate clamp-and-check",
  "The tubing is obstructed; strip the tube every 15 minutes",
  "Suction pressure has failed; increase it until bubbling returns"],
 ans:0,
 rat:{c:"Resolution of an air leak in a water-seal chamber, with a comfortable client, often means the pleural leak has sealed/lung re-expanded — the provider evaluates for possible removal. Vigorous stripping and empirical suction increases are not first responses.",
  o:["Correct — a resolved leak plus stable breathing typically means healing; confirm with the provider.",
     "Clamping is reserved for locating a leak when one is SUSPECTED — not when one has resolved.",
     "Routine stripping is avoided — it creates dangerous negative pressure.",
     "Bubbling in the seal chamber is not a goal in itself; suction is set, not chased."],
  s:"With chest tubes, read the system: gone bubbling + comfortable client = likely sealed leak → provider evaluation."},
 ref:"Chest tube systems · water-seal interpretation"},

{id:"RRP-025", t:"cloze", cn:"RRP", sys:"RESP", topic:"Arterial blood gases", d:3, b:0.85, cj:"analyze", tags:["abg","acid-base"],
 stem:"A client in severe respiratory distress has an arterial blood gas of pH 7.28 · PaCO₂ 62 mm Hg · HCO₃⁻ 26 mEq/L · PaO₂ 58 mm Hg on room air. Complete the interpretation.",
 cloze:{ lines:[
   {pre:"This client's primary acid-base problem is ", post:".", opts:["Respiratory acidosis","Metabolic acidosis","Respiratory alkalosis","Metabolic alkalosis"], ans:0},
   {pre:"The expected nursing priority is to ", post:".", opts:["Improve ventilation and oxygenation","Administer sodium bicarbonate","Slow the breathing rate","Increase oral sodium intake"], ans:0},
   {pre:"Compensation status is ", post:".", opts:["Uncompensated","Fully compensated","Partially compensated","Not applicable"], ans:0}]},
 rat:{c:"Low pH with high PaCO₂ and normal bicarbonate = uncompensated respiratory acidosis; the priority is ventilation and oxygenation, not buffers.",
  s:"ABG ladder: pH → PaCO₂ (respiratory) → HCO₃⁻ (metabolic) → match the mover → check compensation. Fix the cause, not the number."},
 ref:"ABG interpretation · respiratory failure"},

/* ── Basic Care & Comfort ──────────────────────────────────────── */
{id:"BCC-013", t:"single", cn:"BCC", sys:"GI", topic:"Nutrition / dysphagia", d:1, b:-0.2, cj:"act", tags:["nutrition","dysphagia","safety"],
 stem:"A client post-stroke is started on a thickened-liquid diet after a swallowing evaluation. Which nursing action best prevents aspiration during meals?",
 opts:["Position the client upright at 90° during and 30 minutes after eating",
  "Mix thin liquids into pureed foods to thin the overall texture",
  "Encourage large bites to reduce total meal length",
  "Serve all fluids piping hot to stimulate swallow reflexes"],
 ans:0,
 rat:{c:"Uright 90° during meals and for 30 minutes after is the single most protective positioning for dysphagia. Textures must stay as prescribed; small bites and unhurried pacing reduce aspiration risk.",
  o:["Correct — upright during + 30 minutes after is the evidence-based standard.",
     "Altering prescribed textures defeats the swallowing evaluation.",
     "Large bites increase choking/aspiration risk.",
     "Temperature extremes do not protect the airway."],
  s:"Dysphagia safety = upright positioning, prescribed textures, small bites, no distractions."},
 ref:"Dysphagia · aspiration prevention"},

{id:"BCC-014", t:"single", cn:"BCC", sys:"MSK", topic:"Mobility / assistive devices", d:1, b:-0.15, cj:"act", tags:["mobility","safety","crutches"],
 stem:"A client learning to walk with a cane holds it on the left side because the left knee is painful. What is the nurse's best correction?",
 opts:["The cane belongs on the RIGHT (strong) side, moving with the left (weak) leg",
  "The cane is correctly placed; keep it on the painful side",
  "Switch the cane between hands every few blocks to share the load",
  "Hold the cane on the left but step with both legs together"],
 ans:0,
 rat:{c:"A cane is held on the STRONG side and advances WITH the weak leg, widening the base and offloading the affected limb.",
  o:["Correct — cane on the strong side, paired with the weak leg's stride.",
     "Using the painful side narrows support and worsens gait.",
     "Alternating hands breaks the gait pattern and balance.",
     "Stepping with both legs together is not a safe gait."],
  s:"Cane rule: strong side holds it; cane + weak leg move together."},
 ref:"Assistive devices · cane gait"},

{id:"BCC-015", t:"single", cn:"BCC", sys:"NEURO", topic:"Sleep / comfort", d:1, b:-0.3, cj:"generate", tags:["sleep","nonpharmacologic"],
 stem:"An older adult on a medical unit reports sleeping poorly. Which nursing measure best promotes sleep without adding medication?",
 opts:["Cluster nighttime care activities and keep the environment quiet and dim",
  "Encourage a long afternoon nap to repay the sleep debt",
  "Offer caffeinated tea in the early evening to establish a rhythm",
  "Keep the room television on at low volume for background noise"],
 ans:0,
 rat:{c:"Sleep hygiene for hospitalized older adults: cluster care, minimize noise/light, protect nighttime hours. Daytime napping, evening caffeine, and background TV all fragment sleep.",
  o:["Correct — protecting uninterrupted nighttime hours is the core hospital sleep intervention.",
     "Long afternoon naps reduce sleep pressure at night.",
     "Caffeine in the evening delays sleep onset.",
     "Background TV noise is a known hospital sleep disruptor."],
  s:"In-hospital insomnia: fix the environment first — clustered care, quiet, dim, no caffeine naps."},
 ref:"Sleep promotion · hospital sleep hygiene"},

{id:"BCC-016", t:"single", cn:"BCC", sys:"REN", topic:"Elimination", d:1, b:-0.1, cj:"act", tags:["elimination","bladder"],
 stem:"A client reports not voiding for 10 hours postoperatively and feels lower abdominal fullness. Bladder scan shows 520 mL. What is the nurse's first action?",
 opts:["Perform catheterization per standing post-retention protocol",
  "Encourage oral fluids to stimulate voiding",
  "Apply warm pressure over the symphysis pubis",
  "Recheck the bladder scan in 2 hours"],
 ans:0,
 rat:{c:"A palpable/bladder-scanned 520 mL with time since voiding indicates acute retention; the first-line relief is catheterization (often per standing protocol after consulting criteria). Fluids add volume; waiting risks distension injury.",
  o:["Correct — relieve the retained volume; protocols typically direct catheterization at this level.",
     "More intake into a full bladder worsens discomfort and risk.",
     "Warm pressure may help milder cases but is too slow at 520 mL.",
     "Delaying 2 hours risks bladder over-distension injury."],
  s:"Post-op retention over ~500 mL: empty the bladder — don't wait, don't add fluids."},
 ref:"Postoperative urinary retention"},

/* ── Safety & Infection Prevention ─────────────────────────────── */
{id:"SIC-014", t:"single", cn:"SIC", sys:"INF", topic:"Isolation precautions", d:1, b:-0.25, cj:"act", tags:["isolation","infection-control"], variantGroup:"isolation-airborne",
 stem:"A school-age client is admitted with fever, cough, and a maculopapular rash that started on the face. Measles is suspected. Which precautions does the nurse implement immediately?",
 opts:["Airborne precautions with an N95 respirator for entering staff",
  "Droplet precautions with a surgical mask within 3 feet",
  "Contact precautions with gown and gloves for all contact",
  "Standard precautions only until the rash is confirmed measles"],
 ans:0,
 rat:{c:"Suspected measles = airborne precautions plus N95, and a negative-pressure room when available — suspected means treated as confirmed for isolation purposes.",
  o:["Correct — measles is airborne; N95 is required, not a surgical mask.",
     "Droplet precautions suit pertussis/meningitis, not measles.",
     "Contact precautions alone miss the airborne route.",
     "Never wait for confirmation to start protective isolation."],
  s:"Rash + fever + cough: think measles → AIRBORNE + N95 immediately on suspicion (variant presentation)."},
 ref:"Transmission-based precautions · measles (variant)"},

{id:"SIC-015", t:"single", cn:"SIC", sys:"MSK", topic:"Surgical safety", d:1, b:-0.2, cj:"act", tags:["surgical-safety","time-out"],
 stem:"In the operating room, the circulating nurse initiates the surgical time-out immediately before incision. Which verification is part of the time-out?",
 opts:["Confirming the correct client, procedure, site, and side with the whole team",
  "Verifying the client's insurance authorization for the surgery",
  "Reviewing the surgeon's preferred postoperative diet orders",
  "Confirming the family is seated in the waiting lounge"],
 ans:0,
 rat:{c:"The time-out is a team pause confirming client, procedure, site, and laterality — wrong-site surgery prevention — immediately before incision.",
  o:["Correct — the universal protocol's core verifications.",
     "Authorization is administrative, done well before the OR.",
     "Diet orders belong to post-op planning, not the time-out.",
     "Family logistics are not a safety-check element."],
  s:"Time-out = right patient, right procedure, right site/side — voiced by the whole team before incision."},
 ref:"Universal protocol · surgical time-out"},

{id:"SIC-016", t:"single", cn:"SIC", sys:"PSYCH", topic:"Restraint safety", d:2, b:0.25, cj:"evaluate", tags:["restraints","safety"],
 stem:"A client in soft wrist restraints becomes more agitated. Which assessment is the priority for the nurse right now?",
 opts:["Circulation, sensation, and skin integrity distal to the restraints",
  "Whether the restraints are the least-restrictive available type",
  "The time elapsed since the last restraint documentation entry",
  "Whether the family has been updated about the restraints"],
 ans:0,
 rat:{c:"Escalating agitation increases struggling — the immediate risk is circulatory and skin injury beneath the restraints; assess distal CSM and skin now, then address behavior and documentation.",
  o:["Correct — compromised circulation is the immediate physical harm.",
     "Least-restrictive review matters but follows the physical check.",
     "Documentation timing is required (typically every 2 hours / per policy) but is not the immediate safety priority.",
     "Family updates are courtesy, not the priority assessment."],
  s:"Restraint safety order: circulation/skin FIRST, behavior plan second, paperwork third."},
 ref:"Restraints · monitoring standards"},

/* ── Psychosocial Integrity ────────────────────────────────────── */
{id:"PSY-014", t:"single", cn:"PSY", sys:"PSYCH", topic:"Crisis / de-escalation", d:1, b:-0.15, cj:"act", tags:["crisis","communication","de-escalation"],
 stem:"A distressed client is pacing the hallway, shouting that everyone is lying. Which nurse response is most likely to de-escalate the situation?",
 opts:["“I can see you're really upset. Let's sit down here and you can tell me what happened.”",
  "“You need to lower your voice and stop this behavior right now.”",
  "“Why are you acting like this when we've done everything for you?”",
  "“I'm going to have to call security if you don't calm down.”"],
 ans:0,
 rat:{c:"De-escalation starts with validation, calm tone, and offering a private space to be heard. Commands, blaming “why” questions, and security threats escalate.",
  o:["Correct — validate, stay calm, offer presence and choice.",
     "Commands challenge autonomy and raise the emotional temperature.",
     "“Why are you acting like this?” blames and implies bad intent.",
     "Threatening security is a last resort once safety fails, not an opener."],
  s:"De-escalation: validate the feeling, keep your voice low, offer choices — never lead with commands or threats."},
 ref:"Crisis intervention · verbal de-escalation"},

{id:"PSY-015", t:"single", cn:"PSY", sys:"PSYCH", topic:"Suicide risk assessment", d:2, b:0.4, cj:"analyze", tags:["suicide-risk","safety"],
 stem:"During a admission assessment, a client says, “Some days I think everyone would be better off without me.” What is the nurse's priority response?",
 opts:["Ask directly whether the client has thoughts of killing themselves now",
  "Redirect the conversation to safer coping topics",
  "Notify security to search the client's belongings",
  "Document the statement and continue the intake questions"],
 ans:0,
 rat:{c:"Any suicide hint warrants a direct, compassionate screening question — asking does not plant the idea and is the standard of care. Deflection, searches, and documentation-only responses miss the assessment window.",
  o:["Correct — direct screening (“Are you having thoughts of killing yourself?”) is the priority.",
     "Changing topics invalidates the disclosure and drops the safety net.",
     "Belonging searches follow assessment and provider orders, not replace asking.",
     "Documenting without exploring leaves the risk unassessed."],
  s:"Hear a hint → ask directly, calmly, now. Assessment always precedes interventions like searches."},
 ref:"Suicide screening · direct inquiry"},

/* ── Health Promotion & Maintenance ────────────────────────────── */
{id:"HPM-013", t:"single", cn:"HPM", sys:"GI", topic:"Health screening", d:1, b:-0.2, cj:"recognize", tags:["screening","prevention"],
 stem:"A 50-year-old client with average colorectal cancer risk asks which screening to schedule. Which option reflects current guidance?",
 opts:["A colonoscopy every 10 years starting at age 45–50",
  "Annual colonoscopy beginning now",
  "Fecal occult blood testing every 5 years only, no colonoscopy",
  "No screening until age 65 unless symptoms appear"],
 ans:0,
 rat:{c:"Average-risk colorectal screening begins at 45–50 with colonoscopy every 10 years (or stool-based alternatives at set intervals). Annual colonoscopy and starting at 65 are outside guidance; FIT alternatives run annually, not every 5.",
  o:["Correct — 10-year colonoscopy from 45–50 for average risk.",
     "Annual colonoscopy exceeds any recommended interval for average risk.",
     "FOBT/FIT is annual when used — not every 5 years alone.",
     "Waiting until 65 forfeits the protective window."],
  s:"Colorectal screening: start 45–50, colonoscopy q10y for average risk — know the alternatives' intervals."},
 ref:"Colorectal cancer screening guidelines"},

{id:"HPM-014", t:"single", cn:"HPM", sys:"RESP", topic:"Health education", d:1, b:-0.25, cj:"generate", tags:["smoking-cessation","teaching"],
 stem:"A client who smokes a pack daily says, “I want to quit but I've failed twice.” Which response uses motivational interviewing most effectively?",
 opts:["“You've tried before — what worked, even a little, in those attempts?”",
  "“Most people succeed with nicotine patches; shall I just order some?”",
  "“Smoking is the worst thing you can do to your lungs, as you know.”",
  "“You'll quit when you're truly ready to commit this time.”"],
 ans:0,
 rat:{c:"MI explores the client's own experience and strengths — evoking past successes builds change talk. Prescribing without exploration, shame, and “come back when ready” all disengage.",
  o:["Correct — draws out what worked, reinforcing self-efficacy.",
     "Jumping to a prescription skips the client's motivation and preferences.",
     "Shaming damages the therapeutic relationship.",
     "Deflecting responsibility offers no help now."],
  s:"Motivational interviewing: ask about THEIR reasons and past wins — don't prescribe, preach, or postpone."},
 ref:"Motivational interviewing · cessation counseling"},

/* ── Physiological Adaptation ──────────────────────────────────── */
{id:"PAA-039", t:"single", cn:"PAA", sys:"CV", topic:"Heart failure", d:2, b:0.3, cj:"evaluate", tags:["heart-failure","fluid-balance"],
 stem:"A client with heart failure has gained 2.3 kg (5 lb) in 2 days, new ankle edema, and worsening dyspnea on exertion. Which assessment finding most confirms the suspected cause?",
 opts:["Crackles in the lung bases with an S₃ heart sound",
  "A friction rub over the heart with pleuritic pain",
  "Bronchial breath sounds over the upper lobes",
  "A pleural friction rub audible only on expiration"],
 ans:0,
 rat:{c:"Rapid weight gain + edema + dyspnea = fluid overload in failing pump; basilar crackles and S₃ are the classic confirmatory findings.",
  o:["Correct — crackles + S₃ are volume-overload signatures.",
     "A friction rub suggests pericarditis — a different process.",
     "Bronchial sounds over upper lobes suggest consolidation, not overload.",
     "Pleural rubs indicate pleural inflammation, not heart failure."],
  s:"Heart failure decompensation triangle: weight up, lungs wet (crackles), gallop (S₃) — confirm with what you hear."},
 ref:"Heart failure · fluid overload assessment"}
);
