/* ============================================================================
   bank19.js — hand-authored wave 9: 18 hard items, NCLEX-RN only

   WHY THIS FILE EXISTS
     After wave 8 the remaining gaps were Management of Care at 16.6% of the
     bank against an 18% blueprint weight — the single largest category on the
     real exam and still under-served — and difficulty in Safety & Infection
     Control (48% hard) and Basic Care & Comfort (46% hard). This wave adds
     6 MOC, 4 SIC, 4 HPM and 4 BCC items, every one d>=2.

   WHAT MAKES THESE HARD (and NCLEX-realistic)
     · scope questions where the tempting answer names a correct action by the
       wrong actor, or takes it in the wrong order
     · device and apparatus items where the sign belongs to one chamber or one
       mechanism and the distractors move it to another
     · confidentiality items where the rule has a genuine legal exception, and
       the distractors are the unqualified version of the rule
     · skin and wound findings that must be differentiated by location and
       shape rather than by severity

   AUTHORING RULES OBSERVED
     · no stem token that occurs only in the key option
     · key is not systematically the longest option
     · every rationale explains the key and each distractor, plus a takeaway
   ========================================================================== */
window.NC.BANK.push(
/* ── Management of Care (blueprint 18%) ────────────────────────────── */
{id:"MOC-084", t:"single", cn:"MOC", sys:"MSK", topic:"Delegation and verified competency", d:3, b:0.6, cj:"analyze", tags:["delegation","competency","scope"],
 stem:"A nurse needs to delegate ambulation of a client who is 1 day post hip arthroplasty. The unlicensed assistive personnel assigned has not previously ambulated a postoperative orthopedic client. Which decision should the nurse make?",
 opts:["Retain the task, because delegation requires verified competency for this client",
  "Delegate the task and stay in the hallway so assistance is immediately available",
  "Delegate the task once the assistive personnel has reviewed the client's care plan",
  "Delegate the task, because ambulating a stable client falls within unlicensed scope"],
 ans:0,
 rat:{c:"Delegation requires the right person, and the right person means the delegatee has demonstrated competency for that task with that client. Scope of practice is a floor rather than a ceiling — a task can sit inside a role's scope and still not be safely delegable to this person for this client. Reviewing a care plan builds knowledge but is not supervised experience, and being nearby does not compensate for an unprepared delegatee at the moment of transfer.",
  o:["Correct — competency for this client is a condition of delegation, not an optional extra.",
   "Hallway availability does not make an unprepared delegatee safe during the transfer itself.",
   "Reading a care plan is not a substitute for demonstrated, supervised experience.",
   "Scope says a task may be delegated; it does not say it may be delegated to anyone holding that role."],
  s:"Scope says a task may be delegated. Competency says it may be delegated to this person. Both must hold before the nurse lets go."},
 ref:"Management of care · competency as a condition of delegation"},

{id:"MOC-085", t:"single", cn:"MOC", sys:"INF", topic:"Employer request for client health information", d:3, b:0.6, cj:"act", tags:["confidentiality","hipaa","authorization"],
 stem:"A client's employer calls the unit and asks the nurse to confirm the diagnosis behind the client's medical leave. The client has not signed a release. Which response by the nurse is appropriate?",
 opts:["Decline to confirm or deny any information without the client's authorization",
  "Confirm the diagnosis but withhold the prognosis until a release is signed",
  "Release the information, because an employer has a legitimate need to plan",
  "Ask the client's provider to make the decision about what may be disclosed"],
 ans:0,
 rat:{c:"Protected health information cannot go to an employer without the client's specific written authorization, and confirming a diagnosis is a disclosure even when nothing further is said. An employer's operational need does not create an exception. Partial disclosure does not cure the missing authorization, and the duty sits with the nurse who holds the information rather than transferring to the provider.",
  o:["Correct — without written authorization the answer is neither confirm nor deny.",
   "Withholding the prognosis still discloses protected information without authorization.",
   "An employer's planning need is not a permitted purpose for disclosure.",
   "The obligation belongs to the nurse holding the information; it cannot be passed on."],
  s:"An employer is not a permitted recipient. Absent the client's written authorization, neither confirming nor denying is safe."},
 ref:"Management of care · confidentiality and employer requests"},

{id:"MOC-086", t:"single", cn:"MOC", sys:"INF", topic:"Mandatory reporting of a gunshot wound", d:2, b:0.45, cj:"act", tags:["mandatory-reporting","law","confidentiality"],
 stem:"A client arrives with a gunshot wound to the thigh and asks the nurse not to involve the police. Which action should the nurse take?",
 opts:["Report the wound to law enforcement, because it is a mandated report",
  "Honor the request, because the client is competent and has declined",
  "Report the wound if the client cannot explain how the injury occurred",
  "Ask the provider whether the wound must be reported to the authorities"],
 ans:0,
 rat:{c:"Gunshot and stab wounds are reportable to law enforcement by statute in most jurisdictions, and that duty does not depend on the client's wishes. The right to refuse treatment is real but does not cancel a mandated report. The nurse reports without waiting for the provider's permission and without conditioning the report on whether the client can explain the injury; documenting the client's objection is appropriate, while withholding the report is not.",
  o:["Correct — a mandated report is made regardless of the client's preference.",
   "Competence protects treatment decisions; it does not override a statutory reporting duty.",
   "The reporting trigger is the wound itself, not the client's account of it.",
   "The nurse's duty is direct; waiting for permission delays a required report."],
  s:"Some reports are mandated by law and do not turn on consent. Gunshot and stab wounds are the classic examples — report, then document."},
 ref:"Management of care · mandatory reporting duties"},

{id:"MOC-087", t:"single", cn:"MOC", sys:"INTG", topic:"Allocation of a scarce intensive care bed", d:3, b:0.7, cj:"analyze", tags:["ethics","justice","resource-allocation"],
 stem:"Two clients deteriorate at the same time and one intensive care bed is available. One is a 34-year-old with reversible septic shock; the other is an 88-year-old with end-stage heart failure who has been awaiting the bed for two days. Which principle should guide the allocation decision?",
 opts:["The bed goes to the client most likely to benefit, decided by a fair process",
  "The bed goes to the client who has waited longest, since that position was earned",
  "The bed goes to the younger client, because age predicts who benefits from care",
  "The bed stays empty until a second opens, because choosing is not the nurse's role"],
 ans:0,
 rat:{c:"Distributive justice allocates a scarce resource by expected benefit rather than by queue position, age alone, or avoidance of the decision. Fairness comes from applying the same transparent criteria to every candidate rather than from any particular outcome. Waiting time matters as a tiebreaker inside a process, not as the deciding principle; age is a poor proxy for benefit; and deferring the choice abandons both clients.",
  o:["Correct — expected benefit, applied through consistent criteria, is the governing principle.",
   "Queue position can break a tie but does not decide who benefits most.",
   "Age alone is not a measure of benefit and would exclude clients who would recover.",
   "Declining to choose is itself a choice, and it is the one that helps neither client."],
  s:"Scarce-resource allocation is judged by benefit and by fairness of process. Neither 'who waited' nor 'who is younger' is the principle."},
 ref:"Management of care · distributive justice"},

{id:"MOC-088", t:"single", cn:"MOC", sys:"INF", topic:"Falsified medication documentation", d:3, b:0.6, cj:"prioritize", tags:["documentation","incident-reporting","safety"],
 stem:"A nurse discovers that a colleague documented an antibiotic as administered, but the dose is still in the client's medication drawer. Which action should the nurse take first?",
 opts:["Notify the nurse manager and file an incident report; do not alter the colleague's entry",
  "Administer the dose and rewrite the colleague's entry to reflect the actual time",
  "Speak with the colleague privately and let the colleague correct the entry",
  "Document the discrepancy in the client's record and take no further action"],
 ans:0,
 rat:{c:"A medication documented but not given is both a patient safety event and a record integrity problem. The dose must be addressed with the provider, the event reported through the incident system, and the manager notified — but another nurse's entry is never altered, because a correction by a different person destroys the audit trail. Leaving it to the colleague privately neither secures the dose nor records the event, and charting a discrepancy without escalating reports nothing.",
  o:["Correct — escalate and report, while leaving the original entry intact for the audit trail.",
   "Rewriting another nurse's entry falsifies the record further and hides the event.",
   "A private conversation neither gives the missed dose nor creates a reportable record.",
   "Documenting alone escalates nothing and leaves the safety event unaddressed."],
  s:"Report the event; never edit another nurse's entry. Corrections are made by their author as an addendum, not by someone else."},
 ref:"Management of care · record integrity and incident reporting"},

{id:"MOC-089", t:"single", cn:"MOC", sys:"INTG", topic:"Missing advance directive on transfer", d:3, b:0.6, cj:"prioritize", tags:["advance-directive","continuity","verification"],
 stem:"A client is transferred from a rehabilitation facility and states that a do-not-resuscitate order exists, but no directive appears in the transfer record. The client is alert and oriented. Which action should the nurse take first?",
 opts:["Ask the client about the directive and notify the provider to have it verified and entered",
  "Assume the directive applies, because the client states that it exists",
  "Assume no directive exists and plan for full resuscitation until paperwork arrives",
  "Contact the rehabilitation facility's medical records department before speaking with the client"],
 ans:0,
 rat:{c:"A directive is actionable once it is verified and in the record, and an alert, oriented client is the fastest source — able to describe the document and say where it is held. The provider must be notified so it can be obtained, verified, and entered and so a current order can be written. Assuming either way substitutes a guess for verification, and calling medical records before speaking to the client bypasses the quickest route.",
  o:["Correct — ask the client and notify the provider so the directive can be verified and entered.",
   "A client's report is a lead to verify, not a document the nurse can act on alone.",
   "Assuming no directive risks performing resuscitation the client has already refused.",
   "Records can follow; the client is present and is the fastest source of information."],
  s:"When the paperwork is missing, ask the client and notify the provider. Neither assumption is safe — verification is the action."},
 ref:"Management of care · continuity of advance directives"},

/* ── Safety & Infection Control ────────────────────────────────────── */
{id:"SIC-065", t:"single", cn:"SIC", sys:"HEME", topic:"Bedside blood product verification", d:2, b:0.45, cj:"act", tags:["transfusion","verification","patient-identification"],
 stem:"A nurse is about to start a transfusion of packed red blood cells. Which step must occur before the product is connected?",
 opts:["A second licensed nurse checks the product against the client's band at the bedside",
  "The nurse verifies the product against the requisition at the blood bank",
  "The nurse confirms identity by asking the client to state a full name",
  "The charge nurse verifies the product in the medication room before transport"],
 ans:0,
 rat:{c:"Blood administration requires two licensed personnel to independently check the product against the client's identification band at the bedside, matching client identifiers, blood type, unit number, and expiration. Verification against a requisition at the blood bank is part of issuing but is not the bedside check, and asking the client to state a name is one identifier where two are required. A check performed away from the client cannot confirm that the right product reaches the right person.",
  o:["Correct — two licensed nurses, at the bedside, against the identification band.",
   "Blood bank verification issues the product; it does not confirm it at the client's side.",
   "A stated name is a single identifier; two identifiers are required before transfusion.",
   "Verification away from the client cannot connect the product to the person receiving it."],
  s:"Two licensed nurses, at the bedside, against the band. That specific check is what prevents a fatal ABO mismatch."},
 ref:"Safety · bedside transfusion verification"},

{id:"SIC-066", t:"single", cn:"SIC", sys:"RESP", topic:"Vest restraint and positional asphyxia", d:3, b:0.55, cj:"prioritize", tags:["restraints","asphyxia","monitoring"],
 stem:"A client is placed in a vest restraint. Which finding during the required monitoring interval requires immediate removal of the restraint?",
 opts:["Cyanosis of the lips and a respiratory rate of 8 breaths per minute",
  "Continued attempts to reach the intravenous line while restrained",
  "Verbal objection to the restraint and a request to have it removed",
  "Elevated blood pressure together with a request for a bedpan"],
 ans:0,
 rat:{c:"A vest restraint can restrict chest excursion and, if it rides up or is applied too tightly, causes positional asphyxia; cyanosis with a respiratory rate of 8 is respiratory compromise, and the restraint comes off at once with airway and breathing support. Ongoing attempts to reach the line mean the restraint is not achieving its purpose and the plan needs review, but that is not an emergency. Verbal objection is expected and documented, and hypertension with a bedpan request is a care need rather than a restraint complication.",
  o:["Correct — any sign of respiratory compromise means remove the restraint immediately.",
   "Ineffective restraint calls for a plan review, not emergency removal.",
   "Objection is anticipated, documented, and addressed through alternatives.",
   "Blood pressure change and elimination needs are care items, not restraint emergencies."],
  s:"Vest restraints can cause positional asphyxia. Respiratory compromise outranks the reason the restraint was applied — remove it first."},
 ref:"Safety · restraint complications and monitoring"},

{id:"SIC-067", t:"single", cn:"SIC", sys:"INTG", topic:"Fire at the surgical site", d:3, b:0.6, cj:"prioritize", tags:["fire","surgical-safety","emergency"],
 stem:"During a surgical procedure the drapes ignite at the site where an alcohol-based skin preparation was applied moments earlier. Which action should the surgical team take first?",
 opts:["Remove the burning drapes from the client and extinguish the flames",
  "Activate the fire alarm and evacuate the operating room",
  "Turn off the oxygen supply at the flowmeter before touching the drapes",
  "Pour sterile saline across the surgical field to extinguish the fire"],
 ans:0,
 rat:{c:"When the fire is on or next to the client, the first action is to remove the burning material and put out the flames, because seconds of contact cause the injury. Evacuation follows RACE for a room fire but would leave the client burning while the team leaves. Oxygen feeds a fire and is stopped, though not before the burning material is off the client. Pouring saline onto an alcohol-based field can spread burning liquid across the skin.",
  o:["Correct — burning material off the client first, because contact time is what injures.",
   "Evacuation is correct for a room fire, but it abandons a client who is on fire.",
   "Oxygen should be stopped, but not before the burning drapes are removed.",
   "Saline can spread burning alcohol across the surgical field and worsen the burn."],
  s:"Fire on the client: get the burning material off first. Alarm, evacuation, and gas changes follow — they never come first."},
 ref:"Safety · surgical fire response"},

{id:"SIC-068", t:"single", cn:"SIC", sys:"INF", topic:"Central line hub disinfection", d:3, b:0.55, cj:"act", tags:["clabsi","central-line","infection-prevention"],
 stem:"A nurse is caring for a client with a central venous catheter. Which practice reduces the risk of a central line-associated bloodstream infection?",
 opts:["Scrub the catheter hub with antiseptic using full friction time before each access",
  "Change the transparent dressing whenever the client reports itching at the site",
  "Replace the catheter administration set every 24 hours on a routine schedule",
  "Apply topical antibiotic ointment to the insertion site at each dressing change"],
 ans:0,
 rat:{c:"The catheter hub is the commonest route for organisms to reach the bloodstream, and mechanical friction with an antiseptic for the full recommended dwell time before every access has the strongest evidence behind it. Dressings are changed on schedule and when soiled, loose, or damp rather than on reported itching. Administration sets are changed no more often than every 96 hours unless the infusion requires it, and ointment at the insertion site promotes fungal colonization and resistance.",
  o:["Correct — hub disinfection with real friction before every access is the highest-yield step.",
   "Dressing changes follow schedule and condition; itching is not a change trigger.",
   "Changing sets more often than recommended breaches the closed system and raises risk.",
   "Topical ointment at the site encourages fungal growth and antimicrobial resistance."],
  s:"Scrub the hub with real friction before every access. More frequent set changes and topical ointment add risk rather than protection."},
 ref:"Safety · CLABSI prevention bundle"},

/* ── Health Promotion & Maintenance ────────────────────────────────── */
{id:"HPM-051", t:"single", cn:"HPM", sys:"REPI", topic:"Live vaccines in pregnancy", d:2, b:0.45, cj:"analyze", tags:["immunization","pregnancy","live-vaccine"],
 stem:"A client who is 10 weeks pregnant asks which immunizations she can receive during this pregnancy. Which vaccine should the nurse identify as contraindicated?",
 opts:["Measles, mumps, and rubella vaccine, because it contains live attenuated virus",
  "Influenza vaccine, because it is given by intramuscular injection",
  "Tetanus, diphtheria, and acellular pertussis vaccine, because it is given in the third trimester",
  "Hepatitis B vaccine, because the client's exposure risk is unknown"],
 ans:0,
 rat:{c:"Live attenuated vaccines — measles, mumps, rubella, varicella, and live influenza — are contraindicated in pregnancy because of theoretical fetal risk, so MMR is given postpartum if the client is not immune. Inactivated influenza vaccine is recommended in any trimester and protects both client and newborn. Tetanus, diphtheria, and acellular pertussis is recommended between 27 and 36 weeks precisely to transfer antibody, not avoided. Hepatitis B vaccine is not contraindicated in pregnancy and is given when indicated.",
  o:["Correct — live attenuated virus is the reason MMR is deferred until postpartum.",
   "Inactivated influenza vaccine is recommended in every trimester, not avoided.",
   "Tdap is recommended in the third trimester to pass antibody to the newborn.",
   "Hepatitis B vaccine may be given in pregnancy when there is an indication."],
  s:"Live vaccines are out in pregnancy; inactivated ones are in. MMR and varicella wait until postpartum, flu is any trimester, Tdap belongs in the third."},
 ref:"Health promotion · immunization in pregnancy"},

{id:"HPM-052", t:"single", cn:"HPM", sys:"REPI", topic:"Combined contraceptive contraindication", d:3, b:0.55, cj:"analyze", tags:["contraception","contraindication","smoking"],
 stem:"A nurse is counseling several clients about combined oral contraceptives. Which client has an absolute contraindication to this method?",
 opts:["A 38-year-old who smokes 15 cigarettes daily",
  "A 24-year-old with well-controlled hypothyroidism",
  "A 30-year-old with a history of gestational diabetes 4 years ago",
  "A 19-year-old with irregular menstrual cycles"],
 ans:0,
 rat:{c:"Combined estrogen-progestin contraception is absolutely contraindicated in women aged 35 or older who smoke, because estrogen, age, and smoking compound to make myocardial infarction and stroke unacceptably likely; a progestin-only or non-hormonal method is used instead. Well-controlled hypothyroidism, a remote history of gestational diabetes, and irregular cycles are not contraindications — irregular cycles are often a reason to prescribe it.",
  o:["Correct — age 35 or older plus smoking is an absolute bar to combined hormonal contraception.",
   "Controlled hypothyroidism does not contraindicate estrogen-containing methods.",
   "Remote gestational diabetes is not a contraindication to combined contraception.",
   "Irregular cycles are frequently an indication for, not a bar to, this method."],
  s:"Age 35 or older plus smoking is an absolute bar to combined hormonal contraception. Offer progestin-only or non-hormonal instead."},
 ref:"Health promotion · contraceptive contraindications"},

{id:"HPM-053", t:"single", cn:"HPM", sys:"REPI", topic:"Mastitis and continued breastfeeding", d:3, b:0.55, cj:"generate", tags:["postpartum","mastitis","breastfeeding"],
 stem:"A breastfeeding client 3 weeks postpartum has a wedge-shaped red, warm, tender area on one breast and a temperature of 38.9 °C. Which instruction should the nurse give?",
 opts:["Keep feeding or expressing from the affected breast and start the prescribed antibiotic",
  "Stop feeding from the affected breast until the antibiotic course is complete",
  "Wean from breastfeeding, because infection makes the milk unsafe for the infant",
  "Apply ice, delay feeding on that side, and return if the temperature persists"],
 ans:0,
 rat:{c:"Mastitis is treated with effective milk removal plus antibiotics; continued feeding or expression from the affected breast drains the obstructed area and shortens the illness, and the milk remains safe for the infant. Stopping or weaning causes stasis, which worsens the infection and risks abscess formation. Ice and delayed feeding do the opposite of what is needed — warmth and frequent drainage are the interventions.",
  o:["Correct — milk removal from that breast is part of the treatment, alongside antibiotics.",
   "Stopping feeding causes stasis, which worsens the infection and risks abscess.",
   "The milk stays safe for the infant; weaning is unnecessary and counterproductive.",
   "Ice and delayed feeding promote stasis; warmth and frequent drainage are indicated."],
  s:"Mastitis means feed more from that side, not less. Milk removal is part of the treatment and the milk stays safe for the infant."},
 ref:"Health promotion · mastitis management"},

{id:"HPM-054", t:"single", cn:"HPM", sys:"MSK", topic:"Scoliosis screening by forward bend", d:2, b:0.4, cj:"recognize", tags:["screening","scoliosis","adolescent"],
 stem:"A school nurse screens a 12-year-old for scoliosis using the forward bend test. Which finding should be referred for further evaluation?",
 opts:["Asymmetry of the rib height on one side during forward bending",
  "A forward bend that reproduces tightness in the hamstring muscles",
  "A body mass index at the 85th percentile for age",
  "A spine that appears straight when the client stands upright"],
 ans:0,
 rat:{c:"The forward bend test detects rotational asymmetry: a rib hump or a prominence on one side indicates vertebral rotation from a lateral curvature and warrants radiographic evaluation. Hamstring tightness is a common and separate finding. A body mass index at the 85th percentile indicates overweight, not a spinal curvature. A straight spine while standing does not exclude curvature, which is exactly why the forward bend is performed.",
  o:["Correct — rib height asymmetry on forward bending is the positive screen.",
   "Hamstring tightness is an unrelated musculoskeletal finding.",
   "Body mass percentile measures weight status, not spinal alignment.",
   "A straight-standing spine does not exclude curvature; that is what the test is for."],
  s:"Look for asymmetry, not for pain. A rib hump on forward bending is the positive screen; a straight-standing spine proves nothing."},
 ref:"Health promotion · adolescent scoliosis screening"},

/* ── Basic Care & Comfort ──────────────────────────────────────────── */
{id:"BCC-051", t:"single", cn:"BCC", sys:"RESP", topic:"Continuous bubbling in the water seal chamber", d:3, b:0.55, cj:"analyze", tags:["chest-tube","water-seal","air-leak"],
 stem:"A client has a chest tube connected to a water seal drainage system. The nurse observes continuous, vigorous bubbling in the water seal chamber. Which interpretation is correct?",
 opts:["There is an air leak somewhere in the system that needs to be located",
  "The system is working correctly, because bubbling shows the lung is re-expanding",
  "Suction pressure is set too high and should be reduced at the wall regulator",
  "Tidaling has stopped, which means the lung has fully re-expanded"],
 ans:0,
 rat:{c:"Continuous bubbling in the water seal chamber means air is entering the system — at the insertion site, a connection, or a crack in the tubing — and it must be found and corrected, because an uncorrected leak defeats the seal. Bubbling that matches respiration can reflect an active air leak from the pleural space, but continuous vigorous bubbling is not normal. Reducing suction does not address a leak, and the absence of tidaling, rather than the presence of bubbling, is the sign of full re-expansion.",
  o:["Correct — continuous bubbling means a leak that must be traced and corrected.",
   "Continuous bubbling is not a sign of correct function; it means the seal is breached.",
   "Lowering suction does not seal a leak and may reduce drainage.",
   "Full re-expansion is shown by absent tidaling, not by continuous bubbling."],
  s:"Water seal chamber: continuous bubbling means a leak, and tidaling means the system is patent. Know which sign belongs to which chamber."},
 ref:"Basic care · chest drainage system interpretation"},

{id:"BCC-052", t:"single", cn:"BCC", sys:"MSK", topic:"Traction weights resting on the floor", d:3, b:0.55, cj:"act", tags:["traction","hip-fracture","alignment"],
 stem:"A client is in Buck traction after a hip fracture. During morning care the nurse finds the traction weights resting on the floor. Which action should the nurse take?",
 opts:["Reposition the client up in bed so the weights hang freely from the frame",
  "Leave the weights on the floor, because traction is no longer needed before surgery",
  "Lift the weights by hand and support the leg until the provider is notified",
  "Increase the weight on the frame to compensate for the loss of pull"],
 ans:0,
 rat:{c:"Traction works only while the weights hang freely; weights resting on the floor remove the pull and let the fracture fragments settle, causing pain and possible neurovascular compromise. Moving the client up in bed restores counter-traction without interrupting the pull. Supporting the leg by hand substitutes the nurse for the apparatus and does not restore alignment, and adding weight changes the prescribed force and risks nerve injury.",
  o:["Correct — free-hanging weights and counter-traction are what make traction work.",
   "Traction is maintained until surgery; letting the weights rest removes the pull.",
   "Hand support replaces the apparatus without restoring alignment.",
   "Adding weight changes the prescribed force and risks nerve and skin injury."],
  s:"Traction requires free-hanging weights and counter-traction. If the weights touch the floor, restore the position — never add weight or hold the leg."},
 ref:"Basic care · maintaining skeletal traction"},

{id:"BCC-053", t:"single", cn:"BCC", sys:"GI", topic:"Oral care for an unconscious client", d:2, b:0.45, cj:"prioritize", tags:["oral-care","aspiration","unconscious"],
 stem:"A nurse provides oral care to an unconscious client. Which action is the priority?",
 opts:["Position the client on the side with the head turned toward the nurse",
  "Use a soft toothbrush and fluoride toothpaste to clean the client's mouth",
  "Swab the mouth with a lemon-glycerin solution to stimulate moisture",
  "Apply a water-soluble lubricant to the lips after the care is finished"],
 ans:0,
 rat:{c:"An unconscious client has no gag protection, so aspiration is the governing risk during oral care; lateral positioning with the head turned lets secretions drain out of the mouth rather than into the airway. Cleaning technique, moisturizing agents, and lip care all matter but are secondary to keeping the airway clear. Lemon-glycerin swabs are additionally discouraged because they dry the mucosa and can erode enamel.",
  o:["Correct — lateral positioning with the head turned protects an unprotected airway.",
   "Cleaning matters, but not before the airway is protected from secretions.",
   "Lemon-glycerin swabs dry the mucosa and can erode enamel; they are discouraged.",
   "Lip care is a finishing step, not the priority during the procedure."],
  s:"Unconscious means no gag reflex, so position first — lateral with the head turned. Airway protection outranks cleaning technique."},
 ref:"Basic care · oral hygiene in the unconscious client"},

{id:"BCC-054", t:"single", cn:"BCC", sys:"INTG", topic:"Incontinence-associated dermatitis vs pressure injury", d:3, b:0.55, cj:"analyze", tags:["skin-integrity","incontinence","differentiation"],
 stem:"A client who is frequently incontinent of stool has a diffuse, shallow, weeping red area across the sacrum and buttock crease, with irregular borders that follow the pattern of contact with stool. Which interpretation should guide care?",
 opts:["This is incontinence-associated dermatitis, treated with a moisture barrier and prompt cleansing",
  "This is a stage 2 pressure injury, treated by offloading and a hydrocolloid dressing",
  "This is a stage 1 pressure injury, treated with a scheduled turning timetable",
  "This is a fungal intertrigo, treated with a prescribed topical antifungal"],
 ans:0,
 rat:{c:"Incontinence-associated dermatitis is moisture damage from prolonged contact with stool and urine: it is diffuse, weeping, irregular, and follows the contact pattern rather than sitting over a bony prominence. Pressure injuries are localized over prominences and are staged, so mislabeling this one leads to offloading alone while the moisture continues. Stage 1 pressure injury is non-blanchable intact skin, which this is not, and a fungal infection typically shows satellite lesions and favors skin folds.",
  o:["Correct — diffuse, weeping, contact-pattern damage is moisture-related, not pressure-related.",
   "A stage 2 injury is localized partial-thickness loss over a prominence, not a diffuse weeping field.",
   "Stage 1 is non-blanchable intact skin; this area is weeping and shallow.",
   "Fungal intertrigo favors folds and shows satellite lesions, which are not described here."],
  s:"Ask where it sits and what shape it has. Moisture damage is diffuse and follows the contact pattern; a pressure injury is localized over a prominence."},
 ref:"Basic care · differentiating moisture and pressure skin damage"}
);
