"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 36) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 35: MOC (17.8% vs 18),
 * SIC (12.8% vs 13), PHA (15.7% vs 16) and PAA (13.7% vs 14).
 * Every item is difficulty 2 or 3, and the clinical detail is
 * written to be defensible.
 *
 * SIC 6: febrile seizure in a toddler, driving restrictions after
 * a first seizure, bathing and swimming safety for a client with
 * epilepsy, SUDEP risk counselling, postictal care and observation,
 * and absence seizure recognition.
 * MOC 6: witnessing consent, confidentiality breach and duty to
 * report, Mental Health Act sectioning and nearest relative,
 * advance decision to refuse treatment, do not attempt resuscitation
 * order, and capacity fluctuation.
 * PHA 4: benzodiazepine taper in long-term users, Wernicke-Korsakoff
 * syndrome and thiamine, pellagra and niacin deficiency, and folate
 * deficiency with megaloblastic anaemia.
 * PAA 4: acute kidney injury staging, contrast-induced nephropathy
 * prevention, rhabdomyolysis and myoglobinuria, and tumour lysis
 * syndrome.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- SIC 6 */
{id:"SIC-138", t:"single", cn:"SIC", sys:"NEURO", topic:"Febrile seizure in a toddler", d:2, b:0.45, cj:"act", tags:["safety","paediatric","febrile seizure","neurological"],
 stem:"A parent brings an 18-month-old child to the emergency department after the child had a generalised tonic-clonic seizure lasting three minutes. The child's temperature is 39.2°C. The child is now drowsy but rousable and moving all limbs normally. Which action by the nurse is the priority?",
 opts:["Reduce the fever with paracetamol and ibuprofen, since fever control is the priority and the seizure has stopped","Administer rectal diazepam as the priority, since another seizure is likely","Perform a lumbar puncture, since meningitis must be excluded","Start intravenous antibiotics, since sepsis is the most common cause"],
 ans:0, rat:{c:"A simple febrile seizure has stopped, and the priority is fever control with antipyretics. Rectal diazepam is used for prolonged or recurrent seizures, not after a seizure has stopped. Lumbar puncture and antibiotics are indicated if there are signs of meningitis or sepsis, which are not present here.", s:"Simple febrile seizures are common in toddlers and are benign; management focuses on fever control and parental reassurance."}},
{id:"SIC-139", t:"single", cn:"SIC", sys:"NEURO", topic:"Driving restrictions after a first seizure", d:3, b:0.55, cj:"act", tags:["safety","epilepsy","driving","counselling"],
 stem:"A 28-year-old client has a first unprovoked generalised tonic-clonic seizure. Investigations are normal and no antiepileptic drug is started. The client asks when they can return to driving. Which response by the nurse is most appropriate?",
 opts:["Explain that driving restrictions apply and the client must inform the licensing authority, since a seizure-free period is required before driving resumes","Advise the client they can drive immediately, since only one seizure has occurred and investigations are normal","Advise the client to wait one week, since this is the standard restriction after a first seizure","Advise the client that driving restrictions apply only if antiepileptic medication is started"],
 ans:0, rat:{c:"After a first unprovoked seizure, driving restrictions apply and the client must inform the licensing authority. A seizure-free period (typically six to twelve months) is required before driving can resume. The restriction applies regardless of whether medication is started.", s:"Driving restrictions after seizure are a legal requirement and a core safety counselling topic; the nurse must ensure the client understands their duty to inform the licensing authority."}},
{id:"SIC-140", t:"single", cn:"SIC", sys:"NEURO", topic:"Bathing and swimming safety for a client with epilepsy", d:2, b:0.45, cj:"act", tags:["safety","epilepsy","bathing","swimming","counselling"],
 stem:"A 10-year-old child with well-controlled epilepsy asks about swimming lessons. The child has been seizure-free for two years on medication. Which response by the nurse is most appropriate?",
 opts:["Swimming is permitted with close adult supervision, since the child has been seizure-free for two years","Swimming is prohibited for at least five years, since any seizure in water is potentially fatal even if the child has been seizure-free","Swimming is permitted only in a supervised pool, not in open water","Swimming is permitted only if the child wears a life jacket at all times"],
 ans:0, rat:{c:"A child with well-controlled epilepsy who has been seizure-free for two years may swim with close adult supervision. Complete prohibition is unnecessary and overly restrictive. Supervision is the key safety measure, whether in a pool or open water.", s:"Safety counselling for epilepsy includes bathing and swimming; the emphasis is on supervision rather than prohibition when seizures are well controlled."}},
{id:"SIC-141", t:"single", cn:"SIC", sys:"NEURO", topic:"SUDEP risk counselling", d:3, b:0.55, cj:"act", tags:["safety","epilepsy","SUDEP","counselling","mortality"],
 stem:"A 35-year-old client with poorly controlled generalised tonic-clonic seizures asks about the risk of sudden unexpected death in epilepsy (SUDEP). Which response by the nurse is most appropriate?",
 opts:["Explain that SUDEP is a real but small risk, and that good seizure control and medication adherence reduce it","Reassure the client that SUDEP is extremely rare and not a realistic concern","Explain that SUDEP only affects clients who do not take medication","Avoid the topic, since discussing mortality may cause unnecessary anxiety"],
 ans:0, rat:{c:"SUDEP is a real but small risk, particularly in clients with poorly controlled generalised tonic-clonic seizures. Good seizure control and medication adherence reduce the risk. Honest, proportionate counselling is appropriate; avoiding the topic or minimising the risk fails the client.", s:"SUDEP counselling is an important aspect of epilepsy care; the nurse must balance honesty with reassurance and emphasise modifiable risk factors."}},
{id:"SIC-142", t:"single", cn:"SIC", sys:"NEURO", topic:"Postictal care and observation", d:2, b:0.45, cj:"act", tags:["safety","epilepsy","postictal","observation"],
 stem:"A client has a generalised tonic-clonic seizure lasting four minutes. The seizure has stopped and the client is now in the postictal phase, drowsy and confused. Which action by the nurse is the priority?",
 opts:["Place the client in the recovery position and maintain airway patency, since aspiration risk is high","Sit the client up and encourage fluids, since rehydration is important","Perform a full neurological assessment, since this will identify any deficit","Administer oxygen, since hypoxia is likely during the postictal phase"],
 ans:0, rat:{c:"In the postictal phase the client is at risk of aspiration from secretions or vomit, so the recovery position and airway patency are the priority. Sitting the client up risks aspiration. A full neurological assessment can wait until the client is more alert. Oxygen is not routinely required unless the client is hypoxic.", s:"Postictal care focuses on airway protection and safety; the client is vulnerable to aspiration and injury during this phase."}},
{id:"SIC-143", t:"single", cn:"SIC", sys:"NEURO", topic:"Absence seizure recognition", d:2, b:0.45, cj:"recognize", tags:["safety","epilepsy","absence seizure","paediatric"],
 stem:"A teacher reports that a 7-year-old pupil frequently stares blankly for five to ten seconds several times a day, does not respond during these episodes, and then resumes activity as if nothing happened. The teacher suspects the child is daydreaming. Which interpretation by the school nurse is most accurate?",
 opts:["These episodes are consistent with absence seizures and require medical evaluation","These episodes are normal daydreaming and require no further action","These episodes suggest attention deficit hyperactivity disorder","These episodes suggest a behavioural problem requiring discipline"],
 ans:0, rat:{c:"Brief staring episodes with unresponsiveness followed by immediate return to activity are characteristic of absence seizures, which are common in children. They are frequently mistaken for daydreaming. Medical evaluation with EEG is required for diagnosis. ADHD and behavioural problems do not present with brief unresponsive episodes.", s:"Absence seizures are often misattributed to daydreaming or inattention; recognition and referral are essential for diagnosis and treatment."}},

/* ---------------------------------------------------------- MOC 6 */
{id:"MOC-186", t:"single", cn:"MOC", sys:"INTG", topic:"Witnessing consent", d:2, b:0.45, cj:"act", tags:["management","consent","witnessing","documentation"],
 stem:"A nurse is asked to witness a client signing a consent form for surgery. The client appears confused and asks the nurse what the surgery involves. Which action by the nurse is most appropriate?",
 opts:["Explain that witnessing a signature only confirms identity and voluntary signing, and refer the client's questions to the surgeon","Explain the surgery to the client, since the nurse has a duty to ensure informed consent","Refuse to witness the signing, since the client appears confused","Sign the form and document the client's confusion, since this protects the nurse"],
 ans:0, rat:{c:"Witnessing a consent form confirms that the signature is genuine and that the client signed voluntarily; it does not confirm that the client understands the procedure. The nurse should refer questions to the surgeon who is obtaining consent. Explaining the surgery exceeds the nurse's role, and refusing to witness or signing without addressing confusion both fail the client.", s:"Understanding the limits of the witnessing role is essential; the nurse confirms identity and voluntariness, not comprehension."}},
{id:"MOC-187", t:"single", cn:"MOC", sys:"INTG", topic:"Confidentiality breach and duty to report", d:3, b:0.55, cj:"act", tags:["management","confidentiality","breach","reporting","safeguarding"],
 stem:"A nurse discovers that a colleague has accessed the medical record of a client who is a public figure, despite not being involved in the client's care. Which action by the nurse is most appropriate?",
 opts:["Report the breach to the line manager or information governance lead, since unauthorised access is a serious breach","Confront the colleague directly, since this may resolve the issue without escalation","Ignore the breach, since the colleague may have had a legitimate reason","Report the breach to the client, since the client has a right to know"],
 ans:0, rat:{c:"Unauthorised access to medical records is a serious breach of confidentiality and must be reported to the line manager or information governance lead. Confronting the colleague directly may not be safe or appropriate. Ignoring the breach fails the client and the organisation. Reporting to the client is the organisation's responsibility, not the individual nurse's.", s:"Confidentiality breaches must be reported through the proper channels; the nurse has a professional duty to act."}},
{id:"MOC-188", t:"single", cn:"MOC", sys:"INTG", topic:"Mental Health Act sectioning and nearest relative", d:3, b:0.55, cj:"analyze", tags:["management","Mental Health Act","sectioning","nearest relative","rights"],
 stem:"A client is detained under section 3 of the Mental Health Act for treatment. The client's nearest relative objects to the detention and wishes to have the client discharged. Which response by the nurse is most appropriate?",
 opts:["Explain that the nearest relative can request discharge but the responsible clinician can block it if there is a risk of harm","Explain that the nearest relative has no role once the client is detained","Explain that the nearest relative can discharge the client immediately","Explain that only a tribunal can discharge the client"],
 ans:0, rat:{c:"The nearest relative has the right to request discharge of a client detained under section 3, but the responsible clinician can block the discharge if there is a risk of harm to the client or others. The nearest relative does have a role, cannot discharge immediately, and is not the only route to discharge.", s:"Understanding the rights of the nearest relative under the Mental Health Act is essential; the nurse must be able to explain these rights accurately."}},
{id:"MOC-189", t:"single", cn:"MOC", sys:"INTG", topic:"Advance decision to refuse treatment", d:3, b:0.55, cj:"analyze", tags:["management","advance decision","capacity","refusal","autonomy"],
 stem:"A 78-year-old client with advanced dementia has a valid and applicable advance decision refusing antibiotics for pneumonia. The client now has pneumonia and lacks capacity to make a current decision. The clinical team believes antibiotics are in the client's best interests. Which action by the nurse is most appropriate?",
 opts:["Ensure the advance decision is followed, since it is valid and applicable and has the same force as a contemporaneous refusal","Administer antibiotics, since best interests override any advance decision that is not valid and applicable","Seek a court order, since the situation is unclear","Ask the family to decide, since they know the client's wishes"],
 ans:0, rat:{c:"A valid and applicable advance decision to refuse treatment has the same legal force as a contemporaneous refusal by a client with capacity. It must be followed even if the clinical team believes treatment is in the client's best interests. Best interests cannot override a valid advance decision.", s:"Advance decisions are legally binding when valid and applicable; understanding this is essential for respecting client autonomy."}},
{id:"MOC-190", t:"single", cn:"MOC", sys:"INTG", topic:"Do not attempt resuscitation order", d:3, b:0.55, cj:"analyze", tags:["management","DNAR","resuscitation","end of life","decision-making"],
 stem:"A 90-year-old client with advanced heart failure and recurrent hospital admissions has a do not attempt resuscitation (DNAR) order in place. The client's daughter asks the nurse to explain why resuscitation would not be attempted. Which response by the nurse is most appropriate?",
 opts:["Explain that resuscitation is unlikely to be successful and may cause harm, and that the decision was made in the client's best interests","Explain that the client is too old for resuscitation","Explain that the decision was made by the medical team and cannot be changed","Explain that resuscitation is not offered to clients with heart failure"],
 ans:0, rat:{c:"A DNAR decision is made when resuscitation is unlikely to be successful or would not be in the client's best interests. The nurse should explain this honestly and sensitively, emphasising that the decision is about the likely outcome rather than age or diagnosis. The decision can be reviewed if circumstances change.", s:"DNAR discussions require sensitivity and honesty; the nurse must be able to explain the rationale without causing unnecessary distress."}},
{id:"MOC-191", t:"single", cn:"MOC", sys:"INTG", topic:"Capacity fluctuation and decision-specific assessment", d:3, b:0.55, cj:"analyze", tags:["management","capacity","assessment","decision-specific","fluctuation"],
 stem:"A 65-year-old client with early dementia is assessed as lacking capacity to consent to a complex surgical procedure. Two weeks later, the client's cognition appears improved and they ask about the procedure again. Which action by the nurse is most appropriate?",
 opts:["Reassess capacity for the specific decision, since capacity can fluctuate and must be assessed for each decision at the time it is made","Use the previous assessment, since the client was already assessed two weeks ago","Ask the family to decide, since the client's capacity is uncertain","Proceed with the procedure, since the clinical team believes it is necessary"],
 ans:0, rat:{c:"Capacity must be assessed for each specific decision at the time it is made, and it can fluctuate. A previous assessment does not determine current capacity. The client should be reassessed if their condition has changed. Family cannot decide if the client has capacity, and proceeding without consent is not appropriate.", s:"Capacity is decision-specific and time-specific; understanding this principle is essential for lawful and ethical practice."}},

/* ---------------------------------------------------------- PHA 4 */
{id:"PHA-172", t:"single", cn:"PHA", sys:"PSYCH", topic:"Benzodiazepine taper in long-term users", d:3, b:0.55, cj:"act", tags:["pharmacology","benzodiazepine","taper","withdrawal","dependence"],
 stem:"A 55-year-old client has been taking diazepam 10 mg daily for anxiety for three years. The client wishes to stop. Which action by the nurse is most appropriate?",
 opts:["Advise a gradual taper over several weeks or months, since abrupt cessation can cause withdrawal seizures","Advise stopping immediately, since long-term use is harmful","Advise switching to a short-acting benzodiazepine, since this is easier to stop","Advise reducing the dose by half each week, since this is a safe rate"],
 ans:0, rat:{c:"Long-term benzodiazepine use causes physiological dependence, and abrupt cessation can cause withdrawal seizures, delirium, and other serious effects. A gradual taper over weeks or months is required. Switching to a short-acting agent or reducing by half each week is too rapid and unsafe.", s:"Benzodiazepine withdrawal is potentially life-threatening; the nurse must understand the need for a slow, supervised taper."}},
{id:"PHA-173", t:"single", cn:"PHA", sys:"NEURO", topic:"Wernicke-Korsakoff syndrome and thiamine", d:3, b:0.55, cj:"act", tags:["pharmacology","thiamine","Wernicke","Korsakoff","alcohol"],
 stem:"A 48-year-old client with a history of chronic alcohol misuse is admitted with confusion, ataxia, and ophthalmoplegia. The clinical team suspects Wernicke encephalopathy. Which action by the nurse is the priority?",
 opts:["Administer intravenous thiamine before any glucose, since glucose can precipitate or worsen Wernicke encephalopathy","Administer intravenous glucose first, since hypoglycaemia is a risk","Administer oral thiamine, since this is sufficient for Wernicke encephalopathy","Withhold thiamine until the diagnosis is confirmed, since treatment is not urgent"],
 ans:0, rat:{c:"Wernicke encephalopathy is a medical emergency requiring immediate intravenous thiamine. Glucose must be given after thiamine, since glucose metabolism depletes thiamine and can precipitate or worsen the condition. Oral thiamine is not sufficient, and delaying treatment risks permanent damage or death.", s:"The thiamine-before-glucose rule is a critical safety point; the nurse must ensure thiamine is given first in suspected Wernicke encephalopathy."}},
{id:"PHA-174", t:"single", cn:"PHA", sys:"GI", topic:"Pellagra and niacin deficiency", d:2, b:0.45, cj:"recognize", tags:["pharmacology","niacin","pellagra","vitamin deficiency","dermatology"],
 stem:"A 60-year-old client with a history of chronic alcohol misuse presents with a symmetric rash on sun-exposed areas, diarrhoea, and confusion. Which interpretation by the nurse is most accurate?",
 opts:["These findings are consistent with pellagra caused by niacin deficiency","These findings are consistent with scurvy caused by vitamin C deficiency","These findings are consistent with beriberi caused by thiamine deficiency","These findings are consistent with rickets caused by vitamin D deficiency"],
 ans:0, rat:{c:"Pellagra is caused by niacin (vitamin B3) deficiency and presents with the classic triad of dermatitis (symmetric rash on sun-exposed areas), diarrhoea, and dementia (confusion). Scurvy presents with bleeding gums and petechiae, beriberi with neuropathy and heart failure, and rickets with bone deformities.", s:"Recognising the classic triad of pellagra is essential; it is common in chronic alcohol misuse and malnutrition."}},
{id:"PHA-175", t:"single", cn:"PHA", sys:"HEME", topic:"Folate deficiency and megaloblastic anaemia", d:2, b:0.45, cj:"analyze", tags:["pharmacology","folate","megaloblastic anaemia","vitamin deficiency","haematology"],
 stem:"A 32-year-old pregnant client presents with fatigue and pallor. Blood tests show a macrocytic anaemia with a mean corpuscular volume of 108 fL. The client's diet is poor and she does not take supplements. Which interpretation by the nurse is most accurate?",
 opts:["Folate deficiency is the most likely cause, since pregnancy increases folate requirements and the client's diet is poor","Vitamin B12 deficiency is the most likely cause, since this is more common in pregnancy","Iron deficiency is the most likely cause, since this is the most common anaemia in pregnancy","Anaemia of chronic disease is the most likely cause, since pregnancy is a chronic condition"],
 ans:0, rat:{c:"Folate deficiency is the most likely cause of macrocytic anaemia in pregnancy, especially with a poor diet and no supplements. Pregnancy increases folate requirements significantly. Vitamin B12 deficiency is less common in pregnancy. Iron deficiency causes microcytic anaemia, not macrocytic.", s:"Folate deficiency is common in pregnancy and causes megaloblastic anaemia; supplementation is routine antenatal care."}},

/* ---------------------------------------------------------- PAA 4 */
{id:"PAA-143", t:"single", cn:"PAA", sys:"REN", topic:"Acute kidney injury staging", d:3, b:0.55, cj:"analyze", tags:["adaptation","acute kidney injury","staging","renal","assessment"],
 stem:"A client's serum creatinine rises from 80 µmol/L on admission to 200 µmol/L over 48 hours. Urine output has fallen to 0.4 mL/kg/hour for eight hours. Which interpretation by the nurse is most accurate?",
 opts:["This meets criteria for stage 2 acute kidney injury, since creatinine has risen more than 2.5 times baseline and urine output is reduced","This meets criteria for stage 1 acute kidney injury, since the rise is less than three times baseline and urine output is not severely reduced","This does not meet criteria for acute kidney injury, since the creatinine is still within normal limits","This meets criteria for stage 3 acute kidney injury, since the client is oliguric"],
 ans:0, rat:{c:"Stage 2 acute kidney injury is defined as a creatinine rise of 2.0 to 2.9 times baseline, or urine output less than 0.5 mL/kg/hour for more than 12 hours. This client's creatinine has risen 2.5 times and urine output is reduced, meeting stage 2 criteria. Stage 1 is a 1.5 to 1.9 times rise, and stage 3 is a 3 times rise or more.", s:"AKI staging guides management and monitoring; the nurse must be able to recognise the criteria and escalate appropriately."}},
{id:"PAA-144", t:"single", cn:"PAA", sys:"REN", topic:"Contrast-induced nephropathy prevention", d:3, b:0.55, cj:"act", tags:["adaptation","contrast","nephropathy","prevention","renal"],
 stem:"A client with chronic kidney disease and an estimated glomerular filtration rate of 35 mL/min/1.73m² requires a contrast-enhanced computed tomography scan. Which action by the nurse is most appropriate to reduce the risk of contrast-induced nephropathy?",
 opts:["Ensure adequate intravenous hydration before and after the procedure, since this is the most effective preventive measure","Withhold all medications on the day of the procedure, since this reduces renal workload","Administer furosemide before the procedure, since this protects the kidneys","Administer N-acetylcysteine, since this is the standard preventive agent"],
 ans:0, rat:{c:"Adequate intravenous hydration before and after contrast administration is the most effective measure to prevent contrast-induced nephropathy. Withholding medications is not indicated unless specifically advised. Furosemide may worsen dehydration and increase risk. N-acetylcysteine is not routinely recommended and evidence is limited.", s:"Hydration is the cornerstone of contrast-induced nephropathy prevention; the nurse must ensure it is given appropriately."}},
{id:"PAA-145", t:"single", cn:"PAA", sys:"REN", topic:"Rhabdomyolysis and myoglobinuria", d:3, b:0.55, cj:"analyze", tags:["adaptation","rhabdomyolysis","myoglobinuria","renal","emergency"],
 stem:"A client is admitted after being trapped under a collapsed structure for six hours. The client's urine is dark brown and the creatine kinase level is 25,000 U/L. Which interpretation by the nurse is most accurate?",
 opts:["These findings are consistent with rhabdomyolysis, and aggressive fluid resuscitation is required to prevent acute kidney injury","These findings are consistent with haematuria from bladder trauma and require catheterisation","These findings are consistent with dehydration and require oral rehydration","These findings are consistent with liver injury and require liver function tests"],
 ans:0, rat:{c:"Dark brown urine with a markedly elevated creatine kinase after crush injury is characteristic of rhabdomyolysis with myoglobinuria. Aggressive intravenous fluid resuscitation is required to prevent acute kidney injury from myoglobin precipitation in the renal tubules. Haematuria, dehydration, and liver injury do not explain the creatine kinase elevation.", s:"Rhabdomyolysis is a medical emergency; early recognition and aggressive hydration are essential to prevent renal failure."}},
{id:"PAA-146", t:"single", cn:"PAA", sys:"HEME", topic:"Tumour lysis syndrome", d:3, b:0.55, cj:"act", tags:["adaptation","tumour lysis","oncology","emergency","electrolytes"],
 stem:"A client with Burkitt lymphoma starts chemotherapy. Twelve hours later the client develops muscle cramps, tetany, and a prolonged QT interval on electrocardiogram. Blood tests show hyperkalaemia, hyperphosphataemia, hypocalcaemia, and hyperuricaemia. Which action by the nurse is the priority?",
 opts:["Recognise tumour lysis syndrome and ensure aggressive hydration and electrolyte management, since this is an oncological emergency","Administer calcium gluconate, since hypocalcaemia is causing the tetany","Administer insulin and dextrose, since hyperkalaemia is the most dangerous abnormality","Stop chemotherapy, since this is causing the syndrome"],
 ans:0, rat:{c:"Tumour lysis syndrome is an oncological emergency requiring aggressive hydration and electrolyte management. The characteristic findings are hyperkalaemia, hyperphosphataemia, hypocalcaemia, and hyperuricaemia. While calcium gluconate and insulin-dextrose may be needed, the priority is recognising the syndrome and initiating comprehensive management.", s:"Tumour lysis syndrome is a medical emergency; early recognition and aggressive management prevent fatal complications."}}

]);
