/* RN Ready — item bank v3h · part 8 (bank growth toward the 2026 blueprints).
   Census at 218 showed INTG 4 · REN 11 · HEME 13 as the thinnest systems, so this
   batch is weighted there (INTG +10 · REN +9 · HEME +7 · other +4) while keeping
   client-need balance (MOC +4 · SIC +4 · HPM +3 · PSY +3 · BCC +3 · PHA +4 ·
   RRP +4 · PAA +5) and format diversity (multi ×2, matrix ×2, cloze ×2, drag, hotspot).
   Two new variant groups: sickle-triggers (adult + pediatric) and ckd-diet.  */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Management of Care ────────────────────────────────────────────── */
{id:"MOC-041", t:"single", cn:"MOC", sys:"NEURO", topic:"Advance directives", d:2, b:0.35, cj:"evaluate", tags:["advance-directive","ethics","autonomy"],
 stem:"A client with a stroke has a written advance directive requesting no artificial ventilation, but the family now demands that everything be done. Which action should the nurse take?",
 opts:["Honor the directive and support the family with an ethics consult and clear communication",
  "Follow the family's wishes because they are the legal surrogate now",
  "Withhold the directive from the chart until the provider writes a new order",
  "Ask the court to appoint a guardian before any further decisions"],
 ans:0,
 rat:{c:"A competent adult's advance directive is the controlling expression of autonomy; surrogates interpret wishes, they cannot override a written directive. The nurse's role is to escalate conflicts (ethics committee, provider) while advocating for the documented choice.",
  o:["Correct — the directive governs; ethics support manages the conflict.",
     "Surrogates speak for the client's wishes — they cannot overturn a written directive.",
     "Directives are part of the legal record and must stay visible to the team.",
     "Guardianship is for clients without capacity or directives — not needed here."],
  s:"Written directive > family preference. Your job: advocate, document, and escalate the conflict through ethics channels."},
 ref:"Advance directives · surrogate decision-making"},

{id:"MOC-042", t:"single", cn:"MOC", sys:"REN", topic:"Delegation", d:1, b:-0.1, cj:"generate", tags:["delegation","uap","dialysis","rights-of-delegation"],
 stem:"The nurse is caring for a client receiving hemodialysis for end-stage kidney disease. Which task related to this client can be safely delegated to assistive personnel?",
 opts:["Measuring and recording intake, output, and daily weight using a consistent scale",
  "Auscultating the lung fields for crackles before the next dialysis session",
  "Teaching the client how to limit fluids between dialysis treatments",
  "Assessing the vascular access for a bruit and thrill"],
 ans:0,
 rat:{c:"Measurement and recording of stable vital data (I&O, weights) is within AP scope when the client is stable and the task is routine, standardized, and low-risk. Assessment, teaching, and vascular-access evaluation require nursing judgment and cannot be delegated.",
  o:["Correct — routine measurement with a standard tool is delegable to AP.",
     "Lung auscultation is assessment — reserved for the nurse.",
     "Education is a nursing function requiring judgment and evaluation.",
     "Access assessment (bruit/thrill) is a focused nursing assessment."],
  s:"Apply the rights of delegation: right task (routine, non-invasive), right person (AP), right circumstances (stable client), right direction, right supervision."},
 ref:"Delegation · chronic kidney disease"},

{id:"MOC-043", t:"single", cn:"MOC", fam:"RN", sys:"RESP", topic:"Assignment quality", d:2, b:0.2, cj:"analyze", tags:["assignment","float","acuity"],
 stem:"A float nurse from the medical-surgical unit is assigned to a pulmonary unit. Which client assignment is most appropriate for the float nurse?",
 opts:["A client receiving nebulizer treatments for stable asthma who ambulates independently",
  "A client on a high-flow nasal cannula being weaned by respiratory therapy",
  "A client 6 hours post-thoracotomy with chest tubes and epidural analgesia",
  "A client with a tracheostomy who needs frequent deep-suctioning and titrated oxygen"],
 ans:0,
 rat:{c:"Match scope and experience to acuity: the stable, self-ambulating asthma client has predictable needs within general medical-surgical competence. High-flow weaning, fresh post-thoracotomy with epidural, and trach suctioning with oxygen titration each demand specialty assessment skills.",
  o:["Correct — predictable trajectory, low-technology care suits a float.",
     "High-flow weaning requires specialty respiratory assessment beyond general med-surg.",
     "Post-thoracotomy with epidural is high-acuity specialty care.",
     "Trach suctioning with titrated oxygen needs advanced airway competence."],
  s:"Float assignments default to the competencies the nurse already has — push specialty/high-acuity clients to unit staff."},
 ref:"Assignment · competence-based matching"},

{id:"MOC-044", t:"single", cn:"MOC", sys:"GI", topic:"Adolescent consent", d:2, b:0.3, cj:"recognize", tags:["consent","minor","confidentiality"],
 stem:"A 16-year-old presents to a community clinic requesting testing and treatment for a sexually transmitted infection and asks that the visit stay private. Which action by the nurse is legally and ethically sound?",
 opts:["Allow the adolescent to consent to the testing and keep today’s care confidential within legal limits",
  "Refuse testing at this visit until a custodial parent signs the consent form",
  "Perform the testing but mail all results to the parents' home address",
  "Report the adolescent to child protective services for sexual activity"],
 ans:0,
 rat:{c:"In every U.S. jurisdiction minors may self-consent to STI (and commonly HIV) testing and treatment, and those services are confidential. Forcing parental consent, breaching confidentiality, or reporting consensual adolescent sexual activity misapplies the law and deters care-seeking.",
  o:["Correct — minors self-consent to STI care; confidentiality applies within legal limits.",
     "STI care is the classic statutory exception to parental consent.",
     "Mailing results home breaches the adolescent's confidential care.",
     "Consensual adolescent sexual activity is not, by itself, reportable abuse."],
  s:"Know the minor-consent exceptions: STI, contraception, prenatal, substance use, mental health — consent and confidentiality belong to the minor."},
 ref:"Adolescent consent · confidential services"},

/* ── Safety and Infection Control ──────────────────────────────────── */
{id:"SIC-029", t:"hotspot", cn:"SIC", sys:"INTG", topic:"Cellulitis monitoring", d:1, b:0.1, cj:"recognize", tags:["cellulitis","skin-infection","deterioration"],
 stem:"A client is on the second day of oral antibiotics for a lower-leg cellulitis. The nurse marked the erythema border at the last assessment. Select every finding in the focused reassessment below that signals treatment failure or worsening infection and must be reported.",
 hotspot:{mode:"rows", rows:[
  "Erythema extends 3 cm beyond the marked border and the leg feels warmer",
  "The client reports steady aching pain at the site, unchanged from yesterday",
  "New fever of 38.6° C (101.5° F) with chills since this morning",
  "A few scattered patches of dry, flaking skin near the healed ankle wound",
  "The calf is now visibly swollen with pitting when pressed for 5 seconds",
  "The client tolerating oral antibiotics without nausea or rash"
 ], ans:[0,2,4]},
 rat:{c:"Spreading borders, new fever/chills, and increasing edema after 48 hours of antibiotics indicate treatment failure or progression — the client likely needs IV therapy. Stable aching pain, post-healing dry skin, and antibiotic tolerance are expected findings.",
  s:"Border-marking turns cellulitis monitoring into objective data: direction of spread + systemic signs = escalate. Local dryness and tolerance are noise."},
 ref:"Cellulitis · antibiotic response"},

{id:"SIC-030", t:"single", cn:"SIC", sys:"REN", topic:"Acute kidney injury labs", d:2, b:0.25, cj:"analyze", tags:["aki","hyperkalemia","critical-values"],
 stem:"A client with oliguric acute kidney injury has a morning serum potassium of 6.2 mEq/L and new peaked T waves on telemetry. Which action should the nurse take first?",
 opts:["Notify the provider immediately about the potassium value and the ECG changes",
  "Recheck the potassium level in four hours before taking further action",
  "Encourage oral potassium binders and continue routine monitoring",
  "Ambulate the client to improve renal perfusion and reassess the rhythm"],
 ans:0,
 rat:{c:"Potassium of 6.2 with ECG changes is a critical, life-threatening value — the first action is immediate provider notification so calcium, insulin/dextrose, and dialysis can be ordered. Waiting, binders alone, or ambulation delay definitive treatment of a dysrhythmia risk.",
  o:["Correct — critical value + ECG changes = immediate escalation.",
     "Hyperkalemia with cardiac changes is never a watch-and-wait situation.",
     "Binders work too slowly for peaked T waves and do not stabilize the myocardium.",
     "Activity does not correct oliguric hyperkalemia; the rhythm needs urgent treatment."],
  s:"Peaked T waves + K⁺ 6.2 = cardiac emergency. Nurse's first move: call — treatment orders follow."},
 ref:"Acute kidney injury · hyperkalemia"},

{id:"SIC-031", t:"multi", cn:"SIC", sys:"HEME", topic:"Neutropenic precautions", d:1, b:0.05, cj:"generate", tags:["neutropenia","oncology","protective-isolation"],
 stem:"A client with leukemia has an absolute neutrophil count of 420/mm³ and is on neutropenic precautions. Select every intervention the nurse should include in the plan of care.",
 opts:["Removing fresh flowers and potted plants from the room",
  "Thorough hand hygiene by all staff and visitors before contact",
  "Serving no raw fruits or vegetables or undercooked meats",
  "Placing a surgical mask on the client during transport to imaging",
  "Restricting all visitation and requiring full gown and glove isolation"],
 ans:[0,1,2,3],
 rat:{c:"Neutropenic care removes obvious microbial reservoirs and exposure: no standing water or plants, meticulous hand hygiene (the single most effective measure), no raw/undercooked foods, and masking the client outside the room. Complete visitor bans and full contact isolation are not required — they isolate the client without reducing risk.",
  o:["Correct — soil and standing water harbor Pseudomonas, Aspergillus, and other pathogens.",
     "Correct — hand hygiene is the cornerstone of protecting the neutropenic client.",
     "Correct — raw produce and undercooked meat carry bacterial and fungal loads.",
     "Correct — masking the client during transport limits airborne exposure.",
     "Reverse isolation gowns/gloves for every visitor are outdated; hygiene and reservoir removal are what matter."],
  s:"Think reservoirs and exposure: water, soil, raw food, crowds. Hand hygiene first; compassion does not require a bubble."},
 ref:"Neutropenic precautions · protective environment"},

{id:"SIC-032", t:"single", cn:"SIC", sys:"INTG", topic:"Contact dermatitis", d:1, b:-0.05, cj:"evaluate", tags:["contact-dermatitis","allergen-avoidance","teaching"],
 stem:"A client has recurrent eczematous patches on both earlobes and wrists. Patch testing confirms allergy to nickel. Which instructions should the nurse give?",
 opts:["Choose jewelry labeled surgical steel, titanium, or 18-karat gold, and use barrier coatings on existing metal items",
  "Apply triple-antibiotic ointment to the patches twice daily until they resolve",
  "Continue wearing the favorite watch but rinse the skin under it every evening",
  "Cover the earlobes with adhesive bandages whenever earrings are worn"],
 ans:0,
 rat:{c:"Allergic contact dermatitis is managed by strict allergen avoidance: nickel-free or low-nickel metals (surgical steel, titanium, high-karat gold) plus physical barriers (clear nail polish on clasps, for example) reduce exposure. Antibiotic ointment treats nothing allergic and risks sensitization; intermittent contact still triggers flares; adhesives themselves commonly cause dermatitis.",
  o:["Correct — avoidance plus barriers on metal surfaces is standard nickel counseling.",
     "Antibiotics do not treat type-IV hypersensitivity and can add contact sensitization.",
     "Rinsing does not remove nickel salts deposited on sweating skin — exposure continues.",
     "Adhesive bandages are a frequent cause of contact dermatitis themselves."],
  s:"Patch-test positive = the treatment is avoidance. Barrier the metal or replace it; nothing topical prevents recurrence."},
 ref:"Contact dermatitis · nickel avoidance"},

/* ── Health Promotion and Maintenance ──────────────────────────────── */
{id:"HPM-021", t:"single", cn:"HPM", sys:"HEME", topic:"Sickle cell self-care", d:1, b:0.0, cj:"generate", tags:["sickle-cell","triggers","hydration"], variantGroup:"sickle-triggers",
 stem:"A young adult with sickle cell disease is being seen for a routine check-up after one year without a pain crisis. Which teaching point should the nurse emphasize to keep that streak going?",
 opts:["Drink enough fluids to keep urine pale and avoid situations that cause dehydration, like heavy alcohol use",
  "Take a daily low-dose aspirin to prevent pain crises from forming",
  "Restrict physical activity to avoid oxygen demand from muscles",
  "Use a home pulse oximeter and stay below 92 percent at all times"],
 ans:0,
 rat:{c:"Prevention of vaso-occlusive crises centers on hydration, avoiding extremes of temperature, and treating triggers early (dehydration, altitude, infection). Aspirin does not prevent crises, activity restriction is unnecessary and unhelpful, and 92% is a threshold to report — not a target to stay under.",
  o:["Correct — steady hydration is the single most practical crisis-prevention habit.",
     "Antiplatelet therapy does not prevent sickling.",
     "Moderate activity is encouraged; deprivation of it adds deconditioning risk.",
     "A home value under 95% warrants evaluation — patients are not told to sit at 92%."],
  s:"Crisis prevention = fluids, temperature extremes avoided, infections treated fast. Everything else is monitoring, not prevention."},
 ref:"Sickle cell disease · crisis prevention"},

{id:"HPM-022", t:"single", cn:"HPM", sys:"REN", topic:"CKD diet teaching", d:2, b:0.2, cj:"evaluate", tags:["ckd","diet","potassium","phosphorus"], variantGroup:"ckd-diet",
 stem:"A client with stage 4 chronic kidney disease is starting diet counseling. Which menu selection indicates the client understood the teaching?",
 opts:["Grilled chicken with white rice, summer squash, and a sliced apple",
  "Baked potato with sour cream, spinach salad, and a glass of orange juice",
  "Canned vegetable soup with whole-wheat crackers and a handful of nuts",
  "Baked beans with braised greens, cornbread, and a chocolate milk"],
 ans:0,
 rat:{c:"The kidney-sparing menu limits potassium, phosphorus, sodium, and protein excesses: chicken (moderate protein), white rice and summer squash (low potassium), and an apple (low potassium fruit) fit. Potatoes, spinach, OJ, nuts, dried beans, greens, whole grains, and chocolate milk are dense in potassium and/or phosphorus.",
  o:["Correct — low-potassium produce and moderated protein match the CKD plan.",
     "Potato skin, spinach, and orange juice are classic potassium loads.",
     "Canned soup (sodium) plus nuts and whole grains (phosphorus) stack two problems.",
     "Beans and greens are potassium-rich; chocolate milk adds dairy phosphorus."],
  s:"CKD menus: swap high-K produce (potato, spinach, citrus, dried fruit) for apples, berries, rice, squash; watch dairy/nuts/cola for phosphorus."},
 ref:"Chronic kidney disease · medical nutrition therapy"},

{id:"HPM-023", t:"single", cn:"HPM", sys:"INTG", topic:"Herpes zoster prevention", d:1, b:0.1, cj:"recognize", tags:["zoster","vaccine","older-adults"],
 stem:"A healthy 62-year-old asks about the vaccine to prevent shingles during an annual wellness visit. Which response by the nurse is accurate?",
 opts:["Two doses of recombinant zoster vaccine are recommended for adults 50 and older, even after a prior episode",
  "The vaccine is only offered once an active rash has been present for a week",
  "A single live-virus dose given in childhood covers shingles for life",
  "The vaccine is reserved for adults who have never had chickenpox"],
 ans:0,
 rat:{c:"Recombinant zoster vaccine (RZV) is a two-dose series recommended at age 50+ regardless of prior shingles or chickenpox history — and it is not a live vaccine, so it suits broader populations. It is prophylactic, not treatment, and childhood varicella vaccination does not prevent later reactivation disease.",
  o:["Correct — RZV, two doses, starting at 50, prior episode irrelevant.",
     "Vaccination is prevention — it is not scheduled around an active zoster rash.",
     "Childhood varicella vaccine protects against primary chickenpox, not reactivation.",
     "Prior chickenpox is actually the population at risk for shingles — they still get RZV."],
  s:"Shingles prevention = recombinant zoster vaccine, 2 doses, age ≥50, immunocompetence permitting. Prior episodes do not exclude."},
 ref:"Herpes zoster · immunization schedule"},

/* ── Psychosocial Integrity ────────────────────────────────────────── */
{id:"PSY-021", t:"single", cn:"PSY", sys:"INTG", topic:"Psoriasis body image", d:1, b:0.15, cj:"evaluate", tags:["psoriasis","body-image","therapeutic-communication"],
 stem:"A young adult with widespread plaque psoriasis says, \"I cancelled my beach trip. Nobody should have to look at my skin.\" Which response by the nurse best addresses the client's concern?",
 opts:["It sounds like the visible plaques have changed how you feel about being seen. Would you like to explore ways to feel more comfortable this summer?",
  "Your skin really is not that bad — most people will hardly notice it.",
  "You should bring a trusted friend who can explain your condition to others.",
  "Psoriasis is not contagious, so other people's opinions are simply wrong."],
 ans:0,
 rat:{c:"The therapeutic response names the feeling (altered body image), accepts it without judgment, and invites collaborative problem-solving. Minimizing (\"not that bad\"), delegating advocacy to others, and dismissing the social experience all invalidate the client's reality even when factually tidy.",
  o:["Correct — reflect, validate, and open problem-solving.",
     "\"Not that bad\" minimizes the client's lived experience.",
     "Advocacy by a friend does not treat the client's own distress.",
     "Correct information delivered dismissively shuts the conversation down."],
  s:"Body image loss = grief work. Name it, normalize it, then problem-solve — information is not the intervention."},
 ref:"Psoriasis · altered body image"},

{id:"PSY-022", t:"single", cn:"PSY", sys:"HEME", topic:"New leukemia diagnosis", d:2, b:0.25, cj:"take-action", tags:["leukemia","crisis-intervention","coping"],
 stem:"A client newly diagnosed with acute leukemia stares at the floor and says, \"This doesn't feel real. My whole life just changed in one phone call.\" Which action should the nurse take first?",
 opts:["Sit with the client and encourage expression of feelings about the diagnosis at the client's pace",
  "Provide a detailed overview of the induction chemotherapy protocol",
  "Reassure the client that leukemia survival rates improve every year",
  "Ask the hospital chaplain to visit before the end of the shift"],
 ans:0,
 rat:{c:"The client is in early crisis — the priority intervention is presence and open-ended invitation to express feelings, establishing trust before information. Teaching dumps, premature reassurance, or referral-first approaches bypass the client's immediate need to be heard.",
  o:["Correct — therapeutic presence first; information follows readiness.",
     "Premature detail overload blocks processing of the shock.",
     "\"Survival rates\" reassurance dismisses the present fear.",
     "Referral may help later but the nurse cannot delegate the first moments of crisis support."],
  s:"Crisis first aid = attend before you inform. Sit, ask open-endedly, and let the client set the pace."},
 ref:"Leukemia · coping and crisis intervention"},

{id:"PSY-023", t:"single", cn:"PSY", sys:"REN", topic:"Dialysis adaptation", d:1, b:0.1, cj:"evaluate", tags:["dialysis","adaptation","coping"],
 stem:"A client on maintenance hemodialysis for eight months has missed two sessions in the past month. Which assessment approach best evaluates the client's psychosocial adaptation?",
 opts:["Explore how dialysis fits into the client's daily life and what has changed for them lately",
  "Remind the client that skipped treatments shorten survival and must stop",
  "Ask a family member to supervise transportation to every appointment",
  "Document noncompliance and notify the provider to change the schedule"],
 ans:0,
 rat:{c:"Missed sessions in a previously adherent client signal something has changed — adaptation fatigue, depression, logistics, or cost. Exploring meaning uncovers the driver and preserves the alliance. Lectures, surrogate supervision, and compliance labeling are premature and pathologize before understanding.",
  o:["Correct — assess meaning and barriers first; behavior is data, not a verdict.",
     "Warning lectures damage trust and rarely change behavior drivers.",
     "Outsourcing adherence to family infantilizes the client and misses the cause.",
     "\"Noncompliance\" labeling before assessment ends the conversation."],
  s:"New nonadherence in a stable client = ask what changed. Empathic inquiry before education or escalation."},
 ref:"Hemodialysis · psychosocial adaptation"},

/* ── Basic Care and Comfort ────────────────────────────────────────── */
{id:"BCC-021", t:"single", cn:"BCC", sys:"INTG", topic:"Cellulitis home care", d:1, b:-0.1, cj:"generate", tags:["cellulitis","handoff","return-precautions"],
 stem:"A client is being discharged on oral antibiotics for lower-leg cellulitis with a border marked in ink. Which instruction belongs in the discharge teaching?",
 opts:["Return promptly if redness spreads past the ink line, fever develops, or pain suddenly increases",
  "Soak the leg in hot water three times a day to draw out the infection",
  "Keep the leg dependent and still to slow the spread of the redness",
  "Stop the antibiotic as soon as the skin looks normal to spare the gut flora"],
 ans:0,
 rat:{c:"Safe cellulitis discharge = defined return triggers (spreading erythema, fever, worsening pain), full antibiotic course, and elevation of the limb. Hot soaking risks burns and maceration, dependency increases swelling, and stopping early invites recurrence and resistance.",
  o:["Correct — concrete worsening triggers plus complete the course.",
     "Hot soaks add burn risk (especially with vascular disease) and no evidence benefit.",
     "The limb should be elevated above heart level, not dependent.",
     "Stopping early is a classic driver of relapse and resistance."],
  s:"Every infection discharge needs: finish the antibiotic, elevate, and exact return triggers tied to the marked border."},
 ref:"Cellulitis · discharge criteria"},

{id:"BCC-022", t:"single", cn:"BCC", sys:"REN", topic:"Interpreter use", d:1, b:0.0, cj:"take-action", tags:["interpreter","health-literacy","ckd"], variantGroup:"ckd-diet",
 stem:"A Spanish-speaking client on fluid restriction is being taught about a new kidney diet through a professional interpreter. Which action best verifies understanding before the session ends?",
 opts:["Ask the client to describe tomorrow's planned meals and drinks in their own words, with the interpreter translating",
  "Hand over printed diet materials in Spanish and document that education was completed",
  "Ask the interpreter whether the client seemed to understand the teaching",
  "Have the client sign the dietary education form to acknowledge receipt"],
 ans:0,
 rat:{c:"Teach-back — the client restating the plan in their own words — is the only option that demonstrates comprehension. Printed material documents delivery, not understanding; the interpreter reports translation, not learning; a signature acknowledges receipt only.",
  o:["Correct — teach-back through the interpreter verifies learning, not paperwork.",
     "Materials supplement but cannot confirm understanding.",
     "The interpreter's role is language transfer; understanding must come from the client.",
     "Signatures document receipt — not comprehension."],
  s:"Interpreter sessions close with teach-back in the client's words. Documents record; they do not verify."},
 ref:"Interpreter-mediated education · teach-back"},

{id:"BCC-023", t:"single", cn:"BCC", sys:"HEME", topic:"Critical value escalation", d:2, b:0.15, cj:"prioritize", tags:["tumor-lysis","critical-values","communication"],
 stem:"A client with leukemia started chemotherapy 18 hours ago and now has a serum potassium of 7.1 mEq/L called from the lab. After ensuring the client is on continuous monitoring, which action should the nurse take next?",
 opts:["Give a verbal critical-value report to the provider now and read back the order received",
  "Page the provider at the end of the shift with the day's laboratory bundle",
  "Repeat the laboratory send and hold action until the second result returns",
  "Document the value in the chart and keep monitoring for ECG changes"],
 ans:0,
 rat:{c:"K⁺ 7.1 is tumor lysis syndrome territory and a critical value: immediate verbal report with read-back of any orders is the required escalation, because cardiac arrest risk is minutes-to-hours. Bundled reporting, redraw-before-action, or documentation-only all delay cardioprotection and treatment.",
  o:["Correct — critical value = immediate verbal report + read-back confirmation.",
     "Critical values are never batched into shift-end reports.",
     "Treatment (calcium, insulin/dextrose) should not wait on a confirmatory redraw.",
     "Monitoring continues, but documentation alone abandons the client's immediate risk."],
  s:"Critical value protocol: stabilize monitoring → call now → read back orders → document. Tumor lysis makes speed the treatment."},
 ref:"Tumor lysis syndrome · critical value communication"},

/* ── Pharmacological and Parenteral Therapies ──────────────────────── */
{id:"PHA-045", t:"cloze", cn:"PHA", sys:"HEME", topic:"Heparin infusion", d:2, b:0.2, cj:"generate", tags:["heparin","aptt","hit","antidote"],
 stem:"Complete the safety checks for a client receiving a continuous heparin infusion for a new deep vein thrombosis.",
 cloze:{lines:[
  {pre:"The infusion is titrated using the activated partial thromboplastin time (aPTT); the usual target range is the laboratory's therapeutic range, typically about ", post:" times the control value.",
   opts:["1.5 to 2.5","0.5 to 1.0","4 to 6","10 to 12"], ans:0},
  {pre:"Six days into therapy the platelet count falls by more than half from baseline. The nurse should suspect heparin-induced thrombocytopenia and ", post:" while the provider is contacted.",
   opts:["stop all heparin exposure","reduce the infusion by half","switch to heparin flushes","recheck the platelet count in three days"], ans:0},
  {pre:"If serious bleeding occurs despite stopping the infusion, the reversal agent the nurse should prepare to administer is ", post:".",
   opts:["protamine sulfate","vitamin K","naloxone","flumazenil"], ans:0}
 ]},
 rat:{c:"Heparin safety in three checks: titrate to aPTT 1.5–2.5× control; treat a >50% platelet drop as HIT — stop ALL heparin, including flushes (do not just reduce); and know protamine sulfate as the specific reversal agent. Vitamin K reverses warfarin; naloxone and flumazenil reverse opioids and benzodiazepines.",
  o:["Target range is 1.5–2.5× control — standard VTE titration.","0.5–1.0× is subtherapeutic — that is an unanticoagulated aPTT.","4–6× control describes therapeutic ranges for far more aggressive protocols not used in VTE.","10–12× would be massive overdosage.",
     "Correct — HIT means zero heparin exposure, then an alternative anticoagulant.","Reducing exposure continues to feed the immune process.","Flushes are heparin too — same HIT trigger.","HIT platelet falls evolve over hours to days — waiting invites thrombosis.",
     "Correct — protamine sulfate binds and neutralizes heparin.","Vitamin K reverses warfarin, not heparin.","Naloxone reverses opioids.","Flumazenil reverses benzodiazepines."],
  s:"Heparin trio: aPTT 1.5–2.5×, platelets (drop >50% = stop everything heparin), protamine for reversal."},
 ref:"Heparin · monitoring and HIT"},

{id:"PHA-046", t:"cloze", cn:"PHA", sys:"REN", topic:"Phosphate binders", d:2, b:0.25, cj:"generate", tags:["ckd","phosphate-binder","sevelamer","medication-timing"],
 stem:"Complete the medication teaching for a client with stage 5 kidney disease starting sevelamer, a non-calcium phosphate binder.",
 cloze:{lines:[
  {pre:"To bind dietary phosphate, each sevelamer dose must be taken ", post:" so it mixes with the food in the gut.",
   opts:["with meals and snacks","on an empty stomach at bedtime","one hour before breakfast","only with plain water between meals"], ans:0},
  {pre:"The nurse should teach that active vitamin D (calcitriol) is prescribed because failing kidneys ", post:" adequately.",
   opts:["cannot convert vitamin D to its active form","store vitamin D instead of releasing it","destroy vitamin D during dialysis","absorb vitamin D only from dairy"], ans:0},
  {pre:"If the client also takes prescribed iron supplements, dosing should be separated from the binder by at least ", post:" to avoid blocking absorption.",
   opts:["one hour","one week","two minutes","one day"], ans:0}
 ]},
 rat:{c:"Binders only work in the gut with food — take with every meal and snack. Calcitriol replaces the kidney's lost 1-alpha-hydroxylation. Binders adsorb more than phosphate: separate iron (and other oral drugs) by at least an hour.",
  o:["Correct — binders must physically mix with the meal's phosphate.","An empty-stomach dose binds nothing — no food, no phosphate.","Pre-breakfast dosing misses the day's phosphate load.","Between-meal timing defeats the purpose.",
     "Correct — kidneys perform the final activation step of vitamin D.","Storage is not the problem; activation is.","Dialysis does not destroy vitamin D.","Dairy is one source, not the activation issue.",
     "Correct — one hour of separation protects iron absorption.","A week apart is impractical and unnecessary.","Two minutes leaves the drugs in contact in the stomach.","A full day apart is more than required."],
  s:"Binder logic: no meal, no dose. Separate the meds it can grab (iron, antibiotics) by an hour."},
 ref:"Chronic kidney disease · binder therapy"},

{id:"PHA-047", t:"single", cn:"PHA", sys:"INTG", topic:"Topical corticosteroids", d:1, b:0.05, cj:"evaluate", tags:["topical-steroid","administration","skin"],
 stem:"A provider prescribes triamcinolone 0.1% cream for a client's eczematous rash on the face and forearm. Which client statement indicates correct understanding of the teaching?",
 opts:["I will apply a thin layer to the patch on my arm and ask about a gentler product for my face",
  "I will spread a thick layer over both areas and cover them with plastic wrap overnight",
  "I will apply it to my eyelids generously since that is where the itching is worst",
  "I will stop using it as soon as the redness fades and save the tube for the next flare"],
 ans:0,
 rat:{c:"Low-potency steroids are used on the face (thin skin, atrophy and telangiectasia risk) and mid-potency on the body; thin layers are the rule and occlusion is provider-directed only. Eyelid use demands ophthalmic caution, and hoarding leftover steroid for self-treatment of future flares invites misuse.",
  o:["Correct — potency matched to site, thin layer, and asking first on the face.",
     "Thick layers add no benefit; wrap occlusion multiplies potency and risks atrophy.",
     "Periorbital skin is the thinnest on the body — highest atrophy risk.",
     "Steroids are tapered per instructions, not stockpiled for self-directed reuse."],
  s:"Topical steroid safety = right potency for the site, thinnest effective layer, no occlusion unless ordered."},
 ref:"Topical corticosteroids · administration"},

{id:"PHA-048", t:"single", cn:"PHA", sys:"ENDO", topic:"Prednisone taper", d:1, b:0.1, cj:"evaluate", tags:["glucocorticoids","tapering","adrenal"],
 stem:"A client has taken prednisone 40 mg daily for three weeks for an autoimmune flare and the provider is tapering the dose. Which statement by the client indicates the taper teaching was effective?",
 opts:["I understand my adrenal glands need time to make their own steroid again as the dose comes down",
  "Once my rash clears I can stop the pills entirely on my own that same day",
  "If I get nausea, I should double the dose for two days and then resume the taper",
  "Because I am tapering, I no longer need to watch my blood sugar closely"],
 ans:0,
 rat:{c:"Three weeks of supraphysiologic glucocorticoid suppresses the hypothalamic–pituitary–adrenal axis; tapering lets the adrenal glands resume endogenous production — stopping abruptly risks adrenal crisis. Abrupt self-stopping and self-adjusting are dangerous, and steroid-induced hyperglycemia persists throughout tapering.",
  o:["Correct — taper exists to wake the suppressed adrenal axis back up.",
     "Sudden cessation after 3 weeks can precipitate adrenal crisis.",
     "Clients do not self-titrate steroids — symptoms are reported, not treated.",
     "Hyperglycemia risk continues for as long as steroids are taken."],
  s:"Any steroid beyond ~2 weeks = tapered, never stopped cold. The taper protects the adrenal axis."},
 ref:"Glucocorticoids · HPA axis suppression"},

/* ── Reduction of Risk Potential ───────────────────────────────────── */
{id:"RRP-032", t:"matrix", cn:"RRP", sys:"INTG", topic:"Venous ulcer care", d:2, b:0.2, cj:"evaluate", tags:["venous-insufficiency","ulcer","expected-vs-report"],
 stem:"A home-health nurse is monitoring a client with a venous stasis ulcer on the medial ankle that was measured 3 × 2 cm last week. For each finding, decide whether it is an expected part of venous ulcer healing or must be reported to the provider.",
 matrix:{cols:["Expected finding","Report to provider"], rows:[
  "Wound bed 90% pink granulation tissue with a moderate amount of drainage",
  "Wound now 4 × 3 cm with exposed tendon at the base",
  "Mild ankle edema at the end of the day that improves overnight",
  "Drainage changed from clear amber to thick green with a new foul odor",
  "Client reports a dull ache around the ankle relieved by elevation"
 ], mode:"one", ans:[0,1,0,1,0]},
 rat:{c:"Venous ulcers heal by granulation with moderate drainage, daily-cycle ankle edema, and an ache eased by elevation — all expected. Rapid enlargement with exposed tendon and purulent malodorous drainage signal deterioration/infection and are reportable.",
  s:"Expected for venous disease: pink bed, steady measurements, gravity-dependent edema, elevation-relieved ache. Escalate: growth, deep structures, pus, smell."},
 ref:"Venous insufficiency · wound trajectory"},

{id:"RRP-033", t:"matrix", cn:"RRP", sys:"REN", topic:"AV fistula assessment", d:1, b:0.05, cj:"recognize", tags:["hemodialysis","av-fistula","expected-vs-report"],
 stem:"A client with a radiocephalic arteriovenous fistula in the left forearm is being assessed before an outpatient hemodialysis treatment. For each finding, decide whether it reflects a healthy, usable fistula or must be reported before cannulation.",
 matrix:{cols:["Healthy fistula finding","Report before cannulation"], rows:[
  "A continuous bruit and a palpable thrill at the anastomosis",
  "Absent thrill and bruit with a new firm, pulsatile mass at the site",
  "Slight bulging of the vessel along the cannulation segment",
  "Redness, warmth, and tenderness tracking along the forearm vein",
  "Arm blood pressure 138/82 in the fistula arm after three minutes of rest"
 ], mode:"one", ans:[0,1,0,1,0]},
 rat:{c:"A working fistula buzzes (bruit) and vibrates (thrill); some vessel dilatation along the segment is normal maturation. Loss of bruit/thrill with a pulsatile mass suggests thrombosis/aneurysm and redness tracking along the vein suggests infection or stenosis — both stop cannulation and are reported. (Blood pressures are simply avoided in the fistula arm — a reading itself is not the emergency.)",
  s:"Bruit + thrill = alive. No-sound-plus-mass or tracking inflammation = hold and call. Never cannulate a quiet fistula."},
 ref:"Hemodialysis access · complication detection"},

{id:"RRP-034", t:"single", cn:"RRP", sys:"REN", topic:"Urinary retention", d:1, b:0.0, cj:"take-action", tags:["retention","bph","bladder-scan"],
 stem:"Four hours after a cystoscopy under sedation, an older adult man with benign prostatic hyperplasia has not voided, reports suprapubic fullness, and is restless. Which action should the nurse take first?",
 opts:["Perform a bladder scan at the bedside to measure the retained volume",
  "Encourage the client to drink two large glasses of water quickly",
  "Insert an indwelling urinary catheter and record the output",
  "Apply firm pressure over the suprapubic area until urine flows"],
 ans:0,
 rat:{c:"Post-procedure retention with BPH is first quantified with a bedside bladder scan — objective volume guides whether a straight catheter (typically ≥400–500 mL with inability to void) is needed. Rapid fluids distend the bladder further, an indwelling catheter jumps the least-invasive step, and suprapubic pressure risks injury in a distended bladder.",
  o:["Correct — measure first; the scan is non-invasive and directs the next step.",
     "More fluid into an already-distended bladder worsens pain and retention.",
     "Catheterization may follow the scan — it is not the blind first move.",
     "Credé pressure on a distended post-procedure bladder can cause trauma and reflux."],
  s:"Retention workup: scan → straight catheterize by volume threshold. Fluids and pressure are not treatments for obstruction."},
 ref:"Post-anesthetic retention · benign prostatic hyperplasia"},

{id:"RRP-035", t:"single", cn:"RRP", sys:"INTG", topic:"Lyme disease", d:1, b:0.0, cj:"recognize", tags:["lyme","tick-borne","erythema-migrans"],
 stem:"A camper presents to a walk-in clinic three days after removing an embedded tick from their thigh. There is now a slowly expanding, uniform red ring about 9 cm across with central clearing. Which action is expected?",
 opts:["Start the provider-ordered doxycycline course and teach about later symptoms to watch for",
  "Reassure the client that a ring-shaped rash after a tick bite always fades harmlessly",
  "Send the client home to return only if joint swelling or facial droop develops",
  "Order blood antibody testing today and treat only if it comes back positive"],
 ans:0,
 rat:{c:"Expanding erythema migrans ≥5 cm within days-to-weeks of a tick bite is clinical Lyme disease — empiric doxycycline is started without waiting for serology (early antibodies are often negative), plus teaching on later signs. Watchful waiting risks dissemination, and same-day antibody testing is unreliable early.",
  o:["Correct — clinical diagnosis, empiric treatment, prevention teaching.",
     "Erythema migrans is Lyme disease — it is treated, never watched.",
     "Waiting for carditis, arthritis, or palsy means waiting for dissemination.",
     "Early infection is frequently seronegative — treatment is not gated on the first test."],
  s:"Tick + expanding bullseye ≥5 cm = treat now. Serology lags the rash by weeks."},
 ref:"Lyme disease · erythema migrans"},

/* ── Physiological Adaptation ──────────────────────────────────────── */
{id:"PAA-043", t:"single", cn:"PAA", sys:"INTG", topic:"Impetigo", d:1, b:-0.1, cj:"generate", tags:["impetigo","pediatrics","hygiene"],
 stem:"The parent of a 3-year-old with honey-crusted impetigo around the nose asks when the child can return to daycare and how to manage it at home. Which teaching should the nurse provide?",
 opts:["The child can go back to daycare after 24 hours of effective antibiotic treatment, with separate towels and short, clean nails for scratching",
  "The child must stay home from daycare until every last crust has fully healed and faded",
  "The lesions should be scrubbed vigorously with antibacterial soap three times daily",
  "Keep the child home for a full week of antibiotics before returning regardless of improvement"],
 ans:0,
 rat:{c:"With topical or systemic antibiotics, impetigo exclusion ends after 24 hours of treatment; hygiene measures (own towels, trimmed nails, no sharing) limit auto-inoculation and household spread. Healing-to-exclusion is unnecessary, and aggressive scrubbing traumatizes lesions and spreads bacteria.",
  o:["Correct — 24 hours treated + hygiene measures is the standard return criterion.",
     "Return does not await total resolution — treatment, not appearance, ends contagiousness.",
     "Gentle cleansing is right; scrubbing spreads crust material and worsens lesions.",
     "A blanket week is longer than evidence requires once treated."],
  s:"Impetigo exclusion rule: 24 hours of effective antibiotics. Home care: gentle care, own linens, short nails."},
 ref:"Impetigo · pediatric exclusion criteria"},

{id:"PAA-044", t:"single", cn:"PAA", sys:"HEME", topic:"Iron-deficiency anemia", d:1, b:0.0, cj:"evaluate", tags:["ida","toddler","nutrition"],
 stem:"An 18-month-old who drinks five 8-ounce bottles of whole milk daily has a hemoglobin of 9.2 g/dL and microcytic, hypochromic erythrocytes. Which teaching should the nurse prioritize with the parent?",
 opts:["Cut milk back to about 16 ounces a day and build meals around iron-rich foods with vitamin C",
  "Eliminate every dairy product from the toddler's diet immediately",
  "Continue current milk intake but add an over-the-counter multivitamin",
  "Switch the toddler to toddler formula and continue bottles as preferred"],
 ans:0,
 rat:{c:"Excessive cow's milk causes toddler iron deficiency through gut blood loss, poor iron intake, and impaired absorption. Correction means cutting milk to ~16 oz/day, transitioning off bottles, and pairing iron-rich foods with vitamin C. Total dairy elimination is unnecessary, a multivitamin without dietary change leaves the driver in place, and formula regresses feeding development.",
  o:["Correct — reduce the milk driver and rebuild iron intake at meals.",
     "Reasonable dairy amounts are fine — the problem is the five bottles.",
     "The driver is the milk volume; a vitamin beside it does not fix that.",
     "At 18 months the direction is cups and table food, not back to formula bottles."],
  s:"Milk-anemia equation: >24 oz/day of cow's milk + bottles = microcytic anemia. Treat by subtracting milk, adding iron + vitamin C."},
 ref:"Iron-deficiency anemia · toddler nutrition"},

{id:"PAA-045", t:"multi", cn:"PAA", sys:"HEME", topic:"Sickle cell triggers", d:1, b:0.05, cj:"generate", tags:["sickle-cell","pediatrics","prevention"], variantGroup:"sickle-triggers",
 stem:"The parent of a school-aged child with sickle cell disease is planning activities for the summer. Select every factor the nurse should teach the family to avoid because it can trigger a vaso-occlusive pain crisis.",
 opts:["High-altitude hiking trips above 8,000 feet without supplemental oxygen",
  "Swimming followed immediately by warm showers and dry clothing",
  "Dehydration during long outdoor play on hot days",
  "Intense competitive sports with frequent maximum-exertion bursts",
  "Extreme cold exposure such as playing outdoors in freezing weather",
  "Attending a weekly art class in an air-conditioned studio"],
 ans:[0,2,3,4],
 rat:{c:"Classic sickling triggers: hypoxia (altitude), dehydration (heat, poor intake), extreme exertion, and cold exposure. Gradual warm-water swimming with prompt rewarming is encouraged activity, and a calm art class poses no trigger risk.",
  o:["Correct — altitude hypoxia is a strong sickling trigger.",
     "Warm-water swimming with prompt warming is a recommended activity.",
     "Correct — dehydration drives the blood toward sickling.",
     "Correct — maximal exertion with poor pacing provokes crises.",
     "Correct — cold causes vasoconstriction and sickling in exposed extremities.",
     "Low-exertion, temperature-controlled activity is safe and encouraged."],
  s:"Trigger quartet to avoid: high altitude, dehydration, max exertion, cold. Movement and warmth are friends."},
 ref:"Sickle cell disease · pediatric trigger education"},

{id:"PAA-046", t:"single", cn:"PAA", sys:"REN", topic:"Pediatric UTI prophylaxis", d:1, b:0.15, cj:"evaluate", tags:["uti","vesicoureteral-reflux","prophylaxis"],
 stem:"A 4-year-old with recurring urinary tract infections and grade III vesicoureteral reflux is starting daily antibiotic prophylaxis. Which statement by the parent indicates the teaching was effective?",
 opts:["My child needs to take the antibiotic every day exactly as prescribed, and we will work on regular voiding and treating constipation",
  "We will start the antibiotic only when my child complains of burning with urination",
  "We can stop the daily dose once my child has gone two weeks without a fever",
  "The medicine works best if we give it right after a long bubble bath at night"],
 ans:0,
 rat:{c:"VUR prophylaxis is continuous daily dosing — completion and consistency protect the kidneys from reflux-associated scarring, paired with bladder-bowel management (timed voiding, constipation treatment). Symptom-triggered or short-course dosing abandons prophylaxis, and bubble baths are a mucosal irritant that raises UTI risk.",
  o:["Correct — daily adherence plus voiding and bowel hygiene is the plan.",
     "Prophylaxis is continuous, not rescue dosing.",
     "Two fever-free weeks is not an endpoint — the prescriber reassesses on imaging and growth.",
     "Bubble baths irritate the urethra and are usually discouraged in UTI-prone children."],
  s:"Prophylaxis = every day, not on symptoms. Pair the antibiotic with timed voiding and constipation control."},
 ref:"Vesicoureteral reflux · prophylactic therapy"},

{id:"PAA-047", t:"drag", cn:"PAA", sys:"INTG", topic:"Pediatric skin disorders", d:2, b:0.3, cj:"generate", tags:["dermatology","matching","teaching"],
 stem:"Match each pediatric skin finding to the teaching point the nurse should give the family. Place every teaching point in the box under the correct finding.",
 drag:{targets:[
  "Honey-colored crusted lesions around a 3-year-old's nose",
  "Boggy, scaling, hairless patches on a 6-year-old's scalp",
  "Silver-scaled plaques on a preteen's elbows and knees",
  "Intensely itchy Burrow tracks between a toddler's finger webs"
 ],
 opts:[
  "Treat the whole household and wash bedding — contagious burrowing mite",
  "Complete the full antibiotic course; return to school after 24 hours treated",
  "Not contagious — chronic immune-mediated course with flare-and-remission cycles",
  "Use oral antifungal therapy and check siblings — shared combs and hats spread it"
 ],
 ans:[1,3,2,0]},
 rat:{c:"Impetigo → 24-hour antibiotic return rule. Tinea capitis → oral antifungals (topicals fail in hair follicles) plus sibling checks. Psoriasis → non-contagious, immune-mediated, lifelong flares. Scabies → treat all close contacts and launder, because mites spread by prolonged contact.",
  o:["Impetigo is bacterial and excluded only until 24 hours of treatment.","Tinea capitis requires systemic antifungal therapy — topical agents cannot reach the follicle.","Psoriasis plaques are immune-mediated and carry no contagion risk.","Scabies management is contact treatment plus environment, not just the patient."],
  s:"Four rashes, four mantras: impetigo-24h, tinea-oral, psoriasis-chronic, scabies-treat-everyone."},
 ref:"Pediatric dermatology · family teaching"}
);
