/* RN Ready — item bank v3p · part 13 (blueprint-gap wave 3).
   After waves 1 and 2 the pool sat within +/-0.8 of every blueprint midpoint,
   so this wave is weighted to the categories still marginally under: BCC (0.6),
   RRP (0.5), SIC (0.4), PHA (0.3), PSY (0.3). MOC and HPM are deliberately not
   grown here — both crossed their midpoints in wave 2.

   Same authoring rules as waves 1-2. The stem-cue gate has caught five defects
   in my own writing across this session, so every key below was checked to
   carry the clinical concept without echoing a distinctive stem token.        */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Basic Care & Comfort (blueprint 9%) ───────────────────────────── */
{id:"BCC-031", t:"single", cn:"BCC", sys:"MSK", topic:"Post-arthroplasty positioning", d:2, b:0.2, cj:"act", tags:["hip-replacement","dislocation","positioning"],
 stem:"A client returns from surgery after a total hip arthroplasty. Which positioning measure should the nurse include in the plan of care?",
 opts:["Maintain abduction with a pillow between the legs when turning",
  "Flex the operative hip beyond ninety degrees during repositioning",
  "Cross the lower limbs at the ankles while resting in bed",
  "Rotate the operated limb inward when the client lies supine"],
 ans:0,
 rat:{c:"Posterior dislocation is the main early risk after hip arthroplasty, so abduction is maintained and flexion past ninety degrees, adduction, and internal rotation are avoided. An abduction pillow preserves alignment during turning.",
  o:["Correct — abduction with a pillow preserves joint alignment.",
    "Flexion beyond ninety degrees risks posterior dislocation.",
    "Crossing the limbs adducts the joint and risks dislocation.",
    "Internal rotation is one of the movements explicitly restricted."],
  s:"Hip precautions: no flexion past 90, no adduction, no internal rotation. Keep abduction."},
 ref:"Musculoskeletal · total hip arthroplasty"},

{id:"BCC-032", t:"single", cn:"BCC", sys:"GI", topic:"Enteral feeding aspiration prevention", d:1, b:-0.1, cj:"act", tags:["enteral","aspiration","nutrition"],
 stem:"A client receiving continuous enteral nutrition through a nasogastric tube is being repositioned. Which action reduces the risk of aspiration?",
 opts:["Elevate the head of the bed to at least thirty degrees during feeding",
  "Place the client flat on the left side for thirty minutes",
  "Increase the infusion rate to finish the feeding sooner",
  "Flush the tube with thirty milliliters of sterile water hourly"],
 ans:0,
 rat:{c:"Head-of-bed elevation of thirty to forty-five degrees is the standard aspiration precaution during and after enteral feeding. A supine position removes gravity's protection, and speeding the infusion increases gastric volume and reflux risk.",
  o:["Correct — semi-Fowler positioning is the primary aspiration safeguard.",
    "A flat position increases reflux and aspiration risk.",
    "Faster infusion raises gastric volume and the chance of regurgitation.",
    "Flushing maintains patency but does not prevent aspiration."],
  s:"Tube feeding: head up 30-45 degrees, verify placement, check residuals, never rush the rate."},
 ref:"Nutrition · enteral feeding safety"},

{id:"BCC-033", t:"single", cn:"BCC", sys:"NEURO", topic:"Dysphagia after stroke", d:2, b:0.15, cj:"prioritize", tags:["dysphagia","stroke","swallowing"],
 stem:"A client who had a stroke two days ago coughs during meals. Which intervention should the nurse implement first?",
 opts:["Request a formal swallowing assessment before the client eats again",
  "Thin all liquids to make them easier to swallow",
  "Encourage the client to eat faster while the food is warm",
  "Provide a straw to control the volume of each sip"],
 ans:0,
 rat:{c:"Coughing during meals signals possible aspiration risk, so a formal swallow evaluation must precede further oral intake. Thin liquids are actually the hardest to control, and straws deliver boluses too quickly for a compromised swallow.",
  o:["Correct — a swallow evaluation must precede further oral intake.",
    "Thin liquids are the most difficult to control and raise aspiration risk.",
    "Eating faster increases the chance of aspiration.",
    "Straws deliver a bolus too rapidly for a compromised swallow."],
  s:"Coughing with meals = stop feeding, get a swallow study. Thickened liquids, upright posture, small bites."},
 ref:"Nutrition · dysphagia management"},

{id:"BCC-034", t:"single", cn:"BCC", sys:"INTG", topic:"Pressure injury staging", d:2, b:0.25, cj:"recognize", tags:["pressure-injury","staging","skin"],
 stem:"During a skin assessment the nurse notes a shallow open ulcer with a red-pink wound bed and no slough on the sacrum. How should this be documented?",
 opts:["Stage 2 pressure injury",
  "Stage 3 pressure injury",
  "Stage 1 pressure injury",
  "Unstageable pressure injury"],
 ans:0,
 rat:{c:"A stage 2 injury is partial-thickness skin loss presenting as a shallow open ulcer with a red-pink bed and no slough. Stage 1 is intact non-blanchable skin, stage 3 involves full-thickness loss with visible subcutaneous fat, and unstageable means the base is obscured.",
  o:["Correct — partial-thickness loss with a clean pink bed is stage 2.",
    "Stage 3 is full-thickness loss exposing subcutaneous fat.",
    "Stage 1 is intact skin with non-blanchable redness.",
    "Unstageable applies when slough or eschar obscures the wound base."],
  s:"Stage 1 intact, stage 2 shallow, stage 3 to fat, stage 4 to bone or muscle. Obscured = unstageable."},
 ref:"Integumentary · pressure injury staging"},

{id:"BCC-035", t:"single", cn:"BCC", sys:"NEURO", topic:"Pain assessment in nonverbal clients", d:2, b:0.3, cj:"analyze", tags:["pain","dementia","assessment"],
 stem:"A client with advanced dementia grimaces and guards the abdomen when repositioned but denies pain when asked. What is the nurse's best action?",
 opts:["Use a behavioral pain scale and treat the observed indicators",
  "Accept the verbal denial and document that no pain is present",
  "Reposition more quickly to minimize the visible discomfort",
  "Wait for a family member to confirm whether pain is present"],
 ans:0,
 rat:{c:"Clients with advanced dementia often cannot report pain reliably, so behavioral indicators such as grimacing, guarding, and restlessness become the assessment. Validated tools exist for exactly this situation, and observed indicators warrant treatment.",
  o:["Correct — behavioral indicators are the assessment when self-report fails.",
    "Verbal denial is unreliable in advanced dementia.",
    "Moving faster does not treat the underlying pain.",
    "Waiting for family delays relief for a client in distress."],
  s:"When self-report is unavailable, behavior is the report. Grimacing, guarding, and restlessness count."},
 ref:"Comfort · pain in cognitively impaired clients"},

/* ── Psychosocial Integrity (blueprint 9%) ─────────────────────────── */
{id:"PSY-032", t:"single", cn:"PSY", sys:"PSYCH", topic:"Responding to delusions", d:2, b:0.25, cj:"act", tags:["schizophrenia","delusions","communication"],
 stem:"A client with schizophrenia states that the hospital staff are planning to poison the food. Which response is most therapeutic?",
 opts:["I understand this feels frightening; let us get your meal from the sealed cart",
  "No one here would ever poison you, so please try to eat something",
  "Show me the proof that the staff intend to harm you today",
  "You need to stop having these thoughts before you can eat"],
 ans:0,
 rat:{c:"Therapeutic technique acknowledges the feeling behind the delusion without reinforcing or directly challenging the false belief. Offering a sealed container gives the client concrete control. Arguing, demanding proof, or dismissing the belief all damage trust.",
  o:["Correct — validate the emotion, do not argue with the belief.",
    "Direct contradiction escalates and does not change the delusion.",
    "Demanding proof engages the delusional content as if it were debatable.",
    "Ordering the thoughts to stop invalidates the client's experience."],
  s:"Delusions: validate the feeling, never argue the content. Focus on safety and trust."},
 ref:"Mental health · therapeutic communication"},

{id:"PSY-033", t:"single", cn:"PSY", sys:"PSYCH", topic:"Panic attack intervention", d:2, b:0.15, cj:"act", tags:["anxiety","panic","intervention"],
 stem:"A client in the emergency department is hyperventilating, trembling, and reports a sense of impending doom. Which action should the nurse take first?",
 opts:["Stay with the client and use short, calm, simple statements",
  "Leave the room briefly to reduce the amount of stimulation",
  "Ask the client to describe the childhood origin of the fear",
  "Explain in detail why these symptoms are not dangerous"],
 ans:0,
 rat:{c:"During acute panic the client cannot process complex information, so the nurse remains present, reduces stimulation, and uses brief simple directions. Abandoning the client increases terror, and insight-oriented questioning is inappropriate mid-crisis.",
  o:["Correct — presence with short, calm statements is the first intervention.",
    "Leaving an acutely panicked client alone intensifies the fear.",
    "Exploring origins is insight work, not crisis intervention.",
    "Lengthy explanations cannot be processed during acute panic."],
  s:"Panic: stay, stay brief, stay calm. Reduce stimuli. Insight work comes after, not during."},
 ref:"Mental health · panic management"},

{id:"PSY-034", t:"single", cn:"PSY", sys:"PSYCH", topic:"Alcohol withdrawal risk", d:3, b:0.45, cj:"prioritize", tags:["alcohol-withdrawal","seizure","safety"],
 stem:"A client admitted forty-eight hours after the last drink is tremulous, diaphoretic, and reports seeing insects on the wall. Which priority should guide the plan of care?",
 opts:["Seizure and safety precautions with frequent vital sign monitoring",
  "Group therapy focused on long-term abstinence motivation",
  "Discharge planning to arrange follow-up counseling referrals",
  "Nutritional counseling about balanced daily food choices"],
 ans:0,
 rat:{c:"Visual hallucinations with tremor and diaphoresis at forty-eight hours indicate severe withdrawal approaching delirium tremens, when seizure risk peaks. Safety precautions and close monitoring take precedence over education, planning, or counseling.",
  o:["Correct — seizure precautions and monitoring are the immediate priority.",
    "Motivational work is appropriate only after stabilization.",
    "Discharge planning is premature during acute withdrawal.",
    "Nutrition matters but is not the acute priority."],
  s:"Withdrawal timeline: 6-12h tremor, 12-24h hallucinations, 24-48h seizures, 48-72h DTs."},
 ref:"Mental health · alcohol withdrawal"},

{id:"PSY-035", t:"single", cn:"PSY", sys:"PSYCH", topic:"Nutrition during mania", d:2, b:0.3, cj:"generate", tags:["mania","nutrition","bipolar"],
 stem:"A client in an acute manic episode has not sat down to eat for two days and has lost three kilograms. Which intervention best addresses the nutritional need?",
 opts:["Provide high-calorie finger foods that can be eaten while moving",
  "Require the client to remain seated until the plate is empty",
  "Withhold food until the client agrees to sit at the table",
  "Offer a large meal only at the standard scheduled mealtimes"],
 ans:0,
 rat:{c:"A manic client cannot sit through a meal, so portable high-calorie finger foods meet the nutritional need without a power struggle. Restricting or withholding food escalates conflict and worsens the deficit.",
  o:["Correct — portable high-calorie foods match the client's activity level.",
    "Forcing sitting creates a power struggle and usually fails.",
    "Withholding food is punitive and worsens weight loss.",
    "Fixed large meals will largely go uneaten in acute mania."],
  s:"Mania nutrition: high-calorie finger foods, frequent offers, no power struggles over sitting."},
 ref:"Mental health · mania and nutrition"},

{id:"PSY-036", t:"single", cn:"PSY", sys:"PSYCH", topic:"Hopelessness in depression", d:1, b:0.0, cj:"act", tags:["depression","communication","hopelessness"],
 stem:"A client with major depression tells the nurse, 'Everything I touch falls apart and nothing will ever change.' Which response is most therapeutic?",
 opts:["It sounds like you feel hopeless right now — tell me more about that",
  "You have a lot to live for, so try to stay positive today",
  "Everything will improve once the new medication takes effect",
  "Other clients here are dealing with much worse problems"],
 ans:0,
 rat:{c:"Reflecting the feeling and inviting the client to elaborate validates the experience and opens assessment, including risk assessment for self-harm. Reassurance, false promises, and comparison all shut down communication.",
  o:["Correct — reflection validates the feeling and opens assessment.",
    "Cheerleading minimizes the client's stated experience.",
    "Promising improvement is a false reassurance that cannot be guaranteed.",
    "Comparing suffering invalidates the client's distress."],
  s:"Depression: reflect the feeling, invite more, assess safety. Never minimize or promise."},
 ref:"Mental health · depression and communication"},

/* ── Reduction of Risk Potential (blueprint 12%) ───────────────────── */
{id:"RRP-047", t:"single", cn:"RRP", sys:"RESP", topic:"Contrast media reaction", d:2, b:0.35, cj:"act", tags:["anaphylaxis","contrast","emergency"],
 stem:"Ten minutes into an intravenous contrast infusion for a computed tomography scan, a client develops wheezing, facial swelling, and a dropping blood pressure. Which action is the priority?",
 opts:["Stop the infusion and prepare to give intramuscular epinephrine",
  "Slow the infusion and continue monitoring the airway closely",
  "Administer an oral antihistamine and recheck in fifteen minutes",
  "Complete the scan quickly and then treat the reaction"],
 ans:0,
 rat:{c:"Wheezing, angioedema, and hypotension together indicate anaphylaxis. Stopping the trigger and giving intramuscular epinephrine is first-line; epinephrine reverses both bronchospasm and vasodilation. Antihistamines are adjuncts and act far too slowly.",
  o:["Correct — stop the trigger, give IM epinephrine, support the airway.",
    "Slowing the infusion continues delivering the allergen.",
    "Oral antihistamines are adjuncts, not first-line for anaphylaxis.",
    "Finishing the scan delays lifesaving treatment."],
  s:"Anaphylaxis: stop the trigger, IM epinephrine first. Antihistamines and steroids are adjuncts."},
 ref:"Multisystem · anaphylaxis"},

{id:"RRP-048", t:"single", cn:"RRP", sys:"ENDO", topic:"Post-thyroidectomy hypocalcemia", d:3, b:0.5, cj:"recognize", tags:["thyroidectomy","hypocalcemia","tetany"],
 stem:"Twenty-four hours after a thyroidectomy, a client reports tingling around the mouth and the nurse observes twitching of the facial muscle on tapping. Which laboratory value should the nurse check first?",
 opts:["Serum calcium",
  "Serum potassium",
  "Serum sodium",
  "Serum magnesium"],
 ans:0,
 rat:{c:"Perioral tingling and a positive Chvostek sign indicate neuromuscular irritability from hypocalcemia, a known risk when the parathyroid glands are injured or devascularized during thyroid surgery. Calcium must be checked and replaced promptly.",
  o:["Correct — hypocalcemia causes perioral tingling and a positive Chvostek sign.",
    "Potassium abnormalities produce cardiac rather than facial findings.",
    "Sodium disturbances present with neurologic status changes.",
    "Magnesium is often checked alongside calcium but calcium is first here."],
  s:"Chvostek and Trousseau signs = low calcium. Common after thyroid and parathyroid surgery."},
 ref:"Endocrine · post-thyroidectomy complications"},

{id:"RRP-049", t:"single", cn:"RRP", sys:"NEURO", topic:"Cerebrospinal fluid leak", d:3, b:0.55, cj:"recognize", tags:["craniotomy","csf-leak","meningitis"],
 stem:"A client who had a craniotomy three days ago reports a salty taste in the mouth, and the nurse notes clear drainage from the nose. Which action is indicated?",
 opts:["Test the drainage for glucose and notify the provider promptly",
  "Suction the nares vigorously to clear the accumulated fluid",
  "Place the client in a flat position to reduce the drainage",
  "Document the finding as expected postoperative nasal congestion"],
 ans:0,
 rat:{c:"A salty taste with clear nasal drainage after craniotomy suggests a cerebrospinal fluid leak, which carries a high meningitis risk. The fluid is tested for glucose and the provider is notified. Suctioning and nose-blowing are contraindicated because they can force organisms upward.",
  o:["Correct — test for glucose and notify; a CSF leak risks meningitis.",
    "Suctioning can introduce organisms into the cranial vault.",
    "A flat position increases intracranial pressure and can worsen the leak.",
    "This finding is not normal congestion and requires evaluation."],
  s:"CSF leak: clear nasal drainage plus salty taste. Test for glucose, notify, no suction or nose-blowing."},
 ref:"Neurologic · post-craniotomy complications"},

{id:"RRP-050", t:"single", cn:"RRP", sys:"CV", topic:"Suspected deep vein thrombosis", d:2, b:0.25, cj:"act", tags:["dvt","thrombosis","postoperative"],
 stem:"Five days after knee replacement a client reports new calf pain and the nurse notes warmth and swelling in the affected leg. Which action should the nurse take?",
 opts:["Maintain bed rest and notify the provider for further evaluation",
  "Massage the calf firmly to relieve the discomfort",
  "Apply a heating pad and encourage ambulation in the hallway",
  "Measure both ankles and recheck the calf in twenty-four hours"],
 ans:0,
 rat:{c:"Unilateral calf pain with warmth and swelling after orthopedic surgery suggests deep vein thrombosis. The limb is rested and the provider notified for diagnostic imaging. Massage is contraindicated because it can dislodge the clot and cause pulmonary embolism.",
  o:["Correct — rest the limb and escalate for imaging; do not manipulate it.",
    "Massage can dislodge the thrombus and cause embolism.",
    "Heat and ambulation increase the risk of embolization.",
    "Waiting twenty-four hours delays diagnosis of a time-critical condition."],
  s:"Suspected DVT: do NOT massage. Rest, notify, anticipate ultrasound and anticoagulation."},
 ref:"Cardiovascular · deep vein thrombosis"},

/* ── Safety & Infection Control (blueprint 13%) ────────────────────── */
{id:"SIC-046", t:"single", cn:"SIC", sys:"GI", topic:"Hand hygiene agent selection", d:1, b:-0.15, cj:"analyze", tags:["hand-hygiene","norovirus","infection-control"],
 stem:"Which situation most clearly requires hand hygiene with soap and water rather than an alcohol-based product?",
 opts:["After providing care to a client with norovirus gastroenteritis",
  "Before performing a sterile dressing change on a surgical wound",
  "After removing clean gloves at the end of a routine assessment",
  "Before entering the room of a client on contact precautions"],
 ans:0,
 rat:{c:"Alcohol does not reliably inactivate non-enveloped viruses such as norovirus, nor does it kill C. difficile spores. In those cases mechanical removal with soap and running water is required. The other situations are appropriately served by alcohol-based rub.",
  o:["Correct — norovirus is not reliably killed by alcohol.",
    "Alcohol-based rub is appropriate before a sterile procedure.",
    "Alcohol-based rub is standard after glove removal.",
    "Contact precautions alone do not require soap and water."],
  s:"Soap and water for: C. diff spores, norovirus, and visibly soiled hands. Otherwise alcohol rub."},
 ref:"Infection control · hand hygiene"},

{id:"SIC-047", t:"single", cn:"SIC", sys:"NEURO", topic:"Droplet precautions", d:2, b:0.1, cj:"act", tags:["meningitis","droplet","isolation"],
 stem:"A client is admitted with suspected bacterial meningitis. Which precaution should the nurse implement while awaiting confirmation?",
 opts:["Droplet precautions with a surgical mask for close contact",
  "Airborne precautions in a negative-pressure room",
  "Contact precautions with a gown and sterile gloves",
  "Standard precautions alone until the culture returns"],
 ans:0,
 rat:{c:"Bacterial meningitis spreads through large respiratory droplets, so droplet precautions with a mask are indicated and should continue for twenty-four hours after effective antibiotics. Waiting for confirmation leaves contacts exposed.",
  o:["Correct — droplet precautions apply from suspicion onward.",
    "Negative-pressure rooms are for airborne pathogens, not meningitis.",
    "Contact precautions address direct transmission, not respiratory droplets.",
    "Standard precautions alone are insufficient for suspected meningitis."],
  s:"Droplet = surgical mask, within three feet. Meningitis, influenza, pertussis, mumps, rubella."},
 ref:"Infection control · droplet isolation"},

{id:"SIC-048", t:"single", cn:"SIC", sys:"INF", topic:"Sharps disposal", d:1, b:-0.2, cj:"act", tags:["sharps","safety","standard-precautions"],
 stem:"After giving an intramuscular injection, the nurse needs to dispose of the used needle. Which action is correct?",
 opts:["Activate the safety device and discard it into the sharps container at the bedside",
  "Recap the needle carefully using both hands before disposal",
  "Break the needle off at the hub and place it in a biohazard bag",
  "Carry the uncovered needle to the disposal unit down the hall"],
 ans:0,
 rat:{c:"Sharps must go directly into a puncture-resistant container located at the point of use. Two-handed recapping is a leading cause of needlestick injury, needles are never bent or broken, and they are never carried loose.",
  o:["Correct — point-of-use disposal without recapping is the standard.",
    "Two-handed recapping is a common cause of needlestick injuries.",
    "Needles must never be bent, broken, or removed from the syringe.",
    "Carrying a loose needle through a corridor risks injury to others."],
  s:"Sharps: no recapping, no bending, no breaking. Point-of-use container, fill only to the line."},
 ref:"Infection control · sharps safety"},

{id:"SIC-049", t:"single", cn:"SIC", sys:"INF", topic:"Latex sensitivity", d:1, b:0.05, cj:"recognize", tags:["latex","allergy","cross-reactivity"],
 stem:"A client reports a history of itching and swelling after balloon inflation at a birthday party. Which item should the nurse remove from the care area?",
 opts:["Any equipment containing natural rubber components",
  "All adhesive tape used for securing intravenous lines",
  "Every product containing iodine-based antiseptic solution",
  "All wool blankets stored in the linen cabinet nearby"],
 ans:0,
 rat:{c:"A reaction to balloon rubber indicates latex sensitivity, so all natural rubber products must be removed and a latex-safe environment maintained. Adhesive, iodine, and wool are separate allergens and are not implicated by this history.",
  o:["Correct — balloon rubber indicates latex sensitivity.",
    "Adhesive sensitivity is a distinct allergy, not indicated here.",
    "Iodine sensitivity is unrelated to a rubber reaction.",
    "Wool allergy is a separate contact sensitivity."],
  s:"Latex clues: reactions to balloons, gloves, or bananas/avocado/kiwi. Use a latex-safe cart."},
 ref:"Infection control · latex precautions"},

/* ── Pharmacological Therapies (blueprint 16%) ─────────────────────── */
{id:"PHA-066", t:"single", cn:"PHA", sys:"INF", topic:"Vancomycin infusion reaction", d:2, b:0.3, cj:"act", tags:["vancomycin","infusion-reaction","antibiotic"],
 stem:"A client receiving intravenous vancomycin develops flushing of the face and neck during the infusion. Which action should the nurse take?",
 opts:["Reduce the delivery rate and assess for rash or hypotension",
  "Stop the medication permanently and document an allergy",
  "Increase the rate to shorten the duration of the exposure",
  "Give the next dose by the intramuscular route instead"],
 ans:0,
 rat:{c:"Flushing of the face and neck during vancomycin describes vancomycin infusion reaction, caused by rapid infusion and histamine release rather than true allergy. Slowing the rate usually resolves it, and premedication with an antihistamine may be used for later doses.",
  o:["Correct — slow the rate and assess; this is rate-related, not allergic.",
    "This reaction is not a true allergy, so the drug need not be abandoned.",
    "Faster infusion worsens histamine release.",
    "Vancomycin is not given intramuscularly."],
  s:"Red-man flushing = infuse slower, not an allergy. True allergy shows urticaria and wheeze."},
 ref:"Antimicrobials · vancomycin administration"},

{id:"PHA-067", t:"single", cn:"PHA", sys:"MSK", topic:"Statin adverse effect monitoring", d:2, b:0.2, cj:"recognize", tags:["statin","myopathy","monitoring"],
 stem:"A client taking atorvastatin reports new muscle aching and dark urine. Which laboratory result should the nurse anticipate?",
 opts:["An elevated creatine kinase level",
  "A decreased international normalized ratio",
  "An elevated serum amylase level",
  "A decreased thyroid-stimulating hormone level"],
 ans:0,
 rat:{c:"Muscle pain with dark urine suggests statin-induced myopathy or rhabdomyolysis, in which muscle breakdown releases creatine kinase and myoglobin. Creatine kinase is the diagnostic marker, and myoglobin can cause acute kidney injury.",
  o:["Correct — muscle breakdown raises creatine kinase.",
    "The INR reflects anticoagulation, not muscle injury.",
    "Amylase relates to pancreatic inflammation.",
    "Thyroid-stimulating hormone screens thyroid function."],
  s:"Statin red flags: muscle pain plus dark urine = check CK, hold the drug, protect the kidneys."},
 ref:"Lipid-lowering agents · statin monitoring"},

{id:"PHA-068", t:"single", cn:"PHA", sys:"CV", topic:"Nitroglycerin client teaching", d:1, b:-0.05, cj:"evaluate", tags:["nitroglycerin","angina","teaching"],
 stem:"A client with angina is prescribed sublingual nitroglycerin. Which instruction should the nurse include in the teaching?",
 opts:["Sit or lie down before taking a dose to prevent lightheadedness",
  "Swallow the tablet whole with a full glass of water",
  "Take up to six tablets spaced five minutes apart before calling",
  "Store the tablets in a clear plastic pill organizer"],
 ans:0,
 rat:{c:"Nitroglycerin causes rapid vasodilation and orthostatic hypotension, so the client should be seated or lying before dosing. The tablet dissolves under the tongue rather than being swallowed, no more than three doses are taken before calling emergency services, and the drug must stay in its original dark glass container.",
  o:["Correct — sitting prevents syncope from sudden vasodilation.",
    "The tablet is placed under the tongue, not swallowed.",
    "The limit is three doses; beyond that, call emergency services.",
    "Nitroglycerin degrades in light and plastic; keep it in dark glass."],
  s:"Nitroglycerin: sit first, one dose every five minutes, three total, then call 911. Dark glass bottle."},
 ref:"Antianginal therapy · nitroglycerin teaching"},

{id:"PHA-069", t:"single", cn:"PHA", sys:"ENDO", topic:"Levothyroxine administration", d:1, b:0.0, cj:"evaluate", tags:["levothyroxine","hypothyroidism","teaching"],
 stem:"A client is newly prescribed levothyroxine for hypothyroidism. Which statement by the client shows correct understanding?",
 opts:["I will take it on an empty stomach about an hour before breakfast",
  "I will stop taking it once my energy level returns to normal",
  "I should take it with a calcium supplement to help absorption",
  "I can double the dose if I miss one during a busy morning"],
 ans:0,
 rat:{c:"Levothyroxine absorption is impaired by food, calcium, and iron, so it is taken on an empty stomach thirty to sixty minutes before breakfast. It is lifelong replacement therapy, and a missed dose is never doubled because of cardiac risk.",
  o:["Correct — an empty stomach before breakfast maximizes absorption.",
    "Thyroid replacement is lifelong; stopping causes relapse.",
    "Calcium binds the drug and reduces absorption.",
    "Doubling a dose risks tachycardia and dysrhythmia."],
  s:"Levothyroxine: empty stomach, morning, separate from calcium/iron by four hours, never double up."},
 ref:"Thyroid therapy · levothyroxine teaching"}
);
