/* RN Ready — item bank v3p · part 11 (blueprint-gap wave 1).
   Authored against the measured client-need gap versus the 2026 RN blueprint
   midpoints: PHA 14.9% vs 16% (largest deficit), then RRP and SIC marginally
   under, with PSY and BCC already above midpoint and deliberately not grown.
   Every item is independently written — distinct clinical scenario, distinct
   key, distinct distractor logic — and carries full rationales plus a strategy
   note. Option lengths are kept even to avoid the longest-key cue, and no
   distinctive stem token is allowed to appear in the key alone.

   This file is wave 1 of an honest growth path: real items, not scaffolds.  */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Pharmacological Therapies (blueprint 16%) ─────────────────────── */
{id:"PHA-056", t:"single", cn:"PHA", sys:"HEME", topic:"Heparin infusion monitoring", d:2, b:0.15, cj:"act", tags:["anticoagulant","heparin","aptt"],
 stem:"A client receiving a continuous intravenous heparin infusion for deep vein thrombosis has an activated partial thromboplastin time of 110 seconds against a control of 30 seconds. Which action should the nurse take first?",
 opts:["Reduce the infusion rate according to the nomogram and repeat the test",
  "Maintain the present rate and document the laboratory result",
  "Discontinue the therapy permanently and apply pressure to the site",
  "Give the prescribed oral anticoagulant in place of the infusion"],
 ans:0,
 rat:{c:"An aPTT of 110 seconds against a 30-second control is roughly 3.7 times control, above the usual therapeutic window of 1.5 to 2.5 times control. Weight-based nomograms call for a rate reduction with a repeat draw rather than abandoning anticoagulation.",
  o:["Correct — supratherapeutic values call for a protocol rate reduction and a repeat test.",
    "Leaving an out-of-range infusion running exposes the client to bleeding.",
    "Permanent discontinuation overcorrects; the thrombosis still requires treatment.",
    "Adding an oral agent on top of a supratherapeutic infusion compounds bleeding risk."],
  s:"Heparin aPTT target is 1.5 to 2.5 times control. Above that, slow it — do not stop it."},
 ref:"Anticoagulant therapy · heparin monitoring"},

{id:"PHA-057", t:"single", cn:"PHA", sys:"ENDO", topic:"Insulin timing with meals", d:1, b:-0.1, cj:"act", tags:["insulin","diabetes","timing"],
 stem:"A client with type 1 diabetes will begin eating breakfast momentarily. Which prescribed insulin should the nurse administer now?",
 opts:["Insulin lispro, a rapid-acting analog",
  "Insulin glargine, a peakless basal insulin",
  "NPH insulin, an intermediate-acting suspension",
  "Insulin detemir, a once-daily basal insulin"],
 ans:0,
 rat:{c:"Rapid-acting analogs such as lispro begin working in roughly 15 minutes and are timed to food intake. The basal and intermediate insulins listed provide background coverage and are not matched to a meal.",
  o:["Correct — rapid-acting analogs are given at the start of a meal.",
    "Glargine has no pronounced peak and is not meal-related.",
    "NPH peaks in four to twelve hours, too slow for immediate coverage.",
    "Detemir is a basal insulin given on a fixed schedule."],
  s:"Meal coverage = rapid-acting. Background coverage = basal. Never substitute one for the other."},
 ref:"Diabetes management · insulin pharmacokinetics"},

{id:"PHA-058", t:"single", cn:"PHA", sys:"CV", topic:"Digoxin administration safety", d:2, b:0.2, cj:"prioritize", tags:["digoxin","apical-pulse","cardiac"],
 stem:"Before administering a scheduled dose of digoxin to an older adult with heart failure, which assessment finding should cause the nurse to withhold the medication and contact the provider?",
 opts:["An apical pulse of 52 beats per minute",
  "A blood pressure of 128/76 mm Hg",
  "A respiratory rate of 18 breaths per minute",
  "An oxygen saturation of 96% on room air"],
 ans:0,
 rat:{c:"Digoxin slows conduction through the atrioventricular node. An apical rate below 60 in an adult is the standard hold parameter, and bradycardia is an early sign of toxicity.",
  o:["Correct — hold for an apical rate under 60 and notify the provider.",
    "This blood pressure is within normal limits and not a hold parameter.",
    "This respiratory rate is normal and unrelated to digoxin effects.",
    "This saturation is acceptable and does not indicate digoxin toxicity."],
  s:"Digoxin hold rule: count a full apical minute; hold under 60 in adults, under 70 in children."},
 ref:"Cardiac glycosides · digoxin safety"},

{id:"PHA-059", t:"single", cn:"PHA", sys:"RESP", topic:"Opioid-induced respiratory depression", d:2, b:0.1, cj:"act", tags:["opioid","naloxone","respiratory"],
 stem:"Forty minutes after intravenous morphine, a postoperative client is difficult to arouse and has a respiratory rate of 8 breaths per minute. Which action is the nurse's priority?",
 opts:["Administer the prescribed naloxone and stay with the client",
  "Document the finding and reassess in thirty minutes",
  "Reposition the client and encourage deep breathing",
  "Reduce the next scheduled dose by half"],
 ans:0,
 rat:{c:"A respiratory rate of 8 with decreased arousal indicates opioid-induced respiratory depression. Naloxone is the specific antagonist and must be given promptly while the nurse remains at the bedside, because its duration is shorter than most opioids and renarcotization can occur.",
  o:["Correct — reverse the opioid and maintain continuous observation.",
    "Waiting thirty minutes risks progression to respiratory arrest.",
    "Positioning cannot reverse pharmacologic respiratory depression.",
    "Adjusting a future dose does nothing for the present emergency."],
  s:"RR under 10 plus sedation after an opioid = naloxone now, monitor for rebound sedation."},
 ref:"Opioid analgesia · overdose reversal"},

{id:"PHA-060", t:"single", cn:"PHA", sys:"PSYCH", topic:"MAOI dietary restriction", d:2, b:0.25, cj:"evaluate", tags:["maoi","tyramine","teaching"],
 stem:"A client started on phenelzine for depression asks which foods to avoid. Which selection by the client shows the teaching was effective?",
 opts:["I will skip the aged cheddar and cured sausage at the deli counter",
  "I will drink extra grapefruit juice to help absorb the medicine",
  "I should eat more leafy greens to keep my vitamin K level steady",
  "I need to avoid eating shellfish before my laboratory draws"],
 ans:0,
 rat:{c:"Monoamine oxidase inhibitors block the breakdown of tyramine. Aged cheeses, cured and smoked meats, and other fermented foods can trigger a hypertensive crisis. Grapefruit, vitamin K, and shellfish relate to other drug classes.",
  o:["Correct — aged cheese and cured meat are high-tyramine foods.",
    "Grapefruit interacts with statins and some calcium channel blockers, not MAOIs.",
    "Vitamin K consistency matters for warfarin, not phenelzine.",
    "Shellfish restriction is associated with iodinated contrast, not MAOIs."],
  s:"MAOI = no tyramine. Aged, fermented, cured, or spoiled protein is the danger list."},
 ref:"Antidepressants · MAOI dietary teaching"},

{id:"PHA-061", t:"single", cn:"PHA", sys:"PSYCH", topic:"Lithium therapeutic monitoring", d:2, b:0.3, cj:"analyze", tags:["lithium","toxicity","bipolar"],
 stem:"A client taking lithium for bipolar disorder reports a coarse hand tremor, vomiting, and unsteady walking. Which interpretation should the nurse make?",
 opts:["The serum level is above the therapeutic range and the dose must be held",
  "These are expected adjustment effects during the first week of therapy",
  "This is a transient extrapyramidal reaction that needs no intervention",
  "This is a mild allergic response that an antihistamine will control"],
 ans:0,
 rat:{c:"Coarse tremor, gastrointestinal upset, and ataxia are classic early signs of lithium toxicity. The dose should be held and a serum level drawn, since levels above the narrow therapeutic range progress to seizures and coma.",
  o:["Correct — hold the dose, draw a level, and encourage fluids.",
    "A fine tremor may occur early, but coarse tremor with ataxia is not expected.",
    "Extrapyramidal symptoms follow antipsychotics, not lithium.",
    "These findings are neurologic and gastrointestinal, not allergic."],
  s:"Fine tremor is common; COARSE tremor plus ataxia plus vomiting is toxicity. Hold and level."},
 ref:"Mood stabilizers · lithium toxicity"},

{id:"PHA-062", t:"single", cn:"PHA", sys:"RESP", topic:"Beta-blocker contraindication", d:2, b:0.2, cj:"analyze", tags:["beta-blocker","asthma","contraindication"],
 stem:"A provider prescribes propranolol for a client whose history includes hypertension and asthma. Which action should the nurse take?",
 opts:["Question the order because nonselective beta-blockers can trigger bronchospasm",
  "Administer the dose since beta-blockers lower airway resistance",
  "Give the dose only when the client reports chest tightness",
  "Hold the medication until the client finishes a steroid taper"],
 ans:0,
 rat:{c:"Propranolol blocks both beta-1 and beta-2 receptors. Beta-2 blockade causes bronchoconstriction and can precipitate an asthma attack, so the order should be clarified and a cardioselective alternative considered.",
  o:["Correct — nonselective beta-blockade is risky in reactive airway disease.",
    "Beta-blockers increase, not decrease, airway resistance.",
    "PRN dosing does not remove the underlying contraindication.",
    "Waiting for a steroid taper ignores the need to clarify the order now."],
  s:"Nonselective beta-blockers end in -olol and hit the lungs. Asthma or COPD — question the order."},
 ref:"Antihypertensives · beta-blocker precautions"},

{id:"PHA-063", t:"single", cn:"PHA", sys:"REN", topic:"Potassium-sparing diuretic teaching", d:1, b:-0.05, cj:"evaluate", tags:["diuretic","hyperkalemia","teaching"],
 stem:"A client newly prescribed spironolactone asks about diet. Which statement indicates the client understands the teaching?",
 opts:["I should not start using a salt substitute without asking my provider",
  "I need to eat more bananas and oranges every single day",
  "I must limit my fluid intake to one liter each day",
  "I should add extra sodium to prevent dizziness when standing"],
 ans:0,
 rat:{c:"Spironolactone conserves potassium. Most salt substitutes are potassium chloride, so combining them raises hyperkalemia risk. Deliberately increasing potassium-rich foods would compound that risk.",
  o:["Correct — salt substitutes are usually potassium-based and unsafe here.",
    "Adding potassium-rich foods increases hyperkalemia risk.",
    "Fluid restriction is not a routine requirement of this medication.",
    "Extra sodium works against the purpose of diuretic therapy."],
  s:"Potassium-sparing means potassium-retaining. Watch salt substitutes, supplements, and salt-free seasonings."},
 ref:"Diuretics · potassium-sparing agents"},

{id:"PHA-064", t:"multi", cn:"PHA", sys:"INTG", topic:"Chemotherapy extravasation", d:3, b:0.55, cj:"act", tags:["chemotherapy","extravasation","vesicant"],
 stem:"A client receiving a vesicant chemotherapy infusion reports burning at the peripheral site, and the nurse notes swelling without blood return. Which actions should the nurse take? Select all that apply.",
 opts:["Stop the infusion immediately while leaving the catheter in place",
  "Aspirate any residual drug from the catheter before removing it",
  "Flush the line briskly with saline to disperse the medication",
  "Notify the provider and document the estimated volume extravasated",
  "Remove the catheter at once and apply firm pressure to the site"],
 ans:[0,1,3],
 rat:{c:"For a suspected vesicant extravasation, stop the infusion but keep the catheter in place so residual drug can be aspirated and an antidote can be instilled if ordered. Flushing disperses the vesicant into more tissue, and removing the catheter discards the access needed for treatment.",
  o:["Correct — stop the infusion, keep the catheter for aspiration.",
    "Correct — aspirating residual drug limits tissue exposure.",
    "Incorrect — flushing spreads the vesicant and enlarges the injury.",
    "Correct — provider notification and volume documentation guide treatment.",
    "Incorrect — removing access early eliminates the route for antidote delivery."],
  s:"Vesicant extravasation: STOP, KEEP the line, ASPIRATE, NOTIFY. Never flush."},
 ref:"Oncology nursing · extravasation management"},

{id:"PHA-065", t:"single", cn:"PHA", sys:"HEME", topic:"Warfarin dietary consistency", d:1, b:0.0, cj:"evaluate", tags:["warfarin","vitamin-k","teaching"],
 stem:"A client on long-term warfarin therapy asks about eating vegetables. Which response by the nurse is most appropriate?",
 opts:["Keep your intake of green leafy vegetables steady from week to week",
  "Eliminate all green leafy vegetables from your diet completely",
  "Eat large salads daily to protect your blood vessels",
  "Avoid green vegetables only in the week before a procedure"],
 ans:0,
 rat:{c:"Vitamin K antagonizes warfarin, so what matters is consistency rather than avoidance. Sudden increases lower the INR and sudden decreases raise it, either way destabilizing anticoagulation.",
  o:["Correct — consistent vitamin K intake keeps the INR stable.",
    "Total elimination is unnecessary and destabilizes the INR if reversed later.",
    "Large daily servings raise vitamin K load and can reduce warfarin effect.",
    "Restricting only before procedures leaves day-to-day control unstable."],
  s:"Warfarin and vitamin K: consistency beats avoidance. Same amount, same frequency."},
 ref:"Anticoagulant therapy · warfarin teaching"},

/* ── Reduction of Risk Potential (blueprint 12%) ───────────────────── */
{id:"RRP-042", t:"single", cn:"RRP", sys:"HEME", topic:"Transfusion reaction", d:2, b:0.15, cj:"prioritize", tags:["transfusion","reaction","blood"],
 stem:"Fifteen minutes into a packed red blood cell transfusion, a client reports flank pain and chills, and the temperature rises to 38.9 C. Which action should the nurse take first?",
 opts:["Stop the transfusion and keep the line open with normal saline",
  "Slow the infusion rate and reassess the client in fifteen minutes",
  "Administer an antipyretic and continue the transfusion as ordered",
  "Draw a post-transfusion blood sample before stopping the infusion"],
 ans:0,
 rat:{c:"Fever, chills, and flank pain suggest an acute hemolytic reaction. The first action is always to stop the transfusion and maintain venous access with normal saline so treatment can be given and the unit returned for investigation.",
  o:["Correct — stop the blood, keep the vein open with saline.",
    "Slowing the rate still delivers incompatible cells.",
    "Treating the fever without stopping the transfusion allows hemolysis to continue.",
    "Laboratory work follows stopping the infusion, never precedes it."],
  s:"Any transfusion reaction: STOP first, saline to keep the line, then notify and send the unit back."},
 ref:"Blood administration · acute hemolytic reaction"},

{id:"RRP-043", t:"single", cn:"RRP", sys:"CV", topic:"Postoperative hemorrhage", d:2, b:0.2, cj:"recognize", tags:["hemorrhage","shock","postoperative"],
 stem:"Four hours after abdominal surgery, a client's heart rate rises from 84 to 124 beats per minute while blood pressure falls from 122/78 to 96/58 mm Hg and urine output drops. Which interpretation is most accurate?",
 opts:["Early hypovolemic shock from possible internal bleeding",
  "An expected response to anesthesia wearing off",
  "A pain response that will settle with the next analgesic dose",
  "A positional change caused by turning the client"],
 ans:0,
 rat:{c:"Rising heart rate with falling blood pressure and decreasing urine output is the classic early pattern of hypovolemic shock. Tachycardia is a compensatory response and appears before blood pressure collapses.",
  o:["Correct — tachycardia, hypotension, and oliguria signal volume loss.",
    "Emerging from anesthesia does not produce this combined pattern.",
    "Pain typically raises both heart rate and blood pressure.",
    "Repositioning does not cause sustained tachycardia with oliguria."],
  s:"Shock shows up as a rising pulse before a falling pressure. Trust the trend, not the single value."},
 ref:"Postoperative care · hemorrhage recognition"},

/* Rewritten: this item previously restated RRP-002 (chest tube disconnected from
   the drainage system → improvise a water seal) with a different stem wording and
   the same key. A paraphrase is a different fingerprint, so the exact-match
   duplicate scan passed it while both items asked one question. */
{id:"RRP-044", t:"single", cn:"RRP", sys:"RESP", topic:"Tracheostomy tube displacement", d:3, b:0.45, cj:"act", tags:["tracheostomy","airway","emergency"],
 stem:"Two days after a tracheostomy, a client's tracheostomy tube is accidentally expelled during repositioning. Which action does the nurse take first?",
 opts:["Call for help and attempt to reinsert a spare tube of the same size",
  "Cover the stoma with a sterile gauze and have the client breathe through the nose",
  "Wait for the respiratory therapist to arrive before acting",
  "Suction the stoma deeply and then reinsert the tube"],
 ans:0,
 rat:{c:"The tract is immature for roughly the first week, so an expelled tube leaves a stoma that narrows and closes quickly. The nurse summons help and immediately attempts reinsertion with the obturator and a same-size spare, because waiting for another clinician can cost the airway.",
  o:["Correct — re-establish the airway now with a same-size spare tube and obturator.",
    "Relying on nasal breathing abandons a client whose upper airway may not be patent.",
    "Waiting risks stoma closure and loss of the airway.",
    "Deep suctioning delays reinsertion and can traumatize an immature tract."],
  s:"Accidental decannulation in a fresh tracheostomy: call for help and reinsert a same-size spare tube immediately."},
 ref:"Airway · tracheostomy emergencies"},

{id:"RRP-045", t:"single", cn:"RRP", sys:"NEURO", topic:"Increased intracranial pressure", d:3, b:0.5, cj:"analyze", tags:["icp","neuro","positioning"],
 stem:"A client with a closed head injury has an intracranial pressure of 24 mm Hg. Which nursing intervention is most appropriate?",
 opts:["Elevate the head of the bed to 30 degrees and keep the neck midline",
  "Position the client flat to maximize cerebral perfusion",
  "Suction the airway for thirty seconds at a time as needed",
  "Cluster all care into a single hour to allow uninterrupted rest"],
 ans:0,
 rat:{c:"Normal intracranial pressure is 5 to 15 mm Hg. Head elevation to 30 degrees with the neck midline promotes venous drainage from the brain and lowers pressure without compromising perfusion. Prolonged suctioning and flat positioning both raise pressure.",
  o:["Correct — head-of-bed elevation with a neutral neck aids venous return.",
    "Flat positioning impairs venous drainage and raises pressure.",
    "Suctioning longer than ten seconds raises intrathoracic and intracranial pressure.",
    "Clustering care causes sustained stimulation and pressure spikes."],
  s:"ICP care: head up 30, neck straight, preoxygenate before brief suction, space out stimulation."},
 ref:"Neurologic care · intracranial pressure management"},

{id:"RRP-046", t:"single", cn:"RRP", sys:"MSK", topic:"Compartment syndrome recognition", d:3, b:0.6, cj:"recognize", tags:["compartment-syndrome","cast","orthopedic"],
 stem:"Six hours after a tibial fracture was casted, a client reports severe pain that is unrelieved by the prescribed opioid and worsens when the nurse passively stretches the toes. Which finding is most concerning?",
 opts:["Pain out of proportion to the injury and with passive stretch",
  "Swelling visible at the proximal edge of the cast",
  "Capillary refill of two seconds in the affected toes",
  "A reported tingling sensation that resolves on repositioning"],
 ans:0,
 rat:{c:"Pain disproportionate to the injury, escalating despite analgesia, and intensified by passive stretch is the earliest and most reliable indicator of compartment syndrome. It precedes pulselessness, which is a late sign.",
  o:["Correct — disproportionate pain with passive stretch is the earliest sign.",
    "Some swelling at a cast edge is expected after a fresh fracture.",
    "Two-second capillary refill is normal and reassuring.",
    "Transient tingling relieved by repositioning suggests pressure, not ischemia."],
  s:"The five P's come late. Disproportionate pain plus pain on passive stretch comes first."},
 ref:"Musculoskeletal trauma · compartment syndrome"},

/* ── Safety & Infection Control (blueprint 13%) ────────────────────── */
{id:"SIC-040", t:"single", cn:"SIC", sys:"INF", topic:"Clostridioides difficile precautions", d:1, b:-0.15, cj:"act", tags:["cdiff","contact-precautions","hand-hygiene"],
 stem:"A nurse prepares to provide care for a client with Clostridioides difficile infection. Which action is essential?",
 opts:["Wash hands with soap and water rather than alcohol-based rub",
  "Wear a fit-tested N95 respirator for the entire shift",
  "Place the client in a negative-pressure isolation room",
  "Use sterile gloves for all contact with the client"],
 ans:0,
 rat:{c:"C. difficile forms spores that alcohol does not kill. Mechanical removal with soap and running water is required after glove removal. Contact precautions with gown and gloves apply, but airborne precautions do not.",
  o:["Correct — soap and water physically remove alcohol-resistant spores.",
    "N95 respirators are for airborne pathogens such as tuberculosis.",
    "Negative-pressure rooms are used for airborne isolation.",
    "Clean gloves suffice; sterility is not required for routine care."],
  s:"Spores beat alcohol: C. diff and norovirus need soap and water."},
 ref:"Infection control · contact precautions"},

{id:"SIC-041", t:"single", cn:"SIC", sys:"RESP", topic:"Airborne precautions", d:2, b:0.1, cj:"act", tags:["tuberculosis","airborne","ppe"],
 stem:"A client is admitted with suspected active pulmonary tuberculosis. Which assignment and precaution set is correct?",
 opts:["Negative-pressure room with a fit-tested N95 respirator for staff",
  "Private room with a surgical mask worn by the nurse at all times",
  "Cohort room with another client who has a chronic cough",
  "Standard precautions alone because the diagnosis is unconfirmed"],
 ans:0,
 rat:{c:"Suspected active tuberculosis requires airborne precautions: a negative-pressure room, a fit-tested N95 or higher respirator, and a mask on the client during transport. Waiting for confirmation leaves staff exposed.",
  o:["Correct — airborne precautions apply from suspicion onward.",
    "A surgical mask does not filter droplet nuclei for the wearer.",
    "Cohorting unconfirmed cases risks cross-infection.",
    "Standard precautions alone are insufficient for suspected tuberculosis."],
  s:"Airborne = negative pressure + N95. TB, measles, varicella, and aerosolized procedures."},
 ref:"Infection control · airborne isolation"},

{id:"SIC-042", t:"single", cn:"SIC", sys:"HEME", topic:"Neutropenic precautions", d:2, b:0.3, cj:"generate", tags:["neutropenia","protective-environment","oncology"],
 stem:"A client undergoing chemotherapy has an absolute neutrophil count of 350 per microliter. Which intervention should the nurse include in the plan of care?",
 opts:["Remove fresh flowers and standing water from the client's room",
  "Encourage visitors to bring fresh fruit from home",
  "Assign the client to a room with another febrile patient",
  "Delay all temperature measurements until the count recovers"],
 ans:0,
 rat:{c:"Severe neutropenia below 500 per microliter puts the client at high infection risk. Fresh flowers, standing water, and raw produce carry fungi and bacteria, so they are excluded from the protective environment.",
  o:["Correct — plants and standing water harbor Aspergillus and gram-negative organisms.",
    "Unwashed raw fruit introduces bacteria and fungi.",
    "Pairing a neutropenic client with a febrile patient invites transmission.",
    "Temperature is the earliest sign of neutropenic sepsis and must be monitored."],
  s:"Neutropenic = protective environment. No plants, no raw food, no rectal temperatures."},
 ref:"Oncology nursing · protective environment"},

{id:"SIC-043", t:"single", cn:"SIC", sys:"NEURO", topic:"Needlestick exposure", d:1, b:-0.2, cj:"act", tags:["needlestick","occupational-exposure","bloodborne"],
 stem:"A nurse sustains a percutaneous injury from a used hollow-bore needle. Which action should the nurse take first?",
 opts:["Wash the site with soap and water, then report the exposure immediately",
  "Complete the shift and report the injury at the end of the day",
  "Squeeze the wound firmly to expel contaminated blood before washing",
  "Wait for the source client's results before taking any action"],
 ans:0,
 rat:{c:"Immediate washing reduces inoculum, and prompt reporting starts the exposure protocol. Post-exposure prophylaxis for HIV is most effective within two hours, so any delay reduces benefit.",
  o:["Correct — wash first, then report without delay.",
    "Delayed reporting can push past the window for effective prophylaxis.",
    "Squeezing or milking the wound can increase tissue trauma and uptake.",
    "Baseline testing and prophylaxis decisions begin before source results return."],
  s:"Sharps injury: wash, report, evaluate — prophylaxis works best within two hours."},
 ref:"Occupational health · bloodborne pathogen exposure"},

{id:"SIC-044", t:"single", cn:"SIC", sys:"INF", topic:"Surgical asepsis breach", d:2, b:0.25, cj:"evaluate", tags:["sterile-field","asepsis","perioperative"],
 stem:"While maintaining a sterile field for a dressing change, the nurse observes that a colleague has reached across the field and the wrapper edge has become moist. Which interpretation is correct?",
 opts:["The field is contaminated and must be discarded and rebuilt",
  "Only the moist corner is contaminated and may be folded under",
  "The field stays sterile because the nurse wore sterile gloves",
  "The field remains usable as long as nothing touches its center"],
 ans:0,
 rat:{c:"Moisture wicks microorganisms through the barrier by capillary action, and reaching across a field sheds particles into it. Once contamination is suspected, the whole field is considered unsterile.",
  o:["Correct — a moist or crossed field is no longer sterile.",
    "Folding a contaminated edge does not restore sterility.",
    "Gloves protect the client from the nurse, not the field from the environment.",
    "Contamination is not confined to the point of contact."],
  s:"Sterile field rules: never reach across, keep it dry, one inch border is unsterile, and doubt means discard."},
 ref:"Aseptic technique · sterile field integrity"},

{id:"SIC-045", t:"single", cn:"SIC", sys:"MSK", topic:"Restraint safety", d:2, b:0.2, cj:"evaluate", tags:["restraints","safety","monitoring"],
 stem:"A client in soft wrist restraints for agitation is being monitored. Which finding requires the nurse to act immediately?",
 opts:["Cool, pale fingers with a capillary refill of five seconds",
  "The client verbalizing anger about being restrained",
  "Two fingers fitting snugly between the restraint and the skin",
  "The restraint secured to the bed frame rather than the side rail"],
 ans:0,
 rat:{c:"Delayed capillary refill with cool, pale digits indicates compromised circulation distal to the restraint and requires immediate release and reassessment. Anger is expected, two-finger slack is correct fit, and anchoring to the frame is proper practice.",
  o:["Correct — impaired perfusion distal to a restraint is an emergency.",
    "Anger is an expected response and not a circulatory emergency.",
    "Two-finger slack is the recommended fit and prevents injury.",
    "Attachment to the movable frame allows quick release and is correct."],
  s:"Restraint checks every 15 minutes: circulation, motion, sensation, and a documented offer to release."},
 ref:"Client safety · restraint monitoring"}
);
