/* RN Ready — item bank v3g · part 7 (bank growth toward the 2026 blueprints).
   Proportions at 187 already track both plans, so this batch keeps the balance
   (MOC +5 · SIC +6 · HPM +5 · PSY +3 · BCC +2 · PHA +4 · RRP +3 · PAA +3)
   while deliberately widening FORMAT coverage: matrix ×2, multi ×2,
   cloze, drag, hotspot (single remains 155/187 — too dominant).
   Two new variant groups: falls-risk (with SIC-019) and a third dka member.  */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Management of Care / Coordinated Care ───────────────────────── */
{id:"MOC-036", t:"single", cn:"MOC", sys:"INF", topic:"Disaster triage", d:2, b:0.4, cj:"prioritize", tags:["disaster","triage","emergency-preparedness"],
 stem:"During a mass casualty incident, the nurse is assigned to field triage using START. Which client is tagged IMMEDIATE (red)?",
 opts:["A client with a respiratory rate of 32 after a head injury, who follows commands",
  "A client walking around asking for help with a bleeding forearm",
  "A client unresponsive with no spontaneous respirations after airway positioning",
  "A client with a fractured ankle and distal pulses, rate 18, walking delayed"],
 ans:0,
 rat:{c:"START: respirations over 30 after positioning, or inability to follow commands, marks IMMEDIATE — treatable, life-threatened, likely survivable with quick care. Ambulatory wounds are GREEN (delayed); apneic-after-airway is BLACK (expectant); stable limping fractures are delayed.",
  o:["Correct — RR >30 + follows commands = RED under START.",
     "Ambulating wounded clients are tagged GREEN (minor/delayed).",
     "No respirations after airway repositioning is the BLACK (expectant) tag.",
     "Ambulatory-capable, stable vitals = delayed category, not red."],
  s:"START ladder in 60 seconds: walk? (green) → breathe >30 or no command-following? (red) → no breath after airway? (black) → the rest delayed."},
 ref:"Emergency preparedness · START triage"},

{id:"MOC-037", t:"matrix", cn:"MOC", sys:"NEURO", topic:"Ethical principles", d:2, b:0.35, cj:"analyze", tags:["ethics","principles"],
 stem:"Match each nursing situation to the ethical principle it most directly demonstrates. Select one cell per row.",
 matrix:{ mode:"radio", cols:["Autonomy","Beneficence","Justice","Nonmaleficence"],
   rows:[
     "Honoring a competent client's decision to refuse a blood transfusion",
     "Assigning the single negative-pressure room to the client with active pulmonary tuberculosis",
     "Double-checking a high-alert medication dose with a second nurse",
     "Supporting a client's choice to try acupuncture alongside prescribed therapy"],
   ans:[0,2,3,0]},
 rat:{c:"Autonomy = honoring the client's informed choices (refusal, complementary therapy). Justice = fair resource distribution (the isolation room to the most contagious). Nonmaleficence = preventing harm (double-checks). Beneficence = actively promoting good.",
  s:"Sort ethics by object: choices belong to autonomy, fairness of resources to justice, harm-prevention to nonmaleficence, active good to beneficence."},
 ref:"Ethical principles · applied matrix"},

{id:"MOC-038", t:"single", cn:"MOC", sys:"CV", topic:"Right of refusal", d:1, b:-0.1, cj:"act", tags:["ethics","refusal","autonomy"],
 stem:"A competent adult client refuses a prescribed statin, stating, “The muscle pain wasn't worth it.” What is the nurse's appropriate action?",
 opts:["Document the refusal, inform the provider, and explore the client's concerns",
  "Persuade the client that the medication is essential for survival",
  "Crush the dose into the evening meal to ensure compliance",
  "Withhold further discussion to respect the decision"],
 ans:0,
 rat:{c:"A competent client may refuse any treatment. The nurse documents, notifies the prescriber (options may exist — a different statin, dosing change), and keeps the conversation open. Covert administration is battery; browbeating and silence both fail the teaching duty.",
  o:["Correct — document, notify, and keep exploring: there may be a tolerable alternative.",
     "Exaggerating necessity disrespects autonomy and distorts informed choice.",
     "Hiding medication in food is covert administration — legally battery.",
     "Respect includes offering information, not withdrawing."],
  s:"Refusal by a competent adult ends the dose, not the dialogue: document, notify, debrief, adjust."},
 ref:"Client rights · refusal of medication"},

{id:"MOC-039", t:"single", cn:"MOC", sys:"ENDO", topic:"Teaching / return demonstration", d:1, b:-0.15, cj:"generate", tags:["teaching","delegation","scope"],
 stem:"A newly diagnosed client with diabetes must learn insulin self-injection before discharge tomorrow. Which delegation is appropriate?",
 opts:["The RN teaches the injection and observes a return demonstration; the UAP may remind the client about practice times",
  "The UAP teaches injection using a printed handout while the RN supervises medication passes",
  "The LPN performs the initial teaching and the RN signs the education record",
  "The RN provides the handout and tells the client to ask the pharmacist"],
 ans:0,
 rat:{c:"First-time skill teaching and validation by return demonstration are RN responsibilities; a UAP may only reinforce scheduled reminders. LPNs reinforce (not initiate) teaching — having the LPN do initial teaching while the RN rubber-stamps the record inverts scope.",
  o:["Correct — RN teaches and validates; UAP reinforces timing only.",
     "Initial teaching is never a UAP task, handout or not.",
     "LPN-reinforce/RN-sign flips the legal responsibility for teaching.",
     "Deferring mandatory discharge education to pharmacy abandons it."],
  s:"First teaching and competency checks belong to the RN; reinforcement can be shared — signatures don't transfer responsibility."},
 ref:"Education · delegation boundaries"},

{id:"MOC-040", t:"drag", cn:"MOC", fam:"RN", sys:"INF", topic:"Chain of command", d:1, b:-0.05, cj:"generate", tags:["escalation","safety","communication"],
 stem:"A new nurse is worried about a client's subtle deterioration but the assigned provider has not responded to two pages. Order the escalation steps from first to last. Assign one step per position.",
 drag:{ targets:["1 — First","2","3","4 — Last"],
   opts:[
     "Reassess and document the client's exact findings and the pages sent",
     "Notify the charge nurse or unit supervisor with the documented concern",
     "Escalate to the on-call provider or house supervisor per chain of command",
     "File a safety event report if harm occurs or the system fails"],
   ans:[0,1,2,3]},
 rat:{c:"Escalation is sequential: solidify your data, engage the charge nurse, climb the chain of command, and use the event-reporting system for system failures. Skipping straight to reports or acting informally weakens both safety and documentation.",
  o:["Correct — facts and timestamps first.",
     "Correct — unit leadership engages next.",
     "Correct — formal chain-of-command escalation follows.",
     "Correct — reporting is the closing system step, not the opener."],
  s:"Escalate on a ladder: data → charge nurse → chain of command → event report. Each rung needs the documentation from the last."},
 ref:"Professional practice · chain of command"},

/* ── Safety & Infection Prevention ─────────────────────────────── */
{id:"SIC-023", t:"single", cn:"SIC", sys:"PSYCH", topic:"Restraint alternatives", d:1, b:-0.15, cj:"generate", tags:["restraints","safety","alternatives"],
 stem:"A confused client at risk for falls repeatedly approaches the nurses' station at night. Which measure should the nurse try BEFORE considering restraints?",
 opts:["Move the client closer to the nurses’ desk, use a familiar routine, and offer frequent toileting rounds",
  "Administer a PRN sedative to establish a night sleep pattern",
  "Ask a family member to hold the client's hand through the night",
  "Place the client in a room with the door closed to reduce stimulation"],
 ans:0,
 rat:{c:"Restraints are a last resort: proximity to staff, predictable routines, and scheduled toileting address most wandering and agitation. Sedation chemically restrains, holding hands all night is unsustainable, and a closed door hides the client from observation.",
  o:["Correct — proximity, routine, and toileting are the first-line alternatives.",
     "Sedation for convenience is a chemical restraint — same rules, more risks.",
     "Family as all-night observers is neither safe nor sustainable.",
     "Closing the door removes the staff's line of sight — the opposite of safety."],
  s:"Before any restraint: reposition, reorient, routinize, toilet. Confusion is usually unmet need in disguise."},
 ref:"Restraints · least-restrictive alternatives"},

{id:"SIC-024", t:"single", cn:"SIC", sys:"MSK", topic:"Fall prevention", d:1, b:-0.2, cj:"act", tags:["falls","home-safety"], variantGroup:"falls-risk",
 stem:"A home health nurse is assessing a 78-year-old's apartment for fall hazards. Which observation is the highest priority to address today?",
 opts:["A scatter rug without backing at the foot of the bed",
  "A night-light rated for a warm bulb in the hallway",
  "A grab bar mounted beside the tub at a slight angle",
  "Frequently used dishes stored on the second shelf"],
 ans:0,
 rat:{c:"Loose scatter rugs are among the most common and most fixable household fall triggers — first-step-out-of-bed is a peak fall moment. A working night-light is protective; a slightly angled grab bar still functions but should be re-leveled; shelf placement is ergonomic, not urgent.",
  o:["Correct — loose rugs by the bed cause the classic night-time fall; remove it today.",
     "A lit hallway at night REDUCES falls — keep it.",
     "Worth fixing, but it still provides grip — lower priority than the rug.",
     "Reaching is a strain concern, not an urgent fall hazard."],
  s:"Home fall hazards: hunt loose rugs first, then lighting, then rails — the bedroom-to-bathroom path is the fall highway (variant presentation)."},
 ref:"Home safety assessment · fall hazards (variant)"},

{id:"SIC-025", t:"single", cn:"SIC", sys:"INF", topic:"Sharps safety", d:1, b:-0.25, cj:"act", tags:["sharps","bloodborne","prevention"],
 stem:"Which practice best prevents needlestick injuries during medication administration?",
 opts:["Activate the safety device and dispose of the sharp in the room's puncture-proof container as one motion",
  "Recap the needle using a one-handed scoop before walking to the sharps container",
  "Carry used syringes to the medication room's central sharps bin",
  "Detach the needle and discard the syringe in the regular trash"],
 ans:0,
 rat:{c:"One-motion disposal at the point of use — safety device engaged, straight into the room container — eliminates the handling steps where sticks happen. Two-handed recapping is prohibited; transporting exposed sharrs multiplies exposure; trash disposal is a hazard to everyone downstream.",
  o:["Correct — activate and dispose immediately at the point of use.",
     "Recapping (even scooped) is reserved for rare exceptions — never routine practice.",
     "Carrying exposed sharps creates hallway exposure risk.",
     "Syringes never go in regular trash — injury and contamination risk."],
  s:"Sharps rule: activate the safety device and dispose in the SAME motion, in the SAME room. Hands off, caps off."},
 ref:"Sharps injury prevention"},

{id:"SIC-026", t:"single", cn:"SIC", sys:"RESP", topic:"Home oxygen safety", d:1, b:-0.2, cj:"act", tags:["oxygen","home-care","safety"],
 stem:"The nurse is teaching a client going home on 2 L/min nasal oxygen. Which instruction is essential?",
 opts:["Do not smoke or allow open flames within 10 feet (3 m) of the tubing; use water-based moisturizer only",
  "Use oil-based petroleum jelly liberally around the nostrils for dryness",
  "Keep the concentrator in a closed closet to reduce noise",
  "Increase the flow to 4 L/min whenever shortness of breath worsens"],
 ans:0,
 rat:{c:"Oxygen concentrates fire: no smoking/flames near the flow, and only water-based products near the mask (petroleum is flammable). Enclosed spaces overheat concentrators; clients never self-adjust prescribed flows.",
  o:["Correct — flame distance plus water-based lubricants are the core teaching.",
     "Petroleum jelly near oxygen is a fire hazard — water-based only.",
     "Concentrators need ventilated space; closets cause overheating.",
     "Self-titrating flow is unsafe — worsening dyspnea is a call-the-clinic event."],
  s:"Home O₂ teaching: distance the flames, water-based only, ventilate the machine, never touch the dial."},
 ref:"Home oxygen · fire safety"},

{id:"SIC-027", t:"hotspot", cn:"SIC", sys:"CV", topic:"Deterioration / when to escalate", d:2, b:0.3, cj:"evaluate", tags:["deterioration","escalation","monitoring"],
 stem:"The nurse is reviewing the morning assessment of a client 2 days after a hip replacement. Select every finding that requires immediate provider notification.",
 hotspot:{ mode:"rows",
   rows:[
     "Sudden onset of dyspnea with a respiratory rate of 30/min",
     "Incisional pain rated 4/10 with movement",
     "Unilateral left calf tenderness and swelling",
     "Temperature 99.0 °F (37.2 °C) on the second post-op day",
     "Heart rate 118/min with a blood pressure of 96/54 mm Hg",
     "Passing flatus and tolerating a soft diet"],
   ans:[0,2,4]},
 rat:{c:"Dyspnea + tachypnea (possible PE), unilateral calf findings (possible DVT), and tachycardia with hypotension (hemorrhage or sepsis) are red-flag post-op patterns. Moderate incisional pain, borderline low-grade temperature, and returning bowel function are expected postoperative courses.",
  s:"Post-op day 2 scan: anything airway, clot, or circulation — PE, DVT, shock physiology — is a now-call; pain and low-grade temp are managed on rounds."},
 ref:"Postoperative deterioration · escalation triggers"},

{id:"SIC-028", t:"single", cn:"SIC", sys:"INF", topic:"PPE sequence", d:1, b:-0.1, cj:"act", tags:["ppe","isolation","standard-precautions"],
 stem:"A nurse is leaving the room of a client on contact precautions after completing care. What is the correct order of removal?",
 opts:["Gloves → gown → perform hand hygiene",
  "Gown → gloves → perform hand hygiene",
  "Gloves → gown → new gloves → hand hygiene",
  "Gown and gloves simultaneously → hand hygiene"],
 ans:0,
 rat:{c:"Gloves are the most contaminated item and come off first, then the gown (front and sleeves contaminated), rolled away from the body, then hand hygiene — always last and always performed.",
  o:["Correct — dirtiest first: gloves, then gown, then wash.",
     "Removing the gown over contaminated gloves exposes the uniform.",
     "Donning fresh gloves mid-removal adds a contaminated surface — not a step.",
     "Simultaneous removal invites self-contamination of hands and clothing."],
  s:"Doffing logic: most-contaminated off first, hands last and loudest — glove, gown, wash."},
 ref:"PPE · doffing sequence"},

/* ── Health Promotion & Maintenance ────────────────────────────── */
{id:"HPM-016", t:"single", cn:"HPM", sys:"MSK", topic:"Osteoporosis prevention", d:1, b:-0.2, cj:"generate", tags:["osteoporosis","prevention","teaching"],
 stem:"A 58-year-old postmenopausal client asks how to protect bone health. Which teaching is most appropriate?",
 opts:["Weight-bearing exercise most days plus calcium and vitamin D intake aligned with recommended amounts",
  "Bed rest to spare the vertebrae from compression stress",
  "Daily high-impact jumping exercises regardless of joint status",
  "Calcium supplements alone — exercise does not affect bone density"],
 ans:0,
 rat:{c:"Bone responds to load: regular weight-bearing activity plus adequate calcium and vitamin D (with smoking cessation) is the preventive core. Immobilization ACCELERATES loss; high-impact loading can fracture fragile bone; supplements without loading stimulus underperform.",
  o:["Correct — load the bones and feed the remodeling: exercise + calcium + vitamin D.",
     "Disuse accelerates bone loss — the opposite of prevention.",
     "High-impact loading of osteoporotic bone risks fracture; walking/resistance is safer.",
     "Mechanical loading is half the physiology — supplements alone don't hold bone."],
  s:"Bone = bank account: deposit with calcium/vitamin D, and spend wisely with weight-bearing — rest withdrawals bone."},
 ref:"Osteoporosis · primary prevention"},

{id:"HPM-017", t:"single", cn:"HPM", sys:"NEURO", topic:"Infant safe sleep", d:0, b:-0.35, cj:"act", tags:["infant","safety","teaching"],
 stem:"A new parent asks about sleep arrangements for their 2-month-old. Which guidance follows safe-sleep recommendations?",
 opts:["Place the baby on the back, on a firm mattress, with no pillows, blankets, or bumpers in the crib",
  "Place the baby on the stomach once they can lift the head during waking hours",
  "Keep a soft blanket and small pillow for warmth and head shaping",
  "Share the parents' bed for easier night feeding"],
 ans:0,
 rat:{c:"Back-to-sleep on a firm bare surface in the parents' room (separate surface) is the standard through the first year. Stomach positioning, soft bedding, and bed-sharing are the major modifiable SIDS/suffocation risks.",
  o:["Correct — supine, firm, bare crib; room-share, not bed-share.",
     "Head-lifting ability does not license prone sleep at 2 months.",
     "Soft bedding is a suffocation hazard regardless of head-shaping intent.",
     "Bed-sharing raises overlay and suffocation risk — a separate surface is recommended."],
  s:"Safe sleep = A-B-C alone, on the Back, in a Crib — bare, firm, nearby."},
 ref:"Infant safety · SIDS risk reduction"},

{id:"HPM-018", t:"single", cn:"HPM", sys:"INF", topic:"Immunization schedule", d:1, b:-0.1, cj:"recognize", tags:["immunization","infant"],
 stem:"At the 2-month well-child visit, which vaccine combination is scheduled per the routine infant immunization timeline?",
 opts:["DTaP, IPV, Hib, PCV, RV, and hepatitis B (if not completed at birth)",
  "MMR and varicella only",
  "Annual influenza vaccine only",
  "DTaP booster and human papillomavirus series"],
 ans:0,
 rat:{c:"The 2-month set is DTaP, IPV, Hib, PCV, rotavirus, plus hepatitis B catch-up if needed. MMR and varicella begin at 12 months; HPV starts at age 9; influenza is annual from 6 months.",
  o:["Correct — that is the classic 2-month platform.",
     "MMR/varicella are 12-month vaccines.",
     "Influenza starts at 6 months, and never 'only' at 2 months.",
     "HPV is an adolescent series — not infant care."],
  s:"Anchor the 2-month visit: DTaP-IPV-Hib-PCV-RV (± HepB). MMR waits for the first birthday."},
 ref:"Immunization schedule · infant series"},

{id:"HPM-019", t:"single", cn:"HPM", sys:"REPI", topic:"STI screening", d:1, b:-0.15, cj:"recognize", tags:["screening","sti","prevention"],
 stem:"Which screening recommendation for sexually transmitted infections is accurate?",
 opts:["All sexually active women 25 and younger are screened for chlamydia and gonorrhea at least annually",
  "Chlamydia screening is only needed when symptoms are present",
  "Syphilis screening is limited to clients over age 65",
  "HIV screening is performed once at 18 and never repeated for anyone who is sexually active"],
 ans:0,
 rat:{c:"Annual chlamydia/gonorrhea screening for sexually active women ≤25 (and older women with risk factors) is standard, since most infections are asymptomatic. Syphilis screening targets pregnancy and risk groups; HIV is screened at least once for adults 13–64 and repeated with ongoing risk.",
  o:["Correct — young women are the highest-prevalence asymptomatic group.",
     "Waiting for symptoms misses the majority of infections.",
     "Syphilis screening follows pregnancy/risk, not age 65+.",
     "HIV repeats with risk exposure and per guideline intervals — not a one-time event."],
  s:"Screen where the disease hides: young + asymptomatic = annual chlamydia/gonorrhea testing."},
 ref:"STI screening guidelines"},

{id:"HPM-020", t:"single", cn:"HPM", sys:"NEURO", topic:"Early detection / self-awareness", d:1, b:-0.2, cj:"generate", tags:["screening","self-exam","teaching"],
 stem:"A 24-year-old asks about testicular cancer screening. Which teaching is accurate?",
 opts:["A monthly self-examination after a warm shower, with prompt reporting of any painless lump, fits men 15–35",
  "Testicular self-examination should begin at age 50",
  "Any lump found is nearly always cancerous and needs emergency care",
  "Screening is unnecessary if there is no family history"],
 ans:0,
 rat:{c:"Testicular cancer peaks in 15–35-year-olds; monthly self-awareness checks after a warm shower (when the scrotum is relaxed), reporting painless lumps promptly, is the accepted teaching. Most lumps are NOT cancer — but all need evaluation; family history absence doesn't remove risk.",
  o:["Correct — right age window, right technique, right escalation.",
     "Age 50 is prostate-screening thinking — testicular cancer is a young man's disease.",
     "Most lumps are benign — urgency without catastrophizing.",
     "Most cases have no family history — screening awareness still applies."],
  s:"Testicular cancer teaches to the young: warm shower, monthly feel, painless lump = same-week visit, not same-hour panic."},
 ref:"Cancer awareness · testicular self-examination"},

/* ── Psychosocial Integrity ────────────────────────────────────── */
{id:"PSY-018", t:"single", cn:"PSY", sys:"PSYCH", topic:"Anxiety / panic", d:1, b:-0.1, cj:"act", tags:["anxiety","panic","therapeutic-communication"],
 stem:"A client in a clinic waiting room begins a panic attack — rapid breathing, trembling, and a sense of impending doom. What is the nurse's first intervention?",
 opts:["Stay with the client and coach slow breathing: “Breathe in with me… now out slowly.”",
  "Leave to fetch the crisis team while the client waits alone",
  "Encourage rapid breathing into a paper bag to expel excess air",
  "Ask rapid factual questions to redirect the thoughts"],
 ans:0,
 rat:{c:"Presence plus paced breathing coaching is the first-line response — panic peaks and recedes, and a calm model regulates it. Leaving removes the anchor; paper-bag rebreathing is outdated and risky; interrogation adds stimulation.",
  o:["Correct — stay, model, pace the breath.",
     "Abandoning a panicking client mid-attack is unsafe.",
     "Paper bags are no longer recommended — CO₂ rebreathing has complications and the technique dignifies the panic.",
     "Rapid questioning escalates stimulation."],
  s:"Panic first aid = presence + paced breathing. You are the metronome; everything else waits."},
 ref:"Anxiety disorders · panic response"},

{id:"PSY-019", t:"multi", cn:"PSY", sys:"GI", topic:"Eating disorders", d:2, b:0.35, cj:"recognize", tags:["eating-disorders","assessment"],
 stem:"Which assessment findings suggest anorexia nervosa rather than simple dieting? Select all that apply.",
 opts:["Serum potassium of 3.0 mEq/L with occasional skipped beats",
  "Fine downy hair growth on the arms and back",
  "A stated goal of losing 5 kg before a wedding",
  "Amenorrhea for the past 4 months",
  "BMI 16.1 with a persistent belief of being overweight",
  "Eating three meals daily with occasional snacks"],
 ans:[0,1,3,4],
 rat:{c:"Hypokalemia with dysrhythmia risk, lanugo, amenorrhea, and severely low BMI paired with distorted body image are physiologic and psychologic markers of anorexia nervosa. A defined event goal and normal meal patterns describe ordinary dieting.",
  o:["Correct — electrolyte depletion from purging/restriction is a red flag.",
     "Correct — lanugo is the body's insulation response to extreme low fat.",
     "A time-boxed cosmetic goal alone is dieting behavior.",
     "Correct — hormonal shutdown from malnutrition.",
     "Correct — BMI 16 with body-image distortion is the anorexia signature.",
     "Regular eating patterns argue against restrictive disease."],
  s:"Anorexia = body failing (K⁺, lanugo, amenorrhea, BMI) + mind fixed (feels fat at 16). Dieting keeps neither."},
 ref:"Eating disorders · distinguishing findings"},

{id:"PSY-020", t:"single", cn:"PSY", sys:"PSYCH", topic:"Substance use screening", d:1, b:-0.1, cj:"act", tags:["substance-use","screening","brief-intervention"],
 stem:"During a routine visit, a client reports drinking “four or five drinks most nights.” What is the nurse's most appropriate first response?",
 opts:["Use a validated screening tool (e.g., AUDIT-C), give brief nonjudgmental feedback, and explore the client's own view",
  "Advise the client they are an alcoholic and must stop immediately",
  "Refer to an inpatient rehabilitation program today",
  "Document the report and address it only if the client raises it again"],
 ans:0,
 rat:{c:"Screening + brief intervention is the evidence-based sequence: validated tool, feedback framed to readiness, and the client's own perspective invited. Labeling, immediate rehab referral, and passive documentation all skip the brief-intervention step that actually changes behavior.",
  o:["Correct — screen, feedback, explore: SBIRT's first three beats.",
     "Labels provoke defensiveness and are clinically wrong at this stage.",
     "Inpatient referral is for severe dependence after proper assessment.",
     "Passive documentation ignores a teachable health moment."],
  s:"Meet alcohol disclosure with SBIRT rhythm: Screen, Brief feedback, explore Readiness — save referrals for assessment-confirmed dependence."},
 ref:"Substance use · screening and brief intervention"},

/* ── Basic Care & Comfort ──────────────────────────────────────── */
{id:"BCC-019", t:"single", cn:"BCC", sys:"REN", topic:"Hydration / aging", d:1, b:-0.15, cj:"evaluate", tags:["hydration","older-adult"],
 stem:"Which client is at greatest risk for dehydration?",
 opts:["An 86-year-old on a diuretic who has a diminished sense of thirst and needs help to the bathroom",
  "A 40-year-old who drinks 2 liters of water daily and exercises three times weekly",
  "A 55-year-old with type 2 diabetes controlled by diet alone",
  "A 30-year-old breastfeeding parent drinking to thirst"],
 ans:0,
 rat:{c:"Older adults have blunted thirst, lower water reserve, and here a diuretic plus deliberate fluid restriction to avoid bathroom trips — the classic dehydration stack. The others maintain adequate intake.",
  o:["Correct — age + diuretic + blunted thirst + toileting avoidance compounds fast.",
     "Adequate intake with routine exercise maintains hydration.",
     "Diet-controlled diabetes without osmotic symptoms is not a primary dehydration risk.",
     "Drinking to thirst meets lactation demands."],
  s:"Dehydration math in elders: thirst fades, reserves shrink, diuretics drain, and dignity limits drinking — offer fluids on a schedule."},
 ref:"Older adults · dehydration risk"},

{id:"BCC-020", t:"single", cn:"BCC", sys:"GI", topic:"Constipation management", d:1, b:-0.2, cj:"act", tags:["bowel","opioids","comfort"],
 stem:"A client on scheduled opioids for chronic back pain reports new constipation. Which measure is most appropriate to implement first?",
 opts:["Start a preventive bowel regimen: increased fluids, fiber, and activity, with a stimulant laxative as ordered",
  "Advise holding all opioid doses until bowel function normalizes",
  "Recommend a bulk-forming laxative alone, taken once daily",
  "Suggest delaying treatment until impaction is confirmed"],
 ans:0,
 rat:{c:"Opioid-induced constipation is anticipated, not reactive: prophylactic scheduled regimens (fluid/fiber/activity plus a stimulant, often with a softener) start WITH the opioid. Bulk agents alone can worsen obstruction-pattern constipation without peristalsis support; stopping analgesia and waiting for impaction are both harmful.",
  o:["Correct — scheduled prevention from day one of opioid therapy.",
     "Withdrawing needed analgesia trades pain for complications.",
     "Bulk fiber without motility support can compound the blockage.",
     "Waiting for impaction inverts prevention."],
  s:"Opioids and bowels: the rule is scheduled and ahead — never wait for the impaction."},
 ref:"Opioid-induced constipation · bowel regimen"},

/* ── Pharmacological Therapies ─────────────────────────────────── */
{id:"PHA-041", t:"single", cn:"PHA", sys:"CV", topic:"Beta blockers", d:1, b:-0.1, cj:"evaluate", tags:["beta-blocker","hold-parameters"],
 stem:"Before administering the morning metoprolol, the nurse finds the apical pulse is 54/min and the client reports feeling dizzy on standing. What is the nurse's best action?",
 opts:["Hold the dose and notify the provider of the rate and symptoms",
  "Administer the dose — 54/min is within normal range",
  "Administer half the dose and recheck the pulse in an hour",
  "Give the dose with food to slow absorption"],
 ans:0,
 rat:{c:"Symptomatic bradycardia (dizziness) at 54/min meets typical hold criteria (commonly <60 with symptoms, per order); the nurse holds and notifies. Splitting doses or masking with food is improvisation outside the order.",
  o:["Correct — symptoms plus rate below the usual threshold: hold and call.",
     "54 is below typical beta-blocker hold parameters, and dizziness makes it urgent.",
     "Nurses do not titrate prescribed doses independently.",
     "Food timing does not address bradycardia."],
  s:"Beta-blocker pre-checks are binary: rate below the ordered floor OR symptomatic → hold and notify. Never split, never sneak it in."},
 ref:"Beta blockers · hold parameters"},

{id:"PHA-042", t:"single", cn:"PHA", sys:"CV", topic:"Calcium channel blockers", d:1, b:-0.15, cj:"recognize", tags:["ccb","side-effects","teaching"],
 stem:"A client started on amlodipine 3 weeks ago reports new ankle swelling without pain or redness. What is the nurse's best interpretation?",
 opts:["A known dose-related effect of dihydropyridine calcium channel blockers — report for dose review; elevate the feet meanwhile",
  "A sign of heart failure that requires an urgent echocardiogram",
  "An allergic reaction requiring immediate drug discontinuation",
  "Unrelated to the medication because amlodipine is a vasodilator"],
 ans:0,
 rat:{c:"Painless ankle edema is the signature adverse effect of amlodipine-type CCBs (precapillary vasodilation), not fluid overload — the fix is dose adjustment or class switch, with elevation for comfort. It is neither allergy nor automatically heart failure.",
  o:["Correct — recognize, report for dose review, elevate for comfort.",
     "Painless bilateral CCB edema is not an HF picture by itself.",
     "This is a pharmacologic effect, not allergy — no discontinuation emergency.",
     "The vasodilation mechanism is exactly the CAUSE — related, not exempt."],
  s:"Amlodipine ankles: bilateral, painless, pharmacologic — report for dose work, not a fluid-workup panic."},
 ref:"Calcium channel blockers · peripheral edema"},

{id:"PHA-043", t:"cloze", cn:"PHA", sys:"RESP", topic:"Inhaler technique", d:1, b:-0.05, cj:"generate", tags:["inhaler","asthma","teaching"],
 stem:"Complete the coaching sequence for a client's first albuterol metered-dose inhaler use.",
 cloze:{ lines:[
   {pre:"Before the first spray of a new canister or after a week unused, the client should ", post:".", opts:["prime the inhaler with test sprays","rinse the mouthpiece with hot water","shake it once and begin","store it in the freezer"], ans:0},
   {pre:"At the moment of actuation, the client should exhale fully, then ", post:".", opts:["inhale slowly and deeply while pressing the canister","breathe out again quickly","hold the inhaler 10 cm from the open mouth sideways","take four rapid shallow puffs"], ans:0},
   {pre:"After the dose, the client should ", post:" to reduce local effects.", opts:["rinse the mouth with water and spit","drink a full glass of juice","brush the teeth with toothpaste vigorously","lie flat for 10 minutes"], ans:0}]},
 rat:{c:"MDI sequence: prime new/unused canisters, exhale then inhale slowly and deeply with actuation, hold the breath, and rinse — for albuterol, rinsing limits irritation; for steroids it prevents thrush.",
  s:"MDI mantra: Prime → Exhale → slow deep inhale with press → hold → Rinse. Every skipped step wastes drug."},
 ref:"Inhaler technique · metered-dose inhalers"},

{id:"PHA-044", t:"single", cn:"PHA", sys:"GI", topic:"Pediatric medication safety", d:2, b:0.3, cj:"act", tags:["pediatrics","dosage","safety"],
 stem:"The provider orders an oral medication for a 9-kg toddler at 15 mg/kg/dose. The nurse calculates 135 mg. Which action is safest before administration?",
 opts:["Recheck the calculation against the ordered dose and the concentration, and validate with a second nurse if it is a high-alert drug",
  "Round 135 mg up to 140 mg for easier measurement",
  "Give 100 mg to stay safely below the maximum",
  "Ask the parent to confirm the usual home dose"],
 ans:0,
 rat:{c:"15 × 9 = 135 mg is correct math; safe administration still requires verifying the order, the product concentration, and drawn volume — with independent double-checks for high-alert drugs. Arbitrary rounding (up OR down) changes the prescribed dose, and parents don't verify orders.",
  o:["Correct — recalculate, match concentration to volume, double-check high-alert drugs.",
     "Rounding up doses without an order overdoses by convenience.",
     "Under-dosing 'to be safe' withholds therapy — also a medication error.",
     "Parent recall is not a verification source for a prescribed dose."],
  s:"Pediatric dosing: mg/kg math is step one, not the finish line — concentration, volume, and a second set of eyes close the loop."},
 ref:"Pediatric pharmacology · safe dosing"},

/* ── Reduction of Risk Potential ───────────────────────────────── */
{id:"RRP-029", t:"single", cn:"RRP", sys:"NEURO", topic:"Autonomic dysreflexia", d:2, b:0.5, cj:"act", tags:["spinal-cord-injury","emergency"],
 stem:"A client with a T6 spinal cord injury reports a pounding headache and blurred vision; the blood pressure is 190/104 mm Hg. What is the nurse's first action?",
 opts:["Sit the client upright and search for a noxious stimulus below the level of the lesion — most often bladder or bowel",
  "Administer the PRN antihypertensive immediately before any other assessment",
  "Lower the head of the bed flat to improve cerebral perfusion",
  "Notify the provider and wait for orders before intervening"],
 ans:0,
 rat:{c:"Autonomic dysreflexia above T6 is a bradycardic hypertensive emergency triggered by noxious stimuli — sit upright (drops pressure), then find and remove the cause (blocked catheter, impacted rectum). Antihypertensives follow positioning and stimulus removal; lying flat worsens the pressure.",
  o:["Correct — upright plus hunt the trigger: catheter, bowel, skin, clothing.",
     "Drugs come after positioning and cause-hunting.",
     "Flat positioning raises the hypertensive crisis — the reverse of correct.",
     "Waiting on orders while BP is 190/104 is not an option."],
  s:"T6+ headache + hypertension = autonomic dysreflexia: SIT UP, strip the trigger (bladder first), then meds."},
 ref:"Spinal cord injury · autonomic dysreflexia"},

{id:"RRP-030", t:"single", cn:"RRP", sys:"HEME", topic:"Sickle cell crisis", d:2, b:0.25, cj:"generate", tags:["sickle-cell","prevention","teaching"],
 stem:"Which teaching best reduces sickle cell crisis frequency for a client with sickle cell disease?",
 opts:["Drink plenty of fluids daily, avoid high altitudes and unpressurized flights, and treat infections early",
  "Take one aspirin daily to prevent crisis-triggering clots",
  "Limit fluids during pain episodes to reduce swelling",
  "Avoid all exercise to prevent oxygen demand increases"],
 ans:0,
 rat:{c:"Crisis prevention = avoid hypoxia, dehydration, and infection: hydration, altitude awareness, prompt infection care, and moderate activity. Aspirin doesn't prevent vaso-occlusion; restricting fluids worsens sickling; complete inactivity promotes stasis.",
  o:["Correct — hydration + oxygen-environment awareness + early infection treatment.",
     "Aspirin is not a crisis preventive.",
     "Dehydration is a crisis TRIGGER — fluids continue during episodes.",
     "Stasis from immobility promotes sickling; moderate activity is encouraged."],
  s:"Sickle cell triggers the triad: dry (dehydration), high (altitude), and germs (infection). Hydrate, stay low, treat early."},
 ref:"Sickle cell disease · crisis prevention"},

{id:"RRP-031", t:"matrix", cn:"RRP", sys:"CV", topic:"Postoperative findings", d:2, b:0.4, cj:"analyze", tags:["postoperative","assessment","escalation"],
 stem:"It is the first evening after an open cholecystectomy. Classify each finding as EXPECTED (needs routine care) or REPORT NOW (needs provider notification). Select one cell per row.",
 matrix:{ mode:"radio", cols:["Expected","Report now"],
   rows:[
     "Serous drainage on the dressing, 2 cm total",
     "Bright red drainage saturating the dressing hourly",
     "Temperature 99.4 °F (37.4 °C) this evening",
     "New abdominal distension with absent bowel sounds and vomiting",
     "Incisional pain 3/10 relieved by the ordered analgesic"],
   ans:[0,1,0,1,0]},
 rat:{c:"Expected early post-op: small serous drainage, low evening temperature, controlled pain. Report now: frank bleeding (hourly saturation) and a possible ileus/obstruction pattern (distension + absent bowel sounds + vomiting).",
  s:"Post-op grid: bleeding and bowel silence go up the chain; serous, sub-100 temps, and controlled pain stay on rounds."},
 ref:"Postoperative assessment · expected versus concerning"},

/* ── Physiological Adaptation ──────────────────────────────────── */
{id:"PAA-040", t:"single", cn:"PAA", sys:"ENDO", topic:"DKA", d:2, b:0.5, cj:"evaluate", tags:["dka","pediatrics","endocrine"], variantGroup:"dka",
 stem:"A 12-year-old with type 1 diabetes has had 3 days of thirst, frequent urination, and vomiting, and now breathes deeply and rapidly with a fruity odor. What does the nurse suspect and do first?",
 opts:["Diabetic ketoacidosis — obtain point-of-care glucose and ketones, and alert the provider",
  "Asthma exacerbation — apply oxygen and prepare a nebulizer",
  "Viral gastroenteritis — start oral rehydration at home",
  "Hypoglycemia — give 15 g of fast-acting carbohydrate"],
 ans:0,
 rat:{c:"Kussmaul respirations + fruity breath + dehydration in type 1 diabetes is DKA; confirmation (glucose, ketones) and provider notification start the fixed-rate insulin/fluid protocol. Asthma, gastroenteritis, and hypoglycemia treatments would each delay the correct path or worsen it.",
  o:["Correct — recognize DKA, confirm, escalate.",
     "Deep slow-effective breathing is metabolic, not wheezing — oxygen won't fix acidosis.",
     "Oral rehydration at home misses a ketoacidosis emergency.",
     "A sugar load into DKA worsens hyperglycemia."],
  s:"Type 1 + thirst + vomiting + Kussmaul/fruity breath = DKA until proven otherwise (variant presentation: pediatric)."},
 ref:"Diabetic ketoacidosis · pediatric presentation (variant)"},

{id:"PAA-041", t:"single", cn:"PAA", sys:"ENDO", topic:"Adrenal crisis", d:2, b:0.55, cj:"act", tags:["adrenal","endocrine","emergency"],
 stem:"A client with Addison disease on daily hydrocortisone develops sudden severe vomiting, abdominal pain, and hypotension after 2 days of influenza. What is the priority nursing action?",
 opts:["Administer stress-dose steroids per protocol and notify the provider immediately",
  "Encourage oral fluids and double the oral dose at home",
  "Administer the daily maintenance dose and recheck blood pressure in 2 hours",
  "Hold steroids to avoid worsening the infection"],
 ans:0,
 rat:{c:"Adrenal insufficiency plus stress (illness) risks adrenal crisis: vomiting, abdominal pain, hypotension. The lifesaving move is parenteral stress-dose glucocorticoids — oral dosing cannot be relied on with vomiting, and maintenance doses are insufficient under stress.",
  o:["Correct — stress dosing IS the emergency treatment; do not wait.",
     "Oral intake during vomiting fails; doubling oral doses is not crisis care.",
     "Maintenance dosing under-covers physiologic stress — the crisis progresses.",
     "Steroids are physiologic replacement — infection is not a reason to withhold them."],
  s:"Addison + illness + GI collapse = adrenal crisis: give stress-dose steroids NOW. Sick-day rules exist so patients never 'wait and see.'"},
 ref:"Adrenal insufficiency · crisis management"},

{id:"PAA-042", t:"single", cn:"PAA", sys:"ENDO", topic:"Thyroid storm", d:3, b:0.75, cj:"analyze", tags:["thyroid","endocrine","emergency"],
 stem:"A client with untreated hyperthyroidism arrives with a temperature of 39.5 °C (103.1 °F), heart rate 160/min, and marked agitation. Which interpretation and action are correct?",
 opts:["Thyroid storm — this is an endocrine emergency requiring immediate provider involvement and monitoring",
  "Expected thyrotoxicosis — schedule an outpatient endocrinology visit",
  "Simple heatstroke — move to a cool room and observe",
  "Thyroid storm — a routine presentation manageable with oral medication at home"],
 ans:0,
 rat:{c:"Extreme fever, severe tachycardia, and CNS agitation over hyperthyroidism define thyroid storm — a life-threatening emergency needing ICU-level care (beta blockade, thionamides, iodine, cooling, supportive care).",
  o:["Correct — storm recognition: fever + tachycardia + agitation = emergency escalation.",
     "Outpatient scheduling courts cardiac collapse.",
     "Heatstroke lacks the hyperthyroid context and would still be an emergency.",
     "Storm is never routine or home-managed."],
  s:"Untreated hyperthyroid + fever + heart racing + agitation = thyroid storm. Treat like sepsis: now, monitored, inpatient."},
 ref:"Thyroid emergencies · thyroid storm"}
);
