/* RN Ready — item bank v3p · part 12 (blueprint-gap wave 2).
   Recomputed against the live pool after wave 1: MOC carried the largest
   remaining deficit (16.7% against an 18% midpoint), then PAA (13.1% vs 14%)
   and HPM (8.5% vs 9%). This wave is weighted to close those three while
   leaving PHA, SIC, RRP, PSY and BCC alone, since wave 1 pushed them at or
   slightly above their midpoints already.

   Authoring rules applied to every item below:
     · one scenario, one decision, one defensible key
     · distractors are real misconceptions, not obviously wrong filler
     · no distinctive stem token is allowed to sit in the key option alone
       (itemlint's stem-cue gate caught exactly this error in wave 1)
     · option lengths kept even so the longest option is not always the key
     · full per-option rationales plus a strategy note                       */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Management of Care (blueprint 18%) ────────────────────────────── */
{id:"MOC-057", t:"single", cn:"MOC", sys:"INF", topic:"Advance directive conflict", d:2, b:0.2, cj:"prioritize", tags:["advance-directive","ethics","end-of-life"],
 stem:"An older adult with a documented advance directive declines mechanical ventilation. The adult child arrives and insists the nurse intubate the parent immediately. Which action should the nurse take?",
 opts:["Uphold the client's own stated wishes and support the child through it",
  "Follow the child's instructions because family holds decision authority",
  "Intubate first and resolve the disagreement with ethics afterward",
  "Ask the child to sign a release before any further discussion occurs"],
 ans:0,
 rat:{c:"A competent adult's documented advance directive governs care. An adult child cannot override the client's own expressed wishes, so the nurse upholds the directive while supporting the family through the conversation.",
  o:["Correct — the client's directive controls; support the family without overriding it.",
    "Family surrogates act only when the client cannot, and never against a directive.",
    "Intubating against a directive is battery, not a sequencing problem.",
    "A signed release does not transfer decision-making authority to the child."],
  s:"Advance directive beats family preference. Surrogates substitute judgment, they do not override it."},
 ref:"Ethical practice · advance directives"},

{id:"MOC-058", t:"single", cn:"MOC", sys:"INF", topic:"Informed consent and the nurse's role", d:1, b:-0.1, cj:"act", tags:["informed-consent","scope","legal"],
 stem:"A client scheduled for surgery tells the nurse, 'I signed the consent form, but I still don't understand what they are removing.' Which action should the nurse take?",
 opts:["Notify the surgeon and document that the client needs further explanation",
  "Explain the procedure in detail since the nurse has already assessed understanding",
  "Reassure the client that the surgeon will clarify everything on the morning of surgery",
  "Witness a second consent form to confirm the client's signature is valid"],
 ans:0,
 rat:{c:"Obtaining informed consent is the provider's responsibility. The nurse's role is to witness the signature, verify identity, and confirm the client is signing voluntarily. When understanding is absent, the nurse escalates to the provider rather than supplying the explanation.",
  o:["Correct — the provider must re-explain; the nurse escalates and documents.",
    "Providing the operative explanation is outside the nurse's consent role.",
    "Deferring to surgery morning risks the client being sedated before clarification.",
    "A second form does not cure a lack of understanding."],
  s:"Consent: the provider explains, the nurse witnesses. Doubt about understanding goes back to the provider."},
 ref:"Legal rights · informed consent"},

{id:"MOC-059", t:"single", cn:"MOC", sys:"INF", topic:"Delegation scope", d:2, b:0.15, cj:"prioritize", tags:["delegation","scope","uap"],
 stem:"Which task is appropriate for the registered nurse to delegate to unlicensed assistive personnel?",
 opts:["Assisting a stable client to ambulate in the hallway with a gait belt",
  "Assessing breath sounds on a client who reports new shortness of breath",
  "Teaching a newly diagnosed diabetic client how to draw up insulin",
  "Developing the plan of care for a client admitted this morning"],
 ans:0,
 rat:{c:"Unlicensed assistive personnel may perform routine, non-invasive tasks for stable clients whose care is predictable. Ambulation assistance with a gait belt fits that scope. Assessment, teaching, and care planning require nursing judgment and are never delegable.",
  o:["Correct — routine ambulation of a stable client is within UAP scope.",
    "Assessment requires nursing judgment and cannot be delegated.",
    "Teaching is a nursing function reserved to licensed staff.",
    "Care planning is a registered nurse responsibility."],
  s:"Never delegate assessment, teaching, evaluation, or planning. Stable and routine is the delegable category."},
 ref:"Supervision · delegation to UAP"},

{id:"MOC-060", t:"single", cn:"MOC", sys:"INF", topic:"Client privacy breach", d:1, b:-0.2, cj:"act", tags:["hipaa","privacy","confidentiality"],
 stem:"A nurse needs to discuss a client's wound care plan with a colleague in a busy hospital corridor. Which action best protects the client's privacy?",
 opts:["Move the conversation to a private area away from the public corridor",
  "Speak quietly because the corridor is only briefly occupied",
  "Use the client's initials instead of a full name while talking",
  "Delay the discussion until the client is discharged from the unit"],
 ans:0,
 rat:{c:"Protected health information must not be discussed where it can be overheard, regardless of volume or how the client is identified. Relocating to a private space is the correct control. Delaying a clinically relevant handoff is not an acceptable alternative.",
  o:["Correct — remove the conversation from public earshot.",
    "Lowering volume does not make a public corridor private.",
    "Initials still identify the client and remain protected information.",
    "Postponing needed clinical communication compromises care."],
  s:"Privacy is about location, not volume. If the public can overhear, move the conversation."},
 ref:"Legal practice · confidentiality"},

{id:"MOC-061", t:"single", cn:"MOC", sys:"INF", topic:"Leaving against medical advice", d:2, b:0.25, cj:"act", tags:["ama","legal","rights"],
 stem:"A competent adult client announces the intention to leave the hospital before completing antibiotic therapy. Which action should the nurse take first?",
 opts:["Explore the reasons for leaving and notify the provider of the intent",
  "Refuse to return the client's belongings until the provider arrives",
  "Inform the client that insurance will not cover the admission",
  "Ask security to detain the client pending a provider evaluation"],
 ans:0,
 rat:{c:"A competent adult has the right to refuse treatment and leave. The nurse's first action is to understand the reason, because a solvable barrier may change the decision, and to notify the provider so risks can be explained and the form completed.",
  o:["Correct — assess the reason and escalate to the provider.",
    "Withholding belongings is coercive and legally improper.",
    "Coverage consequences are not the nurse's to assert as a deterrent.",
    "Detaining a competent adult constitutes false imprisonment."],
  s:"Competent adults may leave. Explore, inform the provider, document — never detain or threaten."},
 ref:"Client rights · refusal of care"},

{id:"MOC-062", t:"single", cn:"MOC", sys:"CV", topic:"Do-not-resuscitate verification", d:2, b:0.3, cj:"analyze", tags:["dnr","code-status","documentation"],
 stem:"A client is admitted from a long-term care facility. The nurse cannot locate a do-not-resuscitate order in the chart, though the family states one exists. Which action is correct?",
 opts:["Initiate full resuscitation efforts if arrest occurs until an order is verified",
  "Withhold resuscitation based on the family's verbal report",
  "Contact the long-term care facility after the shift ends to clarify",
  "Document the family statement as a valid substitute for the order"],
 ans:0,
 rat:{c:"A do-not-resuscitate order must be a written provider order in the chart. Absent that order, full resuscitation is the default. The nurse should also escalate immediately to obtain and verify the order rather than waiting.",
  o:["Correct — no verified order means full resuscitation.",
    "A verbal family report is not a valid resuscitation order.",
    "Deferring clarification leaves the code status unresolved during the shift.",
    "Family statements cannot be charted in place of a provider order."],
  s:"No written DNR order in the chart = full code. Escalate to verify, but do not withhold."},
 ref:"Management of care · code status"},

{id:"MOC-063", t:"single", cn:"MOC", sys:"INF", topic:"Language barrier and consent", d:1, b:-0.05, cj:"act", tags:["interpreter","communication","health-literacy"],
 stem:"A nurse must obtain a nursing history from a client who speaks limited English. Which approach is most appropriate?",
 opts:["Use a qualified medical interpreter to conduct the interview",
  "Ask the client's adolescent child to translate during the interview",
  "Speak slowly and loudly in English until the client responds",
  "Rely on gestures and complete the history at the next visit"],
 ans:0,
 rat:{c:"Qualified interpreters are trained in medical terminology and confidentiality, and they avoid the errors and role reversals that arise when family members translate. Children must never be used as interpreters for a parent's care.",
  o:["Correct — a qualified interpreter ensures accuracy and confidentiality.",
    "Minors should not interpret; accuracy and emotional burden both suffer.",
    "Volume does not improve comprehension across a language barrier.",
    "Deferring the history delays assessment and treatment planning."],
  s:"Interpreter rules: qualified staff or service only. Never a minor, never another patient."},
 ref:"Collaboration · interpreter use"},

{id:"MOC-064", t:"single", cn:"MOC", sys:"INF", topic:"Unsafe assignment and chain of command", d:2, b:0.35, cj:"act", tags:["chain-of-command","advocacy","staffing"],
 stem:"A nurse is assigned eight acutely ill clients, including two requiring continuous titration of vasoactive infusions. Which action is most appropriate?",
 opts:["Report the concern to the charge nurse and request a revised assignment",
  "Accept the assignment and document the concern at the end of the shift",
  "Refuse the assignment and leave the unit immediately",
  "Ask a colleague to take the titration clients informally"],
 ans:0,
 rat:{c:"When an assignment exceeds safe capacity, the nurse raises it through the chain of command before care begins. Accepting an unsafe assignment and documenting afterward does not protect clients, and abandoning the assignment leaves clients without care.",
  o:["Correct — escalate through the chain of command before starting.",
    "Documenting after the fact does not mitigate risk during the shift.",
    "Abandonment leaves clients unattended and is a licensure issue.",
    "Informal transfers bypass the chain of command and go undocumented."],
  s:"Unsafe assignment: raise it up the chain first, in writing if needed. Do not abandon."},
 ref:"Quality improvement · chain of command"},

{id:"MOC-065", t:"single", cn:"MOC", sys:"INF", topic:"Handoff communication", d:1, b:-0.15, cj:"act", tags:["sbar","handoff","communication"],
 stem:"A nurse gives change-of-shift report on a client who became hypotensive two hours earlier. Which element is most essential to include?",
 opts:["The interventions given, the client's response, and the current blood pressure trend",
  "The client's full admission history and prior hospitalizations",
  "The name of the provider who wrote the original admission orders",
  "The scheduled menu selections for the coming twelve hours"],
 ans:0,
 rat:{c:"Handoff must convey what changed, what was done, how the client responded, and where things stand now. Structured frameworks such as SBAR exist to keep the receiving nurse oriented to the active problem rather than to static history.",
  o:["Correct — action, response, and current trend drive the next nurse's decisions.",
    "Historical detail belongs in the record, not the active handoff.",
    "Provider names are reference data, not the clinical priority.",
    "Menu selection is not clinically relevant to a hypotensive episode."],
  s:"SBAR: Situation, Background, Assessment, Recommendation. Lead with what changed and what is needed now."},
 ref:"Continuity of care · structured handoff"},

{id:"MOC-066", t:"single", cn:"MOC", sys:"INF", topic:"Mass casualty triage", d:3, b:0.55, cj:"prioritize", tags:["triage","disaster","mass-casualty"],
 stem:"At a mass casualty incident, the nurse assesses four victims. Which client should be tagged for immediate treatment?",
 opts:["An adult with absent respirations that resume after the airway is repositioned",
  "An adult walking calmly around the scene with superficial abrasions",
  "An adult with a palpable radial pulse and a deformed femur",
  "An adult with no respirations after two attempts to open the airway"],
 ans:0,
 rat:{c:"In disaster triage the goal is the greatest good for the greatest number. A victim who begins breathing after airway repositioning is salvageable with minimal intervention and is tagged immediate. A victim who remains apneic after airway maneuvers is tagged expectant, because resources cannot be diverted from salvageable victims.",
  o:["Correct — apnea reversed by repositioning is an immediate, salvageable airway problem.",
    "Ambulatory victims with minor injuries are tagged minimal.",
    "A deformed femur with a palpable pulse is delayed, not immediate.",
    "Persistent apnea after airway attempts is tagged expectant in a disaster."],
  s:"Disaster triage inverts routine triage: walking wounded last, apneic-after-airway expectant. Greatest good, greatest number."},
 ref:"Disaster response · START triage"},

{id:"MOC-067", t:"single", cn:"MOC", sys:"RESP", topic:"Discharge planning for oxygen therapy", d:2, b:0.2, cj:"generate", tags:["discharge","home-oxygen","case-management"],
 stem:"A client with chronic obstructive pulmonary disease is being discharged on home oxygen. Which statement by the client indicates that discharge teaching was effective?",
 opts:["I will keep the concentrator at least ten feet from the gas stove",
  "I can increase the flow rate whenever I feel short of breath",
  "I should apply petroleum jelly to my nostrils to prevent dryness",
  "I will smoke only in rooms where the concentrator is not running"],
 ans:0,
 rat:{c:"Oxygen vigorously supports combustion, so the concentrator must be kept well away from open flame and heat sources. Clients must not self-adjust flow rates, petroleum-based products are flammable near oxygen, and smoking is prohibited entirely.",
  o:["Correct — maintaining distance from flame is the core oxygen safety rule.",
    "Flow rates are prescribed; self-adjustment risks carbon dioxide retention.",
    "Petroleum jelly is flammable; water-soluble lubricant is used instead.",
    "No smoking is permitted anywhere while using home oxygen."],
  s:"Home oxygen: no flame, no smoking, no petroleum products, no self-adjusting the flow."},
 ref:"Case management · home oxygen discharge teaching"},

{id:"MOC-068", t:"single", cn:"MOC", sys:"INF", topic:"Medication error disclosure", d:2, b:0.3, cj:"act", tags:["medication-error","safety-culture","incident-report"],
 stem:"A nurse realizes that a client received the wrong dose of an antihypertensive one hour earlier. The client is currently asymptomatic. Which action should the nurse take first?",
 opts:["Assess the client, notify the provider, and complete an incident report",
  "Monitor quietly and report only if the client becomes symptomatic",
  "Complete the incident report before assessing the client",
  "Ask the pharmacist whether the dose is significant before notifying anyone"],
 ans:0,
 rat:{c:"Client safety comes first, so assessment and provider notification precede paperwork. Errors are reported regardless of whether harm occurred, because reporting drives system-level correction and the client may still deteriorate.",
  o:["Correct — assess, notify, then document; report even without apparent harm.",
    "Waiting for symptoms delays intervention and conceals the error.",
    "Paperwork never precedes client assessment.",
    "Pharmacy input is helpful but does not replace provider notification."],
  s:"Error sequence: assess the client, notify the provider, document, then file the incident report."},
 ref:"Performance improvement · error reporting"},

/* ── Physiological Adaptation (blueprint 14%) ──────────────────────── */
{id:"PAA-056", t:"single", cn:"PAA", sys:"ENDO", topic:"SIADH and hyponatremia", d:3, b:0.5, cj:"analyze", tags:["siadh","hyponatremia","electrolytes"],
 stem:"A client with small cell lung cancer develops confusion and a serum sodium of 118 mEq/L. Which finding is most consistent with the underlying disorder?",
 opts:["Concentrated urine with a low serum osmolality and no peripheral edema",
  "Dilute urine with marked thirst and a serum sodium above 150 mEq/L",
  "Bounding pulse with generalized pitting edema and jugular distension",
  "Dry mucous membranes with poor skin turgor and a rapid thready pulse"],
 ans:0,
 rat:{c:"Syndrome of inappropriate antidiuretic hormone causes water retention that dilutes serum sodium while the kidneys continue to excrete concentrated urine. Because the retained volume is distributed intracellularly, overt edema is typically absent.",
  o:["Correct — dilutional hyponatremia with inappropriately concentrated urine.",
    "Dilute urine with hypernatremia describes diabetes insipidus, the opposite picture.",
    "Bounding pulse with edema suggests volume overload from another cause.",
    "Dry membranes and poor turgor describe fluid volume deficit."],
  s:"SIADH = too much water, too little sodium, concentrated urine, no edema. Treat with fluid restriction."},
 ref:"Fluid and electrolyte · SIADH"},

{id:"PAA-057", t:"single", cn:"PAA", sys:"CV", topic:"Hyperkalemia cardiac effects", d:3, b:0.55, cj:"recognize", tags:["hyperkalemia","ecg","renal"],
 stem:"A client with acute kidney injury has a serum potassium of 6.9 mEq/L. Which electrocardiogram change should the nurse anticipate?",
 opts:["Tall peaked T waves with a widened QRS complex",
  "Prominent U waves with a flattened T wave and ST depression",
  "A shortened QT interval with a prolonged PR segment only",
  "Diffuse ST elevation with reciprocal changes in lead aVR"],
 ans:0,
 rat:{c:"Elevated extracellular potassium accelerates repolarization and slows conduction, producing tall peaked T waves early and QRS widening as levels climb. This progression can advance to a sine wave and asystole, so it is treated as an emergency.",
  o:["Correct — peaked T waves and QRS widening are the classic hyperkalemia pattern.",
    "U waves with flattened T waves indicate hypokalemia.",
    "Isolated PR prolongation without T wave change is not the hallmark pattern.",
    "Diffuse ST elevation with reciprocal aVR change suggests pericarditis."],
  s:"Potassium up = peaked T waves, wide QRS. Potassium down = U waves, flat T waves."},
 ref:"Cardiac · hyperkalemia"},

{id:"PAA-058", t:"single", cn:"PAA", sys:"ENDO", topic:"Diabetic ketoacidosis management", d:3, b:0.45, cj:"prioritize", tags:["dka","insulin","fluids"],
 stem:"A client arrives with diabetic ketoacidosis. Blood glucose is 540 mg/dL, potassium is 5.6 mEq/L, and the client is tachypneic with a fruity breath odor. Which order should the nurse implement first?",
 opts:["Intravenous isotonic fluid replacement at the prescribed rate",
  "Intravenous regular insulin by continuous infusion",
  "Sodium bicarbonate to correct the metabolic acidosis",
  "Intravenous potassium chloride added to the maintenance fluid"],
 ans:0,
 rat:{c:"Osmotic diuresis in DKA produces profound volume depletion, so isotonic fluid resuscitation comes first and also lowers glucose by dilution and improved perfusion. Insulin follows, and potassium is added only after levels fall and urine output is confirmed.",
  o:["Correct — volume replacement precedes insulin in DKA.",
    "Insulin given before fluids worsens intravascular depletion and shifts potassium.",
    "Bicarbonate is reserved for severe acidosis and is not first-line.",
    "Potassium is added later, once levels drop and output is established."],
  s:"DKA order of operations: fluids, then insulin, then potassium. Never insulin before volume."},
 ref:"Endocrine emergencies · DKA"},

{id:"PAA-059", t:"single", cn:"PAA", sys:"ENDO", topic:"Adrenal crisis", d:3, b:0.6, cj:"recognize", tags:["addisonian-crisis","adrenal","shock"],
 stem:"A client with Addison disease develops vomiting, severe hypotension, and a serum sodium of 126 mEq/L after missing two days of hydrocortisone. Which intervention is the priority?",
 opts:["Rapid intravenous corticosteroid with isotonic fluid replacement",
  "Oral fludrocortisone once the vomiting has resolved",
  "A sodium-restricted diet with careful daily weights",
  "Insulin infusion to correct the associated hyperglycemia"],
 ans:0,
 rat:{c:"Adrenal crisis is distributive shock from acute cortisol deficiency. Intravenous hydrocortisone plus aggressive isotonic fluids is lifesaving and must not wait. Oral therapy cannot be absorbed during vomiting, and Addison disease causes hypoglycemia rather than hyperglycemia.",
  o:["Correct — IV steroid and volume together reverse the crisis.",
    "Oral medication is unreliable during vomiting and acts too slowly.",
    "Sodium restriction worsens the existing hyponatremia and volume loss.",
    "Adrenal insufficiency typically produces low, not high, blood glucose."],
  s:"Adrenal crisis: IV hydrocortisone plus fluids, immediately. Never wait for oral absorption."},
 ref:"Endocrine emergencies · adrenal crisis"},

{id:"PAA-060", t:"single", cn:"PAA", sys:"GI", topic:"Hepatic encephalopathy and lactulose", d:2, b:0.35, cj:"evaluate", tags:["cirrhosis","lactulose","ammonia"],
 stem:"A client with cirrhosis is prescribed lactulose. Which finding best indicates that the medication is achieving its intended effect?",
 opts:["Improved alertness with two to three soft stools daily",
  "Absence of any bowel movement for forty-eight hours",
  "Increasing abdominal girth with worsening peripheral edema",
  "A rising serum ammonia level on the morning laboratory draw"],
 ans:0,
 rat:{c:"Lactulose traps ammonia in the colon and expels it through stool, lowering serum ammonia and improving mental status. Two to three soft stools daily is the usual titration target. Rising ammonia or absent stools indicate the dose is inadequate.",
  o:["Correct — mental status improvement with soft daily stools shows ammonia removal.",
    "No stool means ammonia is not being cleared.",
    "Increasing girth and edema reflect ascites, not lactulose effect.",
    "A rising ammonia level indicates treatment failure."],
  s:"Lactulose works when the client is clearer and having two to three soft stools. Dose to the stool count."},
 ref:"Gastrointestinal · hepatic encephalopathy"},

{id:"PAA-061", t:"multi", cn:"PAA", sys:"INF", topic:"Sepsis bundle implementation", d:3, b:0.5, cj:"act", tags:["sepsis","bundle","lactate"],
 stem:"A client meets screening criteria for sepsis with a suspected pulmonary source. Which actions belong in the first-hour bundle? Select all that apply.",
 opts:["Obtain blood cultures before starting antimicrobial therapy",
  "Administer broad-spectrum antibiotics within one hour",
  "Measure a serum lactate level",
  "Begin a thirty mL/kg crystalloid bolus if hypotensive or lactate is elevated",
  "Withhold fluids until central venous access is obtained"],
 ans:[0,1,2,3],
 rat:{c:"The first-hour bundle is cultures before antibiotics, broad-spectrum antibiotics within the hour, a lactate level, and thirty mL/kg of crystalloid for hypotension or a lactate of four or higher. Waiting for central access delays resuscitation, which is time-critical.",
  o:["Correct — cultures must precede antibiotics so the organism is identified.",
    "Correct — antibiotics within one hour reduce mortality.",
    "Correct — lactate gauges tissue perfusion and guides resuscitation.",
    "Correct — thirty mL/kg crystalloid is the standard initial bolus.",
    "Incorrect — peripheral access is sufficient to begin; central lines must not delay fluids."],
  s:"Sepsis hour one: cultures, antibiotics, lactate, thirty mL/kg fluid. Time is tissue."},
 ref:"Multisystem · sepsis bundle"},

{id:"PAA-062", t:"single", cn:"PAA", sys:"RESP", topic:"ARDS and PEEP", d:3, b:0.6, cj:"evaluate", tags:["ards","ventilator","peep"],
 stem:"A client with acute respiratory distress syndrome is mechanically ventilated with positive end-expiratory pressure of 12 cm H2O. Which finding indicates the nurse should reassess the client promptly?",
 opts:["Falling cardiac output with a dropping systolic reading",
  "An oxygen saturation of 94% on the present settings",
  "Bilateral crackles heard on auscultation of the lung fields",
  "A tidal volume matching the volume set on the ventilator"],
 ans:0,
 rat:{c:"Positive end-expiratory pressure raises intrathoracic pressure, which reduces venous return and can lower cardiac output. Falling blood pressure signals that PEEP is compromising perfusion and requires reassessment. Crackles are expected in ARDS, and saturation of 94% meets the usual target.",
  o:["Correct — hemodynamic compromise from high PEEP demands reassessment.",
    "A saturation of 94% is within the accepted ARDS target range.",
    "Crackles reflect the underlying disease, not a new ventilator problem.",
    "Delivered tidal volume matching the set volume is expected."],
  s:"High PEEP trades oxygenation for venous return. Watch blood pressure and urine output, not just saturation."},
 ref:"Respiratory · ARDS ventilation"},

{id:"PAA-063", t:"single", cn:"PAA", sys:"INF", topic:"End-of-life symptom management", d:2, b:0.25, cj:"act", tags:["palliative","dyspnea","end-of-life"],
 stem:"A client receiving hospice care has terminal dyspnea and appears air hungry. The family asks whether morphine will hasten death. Which response by the nurse is most appropriate?",
 opts:["Morphine relieves breathlessness; the goal is comfort, and the dose is titrated to that goal",
  "Morphine is avoided at the end of life because it suppresses respiration",
  "We will use morphine only after every other option has failed completely",
  "Oxygen alone is sufficient for terminal breathlessness in most clients"],
 ans:0,
 rat:{c:"Low-dose opioids are first-line for refractory dyspnea at the end of life. When titrated to symptom relief, they ease breathlessness without an intent to hasten death — the ethical principle of double effect applies. Withholding them leaves a distressing symptom untreated.",
  o:["Correct — opioids are first-line for terminal dyspnea, titrated to comfort.",
    "Avoiding opioids leaves air hunger untreated at the worst moment.",
    "Opioids are first-line here, not a last resort.",
    "Oxygen helps only when hypoxemia is the driver; it does not relieve all dyspnea."],
  s:"Terminal dyspnea: low-dose opioid, titrate to comfort. Double effect supports treating the symptom."},
 ref:"Palliative care · symptom management"},

/* ── Health Promotion & Maintenance (blueprint 9%) ─────────────────── */
{id:"HPM-029", t:"single", cn:"HPM", sys:"INF", topic:"Infant immunization schedule", d:1, b:-0.1, cj:"evaluate", tags:["immunization","pediatrics","prevention"],
 stem:"A parent asks which vaccines a healthy infant should receive at the two-month visit. Which response is correct?",
 opts:["DTaP, IPV, Hib, PCV13, and rotavirus",
  "MMR, varicella, and hepatitis A only",
  "Influenza and the human papillomavirus series",
  "Measles, mumps, and rubella given as separate injections"],
 ans:0,
 rat:{c:"The two-month visit includes DTaP, inactivated polio, Hib, pneumococcal conjugate, and rotavirus. MMR and varicella begin at twelve months, human papillomavirus begins at nine to twelve years, and measles, mumps, and rubella are given as the combined MMR.",
  o:["Correct — these five are the standard two-month vaccines.",
    "MMR, varicella, and hepatitis A start at twelve months or later.",
    "Influenza starts at six months; HPV starts at nine years.",
    "Measles, mumps, and rubella are given as one combination vaccine at twelve months."],
  s:"Two months = the big bacterial and rotavirus set. Live viral vaccines wait until twelve months."},
 ref:"Health promotion · childhood immunization"},

{id:"HPM-030", t:"single", cn:"HPM", sys:"GI", topic:"Colorectal cancer screening", d:1, b:-0.15, cj:"recognize", tags:["screening","colorectal","prevention"],
 stem:"A 47-year-old client at average risk for colorectal cancer asks about screening. Which recommendation is appropriate?",
 opts:["Screening should begin now, since average-risk screening starts at 45",
  "Screening should begin at 50 unless symptoms develop first",
  "Screening is needed only if a first-degree relative had polyps",
  "Screening is unnecessary without rectal bleeding or weight loss"],
 ans:0,
 rat:{c:"Average-risk colorectal cancer screening now begins at 45 rather than 50, reflecting a rising incidence in younger adults. Waiting for symptoms defeats the purpose, because early disease is typically silent.",
  o:["Correct — average-risk screening begins at 45.",
    "Starting at 50 reflects the older, superseded guideline.",
    "Average-risk adults are screened regardless of family history.",
    "Waiting for symptoms delays detection of treatable early disease."],
  s:"Colorectal screening starts at 45 for average risk, earlier and more often with family history."},
 ref:"Health screening · colorectal cancer"},

{id:"HPM-031", t:"single", cn:"HPM", sys:"REPI", topic:"Prenatal danger signs", d:2, b:0.15, cj:"recognize", tags:["prenatal","preeclampsia","teaching"],
 stem:"A nurse teaches a client at 30 weeks gestation which symptoms require immediate reporting. Which statement shows the client understood?",
 opts:["I will call right away if I have a severe headache that does not go away",
  "I should expect some swelling in my ankles by the end of each day",
  "Mild fatigue in the third trimester is something I can manage at home",
  "Occasional back ache means I simply need to rest more often"],
 ans:0,
 rat:{c:"A persistent severe headache is a warning sign of preeclampsia and requires immediate evaluation. Dependent ankle edema, fatigue, and intermittent back ache are common third-trimester findings and are not by themselves emergent.",
  o:["Correct — unrelenting headache is a preeclampsia warning sign.",
    "Dependent ankle edema is a common, expected finding.",
    "Third-trimester fatigue is expected and not emergent.",
    "Intermittent back ache is a normal discomfort of pregnancy."],
  s:"Preeclampsia red flags: severe headache, visual changes, right upper quadrant pain, sudden facial or hand swelling."},
 ref:"Antepartum · danger sign teaching"},

{id:"HPM-032", t:"single", cn:"HPM", sys:"NEURO", topic:"Fall prevention in older adults", d:1, b:-0.2, cj:"generate", tags:["falls","geriatric","safety"],
 stem:"An 82-year-old client with a history of two falls in six months is being assessed at home. Which intervention most directly reduces future fall risk?",
 opts:["Reviewing the medication list for agents that cause dizziness or sedation",
  "Advising the client to remain seated for most of the day",
  "Placing throw rugs in the hallway to cushion any future fall",
  "Restricting fluids in the evening to reduce nighttime trips"],
 ans:0,
 rat:{c:"Medications that cause orthostatic hypotension, sedation, or dizziness are among the strongest modifiable fall risk factors, so a deprescribing review is high-yield. Activity restriction causes deconditioning and increases risk, and throw rugs are a trip hazard.",
  o:["Correct — sedating and hypotensive medications are modifiable risk factors.",
    "Immobility causes weakness and raises rather than lowers fall risk.",
    "Loose rugs are a leading cause of trips and should be removed.",
    "Fluid restriction risks dehydration and orthostatic hypotension."],
  s:"Fall prevention: review the med list, remove rugs, add strength and balance work, check vision and footwear."},
 ref:"Aging · fall prevention"},

{id:"HPM-033", t:"single", cn:"HPM", sys:"PSYCH", topic:"Adolesent development and confidentiality", d:2, b:0.3, cj:"act", tags:["adolescent","confidentiality","development"],
 stem:"A 16-year-old client asks to speak with the nurse privately about contraception and states that no one at home knows about the visit. Which action is most appropriate?",
 opts:["Provide confidential counseling while explaining the limits of confidentiality",
  "Decline to discuss contraception because a parent must be present",
  "Contact the parent immediately to obtain permission to continue",
  "Provide written material only and avoid any verbal discussion"],
 ans:0,
 rat:{c:"Adolescents may consent to reproductive health services in most jurisdictions, and confidential counseling encourages care-seeking. The nurse should still be explicit about the limits of confidentiality, including mandatory reporting duties.",
  o:["Correct — confidential care with clear limits supports honest disclosure.",
    "Requiring a parent can deter adolescents from seeking needed care.",
    "Immediate parental contact breaches the confidentiality the client requested.",
    "Handouts alone avoid the assessment and counseling the client needs."],
  s:"Adolescent confidentiality: offer it, but state its limits up front — harm to self or others must be reported."},
 ref:"Developmental stages · adolescent confidentiality"},

{id:"HPM-034", t:"single", cn:"HPM", sys:"REPI", topic:"Postpartum hemorrhage assessment", d:2, b:0.3, cj:"recognize", tags:["postpartum","hemorrhage","fundus"],
 stem:"One hour after a vaginal delivery, a nurse saturates a perineal pad in fifteen minutes. The fundus is boggy and displaced to the right of the umbilicus. Which action should the nurse take first?",
 opts:["Massage the uterus and assist the client to empty the bladder",
  "Document the pad count and reassess in another fifteen minutes",
  "Apply an ice pack to the perineum to slow the bleeding",
  "Prepare for an immediate return to the operating room"],
 ans:0,
 rat:{c:"A boggy, laterally displaced fundus points to uterine atony compounded by a full bladder. Fundal massage restores tone and bladder emptying removes the mechanical displacement. This first-line action usually controls the bleeding before escalation is needed.",
  o:["Correct — massage plus bladder emptying treats the most common cause.",
    "Documenting and waiting allows continued blood loss.",
    "Ice reduces perineal swelling but does not correct uterine atony.",
    "Surgical intervention follows failed conservative measures, not precedes them."],
  s:"Boggy fundus = atony. Massage it, empty the bladder, then escalate if bleeding continues."},
 ref:"Postpartum · hemorrhage management"},

{id:"HPM-035", t:"single", cn:"HPM", sys:"CV", topic:"Hypertension lifestyle teaching", d:1, b:-0.05, cj:"evaluate", tags:["hypertension","diet","lifestyle"],
 stem:"A client newly diagnosed with hypertension asks which lifestyle change is most effective. Which response by the nurse is most accurate?",
 opts:["Adopting the DASH eating pattern and keeping sodium under 2,300 mg daily",
  "Eliminating all dietary sodium from meals and snacks entirely",
  "Exercising intensely for one hour once each week",
  "Switching from coffee to caffeinated tea each morning"],
 ans:0,
 rat:{c:"The DASH eating pattern with sodium reduction is the best-supported dietary intervention for lowering blood pressure. Total sodium elimination is neither practical nor physiologic, and exercise is most effective when it is regular rather than occasional.",
  o:["Correct — DASH with sodium under 2,300 mg is first-line.",
    "Zero sodium is impractical and not required for benefit.",
    "Once-weekly exercise does not provide sustained blood pressure reduction.",
    "Caffeine substitution has minimal effect on blood pressure control."],
  s:"First-line lifestyle measures: DASH, sodium under 2,300 mg, regular activity, weight loss, and moderated alcohol."},
 ref:"Health promotion · hypertension lifestyle management"}
);
