/* ============================================================================
   bank17.js — hand-authored wave 7: 20 hard items, NCLEX-RN only

   WHY THIS FILE EXISTS
     Wave 5 raised the difficulty floor across SIC, HPM and BCC. Measured
     against the shipped bank it still left two categories soft: HPM held 42
     items with only 26% at d>=2, and BCC held 42 with only 36%. Those are the
     two categories where an examinee drilling here would meet an easier exam
     than the real one. This wave adds 8 HPM and 8 BCC items, all d>=2, plus
     4 SIC items in transmission-precaution territory the bank had not covered.

   WHAT MAKES THESE HARD (and NCLEX-realistic)
     · second-order asks: not "what do you do" but "what do you do next"
     · eligibility questions with three independent gates, where three of four
       options clear two of them
     · distractors that are correct actions in a different scenario
     · stability-based exceptions to rules the bank has already drilled
       (intact heel eschar, phantom limb pain, PCA by proxy)

   AUTHORING RULES OBSERVED
     · no stem token that occurs only in the key option
     · key is not systematically the longest option
     · every rationale explains the key and each distractor, plus a takeaway
   ========================================================================== */
window.NC.BANK.push(
/* ── Health Promotion & Maintenance (was 26% hard) ─────────────────── */
{id:"HPM-043", t:"single", cn:"HPM", sys:"REPI", topic:"Rh isoimmunization prophylaxis", d:3, b:0.45, cj:"generate", tags:["prenatal","rh-isoimmunization","prophylaxis"],
 stem:"A nurse reviews the prenatal record of a primigravida at 28 weeks gestation. The blood type is O negative and the antibody screen is negative. Which action should the nurse anticipate?",
 opts:["Rh(D) immune globulin now, then again within 72 hours after birth if the newborn is Rh positive",
  "Rh(D) immune globulin deferred until after delivery, once the newborn's blood type is known",
  "Rh(D) immune globulin withheld until an episode of vaginal bleeding occurs",
  "Paternal blood typing first, with Rh(D) immune globulin deferred until that result returns"],
 ans:0,
 rat:{c:"An unsensitized Rh-negative client receives Rh(D) immune globulin prophylactically at 28 weeks because silent fetomaternal hemorrhage is common in the third trimester, then again within 72 hours of delivery if the neonate is Rh positive. Deferring the dose until bleeding occurs misses those silent bleeds, and paternal typing is not a prerequisite for the scheduled 28-week dose.",
  o:["Correct — the 28-week dose is scheduled prophylaxis, not a reaction to an event, and the postpartum dose follows within 72 hours.",
   "Waiting for delivery leaves the third-trimester window unprotected, which is precisely what the 28-week dose covers.",
   "Most sensitizing bleeds are silent; waiting for visible bleeding forgoes prophylaxis entirely.",
   "Paternal typing may refine counselling but does not gate a scheduled prophylactic dose."],
  s:"Rh(D) immune globulin is given at fixed points — 28 weeks and 72 hours postpartum — not when an event you are waiting to observe finally appears."},
 ref:"Health promotion · Rh isoimmunization prophylaxis"},

{id:"HPM-044", t:"single", cn:"HPM", sys:"REPI", topic:"Group B streptococcus intrapartum prophylaxis", d:2, b:0.35, cj:"analyze", tags:["prenatal","gbs","prophylaxis"],
 stem:"A client at 37 weeks gestation receives a positive rectovaginal culture for group B Streptococcus and asks what happens next. Which response by the nurse is accurate?",
 opts:["You will receive intravenous antibiotics once labor begins.",
  "You will begin an oral antibiotic course today and finish it before delivery.",
  "Treatment is needed if your membranes rupture before labor begins.",
  "A repeat culture at 39 weeks will determine whether treatment is needed."],
 ans:0,
 rat:{c:"Intrapartum intravenous antibiotic prophylaxis beginning at the onset of labor or rupture of membranes is the intervention shown to reduce early-onset neonatal group B Streptococcus disease. Antepartum oral therapy suppresses colonization transiently but does not eradicate it, so it does not protect the neonate at delivery, and a repeat culture does not change management.",
  o:["Correct — intrapartum intravenous coverage is timed to labor, the exposure window that matters.",
   "Antepartum oral therapy does not eradicate colonization by delivery, so it does not protect the neonate.",
   "Rupture of membranes is one trigger for starting prophylaxis, not a condition that decides whether prophylaxis is needed.",
   "Management is already decided by the positive culture; repeating it delays nothing and adds nothing."],
  s:"Group B Streptococcus prophylaxis is timed to labor rather than to the culture result, because colonization recurs between the test and delivery."},
 ref:"Health promotion · intrapartum GBS prophylaxis"},

{id:"HPM-045", t:"single", cn:"HPM", sys:"RESP", topic:"Low-dose CT lung cancer screening eligibility", d:2, b:0.4, cj:"analyze", tags:["screening","lung-cancer","eligibility"],
 stem:"A nurse in an occupational health clinic is identifying employees who meet criteria for annual low-dose CT lung cancer screening. Which employee should be referred?",
 opts:["A 62-year-old former smoker with a 30 pack-year history who quit 8 years ago",
  "A 55-year-old current smoker whose total exposure is 15 pack-years",
  "A 70-year-old former smoker with 40 pack-years who stopped 20 years ago",
  "A 48-year-old current smoker with a 30 pack-year history"],
 ans:0,
 rat:{c:"Annual low-dose CT screening applies to adults aged 50 to 80 with at least a 20 pack-year history who currently smoke or quit within the past 15 years. The 62-year-old meets the age range, the pack-year minimum, and the recency limit; the others fail on pack-years, on recency, and on age respectively.",
  o:["Correct — clears the age band, the 20 pack-year minimum, and the 15-year recency limit.",
   "Fifteen pack-years is below the 20 pack-year threshold, so current smoking does not rescue the referral.",
   "Quitting 20 years ago falls outside the 15-year recency window despite a heavy exposure history.",
   "At 48 the employee is below the 50-year floor regardless of exposure."],
  s:"Screening eligibility has separate gates for age, cumulative exposure, and how recently the exposure ended. Test each candidate against every gate rather than the one that stands out."},
 ref:"Health promotion · low-dose CT screening criteria"},

{id:"HPM-046", t:"single", cn:"HPM", sys:"CV", topic:"Abdominal aortic aneurysm screening", d:2, b:0.4, cj:"analyze", tags:["screening","aneurysm","eligibility"],
 stem:"A nurse at a community health fair decides which visitor qualifies for a one-time abdominal ultrasound to screen for abdominal aortic aneurysm. Which visitor meets the criteria?",
 opts:["A 68-year-old man who smoked for 20 years",
  "A 70-year-old woman who smoked for 30 years",
  "A 62-year-old man with no history of smoking",
  "A 78-year-old man who stopped smoking 10 years ago"],
 ans:0,
 rat:{c:"A one-time abdominal ultrasound is recommended for men aged 65 to 75 who have smoked at any point. The 68-year-old man satisfies the sex, the age band, and the smoking condition; the woman falls outside the sex-specific recommendation, the 62-year-old is below the age band, and the 78-year-old is above it.",
  o:["Correct — male, inside the 65 to 75 band, and a past smoker.",
   "The recommendation is sex-specific; a heavier exposure history does not extend it to women.",
   "Below the age band, and never-smoking removes the qualifying exposure as well.",
   "Above the upper age limit, so the one-time screen is no longer indicated."],
  s:"This recommendation is narrow on three axes at once — sex, age band, and smoking history. Check each axis, because three of the options satisfy two of them."},
 ref:"Health promotion · abdominal aortic aneurysm screening"},

{id:"HPM-047", t:"single", cn:"HPM", sys:"INF", topic:"Newborn hearing screening follow-up", d:2, b:0.4, cj:"analyze", tags:["newborn","hearing","screening"],
 stem:"A newborn does not pass the automated auditory brainstem response screen before discharge. The parent asks what the result means. Which response by the nurse is accurate?",
 opts:["A diagnostic hearing evaluation is needed, and it should happen within the next month.",
  "Your newborn is deaf, and we will begin planning for hearing aids.",
  "Newborn hearing screens are unreliable, so follow-up is not required.",
  "The screen will be repeated when your newborn reaches 6 months of age."],
 ans:0,
 rat:{c:"A failed newborn hearing screen is a screening result rather than a diagnosis; a diagnostic audiology evaluation confirms it, ideally by 3 months of age so that intervention can begin by 6 months. Waiting until 6 months to repeat the screen consumes the window in which early amplification has the greatest effect on language development.",
  o:["Correct — the screen flags risk, and a prompt diagnostic evaluation confirms or clears it.",
   "A screening failure is not a diagnosis; many infants who fail pass on diagnostic testing.",
   "The screen is validated precisely because it is followed by a diagnostic step, not because it settles the question.",
   "Repeating at 6 months spends the critical period for language development that early intervention exists to protect."],
  s:"A screening test narrows a population; a diagnostic test answers the question. When a screen is positive, schedule the confirmation promptly rather than treating it as final or as noise."},
 ref:"Health promotion · newborn hearing screen follow-up"},

{id:"HPM-048", t:"single", cn:"HPM", sys:"GI", topic:"Iron supplementation in the breastfed infant", d:3, b:0.5, cj:"generate", tags:["infant","nutrition","iron"],
 stem:"A nurse counsels the parent of a healthy 4-month-old term infant who is exclusively breastfed. Which recommendation is appropriate?",
 opts:["Begin a daily iron supplement of 1 mg per kilogram of body weight.",
  "Add iron-fortified cereal to a bottle at each feeding.",
  "Continue exclusive breastfeeding with no supplement until 6 months.",
  "Replace breastfeeding with an iron-fortified formula."],
 ans:0,
 rat:{c:"Term infants exhaust their hepatic iron stores around 4 months, and breast milk supplies iron in a quantity too small to cover needs after that point, so 1 mg/kg per day of supplemental iron is indicated until iron-containing complementary foods are established. Cereal delivered in a bottle is not an accepted route at this age, and stopping breastfeeding is unnecessary.",
  o:["Correct — 1 mg/kg per day bridges the gap between depleted stores and iron-containing solids.",
   "Bottle-delivered cereal is not a recommended route for a 4-month-old and displaces milk intake.",
   "Exclusive breastfeeding is recommended for about 6 months, but iron is the recognized exception to that rule.",
   "Formula substitution is not required; supplemental iron preserves breastfeeding."],
  s:"Iron is the one nutrient where the six-month exclusive-breastfeeding rule has a recognized carve-out. Know which supplement the guidance adds and when it starts."},
 ref:"Health promotion · infant iron requirements"},

{id:"HPM-049", t:"single", cn:"HPM", sys:"PSYCH", topic:"Six-month developmental milestones", d:2, b:0.35, cj:"recognize", tags:["development","infant","milestones"],
 stem:"A nurse assesses a 6-month-old infant during a well-child visit. Which finding is consistent with expected development at this age?",
 opts:["Sits briefly without support and transfers objects from hand to hand",
  "Pulls to a standing position and cruises along furniture",
  "Uses two words with meaning besides mama and dada",
  "Stacks two blocks together when asked to do so"],
 ans:0,
 rat:{c:"At 6 months an infant sits briefly without support and transfers objects from hand to hand. Pulling to stand and cruising emerge around 9 to 12 months, meaningful words beyond mama and dada appear near 12 months, and stacking two blocks is an 18-month skill, so each of those findings would signal advancement beyond this age.",
  o:["Correct — unsupported sitting and hand-to-hand transfer are the hallmark 6-month skills.",
   "Cruising is a 9 to 12 month skill, well past this visit.",
   "Meaningful vocabulary beyond mama and dada emerges near the first birthday.",
   "Stacking two blocks is an 18-month fine motor achievement."],
  s:"Milestone questions are answered fastest by fixing the age anchor first, then treating options that belong to a later age as distractors rather than weighing each on its merits."},
 ref:"Health promotion · infant developmental milestones"},

{id:"HPM-050", t:"single", cn:"HPM", sys:"INF", topic:"Child passenger safety seat use", d:2, b:0.4, cj:"evaluate", tags:["safety","infant","teaching"],
 stem:"A nurse teaches the parent of a 14-month-old infant weighing 22 pounds about car safety seat use. Which statement by the parent indicates correct understanding?",
 opts:["My child stays rear-facing until reaching the seat's height or weight limit.",
  "My child can turn forward-facing now because he is over 1 year old.",
  "My child should ride in the front seat if the airbag is switched off.",
  "A booster seat is appropriate once my child reaches 20 pounds."],
 ans:0,
 rat:{c:"Children remain rear-facing until they exceed the seat manufacturer's height or weight limit, which for convertible seats is well past the first birthday; the former one-year-and-20-pound threshold no longer applies. Children ride in the back seat until at least age 13, and a booster seat follows a forward-facing harness rather than replacing it.",
  o:["Correct — the seat's own limits, not a birthday, decide when to turn the child forward.",
   "The one-year rule is outdated; convertible seats keep children rear-facing far longer.",
   "Children ride in the back seat until at least age 13; deactivating an airbag does not make the front seat safe.",
   "A booster follows a forward-facing harness and is keyed to height and age, not 20 pounds."],
  s:"Car seat guidance that keyed to the first birthday has been superseded by limits set by the seat itself. Outdated thresholds often survive as distractors."},
 ref:"Health promotion · child passenger safety"},

/* ── Basic Care & Comfort (was 36% hard) ───────────────────────────── */
{id:"BCC-043", t:"single", cn:"BCC", sys:"GI", topic:"Interrupted parenteral nutrition", d:3, b:0.5, cj:"prioritize", tags:["nutrition","parenteral","hypoglycemia"],
 stem:"A client receiving total parenteral nutrition through a central venous catheter has the infusion interrupted because the next container has not arrived from the pharmacy. Which action should the nurse take first?",
 opts:["Infuse 10% dextrose in water at the same rate as the previous infusion.",
  "Flush the catheter with heparin and wait for the next container.",
  "Restart the infusion at half the previous rate when the container arrives.",
  "Administer a bolus of normal saline to keep the catheter patent."],
 ans:0,
 rat:{c:"Abrupt interruption of parenteral nutrition removes a concentrated glucose load that the client's insulin secretion has adapted to, creating a risk of rebound hypoglycemia; infusing 10% dextrose at the same rate bridges the gap until the nutrition resumes. Flushing or saline maintains patency but leaves the glucose deficit uncorrected, and restarting at half rate leaves it partly uncorrected.",
  o:["Correct — 10% dextrose at the same rate substitutes for the withdrawn glucose load.",
   "Heparin preserves the line but does nothing about the sudden glucose withdrawal.",
   "A half rate still under-delivers glucose and leaves rebound hypoglycemia possible.",
   "Saline keeps the catheter open while the client remains hypoglycemic."],
  s:"When a concentrated dextrose infusion stops suddenly, the priority is glucose withdrawal, not line patency. Replace the substrate at the same rate until the real infusion resumes."},
 ref:"Basic care · rebound hypoglycemia after interrupted TPN"},

{id:"BCC-044", t:"single", cn:"BCC", sys:"INTG", topic:"Stable heel eschar management", d:3, b:0.55, cj:"act", tags:["wound","pressure-injury","eschar"],
 stem:"A nurse assesses a client who has a dry, intact, firmly adherent black eschar covering the heel. There is no redness, drainage, or fluctuance around the area. Which action is appropriate?",
 opts:["Keep the eschar in place and redistribute pressure away from the heel.",
  "Perform sharp debridement of the eschar at the bedside.",
  "Apply a moist dressing to soften the eschar and lift it away.",
  "Document the wound as a stage 4 pressure injury."],
 ans:0,
 rat:{c:"Stable, dry, intact eschar on the heel or an ischemic limb acts as a natural biological cover and should not be removed; the intervention is pressure redistribution plus monitoring for infection. Debridement or moist dressings convert a stable wound into an open one, and an eschar-covered wound is classified as unstageable rather than stage 4.",
  o:["Correct — stable heel eschar is protected, so offloading and surveillance are the interventions.",
   "Sharp debridement of stable heel eschar removes a biological cover and opens the wound.",
   "Moist dressings soften eschar deliberately, which is contraindicated when the tissue is stable.",
   "Full-thickness loss obscured by eschar is documented as unstageable, not stage 4."],
  s:"The word stable changes the plan. Eschar elsewhere is usually debrided, but on a heel or ischemic limb it is protected, so identify location and tissue condition before choosing an intervention."},
 ref:"Basic care · unstageable pressure injury with stable eschar"},

{id:"BCC-045", t:"single", cn:"BCC", sys:"MSK", topic:"Suspected compartment syndrome", d:3, b:0.5, cj:"prioritize", tags:["orthopedic","compartment-syndrome","emergency"],
 stem:"A client with a long leg cast applied 6 hours ago reports escalating pain that opioid analgesia does not relieve, and the nurse observes pain when the toes are passively stretched. Which action should the nurse take first?",
 opts:["Notify the provider of suspected compartment syndrome.",
  "Elevate the limb above the level of the heart and apply ice.",
  "Give the next scheduled dose of analgesia and reassess in 1 hour.",
  "Document the finding as expected discomfort after cast application."],
 ans:0,
 rat:{c:"Pain out of proportion to the injury and pain on passive stretch are the earliest and most reliable signs of compartment syndrome, a surgical emergency requiring prompt decompression; delaying for analgesia or elevation risks irreversible muscle and nerve necrosis within hours. Elevation above heart level reduces arterial perfusion pressure and worsens ischemia.",
  o:["Correct — this presentation is a surgical emergency and the provider must be notified now.",
   "Elevating above the heart lowers arterial perfusion pressure and accelerates ischemic injury.",
   "Waiting an hour on a scheduled dose forfeits the window in which decompression preserves function.",
   "Analgesia-resistant pain with pain on passive stretch is not expected post-casting discomfort."],
  s:"Pain on passive stretch together with analgesia that does not help is the compartment syndrome signature. Treat it as a surgical emergency and notify, rather than escalating comfort measures first."},
 ref:"Basic care · compartment syndrome after casting"},

{id:"BCC-046", t:"single", cn:"BCC", sys:"MSK", topic:"Phantom limb pain", d:2, b:0.4, cj:"act", tags:["amputation","pain","neuropathic"],
 stem:"A client 3 days after an above-the-knee amputation reports severe cramping pain in the toes of the amputated limb. Which action should the nurse take?",
 opts:["Administer the prescribed analgesic and document the pain as phantom limb pain.",
  "Explain that the limb is gone and the sensation will resolve on its own.",
  "Request a psychiatric consultation about the reported sensation.",
  "Apply a compression dressing to the residual limb."],
 ans:0,
 rat:{c:"Phantom limb pain is genuine neuropathic pain arising from peripheral and central nerve reorganization after amputation, and it is treated with analgesics, often including agents for neuropathic pain. Dismissing it as imaginary or referring for psychiatric evaluation invalidates a real physiological experience, and compressing the residual limb addresses swelling rather than this pain.",
  o:["Correct — phantom limb pain is real neuropathic pain and is treated as pain.",
   "Telling the client the sensation is unreal is both inaccurate and dismissive of a physiological process.",
   "Psychiatric referral misattributes a neuropathic phenomenon to a mental health condition.",
   "Compression manages residual limb edema and does not treat phantom sensation."],
  s:"Pain reported in an absent limb is physiological rather than psychological. Treat the pain you are told about and document its character, rather than questioning whether it is real."},
 ref:"Basic care · phantom limb pain after amputation"},

{id:"BCC-047", t:"single", cn:"BCC", sys:"GI", topic:"Ischemic new colostomy stoma", d:3, b:0.5, cj:"prioritize", tags:["ostomy","perfusion","emergency"],
 stem:"A nurse assesses a client 8 hours after creation of a colostomy. The stoma appears dusky purple and feels cool to touch. Which action should the nurse take first?",
 opts:["Notify the surgeon immediately.",
  "Document the finding as expected postoperative edema.",
  "Apply warm saline gauze to the stoma and reassess in 4 hours.",
  "Empty the ostomy appliance and measure the stoma."],
 ans:0,
 rat:{c:"A healthy new stoma is beefy red and moist; a dusky, purple, or black appearance signals impaired perfusion and possible necrosis of the bowel segment, which requires immediate surgical evaluation. Edema is expected but does not change color, and reassessing later allows necrosis to progress.",
  o:["Correct — a dusky, cool stoma indicates compromised blood supply and needs surgical review now.",
   "Edema is expected after creation but does not turn the stoma dusky or cool.",
   "Warm gauze does not restore perfusion, and a 4-hour delay allows necrosis to advance.",
   "Measuring and emptying the appliance is routine care and ignores the perfusion finding."],
  s:"Color is the fastest stoma viability check: red is perfused, dusky or black is not. Any deviation from beefy red in a new stoma is a call-the-surgeon finding rather than a routine one."},
 ref:"Basic care · stomal ischemia in the immediate postoperative period"},

{id:"BCC-048", t:"single", cn:"BCC", sys:"REN", topic:"Catheter-associated infection prevention", d:2, b:0.4, cj:"act", tags:["infection","catheter","prevention"],
 stem:"A nurse is caring for a client with an indwelling urinary catheter. Which action reduces the risk of a catheter-associated urinary tract infection?",
 opts:["Keep the drainage bag below the level of the bladder.",
  "Clamp the catheter briefly to obtain an accurate hourly output.",
  "Replace the catheter at routine scheduled intervals.",
  "Irrigate the catheter daily with an antiseptic solution."],
 ans:0,
 rat:{c:"Keeping the collection bag below bladder level prevents reflux of colonized urine back into the bladder and maintains unobstructed drainage. Scheduled catheter changes and antiseptic irrigation raise infection risk by disrupting the closed system and selecting resistant organisms, and clamping creates stasis and reflux.",
  o:["Correct — a dependent bag prevents reflux and keeps drainage unobstructed.",
   "Clamping causes stasis and reflux of colonized urine, both of which raise infection risk.",
   "Routine replacement breaches the closed system; catheters are changed for indication, not on schedule.",
   "Daily antiseptic irrigation disrupts the closed system and selects for resistant organisms."],
  s:"Closed-system integrity is the core of catheter infection prevention. Actions that open, irrigate, or routinely replace the system add risk rather than reducing it, so keep the circuit sealed and dependent."},
 ref:"Basic care · CAUTI prevention bundle"},

{id:"BCC-049", t:"single", cn:"BCC", sys:"INF", topic:"Patient-controlled analgesia by proxy", d:2, b:0.45, cj:"act", tags:["pain","opioid","safety"],
 stem:"A client using patient-controlled analgesia asks the nurse to press the button because he is too tired to use it himself. Which action should the nurse take?",
 opts:["Explain that the client must be the one to press the button, and move it within reach.",
  "Press the button once on the client's behalf and document the dose.",
  "Ask the client's spouse to press the button when needed overnight.",
  "Switch the client to scheduled intravenous opioid doses."],
 ans:0,
 rat:{c:"The safety of patient-controlled analgesia depends on the client being the sole person able to deliver a dose, because sedation from accumulating opioid eventually prevents further self-administration. Administration by a nurse or family member removes that built-in ceiling and is a recognized cause of fatal overdose; repositioning the button preserves both access and safety.",
  o:["Correct — repositioning the device solves the access problem without surrendering the safety mechanism.",
   "Nurse-administered doses bypass the sedation ceiling that makes the device self-limiting.",
   "Family-administered dosing is the same hazard under another name and is never delegated.",
   "Scheduled intravenous dosing abandons a working modality to solve a problem that repositioning solves."],
  s:"The lockout interval protects the client when the client alone controls the trigger. Do not delegate the button; solve an access problem by moving the device rather than by taking over."},
 ref:"Basic care · PCA by proxy as an overdose mechanism"},

{id:"BCC-050", t:"single", cn:"BCC", sys:"RESP", topic:"Hospice eligibility criteria", d:2, b:0.45, cj:"analyze", tags:["palliative","hospice","eligibility"],
 stem:"A client with end-stage chronic obstructive pulmonary disease asks about enrolling in hospice. Which statement by the nurse is accurate?",
 opts:["Hospice needs a provider certification of a life expectancy of 6 months or less if the illness runs its usual course.",
  "Hospice enrollment requires discontinuing any medication that is unrelated to comfort.",
  "Hospice becomes available once curative treatment has been attempted for 1 full year.",
  "Enrolling in hospice permanently gives up the client's right to any hospital care."],
 ans:0,
 rat:{c:"Hospice eligibility rests on a physician certification of a prognosis of 6 months or less should the disease run its expected course, and enrollment is renewable when the client continues to meet the criteria. Comfort-directed care is the focus, but medications are managed rather than categorically stopped, and hospice can be revoked or the client hospitalized when needed.",
  o:["Correct — the 6-month certification is the eligibility requirement, and enrollment stays renewable.",
   "Medications are reviewed and often continued when they serve comfort; there is no blanket discontinuation rule.",
   "Eligibility is prognostic, not a function of how long curative treatment was attempted.",
   "Hospice can be revoked at any time, and hospital care remains available when it is needed."],
  s:"Hospice criteria are prognostic rather than therapeutic. The 6-month estimate is a certification requirement, not a prediction that ends benefits, and enrollment stays reversible."},
 ref:"Basic care · hospice eligibility and reversibility"},

/* ── Safety & Infection Control ────────────────────────────────────── */
{id:"SIC-061", t:"single", cn:"SIC", sys:"INTG", topic:"Safe patient handling and shear prevention", d:3, b:0.5, cj:"act", tags:["safe-handling","shear","skin-integrity"],
 stem:"A nurse and an assistive personnel need to move a client up in bed. The client is able to assist using the trapeze. Which technique prevents shearing injury to the client's skin?",
 opts:["Use a friction-reducing sheet and lift rather than drag the client upward",
  "Have the client push against the footboard while the staff pull at the shoulders",
  "Raise the head of the bed to 45 degrees to make the move easier",
  "Roll the client from side to side to inch the client up the bed"],
 ans:0,
 rat:{c:"Shearing injury occurs when the skin stays fixed against the linens while deeper tissue slides over it, so dragging a client up in bed is the mechanism that produces it. A friction-reducing sheet plus lifting rather than pulling distributes the force, and lowering the head of the bed reduces the gravitational resistance. Pulling at the shoulders concentrates force across the scapulae and sacrum, raising the head increases the downward drag, and side-to-side rolling does not move the client upward at all.",
  o:["Correct — a friction-reducing sheet and lifting remove the drag that produces shear.",
   "Pulling at the shoulders concentrates force across the scapulae and sacrum, where shear damage occurs.",
   "Raising the head increases gravitational resistance and the pulling force required, worsening shear.",
   "Rolling side to side adds friction without moving the client toward the head of the bed."],
  s:"Shear comes from dragging, not from the move itself. Lower the head of the bed, use a friction-reducing sheet, and lift with enough help rather than pulling."},
 ref:"Safety · shear injury during repositioning"},

{id:"SIC-062", t:"single", cn:"SIC", sys:"INF", topic:"Electrical equipment malfunction at the bedside", d:3, b:0.5, cj:"prioritize", tags:["electrical-safety","equipment","emergency"],
 stem:"A nurse hears a crackling sound from an intravenous infusion pump and notices a faint burning smell. Which action should the nurse take first?",
 opts:["Unplug the pump by grasping the plug body, then run the infusion by gravity",
  "Press the power button on the pump to stop the infusion",
  "Disconnect the client's intravenous tubing at the hub and leave the pump running",
  "Call biomedical engineering to inspect the pump before further use"],
 ans:0,
 rat:{c:"A device that is crackling and smelling of burning insulation has an electrical fault and must be disconnected from the power source. Grasping the plug body rather than the cord avoids transmitting the fault and avoids further cord damage, and gravity flow keeps the therapy running while the pump is out of service. A power button stops the mechanism but leaves the device energized; disconnecting the client without removing the hazard leaves the fault live at the bedside; and biomedical engineering is notified after the device is unplugged and tagged, not before.",
  o:["Correct — remove the device from the power source by the plug, then maintain the infusion by gravity.",
   "A power button deactivates the mechanism but leaves the device connected and energized.",
   "Interrupting the client's therapy while the fault stays live protects neither the client nor the nurse.",
   "Biomedical engineering is notified once the device is unplugged and tagged out of service."],
  s:"Electrical fault at the bedside: disconnect at the plug, keep the therapy running another way, then report. Grasping the plug body rather than the cord is the tested detail."},
 ref:"Safety · electrical equipment fault at the bedside"},

{id:"SIC-063", t:"single", cn:"SIC", sys:"RESP", topic:"Negative-pressure room allocation", d:3, b:0.45, cj:"prioritize", tags:["isolation","airborne","resource-allocation"],
 stem:"A hospital has one negative-pressure airborne infection isolation room available and four clients requiring transmission-based precautions. Which client should receive the room?",
 opts:["A client with suspected active pulmonary tuberculosis.",
  "A client with influenza requiring droplet precautions.",
  "A client with methicillin-resistant Staphylococcus aureus bacteremia.",
  "A client with Clostridioides difficile colitis."],
 ans:0,
 rat:{c:"Negative-pressure airborne isolation is reserved for pathogens carried in droplet nuclei that remain suspended and travel on air currents, principally Mycobacterium tuberculosis, measles, and varicella. Influenza requires droplet precautions, and both staphylococcal bacteremia and C. difficile require contact precautions; none of those needs negative pressure, so the tuberculosis client is the one whose precautions the room actually provides.",
  o:["Correct — airborne transmission is the indication for negative pressure, and tuberculosis is airborne.",
   "Droplet precautions use a private room or spacing, not negative-pressure air handling.",
   "Contact precautions require a private room and dedicated equipment, not engineered airflow.",
   "Contact plus enteric precautions govern here; negative pressure adds nothing."],
  s:"Match the room to the transmission route, not to how sick or how infectious the client seems. Negative pressure solves an airborne problem and does nothing for contact or droplet spread."},
 ref:"Safety · airborne infection isolation room allocation"},

{id:"SIC-064", t:"single", cn:"SIC", sys:"NEURO", topic:"Client found on the floor", d:2, b:0.4, cj:"prioritize", tags:["falls","assessment","safety"],
 stem:"A nurse finds an older adult client lying on the floor beside the bed. The client is alert and says, \"I slipped when I tried to stand.\" Which action should the nurse take first?",
 opts:["Assess for injury, vital signs, and neurological status while the client stays on the floor.",
  "Help the client up from the floor and back into bed, then check for bruising.",
  "Call the provider to report the fall before doing anything else.",
  "Ask the client what caused the slip and document the statement."],
 ans:0,
 rat:{c:"A client found on the floor must be assessed before being moved, because lifting someone with an undetected fracture, head injury, or spinal injury can convert a minor fall into a serious one. Vital signs and a neurological check identify internal injury and orthostatic causes; moving the client first destroys the evidence needed for both.",
  o:["Correct — assess in place for injury, hemodynamics, and neurology before any movement.",
   "Moving the client before assessment risks displacing an undetected fracture or spinal injury.",
   "The provider is notified after the assessment, once findings are known and the client is safe.",
   "The client's account is documented, but it does not replace a physical assessment."],
  s:"Found on the floor means assess in place. Movement comes after the assessment, not before, however inconvenient the position is for the client or the nurse."},
 ref:"Safety · post-fall assessment before movement"}
);
