/* ============================================================================
   bank15.js — hand-authored wave 5: 30 hard items, NCLEX-RN only

   WHY THIS FILE EXISTS
     Waves 1-4 corrected blueprint share. This wave corrects difficulty. Before
     it, the bank held 20 items at d=3 out of 402 (5%), and SIC, HPM and BCC held
     none at all — so an examinee drilling here met an easier exam than the real
     one. Every item below is d=3 with b >= 0.4, weighted toward the categories
     that had no hard content.

   WHAT MAKES THESE HARD (and NCLEX-realistic)
     · two or more options are clinically defensible; only one is right *first*
     · second-order asks: not "what do you do" but "what do you do next"
     · autonomy, capacity and refusal where the instinct to intervene is wrong
     · lab sets that require synthesis rather than recall of one value
     · distractors that are correct actions in a different scenario

   DISTRIBUTION
     MOC 4 · SIC 5 · HPM 3 · PSY 4 · BCC 4 · PHA 4 · RRP 3 · PAA 3

   AUTHORING RULES OBSERVED
     · no stem token that occurs only in the key option
     · key is not systematically the longest option
     · every rationale explains the key and each distractor, plus a takeaway
   ========================================================================== */
window.NC.BANK.push(
/* ── Management of Care (blueprint 18%) ───────────────────────────── */
{id:"MOC-074", t:"single", cn:"MOC", sys:"INTG", topic:"Capacity assessment", d:3, b:0.7, cj:"analyze", tags:["capacity","autonomy","refusal"],
 stem:"A 62-year-old with dry gangrene of the right foot is alert, oriented, and able to restate the surgeon's explanation of amputation and its risks, but declines the surgery. The nurse's best action is to:",
 opts:["Document the client's understanding and support the decision to decline",
  "Request an emergency psychiatric consultation to evaluate the refusal",
  "Ask the surgeon to postpone until the client reconsiders the option",
  "Contact the client's adult child to obtain surrogate permission"],
 ans:0,
 rat:{c:"Capacity is decision-specific and demonstrated by understanding, appreciation, reasoning, and expressing a choice. This client restates the risks accurately, so the refusal is informed and must be honored. Disagreeing with a sound decision is not evidence of incapacity.",
  o:["Correct — intact capacity makes the refusal binding, and the nurse's role is to document and support.",
    "Psychiatric consultation is not triggered by an unwise but capacitated refusal.",
    "Postponement to pressure a change of mind undermines informed refusal.",
    "A surrogate is used only when the client lacks capacity; this client has it."],
  s:"A capacitated adult may refuse any treatment. Document understanding, do not coerce."},
 ref:"Management of care · informed refusal and capacity"},

{id:"MOC-075", t:"single", cn:"MOC", sys:"INTG", topic:"Emergency treatment without consent", d:3, b:0.6, cj:"prioritize", tags:["emergency","consent","implied"],
 stem:"An unconscious adult is brought to the emergency department after a motor vehicle crash with a systolic blood pressure of 68 mm Hg. No identification or family is available. The nurse understands that emergency surgery will proceed because:",
 opts:["Implied consent applies when delay would risk life or permanent harm",
  "The trauma team may waive consent in any emergency department case",
  "Two nurses may sign as witnesses to substitute for the client's consent",
  "The hospital administrator can grant consent on the client's behalf"],
 ans:0,
 rat:{c:"Implied consent exists for emergencies when the client cannot consent, no surrogate is available, and delay threatens life or limb. It rests on the presumption that a reasonable person would consent to lifesaving care — not on a blanket waiver for the setting.",
  o:["Correct — emergency doctrine covers lifesaving care when delay is dangerous.",
    "Emergency departments do not waive consent generally; capacity and surrogacy still apply.",
    "Witness signatures verify a signature; they never substitute for consent.",
    "Administrators do not hold consent authority for unconscious clients."],
  s:"Implied consent: unconscious, no surrogate, and delay endangers life or limb."},
 ref:"Management of care · consent in emergencies"},

{id:"MOC-076", t:"single", cn:"MOC", sys:"HEME", topic:"Blood transfusion refusal", d:3, b:0.75, cj:"act", tags:["refusal","autonomy","bloodless-care"],
 stem:"A hospitalized adult who is a Jehovah's Witness has a hemoglobin of 5.4 g/dL and refuses packed red blood cells. The provider orders the transfusion anyway. The nurse's priority action is to:",
 opts:["Withhold the transfusion and notify the provider of the documented refusal",
  "Start the transfusion slowly because the provider holds the order",
  "Ask the client to sign a new refusal form before questioning the order",
  "Transfer the client's care to a colleague who will give the product"],
 ans:0,
 rat:{c:"A capacitated adult's informed refusal overrides a provider order. Administering blood against a documented refusal is battery. The nurse's duty is to protect the client, refuse the order, and escalate — while still pursuing acceptable alternatives such as iron or erythropoietin.",
  o:["Correct — do not administer; report the conflict and document the refusal.",
    "An order does not authorize treatment a capacitated client has refused.",
    "Repeated forms pressure the client and do not resolve the conflict.",
    "Handing off the task transfers the ethical problem, not the duty."],
  s:"A capacitated refusal outranks a provider order. Do not administer; escalate."},
 ref:"Management of care · refusal of blood products"},

{id:"MOC-077", t:"single", cn:"MOC", sys:"PSYCH", topic:"Adolescent confidentiality and mandatory reporting", d:3, b:0.8, cj:"prioritize", tags:["confidentiality","mandated-report","adolescent"],
 stem:"A 15-year-old seen alone in a clinic confides that a parent's partner has been hitting her, and begs the nurse not to tell anyone. The nurse's best response is to:",
 opts:["Explain that suspected abuse must be reported, then make the report",
  "Promise confidentiality because the visit was arranged as private",
  "Confront the parent's partner before involving any outside agency",
  "Advise the adolescent to stay with a relative instead of reporting"],
 ans:0,
 rat:{c:"Adolescent confidentiality is broad but not absolute: suspected child abuse is a mandated-report exception in every state. The nurse must be honest about the limit rather than promise secrecy, and must report — informal workarounds leave the child in danger and expose the nurse legally.",
  o:["Correct — disclose the reporting duty, then file the report.",
    "A promise of secrecy the nurse cannot keep destroys trust and is unlawful.",
    "Confronting a suspected abuser endangers the child and the nurse.",
    "Suggesting an alternative living arrangement is not a substitute for reporting."],
  s:"Suspected child abuse is reportable regardless of a confidentiality promise."},
 ref:"Management of care · mandated reporting exceptions"},

/* ── Safety and Infection Control (blueprint 13%) ─────────────────── */
{id:"SIC-053", t:"single", cn:"SIC", sys:"REPI", topic:"Airborne and contact precautions combined", d:3, b:0.7, cj:"prioritize", tags:["isolation","tuberculosis","mdro"],
 stem:"A client with active pulmonary tuberculosis is transferred from a general ward where MRSA was also grown from a draining wound. Which room assignment is correct?",
 opts:["A negative-pressure room with contact precautions added for the wound",
  "A private room with standard precautions, since the wound is covered",
  "A cohort room with another tuberculosis client to conserve isolation rooms",
  "A positive-pressure room to protect the client from outside pathogens"],
 ans:0,
 rat:{c:"Precaution categories are additive, not exclusive. Active pulmonary tuberculosis requires airborne isolation in negative pressure with an N95, and the MRSA wound independently requires contact precautions. Cohorting is acceptable only for the same organism, and positive pressure protects an immunosuppressed client, not others.",
  o:["Correct — negative pressure for airborne, plus contact precautions for MRSA.",
    "Standard precautions do not contain airborne tuberculosis.",
    "Cohorting requires the same pathogen; the MRSA wound would cross-contaminate.",
    "Positive pressure protects the client inside, not the people around them."],
  s:"Precautions stack: airborne in negative pressure, plus contact for the MDRO wound."},
 ref:"Infection control · combining transmission-based precautions"},

{id:"SIC-054", t:"single", cn:"SIC", sys:"INTG", topic:"Disseminated herpes zoster precautions", d:3, b:0.65, cj:"analyze", tags:["varicella","isolation","immunocompromised"],
 stem:"An immunocompromised client develops vesicular lesions across three dermatomes on both sides of the torso. Which precaution does the nurse initiate?",
 opts:["Airborne and contact precautions until all lesions are crusted",
  "Contact precautions alone because zoster spreads by direct touch",
  "Droplet precautions because the virus travels in respiratory secretions",
  "Standard precautions because the lesions can be fully covered"],
 ans:0,
 rat:{c:"Localized zoster in an immunocompetent client needs only contact precautions and coverage. Disseminated disease — crossing dermatomes or bilateral — behaves like primary varicella and becomes airborne-transmissible, so airborne plus contact precautions continue until every lesion crusts.",
  o:["Correct — disseminated zoster requires airborne and contact until crusting.",
    "Contact alone misses the airborne route in disseminated disease.",
    "Varicella-zoster is not spread by droplet nuclei from casual coughing.",
    "Standard precautions are insufficient once the disease is disseminated."],
  s:"Disseminated zoster = airborne + contact until all lesions crust."},
 ref:"Infection control · varicella-zoster precautions"},

{id:"SIC-055", t:"single", cn:"SIC", sys:"INF", topic:"Occupational splash exposure", d:3, b:0.6, cj:"prioritize", tags:["occupational-exposure","ppe","bloodborne"],
 stem:"While emptying a suction canister, a nurse is splashed in the eye with blood-tinged secretions. The nurse removes goggles and should next:",
 opts:["Flush the eye with water or saline for fifteen minutes, then report",
  "Report to employee health first so prophylaxis is not delayed",
  "Instill antibiotic drops and continue the shift until relieved",
  "Wait to see whether the source client tests positive"],
 ans:0,
 rat:{c:"A mucous membrane exposure is first treated as a contamination event: immediate, prolonged irrigation dilutes and removes the fluid. Reporting and risk assessment follow, but prophylaxis windows are hours long while irrigation takes minutes — and delay at the eye is what causes injury.",
  o:["Correct — irrigate the mucous membrane first, then report the exposure.",
    "Reporting matters, but the eye needs immediate irrigation.",
    "Antibiotic drops do not address bloodborne pathogen exposure.",
    "Waiting for source results forfeits the post-exposure prophylaxis window."],
  s:"Mucous membrane splash: irrigate fifteen minutes, then report and assess risk."},
 ref:"Infection control · occupational exposure response"},

{id:"SIC-056", t:"single", cn:"SIC", sys:"INF", topic:"Surgical count discrepancy", d:3, b:0.7, cj:"prioritize", tags:["surgical-safety","retained-item","escalation"],
 stem:"At wound closure the circulating nurse's sponge count is incorrect. The surgeon states the count is wrong and wants to finish the operation. The nurse's best action is to:",
 opts:["Refuse to close until the count is resolved or imaging rules out a retained item",
  "Document the surgeon's statement and allow the closure to proceed",
  "Repeat the count once and accept it if the second count is correct",
  "Report the discrepancy after the client leaves the operating room"],
 ans:0,
 rat:{c:"A retained foreign body is a never event. An unresolved count blocks closure until the item is found or radiography excludes it; a surgeon's opinion does not settle a factual count. The nurse has both the authority and the duty to escalate through the chain of command.",
  o:["Correct — an unresolved count stops closure until found or imaged.",
    "Documenting an override leaves the client with a possible retained sponge.",
    "A corrected repeat count can still be wrong if the first item is missing.",
    "Reporting afterward makes retrieval harder and injury more likely."],
  s:"Wrong count = no closure. Resolve it, or image before closing."},
 ref:"Safety · retained surgical item prevention"},

{id:"SIC-057", t:"single", cn:"SIC", sys:"INF", topic:"Source status unknown after sharps injury", d:3, b:0.65, cj:"act", tags:["post-exposure-prophylaxis","hiv","timing"],
 stem:"A nurse sustains a hollow-bore needlestick from a discarded needle whose source cannot be identified. Baseline testing is drawn. The nurse understands that antiretroviral prophylaxis should:",
 opts:["Be started as soon as possible, ideally within two hours of exposure",
  "Wait for the source client's test result before the first dose is given",
  "Begin only if symptoms of seroconversion develop within six weeks",
  "Be deferred because an unidentified source cannot be risk stratified"],
 ans:0,
 rat:{c:"Post-exposure prophylaxis is time-critical: benefit falls sharply after the first hours and it is generally not started beyond 72 hours. An unknown source is treated as potentially positive rather than as no risk, and waiting for seroconversion means waiting past the window in which prophylaxis works.",
  o:["Correct — start prophylaxis immediately, ideally within two hours.",
    "Waiting for source results can exceed the effective window.",
    "Symptoms appear weeks later, long after prophylaxis can help.",
    "Unknown source means presumed risk, not absent risk."],
  s:"Needlestick with unknown source: start HIV prophylaxis within hours, not days."},
 ref:"Infection control · post-exposure prophylaxis timing"},

/* ── Health Promotion and Maintenance (blueprint 9%) ──────────────── */
{id:"HPM-037", t:"single", cn:"HPM", sys:"NEURO", topic:"Lead poisoning screening", d:3, b:0.6, cj:"analyze", tags:["pediatric","environmental","screening"],
 stem:"A 22-month-old living in a pre-1950 home with peeling paint has a hemoglobin of 9.4 g/dL and a capillary lead level of 26 mcg/dL. The nurse's priority action is to:",
 opts:["Arrange a confirmatory venous lead level and a home environmental assessment",
  "Begin oral iron and recheck the hemoglobin in three months",
  "Reassure the parent that capillary samples are frequently falsely high",
  "Start chelation therapy immediately at this lead level"],
 ans:0,
 rat:{c:"Capillary specimens are easily contaminated by lead on the skin, so any elevated result must be confirmed venously. Concurrently, the source must be found — paint dust is the usual cause — because removing exposure is the primary treatment. Iron deficiency also increases lead absorption, so the anemia matters but is not the first action.",
  o:["Correct — confirm venously and identify the environmental source.",
    "Iron treats the anemia but ignores a toxic exposure that needs confirmation.",
    "False positives are common, but dismissal without confirmation is unsafe.",
    "Chelation is generally reserved for substantially higher confirmed levels."],
  s:"High capillary lead: confirm with a venous draw and find the source."},
 ref:"Health promotion · childhood lead exposure"},

{id:"HPM-038", t:"single", cn:"HPM", sys:"REPI", topic:"Teratogen exposure in the first trimester", d:3, b:0.7, cj:"analyze", tags:["pregnancy","teratogen","isotretinoin"],
 stem:"A client at eight weeks' gestation reports she has been taking isotretinoin for acne and stopped it two days ago when she learned she was pregnant. The nurse's priority action is to:",
 opts:["Refer urgently to maternal-fetal medicine and document the exposure window",
  "Reassure her because the medication was stopped before the second trimester",
  "Advise termination of the pregnancy during the same visit",
  "Recheck a pregnancy test in four weeks before taking any further action"],
 ans:0,
 rat:{c:"Isotretinoin is a potent teratogen, and organogenesis occurs during the first trimester — exactly when this exposure happened. The client needs urgent specialist counseling about risk and options. Reassurance is unfounded, and neither directing her decision nor delaying assessment is appropriate nursing action.",
  o:["Correct — urgent specialist referral with an accurate exposure timeline.",
    "First-trimester exposure is the highest-risk period, not a safe one.",
    "Directing the client's decision is outside the nurse's role.",
    "Delay defers counseling during the period when decisions must be made."],
  s:"Known teratogen in the first trimester: urgent specialist referral, never reassurance."},
 ref:"Health promotion · teratogenic exposure"},

{id:"HPM-039", t:"single", cn:"HPM", sys:"PSYCH", topic:"Intimate partner violence safety planning", d:3, b:0.65, cj:"generate", tags:["screening","safety-plan","advocacy"],
 stem:"A client discloses that her partner has begun threatening her and has access to a firearm. The nurse's priority action is to:",
 opts:["Build a safety plan with the client and offer advocacy resources now",
  "Encourage her to leave immediately while she is still at the clinic",
  "Confront the partner during the visit to establish limits",
  "Document the disclosure and schedule a routine follow-up visit"],
 ans:0,
 rat:{c:"Lethality risk rises sharply when a firearm is present and when a survivor attempts to leave. Safety planning is client-led, practical, and done now — documents, keys, a code word, a route. Pressuring immediate departure can precipitate violence, and confronting the partner removes the client's protection.",
  o:["Correct — immediate, client-directed safety planning with advocacy support.",
    "Forced departure is the highest-risk moment and must be the client's choice.",
    "Confronting the abuser endangers the client after she goes home.",
    "Deferring action ignores an acute lethality risk."],
  s:"Firearm plus threats means high lethality risk: safety plan now, client leads."},
 ref:"Health promotion · intimate partner violence"},

/* ── Psychosocial Integrity (blueprint 9%) ────────────────────────── */
{id:"PSY-038", t:"single", cn:"PSY", sys:"PSYCH", topic:"Post-electroconvulsive therapy care", d:3, b:0.55, cj:"prioritize", tags:["ect","airway","post-anesthesia"],
 stem:"Ten minutes after electroconvulsive therapy, a client is drowsy, has an oxygen saturation of 93% on room air, and has coarse breath sounds with pooled secretions. The nurse's first action is to:",
 opts:["Position the client on the side and suction the oral cavity",
  "Apply oxygen at four liters per minute by nasal cannula",
  "Notify the anesthesia provider of the falling saturation",
  "Recheck the saturation after the client is fully awake"],
 ans:0,
 rat:{c:"After a generalized seizure and brief anesthesia, airway protection comes first. Pooling secretions with coarse sounds indicate the client cannot clear them, so lateral positioning and suction remove the obstruction — the cause. Oxygen over an obstructed airway treats the number, not the problem.",
  o:["Correct — clear the airway by positioning and suctioning first.",
    "Oxygen does not help while secretions still obstruct the airway.",
    "Notification follows once the airway is managed.",
    "Waiting through hypoxemia risks aspiration and further decline."],
  s:"Post-ECT airway first: turn, suction, then oxygen and reassess."},
 ref:"Psychosocial · post-ECT recovery"},

{id:"PSY-039", t:"single", cn:"PSY", sys:"PSYCH", topic:"Command hallucinations", d:3, b:0.8, cj:"prioritize", tags:["psychosis","risk-assessment","safety"],
 stem:"A client admitted with schizophrenia states, 'The voices keep telling me to hurt myself, and it is getting hard to say no.' The nurse's priority action is to:",
 opts:["Ask directly about a plan and means, and initiate close observation",
  "Reassure the client that the voices are not real and cannot cause harm",
  "Redirect the client to a group activity to reduce the preoccupation",
  "Document the hallucination and report it during the next shift handoff"],
 ans:0,
 rat:{c:"Command hallucinations to self-harm carry a high risk of acting out, and the client's own report of weakening resistance raises that risk further. Direct assessment of plan and means plus continuous observation is required. Reality-testing arguments, distraction, and delayed reporting all leave an acute risk unmanaged.",
  o:["Correct — assess plan and means now and place the client on close observation.",
    "Arguing with the hallucination does not reduce the risk of acting on it.",
    "Redirecting leaves an escalating risk unobserved.",
    "Deferring to handoff delays intervention on an active safety threat."],
  s:"Command hallucinations to self-harm: ask about plan and means, observe continuously."},
 ref:"Psychosocial · acute suicide risk"},

{id:"PSY-040", t:"single", cn:"PSY", sys:"PSYCH", topic:"Countertransference", d:3, b:0.7, cj:"analyze", tags:["therapeutic-use-of-self","boundaries","supervision"],
 stem:"A nurse notices growing irritation toward a client who reminds the nurse of a demanding parent, and begins avoiding the client's room. The nurse's best action is to:",
 opts:["Discuss the reaction in supervision and continue to provide the assigned care",
  "Request reassignment so personal feelings do not influence the care",
  "Conceal the irritation because professional nurses are unaffected by clients",
  "Tell the client about the resemblance in order to build rapport"],
 ans:0,
 rat:{c:"This is countertransference — the nurse's own history shaping the response. The professional move is to recognize it, take it to supervision, and keep caring for the client. Avoidance is already affecting care; disclosure transfers the nurse's issue onto the client and breaches therapeutic boundaries.",
  o:["Correct — name it in supervision and keep the assignment intact.",
    "Reassignment avoids the problem and confirms the avoidance already occurring.",
    "Suppression prevents recognition and makes the reaction harder to manage.",
    "Disclosing personal reactions uses the client to meet the nurse's needs."],
  s:"Countertransference: recognize it, take it to supervision, keep caring."},
 ref:"Psychosocial · therapeutic use of self"},

{id:"PSY-041", t:"single", cn:"PSY", sys:"PSYCH", topic:"Criteria for involuntary hospitalization", d:3, b:0.75, cj:"analyze", tags:["legal","civil-commitment","risk"],
 stem:"A client with major depression refuses voluntary admission. Which finding most strongly supports involuntary hospitalization?",
 opts:["A specific plan with a stockpiled supply of medication and access to it",
  "A prior psychiatric admission three years earlier for a depressive episode",
  "Severely depressed affect with slowed speech during the assessment",
  "A family request that the client remain hospitalized for observation"],
 ans:0,
 rat:{c:"Civil commitment generally requires mental illness plus danger to self or others, or grave disability. A specific plan with means and access is direct evidence of imminent danger. History, observable severity, and family preference may inform judgment but do not by themselves meet the legal threshold.",
  o:["Correct — plan, means, and access establish imminent danger to self.",
    "A remote admission is history, not present danger.",
    "Depressed affect alone does not establish imminent risk.",
    "Family wishes do not substitute for the statutory criteria."],
  s:"Involuntary hold needs present danger: a specific plan with means and access."},
 ref:"Psychosocial · civil commitment criteria"},

/* ── Basic Care and Comfort (blueprint 9%) ────────────────────────── */
{id:"BCC-036", t:"single", cn:"BCC", sys:"GI", topic:"Aspiration during enteral feeding", d:3, b:0.6, cj:"prioritize", tags:["enteral","aspiration","positioning"],
 stem:"A client receiving continuous nasogastric tube feeding develops a new cough, wet voice quality, and an oxygen saturation that has fallen from 96% to 89%. The nurse's first action is to:",
 opts:["Stop the feeding and raise the head of the bed to at least 45 degrees",
  "Auscultate the lung fields and document the assessment findings",
  "Slow the feeding rate and recheck the saturation in thirty minutes",
  "Obtain a chest radiograph order to evaluate for aspiration"],
 ans:0,
 rat:{c:"These findings indicate active aspiration. The first action removes the source and uses gravity — stop the infusion and elevate the head. Assessment, rate reduction, and imaging all continue to deliver formula into a compromised airway while they wait.",
  o:["Correct — stop the feed and elevate the head of the bed immediately.",
    "Assessment is important but does not stop ongoing aspiration.",
    "A slower rate still delivers formula into an unprotected airway.",
    "Imaging confirms the diagnosis later; it does not prevent further aspiration."],
  s:"Suspected tube-feeding aspiration: stop the feed and elevate first."},
 ref:"Basic care · enteral feeding complications"},

{id:"BCC-037", t:"single", cn:"BCC", sys:"PSYCH", topic:"Terminal restlessness", d:3, b:0.65, cj:"analyze", tags:["palliative","delirium","symptom-management"],
 stem:"A client in the last days of life becomes agitated, pulls at bedding, and appears distressed, with no pain reported and a full bladder on assessment. The nurse's best initial action is to:",
 opts:["Treat the reversible cause by relieving the urinary retention",
  "Administer a scheduled opioid to control the presumed discomfort",
  "Apply soft wrist restraints to prevent the client from falling",
  "Increase stimulation so the client remains oriented to the room"],
 ans:0,
 rat:{c:"Terminal restlessness is frequently driven by a reversible trigger — a full bladder, constipation, hypoxia, or medication effect. A palpable bladder here is the most likely cause, and relieving it treats the source. Sedation is reserved for refractory distress, and restraints or stimulation worsen agitation.",
  o:["Correct — identify and relieve the reversible trigger first.",
    "Opioids target pain, which this client does not report.",
    "Restraints increase agitation and are not a substitute for treating the cause.",
    "Added stimulation escalates agitation in a dying client."],
  s:"Terminal restlessness: look for a reversible cause — bladder, bowel, hypoxia, drugs."},
 ref:"Basic care · end-of-life symptom management"},

{id:"BCC-038", t:"single", cn:"BCC", sys:"PSYCH", topic:"Palliative sedation and double effect", d:3, b:0.8, cj:"analyze", tags:["ethics","palliative","double-effect"],
 stem:"A dying client has refractory dyspnea despite maximal therapy. The family worries that increasing sedation to ease the distress will hasten death. The nurse's best response is based on which principle?",
 opts:["An action intended to relieve suffering is ethical even if death is a foreseeable risk",
  "Sedation may never be increased once death is expected within days",
  "Relieving dyspnea at this stage is a form of hastening death and requires consent",
  "The dose may be raised only if the family formally accepts the risk of death"],
 ans:0,
 rat:{c:"The principle of double effect holds that an act with a good intent — relieving refractory suffering — is ethically permissible even when a foreseen but unintended bad effect may follow. The distinction rests on intent and on proportionate dosing, not on a prohibition or on family authorization.",
  o:["Correct — intent to relieve suffering justifies proportionate sedation.",
    "There is no rule barring titration in the last days of life.",
    "Treating dyspnea is symptom relief, not hastening death by intent.",
    "Consent for comfort care does not require accepting a risk of death."],
  s:"Double effect: relieving refractory suffering is ethical even if death is foreseen."},
 ref:"Basic care · ethics at the end of life"},

{id:"BCC-039", t:"single", cn:"BCC", sys:"NEURO", topic:"Targeted temperature management", d:3, b:0.6, cj:"act", tags:["post-arrest","hypothermia","neuroprotection"],
 stem:"A client after cardiac arrest is undergoing targeted temperature management at 33 degrees C. Shivering is noted. The nurse's priority action is to:",
 opts:["Report the shivering so it can be controlled, since it raises oxygen demand",
  "Increase the blanket coverage to reduce the shivering response",
  "Rewarm the client gradually because shivering indicates overcooling",
  "Document the finding as an expected response to therapeutic hypothermia"],
 ans:0,
 rat:{c:"Shivering is expected during cooling but not benign: it markedly increases metabolic rate and oxygen consumption, undermining the neuroprotective goal and stressing a post-arrest heart. It is treated — usually with sedation or specific agents — not covered, not reversed, and not merely recorded.",
  o:["Correct — shivering must be suppressed because it raises oxygen consumption.",
    "Blankets oppose the cooling target and do not stop shivering.",
    "Rewarming abandons the therapy the shivering is a side effect of.",
    "Expected does not mean acceptable; it still needs treatment."],
  s:"During targeted cooling, shivering must be controlled — it drives up oxygen demand."},
 ref:"Basic care · post-cardiac arrest care"},

/* ── Pharmacological & Parenteral Therapies (blueprint 16%) ───────── */
{id:"PHA-074", t:"single", cn:"PHA", sys:"HEME", topic:"Heparin to warfarin bridging", d:3, b:0.7, cj:"analyze", tags:["anticoagulation","bridging","protein-c"],
 stem:"A client with deep vein thrombosis receives intravenous heparin and warfarin together for five days. The nurse understands the overlap is necessary because:",
 opts:["Warfarin initially lowers protein C, so full anticoagulation depends on heparin first",
  "Warfarin requires five days to be absorbed from the gastrointestinal tract",
  "Heparin prevents the bleeding risk that warfarin causes during the first week",
  "Combining both agents reduces the total anticoagulant dose required"],
 ans:0,
 rat:{c:"Warfarin inhibits vitamin K dependent factors, and protein C — a natural anticoagulant — has the shortest half-life. Early warfarin therefore produces a transient hypercoagulable state, so heparin must continue until the international normalized ratio is therapeutic for at least 24 hours.",
  o:["Correct — the early protein C drop is why heparin bridges the first days.",
    "Warfarin is absorbed quickly; the delay is factor half-life, not absorption.",
    "Heparin does not offset warfarin bleeding risk; both agents add to it.",
    "The overlap is about timing of factor decline, not dose sparing."],
  s:"Bridge warfarin with heparin until the INR is therapeutic — early protein C falls first."},
 ref:"Pharmacology · anticoagulation initiation"},

{id:"PHA-075", t:"single", cn:"PHA", sys:"INTG", topic:"Chemotherapy extravasation antidote", d:3, b:0.7, cj:"act", tags:["vesicant","extravasation","antidote"],
 stem:"A client receiving intravenous doxorubicin reports burning at the site, and the nurse notes swelling with no blood return. After stopping the infusion, the nurse's next action is to:",
 opts:["Aspirate residual drug from the catheter before removing it",
  "Flush the line with normal saline to disperse the remaining drug",
  "Apply warm compresses to increase local blood flow to the area",
  "Elevate the limb and remove the catheter immediately without aspirating"],
 ans:0,
 rat:{c:"Doxorubicin is a vesicant that causes tissue necrosis. After stopping the infusion, residual drug is aspirated through the existing catheter to remove as much as possible; only then is the line removed. Flushing drives more vesicant into the tissue, and cold — not warmth — is used for anthracyclines to limit spread.",
  o:["Correct — aspirate residual drug through the catheter, then remove it.",
    "Flushing forces additional vesicant into surrounding tissue.",
    "Warmth increases spread; anthracycline extravasation uses cold.",
    "Pulling the catheter first forfeits the chance to aspirate the drug."],
  s:"Vesicant extravasation: stop, aspirate through the line, then remove it."},
 ref:"Pharmacology · vesicant administration"},

{id:"PHA-076", t:"single", cn:"PHA", sys:"PSYCH", topic:"Clozapine agranulocytosis monitoring", d:3, b:0.7, cj:"prioritize", tags:["antipsychotic","neutropenia","monitoring"],
 stem:"A client taking clozapine for treatment-resistant schizophrenia reports a sore throat and has a temperature of 38.8 degrees C. The absolute neutrophil count is 900 per microliter, down from 2,400 last month. The nurse's priority action is to:",
 opts:["Hold the next dose and notify the prescriber of the falling count",
  "Give acetaminophen and repeat the temperature in four hours",
  "Continue the scheduled dose because the count is above 500",
  "Recommend a throat culture and continue the current regimen"],
 ans:0,
 rat:{c:"Clozapine can cause life-threatening agranulocytosis, and infection with a rapidly falling neutrophil count is the presentation that defines it. The dose is held and the prescriber notified before the count falls further. A single value above an arbitrary floor is reassurance without trend, and the trend here is steep.",
  o:["Correct — hold the drug and escalate a falling count with infection.",
    "An antipyretic treats the fever while the marrow suppression continues.",
    "A static threshold ignores a steep drop, which is the danger signal.",
    "Culturing without holding the drug risks progression to agranulocytosis."],
  s:"Clozapine plus fever and a falling neutrophil count: hold the dose and report now."},
 ref:"Pharmacology · clozapine hematologic monitoring"},

{id:"PHA-077", t:"single", cn:"PHA", sys:"PSYCH", topic:"Serotonin syndrome", d:3, b:0.75, cj:"analyze", tags:["interaction","serotonin","emergency"],
 stem:"A client taking fluoxetine for depression is prescribed linezolid for a resistant infection and then develops agitation, a temperature of 38.9 degrees C, tremor, and clonus at the ankles. The nurse's priority action is to:",
 opts:["Stop both medications and notify the provider of suspected serotonin syndrome",
  "Administer acetaminophen and recheck the temperature in one hour",
  "Reduce the fluoxetine dose because the symptoms suggest an adverse effect",
  "Document the findings as an expected reaction to a new antibiotic"],
 ans:0,
 rat:{c:"Linezolid is a weak monoamine oxidase inhibitor; combined with a selective serotonin reuptake inhibitor it can precipitate serotonin syndrome — the triad of mental status change, autonomic instability, and neuromuscular hyperactivity such as clonus. Both agents must stop at once. This is not a simple fever or an expected reaction.",
  o:["Correct — stop the interacting drugs immediately and escalate.",
    "Antipyretics treat a number while the underlying toxicity continues.",
    "Tapering one agent still leaves the dangerous combination in place.",
    "Clonus with hyperthermia is a toxic emergency, not an expected effect."],
  s:"SSRI plus linezolid risks serotonin syndrome: clonus, hyperthermia — stop both."},
 ref:"Pharmacology · dangerous drug interactions"},

/* ── Reduction of Risk Potential (blueprint 12%) ──────────────────── */
{id:"RRP-055", t:"single", cn:"RRP", sys:"RESP", topic:"Mixed acid-base disorder", d:3, b:0.8, cj:"analyze", tags:["abg","mixed-disorder","interpretation"],
 stem:"A client with chronic kidney disease and septic shock has these results: pH 7.28, PaCO2 24 mm Hg, HCO3 12 mEq/L, and a lactate of 6.1 mmol/L. The nurse interprets this as:",
 opts:["Metabolic acidosis with appropriate respiratory compensation",
  "Respiratory acidosis from inadequate alveolar ventilation",
  "A mixed metabolic acidosis and concurrent respiratory acidosis",
  "Metabolic alkalosis with compensatory carbon dioxide retention"],
 ans:0,
 rat:{c:"The low pH with low bicarbonate identifies metabolic acidosis, driven here by lactate and renal failure. Winter's formula predicts a PaCO2 near 1.5 x 12 + 8 = 26, and the measured 24 is close, so the low carbon dioxide is compensation working correctly rather than a second disorder.",
  o:["Correct — metabolic acidosis with the expected respiratory compensation.",
    "Respiratory acidosis would show a carbon dioxide above 40 mm Hg.",
    "The carbon dioxide matches the predicted compensation, so it is not mixed.",
    "Alkalosis is excluded by a pH below 7.35."],
  s:"Check compensation with Winter's formula before calling a disorder mixed."},
 ref:"Reduction of risk · acid-base interpretation"},

{id:"RRP-056", t:"single", cn:"RRP", sys:"RESP", topic:"Ventilator high-pressure alarm", d:3, b:0.7, cj:"prioritize", tags:["mechanical-ventilation","alarm","troubleshooting"],
 stem:"A ventilated client's high-pressure alarm sounds. The client is agitated, the peak inspiratory pressure is elevated, and breath sounds are diminished on the right with tracheal deviation to the left. The nurse's first action is to:",
 opts:["Disconnect the ventilator and ventilate manually with a bag-valve device",
  "Silence the alarm and increase the sedation infusion rate",
  "Suction the endotracheal tube to clear a probable mucous obstruction",
  "Increase the positive end-expiratory pressure to improve oxygenation"],
 ans:0,
 rat:{c:"Unilateral diminished breath sounds with tracheal deviation away from that side indicate tension pneumothorax, a life threat. The client is first taken off the ventilator and bagged manually to maintain ventilation while the cause is treated. Suctioning assumes an obstruction the findings contradict, and sedation masks the emergency.",
  o:["Correct — bag manually to secure ventilation, then treat the pneumothorax.",
    "More sedation hides the cause while the client deteriorates.",
    "Suctioning does not address tracheal deviation or absent breath sounds.",
    "Raising PEEP can worsen a tension pneumothorax."],
  s:"High-pressure alarm plus deviation: suspect tension pneumothorax, bag manually first."},
 ref:"Reduction of risk · mechanical ventilation emergencies"},

{id:"RRP-057", t:"single", cn:"RRP", sys:"REN", topic:"Dialysis disequilibrium syndrome", d:3, b:0.7, cj:"analyze", tags:["hemodialysis","cerebral-edema","complication"],
 stem:"Near the end of a first hemodialysis treatment, a client develops headache, nausea, rising blood pressure, and increasing confusion. The nurse's priority action is to:",
 opts:["Slow or stop the dialysis and notify the provider immediately",
  "Administer an antiemetic and continue the planned treatment time",
  "Increase the ultrafiltration rate to remove the excess fluid",
  "Reassure the client that these symptoms resolve after treatment"],
 ans:0,
 rat:{c:"Dialysis disequilibrium syndrome occurs when urea falls faster in blood than in brain tissue, drawing water into the brain and causing cerebral edema. It is most common in a first or aggressive treatment. Slowing or stopping the exchange limits the osmotic shift; continuing, or removing more fluid, worsens it.",
  o:["Correct — slow or stop dialysis and report these neurologic changes at once.",
    "An antiemetic treats one symptom while cerebral edema progresses.",
    "More ultrafiltration increases the osmotic gradient and the risk.",
    "Reassurance delays treatment of a potentially fatal complication."],
  s:"Headache and confusion during a first dialysis: slow it and call — think cerebral edema."},
 ref:"Reduction of risk · hemodialysis complications"},

/* ── Physiological Adaptation (blueprint 14%) ─────────────────────── */
{id:"PAA-070", t:"single", cn:"PAA", sys:"RESP", topic:"ARDS and positive end-expiratory pressure", d:3, b:0.7, cj:"analyze", tags:["ards","oxygenation","recruitment"],
 stem:"A client with acute respiratory distress syndrome has an oxygen saturation of 86% on 100% oxygen, and chest imaging shows diffuse bilateral infiltrates. The nurse understands that raising positive end-expiratory pressure improves oxygenation primarily by:",
 opts:["Recruiting collapsed alveoli and reducing intrapulmonary shunt",
  "Increasing the tidal volume delivered with each breath",
  "Lowering the fraction of inspired oxygen that is required",
  "Decreasing the client's intrinsic respiratory drive"],
 ans:0,
 rat:{c:"Acute respiratory distress syndrome produces atelectasis and fluid-filled alveoli, so blood passes unventilated areas — a shunt that supplemental oxygen cannot correct. Positive end-expiratory pressure splints alveoli open, recruits them, and reduces the shunt. Lower inspired oxygen may follow but is a consequence, not the mechanism.",
  o:["Correct — PEEP recruits alveoli and corrects shunt-driven hypoxemia.",
    "Tidal volume is set separately and is not the goal of PEEP.",
    "Reducing inspired oxygen is a result of better recruitment, not the cause.",
    "PEEP does not act on respiratory drive."],
  s:"In ARDS, hypoxemia is shunt; PEEP recruits alveoli, oxygen alone will not fix it."},
 ref:"Physiological adaptation · ARDS management"},

{id:"PAA-071", t:"single", cn:"PAA", sys:"GI", topic:"Hepatorenal syndrome", d:3, b:0.75, cj:"analyze", tags:["cirrhosis","kidney-injury","ascites"],
 stem:"A client with advanced cirrhosis and large-volume ascites develops a rising creatinine with a urine sodium below 10 mEq/L and a bland urine sediment. Which interpretation is most consistent?",
 opts:["Hepatorenal syndrome driven by renal vasoconstriction and low perfusion",
  "Acute tubular necrosis from prolonged hypotension",
  "Prerenal azotemia that will respond to simple fluid restriction",
  "Postrenal obstruction caused by the tense ascites"],
 ans:0,
 rat:{c:"In hepatorenal syndrome, splanchnic vasodilation and low effective circulating volume trigger intense renal vasoconstriction. The kidney is structurally intact, so urine sodium stays very low and the sediment stays bland — the pattern here. Acute tubular necrosis produces muddy casts and higher urine sodium, and fluid restriction worsens perfusion.",
  o:["Correct — renal vasoconstriction with an intact tubule and very low urine sodium.",
    "Tubular necrosis shows granular casts and urine sodium above 40 mEq/L.",
    "Restricting fluid lowers perfusion further in this physiology.",
    "Ascites does not obstruct the urinary tract."],
  s:"Cirrhosis plus rising creatinine, low urine sodium, bland sediment = hepatorenal syndrome."},
 ref:"Physiological adaptation · hepatorenal syndrome"},

{id:"PAA-072", t:"single", cn:"PAA", sys:"NEURO", topic:"Cerebral perfusion pressure", d:3, b:0.8, cj:"analyze", tags:["icp","cpp","hemodynamics"],
 stem:"A client with a traumatic brain injury has a mean arterial pressure of 72 mm Hg and an intracranial pressure of 24 mm Hg. The cerebral perfusion pressure is:",
 opts:["48 mm Hg, which is below the target and requires intervention",
  "96 mm Hg, which is adequate for cerebral blood flow",
  "72 mm Hg, since cerebral perfusion equals the mean arterial pressure",
  "24 mm Hg, since intracranial pressure determines the perfusion"],
 ans:0,
 rat:{c:"Cerebral perfusion pressure equals mean arterial pressure minus intracranial pressure: 72 - 24 = 48 mm Hg. The usual target is at least 60 mm Hg, so this client is underperfused and needs either a higher mean arterial pressure or a lower intracranial pressure — often both.",
  o:["Correct — 72 minus 24 is 48, below the usual 60 mm Hg target.",
    "Adding the two values is not the formula for perfusion pressure.",
    "Mean arterial pressure alone ignores the opposing intracranial pressure.",
    "Intracranial pressure opposes perfusion; it does not define it."],
  s:"CPP = MAP - ICP, target at least 60. Raise the MAP, lower the ICP, or both."},
 ref:"Physiological adaptation · intracranial hemodynamics"}
);
