/* RN Ready — item bank v3f · part 6 (bank growth toward the 2026 blueprints).
   Weighted to Coordinated Care / Management of Care (the PN plan's largest
   category at 18–24% and the RN's at 15–21%) and Safety, with Pharm, Risk
   Reduction, Comfort, Psychosocial and Health Promotion rounding out.
   MOC +12 · SIC +6 · PHA +4 · RRP +3 · BCC +2 · PSY +2 · HPM +1.
   The digoxin-toxicity variant group grows to 3 members.                    */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Management of Care / Coordinated Care ───────────────────────── */
{id:"MOC-024", t:"single", cn:"MOC", sys:"HEME", topic:"Supervision / scope", d:2, b:0.3, cj:"act", tags:["supervision","scope","blood-products"],
 stem:"An LPN tells the RN, “I'm caught up — should I go ahead and start the blood transfusion in room 12?” Which response reflects correct scope and supervision?",
 opts:["The RN starts the blood; the LPN may monitor the client once it is running per facility policy",
  "The LPN may start it since the client is stable and the LPN is experienced",
  "The LPN starts it and the RN verifies the labels afterward",
  "Both nurses check the blood together, then the LPN runs it alone"],
 ans:0,
 rat:{c:"Blood product administration is an RN-level intervention in most practice acts and policies; the RN initiates and takes the first vital-sign cycle, after which routine monitoring may be delegated where policy allows.",
  o:["Correct — RN starts high-acuity therapies; stable monitoring may be shared per policy.",
     "Experience does not expand the LPN's legal scope for blood administration.",
     "Verifying labels after the fact inverts safety — checks precede infusion.",
     "Co-checking is right, but the LPN does not independently run blood."],
  s:"Scope is set by law and policy, not by workload or experience: RNs start blood, then delegate the watching."},
 ref:"Supervision · blood product administration"},

{id:"MOC-025", t:"multi", cn:"MOC", sys:"GI", topic:"Delegation to LPN", d:2, b:0.2, cj:"generate", tags:["delegation","scope","lpn"],
 stem:"The RN is planning care for a stable medical unit. Which tasks may be delegated to an LPN/VN? Select all that apply.",
 opts:["Administer an oral antihypertensive to a stable client",
  "Perform the initial admission assessment on a new client",
  "Reinforce teaching the RN started about ostomy care",
  "Administer an IM antibiotic to a stable client",
  "Revise a client's plan of care after a condition change",
  "Collect a clean-catch urine specimen"],
 ans:[0,2,3,5],
 rat:{c:"LPNs/VNs handle routine medication administration (oral/IM) for stable clients, reinforce prior teaching, and collect specimens. Initial assessments, care-plan revision, and first-time teaching require the RN.",
  o:["Correct — routine oral meds to stable clients are within LPN scope.",
     "The initial (admission) assessment is non-delegatable RN work.",
     "Correct — reinforcing teaching the RN began is LPN-appropriate.",
     "Correct — IM medications to stable clients are routine LPN tasks.",
     "Care-plan revision after a change requires RN judgment.",
     "Correct — specimen collection is a standard delegated task."],
  s:"LPN line: give meds, reinforce teaching, collect data. RN line: assess initially, analyze, plan, teach first."},
 ref:"Delegation · LPN/VN scope"},

{id:"MOC-026", t:"single", cn:"MOC", sys:"CV", topic:"UAP reports / escalation", d:1, b:-0.1, cj:"recognize", tags:["delegation","assessment"],
 stem:"Which finding reported by a UAP measuring vital signs must the RN assess personally first?",
 opts:["A heart rate of 118/min in a client who was ambulating 10 minutes ago",
  "A blood pressure of 168/98 mm Hg in a client with a history of hypertension",
  "A respiratory rate of 26/min in a client receiving oxygen",
  "An oral temperature of 99.2 °F (37.3 °C) in a postoperative client"],
 ans:2,
 rat:{c:"A respiratory rate of 26/min in a client already on oxygen signals possible respiratory deterioration — the RN assesses immediately. Tachycardia after activity and low-grade post-op fever have benign explanations; the hypertensive reading needs follow-up but the airway/breathing concern leads.",
  o:["Expected sinus tachycardia after ambulation — recheck after rest, not an emergency.",
     "Above baseline but chronic and not the ABC threat; recheck and review meds.",
     "Correct — tachypnea ON oxygen means the client is working to compensate: assess now.",
     "Low-grade post-op temperature is common — monitor, hydrate, encourage splinted coughing."],
  s:"Triage UAP reports by ABC: breathing problems outrate circulation and temperature every time."},
 ref:"Escalation · prioritizing UAP reports"},

{id:"MOC-027", t:"single", cn:"MOC", sys:"ENDO", topic:"Triage / call-backs", d:2, b:0.45, cj:"prioritize", tags:["triage","prioritize","telephone"],
 stem:"A clinic nurse is returning four client calls. Which client does the nurse call back FIRST?",
 opts:["A client with type 1 diabetes reporting a 2-day history of blood glucose readings above 250 mg/dL and mild thirst",
  "A client 5 days post-appendectomy reporting new redness and warmth at the incision",
  "A client with heart failure reporting a 1.4 kg (3 lb) weight gain over 2 days",
  "A client on chemotherapy reporting a temperature of 100.8 °F (38.2 °C)"],
 ans:3,
 rat:{c:"Fever in a neutropenic-risk chemotherapy client is an oncologic emergency — same-hour evaluation and cultures. The other three need prompt same-day follow-up but none is immediately life-threatening.",
  o:["Hyperglycemia with mild symptoms needs same-day adjustment guidance.",
     "Early surgical-site infection needs prompt assessment — but hours, not minutes.",
     "Modest fluid gain needs a diuretic review call-back today.",
     "Correct — chemo + fever = presumed neutropenic sepsis until proven otherwise."],
  s:"Chemotherapy + fever goes to the top of every callback list; infection in the immunosuppressed moves at sepsis speed."},
 ref:"Telephone triage · oncologic emergencies"},

{id:"MOC-028", t:"single", cn:"MOC", sys:"CV", topic:"Case management", d:1, b:-0.15, cj:"generate", tags:["case-management","discharge"],
 stem:"Which client is the strongest candidate for a referral to the case manager before discharge planning begins?",
 opts:["A client with heart failure readmitted twice in 60 days who is unsure how to afford medications",
  "A client recovering uneventfully 1 day after an appendectomy",
  "A client with a first-degree burn being discharged with a dressing change schedule",
  "A client scheduled for a routine colonoscopy next month"],
 ans:0,
 rat:{c:"Readmission + a stated social/financial barrier is the classic case-management trigger — medication access, home support, and follow-up coordination decide whether this client stays out of the hospital.",
  o:["Correct — readmission pattern + affordability barrier = case management referral.",
     "Uncomplicated post-op course needs teaching, not intensive case management.",
     "A simple dressing plan is standard discharge teaching.",
     "Routine screening needs scheduling, not case management."],
  s:"Case management clues: readmissions, money, meds, mobility, home support — the non-medical determinants that drive readmission."},
 ref:"Case management · high-risk discharge"},

{id:"MOC-029", t:"single", cn:"MOC", sys:"PSYCH", topic:"Conflict resolution / staff", d:2, b:0.3, cj:"act", tags:["conflict","leadership","communication"],
 stem:"Two staff nurses disagree loudly about a holiday schedule at the nurses' station in front of clients. What is the charge nurse's first action?",
 opts:["Move the discussion to a private area and facilitate a fair resolution",
  "Reassign one nurse to another unit for the shift",
  "Tell both nurses to behave professionally or go home",
  "Post the final schedule and void further discussion"],
 ans:0,
 rat:{c:"Professional conflict is handled privately and collaboratively — move it away from clients, hear both sides, and guide a fair resolution. Public reprimands, reassignment, and ultimatums escalate and humiliate.",
  o:["Correct — privacy first, then facilitated problem-solving.",
     "Reassignment punishes without resolving and strains staffing.",
     "Threats shut down communication and do not solve the conflict.",
     "Imposing a decision without input breeds the next conflict."],
  s:"Conflict rule: take it private, hear both sides, fix the process — never discipline an audience."},
 ref:"Leadership · conflict management"},

{id:"MOC-030", t:"single", cn:"MOC", sys:"GI", topic:"Language access / interpreters", d:1, b:-0.2, cj:"act", tags:["interpreters","equity","communication"],
 stem:"A client who speaks limited English needs discharge teaching about a new anticoagulant. Which approach is best?",
 opts:["Use a qualified medical interpreter and teach-back to confirm understanding",
  "Ask the client's bilingual teenage child to translate the instructions",
  "Provide written translated material and skip the discussion",
  "Speak slowly and use gestures for the key points"],
 ans:0,
 rat:{c:"Qualified medical interpreters are the standard of care for consent-level teaching, paired with teach-back. Family members (especially minors) are not appropriate for clinical translation; paper alone and slow speech with gestures leave too much room for error.",
  o:["Correct — qualified interpreter + teach-back is the evidence-based pairing.",
     "Minor family members may censor, misstate, or carry emotional burden — not appropriate.",
     "Written translation supports but never replaces interactive teaching.",
     "Loud/slow/gesture communication is not language access."],
  s:"Clinical conversations need qualified interpreters — never family, never gestures — then confirm with teach-back."},
 ref:"Language access · interpreter standards"},

{id:"MOC-031", t:"drag", cn:"MOC", sys:"CV", topic:"Handoff / SBAR", d:1, b:-0.1, cj:"generate", tags:["communication","sbar","handoff"],
 stem:"During shift handoff, order each statement into its correct SBAR component. Assign one statement per component in order.",
 drag:{ targets:["S — Situation","B — Background","A — Assessment","R — Recommendation"],
   opts:[
     "Mr. Ofori in 214, day 2 after a femoral stent placement",
     "His blood pressure has drifted down and his heart rate has risen over 4 hours",
     "I think he may be bleeding into the thigh or retroperitoneum",
     "I'd like a hemoglobin and a provider at the bedside within 30 minutes"],
   ans:[0,1,2,3]},
 rat:{c:"SBAR: Situation names the client and current concern; Background gives relevant history; Assessment is the nurse's read of the data; Recommendation states the requested action.",
  o:["Correct — identifying the client and setting is the Situation line.",
     "Correct — trend data is Background context.",
     "Correct — the nurse's interpretation is the Assessment.",
     "Correct — a concrete ask is the Recommendation."],
  s:"SBAR is a sentence pattern: who and why now → what came before → what I think → what I want."},
 ref:"Handoff communication · SBAR structure"},

{id:"MOC-032", t:"single", cn:"MOC", sys:"MSK", topic:"Mandatory reporting", d:2, b:0.35, cj:"act", tags:["legal","abuse","mandatory-reporting"],
 stem:"A home health nurse notes multiple bruises in various stages of healing on an older adult client, who becomes quiet when the adult child in the room answers questions for them. What is the nurse's priority action?",
 opts:["Report the suspected abuse to the state adult protective services line",
  "Confront the adult child about the injuries immediately",
  "Document the findings and revisit the concern next visit",
  "Ask the client to call if anything happens after the visit"],
 ans:0,
 rat:{c:"Suspicion of abuse in a vulnerable adult is mandatory-report territory: the nurse reports directly to adult protective services — no diagnosis of abuse is required first, and delay leaves the client at risk.",
  o:["Correct — nurses report suspicion; investigators confirm.",
     "Confronting a possible abuser escalates danger for the client.",
     "Waiting leaves the client unprotected between visits.",
     "Handing responsibility to a possibly controlled client is unsafe."],
  s:"You don't need proof to report — suspicion triggers the report, injuries in stages plus a controlling companion are enough."},
 ref:"Mandatory reporting · vulnerable adults"},

{id:"MOC-033", t:"single", cn:"MOC", sys:"RESP", topic:"Advance directives", d:2, b:0.4, cj:"act", tags:["ethics","advance-directives","end-of-life"],
 stem:"A client with a signed DNR order in the chart develops severe respiratory distress. The family at the bedside begs the nurse to “do something.” What is the nurse's best action?",
 opts:["Provide comfort-focused care and explain the DNR to the family",
  "Call a code and begin resuscitation since the family is requesting it",
  "Ask the provider to rescind the DNR while the family decides",
  "Leave the room so the family can grieve privately"],
 ans:0,
 rat:{c:"A valid DNR directs care regardless of family wishes in the moment; the nurse's duty is comfort, presence, and clear explanation. The provider may revisit goals WITH the client if the client retains capacity — but the document stands.",
  o:["Correct — honor the directive, treat the distress (positioning, oxygen for comfort, medication per orders), support the family.",
     "Family requests do not override the client's own documented decision.",
     "A DNR is the client's, not the family's or provider's alone to rescind.",
     "Withdrawing presence abandons both client and family."],
  s:"The chart speaks for the client who cannot: follow the directive, treat the suffering, translate for the family."},
 ref:"Advance directives · DNR conflicts"},

{id:"MOC-034", t:"single", cn:"MOC", sys:"NEURO", topic:"Shift prioritization", d:2, b:0.5, cj:"prioritize", tags:["prioritization","assessment"],
 stem:"The day shift RN receives handoff on four clients. Which client does the RN assess first?",
 opts:["A client 6 hours post-carotid endarterectomy with new-onset hoarseness",
  "A client 2 days post-laminectomy requesting a pain refill",
  "A client with pneumonia whose IV antibiotic is due now",
  "A client with a leg cast reporting mild itching inside the cast"],
 ans:0,
 rat:{c:"Hoarseness (or any airway/neck change) after carotid surgery can herald hematoma compromising the airway — a surgical emergency. Pain refill, a due antibiotic, and cast itching are routine sequencing.",
  o:["Correct — new airway-adjacent sign post-carotid = assess first, call now.",
     "Chronic post-op pain management follows.",
     "Important but time-windowed in minutes-to-hours, not airway.",
     "Itching is common; check neurovascular status on rounds."],
  s:"Post-op neck + voice change = airway risk until cleared; ABC outranks schedule and comfort."},
 ref:"Prioritization · postoperative airway risk"},

{id:"MOC-035", t:"single", cn:"MOC", sys:"INF", topic:"Incident reporting", d:1, b:-0.15, cj:"act", tags:["safety","documentation","incident-report"],
 stem:"After a client falls, the nurse completes an incident report. Which entry belongs in the client's medical record?",
 opts:["Objective assessment findings and care provided after the fall",
  "A reference to the completed incident report",
  "A statement that the fall was caused by short staffing",
  "The names of the staff who completed the report"],
 ans:0,
 rat:{c:"The medical record carries clinical facts: findings and interventions. The incident report is a separate internal quality document and should never be referenced or filed in the chart; blame language belongs in neither.",
  o:["Correct — document what you found and what you did, clinically.",
     "Referencing the incident report in the chart is prohibited and discoverable.",
     "Causative blame is an opinion — excluded from both documents.",
     "Staff names belong on the report, not the clinical chart."],
  s:"Chart the care; report the event; never mix the two or editorialize blame."},
 ref:"Incident reporting · documentation rules"},

/* ── Safety & Infection Prevention ─────────────────────────────── */
{id:"SIC-017", t:"single", cn:"SIC", sys:"RESP", topic:"Fire safety / oxygen", d:1, b:-0.25, cj:"act", tags:["fire-safety","oxygen"],
 stem:"A trash can ignites in the room of a client receiving oxygen via nasal cannula. After pulling the fire alarm, what is the nurse's next action?",
 opts:["Move the client away from the fire and close the door",
  "Attempt to extinguish the fire with water from the sink",
  "Turn off the client's oxygen and wait for the fire team",
  "Open windows to vent the smoke from the room"],
 ans:0,
 rat:{c:"RACE: Rescue first — move the client (and anyone else) to safety behind a closing door, then contain. Water near an oxygen-fed electrical fire risks injury; waiting and window-opening waste rescue time.",
  o:["Correct — rescue people, confine the fire with a closed door.",
     "Water is wrong for electrical/oxygen-involved fires (Class C risk).",
     "Rescue comes before equipment management in RACE.",
     "Ventilation does not rescue or contain — and delays both."],
  s:"RACE order is a ladder: Rescue → Alarm → Contain → Extinguish. People before flames before property."},
 ref:"Fire safety · RACE protocol"},

{id:"SIC-018", t:"single", cn:"SIC", sys:"INF", topic:"Needlestick exposure", d:2, b:0.25, cj:"act", tags:["exposure-control","bloodborne"],
 stem:"A nurse sustains a needlestick from a device used on a client with hepatitis B. Which action sequence is correct?",
 opts:["Wash the site, report immediately, and begin post-exposure prophylaxis per protocol",
  "Squeeze the wound to express blood, then apply antiseptic",
  "Test the source client again after consent and wait for results before reporting",
  "Irrigate the site and return to care; report only if symptoms develop"],
 ans:0,
 rat:{c:"Post-exposure response: wash (no squeezing), report at once, and start prophylaxis in the recommended window — HBV prophylaxis works best within 24 hours. Waiting for serology or symptoms forfeits the prevention window.",
  o:["Correct — wash, report, prophylax inside the window.",
     "Squeezing/milking drives fluid deeper — contraindicated.",
     "Source testing follows protocol; reporting and PEP are not gated on it.",
     "Symptom-based reporting misses the entire prophylaxis window."],
  s:"Exposure clock: wash → report → prophylaxis. The window is hours, not days — and never milk the wound."},
 ref:"Bloodborne exposure · post-exposure prophylaxis"},

{id:"SIC-019", t:"single", cn:"SIC", sys:"NEURO", topic:"Fall prevention", d:1, b:-0.2, cj:"analyze", tags:["falls","safety","risk"], variantGroup:"falls-risk",
 stem:"Which client on a medical unit is at the HIGHEST risk for falls?",
 opts:["An 82-year-old with dementia who has urgency-related frequent toileting and takes a nighttime sedative",
  "A 60-year-old post-op knee replacement using a walker with steady gait",
  "A 45-year-old on continuous cardiac monitoring for palpitations",
  "A 30-year-old with a fractured wrist in a sling, ambulatory"],
 ans:0,
 rat:{c:"Fall risk compounds: age + cognitive impairment + urinary urgency + sedating medication is the classic high-risk stack — urgency pulls the client up unsupervised and the sedative blunts them.",
  o:["Correct — the accumulation of risks, not any single factor, drives the score.",
     "Mobility aid plus steady gait is managed risk.",
     "Monitoring implies a stable, attended client.",
     "Young, ambulatory, and unimpaired is low risk."],
  s:"Count the stack: confusion + urgency + sedatives + age. The more factors, the faster they fall."},
 ref:"Fall prevention · risk factors"},

{id:"SIC-020", t:"single", cn:"SIC", sys:"GI", topic:"MDRO / C. difficile", d:1, b:-0.15, cj:"act", tags:["isolation","mdro","infection-control"],
 stem:"A client with C. difficile diarrhea is on contact precautions. Which practice is essential for this client specifically?",
 opts:["Hand hygiene with soap and water, not alcohol rub, after care",
  "Placing the client in a negative-airflow room",
  "Wearing an N95 respirator for all room entries",
  "Dedicated stethoscope sterilized with alcohol after each use"],
 ans:0,
 rat:{c:"C. difficile spores survive alcohol-based rub — soap-and-water mechanical removal is required. It spreads by contact (no airborne room or N95), and alcohol cannot reliably kill spores on equipment either.",
  o:["Correct — spores need soap, water, and friction.",
     "Negative airflow is for airborne diseases, not C. diff.",
     "N95 addresses airborne spread; C. diff is contact-borne.",
     "Alcohol is inadequate against spores — equipment needs sporicidal cleaning."],
  s:"C. diff rule: CONTACT precautions + SOAP and water. Alcohol rub and airborne measures miss the spore."},
 ref:"Contact precautions · C. difficile specifics"},

{id:"SIC-021", t:"single", cn:"SIC", sys:"INF", topic:"Client identification", d:0, b:-0.4, cj:"act", tags:["safety","identification"],
 stem:"Before administering an oral medication, which is the safest client identification practice?",
 opts:["Compare the medication record with the client's wristband and a second identifier stated by the client",
  "Ask the client to state their room number and confirm the name on the door",
  "Verify the wristband and proceed — the client is sleeping",
  "Use the most recent photo on the chart for visual confirmation"],
 ans:0,
 rat:{c:"Two identifiers — the wristband plus something the client states (name, birth date) — checked against the record is the standard. Room numbers are location data, not identity; sleeping clients still get woken for safe verification; photos are adjuncts at most.",
  o:["Correct — wristband + client-stated second identifier vs. the record.",
     "Room and door labels relocate easily; they are not identifiers.",
     "Skipping client participation drops one identifier entirely.",
     "Photos substitute for neither band nor stated identifier."],
  s:"Two identifiers, at least one from the client's own mouth, matched to the record — every time, even for a sleeping client."},
 ref:"Client safety · two-identifier rule"},

{id:"SIC-022", t:"single", cn:"SIC", sys:"PSYCH", topic:"Workplace violence", d:2, b:0.3, cj:"act", tags:["workplace-violence","safety","de-escalation"],
 stem:"A visibly intoxicated visitor blocks the medication room door and raises their voice at the charge nurse. What is the nurse's priority action?",
 opts:["Signal a colleague to call security while speaking calmly and keeping an exit route open",
  "Physically guide the visitor away from the door",
  "State firmly that police will be called unless they leave now",
  "Ignore the visitor and continue preparing medications"],
 ans:0,
 rat:{c:"Priority is summoning help while staying calm, keeping distance, and keeping an escape path — never physical contact, ultimatums, or turning away. De-escalation works best before, not after, threats.",
  o:["Correct — parallel actions: get help coming and keep yourself safe.",
     "Physical contact escalates violence and creates liability.",
     "Ultimatums back a cornered person into escalation.",
     "Turning away abandons situational awareness at the worst moment."],
  s:"Violence basics: call for help early, keep talking calmly, keep your exit — never touch, never threaten, never ignore."},
 ref:"Workplace violence · response priorities"},

/* ── Pharmacological Therapies ─────────────────────────────────── */
{id:"PHA-037", t:"single", cn:"PHA", sys:"HEME", topic:"Anticoagulation", d:2, b:0.3, cj:"evaluate", tags:["heparin","monitoring"],
 stem:"A client on a continuous heparin infusion has an aPTT of 95 seconds (control 35) with no visible bleeding. What does the nurse anticipate?",
 opts:["The infusion will be held or reduced per protocol, with a repeat aPTT in 6 hours",
  "The infusion continues unchanged since no bleeding is present",
  "Protamine sulfate will be given IV push immediately",
  "The heparin will be switched to oral warfarin tonight"],
 ans:0,
 rat:{c:"An aPTT roughly 2.7× control is supratherapeutic (target ~1.5–2.5×): standard practice is holding or reducing per the institution's nomogram and rechecking. Protamine reversal is reserved for significant bleeding.",
  o:["Correct — nomogram-based hold/reduce plus recheck is the routine response.",
     "No-bleeding does not justify continuing an excessive anticoagulant effect.",
     "Protamine is for major bleeding, not asymptomatic over-anticoagulation.",
     "Crossing to warfarin is a treatment-plan decision, not an aPTT response."],
  s:"Know your therapeutic band: aPTT 1.5–2.5× control. Above it → hold/reduce per nomogram; reversal is for bleeding."},
 ref:"Heparin therapy · aPTT nomograms"},

{id:"PHA-038", t:"single", cn:"PHA", sys:"INF", topic:"Medication safety / allergies", d:1, b:-0.2, cj:"act", tags:["allergy","medication-safety"],
 stem:"Before giving the first dose of an IV antibiotic, the client states, “I think penicillin made my face swell once.” What is the nurse's priority action?",
 opts:["Hold the dose and clarify the reaction and order with the provider and pharmacy",
  "Give the dose slowly with the emergency cart nearby",
  "Administer a test dose and observe for 15 minutes",
  "Substitute a macrolide from the unit stock and document the change"],
 ans:0,
 rat:{c:"A reported angioedema-type history is a potential anaphylaxis warning — hold, verify with the client and provider/pharmacy, and let the prescriber choose an alternative. Nurses never substitute medications independently, and there is no 'test dose' practice for this.",
  o:["Correct — hold and verify; the prescriber adjusts the order.",
     "Slow administration does not make an anaphylactic allergen safe.",
     "Elective 'test dosing' outside desensitization protocols is not a nursing action.",
     "Independent substitution is outside nursing authority."],
  s:"Swelling history = airway-risk allergy until cleared: hold, verify, let the prescriber re-route. Never 'try it and see.'"},
 ref:"Medication safety · allergy verification"},

{id:"PHA-039", t:"single", cn:"PHA", sys:"CV", topic:"Digoxin toxicity", d:2, b:0.4, cj:"evaluate", tags:["digoxin","toxicity"], variantGroup:"digoxin-toxicity",
 stem:"A home health client taking digoxin and furosemide reports nausea, poor appetite, and seeing yellow halos around lights for 2 days. What is the nurse's priority action?",
 opts:["Obtain a stat digoxin level and potassium, and hold the morning dose pending results",
  "Reassure the client that halos are a normal digoxin effect",
  "Schedule a routine provider visit for next week",
  "Advise taking digoxin with food to reduce the nausea"],
 ans:0,
 rat:{c:"GI symptoms + visual halos in a client on digoxin WITH a potassium-wasting diuretic is the classic toxicity picture (hypokalemia potentiates digoxin). Hold the dose and get stat levels and electrolytes.",
  o:["Correct — suspect, hold, level, potassium. Loop diuretics lower K⁺ and raise risk.",
     "Halos are toxicity signs, never normal.",
     "A week's delay risks dysrhythmias.",
     "Food timing treats nausea, not the toxicity driving it."],
  s:"Digoxin + loop diuretic + GI/visual complaints = toxicity until the level says otherwise (variant presentation)."},
 ref:"Digoxin toxicity · hypokalemia potentiation (variant)"},

{id:"PHA-040", t:"single", cn:"PHA", sys:"NEURO", topic:"Anticonvulsants", d:2, b:0.45, cj:"act", tags:["phenytoin","administration"],
 stem:"Phenytoin is prescribed IV for a client with ongoing seizures. Which administration practice is correct?",
 opts:["Give it diluted in normal saline with cardiac monitoring",
  "Give it rapidly undiluted to stop seizures sooner",
  "Mix it in dextrose 5% water to reduce vein irritation",
  "Give it IM to avoid dysrhythmia risk"],
 ans:0,
 rat:{c:"IV phenytoin precipitates in dextrose solutions, must be diluted in saline, given no faster than 50 mg/min with cardiac monitoring. IM administration is erratic and harms tissue.",
  o:["Correct — saline only, rate-limited, on a monitor.",
     "Rapid IV push risks hypotension and dysrhythmias.",
     "D5W causes precipitation — never used.",
     "IM phenytoin is irritating and unreliable — not for active seizures."],
  s:"Phenytoin rules: SALINE, SLOW (≤50 mg/min), MONITOR — and never dextrose, never IM."},
 ref:"Phenytoin IV · safe administration"},

/* ── Reduction of Risk Potential ───────────────────────────────── */
{id:"RRP-026", t:"single", cn:"RRP", sys:"GI", topic:"Wound complications", d:2, b:0.35, cj:"act", tags:["postoperative","dehiscence"],
 stem:"On day 5 after abdominal surgery, a client's cough splits the incision and a loop of bowel is visible. Which action sequence is correct?",
 opts:["Cover the wound with a sterile saline-moistened dressing, keep the client NPO and supine, and notify the provider immediately",
  "Gently replace the bowel and secure the wound with sterile strips",
  "Irrigate the exposed bowel with antiseptic and apply a dry dressing",
  "Apply an abdominal binder tightly and monitor for shock"],
 ans:0,
 rat:{c:"Evisceration is a surgical emergency: stay calm, position supine with knees bent, cover viscera with sterile saline-moistened dressing, NPO, and prepare for surgery. Nothing goes back in by hand; antiseptics and pressure harm exposed bowel.",
  o:["Correct — moist sterile cover, NPO, notify, to the OR.",
     "Manual replacement is a surgical act — never nursing practice.",
     "Antiseptics are cytotoxic to exposed tissue.",
     "A tight binder crushes the viscera — contraindicated."],
  s:"Evisceration = cover moist, bend knees, NPO, call. The bowel stays outside until the OR."},
 ref:"Postoperative complications · evisceration"},

{id:"RRP-027", t:"single", cn:"RRP", sys:"NEURO", topic:"Increased ICP", d:2, b:0.4, cj:"evaluate", tags:["icp","neuro","monitoring"],
 stem:"Which finding is the EARLIEST indicator of rising intracranial pressure in a client with a head injury?",
 opts:["A change in the level of consciousness or restlessness",
  "Widened pulse pressure with bradycardia",
  "Fixed and dilated pupils",
  "Decerebrate posturing to stimulus"],
 ans:0,
 rat:{c:"Mental-status change is the earliest and most sensitive sign — the brain complains behaviorally before hemodynamics shift. Cushing's triad, fixed pupils, and posturing are LATE findings.",
  o:["Correct — level of consciousness declines before numbers move.",
     "Widened pulse pressure + bradycardia (Cushing's) appears late.",
     "Fixed dilated pupils signal herniation-level pressure.",
     "Posturing reflects brainstem compromise — late."],
  s:"ICP escalation order: think first (confusion, restlessness), then vital signs, then pupils, then posture. Earliest = how they think."},
 ref:"Increased ICP · early versus late signs"},

{id:"RRP-028", t:"single", cn:"RRP", sys:"REN", topic:"Vascular access / dialysis", d:2, b:0.25, cj:"evaluate", tags:["dialysis","av-fistula","assessment"],
 stem:"A client on hemodialysis has an arteriovenous fistula in the left arm. Which finding warrants contacting the dialysis center immediately?",
 opts:["Absence of a bruit and thrill over the fistula",
  "A continuous machinery-like bruit audible over the fistula",
  "Mild bruising at the needle sites after yesterday's treatment",
  "The client preferring to sleep on the right side"],
 ans:0,
 rat:{c:"The bruit and thrill ARE the fistula's life signs — losing them means clotting/thrombosis and access loss risk; same-day intervention can save the access. Machinery bruit is normal; needle-site bruising is routine.",
  o:["Correct — no bruit, no thrill = clotted access = call now.",
     "A continuous bruit is exactly what a working fistula sounds like.",
     "Post-treatment needle bruising is expected.",
     "Positioning preference is irrelevant unless it pressures the arm."],
  s:"Fistula check every shift: LOOK (pulse), LISTEN (bruit), FEEL (thrill) — absent signs mean the clock is running."},
 ref:"Hemodialysis access · AV fistula surveillance"},

/* ── Basic Care & Comfort ──────────────────────────────────────── */
{id:"BCC-017", t:"single", cn:"BCC", sys:"NEURO", topic:"Pain assessment", d:1, b:-0.2, cj:"recognize", tags:["pain","assessment"],
 stem:"A client with advanced dementia grimaces, guards their shoulder, and resists movement during bathing, but cannot complete a numeric pain scale. What is the nurse's best action?",
 opts:["Use a behavioral observational pain tool such as PAINAD and treat per findings",
  "Document “unable to assess pain” and recheck next shift",
  "Withhold analgesia until the client can report a score",
  "Use the client's blood pressure and heart rate as the pain measure"],
 ans:0,
 rat:{c:"When self-report is impossible, validated observational tools (PAINAD and similar) guide assessment and treatment. Vital signs are neither sensitive nor specific for pain; withholding analgesia for a missing number is harmful.",
  o:["Correct — observe behaviors, score them, treat what you see.",
     "“Unable to assess” abandons the obligation to assess differently.",
     "Pain treatment never waits for a number the client cannot give.",
     "Vitals respond to many stressors — they do not measure pain."],
  s:"Self-report is gold — when it's gone, behavior is the data: grimace, guard, resist. Score it, treat it."},
 ref:"Pain assessment · nonverbal clients"},

{id:"BCC-018", t:"single", cn:"BCC", sys:"MSK", topic:"Heat / cold therapy", d:1, b:-0.1, cj:"act", tags:["comfort","heat-cold","safety"],
 stem:"Which client situation is a contraindication to applying a heating pad to the lower back?",
 opts:["A client with diabetic neuropathy reporting chronic back stiffness",
  "A client with menstrual cramps and intact sensation",
  "A client with a pulled muscle who can feel the heat clearly",
  "A client with back soreness after physical therapy"],
 ans:0,
 rat:{c:"Diminished sensation (diabetic neuropathy) removes the protective response to heat — burns occur without warning. Intact sensation makes the other scenarios routine applications with standard precautions.",
  o:["Correct — no sensation means no protective withdrawal: burn risk.",
     "Intact sensation and cramps are classic appropriate use.",
     "Able to feel heat = can self-protect.",
     "Post-exercise soreness is routine heat territory."],
  s:"Heat safety = sensation. If they can't feel it, they can't protect themselves from it."},
 ref:"Therapeutic heat · contraindications"},

/* ── Psychosocial Integrity ────────────────────────────────────── */
{id:"PSY-016", t:"single", cn:"PSY", sys:"PSYCH", topic:"Substance withdrawal", d:2, b:0.45, cj:"evaluate", tags:["withdrawal","alcohol","monitoring"],
 stem:"A client hospitalized after surgery has a history of heavy daily alcohol use and begins showing tremors, sweating, and agitation 24 hours after admission. What is the nurse's priority?",
 opts:["Initiate withdrawal monitoring (e.g., CIWA-Ar) and treat per protocol before symptoms escalate",
  "Provide a quiet dark room and reassess in 4 hours",
  "Request a psychiatric consultation for withdrawal management",
  "Administer a PRN benzodiazepine only if seizures occur"],
 ans:0,
 rat:{c:"Untreated alcohol withdrawal escalates to seizures and delirium tremens; symptom-triggered protocols (CIWA-Ar-guided benzodiazepines) started EARLY prevent deterioration. Waiting for seizures is late by definition.",
  o:["Correct — score early, treat by protocol, prevent progression.",
     "Unmonitored observation lets withdrawal escalate.",
     "Psychiatry may advise, but withdrawal protocols are nursing-initiated and urgent.",
     "Treating only after seizures concedes the preventable complication."],
  s:"Alcohol withdrawal is a race: tremors at 24 h → seizures by 48 h → DTs at 72 h. Score (CIWA) and treat before the ladder climbs."},
 ref:"Alcohol withdrawal · symptom-triggered management"},

{id:"PSY-017", t:"single", cn:"PSY", sys:"PSYCH", topic:"Grief", d:1, b:-0.2, cj:"act", tags:["grief","therapeutic-communication"],
 stem:"A client whose spouse died 3 weeks ago says, “Some mornings I forget they're gone and set two coffee cups.” Which response is most therapeutic?",
 opts:["“Setting two cups shows how woven into your days they were. Would you like to talk about them?”",
  "“It's time to focus on the future — have you considered a bereavement group?”",
  "“Everyone grieves differently; give it a few more weeks.”",
  "“Try keeping one cup out of sight to avoid the reminder.”"],
 ans:0,
 rat:{c:"Normal grief expression deserves reflection and an open invitation to share — presence over solutions. Redirecting to the future, normalizing with timelines, and removing reminders dismiss the loss.",
  o:["Correct — reflects meaning and opens the door to talk.",
     "Pushing 'the future' minimizes present grief.",
     "Timelines and comparisons offer no therapeutic presence.",
     "Avoiding reminders suppresses rather than supports grieving."],
  s:"Grief responses: reflect, honor, invite. Never rush, never compare, never hide the reminders."},
 ref:"Grief and loss · therapeutic communication"},

/* ── Health Promotion & Maintenance ────────────────────────────── */
{id:"HPM-015", t:"single", cn:"HPM", sys:"INF", topic:"Immunizations", d:1, b:-0.15, cj:"act", tags:["immunization","prevention"],
 stem:"A client receiving chemotherapy asks which vaccines are appropriate during treatment. What is the nurse's best guidance?",
 opts:["Inactivated vaccines may be given per schedule; live vaccines are deferred until immunocompromise resolves",
  "All vaccines should be paused until chemotherapy ends",
  "Live attenuated vaccines are preferred for a quicker response",
  "Only the annual inactivated influenza vaccine is permitted during treatment"],
 ans:0,
 rat:{c:"Inactivated vaccines remain safe (though response may be blunted) while live attenuated vaccines (MMR, varicella, LAIV) risk uncontrolled infection in the immunocompromised. More than influenza alone is permitted.",
  o:["Correct — inactivated yes, live deferred.",
     "Pausing everything abandons protection that is still safe and useful.",
     "Live vaccines are precisely the ones to avoid during chemo.",
     "Other inactivated vaccines (e.g., pneumococcal, Tdap per guidance) are also appropriate."],
  s:"Chemotherapy vaccine rule: killed is safe, live is deferred. Explain the difference, not a blanket pause."},
 ref:"Immunization · immunocompromised clients"}
);
