"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 43) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 42: SIC (12.8% vs 13),
 * PSY (8.9% vs 9), BCC (8.9% vs 9) and PHA (15.8% vs 16). Every
 * item is difficulty 2 or 3, and the clinical detail is written
 * to be defensible.
 *
 * SIC 6: spinal precautions, log roll technique, the Cushing
 * reflex, pupil assessment, the Glasgow Coma Scale, and delirium
 * screening with the CAM-ICU.
 * PSY 5: family presence during resuscitation, family centred
 * care, therapeutic play, atraumatic care, and family anxiety.
 * BCC 5: spontaneous breathing trial, speaking valve, closed
 * suction, micro-aspiration, and stress ulcer prophylaxis.
 * PHA 4: ciclosporin, mycophenolate, everolimus, and
 * methylprednisolone.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- SIC 6 */
{id:"SIC-156", t:"single", cn:"SIC", sys:"NEURO", topic:"Spinal precautions", d:3, b:0.55, cj:"act", tags:["safety","spinal precautions","trauma","immobilisation","neurological"],
 stem:"A client is brought to the emergency department after a fall from height. The client reports neck pain and has midline cervical tenderness. Which action by the nurse is the priority?",
 opts:["Maintain spinal precautions with manual inline stabilisation until the spine is cleared","Sit the client up to assess airway and breathing, since this takes priority","Remove the cervical collar to assess the neck, since tenderness must be evaluated","Allow the client to move freely, since this identifies any neurological deficit"],
 ans:0, rat:{c:"Midline cervical tenderness after a fall from height requires spinal precautions with manual inline stabilisation until the spine is formally cleared. Sitting the client up, removing the collar, or allowing free movement all risk secondary spinal cord injury.", s:"Spinal precautions are maintained until formal clearance; the nurse must not interrupt immobilisation without authorisation."}},
{id:"SIC-157", t:"single", cn:"SIC", sys:"MSK", topic:"Log roll technique", d:3, b:0.55, cj:"act", tags:["safety","log roll","spinal","immobilisation","teamwork"],
 stem:"A client with a suspected spinal injury requires turning for skin assessment. Which action by the nurse is most appropriate?",
 opts:["Perform a coordinated log roll with sufficient staff to maintain spinal alignment throughout the turn","Turn the client onto their side by rolling the shoulders first, since spinal alignment is maintained by the collar","Ask the client to turn themselves, since self-movement is safer","Use a turning frame only, since manual turning is unsafe"],
 ans:0, rat:{c:"A log roll requires coordinated team movement with sufficient staff to maintain spinal alignment throughout the turn. Rolling the shoulders first, asking the client to self-turn, or relying only on a frame all risk spinal movement and secondary injury.", s:"Log roll technique requires team coordination; the nurse must ensure adequate staffing and spinal alignment."}},
{id:"SIC-158", t:"single", cn:"SIC", sys:"NEURO", topic:"Cushing reflex", d:3, b:0.55, cj:"recognize", tags:["safety","Cushing reflex","intracranial pressure","herniation","emergency"],
 stem:"A client with a head injury develops a rising blood pressure with widening pulse pressure, a falling heart rate, and an irregular respiratory pattern. Which interpretation by the nurse is most accurate?",
 opts:["These findings are consistent with the Cushing reflex and suggest rising intracranial pressure requiring urgent intervention","These findings are consistent with improving neurological status and require no action","These findings are consistent with hypovolaemic shock, where rising heart rate and falling pressure are expected","These findings are consistent with sepsis and require antibiotic therapy"],
 ans:0, rat:{c:"The Cushing reflex comprises hypertension with widening pulse pressure, bradycardia, and irregular respiration, indicating rising intracranial pressure and impending herniation. It requires urgent intervention. It does not indicate improvement, hypovolaemia, or sepsis.", s:"The Cushing reflex is a late and ominous sign of raised intracranial pressure; recognition prompts immediate escalation."}},
{id:"SIC-159", t:"single", cn:"SIC", sys:"NEURO", topic:"Pupil assessment", d:2, b:0.45, cj:"recognize", tags:["safety","pupil assessment","neurological","assessment","deterioration"],
 stem:"A client with a head injury develops a fixed and dilated left pupil that was previously reactive. Which action by the nurse is the priority?",
 opts:["Escalate immediately, since a newly fixed and dilated pupil suggests uncal herniation","Document the finding and reassess in one hour, since a fixed and dilated pupil may be temporary","Reassess with a brighter light, since the pupil may respond","Administer mannitol immediately, since this is standard treatment"],
 ans:0, rat:{c:"A newly fixed and dilated pupil suggests uncal herniation from raised intracranial pressure and requires immediate escalation. Documenting and waiting, re-checking the light, or administering mannitol without medical direction all delay critical intervention.", s:"Pupil changes are a key indicator of neurological deterioration; a newly fixed and dilated pupil is an emergency."}},
{id:"SIC-160", t:"single", cn:"SIC", sys:"NEURO", topic:"Glasgow Coma Scale", d:2, b:0.45, cj:"analyze", tags:["safety","Glasgow coma scale","neurological","assessment","monitoring"],
 stem:"A client opens their eyes to speech, is confused in conversation, and localises to pain. Which interpretation by the nurse is most accurate?",
 opts:["The Glasgow Coma Scale score is 12, calculated as eyes 3, verbal 4, and motor 5","The Glasgow Coma Scale score is 9, calculated as eyes 2, verbal 3, and motor 4","The Glasgow Coma Scale score is 15, indicating normal consciousness","The Glasgow Coma Scale cannot be calculated without a full neurological examination"],
 ans:0, rat:{c:"The Glasgow Coma Scale score is calculated as eyes opening to speech (3), confused conversation (4), and localising to pain (5), totalling 12. A score of 9 would indicate more severe impairment, and 15 would indicate normal consciousness.", s:"Accurate Glasgow Coma Scale scoring requires understanding each component; the nurse must document the individual scores as well as the total."}},
{id:"SIC-161", t:"single", cn:"SIC", sys:"NEURO", topic:"Delirium screening with the CAM-ICU", d:3, b:0.55, cj:"act", tags:["safety","delirium","CAM-ICU","screening","ICU"],
 stem:"A client in the intensive care unit is noted to be intermittently agitated and inattentive. The client's behaviour fluctuates between shifts. Which action by the nurse is most appropriate?",
 opts:["Perform a validated delirium screen such as the CAM-ICU, since delirium is common and often missed","Assume the client is sedated and reduce the sedation infusion","Administer an antipsychotic, since agitation requires treatment","Reassure the family, since confusion is expected in the intensive care unit"],
 ans:0, rat:{c:"Fluctuating agitation and inattention in an intensive care client warrant a validated delirium screen such as the CAM-ICU, since delirium is common and frequently missed. Assuming sedation, administering antipsychotics, or dismissing confusion all fail to identify and address delirium.", s:"Delirium screening with a validated tool is a standard of critical care; the nurse must screen rather than assume."}},

/* ---------------------------------------------------------- PSY 5 */
{id:"PSY-102", t:"single", cn:"PSY", sys:"PSYCH", topic:"Family presence during resuscitation", d:3, b:0.55, cj:"act", tags:["psych","family presence","resuscitation","support","communication"],
 stem:"A client suffers a cardiac arrest in the emergency department. The client's spouse is present and asks to remain during the resuscitation attempt. Which action by the nurse is most appropriate?",
 opts:["Offer the spouse the choice to remain with a staff member present to support and explain, in line with policy","Ask the spouse to leave, since having family present interferes with resuscitation","Allow the spouse to remain but ask them not to speak, since this distracts the team","Make the decision for the spouse, since they are too distressed to decide"],
 ans:0, rat:{c:"Evidence supports offering families the choice of presence during resuscitation, with a dedicated staff member to support and explain. Excluding the spouse, imposing silence, or deciding for them all fail to respect the family's autonomy and the evidence base.", s:"Family presence during resuscitation is supported by evidence; the nurse should offer choice and provide a dedicated support person."}},
{id:"PSY-103", t:"single", cn:"PSY", sys:"PSYCH", topic:"Family centred care", d:2, b:0.45, cj:"act", tags:["psych","family centred care","partnership","communication","paediatric"],
 stem:"A nurse is caring for a hospitalised child. The parents wish to be involved in their child's daily care decisions. Which action by the nurse is most appropriate?",
 opts:["Include the parents as partners in care planning and decision-making, since this is the basis of family centred care","Explain that clinical decisions are made by the medical team and parents may observe","Involve the parents only in non-clinical aspects of care such as feeding","Ask the parents to complete a satisfaction survey instead, since this captures their views"],
 ans:0, rat:{c:"Family centred care treats the family as partners in care planning and decision-making. Limiting parents to observation or non-clinical tasks, or substituting a survey for involvement, all fail the principles of partnership.", s:"Family centred care requires genuine partnership; the nurse must actively include families in decisions about their relative's care."}},
{id:"PSY-104", t:"single", cn:"PSY", sys:"PSYCH", topic:"Therapeutic play", d:2, b:0.45, cj:"act", tags:["psych","therapeutic play","paediatric","coping","preparation"],
 stem:"A five-year-old is awaiting a painful procedure and is visibly anxious. The nurse has access to a play specialist. Which action by the nurse is most appropriate?",
 opts:["Arrange therapeutic play to help the child express feelings and prepare for the procedure","Proceed quickly with the procedure, since delay will increase anxiety","Explain the procedure in detail using clinical terms, since honesty is important","Ask the parents to hold the child firmly, since restraint reduces distress"],
 ans:0, rat:{c:"Therapeutic play helps a young child express feelings, understand what will happen, and regain a sense of control. Rushing the procedure, using clinical terminology, or restraining the child all increase trauma and fail the child's emotional needs.", s:"Therapeutic play is an evidence-based intervention to reduce procedural anxiety in children."}},
{id:"PSY-105", t:"single", cn:"PSY", sys:"PSYCH", topic:"Atraumatic care", d:3, b:0.55, cj:"act", tags:["psych","atraumatic care","paediatric","psychological harm","intervention"],
 stem:"A nurse is planning care for a child requiring repeated painful procedures over a prolonged admission. Which action by the nurse is most appropriate?",
 opts:["Apply atraumatic care principles to minimise physical and psychological distress across all procedures","Focus on completing procedures efficiently, since this reduces overall exposure","Use distraction only, since this is the least resource-intensive approach","Rotate staff for each procedure, since the child will not associate any one nurse with pain"],
 ans:0, rat:{c:"Atraumatic care minimises physical and psychological distress through preparation, distraction, topical anaesthesia, and clustering procedures. Prioritising efficiency, using distraction alone, or rotating staff all fail to provide comprehensive atraumatic care.", s:"Atraumatic care is a framework rather than a single technique; the nurse must plan holistically across an admission."}},
{id:"PSY-106", t:"single", cn:"PSY", sys:"PSYCH", topic:"Family anxiety", d:2, b:0.45, cj:"act", tags:["psych","family anxiety","support","communication","intensive care"],
 stem:"The relatives of a critically ill client are highly anxious and repeatedly ask the same questions about the client's condition. Which action by the nurse is most appropriate?",
 opts:["Recognise the anxiety as a normal response, give consistent information, and arrange a scheduled family update","Ask the relatives to write down their questions and submit them once daily","Explain that the same questions cannot be answered repeatedly, since this wastes clinical time","Refer the relatives to the chaplain, since anxiety at this level requires spiritual support"],
 ans:0, rat:{c:"Repeated questioning from relatives reflects anxiety and impaired information processing, which is a normal response to critical illness. Consistent information and a scheduled update address the underlying need. Restricting questions, refusing to answer, or redirecting to the chaplain all fail to support the family.", s:"Family anxiety impairs information retention; the nurse should respond with consistency and structured communication."}},

/* ---------------------------------------------------------- BCC 5 */
{id:"BCC-109", t:"single", cn:"BCC", sys:"RESP", topic:"Spontaneous breathing trial", d:3, b:0.55, cj:"act", tags:["basic care","spontaneous breathing trial","weaning","ventilation","assessment"],
 stem:"A ventilated client is being considered for weaning. A spontaneous breathing trial is started, and after twenty minutes the client's respiratory rate rises to 34 and they appear distressed. Which action by the nurse is most appropriate?",
 opts:["Stop the trial and return the client to full ventilatory support, then report the findings","Continue the trial, since tolerance improves with persistence","Increase the pressure support, since this will reduce the respiratory rate","Administer sedation, since distress is causing the tachypnoea"],
 ans:0, rat:{c:"Rising respiratory rate and distress during a spontaneous breathing trial indicate failure and require the trial to be stopped, with return to full support and reporting of the findings. Continuing the trial, increasing pressure support, or sedating the client all mask failure and risk harm.", s:"Recognising spontaneous breathing trial failure is a core critical care skill; the nurse must stop the trial rather than push through."}},
{id:"BCC-110", t:"single", cn:"BCC", sys:"RESP", topic:"Speaking valve", d:2, b:0.45, cj:"act", tags:["basic care","speaking valve","tracheostomy","communication","assessment"],
 stem:"A client with a tracheostomy asks about using a speaking valve to communicate. Which action by the nurse is most appropriate?",
 opts:["Assess suitability first, ensuring the cuff is deflated and the client can exhale around the tube","Fit the speaking valve immediately, since communication is a priority","Keep the cuff inflated while the valve is in place, since this prevents aspiration","Decline the request, since speaking valves are not used in tracheostomy care"],
 ans:0, rat:{c:"A speaking valve requires assessment of suitability, cuff deflation, and confirmation that the client can exhale around the tube. Fitting it without assessment, or leaving the cuff inflated, risks airway obstruction. Speaking valves are a well-established intervention.", s:"Speaking valve use requires careful assessment; an inflated cuff with a one-way valve can cause fatal airway obstruction."}},
{id:"BCC-111", t:"single", cn:"BCC", sys:"RESP", topic:"Closed suction", d:2, b:0.45, cj:"act", tags:["basic care","closed suction","ventilation","airway","infection prevention"],
 stem:"A ventilated client with a positive end-expiratory pressure requirement of 12 cmH2O needs tracheal suctioning. Which action by the nurse is most appropriate?",
 opts:["Use a closed suction system, since this maintains positive end-expiratory pressure and reduces derecruitment","Use open suction, since this is always more effective even when positive end-expiratory pressure is high","Disconnect the ventilator briefly, since this makes suctioning easier","Withhold suctioning, since it will cause desaturation"],
 ans:0, rat:{c:"A closed suction system maintains positive end-expiratory pressure and prevents derecruitment in a client with high positive end-expiratory pressure. Open suctioning disconnects the circuit and causes derecruitment. Disconnecting the ventilator or withholding suctioning both harm the client.", s:"Closed suction preserves lung recruitment in clients with high positive end-expiratory pressure requirements."}},
{id:"BCC-112", t:"single", cn:"BCC", sys:"RESP", topic:"Micro-aspiration", d:3, b:0.55, cj:"act", tags:["basic care","micro-aspiration","ventilator-associated pneumonia","prevention","oral care"],
 stem:"A critically ill client is ventilated with a cuffed tracheal tube. The team wishes to reduce the risk of ventilator-associated pneumonia. Which action by the nurse is most appropriate?",
 opts:["Maintain cuff pressure within the recommended range and provide regular oral care, since micro-aspiration of contaminated secretions drives infection","Increase the cuff pressure above the recommended range, since this seals the airway more completely","Reduce oral care frequency, since disturbance increases secretions","Nurse the client flat, since this reduces secretion pooling"],
 ans:0, rat:{c:"Micro-aspiration of contaminated oropharyngeal secretions past the cuff is the main driver of ventilator-associated pneumonia. Correct cuff pressure and regular oral care reduce this risk. Excessive cuff pressure damages the tracheal mucosa, and lying flat increases aspiration risk.", s:"Micro-aspiration is central to ventilator-associated pneumonia; cuff pressure and oral care are the key modifiable factors."}},
{id:"BCC-113", t:"single", cn:"BCC", sys:"GI", topic:"Stress ulcer prophylaxis", d:2, b:0.45, cj:"act", tags:["basic care","stress ulcer prophylaxis","critically ill","prevention","indication"],
 stem:"A critically ill client who is mechanically ventilated is reviewed for stress ulcer prophylaxis. Which action by the nurse is most appropriate?",
 opts:["Ensure prophylaxis is given, since mechanical ventilation is an accepted indication","Withhold prophylaxis, since it is no longer recommended for any client","Give prophylaxis only if the client has a history of peptic ulcer disease","Withhold prophylaxis, since it increases the risk of bleeding"],
 ans:0, rat:{c:"Mechanical ventilation is an accepted indication for stress ulcer prophylaxis in critically ill clients. Prophylaxis is not universally withheld, is not limited to those with prior ulcer disease, and reduces rather than increases bleeding risk in indicated clients.", s:"Stress ulcer prophylaxis is indicated by specific risk factors; mechanical ventilation is one of the strongest indications."}},

/* ---------------------------------------------------------- PHA 4 */
{id:"PHA-195", t:"single", cn:"PHA", sys:"REPI", topic:"Ciclosporin", d:3, b:0.55, cj:"act", tags:["pharmacology","ciclosporin","immunosuppression","monitoring","transplant"],
 stem:"A renal transplant recipient is prescribed ciclosporin. Which action by the nurse is most appropriate?",
 opts:["Monitor trough levels, blood pressure, and renal function, since ciclosporin has a narrow therapeutic index and is nephrotoxic","Monitor blood glucose only, since ciclosporin has no renal adverse effects","Advise the client to take the dose with grapefruit juice to improve absorption","Advise the client to stop the drug if they feel well, since long-term use is unnecessary"],
 ans:0, rat:{c:"Ciclosporin has a narrow therapeutic index and is nephrotoxic, requiring monitoring of trough levels, blood pressure, and renal function. Grapefruit juice inhibits its metabolism and raises levels dangerously. It must not be stopped when the client feels well.", s:"Ciclosporin requires therapeutic drug monitoring and awareness of significant food and drug interactions."}},
{id:"PHA-196", t:"single", cn:"PHA", sys:"REPI", topic:"Mycophenolate", d:3, b:0.55, cj:"act", tags:["pharmacology","mycophenolate","immunosuppression","monitoring","transplant"],
 stem:"A transplant recipient taking mycophenolate reports new diarrhoea and the full blood count shows a falling white cell count. Which action by the nurse is most appropriate?",
 opts:["Report both findings promptly, since diarrhoea and bone marrow suppression are recognised adverse effects requiring dose review","Continue the current dose, since diarrhoea is common and self-limiting","Administer an antidiarrhoeal and repeat the blood count in one month","Advise the client to halve the dose themselves until symptoms settle"],
 ans:0, rat:{c:"Diarrhoea and bone marrow suppression are recognised mycophenolate adverse effects and both findings require prompt reporting for dose review. Continuing unchanged, treating symptomatically without review, or self-adjusting the dose all risk harm.", s:"Mycophenolate commonly causes gastrointestinal toxicity and myelosuppression; the nurse must report and monitor."}},
{id:"PHA-197", t:"single", cn:"PHA", sys:"REPI", topic:"Everolimus", d:3, b:0.55, cj:"act", tags:["pharmacology","everolimus","immunosuppression","monitoring","wound healing"],
 stem:"A transplant recipient is prescribed everolimus. Which action by the nurse is most appropriate?",
 opts:["Monitor trough levels and observe wound healing, since everolimus can impair healing and requires therapeutic drug monitoring","Monitor trough levels only, since wound healing is unaffected by this drug","Advise the client that no monitoring is required, since everolimus is well tolerated","Advise the client to take a double dose if one is missed, since levels must be maintained"],
 ans:0, rat:{c:"Everolimus requires trough level monitoring and can impair wound healing, so surgical sites need observation. It is not free of monitoring requirements, and doubling a missed dose risks toxicity.", s:"Everolimus combines therapeutic drug monitoring with specific adverse effects including impaired wound healing."}},
{id:"PHA-198", t:"single", cn:"PHA", sys:"REPI", topic:"Methylprednisolone", d:2, b:0.45, cj:"act", tags:["pharmacology","methylprednisolone","corticosteroid","rejection","monitoring"],
 stem:"A transplant recipient is prescribed high-dose intravenous methylprednisolone for suspected acute rejection. Which action by the nurse is most appropriate?",
 opts:["Monitor blood glucose, blood pressure, and for signs of infection, since high-dose corticosteroids cause hyperglycaemia, hypertension, and immunosuppression","Monitor blood glucose only, since this is the sole significant adverse effect","Advise the client to stop the drug once symptoms improve, since prolonged use is harmful","Withhold the dose, since high-dose corticosteroids are no longer used for rejection"],
 ans:0, rat:{c:"High-dose corticosteroids cause hyperglycaemia, hypertension, and immunosuppression, so all three require monitoring. Monitoring glucose alone is insufficient, abrupt cessation is harmful, and high-dose steroids remain standard rejection treatment.", s:"High-dose methylprednisolone requires broad monitoring; the nurse must anticipate metabolic and infectious complications."}}

]);
