"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 47) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 46: MOC (17.8% vs 18),
 * PHA (15.8% vs 16) and RRP (11.8% vs 12). Every item is
 * difficulty 2 or 3, and the clinical detail is written to be
 * defensible.
 *
 * MOC 7: safeguarding referral, a section 47 child protection
 * enquiry, a section 42 adult safeguarding enquiry, financial
 * abuse, coercive control, apology as not an admission of
 * liability, and human factors with the Swiss cheese model.
 * PHA 7: continuous glucose monitoring, time in range,
 * hypoglycaemia unawareness, sick day rules, lipohypertrophy,
 * insulin-to-carbohydrate ratio, and steroid-induced diabetes.
 * RRP 6: driving and hypoglycaemia, blood ketone monitoring,
 * variable rate intravenous insulin infusion, HbA1c, point of care
 * testing quality, and exercise-related insulin adjustment.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- MOC 7 */
{id:"MOC-225", t:"single", cn:"MOC", sys:"INTG", topic:"Safeguarding referral", d:3, b:0.55, cj:"act", tags:["management","safeguarding","referral","protection","accountability"],
 stem:"A nurse sustains a concern that a client's relative may be causing harm through neglect. The relative is present and becomes defensive when questioned. Which action by the nurse is most appropriate?",
 opts:["Make a safeguarding referral according to policy without confronting the relative further, and ensure the client is safe","Confront the relative directly, since this may secure an admission","Delay the referral until more evidence is gathered, since suspicion alone is insufficient","Discuss the concern with the relative's other family members, since they may intervene"],
 ans:0, rat:{c:"A safeguarding concern must be referred according to policy without delay; gathering evidence is not the nurse's role, and confrontation risks escalating danger to the client. Involving other family members breaches confidentiality and may increase risk.", s:"The nurse's duty is to refer, not to investigate; delaying or confronting both endanger the client."}},
{id:"MOC-226", t:"single", cn:"MOC", sys:"INTG", topic:"Section 47 child protection enquiry", d:3, b:0.55, cj:"analyze", tags:["management","section 47","child protection","enquiry","multi-agency"],
 stem:"A child is referred to social care with concerns of physical abuse, and a section 47 enquiry is opened. The nurse is asked to contribute. Which interpretation by the nurse is most accurate?",
 opts:["A section 47 enquiry is a multi-agency child protection investigation, and the nurse must contribute factual information as requested","A section 47 enquiry is a voluntary support service that the family may decline","A section 47 enquiry is a police investigation about the child in which health professionals have no role to contribute","A section 47 enquiry is only opened once harm has been proven"],
 ans:0, rat:{c:"A section 47 enquiry is a statutory multi-agency child protection investigation to determine whether a child is suffering or likely to suffer significant harm. It is not voluntary, health staff have a clear contribution, and it is opened on reasonable cause to suspect, not proven harm.", s:"Understanding the section 47 threshold and the nurse's contribution is essential for effective multi-agency working."}},
{id:"MOC-227", t:"single", cn:"MOC", sys:"INTG", topic:"Section 42 adult safeguarding enquiry", d:3, b:0.55, cj:"analyze", tags:["management","section 42","adult safeguarding","enquiry","capacity"],
 stem:"An adult with care and support needs is suspected of being at risk of abuse and is unable to protect themselves. Which interpretation by the nurse is most accurate?",
 opts:["The local authority has a duty under section 42 to make enquiries, and the nurse should support this process","Safeguarding enquiries only apply to children with care and support needs, so no action is required","The adult must consent before any enquiry can be made, regardless of risk","The nurse should investigate personally before involving the local authority"],
 ans:0, rat:{c:"Section 42 places a duty on the local authority to make enquiries where an adult with care and support needs is at risk of abuse and cannot protect themselves. Adult safeguarding is statutory, consent does not override serious risk, and the nurse should not investigate personally.", s:"Adult safeguarding duties are statutory; the nurse must understand when the duty is triggered."}},
{id:"MOC-228", t:"single", cn:"MOC", sys:"INTG", topic:"Financial abuse", d:3, b:0.55, cj:"recognize", tags:["management","financial abuse","safeguarding","exploitation","recognition"],
 stem:"An older client's daughter has taken control of the client's bank cards. The client is now unable to pay for prescriptions and has missed meals. Which interpretation by the nurse is most accurate?",
 opts:["These findings suggest financial abuse and require a safeguarding referral","These findings suggest poor family budgeting and require financial advice only","These findings suggest the client's own mismanagement and require education","These findings are a private family matter and do not concern the nurse"],
 ans:0, rat:{c:"Control of finances resulting in unmet essential needs suggests financial abuse, a recognised category of abuse requiring safeguarding referral. It is not merely poor budgeting, self-mismanagement, or a private matter.", s:"Financial abuse is often missed because it presents as practical hardship; the nurse must link the financial control to the unmet needs."}},
{id:"MOC-229", t:"single", cn:"MOC", sys:"INTG", topic:"Coercive control", d:3, b:0.55, cj:"recognize", tags:["management","coercive control","domestic abuse","recognition","safeguarding"],
 stem:"A client attends frequently with vague symptoms. The partner answers all questions, controls the appointment time, and the client appears anxious and defers constantly. Which interpretation by the nurse is most accurate?",
 opts:["These findings suggest coercive control and warrant a safe opportunity to speak to the client alone","These findings suggest a supportive partner and require no further action","These findings suggest the client has a communication difficulty and requires speech therapy","These findings suggest health anxiety and require psychiatric referral"],
 ans:0, rat:{c:"A partner answering for the client, controlling access, and the client's deference and anxiety suggest coercive control. The nurse should create a safe opportunity to speak with the client alone. It is not simply supportive behaviour, communication difficulty, or health anxiety.", s:"Coercive control rarely presents with physical injury; the nurse must recognise behavioural and interactional indicators."}},
{id:"MOC-230", t:"single", cn:"MOC", sys:"INTG", topic:"Apology as not an admission of liability", d:2, b:0.45, cj:"act", tags:["management","apology","duty of candour","liability","communication"],
 stem:"A nurse is advised to apologise to a client following an incident but worries this admits legal liability. Which interpretation by the nurse is most accurate?",
 opts:["An apology given under the duty of candour is not an admission of legal liability and should not be withheld","An apology admits liability and should be avoided until legal advice is obtained","An apology should be given only if the client explicitly requests one","An apology is inappropriate where no harm has occurred"],
 ans:0, rat:{c:"An apology under the duty of candour is expressly not an admission of legal liability and must not be withheld for that reason. It is not contingent on a request, and it is appropriate even where no harm occurred, since the incident itself warrants acknowledgement.", s:"Understanding that apology and liability are separate removes a common barrier to open disclosure."}},
{id:"MOC-231", t:"single", cn:"MOC", sys:"INTG", topic:"Human factors and the Swiss cheese model", d:3, b:0.55, cj:"analyze", tags:["management","human factors","Swiss cheese","systems","error prevention"],
 stem:"Following a medication error, an investigation identifies several system weaknesses that each alone would not have caused harm but which aligned. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with the Swiss cheese model, where multiple system defences fail together and system redesign is required","This confirms the individual nurse is at fault and requires disciplinary action","This indicates a single system failure requiring one specific fix","This model does not apply to medication errors"],
 ans:0, rat:{c:"The Swiss cheese model describes how several latent system weaknesses align to allow harm, requiring system-level redesign rather than individual blame. It does not confirm individual fault, and a single fix would leave the other holes in place.", s:"Human factors thinking shifts investigation from who to why; the nurse should understand the model's implications for prevention."}},

/* ---------------------------------------------------------- PHA 7 */
{id:"PHA-208", t:"single", cn:"PHA", sys:"ENDO", topic:"Continuous glucose monitoring", d:2, b:0.45, cj:"analyze", tags:["pharmacology","continuous glucose","CGM","diabetes","monitoring"],
 stem:"A client with type 1 diabetes uses continuous glucose monitoring. A capillary reading and the sensor reading disagree significantly, and the client feels unwell. Which action by the nurse is most appropriate?",
 opts:["Act on the capillary reading, since sensor readings can be unreliable when glucose is changing rapidly or the client is unwell","Act on the sensor glucose reading, since it is more advanced technology even when the client is unwell","Average the two readings and act on the mean rather than the capillary value","Wait thirty minutes and repeat both readings, since the discrepancy will resolve"],
 ans:0, rat:{c:"Sensor glucose measures interstitial fluid and lags behind blood glucose, particularly during rapid change or illness. Where readings disagree and the client is unwell, the capillary reading must guide action. Averaging or waiting both risk incorrect treatment.", s:"Understanding the physiological lag of sensor glucose is essential for safe decision-making with CGM."}},
{id:"PHA-209", t:"single", cn:"PHA", sys:"ENDO", topic:"Time in range", d:3, b:0.55, cj:"evaluate", tags:["pharmacology","time in range","CGM","diabetes","evaluation"],
 stem:"A client with type 1 diabetes has an HbA1c within target but continuous glucose monitoring shows frequent nocturnal hypoglycaemia. Which interpretation by the nurse is most accurate?",
 opts:["Time in range and hypoglycaemia metrics reveal risk that HbA1c alone conceals, and the regimen requires review","The HbA1c confirms good control and no change is required","Hypoglycaemia at night is not clinically significant and requires no action","HbA1c and time in range measure the same thing and cannot disagree"],
 ans:0, rat:{c:"HbA1c is an average and can conceal significant variability, including recurrent hypoglycaemia. Time in range and hypoglycaemia metrics reveal this risk and should prompt regimen review. Nocturnal hypoglycaemia is clinically significant.", s:"HbA1c averaging can mask dangerous variability; the nurse must interpret it alongside CGM-derived metrics."}},
{id:"PHA-210", t:"single", cn:"PHA", sys:"ENDO", topic:"Hypoglycaemia unawareness", d:3, b:0.55, cj:"act", tags:["pharmacology","hypoglycaemia unawareness","diabetes","risk","education"],
 stem:"A client with long-standing type 1 diabetes reports no warning symptoms during recent hypoglycaemic episodes and has had two severe events. Which action by the nurse is most appropriate?",
 opts:["Recognise hypoglycaemia unawareness, review targets and regimen to reduce further hypoglycaemia, and consider specialist referral","Advise the client to check glucose less often, since frequent checking increases anxiety","Increase insulin doses, since tighter control will restore awareness","Reassure the client, since awareness usually returns spontaneously"],
 ans:0, rat:{c:"Hypoglycaemia unawareness significantly increases the risk of severe hypoglycaemia and requires relaxation of targets, regimen review, and specialist referral. Reducing monitoring, increasing insulin, or expecting spontaneous recovery all increase risk.", s:"Hypoglycaemia unawareness can sometimes be improved by strict avoidance of hypoglycaemia; the nurse must act to reduce exposure."}},
{id:"PHA-211", t:"single", cn:"PHA", sys:"ENDO", topic:"Sick day rules", d:3, b:0.55, cj:"act", tags:["pharmacology","sick day rules","diabetes","ketones","education"],
 stem:"A client with type 1 diabetes has gastroenteritis, is vomiting, and has not eaten. They ask whether to omit insulin. Which action by the nurse is most appropriate?",
 opts:["Advise never to omit basal insulin, to monitor glucose and ketones frequently, and to seek help if ketones rise","Advise omitting insulin, since the client is not eating and hypoglycaemia is a risk","Advise taking only bolus insulin with any food eaten","Advise doubling the insulin dose, since illness increases requirements"],
 ans:0, rat:{c:"Basal insulin must never be omitted during illness, even without eating, because insulin requirement often rises and omission risks diabetic ketoacidosis. Glucose and ketones require frequent monitoring with clear escalation. Omitting insulin or blanket dose doubling are both unsafe.", s:"Sick day rules are a critical safety teaching point; omission of basal insulin is a common cause of avoidable ketoacidosis."}},
{id:"PHA-212", t:"single", cn:"PHA", sys:"ENDO", topic:"Lipohypertrophy", d:2, b:0.45, cj:"recognize", tags:["pharmacology","lipohypertrophy","injection site","diabetes","assessment"],
 stem:"A client with diabetes has erratic glucose control despite unchanged insulin doses. Inspection reveals lumpy, thickened areas at frequently used injection sites. Which interpretation by the nurse is most accurate?",
 opts:["These findings suggest lipohypertrophy causing erratic insulin absorption, and site rotation is required","These findings suggest infection and require antibiotic treatment","These findings suggest an allergic reaction and require a change of insulin","These findings are normal and do not cause erratic glucose control"],
 ans:0, rat:{c:"Lipohypertrophy from repeated injection into the same site causes unpredictable insulin absorption and erratic control, requiring site rotation and avoidance of affected areas. It is not infection or allergy, and it does affect control significantly.", s:"Lipohypertrophy is a common and reversible cause of erratic control; the nurse must inspect injection sites routinely."}},
{id:"PHA-213", t:"single", cn:"PHA", sys:"ENDO", topic:"Insulin-to-carbohydrate ratio", d:3, b:0.55, cj:"act", tags:["pharmacology","insulin ratio","carbohydrate counting","diabetes","dosing"],
 stem:"A client with type 1 diabetes uses an insulin-to-carbohydrate ratio of 1 unit to 15 grams and plans to eat a meal containing 60 grams of carbohydrate. Which action by the nurse is appropriate when verifying the client's dose?",
 opts:["Confirm the calculated dose of 4 units, since 60 grams divided by 15 grams per unit equals 4 units","Confirm a dose of 15 units, since the ratio is 1 unit to 15 grams","Confirm a dose of 60 units, since this matches the carbohydrate content","Confirm a dose of 90 units, since the carbohydrate and ratio are multiplied"],
 ans:0, rat:{c:"At a ratio of 1 unit per 15 grams, 60 grams of carbohydrate requires 60 divided by 15, which is 4 units. Using the ratio figure directly, the carbohydrate figure, or multiplying all produce dangerously incorrect doses.", s:"Ratio calculations are a common source of error; the nurse must be able to verify the client's arithmetic."}},
{id:"PHA-214", t:"single", cn:"PHA", sys:"ENDO", topic:"Steroid-induced diabetes", d:3, b:0.55, cj:"act", tags:["pharmacology","steroid induced diabetes","hyperglycaemia","monitoring","treatment"],
 stem:"A client without previous diabetes starts high-dose prednisolone and develops glucose readings of 16 mmol/L. Which action by the nurse is most appropriate?",
 opts:["Recognise steroid-induced hyperglycaemia, monitor glucose, and escalate for treatment, often requiring insulin","Reduce the steroid dose without discussion, since this will lower the glucose","Reassure the client, since steroid-induced hyperglycaemia requires no treatment","Withhold carbohydrate from the diet, since this alone will normalise glucose"],
 ans:0, rat:{c:"Corticosteroids commonly cause hyperglycaemia, often requiring insulin treatment. It must be recognised, monitored, and escalated. Unilaterally reducing steroids risks adrenal crisis and disease relapse, and dietary change alone is insufficient.", s:"Steroid-induced hyperglycaemia is common and treatable; the nurse must monitor and escalate rather than alter steroid prescribing."}},

/* ---------------------------------------------------------- RRP 6 */
{id:"RRP-158", t:"single", cn:"RRP", sys:"ENDO", topic:"Driving and hypoglycaemia", d:3, b:0.55, cj:"act", tags:["risk","driving","hypoglycaemia","diabetes","safety","legal"],
 stem:"A client on insulin asks about driving requirements. Which action by the nurse is most appropriate?",
 opts:["Advise checking glucose before driving and at intervals on longer journeys, carrying fast-acting carbohydrate, and not driving if hypoglycaemic","Advise that no precautions are needed if the client feels well","Advise stopping driving altogether, since insulin treatment prohibits it","Advise checking glucose only at the start of the journey"],
 ans:0, rat:{c:"Insulin-treated drivers must check glucose before driving and at intervals on longer journeys, carry carbohydrate, and must not drive while hypoglycaemic or shortly after an episode. Feeling well is unreliable, particularly with impaired awareness, and insulin does not automatically prohibit driving.", s:"Driving requirements for insulin-treated clients are legal obligations; the nurse must give and document the advice."}},
{id:"RRP-159", t:"single", cn:"RRP", sys:"ENDO", topic:"Blood ketone monitoring", d:3, b:0.55, cj:"act", tags:["risk","ketones","diabetes","ketoacidosis","monitoring"],
 stem:"A client with type 1 diabetes has a blood glucose of 18 mmol/L and feels nauseated with abdominal pain. Which action by the nurse is the priority?",
 opts:["Check blood ketones immediately, since hyperglycaemia with these symptoms may indicate diabetic ketoacidosis","Reduce the insulin dose, since the glucose will fall gradually","Recheck the blood glucose in four hours, since one reading is insufficient","Advise carbohydrate restriction, since this lowers glucose safely"],
 ans:0, rat:{c:"Hyperglycaemia with nausea and abdominal pain in type 1 diabetes requires immediate blood ketone measurement, as this combination may indicate ketoacidosis. Reducing insulin worsens the situation, delaying assessment is dangerous, and carbohydrate restriction does not treat insulin deficiency.", s:"Ketone testing is the decisive step in identifying ketoacidosis; the nurse must not delay it."}},
{id:"RRP-160", t:"single", cn:"RRP", sys:"ENDO", topic:"Variable rate intravenous insulin infusion", d:3, b:0.55, cj:"act", tags:["risk","VRII","insulin infusion","diabetes","monitoring"],
 stem:"A client is receiving a variable rate intravenous insulin infusion. Hourly capillary glucose monitoring is required. Which action by the nurse is most appropriate?",
 opts:["Monitor glucose hourly, adjust the infusion according to the protocol, and monitor potassium since insulin shifts it intracellularly","Monitor glucose every four hours rather than hourly, since this is sufficient during infusion","Adjust the rate according to clinical impression rather than the protocol","Withhold potassium monitoring, since insulin does not affect potassium"],
 ans:0, rat:{c:"Variable rate insulin infusion requires hourly glucose monitoring, protocol-driven rate adjustment, and potassium monitoring because insulin drives potassium into cells, risking hypokalaemia. Four-hourly monitoring and impression-based adjustment both breach safety requirements.", s:"Insulin infusion carries a hypokalaemia risk that is easily missed; the nurse must monitor both glucose and potassium."}},
{id:"RRP-161", t:"single", cn:"RRP", sys:"ENDO", topic:"HbA1c", d:2, b:0.45, cj:"analyze", tags:["risk","HbA1c","diabetes","monitoring","interpretation"],
 stem:"A client has an HbA1c of 8.5%. Which interpretation by the nurse is most accurate?",
 opts:["This reflects average glucose over approximately the preceding three months and indicates suboptimal control","This reflects glucose control over the preceding week","This indicates that control was good until recently and has suddenly worsened","HbA1c measures current blood glucose at the moment of sampling"],
 ans:0, rat:{c:"HbA1c reflects average glucose over approximately three months, corresponding to red cell lifespan, and 8.5% indicates suboptimal control. It does not reflect one week, cannot identify when control changed, and is not a point measurement.", s:"Understanding the timeframe HbA1c represents is essential for interpreting results and planning review."}},
{id:"RRP-162", t:"single", cn:"RRP", sys:"ENDO", topic:"Point of care testing quality", d:3, b:0.55, cj:"act", tags:["risk","point of care","quality control","testing","accuracy"],
 stem:"A ward glucometer produces a result that does not match the client's clinical presentation. Which action by the nurse is most appropriate?",
 opts:["Verify with a laboratory sample, check the meter's quality control status, and do not act on the doubtful result alone","Act on the meter result, since point of care testing is reliable","Repeat the meter test on the same finger, since this confirms the result","Replace the client's treatment based on the clinical impression alone"],
 ans:0, rat:{c:"A result discordant with presentation requires laboratory verification and quality control review before action. Repeating on the same finger may reproduce the same error, and treating on impression alone is unsafe. Point of care devices are not infallible.", s:"Point of care testing requires quality assurance; the nurse must know when to seek laboratory confirmation."}},
{id:"RRP-163", t:"single", cn:"RRP", sys:"ENDO", topic:"Exercise-related insulin adjustment", d:3, b:0.55, cj:"act", tags:["risk","exercise","insulin","diabetes","hypoglycaemia","education"],
 stem:"A client with type 1 diabetes plans to begin regular vigorous exercise and is concerned about hypoglycaemia. Which action by the nurse is most appropriate?",
 opts:["Advise planning carbohydrate intake and insulin dose adjustment around exercise, with additional monitoring before, during, and after","Advise exercising only in the morning, since hypoglycaemia cannot occur then","Advise stopping insulin on exercise days, since this prevents hypoglycaemia","Advise exercising without adjustment, since tolerance develops quickly"],
 ans:0, rat:{c:"Exercise increases insulin sensitivity and glucose uptake, requiring planned carbohydrate intake, dose adjustment, and monitoring before, during, and after activity, including delayed hypoglycaemia risk. Timing alone does not prevent risk, omitting insulin is dangerous, and no adjustment risks severe hypoglycaemia.", s:"Delayed hypoglycaemia can occur hours after exercise; the nurse must advise planning rather than restriction."}}

]);
