"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 45) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 44: MOC (17.9% vs 18),
 * SIC (12.9% vs 13), HPM (8.9% vs 9) and PHA (15.9% vs 16).
 * Every item is difficulty 2 or 3, and the clinical detail is
 * written to be defensible.
 *
 * MOC 5: mental capacity assessment, best interests meeting,
 * controlled drug register, two nurse check, and loss of a
 * controlled drug.
 * PHA 5: syringe driver, breakthrough dose, dose conversion,
 * opioid tolerance, and pseudo-addiction.
 * HPM 5: very brief advice for smoking, alcohol brief intervention,
 * binge drinking, alcohol in pregnancy, and carbon monoxide
 * monitoring.
 * SIC 5: take-home naloxone, cannabis-induced psychosis, nitrous
 * oxide, needle exchange, and drug driving.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- MOC 5 */
{id:"MOC-220", t:"single", cn:"MOC", sys:"INTG", topic:"Mental capacity assessment", d:3, b:0.55, cj:"analyze", tags:["management","mental capacity","assessment","decision-specific","autonomy"],
 stem:"A 70-year-old client with mild dementia wishes to refuse a recommended hip replacement. The surgical team believes the decision is unwise. Which action by the nurse is most appropriate?",
 opts:["Assess capacity for this specific decision, since an unwise decision does not in itself indicate lack of capacity","Assume lack of capacity, since the client has dementia and the decision is unwise","Ask the family to decide, since they know the client best","Proceed with surgery, since it is clinically indicated"],
 ans:0, rat:{c:"Capacity is decision-specific and time-specific; an unwise decision does not in itself indicate lack of capacity. A diagnosis of dementia does not automatically mean incapacity. Family cannot decide if the client has capacity, and proceeding without consent is unlawful.", s:"The principles of mental capacity law require decision-specific assessment and respect for unwise decisions made with capacity."}},
{id:"MOC-221", t:"single", cn:"MOC", sys:"INTG", topic:"Best interests meeting", d:3, b:0.55, cj:"act", tags:["management","best interests","capacity","decision-making","documentation"],
 stem:"A client lacks capacity to decide about discharge placement. The family want the client home, but the team believes a care home is safer. Which action by the nurse is most appropriate?",
 opts:["Convene a best interests meeting with the multidisciplinary team and family, and document the reasoning","Allow the family to decide, since they are next of kin","Decide as a team without involving the family, since clinical judgement prevails","Delay the decision until the client regains capacity"],
 ans:0, rat:{c:"A best interests decision requires a structured meeting involving the multidisciplinary team and family, with documented reasoning. Next of kin do not automatically decide, excluding the family breaches the process, and delaying indefinitely fails the client.", s:"Best interests decisions follow a statutory checklist; the nurse must ensure the process is followed and documented."}},
{id:"MOC-222", t:"single", cn:"MOC", sys:"INTG", topic:"Controlled drug register", d:2, b:0.45, cj:"act", tags:["management","controlled drug","register","documentation","legal"],
 stem:"A nurse administers a controlled drug and must record it. Which action by the nurse is most appropriate?",
 opts:["Record the administration in the controlled drug register at the time of administration, with a second nurse signature","Record it at the end of the shift, since this is more efficient","Record it in the patient notes only, since the controlled drug register is not required","Ask a healthcare assistant to record it, since this saves time"],
 ans:0, rat:{c:"Controlled drug administration must be recorded contemporaneously in the controlled drug register with a second nurse signature. Delayed recording, recording only in notes, or delegation to an unlicensed assistant all breach legal requirements.", s:"Controlled drug record keeping is a legal requirement; the nurse must understand the timing and signature requirements."}},
{id:"MOC-223", t:"single", cn:"MOC", sys:"INTG", topic:"Two nurse check", d:2, b:0.45, cj:"act", tags:["management","two nurse check","controlled drug","safety","verification"],
 stem:"A nurse is preparing to administer a controlled drug. Which action by the nurse is most appropriate?",
 opts:["Have a second registered nurse verify the drug, dose, route, and client identity before administration","Check the drug against the prescription alone, since this is sufficient","Ask a healthcare assistant to witness, since they are available","Administer the drug and ask a colleague to sign afterwards"],
 ans:0, rat:{c:"A second registered nurse must verify the drug, dose, route, and client identity before administration. Checking alone, using an unlicensed assistant, or obtaining a retrospective signature all fail the requirement for independent contemporaneous verification.", s:"Two nurse checking is a core controlled drug safety control; the nurse must understand who may act as second checker."}},
{id:"MOC-224", t:"single", cn:"MOC", sys:"INTG", topic:"Loss of a controlled drug", d:3, b:0.55, cj:"act", tags:["management","controlled drug","loss","reporting","accountability"],
 stem:"A nurse discovers that a controlled drug ampoule has been dropped and the contents lost. Which action by the nurse is most appropriate?",
 opts:["Record the wastage in the controlled drug register with a witness signature and report the loss according to policy","Dispose of the broken ampoule and record the controlled drug as a full dose administered","Record the wastage at the end of the shift, since this is when records are completed","Do not record it, since the drug was not given to a client"],
 ans:0, rat:{c:"Controlled drug wastage must be recorded contemporaneously in the register with a witness signature and reported according to policy. Recording a full dose as administered is falsification, delayed recording breaches requirements, and omitting the record breaches accountability.", s:"Controlled drug wastage and loss require specific recording and reporting; the nurse must follow both."}},

/* ---------------------------------------------------------- PHA 5 */
{id:"PHA-203", t:"single", cn:"PHA", sys:"INTG", topic:"Syringe driver", d:3, b:0.55, cj:"act", tags:["pharmacology","syringe driver","subcutaneous infusion","palliative","administration"],
 stem:"A client at the end of life can no longer swallow and requires continuous symptom control. Which action by the nurse is most appropriate?",
 opts:["Convert to a subcutaneous infusion via syringe driver, calculating the 24-hour dose from the current oral requirement","Continue oral medication crushed in water, since this maintains the current regimen","Administer intramuscular injections hourly, since this ensures absorption","Withhold analgesia, since the client is dying and no longer requires it"],
 ans:0, rat:{c:"When the oral route is lost, conversion to a continuous subcutaneous infusion with the 24-hour dose calculated from the oral requirement maintains symptom control. Crushed oral medication is unreliable, hourly intramuscular injections are painful and impractical, and withholding analgesia is unacceptable.", s:"Syringe driver conversion is a core palliative care skill; the nurse must understand dose conversion and route change."}},
{id:"PHA-204", t:"single", cn:"PHA", sys:"INTG", topic:"Breakthrough dose", d:2, b:0.45, cj:"act", tags:["pharmacology","breakthrough dose","opioid","palliative","dosing"],
 stem:"A client is taking modified-release morphine 60 mg twice daily for cancer pain. The prescription requires a breakthrough dose. Which action by the nurse is most appropriate?",
 opts:["Administer one sixth of the total daily dose, which is 20 mg of immediate-release morphine, as breakthrough","Administer 60 mg of immediate-release morphine, since this matches the daily modified-release dose","Administer 30 mg of immediate-release morphine, since this is half the modified-release dose","Withhold breakthrough analgesia, since the modified-release dose should be sufficient"],
 ans:0, rat:{c:"The breakthrough dose is typically one sixth of the total daily modified-release dose. For 60 mg twice daily (120 mg total), one sixth is 20 mg. Using the full modified-release dose, half the dose, or withholding breakthrough analgesia are all incorrect.", s:"Breakthrough dose calculation is a core prescribing and administration skill; the nurse must be able to verify the calculation."}},
{id:"PHA-205", t:"single", cn:"PHA", sys:"INTG", topic:"Dose conversion", d:3, b:0.55, cj:"act", tags:["pharmacology","dose conversion","opioid","equianalgesic","safety"],
 stem:"A client is being switched from oral morphine to oral oxycodone because of adverse effects. Which action by the nurse is most appropriate?",
 opts:["Use an equianalgesic conversion table and reduce the calculated dose to allow for incomplete cross-tolerance","Convert using an equal milligram dose, since both drugs are equally potent","Double the calculated dose, since oxycodone is less potent than morphine","Ask the client which dose they prefer, since they know what works"],
 ans:0, rat:{c:"Opioid switching requires an equianalgesic conversion table with dose reduction to allow for incomplete cross-tolerance. Equal milligram conversion risks overdose, doubling the dose is incorrect, and client preference does not determine safe conversion.", s:"Incomplete cross-tolerance means converted doses must be reduced; the nurse must understand this safety principle."}},
{id:"PHA-206", t:"single", cn:"PHA", sys:"INTG", topic:"Opioid tolerance", d:2, b:0.45, cj:"analyze", tags:["pharmacology","opioid tolerance","dependence","distinction","assessment"],
 stem:"A client on long-term opioids requires increasing doses to achieve the same analgesic effect. A relative asks whether the client is addicted. Which response by the nurse is most appropriate?",
 opts:["Explain that this is tolerance, a physiological adaptation, which is distinct from addiction","Explain that the client is addicted and requires specialist referral","Explain that the dose should be reduced immediately, since increasing doses are unsafe","Explain that opioids lose all effect over time and should be stopped"],
 ans:0, rat:{c:"Tolerance is a physiological adaptation requiring increasing doses for the same effect, and is distinct from addiction, which involves compulsive use despite harm. Increasing doses are appropriate in tolerance, and opioids do not lose all effect.", s:"Distinguishing tolerance from addiction is essential; the nurse must be able to explain this to clients and families."}},
{id:"PHA-207", t:"single", cn:"PHA", sys:"INTG", topic:"Pseudo-addiction", d:3, b:0.55, cj:"analyze", tags:["pharmacology","pseudo-addiction","pain","under-treatment","assessment"],
 stem:"A client with cancer pain appears preoccupied with obtaining opioids, watches the clock, and requests doses early. The pain score remains high. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with pseudo-addiction caused by under-treated pain, and the analgesic regimen requires review","This is consistent with addiction and requires restriction of opioids","This is consistent with drug-seeking behaviour and requires confrontation","This is consistent with anxiety and requires anxiolytic treatment"],
 ans:0, rat:{c:"Pseudo-addiction describes addiction-like behaviour caused by under-treated pain; the behaviour resolves when pain is controlled. It is not addiction, drug-seeking, or anxiety. Restricting opioids would worsen both the pain and the behaviour.", s:"Recognising pseudo-addiction prevents mislabelling clients in pain; the nurse must assess analgesic adequacy first."}},

/* ---------------------------------------------------------- HPM 5 */
{id:"HPM-112", t:"single", cn:"HPM", sys:"RESP", topic:"Very brief advice for smoking", d:2, b:0.45, cj:"act", tags:["health promotion","smoking","very brief advice","cessation","opportunistic"],
 stem:"A nurse is caring for a client admitted with an exacerbation of chronic obstructive pulmonary disease who smokes. The nurse has only a few minutes available. Which action by the nurse is most appropriate?",
 opts:["Give very brief advice asking, advising, and acting, and offer referral to stop-smoking services","Wait for a dedicated appointment, since brief advice is ineffective","Ask the client to cut down rather than stop, since this is more achievable","Do not raise smoking, since the client is acutely unwell"],
 ans:0, rat:{c:"Very brief advice using ask, advise, act takes under a minute and is effective, particularly during an admission for a smoking-related condition. Waiting for a dedicated appointment misses the opportunity, advising reduction is less effective, and avoiding the topic wastes a teachable moment.", s:"Very brief advice is an evidence-based opportunistic intervention; acute admission is a high-yield moment."}},
{id:"HPM-113", t:"single", cn:"HPM", sys:"GI", topic:"Alcohol brief intervention", d:3, b:0.55, cj:"act", tags:["health promotion","alcohol","brief intervention","screening","behaviour change"],
 stem:"A client screens positive on an alcohol screening tool but does not consider their drinking a problem. Which action by the nurse is most appropriate?",
 opts:["Deliver a brief intervention exploring the link between drinking and current health concerns, without confrontation","Insist the client stop drinking immediately, since the screening is positive","Accept the client's view, since they do not consider it a problem","Refer to specialist services only, since brief intervention is insufficient"],
 ans:0, rat:{c:"A brief intervention explores the link between drinking and the client's health concerns in a non-confrontational way, which can motivate change. Insisting on immediate cessation, accepting denial without exploration, or referring only all fail to deliver the intervention.", s:"Brief intervention is effective for hazardous drinking; the nurse should use a motivational rather than confrontational approach."}},
{id:"HPM-114", t:"single", cn:"HPM", sys:"GI", topic:"Binge drinking", d:2, b:0.45, cj:"analyze", tags:["health promotion","binge drinking","alcohol","risk","assessment"],
 stem:"A young adult reports drinking heavily at weekends but abstaining during the week, and does not consider this harmful. Which interpretation by the nurse is most accurate?",
 opts:["This pattern is consistent with binge drinking and carries acute risks even without daily consumption","This pattern of drinking is protective, since abstinence during the week allows recovery","This pattern indicates alcohol dependence and requires detoxification","This pattern carries no risk, since total weekly intake is low"],
 ans:0, rat:{c:"Binge drinking carries acute risks including injury, arrhythmia, and acute pancreatitis even without daily consumption. Weekend abstinence does not eliminate risk. The pattern does not indicate dependence, and total weekly intake is not the only risk measure.", s:"Binge drinking risk is distinct from dependence; the nurse must recognise acute harms in intermittent heavy drinking."}},
{id:"HPM-115", t:"single", cn:"HPM", sys:"ENDO", topic:"Alcohol in pregnancy", d:3, b:0.55, cj:"act", tags:["health promotion","alcohol","pregnancy","FASD","prevention"],
 stem:"A pregnant client asks how much alcohol is safe to drink. Which response by the nurse is most appropriate?",
 opts:["Advise that there is no known safe level and that the safest approach is to avoid alcohol entirely","Advise that one or two units per week is safe, since this is low risk","Advise that alcohol is safe after the first trimester, since organogenesis is complete","Advise that only spirits should be avoided, since wine and beer are safer"],
 ans:0, rat:{c:"There is no established safe level of alcohol in pregnancy, and the safest approach is complete avoidance. Low-unit advice, trimester-based advice, and beverage-based distinctions are all unsupported and risk harm.", s:"Alcohol in pregnancy carries risk of fetal alcohol spectrum disorder; the nurse must give unambiguous advice."}},
{id:"HPM-116", t:"single", cn:"HPM", sys:"RESP", topic:"Carbon monoxide monitoring in smoking cessation", d:2, b:0.45, cj:"act", tags:["health promotion","carbon monoxide","smoking cessation","monitoring","motivation"],
 stem:"A client attending a stop-smoking service asks what a carbon monoxide monitor measures. Which response by the nurse is most appropriate?",
 opts:["Explain that it measures exhaled carbon monoxide from smoking and provides immediate feedback on smoke exposure","Explain that it measures blood oxygen saturation rather than carbon monoxide","Explain that it measures nicotine levels in the breath","Explain that it measures lung function"],
 ans:0, rat:{c:"A carbon monoxide monitor measures exhaled carbon monoxide, providing immediate feedback on smoke exposure and reinforcing motivation to quit. It does not measure oxygen saturation, nicotine, or lung function.", s:"Carbon monoxide monitoring is a motivational tool in cessation support; the nurse must explain what it measures accurately."}},

/* ---------------------------------------------------------- SIC 5 */
{id:"SIC-162", t:"single", cn:"SIC", sys:"RESP", topic:"Take-home naloxone", d:3, b:0.55, cj:"act", tags:["safety","naloxone","overdose","harm reduction","opioid"],
 stem:"A client with a history of opioid overdose is being discharged. The client's partner asks about overdose prevention. Which action by the nurse is most appropriate?",
 opts:["Provide take-home naloxone and train the partner in its administration, since this reduces overdose mortality","Advise the partner to call an ambulance only in an overdose, since naloxone is for professionals","Advise the client to use alone, since this avoids involving others","Explain that naloxone is not available for home use"],
 ans:0, rat:{c:"Take-home naloxone with training for the client and their contacts reduces overdose mortality and is a core harm reduction intervention. Advising ambulance-only response, encouraging using alone, or claiming unavailability all withhold a life-saving intervention.", s:"Take-home naloxone is an evidence-based harm reduction measure; the nurse should provide it and train bystanders."}},
{id:"SIC-163", t:"single", cn:"SIC", sys:"PSYCH", topic:"Cannabis-induced psychosis", d:3, b:0.55, cj:"recognize", tags:["safety","cannabis","psychosis","substance use","assessment"],
 stem:"A young adult presents with acute paranoia and hallucinations after several days of heavy cannabis use. Which interpretation by the nurse is most accurate?",
 opts:["This may be cannabis-induced psychosis, which requires assessment and observation, with symptoms often resolving on cessation","This is definitely primary schizophrenia and requires long-term antipsychotic treatment","This is not related to cannabis, since cannabis does not cause psychosis","This requires no intervention, since cannabis effects are harmless"],
 ans:0, rat:{c:"Heavy cannabis use can precipitate acute psychosis, which requires assessment and observation; symptoms often resolve with cessation. A diagnosis of primary schizophrenia cannot be made during intoxication. Cannabis can cause psychosis, and the presentation requires intervention.", s:"Cannabis-induced psychosis is common in young adults; the nurse must assess and observe rather than dismiss or over-diagnose."}},
{id:"SIC-164", t:"single", cn:"SIC", sys:"NEURO", topic:"Nitrous oxide", d:3, b:0.55, cj:"recognize", tags:["safety","nitrous oxide","substance use","neurological","B12"],
 stem:"A young adult who regularly inhales nitrous oxide presents with numbness, paraesthesia, and unsteady gait. Which interpretation by the nurse is most accurate?",
 opts:["These findings suggest nitrous oxide-related functional vitamin B12 inactivation causing neurological damage and require urgent assessment","These findings suggest anxiety and require reassurance","These findings are temporary effects of nitrous oxide and will resolve without treatment","These findings suggest multiple sclerosis and require neurology referral"],
 ans:0, rat:{c:"Nitrous oxide inactivates vitamin B12 and can cause subacute combined degeneration of the cord with sensory and motor deficits, requiring urgent assessment and B12 treatment. The findings are not anxiety, are not self-limiting, and multiple sclerosis is not the most likely cause.", s:"Nitrous oxide neurotoxicity is an under-recognised emergency; the nurse must link the exposure to the neurological presentation."}},
{id:"SIC-165", t:"single", cn:"SIC", sys:"INF", topic:"Needle exchange", d:2, b:0.45, cj:"act", tags:["safety","needle exchange","harm reduction","infection prevention","substance use"],
 stem:"A client who injects drugs asks about obtaining clean injecting equipment. Which action by the nurse is most appropriate?",
 opts:["Provide information about needle exchange services, since this reduces blood-borne virus transmission without endorsing use","Refuse to discuss it, since this would condone drug use","Advise the client to reuse equipment, since sharing is the only risk","Advise immediate abstinence, since this is the only safe option"],
 ans:0, rat:{c:"Needle exchange reduces blood-borne virus transmission and is a core harm reduction intervention; providing information does not endorse use. Refusing to discuss it, advising reuse, or insisting on abstinence only all increase risk and disengage the client.", s:"Harm reduction engages clients who are not ready to abstain; the nurse must understand its evidence base."}},
{id:"SIC-166", t:"single", cn:"SIC", sys:"INTG", topic:"Drug driving", d:2, b:0.45, cj:"act", tags:["safety","drug driving","legal","counselling","risk"],
 stem:"A client prescribed a sedating medication asks whether they may continue to drive. Which action by the nurse is most appropriate?",
 opts:["Advise the client of the impairment risk and their legal duty not to drive while impaired, and document the advice","Advise the client that they may drive if they feel alert","Avoid the topic, since driving is not a nursing responsibility","Advise the client to stop the medication so they can continue driving"],
 ans:0, rat:{c:"The nurse must advise on impairment risk and the legal duty not to drive while impaired, and document that advice. Advising driving based on subjective alertness, avoiding the topic, or stopping necessary medication all fail the client and increase risk.", s:"Driving advice for sedating medication is a legal and safety duty; the nurse must give and document it."}}

]);
