/* ============================================================================
   bank14.js — hand-authored wave 4 (24 items)

   WHY THIS FILE EXISTS
     Waves 1-3 were aimed at measured clientNeed share gaps. That targeting was
     too coarse: a wave can close the category count while re-asking a topic the
     bank already covers. The first version of this file did exactly that — 12 of
     its 24 items reused an existing topic outright (thyroid storm, informed
     consent, chain of command, vancomycin infusion reaction, digoxin toxicity,
     postoperative hemorrhage, ABG interpretation, transfusion reaction,
     neutropenic precautions, restraint safety, suicide risk assessment,
     colorectal screening), and several more sat on a neighbouring spelling of a
     covered topic. `itemlint` reported them clean because its duplicate scan is
     fingerprint-exact: a paraphrase of an existing stem is a different
     fingerprint. So those items were rewritten here.

     Every topic below was checked against the rest of the bank (stem + options +
     topic + summary rationale) and appears nowhere else.

   DISTRIBUTION
     PAA 6 · MOC 5 · PHA 4 · RRP 4 · SIC 3 · PSY 1 · HPM 1

   AUTHORING RULES OBSERVED
     · no stem token that occurs only in the key option (defeats guessing)
     · key is not systematically the longest option
     · distractors are plausible and clinically wrong for a real reason
     · rationale explains the key and each distractor, plus a one-line takeaway
   ========================================================================== */
window.NC.BANK.push(
/* ── Physiological Adaptation (blueprint 14%) ─────────────────────── */
{id:"PAA-064", t:"single", cn:"PAA", sys:"ENDO", topic:"Primary aldosteronism", d:2, b:0.2, cj:"analyze", tags:["aldosterone","hypertension","potassium"],
 stem:"A client has persistent hypertension and a serum potassium of 2.9 mEq/L. Testing shows elevated aldosterone with suppressed plasma renin. Which finding does the nurse expect alongside these results?",
 opts:["Mild metabolic alkalosis with sodium retention",
  "Elevated renin with low aldosterone",
  "Hyperkalemia with sodium loss",
  "Metabolic acidosis with a normal sodium"],
 ans:0,
 rat:{c:"Excess aldosterone drives sodium retention and potassium and hydrogen excretion, so hypertension pairs with hypokalemia and a mild metabolic alkalosis. Suppressed renin confirms the aldosterone is primary rather than secondary to low perfusion.",
  o:["Correct — sodium retention with potassium and hydrogen loss.",
    "Elevated renin would indicate secondary aldosteronism, not primary.",
    "Hyperkalemia and sodium loss are the opposite of aldosterone excess.",
    "The acid-base shift is alkalosis from hydrogen excretion, not acidosis."],
  s:"Primary aldosteronism: hypertension, hypokalemia, metabolic alkalosis, low renin."},
 ref:"Endocrine · adrenal cortex disorders"},

{id:"PAA-065", t:"single", cn:"PAA", sys:"ENDO", topic:"Pheochromocytoma crisis", d:3, b:0.5, cj:"prioritize", tags:["catecholamine","hypertensive-crisis","adrenal-medulla"],
 stem:"A client with a known adrenal medullary tumor develops a blood pressure of 224/128 mm Hg, pounding headache, and profuse sweating. Which intervention does the nurse anticipate first?",
 opts:["An intravenous alpha-adrenergic blocking agent",
  "Palpation of the abdomen to assess for a mass",
  "A beta blocking agent given on its own",
  "Restricting oral intake until further instruction"],
 ans:0,
 rat:{c:"A catecholamine surge from a pheochromocytoma causes severe vasoconstriction. Alpha blockade must come first to relax the vasculature. A beta blocker given alone leaves alpha-mediated constriction unopposed and can worsen the hypertension.",
  o:["Correct — alpha blockade is the first step in a catecholamine crisis.",
    "Palpating the tumor can trigger further catecholamine release.",
    "Unopposed alpha stimulation from beta blockade alone raises pressure further.",
    "Fluid status matters later, but intake restriction is not the priority."],
  s:"Pheochromocytoma: alpha blocker before beta blocker, and never palpate the mass."},
 ref:"Endocrine · adrenal medulla disorders"},

{id:"PAA-066", t:"single", cn:"PAA", sys:"ENDO", topic:"Diabetes insipidus after pituitary surgery", d:2, b:0.2, cj:"prioritize", tags:["pituitary","polyuria","vasopressin"],
 stem:"Twenty-four hours after transsphenoidal pituitary surgery, a client's urine output rises to 450 mL per hour and the urine specific gravity falls to 1.003. Which action does the nurse take first?",
 opts:["Notify the provider and anticipate vasopressin replacement",
  "Restrict oral fluids until the output normalizes",
  "Obtain a repeat urine specimen in eight hours",
  "Encourage ambulation to reduce the output"],
 ans:0,
 rat:{c:"Large volumes of dilute urine after pituitary surgery indicate transient or permanent diabetes insipidus from absent antidiuretic hormone. Without replacement the client loses free water rapidly and becomes hypernatremic, so this is a provider notification, not a watchful wait.",
  o:["Correct — report the pattern and expect antidiuretic hormone replacement.",
    "Fluid restriction worsens the free-water deficit and the hypernatremia.",
    "Eight hours of unreported polyuria risks severe dehydration.",
    "Ambulation does not address a hormone deficit and may cause a fall."],
  s:"Post-pituitary polyuria with dilute urine is diabetes insipidus until proven otherwise."},
 ref:"Endocrine · posterior pituitary disorders"},

{id:"PAA-067", t:"single", cn:"PAA", sys:"NEURO", topic:"Cerebral salt wasting", d:3, b:0.6, cj:"analyze", tags:["hyponatremia","volume-status","subarachnoid"],
 stem:"A client with a subarachnoid hemorrhage has a serum sodium of 126 mEq/L, a urine output of 300 mL per hour, and dry mucous membranes with flat neck veins. Which interpretation is correct?",
 opts:["Cerebral salt wasting, which is treated with volume and salt replacement",
  "Syndrome of inappropriate antidiuretic hormone, which is treated with fluid restriction",
  "Diabetes insipidus, which requires vasopressin replacement",
  "Osmotic diuresis from the contrast agent"],
 ans:0,
 rat:{c:"Both cerebral salt wasting and SIADH cause hyponatremia after intracranial injury, so volume status decides. Cerebral salt wasting is hypovolemic with polyuria and needs volume plus sodium. SIADH is euvolemic or hypervolemic and is fluid restricted — giving the wrong one harms the client.",
  o:["Correct — hypovolemia with natriuresis identifies salt wasting, treated with volume and sodium.",
    "SIADH is not volume depleted; restricting fluid here would worsen the hypovolemia.",
    "Diabetes insipidus produces hypernatremia with dilute urine, not hyponatremia.",
    "Contrast osmotic diuresis does not explain a sodium of 126 mEq/L."],
  s:"Hyponatremia after brain injury: check volume status first. Hypovolemic means salt wasting."},
 ref:"Neuro · complications of intracranial hemorrhage"},

{id:"PAA-068", t:"single", cn:"PAA", sys:"ENDO", topic:"Myxedema coma", d:3, b:0.6, cj:"act", tags:["hypothyroidism","hypothermia","emergency"],
 stem:"A client with long-standing untreated hypothyroidism is brought in with a temperature of 34.6 C, a heart rate of 46/min, and shallow respirations. Which intervention does the nurse expect to be included?",
 opts:["Passive rewarming and intravenous thyroid hormone replacement",
  "Active rewarming with a forced-air warming blanket",
  "A cooling blanket until the temperature normalizes",
  "Rapid infusion of a hypotonic solution"],
 ans:0,
 rat:{c:"Myxedema coma is decompensated hypothyroidism with hypothermia, bradycardia, and hypoventilation. Rewarming must be passive because active external warming causes peripheral vasodilation and cardiovascular collapse in a client with reduced cardiac output.",
  o:["Correct — passive rewarming plus hormone replacement, often with glucocorticoids.",
    "Active rewarming causes vasodilation and can precipitate shock.",
    "Cooling would deepen an already dangerous hypothermia.",
    "These clients are usually hyponatremic; hypotonic fluid worsens it."],
  s:"Myxedema coma: warm passively, replace thyroid hormone, support ventilation."},
 ref:"Endocrine · thyroid emergencies"},

{id:"PAA-069", t:"single", cn:"PAA", sys:"ENDO", topic:"Hyperosmolar hyperglycemic state", d:2, b:0.1, cj:"analyze", tags:["hyperglycemia","osmolality","fluid-deficit"],
 stem:"A client with type 2 diabetes arrives with a blood glucose of 780 mg/dL, a serum osmolality of 340 mOsm/kg, and no ketones in the urine. Which finding does the nurse expect?",
 opts:["Profound fluid volume deficit from osmotic diuresis",
  "A rapid onset with marked ketonemia",
  "A serum pH of 7.15 with a fruity breath odor",
  "A blood glucose below 400 mg/dL"],
 ans:0,
 rat:{c:"In hyperosmolar hyperglycemic state there is enough endogenous insulin to suppress lipolysis, so ketones stay absent while extreme hyperglycemia pulls water into the urine. The osmotic diuresis produces a fluid deficit often larger than in ketoacidosis.",
  o:["Correct — massive osmotic diuresis defines the volume deficit.",
    "Rapid onset with ketonemia describes ketoacidosis, which this is not.",
    "Acidosis and fruity breath are ketoacidosis findings; ketones are absent here.",
    "Glucose in this state is typically above 600 mg/dL."],
  s:"HHS: very high glucose, high osmolality, no ketones, severe dehydration."},
 ref:"Endocrine · diabetes emergencies"},

/* ── Management of Care (blueprint 18%) ───────────────────────────── */
{id:"MOC-069", t:"single", cn:"MOC", sys:"INTG", topic:"Client valuables and personal property", d:1, b:-0.8, cj:"act", tags:["property","accountability","safety"],
 stem:"A client is admitted from the emergency department wearing a wedding ring and carrying a wallet. Which action should the nurse take regarding these belongings?",
 opts:["Offer to send the items home with a family member or place them in hospital security",
  "Leave the items at the bedside for the client to keep",
  "Place the items in the client's bedside drawer",
  "Dispose of the wallet and keep the ring on the client"],
 ans:0,
 rat:{c:"The facility is accountable for anything left in its custody, and bedside storage is not secure. Offering a receipted route home or to security protects the client's property and documents the transfer of responsibility.",
  o:["Correct — a receipted disposition removes the loss risk and documents it.",
    "Bedside storage leaves valuables unsecured and unaccounted for.",
    "A bedside drawer is not a controlled storage location.",
    "Discarding client property is never acceptable."],
  s:"Valuables go home or to security with a signed receipt, and the disposition is documented."},
 ref:"Management of care · client property"},

{id:"MOC-070", t:"single", cn:"MOC", sys:"INTG", topic:"Impaired colleague reporting", d:2, b:0.2, cj:"prioritize", tags:["impairment","advocacy","safety"],
 stem:"A nurse smells alcohol on the breath of a colleague who is about to begin a medication pass and notices slurred speech. Which action should the nurse take first?",
 opts:["Report the concern to the nurse manager before the colleague gives any medication",
  "Ask the colleague to explain the slurred speech privately",
  "Complete the medication pass for the colleague",
  "Document the observation and say nothing further"],
 ans:0,
 rat:{c:"Suspected impairment is an immediate client-safety risk, and the nurse who observes it must remove the colleague from care through the proper channel before any further practice. Confrontation and silence both leave clients exposed.",
  o:["Correct — escalate to the manager now, before further practice.",
    "A private conversation does not remove the colleague from client care.",
    "Covering for impaired practice protects no one and implicates the nurse.",
    "Documenting without acting leaves clients at risk."],
  s:"Suspected impairment: report up the chain immediately, and do not cover for it."},
 ref:"Management of care · professional accountability"},

{id:"MOC-071", t:"single", cn:"MOC", sys:"INTG", topic:"Postmortem care and organ donation", d:2, b:0.1, cj:"generate", tags:["death","donation","referral"],
 stem:"A client has just been pronounced dead. The family asks the nurse whether tissues can still be donated. Which response by the nurse is appropriate?",
 opts:["Notify the organ procurement organization, since referral is required before any discussion of donation",
  "Explain that donation is no longer possible once death has been pronounced",
  "Obtain the family's written consent and proceed with the recovery",
  "Tell the family to speak with the medical examiner only"],
 ans:0,
 rat:{c:"Death does not end donation eligibility; hospitals are required to refer every death to the organ procurement organization, which is trained and authorized to make the request and determine suitability.",
  o:["Correct — timely referral is required, and the organization leads the discussion.",
    "Donation remains possible after death; this gives the family false information.",
    "A bedside nurse does not obtain donation consent or arrange recovery.",
    "The medical examiner is involved only in reportable deaths."],
  s:"Every death is referred to the organ procurement organization before donation is discussed."},
 ref:"Management of care · end-of-life and donation"},

{id:"MOC-072", t:"single", cn:"MOC", sys:"INTG", topic:"Interfacility client transfer", d:2, b:-0.2, cj:"act", tags:["continuity","handoff","communication"],
 stem:"A client is being transferred to a rehabilitation facility after a stroke. Which action is the nurse's responsibility during the transfer?",
 opts:["Send a written summary of the client's status, medications, and pending results with the client",
  "Give the family the facility's address and end the involvement",
  "Send only the discharge prescription to the receiving nurse",
  "Wait for the receiving facility to request the records"],
 ans:0,
 rat:{c:"Continuity of care means the receiving team starts with the full clinical picture. A written summary covering status, medications, and pending results prevents duplicated or missed care, whereas a partial handoff shifts the gap onto the client.",
  o:["Correct — a complete written summary travels with the client.",
    "Ending involvement abandons the handoff responsibility.",
    "A prescription alone omits status and pending results.",
    "Waiting for a request delays care and is not the sending nurse's role."],
  s:"Transfers require a complete written handoff: status, medications, pending results."},
 ref:"Management of care · continuity of care"},

{id:"MOC-073", t:"single", cn:"MOC", sys:"INTG", topic:"Client grievance response", d:1, b:-0.9, cj:"generate", tags:["advocacy","communication","rights"],
 stem:"A client tells the nurse, 'No one has answered my call light for twenty minutes, and I want to file a complaint.' Which response by the nurse is best?",
 opts:["Acknowledge the concern, address the immediate need, and explain how to submit a grievance",
  "Explain that the unit was short-staffed on this shift",
  "Tell the client that complaining will not change staffing",
  "Ask another client in the room to use the call light less"],
 ans:0,
 rat:{c:"A grievance is a protected client right. The nurse responds by taking the concern seriously, fixing the underlying problem, and telling the client exactly how to escalate, rather than defending the unit or discouraging the report.",
  o:["Correct — validate, act on the need, and explain the formal route.",
    "Explaining staffing defends the unit instead of serving the client.",
    "Discouraging a complaint undermines a protected right.",
    "Asking another client to limit call light use is inappropriate."],
  s:"For a grievance: acknowledge, remedy the cause, and explain the formal process."},
 ref:"Management of care · client rights"},

/* ── Pharmacological & Parenteral Therapies (blueprint 16%) ───────── */
{id:"PHA-070", t:"single", cn:"PHA", sys:"INF", topic:"Aminoglycoside level monitoring", d:2, b:0.1, cj:"recognize", tags:["aminoglycoside","monitoring","nephrotoxicity"],
 stem:"A client is receiving intravenous gentamicin every eight hours. Which instruction about blood sampling does the nurse anticipate?",
 opts:["Draw a level thirty minutes before the next dose to confirm the lowest concentration",
  "Draw a level immediately after the infusion ends",
  "Skip level monitoring while renal function stays normal",
  "Draw the level only if hearing changes are reported"],
 ans:0,
 rat:{c:"Aminoglycosides are narrow therapeutic index drugs cleared by the kidneys. The trough drawn just before the next dose shows whether drug is accumulating; waiting for ototoxicity or a creatinine rise means waiting for damage that is often irreversible.",
  o:["Correct — the trough reflects accumulation and guides the next dose.",
    "A post-infusion draw is a peak, which answers a different question.",
    "Levels are needed throughout therapy, not only when kidneys decline.",
    "Hearing loss and renal injury are late and often permanent."],
  s:"Aminoglycosides: draw the trough just before the next dose and trend renal function."},
 ref:"Pharmacology · narrow therapeutic index agents"},

{id:"PHA-071", t:"single", cn:"PHA", sys:"INF", topic:"Ophthalmic drop administration", d:1, b:-0.7, cj:"act", tags:["eye","technique","administration"],
 stem:"The nurse is preparing to instill eye drops into a client's right eye. Which technique is correct?",
 opts:["Place the drop in the lower conjunctival sac while the client looks upward",
  "Place the drop directly onto the cornea",
  "Let the tip of the dropper touch the eyelid",
  "Have the client blink repeatedly right after instillation"],
 ans:0,
 rat:{c:"The conjunctival sac holds the medication and spares the sensitive cornea. The dropper must stay above the eye to avoid contaminating the bottle, and repeated blinking pumps the drug out through the nasolacrimal duct.",
  o:["Correct — into the lower sac, with the client looking up.",
    "Drops on the cornea trigger a blink reflex and are poorly retained.",
    "Contact with the eyelid contaminates the bottle for every later dose.",
    "Blinking expels the medication and reduces absorption."],
  s:"Eye drops go in the lower conjunctival sac; never touch the tip to the eye or lid."},
 ref:"Pharmacology · topical administration technique"},

{id:"PHA-072", t:"single", cn:"PHA", sys:"HEME", topic:"Warfarin reversal", d:2, b:0.2, cj:"recognize", tags:["anticoagulation","bleeding","reversal"],
 stem:"A client on long-term warfarin arrives with active bleeding and an international normalized ratio of 6.8. Which medication does the nurse expect to receive?",
 opts:["Vitamin K and four-factor prothrombin complex concentrate",
  "Protamine sulfate to neutralize the drug",
  "An additional dose of warfarin",
  "Aspirin to reduce clot formation"],
 ans:0,
 rat:{c:"Warfarin blocks vitamin K dependent clotting factors. Vitamin K restores synthesis but takes hours, so four-factor prothrombin complex concentrate supplies the factors immediately when bleeding is active and the ratio is this high.",
  o:["Correct — vitamin K plus factor replacement for active bleeding.",
    "Protamine reverses heparin, not warfarin.",
    "More warfarin would deepen an already dangerous anticoagulation.",
    "Aspirin impairs platelets and would worsen the bleeding."],
  s:"Warfarin reversal: vitamin K, plus prothrombin complex concentrate if bleeding."},
 ref:"Pharmacology · anticoagulant reversal"},

{id:"PHA-073", t:"single", cn:"PHA", sys:"ENDO", topic:"Mixing insulins", d:1, b:-0.8, cj:"act", tags:["insulin","technique","medication-safety"],
 stem:"A nurse is preparing a syringe with both regular and NPH insulin. Which sequence is correct?",
 opts:["Air into NPH, air into regular, then draw the regular insulin first",
  "Draw the cloudy NPH before the clear regular insulin",
  "Mix both vials together before drawing either one",
  "Use a separate syringe and give two injections"],
 ans:0,
 rat:{c:"Regular insulin must stay uncontaminated by the longer-acting suspension, so it is drawn first. Injecting air into the NPH vial first prevents negative pressure and keeps the regular vial free of NPH.",
  o:["Correct — air into NPH, air into regular, draw regular first.",
    "Drawing NPH first carries suspension into the regular vial.",
    "Mixing the vials together ruins both preparations.",
    "Two injections are unnecessary when the insulins are compatible."],
  s:"Clear before cloudy: draw regular insulin before NPH, and never contaminate the regular vial."},
 ref:"Pharmacology · insulin administration"},

/* ── Reduction of Risk Potential (blueprint 12%) ──────────────────── */
{id:"RRP-051", t:"single", cn:"RRP", sys:"REN", topic:"Peritoneal dialysis exchange", d:2, b:0.0, cj:"prioritize", tags:["peritoneal","dialysis","troubleshooting"],
 stem:"During an outpatient peritoneal dialysis exchange, the returning fluid has stopped draining and the client reports abdominal fullness. Which action does the nurse take first?",
 opts:["Reposition the client and check the tubing for kinks",
  "Stop the procedure and remove the catheter",
  "Increase the volume of the next exchange",
  "Administer an antihypertensive and reassess in an hour"],
 ans:0,
 rat:{c:"Poor outflow is usually mechanical: the catheter tip has migrated against the peritoneum or the tubing is kinked. Repositioning and inspecting the line resolves most cases and must be tried before escalating.",
  o:["Correct — reposition and inspect the line first.",
    "Catheter removal is a last resort, not a first response.",
    "A larger volume worsens distention if outflow is obstructed.",
    "An antihypertensive does not address a mechanical outflow problem."],
  s:"Poor dialysate outflow: reposition the client and check for kinks before escalating."},
 ref:"Renal · peritoneal dialysis"},

{id:"RRP-052", t:"single", cn:"RRP", sys:"CV", topic:"Arterial line waveform and zeroing", d:2, b:0.2, cj:"prioritize", tags:["hemodynamic-monitoring","transducer","accuracy"],
 stem:"A client has a radial arterial line. The waveform becomes damped and the readings no longer match the cuff pressure. Which action does the nurse take first?",
 opts:["Flush the system, clear any kink, and re-zero the transducer",
  "Remove the catheter and apply pressure",
  "Document the discrepancy and continue monitoring",
  "Change the transducer to the contralateral arm"],
 ans:0,
 rat:{c:"A damped waveform usually means a clot, kink, or loose connection, and drift means the transducer is no longer level with the phlebostatic axis. Restoring an accurate trace matters because therapy is titrated to these numbers.",
  o:["Correct — restore the waveform and re-zero before trusting the numbers.",
    "Removal is not indicated for a fixable waveform problem.",
    "Documenting leaves the team titrating therapy to false values.",
    "Moving sites discards a working access point unnecessarily."],
  s:"Damped or drifting arterial line: flush, clear kinks, re-zero at the phlebostatic axis."},
 ref:"Cardiovascular · invasive hemodynamic monitoring"},

{id:"RRP-053", t:"single", cn:"RRP", sys:"CV", topic:"Pacemaker generator site assessment", d:2, b:0.1, cj:"analyze", tags:["device","postoperative","complication"],
 stem:"Twenty-four hours after permanent pacemaker insertion, the nurse assesses the surgical site. Which finding requires immediate notification of the provider?",
 opts:["A pocket that is tense, swollen, and rapidly enlarging",
  "Mild tenderness at the incision line",
  "A small amount of dried blood on the dressing",
  "A heart rate matching the programmed lower limit"],
 ans:0,
 rat:{c:"A tense, rapidly enlarging pocket signals active bleeding into the device space, which can compromise the leads, the overlying skin, and the airway if it extends. Mild tenderness and dried blood are expected, and pacing at the lower rate limit shows the device is working.",
  o:["Correct — rapid pocket expansion means bleeding and needs urgent evaluation.",
    "Mild tenderness at a fresh incision is expected.",
    "A small amount of dried blood is a normal postoperative finding.",
    "Pacing at the programmed lower limit confirms the device is functioning."],
  s:"Pacemaker site: a tense, enlarging pocket means bleeding and is reported immediately."},
 ref:"Cardiovascular · cardiac device postoperative care"},

{id:"RRP-054", t:"single", cn:"RRP", sys:"REN", topic:"Continuous bladder irrigation", d:2, b:0.1, cj:"prioritize", tags:["urologic","postoperative","catheter"],
 stem:"A client is receiving continuous bladder irrigation after transurethral resection of the prostate. The outflow becomes bright red and the client reports increasing suprapubic pressure. Which action does the nurse take first?",
 opts:["Increase the irrigation rate and hand-irrigate to clear the catheter",
  "Stop the irrigation and clamp the catheter",
  "Reduce the irrigation rate to slow the bleeding",
  "Give an antispasmodic and reassess in one hour"],
 ans:0,
 rat:{c:"Suprapubic pressure with bright red outflow means clots are obstructing the catheter while fluid keeps entering. Clearing the obstruction restores drainage; clamping or slowing the flow lets the bladder keep distending against a blocked outlet.",
  o:["Correct — restore patency by increasing flow and irrigating by hand.",
    "Clamping traps fluid in an obstructed bladder.",
    "Slowing the irrigation does not clear the clot obstruction.",
    "An antispasmodic treats cramping, not an obstructed catheter."],
  s:"Blocked bladder irrigation: clear the catheter first. Never clamp a distending bladder."},
 ref:"Genitourinary · postoperative urologic care"},

/* ── Safety and Infection Control (blueprint 13%) ─────────────────── */
{id:"SIC-050", t:"single", cn:"SIC", sys:"INF", topic:"Chemotherapy spill management", d:2, b:0.0, cj:"prioritize", tags:["hazardous-drug","spill","ppe"],
 stem:"A bag of intravenous chemotherapy ruptures and spills onto the floor of the medication room. Which action does the nurse take first?",
 opts:["Alert others, restrict access to the area, and use the approved spill kit",
  "Wipe the spill with a paper towel and dispose of it in regular trash",
  "Rinse the area with water and let it air dry",
  "Continue the shift and report the spill at the end of the day"],
 ans:0,
 rat:{c:"Antineoplastic agents are hazardous to anyone who contacts them, so the first step is to protect people by limiting exposure and then contain the spill with the designated kit and personal protective equipment. Improvised cleanup spreads the drug and puts the cleaner at risk.",
  o:["Correct — protect people, restrict the area, use the spill kit.",
    "A paper towel spreads the drug and regular trash is the wrong disposal route.",
    "Rinsing spreads contamination into the drain and the air.",
    "Delaying leaves staff and clients exposed for hours."],
  s:"Hazardous drug spill: limit exposure first, then contain with the spill kit and PPE."},
 ref:"Safety · hazardous drug handling"},

{id:"SIC-051", t:"single", cn:"SIC", sys:"INF", topic:"Radiation implant safety", d:2, b:0.2, cj:"act", tags:["brachytherapy","exposure","safety"],
 stem:"While caring for a client with a sealed internal radiation source, the nurse finds the implant dislodged in the bed linens. Which action does the nurse take?",
 opts:["Use long-handled forceps to place it in the bedside lead container and call the therapist",
  "Pick it up with a gloved hand and return it to the client",
  "Leave it in the linens and send them to laundry",
  "Move the client to another room and wait for the next shift"],
 ans:0,
 rat:{c:"Time, distance, and shielding govern exposure. Long-handled forceps maximize distance, the lead container provides shielding, and the source must never be handled directly or allowed to leave the room in linens.",
  o:["Correct — forceps for distance, lead for shielding, then notify immediately.",
    "A glove offers no protection against ionizing radiation.",
    "Sending the source to laundry exposes the whole laundry chain.",
    "Leaving an unsecured source unattended is unsafe."],
  s:"Dislodged implant: forceps into the lead container, never hands, and never out of the room."},
 ref:"Safety · radiation precautions"},

{id:"SIC-052", t:"single", cn:"SIC", sys:"NEURO", topic:"Magnetic resonance imaging safety screening", d:2, b:-0.2, cj:"recognize", tags:["imaging","screening","device-safety"],
 stem:"A client is scheduled for magnetic resonance imaging. Which finding in the client's history requires the nurse to stop the procedure and notify the imaging team?",
 opts:["A cochlear implant placed two years ago",
  "A prior computed tomography scan with contrast",
  "A history of claustrophobia treated with an oral anxiolytic",
  "A previous allergy to shellfish"],
 ans:0,
 rat:{c:"The scanner's magnetic field can move, heat, or deactivate ferromagnetic implants. A cochlear implant is an absolute screening stop because the magnet can be displaced and the device damaged. Claustrophobia is managed with anxiolytics, and shellfish allergy relates to iodinated contrast, not the magnetic field.",
  o:["Correct — a ferromagnetic implant is an absolute stop for the magnetic field.",
    "A prior contrast scan is unrelated to magnetic field safety.",
    "Claustrophobia is anticipated and managed, not a reason to cancel.",
    "Shellfish allergy concerns iodinated contrast, not this procedure."],
  s:"Screen every client for implants before magnetic resonance imaging; ferromagnetic means stop."},
 ref:"Safety · diagnostic procedure screening"},

/* ── Psychosocial Integrity (blueprint 9%) ────────────────────────── */
{id:"PSY-037", t:"single", cn:"PSY", sys:"PSYCH", topic:"Splitting behavior on the unit", d:2, b:0.1, cj:"generate", tags:["milieu","boundaries","staff-cohesion"],
 stem:"A client tells the evening nurse, 'You are the only one who understands me. The day nurse is useless and cruel.' Which response by the nurse is best?",
 opts:["Set a limit on the comparison and communicate consistently with the rest of the team",
  "Agree that the day nurse handled the situation poorly",
  "Tell the client that such statements are not allowed",
  "Ask the day nurse to explain the approach to the client"],
 ans:0,
 rat:{c:"Splitting pits staff against each other and works only if someone takes the flattering side. The therapeutic response names the limit, refuses the alliance, and keeps the whole team consistent so the client cannot drive a wedge.",
  o:["Correct — decline the split, set the limit, stay consistent with the team.",
    "Agreeing rewards the splitting and undermines a colleague.",
    "Banning the statement is punitive and does not address the behavior.",
    "Having the day nurse defend themselves plays into the split."],
  s:"Splitting: do not take the flattered side. Set limits and keep the team consistent."},
 ref:"Psychosocial · milieu management"},

/* ── Health Promotion and Maintenance (blueprint 9%) ──────────────── */
{id:"HPM-036", t:"single", cn:"HPM", sys:"REPI", topic:"Cervical cancer screening", d:1, b:-0.9, cj:"recognize", tags:["screening","prevention","guideline"],
 stem:"A 32-year-old client with an intact cervix and no history of abnormal results asks how often screening is needed. Which response by the nurse is accurate?",
 opts:["Cytology every three years, or with human papillomavirus testing every five years",
  "Screening is no longer needed after age thirty",
  "Screening every year regardless of prior results",
  "Screening only when symptoms such as bleeding occur"],
 ans:0,
 rat:{c:"For average-risk clients in their thirties, cytology every three years or co-testing every five years is the recommended interval. Annual screening produces unnecessary follow-up procedures, and waiting for symptoms misses the preinvasive disease that screening exists to find.",
  o:["Correct — three-year cytology or five-year co-testing at this age.",
    "Screening continues well beyond age thirty.",
    "Annual screening is not recommended for average-risk clients.",
    "Symptom-triggered testing misses the early lesions screening detects."],
  s:"Cervical screening at this age: cytology every three years, or co-testing every five."},
 ref:"Health promotion · cancer screening intervals"}
);
