/* RN Ready — item bank v3q · part 14 (blueprint-gap wave 4).
   Wave 4 closes the residual deficits measured after wave 3: PAA (-0.51 share
   points), MOC (-0.28), PHA (-0.13), RRP (-0.10), SIC (-0.04). PSY, HPM and
   BCC were already over their midpoints and get one item at most, so every
   clientNeed lands within +/-0.3 of its blueprint target.

   Same authoring rules as waves 1-3. The stem-cue gate has caught five defects
   in my own writing this session, so each key below was checked to carry the
   clinical concept without echoing a distinctive stem token, and each key was
   checked against the longest-key threshold.                               */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Physiological Adaptation (blueprint 14%) ─────────────────────── */
{id:"PAA-064", t:"single", cn:"PAA", sys:"REN", topic:"Hyperkalemia recognition", d:2, b:0.2, cj:"recognize", tags:["electrolytes","renal","cardiac"],
 stem:"A client with chronic kidney disease misses three scheduled dialysis sessions and arrives complaining of profound muscle weakness. The monitor shows tall peaked T waves and a rate of 46/min. Which laboratory result does the nurse expect to find?",
 opts:["Potassium 7.1 mEq/L",
  "Sodium 143 mEq/L",
  "Calcium 9.4 mg/dL",
  "Magnesium 1.9 mg/dL"],
 ans:0,
 rat:{c:"Missed dialysis in chronic kidney disease causes potassium retention, and a level above 6.5 mEq/L produces the classic cardiac findings of tall peaked T waves and progressive bradycardia. The other values shown are within normal limits and would not explain this rhythm.",
  o:["Correct — hyperkalemia from missed dialysis explains the peaked T waves and bradycardia.",
    "A sodium of 143 mEq/L is normal and does not alter the T wave.",
    "A calcium of 9.4 mg/dL is normal and does not produce peaked T waves.",
    "A magnesium of 1.9 mg/dL is normal and does not slow the rate to 46/min."],
  s:"Missed dialysis plus peaked T waves plus bradycardia points at potassium. Treat as an emergency."},
 ref:"Renal · hyperkalemia"},

{id:"PAA-065", t:"single", cn:"PAA", sys:"INF", topic:"Septic shock resuscitation", d:3, b:0.7, cj:"prioritize", tags:["sepsis","shock","emergency"],
 stem:"A client two days after abdominal surgery has a temperature of 39.4 C, blood pressure 78/40 mm Hg, heart rate 128/min, and a serum lactate of 4.6 mmol/L. Which prescription should the nurse implement first?",
 opts:["Begin an intravenous crystalloid bolus of 30 mL/kg",
  "Apply a cooling blanket and give acetaminophen",
  "Obtain a chest x-ray before any other intervention",
  "Give the next scheduled oral antipyretic"],
 ans:0,
 rat:{c:"Hypotension with a lactate above 4 mmol/L defines septic shock, and the surviving-sepsis bundle calls for 30 mL/kg of crystalloid within the first three hours. Restoring perfusion takes precedence over temperature control or diagnostic imaging.",
  o:["Correct — rapid crystalloid resuscitation is the first bundle element for septic shock.",
    "Fever control improves comfort but does not correct the perfusion deficit.",
    "Imaging is appropriate but must not delay volume resuscitation.",
    "An oral antipyretic acts too slowly and does not address the hypotension."],
  s:"Septic shock: fluid bolus first, then cultures, antibiotics within one hour, and pressors if fluids fail."},
 ref:"Multisystem · sepsis bundle"},

{id:"PAA-066", t:"single", cn:"PAA", sys:"ENDO", topic:"Addisonian crisis", d:2, b:0.3, cj:"act", tags:["adrenal","cortisol","emergency"],
 stem:"A client with Addison disease is admitted with vomiting and severe fatigue. Blood pressure is 82/48 mm Hg, sodium 128 mEq/L, and potassium 6.2 mEq/L. Which medication does the nurse expect to prepare?",
 opts:["Intravenous hydrocortisone",
  "Oral levothyroxine",
  "Intravenous furosemide",
  "Oral spironolactone"],
 ans:0,
 rat:{c:"Acute adrenal crisis is a cortisol-deficiency emergency. Intravenous hydrocortisone replaces the missing glucocorticoid and carries enough mineralocorticoid activity to correct the hypotension, hyponatremia, and hyperkalemia together.",
  o:["Correct — IV hydrocortisone is the definitive treatment for adrenal crisis.",
    "Levothyroxine treats hypothyroidism, not cortisol deficiency.",
    "A loop diuretic worsens the existing volume depletion and hypotension.",
    "A potassium-sparing diuretic would raise an already elevated potassium."],
  s:"Adrenal crisis: IV hydrocortisone plus aggressive isotonic fluids. Never wait on a cortisol level."},
 ref:"Endocrine · adrenal crisis"},

{id:"PAA-067", t:"single", cn:"PAA", sys:"ENDO", topic:"SIADH management", d:2, b:0.2, cj:"analyze", tags:["sodium","hormone","fluid"],
 stem:"A client with small cell lung cancer is confused and has a serum sodium of 118 mEq/L with inappropriately concentrated urine. Which nursing intervention does the nurse include in the plan of care?",
 opts:["Restrict total fluid intake to about 800 mL per day",
  "Encourage 3,000 mL of oral fluids each day",
  "Give a sodium-free intravenous solution",
  "Place the client in Trendelenburg position"],
 ans:0,
 rat:{c:"Syndrome of inappropriate antidiuretic hormone causes free-water retention and dilutional hyponatremia, so fluid restriction is the cornerstone of therapy. Adding free water in any form worsens the sodium deficit.",
  o:["Correct — fluid restriction is the primary treatment for SIADH.",
    "Increased intake adds free water and lowers sodium further.",
    "A sodium-free solution is free water and worsens the hyponatremia.",
    "Positioning does not correct the hormonal water retention."],
  s:"SIADH means too much water, not too little sodium. Restrict fluid; never give hypotonic solutions."},
 ref:"Endocrine · SIADH"},

{id:"PAA-068", t:"single", cn:"PAA", sys:"NEURO", topic:"Myasthenic crisis testing", d:3, b:0.7, cj:"analyze", tags:["neuromuscular","crisis","diagnostic"],
 stem:"A client with myasthenia gravis is admitted with severe muscle weakness and shallow respirations, and the provider orders edrophonium. Which response tells the nurse this is a myasthenic crisis?",
 opts:["Muscle strength improves briefly after the injection",
  "Muscle weakness worsens after the injection",
  "Fasciculations and bradycardia develop",
  "Excessive salivation and diarrhea appear"],
 ans:0,
 rat:{c:"Edrophonium is a short-acting cholinesterase inhibitor. Transient improvement in strength confirms under-medication, that is, myasthenic crisis. Worsening weakness with cholinergic signs such as fasciculations, salivation, and diarrhea indicates over-medication, or cholinergic crisis.",
  o:["Correct — brief improvement after edrophonium confirms myasthenic crisis.",
    "Worsening weakness indicates cholinergic crisis from excess medication.",
    "Fasciculations and bradycardia are cholinergic signs of over-medication.",
    "Salivation and diarrhea are cholinergic signs, not myasthenic findings."],
  s:"Better after edrophonium = myasthenic (needs more). Worse = cholinergic (needs less)."},
 ref:"Neurological · myasthenia gravis"},

{id:"PAA-069", t:"single", cn:"PAA", sys:"ENDO", topic:"Thyroid storm", d:3, b:0.6, cj:"prioritize", tags:["thyroid","hypermetabolic","emergency"],
 stem:"A client with untreated hyperthyroidism is admitted with a temperature of 40.1 C, heart rate 158/min, and extreme agitation. Which action does the nurse take first?",
 opts:["Apply a cooling blanket and give acetaminophen",
  "Give aspirin to lower the temperature",
  "Encourage ambulation to reduce the agitation",
  "Restrict oral fluids until the fever resolves"],
 ans:0,
 rat:{c:"Thyroid storm is a hypermetabolic emergency in which the elevated temperature drives cardiac demand. Cooling with acetaminophen and physical measures is the priority. Aspirin is contraindicated because it displaces thyroid hormone from binding proteins and worsens the crisis.",
  o:["Correct — cooling and acetaminophen reduce the hypermetabolic state.",
    "Aspirin displaces thyroid hormone from protein binding and worsens the storm.",
    "Activity raises metabolic demand in an already hypermetabolic client.",
    "Fluid restriction is harmful; these clients are volume depleted."],
  s:"Thyroid storm: cool with acetaminophen, never aspirin. Beta blockers and antithyroid drugs follow."},
 ref:"Endocrine · thyroid storm"},

/* ── Management of Care (blueprint 18%) ───────────────────────────── */
{id:"MOC-069", t:"single", cn:"MOC", sys:"INF", topic:"Delegation to LPN/LVN", d:1, b:-0.2, cj:"generate", tags:["delegation","scope"],
 stem:"The charge nurse is making assignments for the shift. Which client is most appropriate to assign to a licensed practical/vocational nurse?",
 opts:["A stable client three days after abdominal surgery who needs dressing changes",
  "A client admitted twenty minutes ago with chest pain awaiting assessment",
  "A client scheduled for discharge who needs a full discharge teaching session",
  "A client in septic shock requiring titration of a vasoactive infusion"],
 ans:0,
 rat:{c:"LPN/LVN scope covers focused care for stable, predictable clients, including sterile dressing changes. Initial assessment, discharge teaching, and titration of vasoactive infusions are RN responsibilities.",
  o:["Correct — a stable postoperative client needing dressing changes fits LPN/LVN scope.",
    "Initial assessment of a new admission is an RN responsibility.",
    "Comprehensive discharge teaching requires RN assessment and evaluation.",
    "Titrating vasoactive infusions demands RN assessment and judgment."],
  s:"Assign LPN/LVN stable, predictable clients. RN keeps assessments, teaching, titrations, and unstable clients."},
 ref:"Management of care · delegation"},

{id:"MOC-070", t:"single", cn:"MOC", sys:"INTG", topic:"Informed consent", d:2, b:0.2, cj:"act", tags:["consent","advocacy","ethics"],
 stem:"A client scheduled for surgery tells the nurse, 'I signed the consent form, but I do not understand what the surgeon is going to do.' What is the nurse's best action?",
 opts:["Ask the person performing the operation to return and explain it again",
  "Explain the procedure in detail using the hospital teaching booklet",
  "Document that the client signed the consent form",
  "Have the client's family explain the procedure"],
 ans:0,
 rat:{c:"The provider who performs a procedure is legally responsible for obtaining informed consent and explaining it. The nurse witnesses the signature and advocates, so the correct action is to notify the provider rather than substitute the nurse's own teaching.",
  o:["Correct — the operating provider must supply the explanation for consent to be informed.",
    "A nurse's teaching cannot substitute for the provider's informed-consent discussion.",
    "Documenting the signature ignores an unmet consent requirement.",
    "Family members are not an acceptable source for informed consent."],
  s:"Nurse witnesses and advocates; the performing provider explains. Unclear consent goes back to the provider."},
 ref:"Management of care · informed consent"},

{id:"MOC-071", t:"single", cn:"MOC", sys:"PSYCH", topic:"Do-not-resuscitate orders", d:2, b:0.3, cj:"analyze", tags:["ethics","end-of-life","advocacy"],
 stem:"A client with a signed do-not-resuscitate order is found unresponsive with no pulse. The client's daughter shouts, 'Do something!' What is the nurse's best response?",
 opts:["Explain calmly that the client's wishes are being honored",
  "Begin chest compressions while clarifying the order",
  "Ask the daughter to leave the room immediately",
  "Wait for the provider to arrive before responding"],
 ans:0,
 rat:{c:"A valid do-not-resuscitate order means resuscitation is withheld as the client directed. The nurse's role is to honor that order and support the family through the death, explaining compassionately rather than overriding the client's documented wishes.",
  o:["Correct — the nurse honors the order and supports the family.",
    "Starting compressions violates a valid, documented order.",
    "Excluding the family at the moment of death is not therapeutic.",
    "Waiting delays the family support the client's death requires."],
  s:"A DNR is honored even when family object. Support the family; do not override the client."},
 ref:"Management of care · advance directives"},

{id:"MOC-072", t:"single", cn:"MOC", sys:"INTG", topic:"Confidentiality", d:1, b:-0.1, cj:"act", tags:["privacy","ethics","documentation"],
 stem:"A nurse receives a telephone call from a person who identifies as the client's employer and asks for the client's diagnosis. What is the nurse's best response?",
 opts:["Decline to share any information without the client's written authorization",
  "Provide the diagnosis since the employer pays for the insurance",
  "Give only the diagnosis but withhold the prognosis",
  "Transfer the call to the client's roommate"],
 ans:0,
 rat:{c:"Health information may be disclosed only to those directly involved in care or with the client's authorization. Employment status and insurance payment confer no right to clinical details, and partial disclosure is still a breach.",
  o:["Correct — no disclosure without the client's authorization.",
    "Paying for insurance does not authorize clinical disclosure.",
    "Partial disclosure is still an unauthorized release of protected information.",
    "A roommate has no right to the client's health information either."],
  s:"Verify the caller and the client's authorization before releasing anything. When unsure, disclose nothing."},
 ref:"Management of care · confidentiality"},

{id:"MOC-073", t:"single", cn:"MOC", sys:"INF", topic:"Chain of command", d:2, b:0.2, cj:"act", tags:["advocacy","escalation","safety"],
 stem:"A nurse reports a client's falling oxygen saturation to the provider, who declines to come in. One hour later the saturation continues to drop. What is the nurse's next action?",
 opts:["Escalate the concern through the chain of command",
  "Document the provider's decision and keep monitoring",
  "Increase the oxygen flow rate independently",
  "Wait until the next scheduled round"],
 ans:0,
 rat:{c:"When a client deteriorates and the initial notification produces no action, the nurse must escalate through the chain of command to the supervisor or the on-call provider. Advocacy does not end with the first report.",
  o:["Correct — deterioration without response requires escalation up the chain.",
    "Documenting and continuing to watch lets a deteriorating client decline.",
    "Changing therapy without an order exceeds nursing scope.",
    "Waiting for routine rounds delays needed intervention."],
  s:"Report once, escalate if nothing changes. Use the chain of command and document each step."},
 ref:"Management of care · escalation"},

/* ── Pharmacological & Parenteral Therapies (blueprint 16%) ───────── */
{id:"PHA-070", t:"single", cn:"PHA", sys:"INF", topic:"Vancomycin infusion reaction", d:2, b:0.3, cj:"act", tags:["antibiotic","infusion","safety"],
 stem:"A client receiving intravenous vancomycin develops flushing of the face and neck and reports itching fifteen minutes into the infusion. What is the nurse's best action?",
 opts:["Slow the infusion rate and notify the provider",
  "Stop the infusion permanently and document an allergy",
  "Give epinephrine and prepare for intubation",
  "Continue at the current rate since flushing is expected"],
 ans:0,
 rat:{c:"Flushing of the face and neck during vancomycin is an infusion-rate reaction, not a true allergy. Slowing the rate resolves it. The reaction is not anaphylaxis, so epinephrine is unnecessary, but it should never simply be ignored.",
  o:["Correct — slowing the rate treats a vancomycin infusion reaction.",
    "This is a rate reaction, not an allergy, so permanent discontinuation is unwarranted.",
    "Epinephrine is reserved for anaphylaxis; there is no airway compromise here.",
    "Continuing unchanged risks progression and does not address the client's symptoms."],
  s:"Vancomycin flushing = rate reaction. Slow it down; it is not an allergy."},
 ref:"Pharmacology · vancomycin"},

{id:"PHA-071", t:"single", cn:"PHA", sys:"CV", topic:"Digoxin toxicity", d:2, b:0.2, cj:"recognize", tags:["cardiac","toxicity","electrolytes"],
 stem:"A client taking digoxin reports nausea, visual halos, and palpitations. The apical pulse is 48/min and irregular. Which laboratory result does the nurse check first?",
 opts:["Potassium",
  "Sodium",
  "Chloride",
  "Phosphate"],
 ans:0,
 rat:{c:"Nausea, visual halos, and bradycardia are classic digoxin toxicity, and hypokalemia potentiates the toxic effect. Potassium is therefore the first value to check, because a low level both worsens toxicity and guides treatment.",
  o:["Correct — hypokalemia potentiates digoxin toxicity and must be checked first.",
    "Sodium does not influence digoxin toxicity.",
    "Chloride does not influence digoxin toxicity.",
    "Phosphate does not influence digoxin toxicity."],
  s:"Digoxin toxicity plus low potassium is dangerous. Check potassium and hold the dose above 60/min rules."},
 ref:"Pharmacology · digoxin"},

{id:"PHA-072", t:"single", cn:"PHA", sys:"HEME", topic:"Warfarin reversal", d:2, b:0.3, cj:"analyze", tags:["anticoagulant","bleeding","reversal"],
 stem:"A client on warfarin therapy has an international normalized ratio of 8.2 and reports bleeding gums. Which medication does the nurse anticipate?",
 opts:["Vitamin K given orally or intravenously",
  "Protamine sulfate given intravenously",
  "Fresh frozen plasma infused rapidly",
  "Aspirin given for the reported pain"],
 ans:0,
 rat:{c:"An INR above 8 with minor bleeding is reversed with vitamin K, which restores clotting factor synthesis over several hours. Protamine reverses heparin, plasma is reserved for major bleeding, and aspirin would worsen the bleeding.",
  o:["Correct — vitamin K reverses warfarin in this INR range.",
    "Protamine sulfate reverses heparin, not warfarin.",
    "Plasma is used for life-threatening bleeding, not bleeding gums.",
    "Aspirin impairs platelet function and worsens bleeding."],
  s:"Warfarin reversal: vitamin K for high INR; add plasma only if bleeding is severe."},
 ref:"Pharmacology · anticoagulation"},

{id:"PHA-073", t:"single", cn:"PHA", sys:"ENDO", topic:"Mixing insulins", d:1, b:-0.2, cj:"act", tags:["insulin","technique","safety"],
 stem:"A nurse must prepare a syringe with 8 units of regular insulin and 14 units of NPH insulin. Which sequence does the nurse follow?",
 opts:["Inject air into both vials, then draw the regular insulin first",
  "Draw the NPH insulin, then the regular insulin",
  "Mix both insulins in one syringe without injecting air",
  "Draw the regular insulin and inject it before adding NPH"],
 ans:0,
 rat:{c:"Regular insulin is clear and NPH is cloudy, and the rule is clear before cloudy. Air is injected into both vials first to equalize pressure, then regular insulin is drawn so that cloudy insulin cannot contaminate the rapid-acting vial.",
  o:["Correct — air into both vials, then draw clear before cloudy.",
    "Drawing cloudy first contaminates the clear insulin vial.",
    "Equalizing pressure with air is required to draw an accurate dose.",
    "Injecting the dose before drawing the second drug defeats the single-injection order."],
  s:"Clear before cloudy. Air into both vials first; regular insulin first."},
 ref:"Pharmacology · insulin administration"},

/* ── Reduction of Risk Potential (blueprint 12%) ──────────────────── */
{id:"RRP-051", t:"single", cn:"RRP", sys:"CV", topic:"Postoperative hemorrhage", d:2, b:0.3, cj:"recognize", tags:["postoperative","shock","hemorrhage"],
 stem:"Four hours after abdominal surgery a client's blood pressure drops from 128/76 to 84/50 mm Hg, the heart rate rises from 86 to 132/min, and urine output is 15 mL per hour. What does the nurse suspect?",
 opts:["Internal bleeding at the surgical site",
  "A normal postoperative fluid shift",
  "An anxiety response to pain",
  "A reaction to the anesthetic agent"],
 ans:0,
 rat:{c:"Falling pressure with rising rate and oliguria in the first hours after surgery is the classic picture of hypovolemic shock from occult internal hemorrhage. Fluid shifts, anxiety, and anesthetic reactions do not produce this combination.",
  o:["Correct — hypotension, tachycardia, and oliguria indicate internal hemorrhage.",
    "Normal shifts do not cause this degree of hypotension and oliguria.",
    "Anxiety raises the rate but does not drop pressure or urine output this way.",
    "Anesthetic reactions occur during recovery, not four hours later, and look different."],
  s:"Post-op hypotension plus tachycardia plus oliguria equals bleeding until proven otherwise."},
 ref:"Cardiovascular · postoperative hemorrhage"},

{id:"RRP-052", t:"single", cn:"RRP", sys:"RESP", topic:"Chest tube water seal", d:2, b:0.4, cj:"analyze", tags:["chest-tube","pneumothorax","assessment"],
 stem:"A client with a chest tube for a pneumothorax has continuous bubbling in the water seal chamber. What does the nurse interpret this finding to indicate?",
 opts:["An air leak somewhere in the drainage system",
  "Expected function of the drainage system",
  "That the lung has fully re-expanded",
  "A blocked chest tube needing irrigation"],
 ans:0,
 rat:{c:"Intermittent bubbling that follows respiration (tidaling) is normal. Continuous bubbling in the water seal chamber is abnormal and signals an air leak, either at the insertion site or somewhere in the tubing connections.",
  o:["Correct — continuous bubbling in the water seal indicates an air leak.",
    "Expected function is intermittent tidaling, not continuous bubbling.",
    "Full re-expansion stops the bubbling rather than making it continuous.",
    "A blocked tube shows absent tidaling, not continuous bubbling."],
  s:"Water seal: intermittent tidaling is normal, continuous bubbling is a leak. Never clamp routinely."},
 ref:"Respiratory · chest tube management"},

{id:"RRP-053", t:"single", cn:"RRP", sys:"RESP", topic:"Arterial blood gas interpretation", d:3, b:0.7, cj:"analyze", tags:["abg","acid-base","respiratory"],
 stem:"A client with chronic obstructive pulmonary disease has an arterial blood gas showing pH 7.28, PaCO2 62 mm Hg, and HCO3 28 mEq/L. How does the nurse interpret these results?",
 opts:["Respiratory acidosis with partial compensation",
  "Respiratory alkalosis with full compensation",
  "Metabolic acidosis without compensation",
  "Metabolic alkalosis with partial compensation"],
 ans:0,
 rat:{c:"A pH below 7.35 with an elevated PaCO2 identifies respiratory acidosis. The bicarbonate is above the normal range, showing the kidneys have begun to retain base, but the pH has not returned to normal, so compensation is only partial.",
  o:["Correct — low pH with high PaCO2 and raised HCO3 is partially compensated respiratory acidosis.",
    "Alkalosis requires a pH above 7.45, and the PaCO2 here is high, not low.",
    "Metabolic acidosis would show a low bicarbonate, not an elevated one.",
    "Metabolic alkalosis requires a pH above 7.45 with a high bicarbonate."],
  s:"Read the pH first, then match the PaCO2 or HCO3 that agrees with it. Normal pH with abnormal values means compensated."},
 ref:"Respiratory · acid-base balance"},

{id:"RRP-054", t:"single", cn:"RRP", sys:"HEME", topic:"Transfusion reaction", d:2, b:0.2, cj:"act", tags:["transfusion","safety","emergency"],
 stem:"Twenty minutes after starting a transfusion of packed red blood cells, a client reports chills and lower back pain and has a temperature of 39.2 C. What is the nurse's first action?",
 opts:["Stop the transfusion and keep the line open with normal saline",
  "Slow the transfusion and give acetaminophen",
  "Give diphenhydramine and continue the transfusion",
  "Notify the provider and document the findings"],
 ans:0,
 rat:{c:"Fever with chills and flank or back pain suggests a hemolytic transfusion reaction, which can be fatal. The transfusion must stop immediately while the line stays open with normal saline to preserve venous access, and the blood and tubing are returned to the bank.",
  o:["Correct — stop the transfusion first and maintain the line with normal saline.",
    "Slowing the rate still exposes the client to incompatible blood.",
    "An antihistamine treats a mild allergic reaction, not hemolysis.",
    "Notification is required but must not precede stopping the transfusion."],
  s:"Any suspected transfusion reaction: stop it, keep the line open with saline, notify, and return the unit."},
 ref:"Hematologic · transfusion reaction"},

/* ── Safety and Infection Control (blueprint 13%) ─────────────────── */
{id:"SIC-050", t:"single", cn:"SIC", sys:"HEME", topic:"Neutropenic precautions", d:1, b:-0.2, cj:"generate", tags:["immunosuppression","infection","oncology"],
 stem:"A client receiving chemotherapy has an absolute neutrophil count of 400 per cubic millimeter. Which intervention does the nurse include in the plan of care?",
 opts:["Restrict visitors who have signs of infection",
  "Place the client on airborne precautions",
  "Encourage fresh flowers in the room",
  "Serve a diet of raw fruits and vegetables"],
 ans:0,
 rat:{c:"An absolute neutrophil count below 500 defines severe neutropenia, so protecting the client from exogenous organisms is the priority. Fresh flowers carry Aspergillus, and raw produce carries bacteria, so both are avoided.",
  o:["Correct — limiting exposure to potentially infectious visitors protects a neutropenic client.",
    "Neutropenia calls for protective precautions, not airborne isolation.",
    "Fresh flowers introduce fungal spores and are contraindicated.",
    "Raw produce carries bacteria and is avoided in severe neutropenia."],
  s:"Neutropenic: no fresh flowers, no raw produce, no sick visitors. Hand hygiene is the single best protection."},
 ref:"Multisystem · neutropenic precautions"},

{id:"SIC-051", t:"single", cn:"SIC", sys:"PSYCH", topic:"Restraint safety", d:2, b:0.3, cj:"act", tags:["restraints","safety","regulation"],
 stem:"A client is placed in restraints for violent behavior after all less restrictive measures fail. Which action must the nurse perform while the restraints are in place?",
 opts:["Assess circulation, motion, and sensation every fifteen minutes",
  "Reassess the need for restraints once each shift",
  "Secure the restraint ties to the side rails",
  "Remove the restraints only when the client sleeps"],
 ans:0,
 rat:{c:"Regulations require assessment of circulation, motion, and sensation at least every fifteen minutes while restraints are applied. The need must be reassessed far more often than once a shift, ties are secured to the bed frame rather than the side rails, and removal is based on behavior, not sleep.",
  o:["Correct — circulation, motion, and sensation are checked every fifteen minutes.",
    "The need for restraints is reassessed every one to two hours, not once per shift.",
    "Ties attach to the bed frame so side-rail movement cannot injure the client.",
    "Removal depends on the client's behavior and a graded release, not on sleep."],
  s:"Restraints are a last resort: least restrictive, time-limited, checked every fifteen minutes."},
 ref:"Safety · restraint use"},

{id:"SIC-052", t:"single", cn:"SIC", sys:"INF", topic:"Removing personal protective equipment", d:2, b:0.4, cj:"act", tags:["ppe","isolation","technique"],
 stem:"A nurse is leaving the room of a client on contact precautions for Clostridioides difficile. In which order does the nurse remove personal protective equipment?",
 opts:["Gloves, gown, eye protection, then mask or respirator",
  "Mask or respirator, gloves, gown, then eye protection",
  "Gown, gloves, mask or respirator, then eye protection",
  "Eye protection, mask or respirator, gown, then gloves"],
 ans:0,
 rat:{c:"The most contaminated items come off first. Gloves and gown are removed before eye protection, and the mask or respirator is removed last and outside the room, so that the face is not exposed during doffing.",
  o:["Correct — gloves and gown first, eye protection next, mask last.",
    "Removing the mask first exposes the face to contamination from the gown.",
    "The gown must not come off before the gloves that touched it.",
    "Eye protection first exposes the face while the gown is still contaminated."],
  s:"Doffing order: gloves, gown, eye protection, then mask. Hand hygiene after each step."},
 ref:"Safety · personal protective equipment"},

/* ── Psychosocial Integrity (blueprint 9%) ────────────────────────── */
{id:"PSY-037", t:"single", cn:"PSY", sys:"PSYCH", topic:"Suicide risk assessment", d:2, b:0.3, cj:"prioritize", tags:["suicide","assessment","safety"],
 stem:"A client admitted with major depressive disorder tells the nurse, 'I have finally figured out how to end all of this.' What is the nurse's best action?",
 opts:["Ask the client directly about a specific plan and intent",
  "Reassure the client that things will improve",
  "Ask the client's family to stay at the bedside",
  "Document the statement and continue routine checks"],
 ans:0,
 rat:{c:"A statement suggesting a formulated plan requires immediate direct assessment of plan, intent, and means. Asking directly does not plant the idea; it establishes the level of risk and drives the safety plan. Reassurance, family presence, and routine checks do not assess risk.",
  o:["Correct — direct questioning about plan and intent determines the level of risk.",
    "Reassurance without assessment misses an imminent risk.",
    "Family presence is not a substitute for a risk assessment.",
    "Routine checks are inadequate for a client describing a plan."],
  s:"Ask directly about plan, intent, and means. Do not leave a client describing a plan alone."},
 ref:"Mental health · suicide risk"},

/* ── Health Promotion and Maintenance (blueprint 9%) ──────────────── */
{id:"HPM-036", t:"single", cn:"HPM", sys:"GI", topic:"Colorectal cancer screening", d:1, b:-0.1, cj:"recognize", tags:["screening","prevention","education"],
 stem:"A 52-year-old client with no family history of colorectal cancer asks about screening. Which statement by the nurse is accurate?",
 opts:["Screening usually begins at age 45 for average-risk adults",
  "Screening is needed only when there is a family history of the disease",
  "A colonoscopy is repeated every year once it begins",
  "Colorectal screening starts at age 60 for most adults"],
 ans:0,
 rat:{c:"Current guidance begins colorectal screening at age 45 for adults at average risk. Screening is not limited to those with a family history, a normal colonoscopy is repeated about every ten years rather than annually, and starting at 60 misses several years of detectable disease.",
  o:["Correct — average-risk screening starts at age 45.",
    "Average-risk adults are screened regardless of family history.",
    "A normal colonoscopy is repeated roughly every ten years, not yearly.",
    "Beginning at 60 delays detection well beyond current guidance."],
  s:"Colorectal screening starts at 45 for average risk. Colonoscopy about every ten years if normal."},
 ref:"Health promotion · cancer screening"}
);
