"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 44) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 43: MOC (17.9% vs 18),
 * PHA (15.9% vs 16) and PAA (13.8% vs 14). Every item is
 * difficulty 2 or 3, and the clinical detail is written to be
 * defensible.
 *
 * MOC 4: safety briefing, ward huddle, ISBAR communication, and
 * structured handover recommendation.
 * PHA 4: heparin in haemodialysis, citrate-related hypocalcaemia,
 * heparin flush in peritoneal dialysis, and first use syndrome.
 * PAA 7: continuous venovenous haemofiltration, haemodiafiltration,
 * dialysis adequacy and Kt/V, intradialytic hypotension, air
 * embolism, peritoneal dialysis peritonitis, and cloudy effluent.
 * RRP 5: filter clotting, transmembrane pressure rise, blood leak
 * alarm, exit site infection, and inadequate peritoneal drainage.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- MOC 4 */
{id:"MOC-216", t:"single", cn:"MOC", sys:"INTG", topic:"Safety briefing", d:2, b:0.45, cj:"act", tags:["management","safety briefing","teamwork","communication","risk"],
 stem:"A ward is introducing a daily safety briefing at the start of each shift. A nurse questions the value, since risks are already documented. Which interpretation by the nurse is most accurate?",
 opts:["The safety briefing surfaces risks in real time and aligns the whole team, which documentation alone does not achieve","The safety briefing duplicates documented risks and wastes clinical time","The safety briefing is only useful when an incident has already occurred","The safety briefing should be led by the most junior nurse to build confidence"],
 ans:0, rat:{c:"A safety briefing surfaces current risks in real time and aligns the whole team on mitigation, which static documentation cannot achieve. It is not duplicative, is proactive rather than reactive, and is normally led by the coordinator in charge.", s:"Safety briefings are a recognised teamwork intervention; the nurse should understand their proactive purpose."}},
{id:"MOC-217", t:"single", cn:"MOC", sys:"INTG", topic:"Ward huddle", d:2, b:0.45, cj:"act", tags:["management","huddle","teamwork","communication","situational awareness"],
 stem:"A busy ward is experiencing delays because staff are unaware of each other's workload and patient acuity. Which action by the nurse is most appropriate?",
 opts:["Introduce a short structured huddle so the team shares acuity, workload, and immediate risks","Circulate a written workload list including acuity, since this avoids interrupting clinical work","Ask each nurse to raise concerns individually with the coordinator, since this is more private","Hold a monthly meeting, since daily meetings are too disruptive"],
 ans:0, rat:{c:"A short structured huddle allows the team to share acuity, workload, and immediate risks, building shared situational awareness. A written list is not interactive, individual escalation fragments the picture, and a monthly meeting is too infrequent to address daily variation.", s:"Huddles are a brief, high-yield teamwork tool; the nurse should understand how they differ from formal handover."}},
{id:"MOC-218", t:"single", cn:"MOC", sys:"INTG", topic:"ISBAR communication", d:3, b:0.55, cj:"act", tags:["management","ISBAR","communication","escalation","structured"],
 stem:"A nurse needs to escalate a deteriorating client to the medical team urgently. Which action by the nurse is most appropriate?",
 opts:["Use the ISBAR structure to identify self, describe the situation and background, give the assessment, and state the recommendation","Describe the client's history in full, since context prevents misunderstanding","Telephone and ask the doctor to attend without giving details, since this is faster","Send a written message, since this creates a record"],
 ans:0, rat:{c:"ISBAR structures urgent escalation: identify, situation, background, assessment, recommendation. A full history delays critical information, escalating without detail wastes the receiver's time, and a written message is inappropriate for an urgent deterioration.", s:"ISBAR is a validated escalation tool; the nurse must be able to use it under time pressure."}},
{id:"MOC-219", t:"single", cn:"MOC", sys:"INTG", topic:"Structured handover recommendation", d:3, b:0.55, cj:"act", tags:["management","handover","recommendation","communication","safety"],
 stem:"A nurse is handing over a client whose observations have been trending down. Which action by the nurse is most appropriate?",
 opts:["State a clear recommendation, such as the observations frequency required and the threshold for escalation","Summarise the shift events, since the receiving nurse can interpret the trend","Hand over the observations chart, since the numbers speak for themselves","Mention the trend only if the receiving nurse asks, since this avoids causing alarm"],
 ans:0, rat:{c:"An explicit recommendation makes the clinical concern and required action unambiguous, reducing the risk that a downward trend is missed. Summarising events, handing over raw data, or waiting to be asked all leave interpretation to the receiver and increase risk.", s:"A clear recommendation is the most safety-critical part of handover; the nurse must state the concern and the action required."}},

/* ---------------------------------------------------------- PHA 4 */
{id:"PHA-199", t:"single", cn:"PHA", sys:"REN", topic:"Heparin in haemodialysis", d:3, b:0.55, cj:"act", tags:["pharmacology","heparin","haemodialysis","anticoagulation","monitoring"],
 stem:"A client on haemodialysis is at high risk of bleeding following recent surgery. The team wishes to minimise systemic anticoagulation during the session. Which action by the nurse is most appropriate?",
 opts:["Raise the option of reduced or no heparin, or regional citrate anticoagulation, with the team","Administer the standard heparin dose, since dialysis cannot run without anticoagulation","Double the heparin dose, since circuit clotting is the greater risk","Administer heparin but omit the post-dialysis flush"],
 ans:0, rat:{c:"In a client at high bleeding risk, reduced or no heparin, or regional citrate anticoagulation, should be discussed. Dialysis can run with reduced or no systemic anticoagulation. Doubling the dose increases bleeding risk, and omitting only the flush does not address the systemic effect.", s:"Anticoagulation in dialysis must be individualised to bleeding risk; the nurse should advocate for the safest option."}},
{id:"PHA-200", t:"single", cn:"PHA", sys:"REN", topic:"Citrate-related hypocalcaemia", d:3, b:0.55, cj:"recognize", tags:["pharmacology","citrate","hypocalcaemia","anticoagulation","monitoring"],
 stem:"A client receiving continuous renal replacement therapy with regional citrate anticoagulation develops perioral tingling and a prolonged QT interval. Which interpretation by the nurse is most accurate?",
 opts:["These findings suggest citrate-related hypocalcaemia and require urgent calcium measurement and treatment","These findings suggest hypercalcaemia and require withholding calcium","These findings suggest an allergic reaction to the circuit and require stopping therapy","These findings are expected during citrate anticoagulation and require no action"],
 ans:0, rat:{c:"Perioral tingling and QT prolongation indicate hypocalcaemia, a recognised complication of citrate anticoagulation when citrate accumulates. It requires urgent calcium measurement and treatment. It is not hypercalcaemia, allergy, or an expected finding.", s:"Citrate accumulation causes hypocalcaemia; the nurse must monitor ionised calcium and recognise the clinical signs."}},
{id:"PHA-201", t:"single", cn:"PHA", sys:"REN", topic:"Heparin flush in peritoneal dialysis", d:2, b:0.45, cj:"act", tags:["pharmacology","heparin","peritoneal dialysis","catheter","patency"],
 stem:"A client on peritoneal dialysis has fibrin strands visible in the drained effluent and drainage has slowed. Which action by the nurse is most appropriate?",
 opts:["Discuss adding heparin to the dialysate with the team, since this reduces fibrin and improves drainage","Increase the dwell time, since this allows fibrin to dissolve","Flush the catheter with saline forcefully, since this clears the obstruction and restores drainage","Stop peritoneal dialysis, since fibrin indicates catheter failure"],
 ans:0, rat:{c:"Fibrin strands in the effluent can obstruct the catheter, and heparin added to the dialysate reduces fibrin and improves drainage. Increasing dwell time does not dissolve fibrin, forceful flushing risks injury, and fibrin does not indicate catheter failure.", s:"Heparin in peritoneal dialysate is a standard intervention for fibrin; the nurse should recognise the indication."}},
{id:"PHA-202", t:"single", cn:"PHA", sys:"REN", topic:"First use syndrome", d:3, b:0.55, cj:"recognize", tags:["pharmacology","first use syndrome","dialyser","reaction","emergency"],
 stem:"A client develops chest and back pain with breathlessness within minutes of starting a haemodialysis session with a new dialyser. Which interpretation by the nurse is most accurate?",
 opts:["These findings suggest a type A first use reaction, which requires stopping the dialysis immediately and not returning the blood","These findings suggest fluid overload and require increased ultrafiltration","These findings suggest angina and require sublingual glyceryl trinitrate","These findings are expected at the start of dialysis and will settle"],
 ans:0, rat:{c:"A type A first use reaction occurs within minutes of starting dialysis with a new dialyser and can be life-threatening; dialysis must be stopped and the blood discarded rather than returned. It is not fluid overload, angina, or an expected finding.", s:"First use syndrome is a dialysis emergency; the nurse must recognise it and withhold blood return."}},

/* ---------------------------------------------------------- PAA 7 */
{id:"PAA-167", t:"single", cn:"PAA", sys:"REN", topic:"Continuous venovenous haemofiltration", d:3, b:0.55, cj:"analyze", tags:["adaptation","CVVH","continuous renal replacement","haemofiltration","clearance"],
 stem:"A haemodynamically unstable client in the intensive care unit requires renal replacement therapy. The team selects continuous venovenous haemofiltration rather than intermittent haemodialysis. Which interpretation by the nurse is most accurate?",
 opts:["Continuous therapy removes fluid and solute slowly, which is better tolerated in haemodynamic instability","Continuous therapy clears solute faster and is therefore always preferred","Continuous therapy is chosen because it requires no anticoagulation","Continuous therapy is indicated only when the client can tolerate rapid fluid shifts"],
 ans:0, rat:{c:"Continuous venovenous haemofiltration removes fluid and solute gradually, making it better tolerated in haemodynamic instability. Intermittent dialysis clears solute faster. Continuous therapy usually requires anticoagulation and is chosen precisely because the client cannot tolerate rapid shifts.", s:"Understanding why continuous therapy is selected in instability is a core critical care nephrology concept."}},
{id:"PAA-168", t:"single", cn:"PAA", sys:"REN", topic:"Haemodiafiltration", d:3, b:0.55, cj:"analyze", tags:["adaptation","haemodiafiltration","continuous renal replacement","clearance","mechanism"],
 stem:"A client receives continuous haemodiafiltration. The client's relative asks how this differs from haemofiltration alone. Which explanation by the nurse is most accurate?",
 opts:["It combines diffusion and convection, so it clears both small and larger solutes","It uses only diffusion and therefore clears larger solutes more effectively","It uses only convection and therefore clears small solutes more effectively","It is identical to haemofiltration but runs at a lower blood flow"],
 ans:0, rat:{c:"Haemodiafiltration combines diffusion across the membrane with convective solute drag, clearing both small and larger molecules. Haemofiltration alone relies on convection. It is not identical to haemofiltration.", s:"Understanding the clearance mechanisms of each modality informs appropriate modality selection."}},
{id:"PAA-169", t:"single", cn:"PAA", sys:"REN", topic:"Dialysis adequacy and Kt/V", d:3, b:0.55, cj:"evaluate", tags:["adaptation","Kt/V","dialysis adequacy","monitoring","urea"],
 stem:"A client on thrice-weekly haemodialysis has a single-pool Kt/V of 0.9. Which interpretation by the nurse is most accurate?",
 opts:["This is below the commonly targeted minimum and suggests inadequate dialysis requiring review","This confirms adequate dialysis, since any measurable Kt/V indicates clearance","This indicates excessive dialysis and the prescription should be reduced","Kt/V measures fluid removal rather than solute clearance"],
 ans:0, rat:{c:"A single-pool Kt/V of 0.9 is below the commonly targeted minimum of around 1.2 to 1.4 and suggests inadequate dialysis requiring review. Kt/V measures solute clearance, not fluid removal, and does not indicate excessive dialysis.", s:"Kt/V is the standard measure of haemodialysis adequacy; the nurse should understand the target range."}},
{id:"PAA-170", t:"single", cn:"PAA", sys:"REN", topic:"Intradialytic hypotension", d:3, b:0.55, cj:"act", tags:["adaptation","intradialytic hypotension","haemodialysis","complication","emergency"],
 stem:"A client becomes light-headed and hypotensive during haemodialysis, with a large volume already removed. Which action by the nurse is the priority?",
 opts:["Stop ultrafiltration, place the client head-down, and give fluid as prescribed","Continue ultrafiltration at a lower rate, since the target volume must be achieved","Administer an antihypertensive, since blood pressure medication may be contributing","Finish the session early and review at the next session"],
 ans:0, rat:{c:"Intradialytic hypotension requires stopping ultrafiltration, positioning head-down, and giving fluid as prescribed. Continuing ultrafiltration worsens the hypotension. Antihypertensives are usually withheld before dialysis. Finishing early without treating the acute episode leaves the client unsafe.", s:"Intradialytic hypotension is the commonest acute dialysis complication; the nurse must act immediately to restore perfusion."}},
{id:"PAA-171", t:"single", cn:"PAA", sys:"REN", topic:"Air embolism during haemodialysis", d:3, b:0.55, cj:"act", tags:["adaptation","air embolism","haemodialysis","emergency","positioning"],
 stem:"A client on haemodialysis suddenly becomes breathless and coughing after air is noted in the venous line. Which action by the nurse is the priority?",
 opts:["Clamp the venous line, stop the blood pump, and position the client in left lateral Trendelenburg","Increase the blood pump speed to push the air through the venous line","Continue the session and monitor, since small volumes of air are harmless","Administer oxygen and continue ultrafiltration"],
 ans:0, rat:{c:"Suspected air embolism requires clamping the venous line, stopping the pump, and positioning the client left lateral head-down to trap air in the right ventricle. Increasing pump speed delivers more air, small volumes can be fatal in this setting, and continuing the session is unsafe.", s:"Air embolism is a rare but fatal dialysis emergency; the nurse must know the immediate positioning response."}},
{id:"PAA-172", t:"single", cn:"PAA", sys:"REN", topic:"Peritoneal dialysis peritonitis", d:3, b:0.55, cj:"act", tags:["adaptation","peritonitis","peritoneal dialysis","infection","emergency"],
 stem:"A client on peritoneal dialysis presents with abdominal pain and cloudy drained effluent. Which action by the nurse is the priority?",
 opts:["Send the effluent for cell count and culture and arrange urgent medical review for intraperitoneal antibiotics","Reassure the client, since cloudy effluent is common and usually resolves","Increase the dialysate glucose concentration, since this draws out infection","Stop peritoneal dialysis permanently, since the catheter must be removed"],
 ans:0, rat:{c:"Cloudy effluent with abdominal pain indicates peritonitis, requiring urgent effluent cell count, culture, and intraperitoneal antibiotics. It is not a benign finding. Increasing glucose does not treat infection, and catheter removal is reserved for refractory cases.", s:"Peritonitis is the most serious complication of peritoneal dialysis; prompt effluent sampling and antibiotics preserve the catheter."}},
{id:"PAA-173", t:"single", cn:"PAA", sys:"REN", topic:"Cloudy effluent assessment", d:2, b:0.45, cj:"recognize", tags:["adaptation","cloudy effluent","peritoneal dialysis","assessment","differential"],
 stem:"A client on peritoneal dialysis reports that the effluent has become cloudy, but has no abdominal pain and no fever. Which interpretation by the nurse is most accurate?",
 opts:["Cloudy effluent still requires investigation for peritonitis, since infection can present without pain or fever","Cloudy effluent without pain or fever is not significant and requires no action","Cloudy effluent indicates dehydration and requires increased fluid intake","Cloudy effluent indicates that the dwell time was too long"],
 ans:0, rat:{c:"Cloudy effluent requires investigation for peritonitis even in the absence of pain or fever, since presentation can be subtle. It is not insignificant, and is not explained by dehydration or dwell time.", s:"Cloudy effluent is a red flag in peritoneal dialysis; the nurse must investigate regardless of other symptoms."}},

/* ---------------------------------------------------------- RRP 5 */
{id:"RRP-153", t:"single", cn:"RRP", sys:"REN", topic:"Filter clotting", d:3, b:0.55, cj:"act", tags:["risk","filter clotting","continuous renal replacement","monitoring","anticoagulation"],
 stem:"During continuous renal replacement therapy the filter darkens and the transmembrane pressure rises steadily. Which action by the nurse is most appropriate?",
 opts:["Recognise impending filter clotting, review anticoagulation, and prepare to change the circuit","Increase the blood flow, since this will wash the clot through","Stop anticoagulation, since the circuit is already clotted","Reduce the effluent rate to prolong filter life"],
 ans:0, rat:{c:"Darkening of the filter with rising transmembrane pressure indicates impending clotting, requiring review of anticoagulation and preparation to change the circuit. Increasing blood flow does not clear a clotting filter, stopping anticoagulation worsens it, and reducing effluent rate does not address the cause.", s:"Filter clotting is the commonest cause of circuit failure; the nurse must recognise the early pressure and visual signs."}},
{id:"RRP-154", t:"single", cn:"RRP", sys:"REN", topic:"Transmembrane pressure rise", d:3, b:0.55, cj:"analyze", tags:["risk","transmembrane pressure","continuous renal replacement","monitoring","troubleshooting"],
 stem:"The transmembrane pressure on a continuous renal replacement circuit has doubled over four hours while other pressures remain stable. Which interpretation by the nurse is most accurate?",
 opts:["A rising transmembrane pressure indicates increasing filter resistance and predicts filter failure","A rising transmembrane pressure indicates improved clearance","A rising transmembrane pressure indicates venous access stenosis","Transmembrane pressure is not a useful monitoring parameter"],
 ans:0, rat:{c:"A rising transmembrane pressure reflects increasing resistance across the filter membrane and predicts filter failure. It does not indicate improved clearance. Venous stenosis would raise the return pressure, not the transmembrane pressure.", s:"Trending transmembrane pressure allows the nurse to anticipate filter failure and plan circuit change."}},
{id:"RRP-155", t:"single", cn:"RRP", sys:"REN", topic:"Blood leak alarm", d:3, b:0.55, cj:"act", tags:["risk","blood leak","dialysis","alarm","emergency"],
 stem:"A blood leak alarm sounds on a haemodialysis machine. Which action by the nurse is the priority?",
 opts:["Stop the blood pump and assess the circuit for a genuine membrane rupture before deciding whether to return the blood","Silence the alarm and restart the machine, since these alarms are frequently false","Continue dialysis at a lower blood flow, since the alarm may be spurious","Return the blood immediately, since blood loss must be minimised"],
 ans:0, rat:{c:"A blood leak alarm may indicate membrane rupture, so the pump must be stopped and the circuit assessed before any decision on blood return. Silencing and restarting, continuing at lower flow, or returning blood blindly all risk returning contaminated blood to the client.", s:"Blood leak alarms must never be overridden without assessment; membrane rupture contaminates the blood with dialysate."}},
{id:"RRP-156", t:"single", cn:"RRP", sys:"REN", topic:"Exit site infection", d:2, b:0.45, cj:"act", tags:["risk","exit site infection","peritoneal dialysis","infection","assessment"],
 stem:"A client on peritoneal dialysis has redness and purulent discharge at the catheter exit site, without abdominal pain. Which action by the nurse is most appropriate?",
 opts:["Take a swab for culture and start treatment as prescribed, since exit site infection requires prompt management","Apply a dry dressing and review in one week, since the effluent is clear","Remove the catheter, since exit site infection always requires removal","Advise more frequent exchanges, since this flushes the infection out"],
 ans:0, rat:{c:"Exit site infection requires swabbing for culture and prompt treatment to prevent progression to peritonitis. Delayed review allows spread, catheter removal is not routinely required, and increasing exchanges does not treat the infection.", s:"Exit site infection is distinct from peritonitis but can progress to it; early swabbing and treatment are essential."}},
{id:"RRP-157", t:"single", cn:"RRP", sys:"REN", topic:"Inadequate peritoneal drainage", d:3, b:0.55, cj:"act", tags:["risk","inadequate drainage","peritoneal dialysis","catheter","troubleshooting"],
 stem:"A client on peritoneal dialysis drains only 400 mL after a 2000 mL fill. The client has no abdominal pain. Which action by the nurse is most appropriate?",
 opts:["Reposition the client and check for constipation, since both commonly impair drainage","Increase the fill volume, since this will increase the drain volume","Flush the catheter forcefully with saline, since this clears obstruction","Stop peritoneal dialysis, since the catheter has failed"],
 ans:0, rat:{c:"Inadequate drainage is commonly caused by catheter migration or constipation, so repositioning and assessing bowel habit are the first steps. Increasing fill volume worsens discomfort, forceful flushing risks injury, and the catheter has not necessarily failed.", s:"Most inadequate drainage resolves with simple measures; the nurse should assess position and bowel function first."}}

]);
