/* ============================================================================
   bank20.js — hand-authored wave 10: 20 hard items, NCLEX-RN only

   WHY THIS FILE EXISTS
     Measured against the blueprint after wave 9, four categories were under
     their target share: Management of Care 17.2% against 18%, Pharmacological
     Therapies 15.2% against 16%, Reduction of Risk Potential 11.1% against
     12%, and Physiological Adaptation 12.9% against 14%. Those four are also
     60% of the real exam between them. This wave adds 2 MOC, 5 PHA, 6 RRP and
     7 PAA items, every one d>=2 and most at d=3.

   WHAT MAKES THESE HARD (and NCLEX-realistic)
     · monitoring values that read normal while the client is dying — the
       device is the trap, not the physiology
     · presentations where the physical examination is benign and the pain is
       not, and the benign finding is the diagnostic clue rather than reassurance
     · drug decisions where the interaction is absolute rather than a matter of
       dose or monitoring
     · named physical signs that must be localized precisely before they mean
       anything

   AUTHORING RULES OBSERVED
     · no stem token that occurs only in the key option
     · key is not systematically the longest option
     · every rationale explains the key and each distractor, plus a takeaway
   ========================================================================== */
window.NC.BANK.push(
/* ── Reduction of Risk Potential (blueprint 12%) ───────────────────── */
{id:"RRP-063", t:"single", cn:"RRP", sys:"RESP", topic:"Pulse oximetry in carbon monoxide poisoning", d:3, b:0.55, cj:"analyze", tags:["carbon-monoxide","monitoring","oximetry"],
 stem:"A client is brought in after being found unconscious in a closed garage with a running car. Pulse oximetry reads 99% on room air, and the skin is not cyanotic. Which interpretation should guide the nurse's next action?",
 opts:["Pulse oximetry cannot distinguish carboxyhemoglobin from oxyhemoglobin, so the reading is unreliable",
  "The reading confirms adequate oxygenation, so oxygen therapy is not urgent",
  "The reading reflects true saturation because the client is not cyanotic",
  "Cyanosis would appear before the pulse oximetry value fell in this exposure"],
 ans:0,
 rat:{c:"Standard pulse oximetry measures absorbance at two wavelengths and cannot separate carboxyhemoglobin from oxyhemoglobin, so a client with significant carbon monoxide poisoning can read 98 to 100% while tissue oxygen delivery is critically impaired; a co-oximetry carboxyhemoglobin level is required. Absence of cyanosis is expected rather than reassuring, because carboxyhemoglobin is bright red, and the normal reading does not reduce the urgency of high-concentration oxygen.",
  o:["Correct — two-wavelength oximetry reads carboxyhemoglobin as oxygenated hemoglobin.",
   "The reading is an artifact of the device, not evidence of adequate oxygenation.",
   "Carboxyhemoglobin is bright red, so a well-perfused appearance is expected and misleading.",
   "Cyanosis is a late and unreliable sign; it does not precede a falling reading here."],
  s:"Pulse oximetry cannot see carbon monoxide. A normal reading after smoke or exhaust exposure means order co-oximetry, not that the client is oxygenated."},
 ref:"Risk reduction · limitations of pulse oximetry"},

{id:"RRP-064", t:"single", cn:"RRP", sys:"NEURO", topic:"Positional headache after lumbar puncture", d:3, b:0.55, cj:"prioritize", tags:["lumbar-puncture","csf-leak","complication"],
 stem:"A client reports a headache 12 hours after a lumbar puncture that worsens markedly when sitting upright and eases when supine. Which action should the nurse take first?",
 opts:["Place the client flat, increase fluids, and notify the provider of the positional headache",
  "Elevate the head of the bed to 45 degrees to reduce intracranial pressure",
  "Administer the prescribed opioid and reassess the headache in one hour",
  "Request a computed tomography scan before changing the client's position"],
 ans:0,
 rat:{c:"A headache that worsens upright and eases when flat after a lumbar puncture is a positional headache from a persistent cerebrospinal fluid leak, and the first actions are supine positioning, hydration, and notifying the provider; simple analgesia and caffeine are the usual first-line treatment, with an epidural blood patch reserved for refractory cases. Elevating the head is the opposite of what helps, analgesia alone delays treatment of the cause, and imaging is not indicated for a classic positional headache.",
  o:["Correct — flat positioning and hydration treat the leak while the provider is notified.",
   "Head elevation worsens a positional headache by increasing the leak gradient.",
   "Analgesia alone masks the symptom and delays treatment of the underlying leak.",
   "A classic positional headache after lumbar puncture does not require imaging first."],
  s:"Positional headache after a lumbar puncture means a cerebrospinal fluid leak. Lie the client flat, hydrate, and escalate — head elevation makes it worse."},
 ref:"Risk reduction · post-lumbar puncture headache"},

{id:"RRP-065", t:"single", cn:"RRP", sys:"RESP", topic:"Pneumothorax after thoracentesis", d:3, b:0.55, cj:"prioritize", tags:["thoracentesis","pneumothorax","complication"],
 stem:"Thirty minutes after a thoracentesis, a client develops sudden pleuritic chest pain and dyspnea with a respiratory rate of 28. The trachea is midline and breath sounds are absent on the procedure side. Which action should the nurse take first?",
 opts:["Notify the provider immediately, because these findings suggest a pneumothorax",
  "Apply oxygen and reassure the client that pain after the procedure is expected",
  "Reposition the client toward the procedure side and reassess in fifteen minutes",
  "Administer the prescribed analgesic, because splinting explains the findings"],
 ans:0,
 rat:{c:"Pneumothorax is the principal complication of thoracentesis, and sudden pleuritic pain with dyspnea, tachypnea, and absent breath sounds on the procedure side within an hour is the classic presentation; it requires immediate provider notification and a chest radiograph. A midline trachea argues against tension physiology but does not exclude a simple pneumothorax. Oxygen and reassurance, repositioning, and analgesia all treat the appearance while the air leak continues.",
  o:["Correct — this cluster of findings within an hour of the procedure means pneumothorax until proven otherwise.",
   "Expected post-procedure pain does not cause absent breath sounds or a rate of 28.",
   "Repositioning and waiting delay diagnosis of an expanding air leak.",
   "Splinting causes shallow breathing, not absent breath sounds on one side."],
  s:"After thoracentesis, absent breath sounds plus sudden pain and dyspnea means pneumothorax. A midline trachea rules out tension, not pneumothorax."},
 ref:"Risk reduction · thoracentesis complications"},

{id:"RRP-066", t:"single", cn:"RRP", sys:"GI", topic:"Wound evisceration", d:3, b:0.6, cj:"prioritize", tags:["evisceration","postoperative","emergency"],
 stem:"On the fourth postoperative day after abdominal surgery, a client reports a popping sensation while coughing, and the nurse observes a loop of bowel protruding through the open incision. Which action should the nurse take first?",
 opts:["Cover the protruding bowel with sterile saline-moistened gauze and notify the surgeon",
  "Attempt to return the bowel to the abdomen and reinforce the dressing",
  "Apply an abdominal binder over the protruding bowel and place the client supine",
  "Document the finding and continue monitoring during the next round"],
 ans:0,
 rat:{c:"Evisceration is a surgical emergency: the exposed bowel must be kept moist and viable with sterile saline-soaked gauze while the surgeon is notified for immediate return to the operating room. Pushing the bowel back risks perforation, ischemia, and contamination; a binder over exposed bowel compresses it; and documenting without acting allows the bowel to dry and become non-viable. The client is positioned with knees flexed to reduce abdominal tension.",
  o:["Correct — keep the bowel moist and sterile and get the surgeon immediately.",
   "Pushing bowel back risks perforation and contamination; that belongs to the surgeon in theatre.",
   "A binder over exposed bowel compresses and further compromises it.",
   "Evisceration is an emergency; documenting and waiting allows the bowel to dry out."],
  s:"Evisceration: cover with sterile saline gauze, flex the knees, call the surgeon. Never push the bowel back."},
 ref:"Risk reduction · postoperative evisceration"},

{id:"RRP-067", t:"single", cn:"RRP", sys:"REN", topic:"Pseudohyperkalemia from a hemolyzed specimen", d:3, b:0.55, cj:"analyze", tags:["hyperkalemia","laboratory","specimen-integrity"],
 stem:"A routine laboratory report shows a serum potassium of 6.1 mEq/L in a client who is asymptomatic, has a normal electrocardiogram, and is not receiving potassium-sparing medications. Which action should the nurse take first?",
 opts:["Request a repeat specimen, because hemolysis during collection falsely elevates potassium",
  "Administer the prescribed insulin and dextrose to shift potassium intracellularly",
  "Place the client on continuous cardiac monitoring and restrict dietary potassium",
  "Notify the provider that the client has life-threatening hyperkalemia"],
 ans:0,
 rat:{c:"A potassium of 6.1 mEq/L with no symptoms, a normal electrocardiogram, and no pharmacologic explanation is most likely pseudohyperkalemia from hemolysis during venipuncture, which releases intracellular potassium; the correct action is a repeat specimen drawn carefully rather than treating a number. Treating a spurious value exposes the client to insulin and dextrose with a real hypoglycemia risk, and acting as though the value is genuine propagates the error.",
  o:["Correct — an isolated high value with a normal tracing points to a collection artifact.",
   "Insulin and dextrose carry a hypoglycemia risk; treating an unconfirmed value is unsafe.",
   "Monitoring and restriction are reasonable once the value is confirmed, not before.",
   "Declaring life-threatening hyperkalemia on a single discordant value is premature."],
  s:"Treat the client and the electrocardiogram, not the number. A high potassium with a normal tracing gets redrawn before it gets treated."},
 ref:"Risk reduction · specimen integrity and false laboratory values"},

{id:"RRP-068", t:"single", cn:"RRP", sys:"CV", topic:"Orthostatic vital sign interpretation", d:2, b:0.45, cj:"analyze", tags:["orthostatic","perfusion","assessment"],
 stem:"A client reports dizziness on standing. Blood pressure is 138/84 lying, 122/76 sitting, and 104/62 standing, with heart rate rising from 78 to 104. Which interpretation is correct?",
 opts:["These findings indicate orthostatic hypotension from intravascular volume depletion",
  "The change is expected because blood pressure normally falls on standing",
  "The findings indicate a primary cardiac arrhythmia causing the dizziness",
  "The changes are within normal limits because systolic pressure stayed above 90"],
 ans:0,
 rat:{c:"Orthostatic hypotension is defined by a fall of at least 20 mm Hg systolic or 10 mm Hg diastolic within three minutes of standing; here the systolic drop is 34 mm Hg with a compensatory rise in heart rate, the pattern of intravascular volume depletion. A small transient fall is normal, but this magnitude with symptoms is not. The tachycardia is compensatory rather than a primary arrhythmia, and a systolic above 90 does not make a 34 mm Hg drop normal.",
  o:["Correct — a 34 mm Hg systolic drop with compensatory tachycardia indicates volume depletion.",
   "A small transient fall is normal; a 34 mm Hg drop with symptoms is not.",
   "The heart rate rise is the compensatory response, not the primary problem.",
   "The absolute value matters less than the change; 34 mm Hg is abnormal."],
  s:"Orthostatic hypotension is a change of 20 systolic or 10 diastolic on standing with a compensatory heart rate rise. Judge the drop, not the absolute number."},
 ref:"Risk reduction · orthostatic vital sign interpretation"},

/* ── Physiological Adaptation (blueprint 14%) ──────────────────────── */
{id:"PAA-079", t:"single", cn:"PAA", sys:"GI", topic:"Severe acute pancreatitis", d:3, b:0.55, cj:"prioritize", tags:["pancreatitis","cullen-sign","resuscitation"],
 stem:"A client presents with severe epigastric pain radiating to the back, a serum lipase 8 times the upper limit of normal, and bluish discoloration around the umbilicus. Which intervention should the nurse anticipate first?",
 opts:["Nothing by mouth, aggressive intravenous fluids, and analgesia",
  "A clear liquid diet advanced as tolerated once the pain settles",
  "Immediate administration of pancreatic enzyme replacement with meals",
  "Insertion of a nasoenteric tube for early enteral feeding"],
 ans:0,
 rat:{c:"Periumbilical discoloration is Cullen sign, indicating retroperitoneal hemorrhage from severe acute pancreatitis; management rests on bowel rest, aggressive isotonic fluid resuscitation, and analgesia, because third-spacing and hypovolemia drive organ failure. Oral intake stimulates pancreatic secretion and worsens the process, enzyme replacement treats exocrine insufficiency rather than acute inflammation, and early nasoenteric feeding is a later consideration once the client is resuscitated.",
  o:["Correct — bowel rest, fluid resuscitation, and analgesia are the foundation of management.",
   "Oral intake stimulates pancreatic secretion and worsens the inflammation.",
   "Enzyme replacement addresses exocrine insufficiency, not acute inflammation.",
   "Early enteral feeding may follow resuscitation, but it is not the first intervention."],
  s:"Cullen and Grey Turner signs mean severe pancreatitis with hemorrhage. Rest the pancreas, fill the vasculature, and control the pain."},
 ref:"Physiological adaptation · severe acute pancreatitis"},

{id:"PAA-080", t:"single", cn:"PAA", sys:"GI", topic:"Acute mesenteric ischemia", d:3, b:0.6, cj:"analyze", tags:["mesenteric-ischemia","atrial-fibrillation","emergency"],
 stem:"A client with atrial fibrillation presents with sudden, severe, diffuse abdominal pain. On examination the abdomen is soft and non-tender, and the pain appears far greater than the findings suggest. Which interpretation should guide the nurse's actions?",
 opts:["Pain out of proportion to examination findings suggests mesenteric ischemia, an emergency",
  "A soft, non-tender examination rules out an acute abdominal emergency",
  "The presentation is consistent with gastroenteritis and needs supportive care",
  "The findings suggest constipation, and a bowel regimen should be started"],
 ans:0,
 rat:{c:"Severe pain with a benign abdomen in a client with atrial fibrillation is the classic presentation of acute mesenteric ischemia from an embolus; the bowel is ischemic but not yet infarcted, so peritoneal signs are absent while pain is extreme. This is a surgical emergency requiring imaging and vascular intervention, because delay leads to bowel necrosis. A soft abdomen does not exclude catastrophe — it is the defining feature of the early phase.",
  o:["Correct — pain out of proportion to findings in atrial fibrillation is mesenteric ischemia.",
   "A soft abdomen is characteristic of early ischemia, not evidence against it.",
   "Gastroenteritis does not produce sudden severe pain with a benign examination.",
   "Constipation does not explain sudden severe pain in a client with atrial fibrillation."],
  s:"Pain out of proportion to the examination is a red flag, not a reassurance. In atrial fibrillation it means mesenteric ischemia until proven otherwise."},
 ref:"Physiological adaptation · acute mesenteric ischemia"},

{id:"PAA-081", t:"single", cn:"PAA", sys:"REPI", topic:"Placental abruption with fetal compromise", d:3, b:0.6, cj:"prioritize", tags:["abruption","obstetric-emergency","fetal-monitoring"],
 stem:"A client at 32 weeks gestation presents with sudden, constant abdominal pain, a firm and tender uterus, and dark vaginal bleeding. Fetal heart rate shows late decelerations. Which action should the nurse take first?",
 opts:["Initiate continuous fetal monitoring, establish intravenous access, and prepare for delivery",
  "Position the client supine and administer oxygen by nasal cannula",
  "Perform a vaginal examination to assess cervical dilation and bleeding source",
  "Administer a tocolytic to reduce uterine irritability and recheck the fetal rate in an hour"],
 ans:0,
 rat:{c:"Sudden constant pain, a firm tender uterus, dark bleeding, and late decelerations indicate placental abruption with fetal compromise; the priorities are continuous fetal monitoring, large-bore intravenous access with fluid and blood available, and preparation for emergent delivery, because concealed hemorrhage can cause maternal shock and fetal death. Supine positioning worsens aortocaval compression — lateral is correct. Vaginal examination is contraindicated with undiagnosed bleeding until previa is excluded, and a tocolytic is contraindicated here.",
  o:["Correct — monitor, resuscitate, and prepare for delivery in that order.",
   "Supine positioning worsens aortocaval compression; lateral positioning is indicated.",
   "Vaginal examination is contraindicated with undiagnosed bleeding until previa is excluded.",
   "Tocolysis is contraindicated in abruption with a non-reassuring fetal heart rate."],
  s:"Abruption presents with a firm tender uterus and fetal compromise. Monitor, resuscitate, prepare for delivery — no vaginal exam, no tocolytics."},
 ref:"Physiological adaptation · placental abruption"},

{id:"PAA-082", t:"single", cn:"PAA", sys:"REPI", topic:"Testicular torsion", d:3, b:0.6, cj:"prioritize", tags:["torsion","adolescent","time-critical"],
 stem:"A 14-year-old presents with sudden, severe right scrotal pain that began two hours ago, with nausea and a high-riding, transverse testis. Which action should the nurse anticipate?",
 opts:["Immediate surgical consultation, because torsion is a time-critical emergency",
  "Scrotal elevation and ice, with reassessment in four hours",
  "Administration of antibiotics for presumed epididymitis",
  "Scheduled ultrasound for the following morning to confirm the diagnosis"],
 ans:0,
 rat:{c:"Sudden severe scrotal pain with a high-riding transverse testis and nausea in an adolescent is testicular torsion until proven otherwise, and viability falls sharply after about six hours, so immediate surgical consultation takes precedence over imaging. Elevation and ice suit epididymitis rather than torsion, and antibiotics treat an infection this presentation does not suggest. Deferring ultrasound to the following morning guarantees loss of the testis.",
  o:["Correct — torsion is diagnosed and treated surgically; time determines viability.",
   "Elevation and ice suit epididymitis; torsion needs detorsion within hours.",
   "Antibiotics treat epididymitis, which presents more gradually with fever.",
   "Waiting until morning exceeds the viability window and sacrifices the testis."],
  s:"Sudden scrotal pain in an adolescent is torsion until proven otherwise. Call the surgeon first — the viability window is about six hours."},
 ref:"Physiological adaptation · testicular torsion"},

{id:"PAA-083", t:"single", cn:"PAA", sys:"GI", topic:"Murphy sign in acute cholecystitis", d:2, b:0.45, cj:"recognize", tags:["cholecystitis","murphy-sign","assessment"],
 stem:"A client reports severe right upper quadrant pain radiating to the right scapula that began after a fried meal, with fever and pain on inspiration during deep palpation of the right upper quadrant. Which finding does the nurse recognize?",
 opts:["Murphy sign, indicating acute inflammation of the gallbladder",
  "McBurney point tenderness, indicating inflammation of the appendix",
  "Rebound tenderness, indicating generalized peritoneal inflammation",
  "Costovertebral angle tenderness, indicating infection of the kidney"],
 ans:0,
 rat:{c:"Arrest of inspiration during deep right upper quadrant palpation is Murphy sign, and with postprandial pain radiating to the scapula and fever it indicates acute cholecystitis. McBurney point tenderness localizes to the right lower quadrant and indicates appendicitis. Rebound tenderness indicates peritoneal irritation from any cause rather than gallbladder inflammation specifically, and costovertebral angle tenderness is elicited posteriorly and indicates kidney involvement.",
  o:["Correct — inspiratory arrest on right upper quadrant palpation is Murphy sign.",
   "McBurney point is in the right lower quadrant and indicates appendicitis.",
   "Rebound tenderness is nonspecific for peritoneal irritation, not gallbladder disease.",
   "Costovertebral angle tenderness is elicited in the flank and indicates renal involvement."],
  s:"Murphy sign is inspiratory arrest on right upper quadrant palpation. Know where each named sign is elicited and what it localizes."},
 ref:"Physiological adaptation · acute cholecystitis assessment"},

{id:"PAA-084", t:"single", cn:"PAA", sys:"NEURO", topic:"Acute angle-closure glaucoma", d:3, b:0.55, cj:"prioritize", tags:["glaucoma","ophthalmic-emergency","intraocular-pressure"],
 stem:"A client reports sudden severe right eye pain, headache, blurred vision, and nausea that began two hours ago. The right pupil is mid-dilated and fixed, and the eye is red and firm to touch. Which action should the nurse take first?",
 opts:["Notify the provider immediately, because this is an ophthalmic emergency",
  "Instill the prescribed pilocarpine and reassess the pupil in four hours",
  "Apply a cool compress and administer the prescribed antiemetic",
  "Schedule an appointment with the optometrist for the following week"],
 ans:0,
 rat:{c:"Sudden severe eye pain with a fixed mid-dilated pupil, a red firm globe, headache, and nausea is acute angle-closure glaucoma; intraocular pressure rises fast enough to cause permanent optic nerve damage within hours, so immediate ophthalmologic intervention is required. Pilocarpine is part of treatment but is given under ophthalmology direction rather than self-initiated with a four-hour wait, comfort measures do nothing for the pressure, and deferring a week guarantees vision loss.",
  o:["Correct — acute angle closure threatens permanent vision loss within hours.",
   "Pilocarpine is used, but the decision belongs to ophthalmology and cannot wait four hours.",
   "Comfort measures do not lower intraocular pressure.",
   "A week's delay would result in irreversible optic nerve damage."],
  s:"A fixed mid-dilated pupil with a red, firm, painful eye is acute angle closure. Hours matter — escalate to ophthalmology now."},
 ref:"Physiological adaptation · acute angle-closure glaucoma"},

{id:"PAA-085", t:"single", cn:"PAA", sys:"CV", topic:"Compensating hypovolemic shock", d:3, b:0.55, cj:"analyze", tags:["shock","pulse-pressure","perfusion"],
 stem:"A client after a motor vehicle crash has a blood pressure of 96/72, heart rate of 128, respiratory rate of 26, cool clammy skin, and urine output of 15 mL in the last hour. Which interpretation is correct?",
 opts:["Narrow pulse pressure with tachycardia indicates compensating hypovolemic shock",
  "The systolic pressure is adequate, so the client is hemodynamically stable",
  "The findings indicate early septic shock with peripheral vasodilation",
  "The urine output is acceptable because it exceeds 10 mL per hour"],
 ans:0,
 rat:{c:"A pulse pressure of 24 mm Hg with tachycardia, tachypnea, cool clammy skin, and oliguria is compensating hypovolemic shock — systemic vascular resistance is high, so diastolic pressure is maintained while stroke volume falls and systolic pressure has not yet collapsed. Reading a systolic of 96 as adequate misses the narrowed pulse pressure and the perfusion markers. Septic shock presents with warm flushed skin and a wide pulse pressure from vasodilation, and 15 mL per hour is well below the 30 mL per hour threshold.",
  o:["Correct — a 24 mm Hg pulse pressure with tachycardia and oliguria is compensating shock.",
   "Systolic pressure alone conceals shock; pulse pressure and perfusion markers tell the truth.",
   "Septic shock produces warm flushed skin and a wide pulse pressure, not cool clammy skin.",
   "Fifteen millilitres per hour is well below the 30 mL per hour adequacy threshold."],
  s:"Shock hides inside a normal-looking systolic. Check pulse pressure, heart rate, skin, and urine output before calling a client stable."},
 ref:"Physiological adaptation · compensating hypovolemic shock"},

/* ── Pharmacological Therapies (blueprint 16%) ─────────────────────── */
{id:"PHA-088", t:"single", cn:"PHA", sys:"CV", topic:"Nitrate and phosphodiesterase inhibitor interaction", d:3, b:0.6, cj:"act", tags:["nitroglycerin","interaction","contraindication"],
 stem:"A client with angina is prescribed sublingual nitroglycerin. During medication reconciliation the nurse notes the client takes sildenafil. Which action should the nurse take?",
 opts:["Hold the nitroglycerin and notify the provider, because the combination causes profound hypotension",
  "Administer the nitroglycerin as prescribed and monitor blood pressure every five minutes",
  "Administer the nitroglycerin at half the prescribed dose to reduce the interaction",
  "Advise the client to skip the next sildenafil dose and take the nitroglycerin as prescribed"],
 ans:0,
 rat:{c:"Phosphodiesterase-5 inhibitors potentiate the cyclic guanosine monophosphate pathway that nitrates activate, and the combination can produce refractory, life-threatening hypotension; nitrates are contraindicated within 24 hours of sildenafil and within 48 hours of tadalafil. Monitoring cannot rescue a collapse, dose reduction does not remove the interaction, and the client cannot be left to manage the interval unaided — the prescriber must choose a different antianginal.",
  o:["Correct — the combination is contraindicated and requires a different antianginal plan.",
   "Monitoring does not prevent refractory hypotension; the combination must be avoided.",
   "There is no safe reduced dose; the interaction is not manageable by titration.",
   "The client cannot be left to manage a contraindicated combination; the prescriber must decide."],
  s:"Nitrates and phosphodiesterase-5 inhibitors are contraindicated together — 24 hours for sildenafil, 48 for tadalafil. Hold and escalate."},
 ref:"Pharmacological therapies · absolute drug contraindication"},

{id:"PHA-089", t:"single", cn:"PHA", sys:"MSK", topic:"Alendronate administration", d:2, b:0.45, cj:"act", tags:["bisphosphonate","administration","teaching"],
 stem:"A client is starting alendronate for osteoporosis. Which instruction should the nurse include?",
 opts:["Take it with a full glass of plain water on rising and remain upright for 30 minutes",
  "Take it with breakfast and a glass of orange juice to improve absorption",
  "Take it at bedtime with a small snack to reduce gastric irritation",
  "Take it with a calcium supplement to protect the stomach lining"],
 ans:0,
 rat:{c:"Bisphosphonates are poorly absorbed and cause esophageal irritation and ulceration, so the dose must be taken on an empty stomach with a full glass of plain water, followed by remaining upright and taking nothing else for 30 minutes. Food and juice bind the drug and abolish absorption, a bedtime dose with a snack leaves the tablet in contact with the esophagus, and calcium taken at the same time prevents absorption entirely.",
  o:["Correct — plain water, empty stomach, upright for 30 minutes protects absorption and the esophagus.",
   "Juice and food bind the drug and prevent absorption.",
   "A bedtime dose leaves the tablet against the esophageal mucosa and risks ulceration.",
   "Calcium binds the drug; supplements must be separated by at least 30 minutes."],
  s:"Bisphosphonates: plain water, empty stomach, stay upright 30 minutes, nothing else by mouth. Anything else blocks absorption or burns the esophagus."},
 ref:"Pharmacological therapies · bisphosphonate administration"},

{id:"PHA-090", t:"single", cn:"PHA", sys:"HEME", topic:"Febrile neutropenia", d:3, b:0.6, cj:"prioritize", tags:["neutropenia","chemotherapy","sepsis"],
 stem:"A client 9 days after chemotherapy has a temperature of 38.2 °C and an absolute neutrophil count of 300 cells/mm3. Which action should the nurse take first?",
 opts:["Notify the provider immediately, because febrile neutropenia requires prompt empiric antibiotics",
  "Administer the prescribed acetaminophen and recheck the temperature in one hour",
  "Obtain blood cultures and wait for the results before starting any antibiotic",
  "Place the client in protective isolation and defer treatment until the count recovers"],
 ans:0,
 rat:{c:"Fever with an absolute neutrophil count below 500 cells/mm3 is febrile neutropenia, a medical emergency in which the inflammatory response is blunted so fever may be the only sign of overwhelming infection; empiric broad-spectrum antibiotics must begin within an hour of presentation, after cultures are drawn but never delayed for results. Antipyretics mask the fever and delay recognition, waiting for culture results allows sepsis to progress, and isolation reduces exposure but does not treat an established infection.",
  o:["Correct — empiric antibiotics within an hour is the standard for febrile neutropenia.",
   "Acetaminophen masks the fever and delays the antibiotics that determine survival.",
   "Cultures are drawn first, but antibiotics are never delayed for the results.",
   "Isolation prevents exposure; it does not treat the infection already present."],
  s:"Fever plus an absolute neutrophil count below 500 equals febrile neutropenia. Cultures then antibiotics within an hour — never wait for the results."},
 ref:"Pharmacological therapies · chemotherapy nadir complications"},

{id:"PHA-091", t:"single", cn:"PHA", sys:"ENDO", topic:"Metformin and iodinated contrast", d:2, b:0.45, cj:"act", tags:["metformin","contrast","lactic-acidosis"],
 stem:"A client taking metformin is scheduled for a computed tomography scan with iodinated contrast. Which instruction should the nurse anticipate?",
 opts:["Metformin is withheld at the time of the scan and resumed after renal function is rechecked",
  "Metformin continues unchanged, because contrast does not interact with it",
  "Metformin is doubled on the day of the scan to cover the fasting period",
  "Metformin is switched to insulin permanently after any contrast exposure"],
 ans:0,
 rat:{c:"Iodinated contrast can cause acute kidney injury, and metformin accumulating in renal impairment produces lactic acidosis, so metformin is withheld at the time of the study and typically held for 48 hours, resuming only after renal function is confirmed stable. Continuing it leaves the client exposed if contrast nephropathy develops, doubling the dose raises the risk precisely when renal clearance may be falling, and contrast exposure does not create permanent insulin dependence.",
  o:["Correct — hold at the study and resume after renal function is confirmed.",
   "The interaction is real and runs through contrast-induced kidney injury.",
   "Doubling the dose increases lactic acidosis risk when clearance may be falling.",
   "Contrast exposure does not convert a client to permanent insulin therapy."],
  s:"Contrast can injure the kidney, and metformin in renal failure causes lactic acidosis. Hold it at the study and recheck renal function before resuming."},
 ref:"Pharmacological therapies · metformin and contrast media"},

{id:"PHA-092", t:"single", cn:"PHA", sys:"NEURO", topic:"Intravenous phenytoin administration", d:3, b:0.55, cj:"act", tags:["phenytoin","infusion-rate","compatibility"],
 stem:"A client in status epilepticus is prescribed intravenous phenytoin. Which precaution must the nurse observe during administration?",
 opts:["Infuse no faster than 50 mg per minute and monitor for hypotension and dysrhythmia",
  "Administer as a rapid intravenous push to terminate the seizure quickly",
  "Mix the dose in 5% dextrose in water and infuse over thirty minutes",
  "Administer through the same line as a continuous heparin infusion"],
 ans:0,
 rat:{c:"Intravenous phenytoin must be given no faster than 50 mg per minute with cardiac monitoring, because rapid infusion causes hypotension and arrhythmias from the propylene glycol diluent and the drug's sodium channel effects; the line is flushed with normal saline, since dextrose precipitates the drug. Rapid push risks cardiovascular collapse, dextrose causes precipitation, and phenytoin is physically incompatible with many drugs including heparin, so a dedicated saline line is used.",
  o:["Correct — a 50 mg per minute ceiling with cardiac monitoring prevents cardiovascular collapse.",
   "Rapid push risks hypotension and arrhythmia; seizure control does not justify the rate.",
   "Phenytoin precipitates in dextrose; it must be diluted in normal saline.",
   "Phenytoin is incompatible with heparin and many drugs; a dedicated saline line is required."],
  s:"Intravenous phenytoin: no faster than 50 mg per minute, normal saline only, dedicated line, cardiac monitoring. Rate and compatibility are the tested details."},
 ref:"Pharmacological therapies · phenytoin infusion safety"},

/* ── Management of Care (blueprint 18%) ────────────────────────────── */
{id:"MOC-090", t:"single", cn:"MOC", sys:"PSYCH", topic:"Veracity when a client asks about dying", d:3, b:0.6, cj:"act", tags:["veracity","communication","prognosis"],
 stem:"A client with metastatic cancer asks the nurse directly, \"Am I dying?\" The provider has not yet discussed prognosis with the client. Which response by the nurse is most appropriate?",
 opts:["Answer honestly within the nurse's knowledge and clarify what the client wants to know",
  "Reassure the client that everything possible is being done to treat the cancer",
  "Change the subject and focus the conversation on the client's comfort today",
  "Explain that only the provider is permitted to discuss the prognosis"],
 ans:0,
 rat:{c:"Veracity obliges the nurse to answer truthfully, and a direct question deserves a direct, unhedged response; exploring what the client wants to know respects autonomy and lets the client set the depth of the conversation. Deflecting with reassurance, changing the subject, and invoking a rule that only the provider may speak all avoid the question and leave the client alone with it. The nurse does not invent a prognosis, but neither does the nurse withhold what is known.",
  o:["Correct — honest, proportionate truth plus an invitation to say how much they want to know.",
   "Reassurance that dodges the question leaves the client's fear unaddressed.",
   "Changing the subject signals that the question is not permitted.",
   "No rule bars the nurse from an honest conversation; deferring it abandons the client."],
  s:"A direct question deserves a direct answer. Tell the truth at the depth the client wants, then bring the provider in — never deflect."},
 ref:"Management of care · veracity in difficult conversations"},

{id:"MOC-091", t:"single", cn:"MOC", sys:"INF", topic:"Fatigue and refusing an unsafe assignment", d:3, b:0.6, cj:"analyze", tags:["fatigue","assignment","professional-duty"],
 stem:"A nurse on a medical-surgical unit is asked to stay an additional twelve-hour shift because the oncoming nurse called in ill. The nurse has already worked twelve hours and has no childcare. Which response is most appropriate?",
 opts:["Decline the additional shift, because working fatigued creates an unsafe assignment",
  "Accept the additional shift, because refusing would constitute client abandonment",
  "Accept the shift and report the staffing agency to the state board",
  "Accept the shift but limit care to medication administration only"],
 ans:0,
 rat:{c:"Fatigue impairs judgment, attention, and psychomotor performance to a degree comparable with alcohol intoxication, so accepting a second consecutive twelve-hour shift creates a foreseeable risk to clients; declining is the professional and ethical action. Abandonment means leaving an assigned client without notice, not refusing an additional shift. Reporting a staffing agency is a separate matter, and self-limiting care while accepting an unsafe assignment still exposes clients to the nurse's impairment.",
  o:["Correct — declining an unsafe assignment is a professional duty, not abandonment.",
   "Abandonment is leaving an assigned client without notice, not refusing extra hours.",
   "Reporting the agency does not make a fatigued shift safe to work.",
   "Self-limiting tasks does not remove the impairment that endangers clients."],
  s:"Fatigue is a safety hazard. Declining an additional shift is not abandonment — abandonment is leaving an assigned client without notice."},
 ref:"Management of care · fatigue and safe assignment"}
);
