/* ============================================================================
   bank18.js — hand-authored wave 8: 19 hard items, NCLEX-RN only

   WHY THIS FILE EXISTS
     Wave 7 lifted HPM and BCC. Measured against the blueprint, three
     categories were still under their target share: Management of Care
     (16.0% of the bank against an 18% blueprint weight), Pharmacological
     Therapies (15.1% against 16%), and Psychosocial Integrity (8.6%
     against 9%). MOC and PHA are also the two largest single categories on
     the real exam, so under-serving them costs more than any other gap.
     This wave adds 6 MOC, 6 PHA and 7 PSY items, every one d>=2.

   WHAT MAKES THESE HARD (and NCLEX-realistic)
     · scope questions where the tempting answer is "correct action, wrong actor"
     · drug decisions where two catastrophic risks have to be weighed against
       each other rather than one being simply wrong
     · laboratory sets where three of four values are expected findings and
       only one is a threat
     · confidentiality items where the rule has a real exception, and the
       distractors are the unqualified version of the rule

   AUTHORING RULES OBSERVED
     · no stem token that occurs only in the key option
     · key is not systematically the longest option
     · every rationale explains the key and each distractor, plus a takeaway
   ========================================================================== */
window.NC.BANK.push(
/* ── Management of Care (blueprint 18%) ────────────────────────────── */
{id:"MOC-078", t:"single", cn:"MOC", sys:"RESP", topic:"Scope of a do-not-resuscitate order", d:3, b:0.55, cj:"analyze", tags:["advance-directive","dnr","scope"],
 stem:"A client's advance directive states \"do not resuscitate.\" The client is admitted with acute respiratory failure and remains alert with a palpable pulse. Which understanding should guide the nurse's care?",
 opts:["Full respiratory support continues, because the directive addresses arrest only",
  "Respiratory support is withheld, because the directive prohibits life-sustaining treatment",
  "Intubation is withheld until the provider confirms the directive's scope in writing",
  "All treatment is limited to comfort measures until the family clarifies the directive"],
 ans:0,
 rat:{c:"A do-not-resuscitate order addresses cardiopulmonary resuscitation after arrest; it does not restrict treatment given before arrest. A client who is alert with a pulse is not in arrest, so respiratory support, medications, and monitoring continue. Withholding treatment, delaying intubation for written confirmation, or defaulting to comfort measures all mistake the order's scope and abandon a client who is still being actively treated.",
  o:["Correct — a DNR limits resuscitation after arrest, not the care given while the client is stable.",
   "A DNR is not a do-not-treat order; withholding support before arrest is a scope error.",
   "Waiting for written confirmation delays care that the order does not restrict.",
   "Comfort-only care requires a separate decision; a family cannot infer it from a DNR."],
  s:"DNR means no resuscitation after arrest. It does not restrict anything given before arrest, and it is not a do-not-treat order."},
 ref:"Management of care · scope of a DNR order"},

{id:"MOC-079", t:"single", cn:"MOC", sys:"PSYCH", topic:"Restraint order renewal intervals", d:3, b:0.6, cj:"recognize", tags:["restraints","order-renewal","adolescent"],
 stem:"A nurse is caring for a 16-year-old placed in physical restraints for violent behavior under a provider's order. Which timeframe governs renewal of that order?",
 opts:["Every 2 hours, because the client is an adolescent",
  "Every 4 hours, which is the standard for adults",
  "Every 8 hours, regardless of the client's age",
  "Once each shift, when the charge nurse assumes assignment"],
 ans:0,
 rat:{c:"For violent or self-destructive behavior, a restraint order must be renewed every 4 hours for adults 18 and older, every 2 hours for clients aged 9 to 17, and every hour for children under 9. A 16-year-old therefore falls in the 2-hour band. Renewal is a provider responsibility on that schedule rather than a per-shift nursing review, and no 8-hour interval exists.",
  o:["Correct — ages 9 to 17 require renewal every 2 hours.",
   "The 4-hour interval applies to adults 18 and older, not to a 16-year-old.",
   "There is no 8-hour interval in the age-banded schedule.",
   "Renewal is the provider's responsibility on the scheduled interval, not a per-shift nursing task."],
  s:"Restraint renewal is age-banded: under 9 every hour, 9 to 17 every 2 hours, 18 and older every 4 hours. Fix the age first."},
 ref:"Management of care · restraint order renewal by age"},

{id:"MOC-080", t:"single", cn:"MOC", sys:"INF", topic:"Social media and client privacy", d:3, b:0.6, cj:"analyze", tags:["confidentiality","social-media","hipaa"],
 stem:"A nurse posts a photograph of an empty hospital room on a personal social media account, with a caption naming the unit and the client's rare diagnosis. No client identifiers are visible. Which concern is most accurate?",
 opts:["The post breaches confidentiality, because the details given can single out the client",
  "The post is acceptable, because no name or medical record number appears in it",
  "The post is acceptable as long as the client's face is not visible in the image",
  "The post breaches confidentiality only if the client happens to see it"],
 ans:0,
 rat:{c:"Confidentiality is breached when the information disclosed is enough to identify the client to someone who knows the setting, even without a name or record number. A rare diagnosis combined with a named unit narrows the field to one person. Whether the client sees the post, and whether a face is visible, are irrelevant to whether the disclosure occurred.",
  o:["Correct — a rare diagnosis plus a named unit is identifying even with no name attached.",
   "Names and record numbers are not the only identifiers; the combination of details is enough.",
   "A visible face would add an identifier, but its absence does not make the post permissible.",
   "The breach occurs when the information is disclosed, not when the client discovers it."],
  s:"De-identification is about whether the details can single the client out, not about whether a name appears. Rare diagnosis plus location is identifying."},
 ref:"Management of care · social media and confidentiality"},

{id:"MOC-081", t:"single", cn:"MOC", sys:"INTG", topic:"Conflict over non-beneficial treatment", d:3, b:0.6, cj:"prioritize", tags:["ethics","futility","communication"],
 stem:"The family of a client with irreversible multi-organ failure insists that the team continue full aggressive treatment, while the provider has documented that further intervention offers no physiologic benefit. Which action should the nurse take first?",
 opts:["Facilitate a care conference that includes the family, provider, and ethics resources",
  "Continue the current orders, because the family's wishes govern the plan of care",
  "Withhold the interventions the provider has judged non-beneficial and document the reason",
  "Transfer decision-making to the hospital administrator to resolve the conflict"],
 ans:0,
 rat:{c:"When a family and the care team disagree about non-beneficial treatment, the nurse's first action is to create a structured forum for the disagreement: a care conference with the family, the provider, and ethics consultation. Unilateral continuation and unilateral withdrawal both bypass that process, and an administrator is not the body that resolves clinical-ethical conflict.",
  o:["Correct — a conference with ethics resources is the mechanism for resolving the disagreement.",
   "Family wishes carry weight but do not by themselves establish that an intervention is beneficial.",
   "Unilateral withdrawal before the process runs its course is not the nurse's first action.",
   "Administrators manage operations; clinical-ethical conflict goes to the ethics process."],
  s:"Futility conflict is resolved in a structured forum, not unilaterally. Convene the conference and bring ethics in before either side acts alone."},
 ref:"Management of care · futility and ethics consultation"},

{id:"MOC-082", t:"single", cn:"MOC", sys:"PSYCH", topic:"Elopement risk on a voluntary admission", d:3, b:0.55, cj:"prioritize", tags:["elopement","psychiatric","risk-assessment"],
 stem:"A client admitted voluntarily to an inpatient psychiatric unit tells the nurse, \"I am leaving tonight whether anyone likes it or not.\" Which action should the nurse take first?",
 opts:["Assess the client's intent and risk, then notify the provider of the elopement risk",
  "Remind the client that leaving before discharge is against hospital policy",
  "Place the client in seclusion until the provider can evaluate the statement",
  "Ask security to station personnel at the unit exit for the remainder of the shift"],
 ans:0,
 rat:{c:"A statement about leaving raises two questions at once — whether the client has capacity to leave voluntarily and whether there is risk of harm — and both are answered by assessment, after which the provider must be notified so an involuntary hold can be considered. Policy reminders assess nothing, seclusion requires an order and a clinical indication rather than a statement, and posting security escalates restriction before risk has been established.",
  o:["Correct — assess intent and risk first, then escalate so a hold decision can be made.",
   "Citing policy neither assesses risk nor addresses why the client wants to leave.",
   "Seclusion requires a provider order and a clinical indication; a statement alone does not meet it.",
   "Security at the exit escalates restriction before risk has been established."],
  s:"A threat to leave is a risk-assessment trigger, not a security problem. Assess, then notify, so the hold decision rests on findings."},
 ref:"Management of care · elopement risk assessment"},

{id:"MOC-083", t:"single", cn:"MOC", sys:"INF", topic:"Nursing student medication scope", d:2, b:0.45, cj:"analyze", tags:["scope","student","medication-safety"],
 stem:"A nursing student asks to administer an intravenous push opioid to a postoperative client while the instructor is in the medication room. Which response by the preceptor nurse is appropriate?",
 opts:["Intravenous push medications are outside student scope, so the nurse gives the dose",
  "The student may give the intravenous dose once the instructor returns to the room",
  "The student may give the dose, because medication administration is within student scope",
  "The student may give the dose if the client's pain score is documented beforehand"],
 ans:0,
 rat:{c:"Nursing students may administer medications only within the limits set by the program and the facility, and high-risk routes such as intravenous push, blood administration, and chemotherapy are excluded. Instructor presence is necessary but not sufficient — the route itself is outside student scope. Pain documentation does not expand scope, and supervision does not convert a prohibited task into an allowed one.",
  o:["Correct — intravenous push stays outside student scope regardless of supervision.",
   "Instructor presence is required but does not make a prohibited route permissible.",
   "Student scope excludes high-risk routes even where oral administration is allowed.",
   "Documenting a pain score is good practice but does not change what the student may administer."],
  s:"Scope is set by the route and the risk, not by who is standing in the room. High-risk routes stay with the licensed nurse."},
 ref:"Management of care · student scope of practice"},

/* ── Pharmacological Therapies (blueprint 16%) ─────────────────────── */
{id:"PHA-082", t:"single", cn:"PHA", sys:"NEURO", topic:"Alteplase contraindication in ischemic stroke", d:3, b:0.55, cj:"analyze", tags:["stroke","thrombolysis","contraindication"],
 stem:"A client arrives 90 minutes after sudden onset of right-sided weakness and expressive aphasia. Computed tomography shows no hemorrhage. Which finding would contraindicate administration of alteplase?",
 opts:["Systolic blood pressure of 192 mm Hg that has not responded to treatment",
  "A National Institutes of Health Stroke Scale score of 14",
  "Onset of symptoms 90 minutes before arrival",
  "A history of hypertension managed with a daily thiazide diuretic"],
 ans:0,
 rat:{c:"Alteplase is contraindicated when blood pressure cannot be brought below 185/110 mm Hg, because thrombolysis at higher pressures carries an unacceptable risk of intracranial hemorrhage; the pressure must be treated and rechecked first. A moderate-to-severe stroke scale score is the reason to treat rather than to withhold, the 90-minute onset sits well inside the treatment window, and controlled chronic hypertension is not a contraindication.",
  o:["Correct — uncontrolled blood pressure above 185/110 mm Hg must be corrected before thrombolysis.",
   "A disabling deficit is the indication for treatment, not a reason to withhold it.",
   "Ninety minutes is well within the window, which is measured in hours.",
   "Managed chronic hypertension does not exclude a client from thrombolysis."],
  s:"Before alteplase, the number that stops you is blood pressure, not stroke severity. Treat the pressure below 185/110, then reassess eligibility."},
 ref:"Pharmacological therapies · thrombolysis eligibility"},

{id:"PHA-083", t:"single", cn:"PHA", sys:"RESP", topic:"Amiodarone pulmonary toxicity", d:3, b:0.55, cj:"prioritize", tags:["antiarrhythmic","pulmonary-toxicity","monitoring"],
 stem:"A client has taken amiodarone for 14 months for atrial fibrillation. Which reported symptom requires the most urgent evaluation?",
 opts:["Progressive shortness of breath with a dry cough over three weeks",
  "A bluish-gray discoloration of the skin on the face and neck",
  "Increased sensitivity to sunlight requiring protective clothing",
  "A metallic taste and mild nausea after the morning dose"],
 ans:0,
 rat:{c:"Amiodarone pulmonary toxicity can be fatal and presents subacutely with progressive dyspnea and a nonproductive cough, so it demands immediate evaluation including imaging and pulmonary function testing. Skin discoloration and photosensitivity are recognized but benign effects managed with sun protection, and metallic taste with nausea is a transient gastrointestinal effect; none of them threatens oxygenation.",
  o:["Correct — progressive dyspnea with a dry cough signals the life-threatening effect.",
   "Blue-gray skin discoloration is cosmetically significant but not dangerous.",
   "Photosensitivity is expected and managed with protective clothing and sunscreen.",
   "Metallic taste and mild nausea are transient and self-limiting."],
  s:"With amiodarone, rank adverse effects by organ threat. Lung toxicity kills; skin and taste changes do not. New dyspnea means imaging now."},
 ref:"Pharmacological therapies · amiodarone toxicity surveillance"},

{id:"PHA-084", t:"single", cn:"PHA", sys:"REN", topic:"Tacrolimus nephrotoxicity", d:3, b:0.55, cj:"prioritize", tags:["immunosuppressant","nephrotoxicity","transplant"],
 stem:"A client is 5 days post kidney transplant and is taking tacrolimus. Which laboratory result should the nurse report to the provider first?",
 opts:["Serum creatinine rising from 1.1 to 2.4 mg/dL over two days",
  "Blood glucose of 148 mg/dL measured before the morning meal",
  "Serum potassium of 5.3 mEq/L on the morning laboratory draw",
  "Hemoglobin of 10.2 g/dL two days after the transplant"],
 ans:0,
 rat:{c:"Tacrolimus is directly nephrotoxic, and a creatinine that has more than doubled in two days signals acute kidney injury in the grafted organ, which requires prompt level checking and dose adjustment to prevent irreversible loss. Mild hyperglycemia and mild hyperkalemia are recognized calcineurin inhibitor effects that are monitored and managed, and a modest anemia is expected shortly after transplant.",
  o:["Correct — a doubling creatinine in a fresh graft is acute injury and is the priority.",
   "Mild hyperglycemia is an expected calcineurin inhibitor effect, not an urgent report.",
   "Potassium of 5.3 mEq/L is a mild, expected elevation that is monitored rather than urgent.",
   "A hemoglobin of 10.2 g/dL is an expected post-transplant finding."],
  s:"Rank tacrolimus labs by threat to the graft. A doubling creatinine is acute injury; mild glucose, potassium, and hemoglobin changes are expected."},
 ref:"Pharmacological therapies · calcineurin inhibitor monitoring"},

{id:"PHA-085", t:"single", cn:"PHA", sys:"CV", topic:"Antiplatelet therapy before elective surgery", d:3, b:0.6, cj:"analyze", tags:["antiplatelet","perioperative","risk-balance"],
 stem:"A client taking clopidogrel after coronary stent placement is scheduled for elective spinal surgery in 5 days. Which decision should the nurse anticipate?",
 opts:["The surgeon and the cardiologist decide together whether clopidogrel is held",
  "Clopidogrel is stopped 24 hours before surgery to reduce bleeding risk",
  "Clopidogrel continues through surgery, because stent thrombosis risk outweighs bleeding",
  "Clopidogrel is replaced with aspirin 48 hours before surgery"],
 ans:0,
 rat:{c:"Stopping clopidogrel after a coronary stent risks stent thrombosis, which is frequently fatal, while continuing it through spinal surgery risks epidural hematoma; the decision weighs the stent's age and type against the procedure's bleeding risk and belongs to the surgeon and cardiologist together. A fixed 24-hour stop is too short for platelet function to recover, and substituting aspirin does not remove the antiplatelet effect that drives the bleeding risk.",
  o:["Correct — this is a shared decision balancing stent thrombosis against surgical bleeding.",
   "Platelet function takes roughly 5 to 7 days to recover, so 24 hours is insufficient.",
   "Continuing through spinal surgery carries epidural hematoma risk that must be weighed, not assumed away.",
   "Aspirin is also an antiplatelet agent and does not eliminate the bleeding risk."],
  s:"Antiplatelet therapy around a recent stent is never a fixed rule. It is a joint surgeon-cardiologist judgment about two competing catastrophic risks."},
 ref:"Pharmacological therapies · perioperative antiplatelet decisions"},

{id:"PHA-086", t:"single", cn:"PHA", sys:"REN", topic:"Epoetin alfa hold parameter", d:2, b:0.45, cj:"act", tags:["anemia","erythropoiesis","hypertension"],
 stem:"A client with chronic kidney disease receives epoetin alfa weekly. Which finding should cause the nurse to withhold the dose and notify the provider?",
 opts:["Blood pressure of 178/102 mm Hg",
  "Hemoglobin of 9.4 g/dL",
  "Reported fatigue between treatments",
  "Serum ferritin of 180 ng/mL"],
 ans:0,
 rat:{c:"Epoetin alfa can cause or worsen hypertension, and uncontrolled blood pressure is a reason to hold the dose because of the added risk of hypertensive encephalopathy and seizure. A hemoglobin of 9.4 g/dL is below the treatment target rather than above it, fatigue between doses is the symptom the drug exists to treat, and a ferritin of 180 ng/mL indicates adequate iron stores for erythropoiesis.",
  o:["Correct — uncontrolled hypertension is a hold parameter for erythropoiesis-stimulating agents.",
   "A hemoglobin of 9.4 g/dL is the indication for treatment, not a reason to stop it.",
   "Fatigue is the target symptom; withholding would leave it untreated.",
   "Adequate ferritin means iron stores support the drug's effect."],
  s:"Hold parameters are about harm, not about whether the drug is working. For epoetin alfa, blood pressure is the number that stops the dose."},
 ref:"Pharmacological therapies · erythropoiesis-stimulating agent safety"},

{id:"PHA-087", t:"single", cn:"PHA", sys:"PSYCH", topic:"Lithium and thiazide interaction", d:3, b:0.6, cj:"analyze", tags:["lithium","drug-interaction","toxicity"],
 stem:"A client taking lithium for bipolar disorder is prescribed hydrochlorothiazide for new hypertension. Which outcome should the nurse anticipate?",
 opts:["Lithium levels may rise, because reduced sodium promotes lithium retention",
  "Lithium levels may fall, because thiazides increase renal lithium clearance",
  "No interaction occurs, because the two drugs act on different systems",
  "Lithium levels stay stable, but potassium supplementation becomes necessary"],
 ans:0,
 rat:{c:"The kidney handles lithium in parallel with sodium, so the sodium loss caused by a thiazide leads the kidney to retain lithium and raises serum levels toward toxicity. Thiazides reduce rather than increase lithium clearance, the interaction is well documented rather than absent, and although potassium may need attention, the clinically urgent consequence is the rise in lithium level.",
  o:["Correct — thiazide-induced sodium loss drives lithium retention and toxicity risk.",
   "Thiazides reduce lithium clearance; they do not increase it.",
   "The interaction is well documented and clinically significant.",
   "Potassium may matter, but the urgent risk is the rising lithium level."],
  s:"Lithium follows sodium. Any cause of sodium loss — thiazides, a low-sodium diet, sweating, vomiting — pushes lithium toward toxicity."},
 ref:"Pharmacological therapies · lithium drug interactions"},

/* ── Psychosocial Integrity (blueprint 9%) ─────────────────────────── */
{id:"PSY-042", t:"single", cn:"PSY", sys:"PSYCH", topic:"Duty to warn an identifiable third party", d:3, b:0.6, cj:"act", tags:["duty-to-warn","confidentiality","violence-risk"],
 stem:"A client in an outpatient mental health clinic tells the nurse, \"When I leave here I am going to kill my neighbor, and I know exactly where she works.\" The client names the neighbor and describes a plan. Which action should the nurse take?",
 opts:["Warn the identified person and notify the authorities, in addition to notifying the provider",
  "Maintain confidentiality, because disclosure requires the client's written consent",
  "Document the statement and address it at the next scheduled treatment session",
  "Ask the client to sign a no-harm contract before the session ends"],
 ans:0,
 rat:{c:"Confidentiality yields when a client makes a credible threat against an identifiable person: the nurse must warn the intended victim, notify law enforcement, and notify the provider so the level of care can change. Written consent is not required for this disclosure, deferring to a future session leaves an imminent threat unaddressed, and a no-harm contract does not discharge the duty to protect a third party.",
  o:["Correct — an identifiable target and a plan trigger the duty to warn and protect.",
   "Consent is not required when disclosure prevents harm to an identified third party.",
   "An imminent threat cannot wait for the next session.",
   "A no-harm contract does not substitute for warning the person at risk."],
  s:"Confidentiality has an exception, not a general waiver, when there is an identifiable victim and a credible plan. Warn the person, notify authorities, notify the provider."},
 ref:"Psychosocial integrity · duty to warn and protect"},

{id:"PSY-043", t:"single", cn:"PSY", sys:"GI", topic:"Refeeding syndrome", d:3, b:0.55, cj:"prioritize", tags:["eating-disorder","refeeding","electrolytes"],
 stem:"A client with anorexia nervosa has a body mass index of 13.8 and is beginning nutritional rehabilitation. Which laboratory trend in the first 72 hours requires the most urgent response?",
 opts:["Serum phosphorus falling to 1.6 mg/dL",
  "Serum sodium of 139 mEq/L",
  "Blood glucose of 104 mg/dL",
  "Hemoglobin of 12.1 g/dL"],
 ans:0,
 rat:{c:"Refeeding syndrome follows the insulin surge that accompanies carbohydrate reintroduction, driving phosphorus, potassium, and magnesium into cells; hypophosphatemia is the hallmark and can cause respiratory failure, arrhythmia, and seizure, so a phosphorus of 1.6 mg/dL requires immediate replacement and often a reduction in caloric advancement. The sodium, glucose, and hemoglobin values here are unremarkable and are not part of this mechanism.",
  o:["Correct — hypophosphatemia is the hallmark of refeeding syndrome and is an emergency.",
   "A sodium of 139 mEq/L is within the normal range.",
   "A glucose of 104 mg/dL is expected once feeding restarts.",
   "A hemoglobin of 12.1 g/dL is unremarkable and unrelated to refeeding."],
  s:"In refeeding, watch phosphorus, potassium, and magnesium in the first 72 hours. Falling phosphorus means replace it and slow the calories."},
 ref:"Psychosocial integrity · refeeding syndrome surveillance"},

{id:"PSY-044", t:"single", cn:"PSY", sys:"PSYCH", topic:"Non-suicidal self-injury in an adolescent", d:3, b:0.55, cj:"analyze", tags:["self-injury","adolescent","coping"],
 stem:"A 15-year-old is admitted after superficial cutting of the forearms and says, \"It is the only way I can stop feeling so overwhelmed. I was not trying to die.\" Which response by the nurse is most appropriate?",
 opts:["Acknowledge the function the behavior serves and teach an alternative coping skill",
  "Explain that self-injury is a suicide attempt and requires constant observation",
  "Ask the adolescent to promise not to cut again while hospitalized",
  "Remove all sharp objects and avoid discussing the behavior directly"],
 ans:0,
 rat:{c:"Non-suicidal self-injury commonly functions as a way to regulate overwhelming affect, and the effective nursing response names that function without condemnation and substitutes a skill the adolescent can use instead. Reclassifying it as a suicide attempt is inaccurate and damages trust, a promise not to repeat the behavior is not a treatment and does not reduce risk, and avoiding the topic leaves the function unaddressed while restricting objects.",
  o:["Correct — validating the function and teaching a replacement skill is the therapeutic move.",
   "Non-suicidal self-injury is not automatically a suicide attempt; the distinction guides care.",
   "A promise not to cut is not an intervention and does not lower risk.",
   "Removing objects without discussing the behavior treats the means but not the function."],
  s:"Ask what the behavior does for the client. Non-suicidal self-injury usually regulates affect, and the response is a replacement skill, not shame or silence."},
 ref:"Psychosocial integrity · non-suicidal self-injury"},

{id:"PSY-045", t:"single", cn:"PSY", sys:"INF", topic:"Medical child abuse reporting", d:3, b:0.6, cj:"act", tags:["child-abuse","mandatory-reporting","safeguarding"],
 stem:"A toddler is admitted for the fourth time this year with unexplained apnea. Each episode resolves when the child is separated from the mother, and the recorded episodes occur only when the mother is present at the bedside. Which action should the nurse take?",
 opts:["Document the pattern objectively and report the suspicion of medical child abuse",
  "Reassure the mother that the episodes are likely to resolve with time",
  "Request continuous cardiorespiratory monitoring to capture an episode",
  "Suggest that the mother rest at home while the child is hospitalized"],
 ans:0,
 rat:{c:"Episodes that occur only in one caregiver's presence and resolve on separation are a recognized pattern of medical child abuse, and the nurse has a mandatory duty to report the suspicion. The report must be objective, describing the observed pattern rather than stating a conclusion. Reassurance minimizes a safeguarding concern, monitoring alone does not discharge the reporting duty, and suggesting rest removes the caregiver without protecting the child or documenting the concern.",
  o:["Correct — report the objective pattern; the duty to report does not require proof.",
   "Reassurance ignores a safeguarding pattern that requires a report.",
   "Monitoring may add information but does not discharge the mandatory reporting duty.",
   "Sending the caregiver home neither protects the child nor documents the concern."],
  s:"Safeguarding suspicions are reported on pattern, not on proof. Document what was observed objectively and make the report."},
 ref:"Psychosocial integrity · factitious disorder imposed on another"},

{id:"PSY-046", t:"single", cn:"PSY", sys:"PSYCH", topic:"Ritual reduction in obsessive-compulsive disorder", d:2, b:0.45, cj:"act", tags:["ocd","rituals","behavioral"],
 stem:"A client with obsessive-compulsive disorder spends 40 minutes washing hands before each meal and becomes visibly distressed when the routine is shortened. Which nursing approach is most appropriate during admission?",
 opts:["Allow the routine initially, then shorten it gradually while teaching anxiety-management skills",
  "Stop the routine immediately, because reinforcement maintains the behavior",
  "Permit the routine without limit, because preventing it causes harm",
  "Administer the prescribed anxiolytic 30 minutes before each meal instead of changing the routine"],
 ans:0,
 rat:{c:"Abruptly blocking rituals produces a sharp rise in anxiety and damages the therapeutic relationship, so the accepted nursing approach is to permit the ritual at first and reduce it in negotiated steps while building alternative anxiety-management skills. Unlimited permission entrenches the ritual and the time it consumes, and substituting medication for a behavioral plan leaves the ritual unchanged.",
  o:["Correct — graduated reduction with skill-building respects the anxiety behind the ritual.",
   "Abrupt prevention spikes anxiety and undermines trust early in admission.",
   "Unlimited permission entrenches the ritual and the time it consumes.",
   "Medication may be part of the plan but does not replace graduated behavioral change."],
  s:"Rituals are reduced in steps, not stopped at once. Permit, then negotiate shorter, while teaching another way to manage the anxiety."},
 ref:"Psychosocial integrity · managing compulsive rituals"},

{id:"PSY-047", t:"single", cn:"PSY", sys:"PSYCH", topic:"Disulfiram client teaching", d:2, b:0.4, cj:"analyze", tags:["substance-use","disulfiram","teaching"],
 stem:"A client starting disulfiram for alcohol use disorder asks what will happen if alcohol is consumed. Which statement by the nurse is accurate?",
 opts:["Even small amounts, including those in cough syrup, can cause a severe reaction",
  "The reaction occurs only with distilled spirits and not with wine or beer",
  "The medication prevents the craving for alcohol rather than causing a reaction",
  "The reaction ends within minutes, so no medical attention is needed"],
 ans:0,
 rat:{c:"Disulfiram inhibits aldehyde dehydrogenase, so any alcohol produces acetaldehyde accumulation with flushing, throbbing headache, nausea, vomiting, chest pain, and hypotension; the amount required is small, and hidden sources such as cough syrup, mouthwash, sauces, and vinegars must be avoided. Beer and wine trigger the reaction like spirits, the drug is an aversive deterrent rather than an anti-craving agent, and the reaction can be severe and prolonged enough to require emergency care.",
  o:["Correct — hidden alcohol in cough syrup and similar products is enough to trigger the reaction.",
   "Any form of alcohol triggers the reaction; the type of beverage does not matter.",
   "Disulfiram is an aversive deterrent, not an anti-craving medication such as naltrexone.",
   "Reactions can be severe and prolonged and may require emergency treatment."],
  s:"With disulfiram, teach hidden alcohol: cough syrup, mouthwash, sauces, vinegars. Small amounts trigger a reaction that can need emergency care."},
 ref:"Psychosocial integrity · aversive pharmacotherapy teaching"},

{id:"PSY-048", t:"single", cn:"PSY", sys:"PSYCH", topic:"Delirium superimposed on dementia", d:3, b:0.6, cj:"analyze", tags:["delirium","dementia","acute-change"],
 stem:"A client with moderate dementia, previously calm and oriented to person, becomes agitated and disoriented over 6 hours and is seen picking at the air. Which interpretation should guide the nurse's plan?",
 opts:["This is an acute medical change requiring investigation of a physical cause",
  "This is expected progression of the underlying dementia and needs no workup",
  "This is sundowning and is managed by reorientation and a night light",
  "This is a behavioral symptom best managed with a prescribed antipsychotic"],
 ans:0,
 rat:{c:"An abrupt change in attention and awareness over hours in a client with dementia indicates delirium superimposed on dementia until proven otherwise, and the priority is finding the physical trigger — infection, hypoxia, dehydration, medication effect, pain, or metabolic derangement. Attributing it to progression, to sundowning, or to behavior all defer that search, and an antipsychotic treats the appearance while the cause continues.",
  o:["Correct — hours-onset change is delirium, and the cause must be found and treated.",
   "Dementia progresses over months to years; an hours-onset change is not progression.",
   "Sundowning follows a diurnal pattern and does not explain new visual disturbance.",
   "An antipsychotic masks the presentation while the underlying cause goes untreated."],
  s:"Dementia changes slowly; delirium changes in hours. Abrupt change means hunt for a physical cause before treating the behavior."},
 ref:"Psychosocial integrity · delirium superimposed on dementia"}
);
