/* RN Ready — item bank v2 · part 1 (Management of Care, Safety, Health Promotion,
   Psychosocial, Basic Care & Comfort). Same metadata model as bank.js.            */
window.NC = window.NC || {};
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Management of Care ─────────────────────────────────────────── */
{id:"MOC-006", t:"single", cn:"MOC", sys:"GI", topic:"Informed consent", d:1, b:-0.3, cj:"act", tags:["safety"],
 stem:"A 16-year-old client who is not emancipated requires an emergency appendectomy. Who should sign the surgical consent?",
 opts:["The client, because the surgery is emergent","A parent or legal guardian","The surgeon, under emergency doctrine","The nurse, as client advocate"],
 ans:1,
 rat:{c:"Minors (unemancipated) cannot legally provide informed consent — a parent or legal guardian must consent, even for urgent surgery, unless true emergency-with-no-guardian applies (then the provider documents emergency consent).",
 o:["A minor's assent may be obtained, but it does not constitute legal consent.","Correct — parent/legal guardian consents for a minor.","Emergency doctrine applies only when NO guardian is reachable and delay threatens life.","Nurses witness consent; they never sign as the consenting party."],
 s:"Consent ladder: adult client → guardian for minors → emergency doctrine (provider) only when no guardian is reachable. The nurse witnesses and verifies understanding."},
 ref:"Legal issues · informed consent"},

{id:"MOC-007", t:"single", cn:"MOC", sys:"PSYCH", topic:"Confidentiality / HIPAA", d:1, b:-0.25, cj:"act", tags:["safety"],
 stem:"A nurse's friend asks how a mutual neighbor — admitted last night — is doing. Which response best protects client confidentiality?",
 opts:["“I can only share information with people involved in the client's care.”","“She's doing much better — she just needed some fluids.”","“I can't talk about it here, but text me later.”","Ask the friend to check with the client's family instead"],
 ans:0,
 rat:{c:"Protected health information may be shared only with those directly involved in care (or with the client's authorization). Redirecting without confirming even the client's presence is the correct, professional response.",
 o:["Correct — need-to-know is the standard.","Any detail, even “she's doing better,” confirms care and discloses PHI.","Offering a private channel to breach confidentiality is still a breach.","Deflecting to family still confirms nothing and fails to set the boundary; the correct action is declining."],
 s:"Rule: no confirmation of presence, condition, or care without authorization. The exam answer is always the option that declines and explains why."},
 ref:"Confidentiality & information security"},

{id:"MOC-008", t:"single", cn:"MOC", sys:"INF", topic:"Handoff communication", d:1, b:-0.2, cj:"generate", tags:["safety","communication" ],
 stem:"During change-of-shift report, which practice best prevents communication errors during handoff?",
 opts:["Delivering report at the bedside of every client without a structured format","Using a standardized tool (e.g., SBAR) with an opportunity for questions and read-back","Giving report only to the oncoming RN in the hallway from memory","Recording report on voicemail so the oncoming nurse can listen anytime"],
 ans:1,
 rat:{c:"Standardized, structured handoff tools with two-way communication (questions, read-back/repeat-back) reliably reduce omissions and misinterpretation during transitions of care.",
 o:["Bedside report is good practice but unstructured delivery loses critical content — combine structure with bedside rounds.","Correct — SBAR + interactive verification is the evidence-based practice.","Memory-based hallway reports invite omissions and interruptions.","One-way recorded reports eliminate clarification and verification."],
 s:"Handoff answers on the exam: structured format + interactive verification (read-back, questions) + updated documentation."},
 ref:"Care coordination · handoff report (SBAR)"},

{id:"MOC-009", t:"single", cn:"MOC", sys:"INF", topic:"Leaving AMA", d:1, b:-0.15, cj:"act", tags:["safety","teaching"],
 stem:"A hospitalized client insists on leaving despite the provider's advice to stay. Which action is correct?",
 opts:["Restrain the client to prevent leaving until the provider arrives","Tell the client the door is locked during treatment hours","Explain the risks of leaving, notify the provider, and ask the client to sign an against-medical-advice (AMA) form","Allow the client to leave without documentation to preserve the relationship"],
 ans:2,
 rat:{c:"Competent adults have the right to refuse care and leave. The nurse explains risks, notifies the provider, documents the discussion, and has the client sign the AMA form — refusal to sign is also documented.",
 o:["Restraints require a behavioral/medical indication — leaving is neither.","Clients cannot be confined; that is false imprisonment.","Correct — informed refusal + documentation + AMA form.","Undocumented departure abandons legal and safety duties."],
 s:"Competent client → educate, escalate, document, AMA form. Never restrain, block, or coerce."}},

{id:"MOC-010", t:"single", cn:"MOC", sys:"REPI", topic:"Cultural & language needs", d:1, b:-0.3, cj:"generate", tags:["communication"],
 stem:"A client who speaks limited English must give informed consent for a procedure. Which approach is best?",
 opts:["Ask the client's 12-year-old child to interpret","Use a trained medical interpreter, either in person or by phone","Speak slowly and loudly in English with gestures","Have a bilingual nursing assistant summarize the consent"],
 ans:1,
 rat:{c:"Trained medical interpreters convey content accurately and neutrally, including risks and alternatives. Family members (especially children) and untrained staff filter, editorialize, or miss critical content, invalidating informed consent.",
 o:["Children must never serve as medical interpreters.","Correct — professional interpretation is the standard of care.","Volume does not create comprehension.","An unverified summary by a bilingual aide risks omissions and bias."],
 s:"Interpreter rules: use trained interpreters, speak to the CLIENT (not the interpreter), avoid family/children, document interpreter use."},
 ref:"Care of diverse clients · language access"},

{id:"MOC-011", t:"single", cn:"MOC", sys:"INF", topic:"Float assignment / scope", d:2, b:0.6, cj:"act", tags:["delegation","safety"],
 stem:"A medical-surgical nurse is floated to the labor and delivery unit and assigned a client in active labor. Which action by the float nurse is most appropriate?",
 opts:["Accept the assignment without comment since staffing is short","Inform the charge nurse of lack of labor-and-delivery experience and request supervision and a task-appropriate assignment","Refuse the float assignment and return to the home unit","Perform the assignment using policies from the medical-surgical unit"],
 ans:1,
 rat:{c:"Float nurses must disclose competency gaps and receive orientation/supervision; assignments must match demonstrated competence. Silence sets up unsafe care; outright refusal is not the first step.",
 o:["Accepting without disclosure ignores duty-to-competence.","Correct — disclose, request supervision, and negotiate a safe assignment.","Mass refusal of a float assignment risks abandonment; raise concerns through the chain of command.","Foreign-unit policies invite unsafe, incorrect care."],
 s:"Float questions: disclose competence gaps + ask for orientation/supervision + document concerns. Avoid both silent acceptance and walk-outs."},
 ref:"Staffing & assignment · competence"},

/* ── Safety & Infection Control ─────────────────────────────────── */
{id:"SIC-006", t:"multi", cn:"SIC", sys:"HEME", topic:"Hazardous medications", d:2, b:0.55, cj:"act", tags:["safety","medication"],
 stem:"The nurse is preparing to administer IV chemotherapy. Which protective measures are required? Select all that apply.",
 opts:["Chemotherapy-tested gloves worn in double layers","A disposable, impermeable gown with closed front","A fit-tested N95 respirator","Eye and face protection","Sterile surgical cap and shoe covers"],
 ans:[0,1,3],
 rat:{c:"Hazardous-drug handling requires double chemo-tested gloves, an impermeable gown, and eye/face protection during administration and disposal. Respirators, caps, and shoe covers are not routine PPE for chemotherapy.",
 o:["Correct — double gloving with tested gloves, changing outer glove per policy.","Correct — impermeable gown protects skin and scrubs.","N95 protects against airborne agents, not chemotherapy splashes.","Correct — splash exposure to mucous membranes must be prevented.","Not part of chemotherapy PPE standards."],
 s:"Chemo PPE: double chemo gloves + impermeable gown + eye/face shield. Prime at the pump? Never — prime tubing under the hood in pharmacy. Dispose in designated hazardous waste."},
 ref:"Safe handling of hazardous drugs (NIOSH)"},

{id:"SIC-007", t:"single", cn:"SIC", sys:"HEME", topic:"Needlestick exposure", d:1, b:-0.2, cj:"act", tags:["safety","priority"],
 stem:"A nurse sustains a needlestick injury from a device used on a client with hepatitis B. Which action should the nurse take first?",
 opts:["Complete an incident report and notify the charge nurse","Wash the site with soap and water and report to employee health immediately","Draw blood from the client for confirmatory testing","Squeeze the wound to express contaminated blood"],
 ans:1,
 rat:{c:"Immediate first aid is washing (not squeezing) the puncture site, then prompt reporting to employee/occupational health for exposure evaluation and post-exposure prophylaxis — timing matters for HBV/HIV PEP effectiveness.",
 o:["Reporting follows immediate first aid — sequence matters.","Correct — wash, then report for evaluation/PEP.","Client testing is coordinated by employee health, not by the nurse directly.","Squeezing/milking the wound is specifically not recommended."],
 s:"Exposure sequence: wash/flush (no milking) → report to occupational health → source testing & PEP decisions → incident report. PEP for HIV is most effective within hours."},
 ref:"Occupational exposure · bloodborne pathogens"},

{id:"SIC-008", t:"single", cn:"SIC", sys:"MSK", topic:"Incident reporting", d:1, b:-0.1, cj:"act", tags:["safety"],
 stem:"A client falls while unassisted to the bathroom. Which documentation approach is correct?",
 opts:["Record objective findings and care provided in the client's chart, and complete a separate incident report","Write “incident report filed” in the client's chart so staff can find details","Document in the chart that the previous shift failed to answer the call light","Wait until the end of shift to document from memory"],
 ans:0,
 rat:{c:"The chart receives objective clinical facts (assessment, injuries, interventions, notifications). The incident report is a separate internal quality document and is never referenced in the chart — the chart must stand alone for care.",
 o:["Correct — two separate documents; never cross-reference the incident report.","Mentioning the incident report in the legal record is improper and discoverable.","Blame language is inappropriate and speculative — document facts only.","Late, memory-based charting is unsafe practice; document promptly and factually."],
 s:"Incident rules: facts in chart (no blame, no “incident report” mention) + separate incident report ASAP. Chart what you saw, did, and notified."},
 ref:"Documentation · adverse events"},

{id:"SIC-009", t:"single", cn:"SIC", sys:"RESP", topic:"Disaster triage", d:2, b:0.65, cj:"prioritize", tags:["priority","safety"],
 stem:"During a mass casualty incident, the triage nurse tags four clients. Which client receives an IMMEDIATE (red) tag?",
 opts:["A client with a fixed and dilated pupil and no spontaneous respirations after airway repositioning","A client with respiratory distress and a sucking chest wound","A client with a closed femur fracture and stable vital signs","A client with full-thickness burns over 60% of the body who is awake"],
 ans:1,
 rat:{c:"Red-tag (immediate) clients have survivable, quickly correctable life threats — an open chest wound compromising breathing is treatable NOW. Expectant (black) applies to nonsurvivable injuries (agonal breathing); green/yellow apply to stable clients.",
 o:["Apneic despite airway maneuvers = expectant (black) in MCI resource logic.","Correct — correctable airway/breathing threat = red/immediate.","Stable long-bone fracture = delayed (yellow).","Massive burns with limited resources are typically expectant/delayed in MCI triage — not immediately salvageable."],
 s:"START triage: walk = green; respiratory effort after airway = red/black; perfusion (radial pulse, cap refill) and mental status sort red vs yellow. In MCIs you do the greatest good for the greatest number."},
 ref:"Emergency response · mass casualty triage"},

{id:"SIC-010", t:"single", cn:"SIC", sys:"INF", topic:"Sharps safety", d:0, b:-1.2, cj:null, tags:["safety"],
 stem:"After administering an IM injection with a safety-engineered syringe, which action prevents needlestick injury?",
 opts:["Recap the needle using a two-handed scooping method","Activate the safety device and dispose of the syringe immediately in the sharps container","Place the uncapped syringe on the tray for later disposal by environmental services","Break the needle off before disposal"],
 ans:1,
 rat:{c:"Activate the needle safety device immediately after use and dispose of it directly into a puncture-proof sharps container at the point of use. Recapping (especially two-handed), delays, and needle-breaking all increase injury risk.",
 o:["Two-handed recapping is the classic prohibited practice — never recap by scooping.","Correct — activate device, dispose immediately at point of use.","Leaving sharps unattended on trays causes injuries to others.","Never manipulate or break needles by hand."],
 s:"Sharps rule: activate safety mechanism immediately + one-motion disposal into the nearest sharps container. Never recap two-handed."},
 ref:"Standard precautions · sharps safety"},

/* ── Health Promotion & Maintenance ─────────────────────────────── */
{id:"HPM-005", t:"single", cn:"HPM", sys:"REPI", topic:"Newborn nutrition", d:1, b:-0.35, cj:"analyze", tags:["teaching"],
 stem:"The parent of a 5-day-old breastfed newborn asks about the baby's stools. Which finding is expected?",
 opts:["Hard, formed, pale stools","Yellow, seedy, loose stools with small white curds","Black, tarry stools","Stools only once every 4 days with straining"],
 ans:1,
 rat:{c:"Breastfed newborn stools are typically yellow to golden, loose, and seedy (unabsorbed milk curds), occurring several times daily. Black tarry = meconium (first days) or blood; hard/pale/infrequent stools suggest formula issues or pathology.",
 o:["Hard formed stools suggest formula-fed constipation or dehydration.","Correct — classic breastfed-milk stool.","Meconium appears in the first 1–2 days; beyond that it suggests problem.","Infrequent straining stools in a breastfed newborn warrant evaluation (or may be normal after ~6 weeks, but not day 5 with the pattern described)."],
 s:"Timeline: meconium ≤24–48 h → transitional → yellow seedy (breastfed) / pale pasty (formula). Know normal so abnormal stands out."},
 ref:"Newborn nutrition & elimination"},

{id:"HPM-006", t:"single", cn:"HPM", sys:"PSYCH", topic:"Toddler discipline", d:1, b:-0.4, cj:"generate", tags:["teaching"],
 stem:"A parent asks how to respond when their 2-year-old throws frequent temper tantrums. Which guidance is most appropriate?",
 opts:["Spank the child briefly to end the tantrum quickly","Stay calm, ensure the child is safe, and ignore the tantrum until the child calms down","Give the child whatever ended the last tantrum to avoid escalation","Send the child to their room alone and lock the door until quiet"],
 ans:1,
 rat:{c:"Tantrums are normal toddler autonomy/limit behavior. The recommended response is calm consistency: keep the child safe, don't reward the tantrum with attention or prizes, and praise calm behavior. Isolating a distressed toddler or physical punishment is inappropriate.",
 o:["Corporal punishment is never the recommended guidance.","Correct — safety + calm + no reinforcement of the tantrum.","Rewarding tantrums teaches that tantrums work.","Locking a toddler alone is unsafe and frightening."],
 s:"Tantrums: calm, safe, consistent limits, ignore the behavior (not the child), reinforce desired behavior."},
 ref:"Toddler psychosocial development"},

{id:"HPM-007", t:"single", cn:"HPM", sys:"PSYCH", topic:"School-age development", d:1, b:-0.3, cj:"analyze", tags:["assessment"],
 stem:"A 9-year-old tells the nurse, “I'm no good at soccer and my grades are bad.” According to Erikson, which developmental conflict is this child struggling with?",
 opts:["Trust vs. mistrust","Initiative vs. guilt","Industry vs. inferiority","Identity vs. role confusion"],
 ans:2,
 rat:{c:"School-age children (≈6–12 y) are in industry vs. inferiority: they build competence through school, tasks, and skills. Feelings of inadequacy at school and activities signal difficulty with exactly this stage.",
 o:["Infancy (birth–18 mo).","Preschool (3–6 y).","Correct — school-age competence and accomplishment.","Adolescence (12–18 y)."],
 s:"Erikson ladder: trust (infant) → autonomy (toddler) → initiative (preschool) → industry (school-age) → identity (teen) → intimacy (young adult)."},
 ref:"Developmental theories · Erikson"},

{id:"HPM-008", t:"single", cn:"HPM", sys:"INF", topic:"Adolescent safety", d:1, b:-0.45, cj:null, tags:["teaching","safety"],
 stem:"During a health-promotion visit, which teaching point addresses the LEADING cause of death in adolescents?",
 opts:["Increase calcium intake to prevent early osteoporosis","Wear sunscreen with SPF 30 or higher","Avoid riding in vehicles with drivers who are texting or impaired","Get adequate sleep on school nights"],
 ans:2,
 rat:{c:"Motor vehicle crashes (and injuries broadly) are the leading cause of adolescent death — seat belt use and refusing to ride with distracted/impaired drivers are priority safety teaching. The others are healthy habits but not the top killer.",
 o:["Important for bone health, not mortality prevention in teens.","Skin cancer prevention — valuable but not the leading threat.","Correct — injury prevention leads adolescent mortality.","Sleep matters, but crashes outrank it."],
 s:"Adolescent exam priorities: motor-vehicle safety, firearms, substance use, sexual health, mental health/suicide screening."},
 ref:"Adolescent health promotion"},

{id:"HPM-009", t:"single", cn:"HPM", sys:"MSK", topic:"Osteoporosis screening", d:0, b:-1.1, cj:null, tags:["teaching","assessment"],
 stem:"A 66-year-old asks when to be screened for osteoporosis. The nurse's best response is based on which guideline?",
 opts:["Bone density (DXA) screening for all women beginning at age 65","DXA screening only after a fracture occurs","Calcium blood levels annually after menopause","DXA screening for all adults beginning at age 40"],
 ans:0,
 rat:{c:"Guidelines recommend DXA bone-density screening for women ≥65 (and earlier ≥50 with risk factors: fracture history, smoking, low weight, steroid use, family history). Serum calcium does not measure bone density.",
 o:["Correct — universal at 65, earlier with risk factors.","Waiting for fracture forfeits prevention.","Calcium levels are not a bone-density screen.","40 is far too early for universal screening."],
 s:"Osteoporosis: screen women at 65+ (younger with risks). Prevention triad: calcium + vitamin D + weight-bearing exercise."},
 ref:"Osteoporosis screening guidance"},

{id:"HPM-010", t:"single", cn:"HPM", sys:"INTG", topic:"Pregnancy changes", d:0, b:-1.2, cj:"analyze", tags:["assessment"],
 stem:"A woman at 28 weeks' gestation reports a dark line developing from her pubic area to the umbilicus. How should the nurse interpret this?",
 opts:["A sign of fetal distress","Expected hyperpigmentation of pregnancy (linea nigra)","A dermatologic infection requiring treatment","A sign of iron deficiency anemia"],
 ans:1,
 rat:{c:"Linea nigra — hyperpigmentation along the linea alba driven by pregnancy hormones (with melasma/chloasma) — is a normal, expected change requiring only reassurance.",
 o:["Skin hyperpigmentation has no relation to fetal status.","Correct — normal pregnancy change; fades postpartum.","No inflammatory or infectious features are described.","Pigmentation does not indicate anemia."],
 s:"Normal pregnancy skin changes: linea nigra, melasma, striae, spider angiomas. Reassure; no treatment."},
 ref:"Normal pregnancy physiology"},

{id:"HPM-011", t:"single", cn:"HPM", sys:"REPI", topic:"Testicular self-exam", d:0, b:-1.05, cj:null, tags:["teaching","assessment"],
 stem:"The nurse teaches a 19-year-old man about testicular self-examination. Which instruction is correct?",
 opts:["Perform the exam monthly, ideally during or right after a warm shower","Perform the exam once a year after age 40","Perform the exam immediately after strenuous exercise","Avoid the exam unless a lump is felt first"],
 ans:0,
 rat:{c:"Testicular cancer is most common in men 15–35. Monthly self-exam is best performed during/after a warm shower when the scrotal skin is relaxed: gently palpate each testicle between thumb and fingers, feeling for lumps or changes.",
 o:["Correct — warmth relaxes the scrotum; monthly from the late teens.","Yearly after 40 misses the highest-risk window entirely.","Post-exam timing has no rationale.","Waiting for symptoms defeats early detection."],
 s:"TSE: monthly, warm shower, both testes, report any painless lump or change. Highest-risk age: young men 15–35."},
 ref:"Cancer screening & self-exam teaching"},

{id:"HPM-012", t:"emr", cn:"HPM", sys:"REPI", topic:"Infant development", d:1, b:-0.2, cj:"recognize", tags:["assessment"],
 stem:"At a 2-month well-child visit, the nurse assesses development. Select the findings that are EXPECTED for age in each group.",
 groups:[
  {h:"Social & language", opts:["Coos and makes gurgling sounds","Smiles socially in response to a face","Says “mama” and “dada” with meaning","Laughs out loud"], ans:[0,1]},
  {h:"Motor", opts:["Lifts head 45° when prone","Holds head steady without support when held sitting","Rolls from abdomen to back consistently","Reaches and transfers objects hand to hand"], ans:[0,1]}],
 rat:{c:"At 2 months expect social smiling, cooing, head lift 45° prone, and beginning head control. Meaningful words (~9–10 mo), consistent rolling (~4–5 mo), belly-to-back rolling (~4 mo), and hand-to-hand transfer (~6 mo) come later; out-loud laughing emerges ~3–4 months.",
 o:["Expected at 2 months.","Expected — social smile appears by ~2 months.","Meaningful words appear around 9–10 months.","Laughing out loud ~3–4 months.","Expected 1–2 months.","Expected by 2 months.","Rolling belly-to-back ~4 months.","Transfer hand-to-hand ~6 months."],
 s:"Learn milestone clusters by age band: 2 mo (social smile, coo, head 45°) → 4 mo (rolls, laughs, hands together) → 6 mo (sits with support, transfers, babbles) → 9 mo (stranger anxiety, pincer begins) → 12 mo (walks, 1–2 words)."},
 ref:"Pediatric developmental milestones"},

/* ── Psychosocial Integrity ─────────────────────────────────────── */
{id:"PSY-005", t:"single", cn:"PSY", sys:"PSYCH", topic:"Lithium", d:1, b:-0.25, cj:"act", tags:["medication","priority","assessment"],
 stem:"A client on lithium for bipolar disorder has a serum level of 1.8 mEq/L with coarse hand tremors, nausea, and confusion. Which action is the priority?",
 opts:["Administer the next scheduled dose with food","Hold the dose and notify the provider","Encourage increased fluid intake and recheck the level next week","Document the findings and continue monitoring"],
 ans:1,
 rat:{c:"Serum lithium 1.8 mEq/L exceeds the therapeutic range (0.6–1.2) and with tremor, GI symptoms, and confusion signals toxicity — hold the drug and notify the provider immediately (treatment may include hydration and, if severe, dialysis).",
 o:["Continuing lithium deepens toxicity.","Correct — hold + notify; toxicity can progress to seizures, dysrhythmias, and coma.","Outpatient “wait and see” is unsafe at a toxic level with neurologic signs.","Documentation alone delays essential action."],
 s:"Lithium therapeutic 0.6–1.2 (acute mania up to 1.5). Toxicity: tremor, GI, confusion → seizures, dysrhythmias. Maintenance teaching: steady salt/fluid intake, avoid NSAIDs/thiazides, monitor levels."},
 ref:"Mood stabilizers · lithium toxicity"},

{id:"PSY-006", t:"single", cn:"PSY", sys:"PSYCH", topic:"Antipsychotic side effects", d:2, b:0.55, cj:"act", tags:["medication","priority"],
 stem:"Two days after starting haloperidol, a client develops painful neck muscle spasms with the head twisted to one side and the eyes deviated upward. Which prescribed PRN medication should the nurse anticipate administering?",
 opts:["Diphenhydramine or benztropine (anticholinergic/antidystonic)","A second dose of haloperidol","Lorazepam for anxiety","Acetaminophen for muscle pain"],
 ans:0,
 rat:{c:"This is acute dystonia — an extrapyramidal reaction to first-generation antipsychotics — treated with anticholinergic/antihistaminic agents (benztropine, diphenhydramine). More antipsychotic worsens it; anxiolytics/analgesics do not reverse dystonia.",
 o:["Correct — antidystonic/anticholinergic agents abort acute dystonia.","Additional haloperidol would worsen the reaction.","Anxiety medication does not treat dystonia (lorazepam helps akathesis sometimes, not first for dystonia).","Symptomatic analgesia ignores the reversible cause."],
 s:"EPS family: dystonia (painful spasm — benztropine), akathisia (restlessness — dose ↓/beta blocker), parkinsonism (rigidity, shuffling — anticholinergic), tardive dyskinesia (late, irreversible — valbenazine/report)."},
 ref:"Antipsychotics · extrapyramidal symptoms"},

{id:"PSY-007", t:"single", cn:"PSY", sys:"PSYCH", topic:"Eating disorders", d:2, b:0.6, cj:"prioritize", tags:["priority","assessment"],
 stem:"An adolescent with anorexia nervosa is admitted for medical stabilization. Which assessment finding requires the most immediate follow-up?",
 opts:["Serum potassium 2.8 mEq/L with ECG showing ST depression and U waves","Weight at 78% of ideal body weight","Lanugo over the arms and back","Preoccupation with food preparation and calories"],
 ans:0,
 rat:{c:"Hypokalemia with ECG changes (U waves, ST depression) signals imminent cardiac dysrhythmia — the leading cause of sudden death in anorexia. The other findings are serious but chronic/stable.",
 o:["Correct — electrolyte + ECG abnormality is an immediate life threat.","Serious chronic finding — supports acuity but not an acute event.","Lanugo reflects chronic malnutrition — monitor.","Behavioral features define the disorder; not emergent."],
 s:"Eating-disorder priorities: cardiac (K+, Mg, bradycardia, QTc) > hemodynamics > refeeding risk (phosphate!) > weight/behavior. Watch for refeeding syndrome when feeding restarts."},
 ref:"Eating disorders · medical complications"},

{id:"PSY-008", t:"single", cn:"PSY", sys:"PSYCH", topic:"Child abuse", d:1, b:-0.15, cj:"act", tags:["safety","priority"],
 stem:"A 4-year-old being treated for a burn has injuries the nurse suspects are caused by abuse. The parent asks whether the nurse will report the concern. Which response is correct?",
 opts:["“Only the provider can decide whether to report the abuse.”","“Nurses are legally mandated to report suspected child abuse; I must report my concerns.”","“I'll keep it between us unless it happens again.”","“I need the child's permission before reporting.”"],
 ans:1,
 rat:{c:"Nurses (and all health professionals) are mandated reporters: suspicion of abuse must be reported to child protective services — no provider approval, child consent, or certainty required. Failure to report is legally actionable.",
 o:["Reporting does not wait for, or depend on, the provider.","Correct — mandated reporting of SUSPICION, by the nurse, immediately.","Confidentiality does not apply to suspected abuse.","A 4-year-old cannot consent; protection overrides."],
 s:"Abuse rules: report suspicion yourself (chain: supervisor does not replace your duty), don't investigate/interrogate the family, document facts verbatim, ensure immediate safety."},
 ref:"Child abuse · mandatory reporting"},

{id:"PSY-009", t:"single", cn:"PSY", sys:"PSYCH", topic:"Alcohol withdrawal management", d:1, b:-0.1, cj:"generate", tags:["medication","priority"],
 stem:"A hospitalized client with heavy alcohol use develops tremors, diaphoresis, and elevated vital signs within 12 hours of admission. Which class of medication does the nurse anticipate administering per protocol?",
 opts:["Benzodiazepines (e.g., lorazepam or chlordiazepoxide)","Antipsychotics (e.g., haloperidol)","SSRIs (e.g., sertraline)","Opioids (e.g., morphine)"],
 ans:0,
 rat:{c:"Benzodiazepines are first-line for alcohol withdrawal — they prevent progression to seizures and delirium tremens and are dosed by symptom-triggered protocols (e.g., CIWA-Ar).",
 o:["Correct — symptom-triggered benzodiazepines per CIWA.","Antipsychotics do not prevent withdrawal seizures/DTs (and lower seizure threshold).","SSRIs have no acute withdrawal role.","Opioids treat pain, not withdrawal, and add sedation risk."],
 s:"Withdrawal armamentarium: benzodiazepines (core), thiamine BEFORE glucose, folate/multivitamin, and CIWA-based dosing. Remember thiamine sequencing."},
 ref:"Substance use · withdrawal protocols"},

{id:"PSY-010", t:"matrix", cn:"PSY", sys:"PSYCH", topic:"Hallucinations", d:1, b:-0.25, cj:"generate", tags:["communication","safety"],
 stem:"A client hospitalized with schizophrenia says, “The voices are telling me to hurt myself.” For each nursing response, indicate whether the nurse should USE it or AVOID it.",
 matrix:{cols:["Use","Avoid"], mode:"radio",
  rows:["“I don't hear the voices, but I believe they feel real to you. What are they telling you?”","“The voices are not real — stop listening to them.”","Assess whether the voices command harm and whether the client intends to act","Ensure the client is observed and the environment is safe"],
  ans:[0,1,0,0]},
 rat:{c:"Therapeutic responses validate the client's experience without reinforcing the hallucination, assess command content and intent, and maintain safety. Arguing that voices “aren't real” invalidates the client and escalates distress.",
 o:["Use — honesty + validation + assessment prompt.","Avoid — arguing with the hallucination invalidates and escalates.","Use — command hallucinations for harm drive safety interventions.","Use — observation and a safe environment are mandatory."],
 s:"Psychosis responses: present reality gently (“I don't hear them, but I know they're real to you”), assess commands/intent, never argue or play along, keep stimulation low."},
 ref:"Schizophrenia · therapeutic communication"},

{id:"PSY-011", t:"hotspot", cn:"PSY", sys:"PSYCH", topic:"Depression risk screening", d:2, b:0.5, cj:"recognize", tags:["assessment","safety"],
 stem:"Review the intake notes for an adolescent seen in the clinic. Tap to highlight each statement/finding that elevates suicide risk and requires follow-up.",
 hotspot:{mode:"rows",
  rows:["“I gave my guitar to my best friend last week — she's kept it.”","“Sometimes I think everyone would be fine if I just didn't wake up.”","Sleeping 11 hours nightly but still feels exhausted","Appetite unchanged; eats dinner with family nightly","Grade point average dropped from 3.6 to 2.1 this term","“I've thought about how I'd do it, but I haven't planned a day.”"],
  ans:[0,1,2,4,5]},
 rat:{c:"Giving away possessions, expressed death wishes, hypersomnia with fatigue, abrupt academic decline, and — most critically — an ideation-with-method statement are all established warning signs. Stable appetite/family meals are not risk markers here.",
 o:["Giving away prized possessions = preparatory behavior: risk.","Passive death wish ideation: risk.","Neurovegetative change: risk.","Neutral/protective — distractor.","Sudden functional decline: risk.","Ideation with method (even without a date) = high risk: assess plan/means/access immediately."],
 s:"Risk cluster: ideation → plan → means/access → intent + preparatory acts (giving things away, goodbye messages), plus function drop (grades, sleep, appetite). Any method statement triggers immediate safety assessment."},
 ref:"Suicide risk assessment · warning signs"},

/* ── Basic Care & Comfort ───────────────────────────────────────── */
{id:"BCC-005", t:"single", cn:"BCC", sys:"INTG", topic:"Wound healing nutrition", d:1, b:-0.4, cj:"generate", tags:["teaching","intervention"],
 stem:"The nurse develops a nutrition plan for an older adult with a nonhealing pressure injury. Which dietary emphasis promotes wound healing?",
 opts:["High protein with vitamin C and zinc as indicated","Low-calorie, low-residue diet","High-fat, low-carbohydrate diet","Fluid restriction to reduce wound drainage"],
 ans:0,
 rat:{c:"Wound healing requires substrate: increased protein (collagen synthesis), vitamin C (collagen cross-linking), adequate calories, hydration, and zinc if deficient. Restricting calories or fluids impairs perfusion and granulation.",
 o:["Correct — protein + micronutrients + calories + hydration.","Caloric restriction starves anabolism.","No rationale; balanced calories are needed.","Dehydration reduces tissue perfusion and worsens healing."],
 s:"Healing diet on the exam: protein, vitamin C, zinc (if deficient), adequate calories and fluids. Negative markers: low-protein diets, fluid restriction."},
 ref:"Nutrition · wound healing"},

{id:"BCC-006", t:"single", cn:"BCC", sys:"INTG", topic:"Pressure injury staging", d:1, b:-0.35, cj:"analyze", tags:["assessment"],
 stem:"The nurse notes a shallow open ulcer with a red-pink wound bed and intact blister on a client's sacrum. How should this pressure injury be staged?",
 opts:["Stage 1","Stage 2","Stage 3","Unstageable"],
 ans:1,
 rat:{c:"Stage 2 = partial-thickness skin loss: shallow open ulcer with a red-pink bed, with or without intact serum-filled blister. Stage 1 is intact nonblanchable skin; stage 3 involves full-thickness loss into subcutaneous tissue; unstageable means the base is covered by slough/eschar.",
 o:["Intact skin with discoloration = stage 1 (not open).","Correct — partial-thickness loss: shallow ulcer ± blister.","Full-thickness into subcutaneous fat = stage 3.","Base not visible (slough/eschar) = unstageable."],
 s:"Staging ladder: 1 nonblanchable redness intact → 2 partial-thickness (blister/shallow) → 3 full-thickness, visible fat → 4 exposed bone/tendon/muscle → unstageable (base covered) + DTI (deep purple, intact)."},
 ref:"Skin integrity · pressure injury classification"},

{id:"BCC-007", t:"single", cn:"BCC", sys:"GI", topic:"Ileostomy", d:2, b:0.6, cj:"act", tags:["assessment","priority"],
 stem:"A client with a new ileostomy has output of 1,200 mL in the last 24 hours. Which action is most important?",
 opts:["Document the output as an expected finding","Notify the provider and monitor electrolytes and hydration status","Apply a skin barrier and change the pouch less frequently","Encourage a low-fiber diet to thicken output"],
 ans:1,
 rat:{c:"Ileostomy output >1,000–1,200 mL/day risks dehydration, sodium/potassium depletion, and renal issues — high-output stomas warrant provider notification, electrolyte monitoring, and hydration management (often antimotility/antisecretory agents).",
 o:["This exceeds normal ileostomy output (~500–800 mL/day).","Correct — high output is a metabolic emergency risk.","Pouch management doesn't address the volume/electrolyte problem.","Diet alone won't control established high output."],
 s:"Ostomy math: ileostomy loses fluid + electrolytes (K+, Na+, Mg) — high output = dehydration + dysrhythmia risk. Colostomy output is formed; ileostomy is liquid."},
 ref:"Ostomy care · high-output stoma"},

{id:"BCC-008", t:"single", cn:"BCC", sys:"NEURO", topic:"Nonpharmacologic pain", d:0, b:-1.25, cj:null, tags:["teaching","intervention"],
 stem:"Which intervention is an example of a nonpharmacologic adjuvant therapy for chronic back pain?",
 opts:["Scheduled acetaminophen","Guided imagery with progressive muscle relaxation","Epidural steroid injection","Transcutaneous patches containing lidocaine"],
 ans:1,
 rat:{c:"Guided imagery and progressive muscle relaxation are cognitive-behavioral, drug-free adjuvant therapies. The other options are pharmacologic (medication or drug-delivering procedures).",
 o:["Pharmacologic (analgesic).","Correct — mind-body adjuvant therapy.","Invasive pharmacologic intervention.","Pharmacologic (drug-delivery patch)."],
 s:"Nonpharm pain toolbox: imagery, relaxation breathing, distraction, music, heat/cold, massage, TENS (device, drug-free), guided imagery. Medications and injections are pharmacologic."},
 ref:"Pain management · integrative therapies"},

{id:"BCC-009", t:"single", cn:"BCC", sys:"NEURO", topic:"Neurogenic bowel", d:2, b:0.7, cj:"generate", tags:["teaching","intervention"],
 stem:"The nurse establishes a bowel program for a client with a spinal cord injury at T6 (reflex bowel). Which schedule is most effective?",
 opts:["Perform the program at the same scheduled time daily, after a meal, using digital stimulation as prescribed","Perform the program whenever the client feels the urge to defecate","Administer a daily enema at bedtime indefinitely","Delay the program until training is complete at a rehabilitation facility"],
 ans:0,
 rat:{c:"Reflex neurogenic bowel is managed with a fixed daily schedule exploiting the gastrocolic reflex (post-meal) plus digital stimulation to trigger evacuation — building predictable continence. Waiting for urge fails (sensation is lost), and daily enemas are not a maintenance program.",
 o:["Correct — consistency + gastrocolic reflex + digital stimulation.","Clients with SCI above the conus typically do NOT feel urge reliably.","Chronic daily enemas cause dependence and electrolyte problems.","Training should begin during acute care, not be deferred."],
 s:"Neurogenic bowel: reflex (above T12/S1) → scheduled program + digital stimulation; areflexic (conus/cauda equina) → manual evacuation/valsalva assist. Same time daily, after meals."},
 ref:"Spinal cord injury · bowel management"}
);
