/* RN Ready — item bank v1. Every item carries the full metadata model:
   t (type) cn (client need) sys (body system) topic d (difficulty 0-3) b (IRT-ish difficulty, logit)
   cj (clinical judgment step or null) tags[] ans/rat (rationales) ref (source note).
   Item formats: single | multi | emr | drag | cloze | hotspot | matrix            */
window.NC = window.NC || {};
NC.BANK = [

/* ── Management of Care ─────────────────────────────────────────── */
{id:"MOC-001", t:"single", cn:"MOC", sys:"MSK", topic:"Delegation", d:1, b:-0.35, cj:"act", tags:["delegation"], variantGroup:"delegation-uap",
 stem:"The RN on a medical-surgical unit is planning care for the shift. Which task is appropriate to delegate to an unlicensed assistive personnel (UAP)?",
 opts:["Determine whether a client's pain has decreased after medication","Ambulate a client who is stable on the second day after an appendectomy","Perform the first assessment after a client returns from endoscopy","Teach a client how to self-administer insulin before discharge"],
 ans:1,
 rat:{c:"Ambulating a stable client is a routine, standardized task within the UAP scope. Delegation requires the task to be safe, routine, and the client stable.",
 o:["Evaluating a response to treatment is a nursing judgment — the RN closes that loop.","Correct — stable client, routine activity, minimal judgment required.","The first post-procedure assessment belongs to the RN; only routine rechecks may follow.","Client teaching requires RN knowledge and cannot be delegated to UAP."],
 s:"Ask: is the task routine and standardized, is the client stable, and does it require nursing judgment? Teaching and assessment stay with the RN."},
 ref:"Management of Care · delegation & assignment principles"},

{id:"MOC-002", t:"single", cn:"MOC", sys:"INF", topic:"Prioritization", d:2, b:0.55, cj:"prioritize", tags:["priority","assessment"],
 stem:"The nurse receives report on four clients. Which client should the nurse assess first?",
 opts:["A client 3 days postoperative who reports new increased serosanguineous drainage from the incision","A client requesting pain medication for incisional pain rated 6/10","A client 24 hours postoperative with an oral temperature of 37.8°C (100.0°F)","A client scheduled for surgery this afternoon who is anxious about the procedure"],
 ans:0,
 rat:{c:"New or increased drainage from a surgical incision may indicate dehiscence, infection, or hemorrhage — an acute physiologic change that can rapidly become life-threatening. Physiologic instability beats pain, low-grade expected fever, and anxiety.",
 o:["Correct — new drainage suggests a possible acute complication (dehiscence/bleed) and needs immediate assessment.","Pain is important but the client is stable; use prioritization frameworks (ABC/maslow/acute vs chronic).","Mild low-grade fever in the first 24–48 h postop is common and expected.","Anxiety is a psychosocial need — address after unstable physiologic issues."],
 s:"Rank by physiologic stability first: potential hemorrhage/dehiscence > pain > expected postop findings > anxiety."},
 ref:"Prioritization · acute vs chronic & stability"},

{id:"MOC-003", t:"multi", cn:"MOC", sys:"INF", topic:"Delegation / LPN scope", d:1, b:-0.2, cj:"generate", tags:["delegation"],
 stem:"Which tasks may the RN appropriately assign to a licensed practical/vocational nurse (LPN/LVN)? Select all that apply.",
 opts:["Administer oral antibiotics to a stable client with pneumonia","Change a sterile dressing on a stable surgical wound","Administer the first dose of an IV antibiotic to a newly admitted client","Develop the plan of care for a newly admitted client","Administer a unit of packed red blood cells"],
 ans:[0,1],
 rat:{c:"LPNs may perform focused tasks for stable clients — including administering oral/IM medications and wound care per established plans. Initial doses of IV medications, comprehensive assessment/care planning, and blood administration require the RN.",
 o:["Correct — stable client, established medication order, within LPN scope.","Correct — sterile dressing change on a stable wound is within LPN scope.","First doses of IV medications carry high anaphylaxis risk — RN responsibility in most jurisdictions and on NCLEX.","Care planning builds on the RN's comprehensive admission assessment — RN responsibility.","Blood product administration is an RN responsibility."],
 s:"LPN = stable clients + established plans + routine treatments. First doses, blood, initial assessment/teaching, and care planning stay with the RN."},
 ref:"Delegation · RN vs LPN scope"},

{id:"MOC-004", t:"single", cn:"MOC", sys:"REPI", topic:"Advance directives", d:1, b:-0.1, cj:"act", tags:["evaluation","teaching"],
 stem:"A client admitted with a worsening chronic illness states, “I don't ever want to be placed on a breathing machine.” Which action is best for the nurse to take?",
 opts:["Document “client refuses mechanical ventilation” in the chart","Clarify the client's wishes, document the discussion, and encourage the client to formalize them in a written advance directive","Tell the client's family so they can make decisions if the client cannot","Notify the provider to write a do-not-resuscitate order"],
 ans:1,
 rat:{c:"An advance directive must reflect the client's specific, informed wishes. The nurse clarifies and documents the conversation and encourages formalizing it — the nurse does not convert a verbal statement into orders.",
 o:["A chart note alone does not protect the client's wishes; it is not a legal directive.","Correct — clarify, document, and encourage a formal advance directive while the client can participate.","Family decision-making applies only if the client loses capacity and has no directive — and is not the nurse's first step.","A DNR order requires the provider and the client's (or surrogate's) informed consent; “no mechanical ventilation” is not the same as DNR."],
 s:"Client autonomy: clarify → document → encourage formalization. Never translate a vague wish into an order yourself."},
 ref:"Client rights & advance directives"},

{id:"MOC-005", t:"matrix", cn:"MOC", sys:"INF", topic:"Assignment", d:2, b:0.7, cj:"generate", tags:["delegation","priority"],
 stem:"The charge nurse is making assignments. For each task, indicate whether it is most appropriate to assign to the RN, the LPN/LVN, or the unlicensed assistive personnel (UAP).",
 matrix:{cols:["RN","LPN/LVN","UAP"], mode:"radio",
  rows:["Administer a unit of packed red blood cells","Obtain routine vital signs on a stable client","Reinforce teaching about wound care for a stable client","Develop the plan of care on admission","Feed an alert, stable client who can swallow normally"],
  ans:[0,2,1,0,2]},
 rat:{c:"Blood products and care planning are RN-only; reinforcing established teaching and routine treatments for stable clients fit the LPN; measuring vital signs and feeding a stable client are UAP tasks.",
 o:["Blood administration → RN (transfusion reactions require RN assessment).","Routine VS on a stable client → UAP.","Reinforcement of existing teaching → LPN.","Care planning flows from the RN admission assessment.","Feeding a stable client with an intact swallow → UAP."],
 s:"Sort by judgment + stability: judgment-heavy or high-risk → RN; established task + stable client → LPN; routine/standardized + stable → UAP."},
 ref:"Assignment & supervision"},

/* ── Safety & Infection Control ─────────────────────────────────── */
{id:"SIC-001", t:"single", cn:"SIC", sys:"RESP", topic:"Isolation precautions", d:1, b:-0.3, cj:"act", tags:["safety"], variantGroup:"isolation-airborne",
 stem:"A client is admitted with suspected pulmonary tuberculosis. Which transmission-based precautions should the nurse initiate?",
 opts:["Contact precautions with gown and gloves","Droplet precautions with a surgical mask within 3 feet","Airborne precautions with an N95 respirator and a negative-pressure room","Standard precautions only until sputum results return"],
 ans:2,
 rat:{c:"TB is spread by airborne droplet nuclei smaller than 5 microns, which remain suspended in air — requiring airborne precautions: N95 respirator for staff and a negative-pressure (AIIR) room.",
 o:["Contact precautions are for organisms spread by touch (e.g., C. difficile, scabies).","Droplet precautions (surgical mask) are for large droplets — pertussis, influenza, rubella.","Correct — airborne: N95 + negative-pressure room.","Suspected TB still requires airborne precautions while awaiting confirmation."],
 s:"Airborne (TB, measles, varicella) = N95 + negative pressure. Droplet = surgical mask. Contact = gown/gloves."},
 ref:"Infection prevention & control · transmission-based precautions"},

{id:"SIC-002", t:"single", cn:"SIC", sys:"INF", topic:"Emergency response", d:1, b:-0.15, cj:"act", tags:["safety","priority"],
 stem:"A fire starts in a client room on the unit. Following RACE, which action should the nurse take first?",
 opts:["Activate the fire alarm","Rescue any clients from the immediate danger area","Attempt to extinguish the fire with the appropriate extinguisher","Close all doors on the unit to contain smoke"],
 ans:1,
 rat:{c:"RACE = Rescue, Alarm, Contain, Extinguish/Evacuate. Client safety comes first: remove clients from immediate danger before alarming, containing, or fighting the fire.",
 o:["The alarm is second — after rescuing clients in immediate danger.","Correct — rescue first.","Extinguishing comes last and only if the fire is small and you are trained.","Containing (closing doors) follows rescue and alarm."],
 s:"Memorize RACE order: Rescue → Alarm → Contain → Extinguish. The exam tests the order, not the definitions."},
 ref:"Emergency response plan · fire safety"},

{id:"SIC-003", t:"multi", cn:"SIC", sys:"NEURO", topic:"Seizure safety", d:0, b:-1.1, cj:"generate", tags:["safety","intervention"],
 stem:"The nurse is setting up seizure precautions for a client with a new seizure disorder. Which measures should be included? Select all that apply.",
 opts:["Oxygen and suction equipment at the bedside","Padding on the bed rails and headboard","A padded tongue blade at the bedside","Restraining the client during the seizure","Ensuring the bed is in the lowest position"],
 ans:[0,1,4],
 rat:{c:"Seizure precautions prioritize airway readiness (oxygen/suction), injury prevention (padding, low bed). Nothing is ever placed in the mouth, and clients are never restrained during a seizure.",
 o:["Correct — airway equipment must be immediately available post-ictally.","Correct — pad rails and headboard to prevent injury.","Never place anything in the mouth — risk of broken teeth and aspiration.","Never restrain — guide, don't restrict, movements; restraint causes injury.","Correct — low bed reduces fall injury."],
 s:"Seizure rules: protect (pad, low bed), position (side), never insert anything in the mouth, never restrain, time the event."},
 ref:"Safety · seizure precautions"},

{id:"SIC-004", t:"single", cn:"SIC", sys:"PSYCH", topic:"Restraints", d:2, b:0.75, cj:"act", tags:["safety","evaluation"],
 stem:"A client has bilateral wrist restraints after repeatedly pulling at a nasogastric tube. How often must the nurse assess circulation and provide range of motion while the restraints are in use?",
 opts:["Every 15 minutes","Every 2 hours","Every 4 hours","Once per shift"],
 ans:1,
 rat:{c:"For non-violent, non-self-destructive restraint use, circulation, sensation, and ROM must be checked and documented at least every 2 hours, with release as clinically appropriate. (The every-15-minute monitoring standard applies to violent/self-destructive restraints.)",
 o:["Every 15 minutes is the monitoring interval for violent/self-destructive behavior restraints — this client is non-violent.","Correct — q2h assessment with release/ROM for non-violent restraints.","Four hours exceeds safe limits for neurovascular checks.","Once per shift is far too infrequent and violates standards."],
 s:"Two standards to keep straight: violent restraints → monitor q15min; non-violent (device protection) → circulation/ROM check q2h. Renewal/renewal orders also differ (violent q4h adult / non-violent q24h)."},
 ref:"Restraint standards · least restrictive intervention"},

{id:"SIC-005", t:"cloze", cn:"SIC", sys:"INF", topic:"Isolation precautions", d:1, b:-0.1, cj:"analyze", tags:["safety"],
 stem:"Complete each statement about transmission-based precautions using the drop-down menus.",
 cloze:{lines:[
  {pre:"A child hospitalized with measles should be placed on", post:"precautions in a negative-pressure room.", opts:["Airborne","Droplet","Contact"], ans:0},
  {pre:"An adult diagnosed with pertussis (whooping cough) requires", post:"precautions, including a surgical mask within 3–6 feet.", opts:["Airborne","Droplet","Contact"], ans:1},
  {pre:"A client admitted with scabies requires", post:"precautions, including gown and gloves during care.", opts:["Airborne","Droplet","Contact"], ans:2}]},
 rat:{c:"Measles spreads by airborne droplet nuclei (N95 + AIIR). Pertussis spreads by large respiratory droplets (surgical mask). Scabies spreads by direct contact with skin/linens (gown + gloves).",
 o:["Airborne = TB, measles, varicella/shingles (disseminated). Droplet = pertussis, influenza, meningococcus, rubella, mumps. Contact = scabies, C. difficile, MRSA, draining wounds."],
 s:"Group memorably: Airborne — “Tiny Big V” (TB, measles, varicella); Droplet — “PIMs” (Pertussis, Influenza, Meningococcal, rubella/S); Contact — everything you can touch."},
 ref:"Transmission-based precautions"},

/* ── Health Promotion & Maintenance ─────────────────────────────── */
{id:"HPM-001", t:"single", cn:"HPM", sys:"INF", topic:"Immunizations", d:1, b:-0.25, cj:"analyze", tags:["teaching"],
 stem:"At the 6-month well-child visit, which immunizations does the nurse expect the infant to receive? ",
 opts:["DTaP, Hib, IPV, PCV, and rotavirus","MMR, varicella, and DTaP","Hepatitis B and MMR only","DTaP and MMR only"],
 ans:0,
 rat:{c:"The 6-month schedule includes DTaP, Hib, IPV (polio), PCV (pneumococcal), rotavirus (and seasonal influenza when in season, plus HepB depending on schedule). MMR and varicella are first given at 12–15 months.",
 o:["Correct — the 6-month set is DTaP, Hib, IPV, PCV, rotavirus.","MMR and varicella begin at 12–15 months, not 6 months.","MMR is not given at 6 months.","MMR is not given at 6 months."],
 s:"Anchor ages: 2/4/6 months = DTaP·Hib·IPV·PCV(+rotavirus); 12–15 months = MMR·varicella·PCV booster; HepB = birth, 1–2 mo, 6–18 mo."},
 ref:"CDC childhood immunization schedule"},

{id:"HPM-002", t:"single", cn:"HPM", sys:"MSK", topic:"Growth & development", d:0, b:-1.2, cj:"analyze", tags:["assessment"],
 stem:"The nurse is assessing an 18-month-old toddler at a well-child visit. Which gross motor finding is expected?",
 opts:["Kicks a ball forward without a demonstration","Walks up stairs with one hand held","Builds a tower of six small cubes","Pedals a tricycle along a hallway"],
 ans:1,
 rat:{c:"An 18-month-old can walk well, climb stairs with one hand held, and begin to run stiffly. Kicking a ball forward emerges ~20–24 months, stacking six cubes is a fine-motor (not gross-motor) 18–24 month skill, and pedaling a tricycle appears ~3 years.",
 o:["Kicking a ball forward is a 2-year milestone — close, but just ahead of 18 months.","Correct — climbing stairs with one hand held is an 18-month gross-motor milestone.","Six-cube towers are FINE motor — the stem asks for gross motor.","Pedaling a tricycle is expected around age 3."],
 s:"Gross-motor ladder: 12–15 mo walk → 18 mo stairs w/ help → 2 yr run/both-feet jump → 3 yr tricycle → 4 yr hop → 5 yr skip."},
 ref:"Pediatric developmental milestones"},

{id:"HPM-003", t:"single", cn:"HPM", sys:"GI", topic:"Screening", d:0, b:-1.0, cj:"generate", tags:["teaching"],
 stem:"During a primary care visit, a client with no family history of colorectal cancer asks when colorectal cancer screening should begin. What is the nurse's best response?",
 opts:["At age 40","At age 45","At age 50","Only if symptoms develop"],
 ans:1,
 rat:{c:"Average-risk adults should begin colorectal cancer screening at age 45 (lowered from 50 in current guidelines). Earlier screening applies to higher-risk clients (family history, IBD, hereditary syndromes).",
 o:["40 applies to higher-risk groups (e.g., strong family history), not average risk.","Correct — average-risk screening begins at 45.","50 was the previous threshold; guidance now starts at 45.","Screening is prevention-oriented — waiting for symptoms defeats its purpose."],
 s:"Know the updated threshold (45 for average risk) and the exceptions that pull it earlier."},
 ref:"Colorectal cancer screening guidance"},

{id:"HPM-004", t:"multi", cn:"HPM", sys:"INF", topic:"Prevention levels", d:2, b:0.6, cj:"analyze", tags:["teaching"],
 stem:"The nurse is teaching a community group about disease prevention. Which activities are examples of primary prevention? Select all that apply.",
 opts:["Smoking cessation counseling for a client who has never had cancer","Daily sunscreen use and avoiding tanning beds","Annual mammography for women over 40","Receiving recommended routine immunizations","Blood pressure screening at a health fair"],
 ans:[0,1,3],
 rat:{c:"Primary prevention prevents disease before it occurs (immunizations, healthy lifestyle, injury prevention). Secondary prevention detects disease early (screenings: mammography, blood pressure screening). Tertiary prevention manages existing disease.",
 o:["Correct — preventing disease onset in a healthy person = primary prevention.","Correct — preventing skin cancer before it occurs.","Mammography detects existing disease early = secondary prevention.","Correct — immunization is classic primary prevention.","BP screening detects hypertension early = secondary prevention."],
 s:"Primary = prevent it. Secondary = find it early. Tertiary = limit damage from it. Screenings are almost always secondary."},
 ref:"Levels of prevention"},

/* ── Psychosocial Integrity ─────────────────────────────────────── */
{id:"PSY-001", t:"single", cn:"PSY", sys:"PSYCH", topic:"Therapeutic communication", d:0, b:-1.3, cj:"generate", tags:["communication" ,"assessment"],
 stem:"A preoperative client says, “I'm scared this surgery won't go well.” Which response by the nurse is most therapeutic?",
 opts:["“Don't worry — the surgeon has done this procedure hundreds of times.”","“You seem frightened. Tell me more about your concerns.”","“Everything will be fine; the odds are in your favor.”","“Would you like medication for your anxiety?”"],
 ans:1,
 rat:{c:"This response acknowledges the feeling and uses an open-ended invitation — the two core therapeutic techniques. The others offer false reassurance or jump to a fix.",
 o:["False reassurance dismisses the client's feelings and closes communication.","Correct — name the feeling, then explore with an open-ended prompt.","Again false reassurance plus statistics — non-therapeutic.","Jumping to medication skips exploring the concern; may be appropriate later."],
 s:"When the client expresses a feeling: reflect + open-ended. Eliminate false reassurance, “why” questions, advice-giving, and changing the subject."},
 ref:"Therapeutic communication techniques"},

{id:"PSY-002", t:"single", cn:"PSY", sys:"PSYCH", topic:"Suicide safety", d:1, b:-0.2, cj:"act", tags:["safety","priority"],
 stem:"A client with depression tells the nurse, “Sometimes I think everyone would be better off if I weren't here.” Which response is most appropriate?",
 opts:["“You have so much to live for — your family loves you.”","“Do you have thoughts of killing yourself or a plan to harm yourself?”","“Let's talk about something more positive.”","“These feelings usually pass with treatment.”"],
 ans:1,
 rat:{c:"Direct, non-judgmental screening for suicidal ideation, plan, and means is the priority — asking does not plant the idea. Safety assessment drives the level of observation and precautions.",
 o:["Platitudes minimize the statement and shut down disclosure.","Correct — assess directly for ideation, plan, means, and intent.","Redirecting invalidates the client and misses a safety risk.","Minimizing a potential safety issue is never appropriate."],
 s:"Any hint of self-harm → ask directly about plan/means → then implement safety precautions based on the answer."},
 ref:"Mental health · suicide risk assessment"},

{id:"PSY-003", t:"single", cn:"PSY", sys:"PSYCH", topic:"Grief & coping", d:2, b:0.6, cj:"evaluate", tags:["assessment"],
 stem:"A client whose spouse died 14 months ago tells the hospice nurse, “I keep wishing I had died instead. I can't get out of bed, I've stopped seeing friends, and I still set a place at the table for her every night.” Which interpretation is most accurate?",
 opts:["This is normal grief that will resolve without intervention","This is complicated grief and the client should be referred for professional support","This is a normal grief response showing continued attachment","This suggests the client is ready to move on and needs encouragement"],
 ans:1,
 rat:{c:"Persistent intense grief with functional impairment (can't get out of bed, social withdrawal, wish to die, inability to accept the loss) more than 12 months after the loss indicates complicated grief (prolonged grief disorder) — it warrants referral, not watchful waiting.",
 o:["Functional impairment >1 year is not uncomplicated grief.","Correct — duration >12 months + impairment + death wish = complicated grief → refer.","Continued attachment rituals alone can be normal — the wish to die and impairment are the red flags.","Nothing here signals readiness to move on; the client is stuck."],
 s:"Grief becomes complicated when time (>1 yr) + impairment + hopelessness/wish-to-die persist together. When you see that cluster on the exam, choose referral."},
 ref:"Grief & loss · complicated grief"},

{id:"PSY-004", t:"single", cn:"PSY", sys:"PSYCH", topic:"Substance use", d:2, b:0.8, cj:"prioritize", tags:["priority","assessment"],
 stem:"A client hospitalized after surgery has a history of heavy daily alcohol use. The nurse monitors for withdrawal. Which finding requires immediate intervention?",
 opts:["Mild hand tremors and irritability 6 hours after the last drink","Heart rate 118/min, blood pressure 168/100, diaphoresis, and visual hallucinations","Reports of nausea and poor appetite","Insomnia and restlessness on the second night"],
 ans:1,
 rat:{c:"Severe autonomic hyperactivity (hypertension, tachycardia, diaphoresis) plus hallucinations signals severe withdrawal / impending delirium tremens — a medical emergency requiring immediate provider notification and treatment (typically benzodiazepines per protocol).",
 o:["Mild tremor/irritability is early minor withdrawal — monitor and treat per protocol, but not emergent.","Correct — autonomic instability + hallucinations = severe withdrawal/DT risk → act now.","Nausea/anorexia are common and expected.","Restlessness/insomnia are minor withdrawal features."],
 s:"Alcohol withdrawal escalation: tremors (6–12h) → seizures (12–48h) → DTs/hallucinations (48–96h). Autonomic instability + hallucination = emergency."},
 ref:"Substance use · alcohol withdrawal syndrome"},

/* ── Basic Care & Comfort ───────────────────────────────────────── */
{id:"BCC-001", t:"single", cn:"BCC", sys:"CV", topic:"Nutrition · sodium restriction", d:1, b:-0.4, cj:"generate", tags:["teaching"],
 stem:"The nurse is teaching a client with heart failure about a 2-gram sodium diet. Which lunch selection indicates the teaching was effective?",
 opts:["Ham sandwich with pickle spears and canned soup","Baked chicken breast, plain baked potato, and a fresh orange","Instant noodles with processed cheese","Fast-food burger with French fries"],
 ans:1,
 rat:{c:"Fresh plain proteins, plain starches, and fresh produce are naturally low in sodium. Processed, cured, canned, instant, and fast foods are the major sodium sources to eliminate.",
 o:["Ham (cured), pickles (brined), and canned soup are among the highest-sodium foods available.","Correct — all components are naturally low in sodium.","Instant noodles + processed cheese = very high sodium.","Fast food is notoriously sodium-dense."],
 s:"Sodium rule for HF: fresh is best; avoid anything cured, canned, instant, brined, or from a drive-through."},
 ref:"Nutrition · therapeutic diets"},

{id:"BCC-002", t:"single", cn:"BCC", sys:"MSK", topic:"Pain management", d:0, b:-1.25, cj:"act", tags:["medication","teaching"],
 stem:"A client with chronic cancer pain reports persistent pain between doses of prescribed PRN opioid analgesics. Which action is best?",
 opts:["Instruct the client to take the analgesics only when the pain becomes severe","Collaborate with the provider to administer analgesics on a scheduled (around-the-clock) basis","Tell the client to double the PRN dose independently","Switch to nonpharmacologic measures only"],
 ans:1,
 rat:{c:"Persistent chronic pain is best controlled with scheduled, around-the-clock dosing, keeping levels steady and preventing pain crises; PRN dosing for breakthrough pain supplements the schedule.",
 o:["Waiting for severe pain undermines control — treating pain early requires less total medication.","Correct — scheduled dosing for persistent pain plus PRN for breakthrough.","Clients must never self-adjust prescribed opioid doses — unsafe and illegal teaching.","Nonpharmacologic measures complement but do not replace adequate analgesia for cancer pain."],
 s:"Chronic/persistent pain → scheduled ATC dosing (+ PRN breakthrough). Acute pain → PRN is acceptable. Never “wait until severe.”"},
 ref:"Pain management principles"},

{id:"BCC-003", t:"single", cn:"BCC", sys:"GI", topic:"Nutrition · fiber", d:0, b:-1.15, cj:"generate", tags:["teaching"],
 stem:"The nurse is helping a client with chronic constipation choose high-fiber foods. Which selection is best?",
 opts:["White rice and cheese omelet","Oatmeal with raspberries and a pear","Clear broth and white toast","Boiled eggs and applesauce"],
 ans:1,
 rat:{c:"Oats, raspberries, pears (with skin), beans, whole grains, and vegetables are high-fiber choices; white rice, cheese, broth, eggs, and applesauce are low-residue/low-fiber.",
 o:["White rice and cheese slow transit — low fiber, and cheese can worsen constipation.","Correct — oats + berries + pear = high fiber (plus fluids should be encouraged).","Clear broth and white toast are low-residue (used for acute GI upset, not constipation).","Eggs and applesauce contain little fiber."],
 s:"High fiber on the exam: oats, bran, beans, berries, pears, whole grains, legumes. Pair teaching with “increase fluids” — fiber without water worsens constipation."},
 ref:"Nutrition · fiber in constipation management"},

{id:"BCC-004", t:"single", cn:"BCC", sys:"NEURO", topic:"Assistive devices", d:2, b:0.65, cj:"evaluate", tags:["safety","teaching"],
 stem:"A client with left-sided weakness from a stroke is learning to use a cane. Which observation indicates correct cane use?",
 opts:["Leans body weight onto the weak left side while holding the cane still","Holds the cane in the right hand and moves the cane forward together with the left leg","Keeps the cane stationary while stepping with the right leg","Carries the cane to favor the strong side while walking without it"],
 ans:1,
 rat:{c:"The cane is held on the STRONG side and advanced TOGETHER with the WEAK leg, widening the base and unloading the affected side: cane + weak leg, then strong leg.",
 o:["The cane belongs in the strong (right) hand, not the weak side.","Correct — cane in strong hand, advanced with the weak leg.","The cane must move with the gait pattern, not stay planted.","Skipping the assistive device defeats its purpose and increases fall risk."],
 s:"Cane mnemonic: “the cane goes with the weak.” Strong hand holds it; cane + weak leg move together; then the strong leg steps through."},
 ref:"Mobility · assistive devices"},

/* ── Pharmacological & Parenteral Therapies ─────────────────────── */
{id:"PHA-001", t:"single", cn:"PHA", sys:"CV", topic:"Digoxin", d:1, b:-0.45, cj:"act", tags:["medication","priority","assessment"],
 stem:"Before administering the daily dose of digoxin, the nurse counts the client's apical pulse at 54/min and irregular. Which action is most appropriate?",
 opts:["Administer the dose since this matches the client's usual resting rate","Withhold the dose and notify the healthcare provider","Administer half the dose and reassess in 30 minutes","Administer the dose and monitor for yellow-tinged vision"],
 ans:1,
 rat:{c:"For digoxin, an apical rate below 60/min (adult) is a hold parameter — bradycardia may signal toxicity, especially with an irregular rhythm. Withhold and notify the provider.",
 o:["A rate this low with a NEW irregularity is not baseline — the hold parameter exists precisely for this moment.","Correct — hold (<60) and notify; also consider a serum level if toxicity signs exist.","Nurses do not alter doses independently.","Yellow vision monitoring matters for toxicity, but it does not address whether to give a bradycardic dose now."],
 s:"Digoxin gate: count apical pulse for a full 60 seconds; <60 adult (or <90–110 infant per protocol) → hold + notify."},
 ref:"High-alert medication · cardiac glycosides"},

{id:"PHA-002", t:"multi", cn:"PHA", sys:"CV", topic:"Digoxin toxicity", d:1, b:-0.25, cj:"recognize", tags:["medication","assessment"], variantGroup:"digoxin-toxicity",
 stem:"A client taking digoxin is suspected of toxicity. Which findings support this? Select all that apply.",
 opts:["Anorexia and nausea","Seeing halos around lights","Heart rate 48/min","Blood pressure 168/95","Fatigue and confusion"],
 ans:[0,1,2,4],
 rat:{c:"Digoxin toxicity presents with GI effects (anorexia, nausea, vomiting), visual disturbances (halos, yellow-tinged vision), neurologic effects (fatigue, confusion), and bradydysrhythmias. Hypokalemia, hypercalcemia, and renal impairment increase risk.",
 o:["Correct — classic GI toxicity sign.","Correct — halos are the signature visual disturbance.","Correct — bradycardia/dysrhythmias are the dangerous cardiac signs.","Hypertension is not a hallmark of digoxin toxicity.","Correct — neurologic toxicity symptoms."],
 s:"Toxicity cluster “GIVE-UP Brady”: GI upset, Inc vision halos, Veiled confusion, Electrolyte risk (low K+), Pulse slow. Check K+ and renal function."},
 ref:"Medication safety · digoxin toxicity"},

{id:"PHA-003", t:"single", cn:"PHA", sys:"HEME", topic:"Anticoagulation", d:2, b:0.7, cj:"act", tags:["medication","priority","calculation"], variantGroup:"warfarin-inr",
 stem:"A client on warfarin for atrial fibrillation has a routine INR of 5.5 and no visible bleeding. Which provider order should the nurse anticipate?",
 opts:["Continue the same warfarin dose and recheck in one week","Hold the next dose(s) of warfarin and monitor more frequently","Administer protamine sulfate IV push","Initiate a heparin infusion"],
 ans:1,
 rat:{c:"INR 5.5 without bleeding = supratherapeutic. Standard management is holding warfarin (with or without a small dose of oral vitamin K depending on level/risk) and monitoring closely — per provider order.",
 o:["Continuing an excessive anticoagulation level invites bleeding.","Correct — hold and anticipate possible low-dose oral vitamin K with closer INR monitoring.","Protamine reverses heparin, not warfarin.","Adding heparin would increase anticoagulation — the opposite of what is needed."],
 s:"INR triage: therapeutic 2–3 (AF) → continue; mildly high, no bleeding → hold ± oral vitamin K; major bleeding → IV vitamin K + 4-factor PCC. Protamine = heparin antidote."},
 ref:"Anticoagulant therapy & monitoring"},

{id:"PHA-004", t:"single", cn:"PHA", sys:"ENDO", topic:"Hypoglycemia", d:0, b:-1.3, cj:"act", tags:["medication","priority","intervention"], variantGroup:"hypoglycemia-15g",
 stem:"A client with type 1 diabetes becomes diaphoretic, shaky, and confused (blood glucose 48 mg/dL). Which action should the nurse take first?",
 opts:["Administer 15 g of a fast-acting carbohydrate","Give the scheduled morning insulin dose","Recheck the glucose in 1 hour","Insert an IV and draw labs"],
 ans:0,
 rat:{c:"This is hypoglycemia (<70 mg/dL) with neurologic symptoms — treat immediately with 15 g fast-acting carbohydrate (juice, glucose tablets) if the client can swallow; recheck in 15 minutes (15/15 rule).",
 o:["Correct — fast sugar first; recheck in 15 min.","More insulin would deepen the hypoglycemia — dangerous.","Waiting an hour delays treatment of a brain-starved client.","No time for IV access workup first — oral fast carbohydrate now (IV D50 if NPO/unconscious)."],
 s:"Shaky+sweaty+confused+glucose <70 = treat now: 15 g fast carbs, recheck 15 min. Unconscious/NPO → glucagon IM or IV D50."},
 ref:"Insulin therapy & hypoglycemia protocol"},

{id:"PHA-005", t:"drag", cn:"PHA", sys:"ENDO", topic:"Insulin", d:1, b:-0.2, cj:"analyze", tags:["medication"],
 stem:"The nurse is reviewing insulin types. Assign each insulin to the correct position when ordered from SHORTEST to LONGEST duration of action.",
 drag:{targets:["1 — Shortest","2","3","4 — Longest"],
  opts:["Insulin lispro (rapid-acting)","Regular insulin (short-acting)","NPH insulin (intermediate-acting)","Insulin glargine (long-acting)"],
  ans:[0,1,2,3]},
 rat:{c:"Duration ranking: lispro ~3–5 h → regular ~6–8 h → NPH ~10–18 h → glargine ~24 h with no peak.",
 o:["Lispro: onset ~15 min, no peak misuse with meals.","Regular: onset 30–60 min, duration 6–8 h — the only clear (drawn first when mixing).","NPH: cloudy, intermediate, peaks 4–12 h.","Glargine: peakless, 24 h — never mix with other insulins."],
 s:"Rapid (lispro/aspart) covers meals; Regular is the only clear-drawn-first insulin when mixing; NPH is cloudy; glargine/detemir are once-daily basals — never mix glargine."},
 ref:"Insulin pharmacology"},

{id:"PHA-006", t:"single", cn:"PHA", sys:"INF", topic:"Dosage calculation", d:1, b:-0.15, cj:"act", tags:["calculation","medication"],
 stem:"A child weighing 18 kg is prescribed amoxicillin 25 mg/kg/day PO divided every 12 hours. The suspension is 250 mg/5 mL. How many mL should the nurse administer per dose? (Round to the nearest tenth.)",
 opts:["2.3 mL","4.5 mL","9.0 mL","5.4 mL"],
 ans:1,
 rat:{c:"25 mg × 18 kg = 450 mg/day → 450 ÷ 2 doses = 225 mg/dose → 225 mg ÷ (250 mg/5 mL = 50 mg/mL) = 4.5 mL.",
 o:["2.3 mL would underdose (that's ~115 mg — half a dose).","Correct — 225 mg per dose at 50 mg/mL = 4.5 mL.","9.0 mL would be the entire day's dose twice a day — double-dosing.","5.4 mL ≈ 270 mg — does not match the calculation."],
 s:"Calculation ladder: mg/kg → per-day total → ÷ doses per day → ÷ concentration. Use the on-screen calculator; write each step down."},
 ref:"Pediatric dosage calculation"},

{id:"PHA-007", t:"single", cn:"PHA", sys:"REN", topic:"IV therapy", d:1, b:-0.55, cj:"act", tags:["calculation","intervention"],
 stem:"The provider orders 1,000 mL of 0.9% sodium chloride to infuse over 8 hours. The nurse sets the infusion pump to deliver how many mL per hour?",
 opts:["100 mL/hr","125 mL/hr","150 mL/hr","80 mL/hr"],
 ans:1,
 rat:{c:"1,000 mL ÷ 8 h = 125 mL/hr.",
 o:["100 mL/hr would take 10 hours.","Correct — volume ÷ hours = rate.","150 mL/hr would finish in ~6.7 hours.","80 mL/hr would take 12.5 hours."],
 s:"Pump rate = total volume ÷ total hours. For gtt/min: volume × drop factor ÷ minutes."},
 ref:"IV flow rate calculation"},

/* ── Reduction of Risk Potential ────────────────────────────────── */
{id:"RRP-001", t:"single", cn:"RRP", sys:"RESP", topic:"Postoperative complications", d:2, b:0.85, cj:"act", tags:["priority","assessment"], variantGroup:"pe-postop",
 stem:"On the first postoperative day after hip surgery, a client suddenly develops dyspnea, tachycardia, and sharp chest pain. Which action should the nurse take first?",
 opts:["Roll the client onto the side and elevate the legs","Apply oxygen and notify the rapid response team","Auscultate bowel sounds and palpate the abdomen","Administer the prescribed oral analgesic"],
 ans:1,
 rat:{c:"Sudden dyspnea + tachycardia + pleuritic chest pain postoperatively suggests pulmonary embolism — an ABC emergency. Apply oxygen immediately and escalate while keeping the client calm and still.",
 o:["No indication for shock positioning; movement could dislodge further clot.","Correct — oxygen first (ABC), then rapid escalation.","GI assessment is irrelevant to this presentation.","Pain medication neither addresses the hypoxia nor is it first for suspected PE."],
 s:"Postop sudden dyspnea = PE until proven otherwise → O2 first (ABC), then HCP/rapid response, positioning, and anticipate V/Q or CT angiography."},
 ref:"Postoperative complications · venous thromboembolism"},

{id:"RRP-002", t:"single", cn:"RRP", sys:"RESP", topic:"Chest tubes", d:2, b:0.8, cj:"act", tags:["safety","intervention"],
 stem:"A client's chest tube becomes accidentally disconnected from the drainage tubing. Which action should the nurse take immediately?",
 opts:["Clamp the chest tube immediately","Place the end of the chest tube in a bottle of sterile water","Apply an occlusive petroleum gauze dressing over the insertion site","Reattach the tube after wiping both ends with alcohol"],
 ans:1,
 rat:{c:"Disconnect at the tube junction risks air entering the pleural space. Immediate action: submerge the disconnected end in sterile water to create a water seal while preparing to re-establish a sterile connection. (Clamping is done briefly only to check for an air leak and can cause a tension pneumothorax if continued.)",
 o:["Clamping can cause a tension pneumothorax — not the immediate response to disconnection.","Correct — sterile water seal prevents air entry.","Petroleum gauze is for an open chest wound at the site, not tubing disconnection.","Field reconnection without sterile technique risks infection; the water seal is the interim safety step."],
 s:"Chest tube emergencies: disconnected tubing → sterile water; system cracks → submerge; accidental removal → petroleum gauze taped on 3 sides; persistent bubbling → check for leaks; never clamp persistently."},
 ref:"Chest tube management · emergency actions"},

{id:"RRP-003", t:"single", cn:"RRP", sys:"CV", topic:"Laboratory values", d:1, b:-0.3, cj:"analyze", tags:["assessment","priority"],
 stem:"The nurse reviews the following morning laboratory results. Which finding requires reporting to the provider first?",
 opts:["Sodium 136 mEq/L","Potassium 2.9 mEq/L","Hemoglobin 11.2 g/dL","Platelets 148,000/mm³"],
 ans:1,
 rat:{c:"K+ 2.9 mEq/L is significantly below range (3.5–5.0) and can cause life-threatening dysrhythmias and muscle weakness — it needs prompt reporting and replacement. The other values are near-normal.",
 o:["136 mEq/L is within normal range (135–145).","Correct — hypokalemia with dysrhythmia risk is the priority.","11.2 g/dL is mild anemia — monitor, not urgent.","148,000 is just below 150k — mild thrombocytopenia, not the priority."],
 s:"Lab priority triage: K+ abnormalities and gas exchanges outrun mild anemia or borderline counts. Know normal ranges cold: K 3.5–5.0, Na 135–145, Hgb ♀12–16/♂14–18, Plt 150–400k."},
 ref:"Diagnostic testing · critical laboratory values"},

{id:"RRP-004", t:"hotspot", cn:"RRP", sys:"CV", topic:"Vital sign trends", d:2, b:0.75, cj:"recognize", tags:["assessment"],
 stem:"Review the nurse's mid-shift assessment notes below. Tap to highlight each row that indicates a finding requiring immediate follow-up.",
 hotspot:{mode:"rows",
  rows:["Alert, oriented, converses in full sentences","Heart rate 118/min, irregular","Blood pressure 92/56 mm Hg (was 132/78 on admission)","Breath sounds: crackles in both lower lobes","Reports pain 2/10 at the incision site","Urine output 20 mL over the past 2 hours"],
  ans:[1,2,3,5]},
 rat:{c:"Tachycardia with a new irregular rhythm, a falling blood pressure, new bilateral crackles (possible fluid overload/heart failure), and oliguria (end-organ perfusion) all demand immediate follow-up. Mild incisional pain and being alert are expected findings.",
 o:["Expected/acceptable finding — no action.","Follow-up: new tachydysrhythmia.","Follow-up: significant hypotensive trend.","Follow-up: new adventitious sounds = fluid shift.","2/10 postop pain is expected and not urgent.","Follow-up: <30 mL/hr suggests poor renal perfusion."],
 s:"Highlight tasks: hunt for CHANGE (trends), ABC threats (rate, rhythm, airway, breath sounds), and perfusion markers (BP, urine output). Expected findings are distractors."},
 ref:"Vital sign trends & nurse's notes"},

{id:"RRP-005", t:"single", cn:"RRP", sys:"GI", topic:"Enteral tubes", d:1, b:-0.35, cj:"act", tags:["safety","intervention"],
 stem:"Before the first feeding through a newly placed nasogastric tube, which method is most reliable for verifying tube placement?",
 opts:["Auscultating a whoosh of air over the stomach","Testing the pH of aspirated gastric secretions","Obtaining an abdominal x-ray","Checking for bubbles when the tip is placed in water"],
 ans:2,
 rat:{c:"Radiographic confirmation (abdominal x-ray) is the gold standard for verifying NG tube placement before the first feeding. pH testing (≤5.5) is an acceptable ongoing bedside check; auscultation is unreliable and no longer recommended.",
 o:["The whoosh test can be misleading (air transmitted to the bowel) — unreliable and unsafe alone.","pH is useful for ongoing checks after initial confirmation, but x-ray is the most reliable.","Correct — direct visualization of tube tip position.","This bubble technique is outdated and unreliable."],
 s:"First feeding → x-ray confirmation. Ongoing checks → pH of aspirate. Never rely on auscultation alone."},
 ref:"Enteral tube management · placement verification"},

/* ── Physiological Adaptation ───────────────────────────────────── */
{id:"PAA-001", t:"single", cn:"PAA", sys:"ENDO", topic:"DKA", d:2, b:0.9, cj:"act", tags:["priority","medication"], variantGroup:"dka",
 stem:"An adolescent arrives with diabetic ketoacidosis: glucose 540 mg/dL, pH 7.20, deep rapid respirations, and dry mucous membranes. Which provider order should the nurse implement first?",
 opts:["Insert an indwelling urinary catheter","Begin the prescribed IV fluid replacement","Administer the prescribed rapid-acting insulin subcutaneously","Administer sodium bicarbonate IV"],
 ans:1,
 rat:{c:"In DKA, fluid deficits kill first: start IV isotonic fluids to restore intravascular volume before (or concurrently with) insulin — insulin given to a volume-depleted client drives further vascular collapse and dangerous shifts. Insulin follows fluids; bicarbonate is rarely used.",
 o:["Monitoring output matters but follows stabilization.","Correct — fluid resuscitation first, then insulin infusion.","Initial insulin in DKA is IV (in the fluid), not subcutaneous — poor absorption when dehydrated.","Bicarbonate is reserved for extreme acidosis (pH <6.9) — not first."],
 s:"DKA sequence on the exam: FLUIDS → insulin (IV) → K+ replacement (once urine output/K permits) → glucose monitoring. Never potassium into an anuric/peaked-T client."},
 ref:"Endocrine emergencies · DKA management"},

{id:"PAA-002", t:"single", cn:"PAA", sys:"NEURO", topic:"Stroke", d:2, b:0.8, cj:"act", tags:["priority","assessment"],
 stem:"A client is brought to the emergency department with sudden right-sided weakness and slurred speech that began 40 minutes ago. Which action should the nurse perform first?",
 opts:["Obtain a computed tomography (CT) scan of the head","Check the client's blood glucose level","Administer prescribed aspirin","Start two large-bore IV lines"],
 ans:1,
 rat:{c:"Bedside blood glucose is the immediate first step for a suspected stroke: hypoglycemia mimics stroke and is instantly reversible — it must be excluded before activating the stroke pathway (then CT to rule out hemorrhage before thrombolytics).",
 o:["CT follows glucose check and stroke activation — you must exclude the mimic first.","Correct — hypoglycemia is a stroke mimic; check glucose immediately.","Aspirin comes after hemorrhage is excluded by imaging.","IV access is needed but does not outrank excluding hypoglycemia."],
 s:"Stroke order: glucose (mimic check) → CT (bleed?) → weigh thrombolytics (within window) — glucose is the 30-second step you do first."},
 ref:"Acute stroke protocol"},

{id:"PAA-003", t:"emr", cn:"PAA", sys:"RESP", topic:"COPD", d:1, b:-0.2, cj:"recognize", tags:["assessment","priority"],
 stem:"A client with COPD is admitted with increased dyspnea. Which assessment findings require immediate follow-up? Select all that apply in each group.",
 groups:[
  {h:"Respiratory status", opts:["Oxygen saturation 88% on room air","Respiratory rate 28/min with accessory muscle use","Occasional dry cough in the morning","Speaking in 3–4 word phrases"], ans:[0,1,3]},
  {h:"Other findings", opts:["Fine tremor of both hands (new)","Uses pursed-lip breathing as taught","Barrel chest appearance","Productive green sputum (change from baseline)"], ans:[0,3]}],
 rat:{c:"Hypoxemia, tachypnea with accessory muscles, short speech (work of breathing), a NEW tremor (possible hypercapnia/β-agonist effect), and a change in sputum color (infection) all require follow-up. Chronic stable findings (pursed-lip breathing, barrel chest) and a mild morning cough are expected with COPD.",
 o:["SpO2 88% → hypoxemia: follow up now.","RR 28 + accessory muscles → impending fatigue: follow up.","Expected for COPD — distractor.","3–4 word phrases → severe work of breathing: follow up.","New tremor is a change from baseline: follow up.","Taught technique working as intended — distractor.","Chronic hyperinflation appearance — expected.","Sputum change suggests infection: follow up."],
 s:"NGN “select findings” logic: flag CHANGE from baseline and ABC threats; expected chronic adaptations are the distractors."},
 ref:"COPD exacerbation assessment"},

{id:"PAA-004", t:"single", cn:"PAA", sys:"CV", topic:"Shock", d:2, b:0.95, cj:"analyze", tags:["assessment","priority"],
 stem:"Which assessment finding best indicates the EARLY (compensated) stage of hypovolemic shock in an adult?",
 opts:["Widened pulse pressure","Narrowed pulse pressure with tachycardia","Bradycardia with hypertension","Bilateral crackles and jugular vein distention"],
 ans:1,
 rat:{c:"In compensated shock, baroreceptors drive tachycardia and vasoconstriction — the diastolic pressure rises, narrowing the pulse pressure (systolic − diastolic) before blood pressure itself falls. By the time BP drops, decompensation has begun.",
 o:["Widened pulse pressure is not a compensated-shock pattern.","Correct — narrowed pulse pressure + tachycardia is the classic early sign.","Bradycardia suggests the late, decompensated (or non-shock) pattern.","Crackles + JVD indicate fluid overload/cardiac issues, not hypovolemia."],
 s:"Early shock = body compensating: ↑HR, ↑RR, normal BP, narrowing pulse pressure, cool pale skin, ↓ urine output. Waiting for hypotension = too late."},
 ref:"Shock stages · compensation physiology"},

{id:"PAA-005", t:"single", cn:"PAA", sys:"NEURO", topic:"Increased ICP", d:1, b:-0.25, cj:"act", tags:["priority","intervention","safety"],
 stem:"A client with a head injury shows early signs of increased intracranial pressure. Which positioning should the nurse use?",
 opts:["Flat and supine","Head of the bed elevated 30 degrees with the head in neutral alignment","Trendelenburg position","Side-lying with the head turned to the side"],
 ans:1,
 rat:{c:"Elevating the head of the bed ~30° with neutral head alignment promotes venous drainage from the brain and lowers ICP without compromising cerebral perfusion.",
 o:["Flat positioning increases intracranial venous pressure.","Correct — 30° + neutral neck = optimal venous drainage.","Trendelenburg markedly increases ICP.","Head rotation can impede jugular venous outflow."],
 s:"ICP first-aid positioning: HOB 30°, neck neutral, avoid hip flexion, clustering care, and Valsalva. Watch for Cushing triad (↑BP with widening pulse pressure, bradycardia, irregular respirations)."},
 ref:"Intracranial pressure management"},

{id:"PAA-006", t:"single", cn:"PAA", sys:"CV", topic:"Fluid overload", d:1, b:-0.35, cj:"act", tags:["priority","intervention"],
 stem:"A client with heart failure reports sudden worsening dyspnea. The nurse notes bilateral crackles, an oxygen saturation of 88%, and respirations 30/min. Which action should the nurse take first?",
 opts:["Place the client in a high-Fowler position and apply the prescribed oxygen","Obtain a daily weight while the client continues the current oxygen setting","Restrict the client's oral sodium intake","Administer the prescribed diuretic"],
 ans:0,
 rat:{c:"Acute pulmonary congestion is an ABC emergency: sit the client upright (high-Fowler drops venous return to the lungs) and apply prescribed oxygen first, then diuresis.",
 o:["Correct — positioning + oxygen address airway/breathing immediately.","Daily weight is monitoring, not acute treatment.","Diet education is important later.","The diuretic follows immediate positioning + O2."],
 s:"Fluid overload acute episode: POSITION (high-Fowler) → OXYGEN → then diuresis/medications. ABCs always outrank meds and monitoring."},
 ref:"Heart failure · acute decompensation"}
];
