"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 35) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 34: MOC (17.6% vs 18),
 * PSY (8.9% vs 9), PHA (15.7% vs 16), RRP (11.9% vs 12) and
 * PAA (13.6% vs 14). Every item is difficulty 2 or 3, and the
 * clinical detail is written to be defensible.
 *
 * MOC 5: Gillick competence and a 15-year-old seeking contraception,
 * lasting power of attorney for health and welfare, deprivation of
 * liberty safeguards, a best-interests decision for a client lacking
 * capacity, and court involvement when parents refuse treatment.
 * PSY 5: removing a ligature point, responding to a client who
 * absconds, a transitional object in a hospitalised toddler,
 * somatisation, and identifying defence mechanisms.
 * RRP 4: distinguishing transfusion-associated circulatory overload
 * from TRALI, cryoprecipitate for low fibrinogen, thoracostomy drain
 * management, and the first action in a transfusion reaction.
 * PAA 3: irradiated blood products, tranexamic acid, and factor
 * concentrate.
 * PHA 3: apixaban reversal, dabigatran reversal, and rivaroxaban
 * reversal.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- PSY 5 */
{id:"PSY-088", t:"single", cn:"PSY", sys:"PSYCH", topic:"Ligature risk removal on an inpatient psychiatric unit", d:3, b:0.55, cj:"act", tags:["psych","safety","ligature","observation"],
 stem:"A nurse on an inpatient psychiatric unit finds a client who has fashioned a ligature point from bed linens and a door hinge. The client is distressed but not currently attempting self-harm. Which action by the nurse is the priority?",
 opts:["Remove the ligature point immediately and place the client on continuous one-to-one observation","Document the incident and increase observations to every fifteen minutes","Ask the client to remove the ligature point voluntarily as part of the safety plan","Call security to restrain the client until the ligature point can be removed"],
 ans:0, rat:{c:"A ligature point is an immediate physical risk that must be removed at once, and a client who has created one needs continuous one-to-one observation rather than intermittent checks. Asking the client to remove it leaves the risk in place, and restraint is not indicated when the client is not actively attempting self-harm.", s:"Ligature risk assessment and removal is a core psychiatric nursing responsibility; the response combines environmental safety with observation level."}},
{id:"PSY-089", t:"single", cn:"PSY", sys:"PSYCH", topic:"Response to a client who absconds from an inpatient unit", d:3, b:0.55, cj:"act", tags:["psych","absconding","safety","documentation"],
 stem:"A client admitted voluntarily to an inpatient psychiatric unit leaves the ward without informing staff. Which action by the nurse is the priority?",
 opts:["Search the immediate area and notify the duty manager and clinical team immediately","Wait thirty minutes in case the client returns voluntarily","Contact the client's family to ask if they know where the client has gone","Document the absence and continue routine ward duties"],
 ans:0, rat:{c:"A client who absconds is at immediate risk and requires an urgent search of the immediate area together with immediate notification of the duty manager and clinical team. Waiting, contacting family first, or continuing routine duties delays the response and increases risk.", s:"Absconding is a psychiatric emergency; the response follows local policy but always begins with an immediate search and escalation."}},
{id:"PSY-090", t:"single", cn:"PSY", sys:"PSYCH", topic:"Transitional object in a hospitalised toddler", d:2, b:0.45, cj:"act", tags:["psych","paediatric","transitional object","separation anxiety"],
 stem:"A two-year-old is admitted to hospital for investigation of recurrent seizures. The child becomes extremely distressed when separated from a small blanket carried from home. The ward routine does not permit personal items in the cot. Which action by the nurse is most appropriate?",
 opts:["Allow the blanket to stay with the child, since it provides comfort and reduces separation anxiety","Remove the blanket, since ward routine prohibits personal items in the cot","Wash the blanket before allowing it back, since infection control takes priority","Give the child a hospital toy instead, since it is easier to clean"],
 ans:0, rat:{c:"A transitional object provides significant emotional security for a young child in an unfamiliar environment and should be allowed to stay. Ward routine should be adapted to the child's needs, not the reverse. Washing or replacing it removes the source of comfort at a time of maximum distress.", s:"Transitional objects are a recognised paediatric nursing intervention for separation anxiety and should be accommodated within infection control limits."}},
{id:"PSY-091", t:"single", cn:"PSY", sys:"PSYCH", topic:"Somatisation as a presentation of psychological distress", d:3, b:0.55, cj:"analyze", tags:["psych","somatisation","assessment","psychosomatic"],
 stem:"A 38-year-old presents to a primary care clinic with multiple physical complaints including headache, abdominal pain, and fatigue. Extensive investigation over the past year has found no organic cause. The client becomes defensive when psychological factors are mentioned. Which interpretation by the nurse is most accurate?",
 opts:["The symptoms are a physical expression of psychological distress and require both physical and psychological assessment","The client is malingering to obtain secondary gain such as time off work, with no psychological component","The symptoms are imaginary and require no further investigation","The client has a rare undiagnosed physical condition requiring specialist referral"],
 ans:0, rat:{c:"Somatisation is the physical expression of psychological distress; the symptoms are real to the client and require a combined physical and psychological approach. Malingering involves conscious fabrication for gain, which is not suggested here. Dismissing the symptoms or assuming a rare diagnosis both fail the client.", s:"Somatisation is common in primary care; the nurse's role is to validate the symptoms while exploring psychological contributors without confrontation."}},
{id:"PSY-092", t:"single", cn:"PSY", sys:"PSYCH", topic:"Identifying defence mechanisms in clinical practice", d:2, b:0.45, cj:"analyze", tags:["psych","defence mechanisms","sublimation","rationalisation"],
 stem:"A nurse observes a colleague who has recently been passed over for promotion. The colleague begins training for a marathon and says, 'At least I have more time for my health now.' Which defence mechanism is the colleague most clearly using?",
 opts:["Sublimation, since the colleague is channelling disappointment into a socially acceptable activity","Rationalisation, since the colleague is making excuses for the disappointment","Projection, since the colleague is attributing their own feelings to others","Denial, since the colleague is refusing to acknowledge the disappointment"],
 ans:0, rat:{c:"Sublimation is the channelling of unacceptable impulses or disappointment into socially acceptable activities. Rationalisation involves making excuses, projection involves attributing one's own feelings to others, and denial involves refusing to acknowledge reality. The colleague's response is adaptive sublimation.", s:"Defence mechanism identification is a core psychiatric nursing competency; sublimation is considered a mature and adaptive mechanism."}},

/* ---------------------------------------------------------- MOC 5 */
{id:"MOC-181", t:"single", cn:"MOC", sys:"INTG", topic:"Gillick competence and a minor seeking contraception", d:3, b:0.55, cj:"analyze", tags:["management","consent","Gillick","minor","confidentiality"],
 stem:"A 15-year-old attends a sexual health clinic alone and requests contraception. She asks that her parents not be informed. She demonstrates understanding of the treatment, its risks, and the alternatives. Which action by the nurse is most appropriate?",
 opts:["Provide contraception and maintain confidentiality, since the client is Gillick competent","Refuse treatment until a parent or guardian gives consent","Provide contraception but inform the parents, since the client is under 16","Refer the client to social services, since parental involvement is a safeguarding concern"],
 ans:0, rat:{c:"A minor under 16 who demonstrates sufficient understanding and intelligence to make an informed decision is Gillick competent and may consent to treatment without parental involvement. Confidentiality should be maintained unless there is a safeguarding concern, which is not indicated here.", s:"Gillick competence is a legal principle allowing minors to consent to treatment when they demonstrate sufficient understanding; it applies to contraception and other treatments."}},
{id:"MOC-182", t:"single", cn:"MOC", sys:"INTG", topic:"Lasting power of attorney for health and welfare", d:3, b:0.55, cj:"analyze", tags:["management","LPA","capacity","decision-making"],
 stem:"A 72-year-old client with early dementia has appointed their daughter as attorney under a lasting power of attorney for health and welfare. The client currently retains capacity to make decisions about their own care. The daughter asks the nurse to make all decisions on the client's behalf. Which response by the nurse is most appropriate?",
 opts:["Explain that the lasting power of attorney applies only when the client lacks capacity, so the client's own decisions stand","Allow the daughter to make decisions, since she holds lasting power of attorney and the client lacks capacity to decide alone","Ask the daughter to provide written confirmation that she wishes to take over decision-making","Refer the matter to the Court of Protection, since the arrangement is unclear"],
 ans:0, rat:{c:"A lasting power of attorney for health and welfare applies only when the donor lacks capacity to make the decision in question. While the client retains capacity, their own decisions stand regardless of the attorney's wishes. The attorney does not override the client's autonomy.", s:"Understanding when an LPA activates is essential; it is not a general power to make decisions while the donor has capacity."}},
{id:"MOC-183", t:"single", cn:"MOC", sys:"INTG", topic:"Deprivation of liberty safeguards", d:3, b:0.55, cj:"analyze", tags:["management","DoLS","capacity","liberty"],
 stem:"An 80-year-old client with advanced dementia is in a care home. The client is under continuous supervision and control and is not free to leave. The client lacks capacity to consent to these arrangements. Which action by the nurse is most appropriate?",
 opts:["Ensure a deprivation of liberty safeguards authorisation is in place, since the arrangements amount to a deprivation of liberty","Continue the arrangements, since they are in the client's best interests","Ask the client's family to consent to the arrangements on the client's behalf","Move the client to a less restrictive setting, since deprivation of liberty should be avoided"],
 ans:0, rat:{c:"Continuous supervision and control plus not being free to leave constitutes a deprivation of liberty. When the person lacks capacity to consent, a deprivation of liberty safeguards authorisation is required to make the arrangements lawful. Family consent is not sufficient, and best interests alone do not authorise deprivation of liberty.", s:"DoLS authorisations protect the rights of people lacking capacity who are deprived of liberty; they are a legal requirement, not optional."}},
{id:"MOC-184", t:"single", cn:"MOC", sys:"INTG", topic:"Best-interests decision for a client lacking capacity", d:3, b:0.55, cj:"act", tags:["management","capacity","best interests","decision-making"],
 stem:"A 65-year-old client with severe learning disabilities lacks capacity to consent to a proposed surgical procedure. The client's family is divided about whether to proceed. Which action by the nurse is most appropriate?",
 opts:["Hold a best-interests meeting involving the multidisciplinary team and family to reach a decision","Allow the majority of the family to decide, since they know the client best","Proceed with the procedure, since it is clinically indicated","Postpone the procedure indefinitely, since there is no clear consensus"],
 ans:0, rat:{c:"When a person lacks capacity, decisions must be made in their best interests following a structured process that involves the multidisciplinary team, family, and anyone else with an interest in the person's welfare. Majority family opinion, clinical indication alone, or indefinite postponement all fail to follow the legal best-interests framework.", s:"Best-interests decisions follow a statutory checklist and must be documented; they are not made by majority vote or clinical judgement alone."}},
{id:"MOC-185", t:"single", cn:"MOC", sys:"INTG", topic:"Court involvement when parents refuse treatment for a child", d:3, b:0.55, cj:"act", tags:["management","court","parental refusal","child"],
 stem:"A 10-year-old requires urgent chemotherapy for leukaemia. The parents refuse consent on religious grounds. The clinical team believes treatment is in the child's best interests. Which action by the nurse is most appropriate?",
 opts:["Support the clinical team in applying to the court for authority to treat, since the child's welfare is paramount","Respect the parents' decision, since they have parental responsibility","Proceed with treatment without consent, since the clinical team considers it life-saving","Delay treatment until the child is old enough to make their own decision"],
 ans:0, rat:{c:"When parents refuse life-saving treatment for a child and the clinical team believes treatment is in the child's best interests, the court can override parental refusal. The child's welfare is the paramount consideration. Proceeding without consent or delaying indefinitely both fail the child.", s:"Courts can authorise treatment against parental wishes when it is in the child's best interests; this is a well-established legal route."}},

/* ---------------------------------------------------------- RRP 4 */
{id:"RRP-131", t:"single", cn:"RRP", sys:"HEME", topic:"Distinguishing transfusion-associated circulatory overload from TRALI", d:3, b:0.55, cj:"analyze", tags:["risk","transfusion","TACO","TRALI","respiratory"],
 stem:"A client receiving a blood transfusion develops acute respiratory distress, hypoxia, and bilateral infiltrates on chest X-ray two hours into the transfusion. The client has a history of heart failure and is hypertensive. Which interpretation by the nurse is most accurate?",
 opts:["Transfusion-associated circulatory overload, since the client has risk factors for volume overload","Transfusion-related acute lung injury, since bilateral infiltrates are characteristic","Anaphylaxis, since respiratory distress is the presenting feature","Febrile non-haemolytic reaction, since fever often accompanies respiratory symptoms"],
 ans:0, rat:{c:"Transfusion-associated circulatory overload (TACO) presents with respiratory distress, hypoxia, bilateral infiltrates, hypertension, and a history of heart failure. TRALI presents similarly but with hypotension and no fluid overload. The client's cardiac history and hypertension point to TACO.", s:"Distinguishing TACO from TRALI guides management: TACO requires diuresis and slowing the transfusion, while TRALI requires respiratory support."}},
{id:"RRP-132", t:"single", cn:"RRP", sys:"HEME", topic:"Cryoprecipitate for low fibrinogen", d:3, b:0.55, cj:"analyze", tags:["risk","transfusion","cryoprecipitate","fibrinogen","coagulation"],
 stem:"A client undergoing major surgery has a fibrinogen level of 0.8 g/L (normal 2.0-4.0 g/L) and is oozing from surgical sites. The surgical team requests a blood product. Which product is most appropriate?",
 opts:["Cryoprecipitate, since it is rich in fibrinogen and will correct the deficiency","Fresh frozen plasma, since it contains all coagulation factors including fibrinogen","Platelets, since the client is bleeding","Packed red cells, since the client is losing blood"],
 ans:0, rat:{c:"Cryoprecipitate is rich in fibrinogen and is the appropriate product when fibrinogen is low and the client is bleeding. Fresh frozen plasma contains all factors but is less concentrated for fibrinogen replacement. Platelets and red cells do not address the fibrinogen deficiency.", s:"Cryoprecipitate is indicated for hypofibrinogenaemia with bleeding; it is more efficient than FFP for raising fibrinogen levels."}},
{id:"RRP-133", t:"single", cn:"RRP", sys:"RESP", topic:"Thoracostomy drain management", d:3, b:0.55, cj:"act", tags:["risk","thoracostomy","chest drain","respiratory","safety"],
 stem:"A client has a thoracostomy drain in situ following a pneumothorax. The drainage system is below the level of the client's chest, the water seal chamber shows tidaling, and there is no air leak. Which action by the nurse is most appropriate?",
 opts:["Continue current management, since the system is functioning correctly","Clamp the drain, since the pneumothorax has resolved","Raise the drainage system above chest level to prevent backflow","Disconnect the drain from suction, since tidaling indicates resolution"],
 ans:0, rat:{c:"A thoracostomy drain system that is below chest level, shows tidaling, and has no air leak is functioning correctly and requires no intervention. Clamping is contraindicated unless specifically ordered, raising the system risks backflow, and disconnecting from suction is not indicated when tidaling is present.", s:"Thoracostomy drain management requires understanding of the drainage system; tidaling indicates the lung is re-expanding and the system is patent."}},
{id:"RRP-134", t:"single", cn:"RRP", sys:"HEME", topic:"First action in a transfusion reaction", d:3, b:0.55, cj:"act", tags:["risk","transfusion","reaction","safety","emergency"],
 stem:"A client receiving a blood transfusion develops flushing, back pain, and a temperature of 38.5°C fifteen minutes into the transfusion. Which action by the nurse is the priority?",
 opts:["Stop the transfusion immediately and maintain intravenous access with normal saline","Slow the transfusion rate and monitor vital signs every five minutes","Administer paracetamol and continue the transfusion","Notify the physician and await further instructions before acting"],
 ans:0, rat:{c:"The first action in any suspected transfusion reaction is to stop the transfusion immediately to prevent further exposure, while maintaining intravenous access with normal saline for emergency treatment. Slowing the rate, giving paracetamol, or awaiting instructions all delay the critical first step.", s:"Stopping the transfusion is the universal first action; it limits exposure to the offending product while preserving venous access for resuscitation."}},

/* ---------------------------------------------------------- PAA 3 */
{id:"PAA-140", t:"single", cn:"PAA", sys:"HEME", topic:"Irradiated blood products to prevent transfusion-associated graft-versus-host disease", d:3, b:0.55, cj:"analyze", tags:["adaptation","transfusion","irradiated blood","TA-GvHD","immunocompromised"],
 stem:"A client with severe combined immunodeficiency requires a red cell transfusion. The blood bank asks whether irradiated products are required. Which response by the nurse is most appropriate?",
 opts:["Yes, irradiated products are required to prevent transfusion-associated graft-versus-host disease","No, standard products are sufficient since the client is not receiving immunosuppressive therapy","Yes, irradiated products are required to prevent haemolytic reaction","No, irradiated products are required only for platelet transfusions"],
 ans:0, rat:{c:"Irradiated blood products are required for immunocompromised clients to prevent transfusion-associated graft-versus-host disease (TA-GvHD), which is often fatal. Irradiation inactivates donor lymphocytes that could mount an immune response against the recipient. Standard products are not sufficient, and irradiation applies to cellular products, not just platelets.", s:"TA-GvHD is a rare but usually fatal complication; irradiation is the only prevention, and it is indicated for immunocompromised recipients."}},
{id:"PAA-141", t:"single", cn:"PAA", sys:"HEME", topic:"Tranexamic acid for bleeding", d:2, b:0.45, cj:"act", tags:["adaptation","tranexamic acid","antifibrinolytic","bleeding"],
 stem:"A client undergoing major orthopaedic surgery is at high risk of bleeding. The surgical team prescribes tranexamic acid. Which action by the nurse is most appropriate?",
 opts:["Administer tranexamic acid as prescribed, since it reduces bleeding by inhibiting fibrinolysis","Withhold tranexamic acid, since it increases the risk of thrombosis and worsens bleeding","Administer tranexamic acid only if the client's haemoglobin falls below 80 g/L","Withhold tranexamic acid, since it is contraindicated in orthopaedic surgery"],
 ans:0, rat:{c:"Tranexamic acid is an antifibrinolytic that reduces bleeding by inhibiting the breakdown of fibrin clots. It is widely used in major surgery to reduce blood loss and transfusion requirements. It does not significantly increase thrombotic risk when used appropriately, and it is not contraindicated in orthopaedic surgery.", s:"Tranexamic acid is a standard intervention in major surgery; understanding its mechanism and appropriate use is essential."}},
{id:"PAA-142", t:"single", cn:"PAA", sys:"HEME", topic:"Factor concentrate for haemophilia", d:3, b:0.55, cj:"act", tags:["adaptation","haemophilia","factor concentrate","bleeding"],
 stem:"A client with haemophilia A presents with an acute haemarthrosis of the knee. The client's factor VIII level is 2% of normal. Which action by the nurse is most appropriate?",
 opts:["Administer factor VIII concentrate as prescribed to raise the factor level and control bleeding","Administer fresh frozen plasma, since it contains all coagulation factors","Apply ice and elevate the joint, since factor replacement is not indicated for haemarthrosis","Administer desmopressin, since it releases stored factor VIII and raises the plasma level"],
 ans:0, rat:{c:"Acute haemarthrosis in haemophilia requires factor VIII concentrate to raise the factor level and control bleeding. Fresh frozen plasma is not concentrated enough. Ice and elevation are adjuncts but do not replace factor. Desmopressin is effective only in mild haemophilia A and is not appropriate for severe disease.", s:"Factor concentrate replacement is the cornerstone of haemophilia management; prompt treatment prevents joint damage."}},

/* ---------------------------------------------------------- PHA 3 */
{id:"PHA-169", t:"single", cn:"PHA", sys:"HEME", topic:"Andexanet alfa for apixaban reversal", d:3, b:0.55, cj:"act", tags:["pharmacology","apixaban","reversal","andexanet","anticoagulation"],
 stem:"A client taking apixaban presents with life-threatening gastrointestinal bleeding. The clinical team requires urgent reversal of the anticoagulant effect. Which agent is most appropriate?",
 opts:["Andexanet alfa, since it is a specific reversal agent for factor Xa inhibitors","Protamine sulfate, since it is a reversal agent for anticoagulant effects","Vitamin K, since it reverses warfarin and is effective for all anticoagulants","Fresh frozen plasma, since it replaces coagulation factors"],
 ans:0, rat:{c:"Andexanet alfa is a specific reversal agent for factor Xa inhibitors including apixaban and rivaroxaban. Protamine reverses heparin, vitamin K reverses warfarin, and fresh frozen plasma is not a specific reversal agent. Using the correct reversal agent is critical in life-threatening bleeding.", s:"Specific reversal agents exist for different anticoagulants; andexanet alfa is the agent of choice for factor Xa inhibitor reversal."}},
{id:"PHA-170", t:"single", cn:"PHA", sys:"HEME", topic:"Idarucizumab for dabigatran reversal", d:3, b:0.55, cj:"act", tags:["pharmacology","dabigatran","reversal","idarucizumab","anticoagulation"],
 stem:"A client taking dabigatran requires urgent surgery following a road traffic collision. The surgical team requires reversal of the anticoagulant effect. Which agent is most appropriate?",
 opts:["Idarucizumab, since it is a specific reversal agent for dabigatran","Andexanet alfa, since it reverses dabigatran and all other direct oral anticoagulants","Protamine sulfate, since it is a universal anticoagulant reversal agent","Vitamin K, since it reverses all anticoagulants"],
 ans:0, rat:{c:"Idarucizumab is a monoclonal antibody fragment that specifically reverses dabigatran, a direct thrombin inhibitor. Andexanet alfa reverses factor Xa inhibitors, not dabigatran. Protamine reverses heparin, and vitamin K reverses warfarin. Using the correct reversal agent is essential.", s:"Idarucizumab is the specific reversal agent for dabigatran; it binds dabigatran with higher affinity than thrombin and neutralises its effect."}},
{id:"PHA-171", t:"single", cn:"PHA", sys:"HEME", topic:"Argatroban for heparin-induced thrombocytopenia", d:3, b:0.55, cj:"act", tags:["pharmacology","argatroban","HIT","heparin","anticoagulation"],
 stem:"A client receiving unfractionated heparin develops a platelet count that falls from 280,000 to 95,000 over five days. The clinical team suspects heparin-induced thrombocytopenia and requires an alternative anticoagulant. Which agent is most appropriate?",
 opts:["Argatroban, since it is a direct thrombin inhibitor that does not cross-react with heparin antibodies","Continue heparin at a lower dose, since the platelet count is still above 50,000","Switch to low molecular weight heparin, since it has a lower risk of HIT","Administer platelet transfusion, since the platelet count has fallen significantly"],
 ans:0, rat:{c:"Argatroban is a direct thrombin inhibitor that does not cross-react with heparin antibodies and is the appropriate alternative anticoagulant in heparin-induced thrombocytopenia. Continuing heparin or switching to LMWH risks further antibody formation. Platelet transfusion is contraindicated in HIT as it can worsen thrombosis.", s:"HIT requires immediate cessation of all heparin products and initiation of a non-heparin anticoagulant such as argatroban or bivalirudin."}}

]);
