/* Wave 11 — 20 hand-authored hard RN items.
 * Targets Management of Care (16.9% against an 18% blueprint share, the largest
 * remaining deficit), Pharmacological Therapies (15.6% against 16%), and
 * Physiological Adaptation. Every item is difficulty 2 or 3.
 *
 * Management of Care  : MOC-092 – MOC-098
 * Pharmacology        : PHA-093 – PHA-098
 * Physiological Adapt.: PAA-086 – PAA-090
 * Safety              : SIC-069 – SIC-070
 */
(function () {
  "use strict";
  var BANK = (typeof window !== "undefined" ? window : globalThis).NC.BANK;

  BANK.push(
/* ---------------- Management of Care (7) ---------------- */

  { id: "MOC-092", cn: "MOC", sys: "INF", t:"single", topic:"near miss reporting", tags: ["just culture", "safety reporting"],
    d: 3, cj: "act", b: 0.55,
    stem: "A nurse scans a medication barcode and the system flags that the dose entered is ten times the prescribed amount. The nurse corrects the dose and administers the medication correctly. The client receives the intended therapy and shows no adverse effect. What action must the nurse take?",
    opts:["Submit the event through the organization's safety reporting system, because a near miss carries the same learning value as a harmful error",
      "No report is required, because the client was not harmed",
      "Document the correction in the client's chart only",
      "Notify the pharmacy informally so the system can be checked"],
    ans: 0,
    rat: { c: "A near miss is an error intercepted before it reached the client, and it is the highest-value safety data an organization collects, because it exposes a system defect that will eventually cause harm. Reporting is required regardless of the outcome.",
      s: "The absence of harm does not remove the reporting obligation. Near misses are reported precisely because they did not cause harm yet — the defect that produced the error is still present and will harm someone else." } },

  { id: "MOC-093", cn: "MOC", sys: "INF", t:"single", topic:"research informed consent", tags: ["clinical trial", "scope of practice"],
    d: 3, cj: "act", b: 0.55,
    stem: "A client with advanced cancer asks the nurse to explain a clinical trial the oncologist mentioned and whether they should sign the research consent form. The client is cognitively intact and speaks English fluently. What is the nurse's appropriate response?",
    opts:["State that the principal investigator must explain the study and obtain the research consent, and offer to arrange that discussion",
      "Explain the trial's risks and benefits and witness the client's signature on the research consent",
      "Advise the client that clinical trials are experimental and should be declined",
      "Refer the client to the unit charge nurse to complete the research consent"],
    ans: 0,
    rat: { c: "Informed consent for research belongs to the investigator, not the bedside nurse. The nurse supports the client's understanding, answers what falls within their scope, and advocates for the client's questions, but does not explain the protocol or obtain research consent.",
      s: "A nurse who explains a protocol and witnesses the signature steps outside their scope and may invalidate the consent. Steering the client away from a trial is equally inappropriate — the decision is the client's." } },

  { id: "MOC-094", cn: "MOC", sys: "INF", t:"single", topic:"utilization review documentation", tags: ["fidelity", "documentation"],
    d: 3, cj: "act", b: 0.55,
    stem: "A utilization review nurse telephones and asks the staff nurse to document that a client \"meets inpatient criteria\" so the stay will be approved. The client's clinical status does not currently meet those criteria. What should the staff nurse do?",
    opts:["Document the client's actual clinical status accurately and allow the reviewer to apply the criteria",
      "Document that the client meets inpatient criteria in order to avoid a denial",
      "Refuse to provide the client's clinical status to the reviewer",
      "Ask the provider to record that the client meets inpatient criteria"],
    ans: 0,
    rat: { c: "Documentation must reflect the client's true clinical condition. Writing a statement the nurse knows to be false is falsification, regardless of who requests it or what the financial consequence would otherwise be.",
      s: "Altering documentation to satisfy a payer is falsification. The nurse documents accurately and escalates through the case manager or attending if the level of care is genuinely disputed." } },

  { id: "MOC-095", cn: "MOC", sys: "REPI", t:"single", topic:"adolescent confidential care", tags: ["confidentiality", "minors"],
    d: 3, cj: "act", b: 0.55,
    stem: "A 16-year-old client asks the nurse about contraception and states clearly that they do not want their parents told. The client is not being coerced and understands the information provided. What is the nurse's appropriate action?",
    opts:["Provide contraceptive counseling and honor the request for confidentiality, because most jurisdictions permit minors to consent to contraceptive care",
      "Notify the parents, because the client is a minor",
      "Refuse to discuss contraception until a parent consents",
      "Document the request and defer all discussion to the provider without counseling"],
    ans: 0,
    rat: { c: "In most US jurisdictions minors may consent to contraceptive, sexually transmitted infection and prenatal care without parental involvement, and confidentiality applies. The nurse may encourage involving a trusted adult but cannot disclose without the client's consent.",
      s: "Parental notification would breach confidentiality where the law permits the minor to consent, and is likely to deter the client from seeking care at all. Refusing to counsel abandons the client's request." } },

  { id: "MOC-096", cn: "MOC", sys: "INF", t:"single", topic:"surrogate decision hierarchy", tags: ["ethics", "substituted judgment"],
    d: 3, cj: "analyze", b: 0.55,
    stem: "An unconscious client has no advance directive. The adult child insists on full aggressive treatment. The spouse, who was the client's primary caregiver for years, states that the client repeatedly said they would not want to be kept alive on machines. The two cannot agree. What should the nurse do?",
    opts:["Recognize the spouse as the higher-priority surrogate under most surrogate hierarchies and escalate the disagreement to the care team and ethics consultation",
      "Follow the wishes of the adult child, who is more insistent",
      "Provide full aggressive treatment until a court appoints a guardian",
      "Ask the adult child and the spouse to decide between themselves and report back"],
    ans: 0,
    rat: { c: "Most jurisdictions define a surrogate hierarchy in which a spouse precedes an adult child. When surrogates disagree, the team identifies the legally recognized decision-maker, applies the substituted-judgment standard, and obtains ethics consultation.",
      s: "Insistence does not determine authority. Deferring entirely to the family without identifying the legal decision-maker leaves the client without a recognized surrogate and the team without a defensible plan." } },

  { id: "MOC-097", cn: "MOC", sys: "INF", t:"single", topic:"telephone order read-back", tags: ["medication safety", "documentation"],
    d: 2, cj: "act", b: 0.45,
    stem: "A nurse takes a telephone order for an intravenous opioid during a busy shift. The prescriber is standing in a noisy corridor and speaking quickly. What must the nurse do before administering the medication?",
    opts:["Read the order back verbatim, obtain the prescriber's confirmation, and record it as a telephone order with the required countersignature",
      "Administer the medication and document the telephone order later from memory",
      "Ask another nurse to listen in and confirm the dose with the prescriber",
      "Transcribe the order and have the charge nurse initial it"],
    ans: 0,
    rat: { c: "Telephone orders require a verbatim read-back with explicit confirmation from the prescriber, because mishearing a dose is a well-documented cause of harm. The order is then documented as a telephone order and countersigned within the organization's timeframe.",
      s: "A second listener does not substitute for the prescriber's confirmation, and the charge nurse is not the prescriber. Documenting from memory after administration defeats the purpose of the read-back entirely." } },

  { id: "MOC-098", cn: "MOC", sys: "PSYCH", t:"single", topic:"restraint without a current order", tags: ["restraints", "regulation", "safety"],
    d: 3, cj: "prioritize", b: 0.55,
    stem: "At the start of the shift the nurse finds a client in a wrist restraint applied by the previous shift. There is no current restraint order in the record, and no documentation of assessment or of alternatives attempted. What is the nurse's priority action?",
    opts:["Remove the restraint, assess the client and the skin, and notify the provider that a new order and assessment are required before it can be reapplied",
      "Leave the restraint in place and request an order and assessment retrospectively",
      "Document the restraint as continuing care from the previous shift",
      "Replace the restraint with a different device to avoid the missing order"],
    ans: 0,
    rat: { c: "A restraint requires a current, time-limited order and documented assessment. Continuing one without either is a regulatory violation and an immediate safety risk. The nurse removes it, assesses the client and skin, and obtains a proper order if restraint is still indicated.",
      s: "A retrospective order does not legitimize an unauthorized restraint, and substituting a different device does not cure the missing order. Documenting it as continuing care conceals the violation." } },

/* ---------------- Pharmacological Therapies (6) ---------------- */

  { id: "PHA-093", cn: "PHA", sys: "GI", t:"single", topic:"antibiotic-associated colitis", tags: ["C. difficile", "clindamycin"],
    d: 2, cj: "analyze", b: 0.45,
    stem: "A client completed a 10-day course of oral clindamycin for a dental infection two weeks ago. They now report 8 to 10 watery stools per day, abdominal cramping, and a temperature of 38.2°C. What should the nurse anticipate?",
    opts:["Testing for Clostridioides difficile toxin and discontinuation of the inciting antibiotic",
      "Restarting clindamycin at a lower dose",
      "Administering an antimotility agent to reduce stool frequency",
      "Increasing dietary fiber to bulk the stool"],
    ans: 0,
    rat: { c: "Clindamycin carries one of the highest risks for C. difficile infection. Frequent watery stools after recent antibiotic exposure require toxin or PCR testing, discontinuation of the inciting agent, and contact precautions.",
      s: "Antimotility agents are contraindicated in suspected C. difficile, because retained toxin increases the risk of toxic megacolon. Restarting the causative antibiotic worsens the dysbiosis that produced the infection." } },

  { id: "PHA-094", cn: "PHA", sys: "NEURO", t:"single", topic:"equianalgesic opioid rotation", tags: ["opioids", "cross-tolerance"],
    d: 3, cj: "analyze", b: 0.55,
    stem: "A client receiving intravenous morphine 10 mg every 4 hours for cancer pain is being converted to intravenous hydromorphone. The nurse calculates the equivalent dose from the published potency ratio. What additional consideration applies to this conversion?",
    opts:["Reduce the calculated dose further to account for incomplete cross-tolerance, then titrate while monitoring both pain and sedation",
      "The published ratio is exact and no adjustment is required",
      "Increase the dose, because hydromorphone is less potent than morphine",
      "Avoid the conversion entirely, because opioid rotation is not used in cancer pain"],
    ans: 0,
    rat: { c: "Published equianalgesic ratios do not account for incomplete cross-tolerance between opioids, so the calculated dose is typically reduced by 25 to 50% when rotating and then titrated. Opioid rotation is a recognized cause of both uncontrolled pain and overdose.",
      s: "Applying the ratio without reduction risks respiratory depression, because tolerance built to one opioid does not transfer completely to another. Opioid rotation is standard practice in cancer pain when analgesia or side effects are inadequate." } },

  { id: "PHA-095", cn: "PHA", sys: "HEME", t:"single", topic:"factor Xa inhibitor reversal", tags: ["apixaban", "intracranial hemorrhage"],
    d: 3, cj: "analyze", b: 0.55,
    stem: "A client taking apixaban for atrial fibrillation is brought to the emergency department with a large intracranial hemorrhage after a fall. The last dose was taken 6 hours ago. What reversal strategy should the nurse anticipate?",
    opts:["Andexanet alfa as the specific reversal agent, with four-factor prothrombin complex concentrate if it is unavailable",
      "Protamine sulfate, because it is the standard reversal agent for anticoagulants",
      "Vitamin K with fresh frozen plasma",
      "Idarucizumab, because it reverses oral factor Xa inhibitors"],
    ans: 0,
    rat: { c: "Andexanet alfa is a recombinant decoy receptor that binds apixaban and rivaroxaban. Four-factor prothrombin complex concentrate is the accepted alternative where andexanet is unavailable. Neither protamine nor vitamin K has any effect on a factor Xa inhibitor.",
      s: "Idarucizumab reverses dabigatran, a direct thrombin inhibitor, not a factor Xa inhibitor. Protamine reverses heparin, and vitamin K reverses warfarin — neither applies to apixaban." } },

  { id: "PHA-096", cn: "PHA", sys: "ENDO", t:"single", topic:"beta blocker masking hypoglycemia", tags: ["diabetes", "hypoglycemia awareness"],
    d: 3, cj: "analyze", b: 0.55,
    stem: "A client with type 1 diabetes takes propranolol for migraine prophylaxis. They report that their usual warning signs of low blood glucose — trembling and a pounding heart — no longer occur before they feel confused. What is the nurse's best explanation?",
    opts:["Beta blockers blunt the adrenergic warning symptoms of hypoglycemia, so the client must rely on glucose monitoring rather than symptoms",
      "The client has developed tolerance to hypoglycemia and needs a higher glucose target",
      "The propranolol dose is too low to affect glucose regulation",
      "The warning symptoms have resolved because glycemic control has improved"],
    ans: 0,
    rat: { c: "Non-selective beta blockers mask the tremor, palpitations and anxiety that warn of falling glucose, while sweating often persists. Loss of awareness shifts the client's protection to scheduled glucose monitoring, and non-selective agents also impair glycogenolysis and delay recovery.",
      s: "Loss of adrenergic warning signs in a client taking a beta blocker is pharmacologic masking, not improved control — and it is dangerous, because the first symptom may be neuroglycopenia." } },

  { id: "PHA-097", cn: "PHA", sys: "PSYCH", t:"single", topic:"antipsychotic metabolic monitoring", tags: ["olanzapine", "monitoring"],
    d: 2, cj: "generate", b: 0.45,
    stem: "A client with schizophrenia has taken olanzapine for 6 months and has gained 12 kg. The provider is reviewing the client's metabolic parameters. Which monitoring is indicated for this client?",
    opts:["Weight and waist circumference, fasting glucose or A1c, and a fasting lipid panel at baseline and periodically",
      "A serum lithium level every 3 months",
      "An absolute neutrophil count weekly for 6 months",
      "A serum prolactin level only if symptoms develop"],
    ans: 0,
    rat: { c: "Second-generation antipsychotics, especially olanzapine and clozapine, carry substantial metabolic risk. Guidelines require baseline and periodic weight, waist circumference, blood pressure, fasting glucose and lipids.",
      s: "Weekly absolute neutrophil count monitoring applies to clozapine, not olanzapine. Lithium levels apply to lithium therapy. Prolactin is checked when symptoms such as galactorrhea or amenorrhea appear, not as routine surveillance." } },

  { id: "PHA-098", cn: "PHA", sys: "HEME", t:"single", topic:"acquired methemoglobinemia", tags: ["benzocaine", "methylene blue"],
    d: 3, cj: "analyze", b: 0.55,
    stem: "A client receives topical benzocaine spray before an endoscopy and develops cyanosis with chocolate-brown blood. The pulse oximetry saturation is 85% and does not improve with supplemental oxygen, while the arterial blood gas shows a normal PaO2. What should the nurse anticipate?",
    opts:["Administration of methylene blue for acquired methemoglobinemia",
      "Increasing the oxygen flow rate until the saturation improves",
      "Administration of naloxone for opioid-induced respiratory depression",
      "Administration of sodium bicarbonate for metabolic acidosis"],
    ans: 0,
    rat: { c: "Topical anesthetics such as benzocaine oxidize hemoglobin to methemoglobin, which cannot carry oxygen and shifts the dissociation curve leftward. Pulse oximetry reads falsely near 85%, the PaO2 is normal, and the blood is chocolate-colored. Methylene blue reduces methemoglobin back to hemoglobin.",
      s: "A normal PaO2 with a low saturation that does not respond to oxygen is the signature of methemoglobinemia, not hypoventilation. More oxygen cannot bind to oxidized hemoglobin, so increasing flow changes nothing." } },

/* ---------------- Physiological Adaptation (5) ---------------- */

  { id: "PAA-086", cn: "PAA", sys: "GI", t:"single", topic:"nasogastric sump patency", tags: ["bowel obstruction", "NG tube"],
    d: 2, cj: "prioritize", b: 0.45,
    stem: "A client with a small bowel obstruction has a Salem sump nasogastric tube connected to low intermittent suction. The nurse notes the drainage has stopped and the client reports increasing nausea. What is the nurse's first action?",
    opts:["Assess the tube for patency and irrigate gently with normal saline if the order permits, rather than increasing the suction",
      "Increase the suction to high continuous to relieve the increasing nausea",
      "Clamp the tube and administer an antiemetic",
      "Advance the tube several centimeters to reposition it"],
    ans: 0,
    rat: { c: "Loss of drainage with worsening nausea indicates an obstructed tube. The nurse assesses patency first and irrigates gently with the prescribed volume of normal saline. Increasing suction will not clear a mechanical obstruction and may injure the mucosa.",
      s: "Blindly advancing a nasogastric tube risks perforation, particularly after gastric or esophageal surgery. Clamping the tube removes the decompression that is relieving the obstruction, and an antiemetic treats the symptom rather than the cause." } },

  { id: "PAA-087", cn: "PAA", sys: "INTG", t:"single", topic:"corneal protection in coma", tags: ["unconscious client", "eye care"],
    d: 3, cj: "generate", b: 0.55,
    stem: "An unconscious client in the intensive care unit has an absent blink reflex and incomplete eyelid closure. The nurse is planning eye care. What intervention should be included?",
    opts:["Instill preservative-free lubricant, close and shield the eyelids, and assess the cornea for drying each shift",
      "Irrigate the eyes with normal saline every 2 hours to keep them moist",
      "Leave the eyelids open so the cornea dries and forms a protective crust",
      "Apply a warm compress and encourage the client to blink"],
    ans: 0,
    rat: { c: "Without a blink reflex the cornea dries and abrades, which can progress to ulceration and permanent vision loss. Lubrication combined with mechanical closure is the standard protective measure, with corneal assessment each shift.",
      s: "Frequent saline irrigation strips what little tear film remains and increases drying. A crust is not protective — it is the precursor to abrasion. An unconscious client cannot blink on command." } },

  { id: "PAA-088", cn: "PAA", sys: "NEURO", t:"single", topic:"autonomic dysreflexia", tags: ["spinal cord injury", "hypertensive emergency"],
    d: 3, cj: "prioritize", b: 0.55,
    stem: "A client with a T4 spinal cord injury sustained 3 years ago reports a pounding headache and blurred vision. The blood pressure is 210/118 mm Hg in the right arm, the heart rate is 48 beats/minute, and the skin above the level of injury is flushed and sweating. What is the nurse's priority action?",
    opts:["Sit the client upright immediately and check the bladder for distention or a blocked catheter",
      "Lay the client flat and administer a beta blocker for the hypertension",
      "Administer an anticholinergic to raise the heart rate",
      "Obtain a computed tomography scan of the head before intervening"],
    ans: 0,
    rat: { c: "Autonomic dysreflexia is a hypertensive emergency in injuries above T6, triggered by a noxious stimulus below the level of injury — most often bladder distention or a blocked catheter. Sitting upright lowers blood pressure by gravity while the stimulus is located and removed.",
      s: "Laying the client flat raises intracranial pressure further and increases stroke risk. The bradycardia is a baroreceptor reflex response to the hypertension, not the problem to treat, and imaging delays the intervention that resolves it." } },

  { id: "PAA-089", cn: "PAA", sys: "GI", t:"single", topic:"colostomy irrigation teaching", tags: ["ostomy", "patient teaching"],
    d: 2, cj: "generate", b: 0.45,
    stem: "A client with a descending colostomy is being taught colostomy irrigation to regulate bowel elimination and asks how often it should be performed. What should the nurse teach?",
    opts:["Irrigate at the same time each day using lukewarm water, pausing if cramping occurs, with the goal of predictable elimination every 24 to 48 hours",
      "Irrigate every 4 hours so that elimination stays continuous",
      "Use cold water to reduce the risk of bleeding",
      "Continue irrigating through cramping so the full volume is instilled"],
    ans: 0,
    rat: { c: "Colostomy irrigation is performed once daily at a consistent time with lukewarm water to train predictable elimination. Cramping signals overdistention and requires pausing. Cold water increases cramping and is not used.",
      s: "Four-hourly irrigation is excessive and risks perforation. Pushing through cramping forces volume into a distended colon. Irrigation is not appropriate for an ileostomy, where output is continuous and liquid." } },

  { id: "PAA-090", cn: "PAA", sys: "REN", t:"single", topic:"citrate-induced hypocalcemia", tags: ["CRRT", "renal replacement therapy"],
    d: 3, cj: "analyze", b: 0.55,
    stem: "A client on continuous renal replacement therapy with regional citrate anticoagulation develops perioral tingling, a positive Chvostek sign, and a prolonged QT interval. The ionized calcium is 0.82 mmol/L. What does the nurse anticipate?",
    opts:["An intravenous calcium infusion, because citrate chelates calcium",
      "Increasing the citrate infusion rate to prevent circuit clotting",
      "Administering oral calcium gluconate as a supplement",
      "Stopping the dialysate to allow calcium to accumulate"],
    ans: 0,
    rat: { c: "Citrate anticoagulates the circuit by chelating calcium, and some returns to the client. Citrate accumulation, particularly with hepatic impairment, causes ionized hypocalcemia with neuromuscular irritability and QT prolongation. Intravenous calcium corrects it.",
      s: "Increasing the citrate worsens the chelation. Oral calcium cannot correct acute ionized hypocalcemia in a critically ill client, and stopping the dialysate does not remove the citrate already circulating." } },

/* ---------------- Safety (2) ---------------- */

  { id: "SIC-069", cn: "SIC", sys: "INF", t:"single", topic:"bedside specimen labeling", tags: ["wrong-patient error", "identification"],
    d: 2, cj: "act", b: 0.45,
    stem: "A nurse collects two blood culture specimens from a client with suspected sepsis. Another client in the same room also requires blood cultures. The nurse plans to label the tubes after returning to the workstation. What must the nurse do instead?",
    opts:["Label each tube at the bedside in the client's presence, immediately after collection, following two-identifier verification",
      "Label the tubes at the workstation while the collection is still fresh in memory",
      "Label the tubes in advance to save time during the collection",
      "Have a colleague label the tubes at the nurses' station"],
    ans: 0,
    rat: { c: "Specimens must be labeled at the point of collection, in the client's presence, after two-identifier verification. Labeling away from the bedside is the most common cause of wrong-patient specimen errors, which lead to misdiagnosis and mistreatment.",
      s: "Pre-labeling is prohibited because the tube may then be used for the wrong client. Delegating labeling to a colleague at the station reproduces the same separation between collection and identification." } },

  { id: "SIC-070", cn: "SIC", sys: "INF", t:"single", topic:"fire evacuation sequence", tags: ["emergency preparedness", "RACE"],
    d: 3, cj: "prioritize", b: 0.55,
    stem: "Smoke is detected in a client room on the fourth floor of an inpatient unit. The fire door to the stairwell is at the far end of the corridor, and several clients are bedbound. What is the correct evacuation sequence?",
    opts:["Move clients horizontally through the fire doors into the adjacent smoke compartment first, and use the stairs only if that compartment becomes unsafe",
      "Evacuate all clients down the stairwell immediately, starting with the most critical",
      "Use the elevator to move bedbound clients to the ground floor",
      "Close all doors to contain the smoke and wait for the fire department"],
    ans: 0,
    rat: { c: "Horizontal evacuation through fire doors into an adjacent smoke compartment is faster and safer than vertical evacuation, especially for bedbound clients. Elevators are never used during a fire, and stairs are used only when the horizontal route is no longer tenable.",
      s: "Attempting vertical evacuation first for immobile clients delays rescue and exposes them to smoke in the stairwell. Waiting passively while smoke spreads, or using an elevator that may fail or open onto the fire floor, both increase risk." } }
  );
})();
