/* RN Ready — item bank v2 · part 2 (Pharmacology, Risk Reduction, Physiological
   Adaptation). Same metadata model as bank.js.                                  */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Pharmacological & Parenteral Therapies ─────────────────────── */
{id:"PHA-017", t:"single", cn:"PHA", sys:"HEME", topic:"Heparin therapy", d:2, b:0.6, cj:"act", tags:["medication","priority","calculation"],
 stem:"A client on a heparin infusion has an aPTT of 95 seconds (control 32 seconds; therapeutic range 60–80 seconds) with no bleeding. Which provider order should the nurse anticipate?",
 opts:["Continue the infusion at the current rate","Hold or reduce the infusion per protocol and recheck the aPTT","Administer vitamin K orally","Stop the infusion permanently and switch to aspirin"],
 ans:1,
 rat:{c:"An aPTT of 95 s is above the therapeutic range (1.5–2.5× control). Standard protocol response is holding or reducing the infusion and repeating the aPTT — permanent discontinuation and vitamin K (warfarin antidote) are incorrect.",
 o:["Continuing deepens the supratherapeutic state.","Correct — protocol-based hold/reduce + recheck.","Vitamin K reverses warfarin, not heparin (protamine reverses heparin).","Abrupt permanent discontinuation is not warranted without bleeding."],
 s:"Heparin: monitor aPTT (goal 1.5–2.5×), antidote protamine. LMWH: anti-Xa, no routine monitoring. Thrombocytopenia <100k → suspect HIT and stop all heparins."},
 ref:"Anticoagulation · unfractionated heparin"},

{id:"PHA-018", t:"single", cn:"PHA", sys:"INF", topic:"Vancomycin", d:1, b:-0.2, cj:"act", tags:["medication","safety"],
 stem:"Fifteen minutes into a client's first vancomycin infusion, the nurse notes flushing of the face, neck, and chest with a mild rash. The infusion is running over 30 minutes. Which action is correct?",
 opts:["Stop the vancomycin permanently and label the client allergic","Slow the infusion to infuse over at least 60 minutes and notify the provider per protocol","Give IV diphenhydramine and continue at the same rate","Speed up the infusion to finish before symptoms worsen"],
 ans:1,
 rat:{c:"Flushing + rash during rapid vancomycin is red man (redneck) syndrome — a rate-related infusion reaction, not a true allergy. Management: slow the infusion (≥60 min, often 90–120 for larger doses) and notify the provider; antihistamines may be co-administered per order.",
 o:["It is rate-related, not allergic — stopping forever forfeits a key antibiotic.","Correct — slow the rate; this is rate-dependent histamine release.","Continuing the rapid rate perpetuates the reaction.","Accelerating is the exact opposite of safe."],
 s:"Vancomycin: infuse slowly (≥1 h) to avoid red man syndrome; monitor troughs and nephrotoxicity/ototoxicity; true allergy ≠ infusion reaction."},
 ref:"Antibiotic administration · infusion reactions"},

{id:"PHA-019", t:"single", cn:"PHA", sys:"REN", topic:"Potassium administration", d:1, b:-0.15, cj:"act", tags:["medication","safety","priority"],
 stem:"A client with hypokalemia has an order for IV potassium chloride 20 mEq. Which action is required before administration?",
 opts:["Verify the dose can be given by IV push over 2 minutes","Dilute the potassium per protocol and administer via infusion pump","Administer through a small peripheral butterfly catheter rapidly","Mix the potassium into a hanging bag of packed red blood cells"],
 ans:1,
 rat:{c:"IV potassium must ALWAYS be diluted and infused by pump at a controlled rate (peripheral typically ≤10 mEq/hr; central lines faster per protocol) with continuous monitoring — never IV push (lethal cardiac arrest).",
 o:["IV push potassium is fatal — absolutely contraindicated.","Correct — dilute + pump + rate limits + cardiac monitoring.","Rapid administration through any device is dangerous.","Never add medications to blood products."],
 s:"K+ rules: never push, always dilute, always a pump, monitor ECG and urine output, never piggyback into blood. Replace Mg+ when low — hypomagnesemia makes hypokalemia refractory."},
 ref:"Electrolyte therapy · potassium safety"},

{id:"PHA-020", t:"single", cn:"PHA", sys:"RESP", topic:"Opioid safety", d:1, b:-0.3, cj:"act", tags:["medication","priority"],
 stem:"The nurse is preparing to administer morphine 4 mg IV to a postoperative client whose respiratory rate is 10/min and who is drowsy but arousable. Which action is appropriate?",
 opts:["Administer the dose as ordered with stimulation","Hold the dose, monitor closely, and anticipate naloxone per protocol if breathing worsens","Administer half the calculated dose","Administer the dose with a stimulant medication"],
 ans:1,
 rat:{c:"Respiratory rate <12/min with sedation before an opioid dose means HOLD the opioid, monitor airway/RR and sedation, escalate, and administer naloxone per protocol if depression deepens. Opioids are titrated to respiratory safety first, pain second.",
 o:["Proceeding compounds depression.","Correct — hold, monitor, escalate, naloxone if needed.","Nurses may not alter prescribed doses independently.","No routine stimulant co-administration exists."],
 s:"Opioid gate: RR ≥12 and sedation scale acceptable before each dose. Reversal: naloxone titrated to respiratory effort (not full wakefulness)."},
 ref:"Opioid administration · respiratory depression"},

{id:"PHA-021", t:"single", cn:"PHA", sys:"ENDO", topic:"Corticosteroids", d:1, b:-0.35, cj:"generate", tags:["medication","teaching"],
 stem:"A client taking prednisone 40 mg daily for 3 weeks for a flare of systemic lupus asks about stopping the drug now that symptoms improved. Which teaching is essential?",
 opts:["Stop the medication today to avoid long-term effects","Taper the dose as prescribed — abrupt cessation can cause adrenal insufficiency","Alternate skipping doses to wean informally","Switch to an over-the-counter steroid cream"],
 ans:1,
 rat:{c:"Supraphysiologic glucocorticoids for >2–3 weeks suppress the hypothalamic–pituitary–adrenal axis; abrupt withdrawal precipitates acute adrenal insufficiency (hypotension, shock). The dose must be tapered under a prescribed schedule.",
 o:["Abrupt stop risks adrenal crisis.","Correct — taper per prescription.","Improvised skipping is unsafe and ineffective.","No substitution of systemic therapy with topical steroid."],
 s:"Steroid teaching set: taper (never stop), take with food in the morning, watch glucose/pressure/weight, infection signs may be masked, never stop steroids during illness/without guidance."},
 ref:"Glucocorticoid therapy · adrenal suppression"},

{id:"PHA-022", t:"single", cn:"PHA", sys:"RESP", topic:"Bronchodilator side effects", d:0, b:-1.2, cj:null, tags:["medication","teaching"],
 stem:"A client newly prescribed an albuterol inhaler reports feeling jittery with a heart rate of 104/min after use. Which response by the nurse is best?",
 opts:["This is an emergency — call 911","Tremor and mild tachycardia are common expected effects and often improve with continued use","Stop the medication immediately — you are allergic","Double the albuterol dose next time to overcome the tremor"],
 ans:1,
 rat:{c:"Albuterol is a β2-agonist (with some β1 effect): tremor, nervousness, and mild tachycardia are expected, typically diminish with continued use, and don't warrant stopping an essential bronchodilator.",
 o:["Not an emergency pattern.","Correct — expected sympathomimetic effects.","These are side effects, not allergy.","Doubling doses is never self-directed and worsens effects."],
 s:"Albuterol side-effect set: tremor, tachycardia, nervousness, headache, hypokalemia (at high doses). Teach rinse-and-spit after ICS to prevent thrush; albuterol before ICS."},
 ref:"Respiratory medications · bronchodilators"},

{id:"PHA-023", t:"single", cn:"PHA", sys:"ENDO", topic:"Metformin", d:1, b:-0.25, cj:"act", tags:["medication","safety"],
 stem:"A client with type 2 diabetes taking metformin is scheduled for a contrast-enhanced CT scan. Which instruction should the nurse reinforce?",
 opts:["Continue metformin as usual through the procedure","Hold metformin before and for ~48 hours after contrast per provider orders, with renal function rechecked","Switch to insulin permanently after any contrast study","Take a double dose the day before the scan"],
 ans:1,
 rat:{c:"Iodinated contrast + metformin in reduced renal function risks lactic acidosis. Standard practice: hold metformin at the time of (or 48 h before) contrast and restart only ~48 h after with a rechecked eGFR/creatinine.",
 o:["Continuing through contrast is the unsafe choice.","Correct — hold and recheck renal function before restarting.","Insulin substitution is a provider decision, not automatic or permanent.","Doubling is dangerous."],
 s:"Metformin pearls: hold with contrast (lactic acidosis), monitor renal function, take with meals (GI upset), watch for B12 deficiency long-term. Hold in dehydration/sepsis/serious illness."},
 ref:"Antidiabetics · metformin & contrast"},

{id:"PHA-024", t:"single", cn:"PHA", sys:"REN", topic:"IV drip calculation", d:1, b:-0.35, cj:null, tags:["calculation","intervention"],
 stem:"The provider orders 1,000 mL of 0.9% sodium chloride over 12 hours. The tubing delivers 15 gtt/mL. At how many gtt/min should the nurse set the manual infusion?",
 opts:["13 gtt/min","21 gtt/min","31 gtt/min","42 gtt/min"],
 ans:1,
 rat:{c:"Volume × drop factor ÷ minutes = (1,000 mL × 15 gtt/mL) ÷ 720 min = 20.8 ≈ 21 gtt/min.",
 o:["That's roughly half the correct rate.","Correct — 20.8 rounds to 21.","That would deliver ~1,490 mL in 12 h.","That would deliver ~2,016 mL in 12 h."],
 s:"Manual rate: (volume × gtt factor) ÷ minutes. Check: 1,000 mL ÷ 12 h = 83 mL/hr; 83 × 15 ÷ 60 ≈ 21 gtt/min."},
 ref:"IV flow rate calculation"},

{id:"PHA-025", t:"single", cn:"PHA", sys:"REPI", topic:"Pediatric weight-based dosing", d:1, b:-0.3, cj:null, tags:["calculation","medication","safety"],
 stem:"A toddler weighing 12 kg needs acetaminophen 15 mg/kg/dose PO. The suspension is 160 mg/5 mL. How many mL per dose should the nurse administer? (Round to the nearest tenth.)",
 opts:["4.2 mL","5.6 mL","8.4 mL","11.2 mL"],
 ans:1,
 rat:{c:"15 mg × 12 kg = 180 mg/dose → 180 mg ÷ 32 mg/mL (160 mg/5 mL) = 5.625 ≈ 5.6 mL.",
 o:["4.2 mL ≈ 135 mg — underdose.","Correct — 180 mg at 32 mg/mL = 5.6 mL.","8.4 mL ≈ 270 mg — a double dose.","11.2 mL ≈ 358 mg — exceeds safe single-dose range."],
 s:"Weight-based steps: mg/kg → dose → ÷ concentration → mL. Always sanity-check against the maximum daily ceiling (acetaminophen 75 mg/kg/day, ~4,000 mg adult)."},
 ref:"Pediatric dosing calculation"},

{id:"PHA-026", t:"matrix", cn:"PHA", sys:"NEURO", topic:"Opioid effects vs toxicity", d:1, b:-0.1, cj:"analyze", tags:["medication","assessment","safety"],
 stem:"A client is receiving a morphine patient-controlled analgesia (PCA). For each finding, indicate whether it is an EXPECTED side effect or a sign of TOXICITY/overdose requiring action.",
 matrix:{cols:["Expected effect","Toxicity"], mode:"radio",
  rows:["Constipation","Respiratory rate 8/min with pinpoint pupils","Drowsiness","Generalized itching without rash","Sedation progressing to unresponsiveness"],
  ans:[0,1,0,0,1]},
 rat:{c:"Constipation, drowsiness, and pruritus (histamine) are expected opioid effects managed prophylactically. Respiratory depression (RR ≤8), pinpoint pupils with sedation, and unresponsiveness are overdose signals requiring naloxone and escalation.",
 o:["Expected — tolerance never develops; treat with a bowel regimen.","Toxicity — the emergency sign: hold PCA, stimulate, naloxone.","Expected — monitor sedation scale.","Expected — histamine release; antihistamine if needed.","Toxicity — escalating sedation precedes respiratory arrest."],
 s:"PCA safety: only the CLIENT presses the button (no proxy dosing), sedation scale before doses, RR gate ≥12. Know the expected-vs-toxic table cold."},
 ref:"Opioid therapy · PCA & toxicity"},

/* ── Reduction of Risk Potential ────────────────────────────────── */
{id:"RRP-011", t:"cloze", cn:"RRP", sys:"RESP", topic:"Arterial blood gas interpretation", d:2, b:0.7, cj:"analyze", tags:["assessment"],
 stem:"A client with COPD has an ABG: pH 7.31, PaCO2 62 mm Hg, HCO3 30 mEq/L, PaO2 58 mm Hg, SpO2 86%. Complete the interpretation using the drop-down menus.",
 cloze:{lines:[
  {pre:"The blood pH of 7.31 is", post:"the expected reference range.", opts:["below","within","above"], ans:0},
  {pre:"This client's primary acid–base imbalance is", post:".", opts:["respiratory acidosis","respiratory alkalosis","metabolic acidosis"], ans:0},
  {pre:"The PaO2 of 58 mm Hg with SpO2 86% indicates", post:": apply prescribed oxygen targeting 88–92% for COPD.", opts:["hypoxemia","normal oxygenation","oxygen toxicity"], ans:0}]},
 rat:{c:"pH 7.31 < 7.35 = acidosis; PaCO2 62 elevated drives respiratory acidosis, partially compensated by HCO3 30 (renal retention). PaO2 58/SpO2 86% = hypoxemia — oxygenate (88–92% target in COPD).",
 o:["<7.35 is acidemia.","Low pH + high CO2 = respiratory acidosis (compensated, HCO3 elevated).","Marked hypoxemia — an ABC priority."],
 s:"ABG ladder: pH → who matches (CO2 respiratory, HCO3 metabolic) → compensation (opposite direction) → oxygenation. COPD target 88–92% to avoid CO2 retention."},
 ref:"Diagnostic testing · ABG interpretation"},

{id:"RRP-012", t:"single", cn:"RRP", sys:"CV", topic:"Abdominal aortic aneurysm", d:2, b:0.8, cj:"act", tags:["priority","assessment"],
 stem:"A client with a known abdominal aortic aneurysm suddenly reports severe tearing back and abdominal pain. Blood pressure is 82/48 mm Hg, heart rate 124/min, and a pulsatile abdominal mass is palpated. Which action is the priority?",
 opts:["Administer prescribed analgesic for pain","Notify the provider immediately and prepare for rapid transport to surgery","Perform a full abdominal assessment to grade the mass","Encourage oral fluids to raise blood pressure"],
 ans:1,
 rat:{c:"Sudden tearing pain + hypotension + tachycardia with a known AAA indicates rupture — a surgical emergency. Immediate provider notification and OR mobilization are the priority; everything else delays definitive care.",
 o:["Pain control never precedes escalation of a rupture.","Correct — rupture = prepare for emergent surgical repair.","Assessment detail is irrelevant now; escalate.","Oral fluids are absurd in shock (and NPO for surgery)."],
 s:"AAA triad of rupture: tearing/severe back or abdominal pain + hypotension + pulsatile mass → call rapid response/surgeon. Monitoring an intact AAA: control BP, no straining, avoid Valsalva."},
 ref:"Vascular emergencies · AAA rupture"},

{id:"RRP-013", t:"single", cn:"RRP", sys:"ENDO", topic:"Post-thyroidectomy", d:1, b:-0.2, cj:"act", tags:["safety","intervention"],
 stem:"A client returns from a total thyroidectomy. Which equipment must be at the bedside?",
 opts:["A chest tube drainage system","A tracheostomy kit and calcium gluconate for IV administration","Defibrillator paddles only","A nasogastric suction setup"],
 ans:1,
 rat:{c:"Thyroid surgery risks include airway compromise (hematoma, laryngeal edema → keep trach kit/suture removal readiness) and hypocalcemia from parathyroid injury (keep IV calcium: watch Chvostek/Trousseau).",
 o:["Chest tubes relate to thoracic surgery.","Correct — airway rescue + calcium replacement.","Defibrillator-only ignores the two specific risks.","NG suction is not routine post-thyroidectomy."],
 s:"Post-thyroidectomy watchlist: airway (hoarseness, stridor, neck swelling), calcium (perioral tingling, Chvostek/Trousseau), hemorrhage. Bedside: trach kit + calcium gluconate."},
 ref:"Postoperative care · thyroidectomy complications"},

{id:"RRP-014", t:"single", cn:"RRP", sys:"INF", topic:"Central line care", d:1, b:-0.25, cj:"generate", tags:["safety","intervention"],
 stem:"The nurse is changing the dressing on a central venous catheter insertion site. Which technique is correct?",
 opts:["Clean the site with alcohol only and apply a clean dressing","Perform hand hygiene, mask, use sterile supplies with chlorhexidine antisepsis, and apply a transparent semipermeable dressing","Change the dressing only when visibly soiled using clean gloves","Cover the site with gauze and tape, changing weekly"],
 ans:1,
 rat:{c:"Central line dressing changes require hand hygiene, mask (client and nurse), sterile gloves, chlorhexidine skin antisepsis with full drying, and a transparent semipermeable dressing changed every 7 days (sooner if soiled/lifting) — the bundle that prevents central line–associated bloodstream infection.",
 o:["Alcohol alone is inferior; non-sterile technique risks CLABSI.","Correct — the full sterile bundle with CHG and transparent dressing.","Clean-glove changes violate sterile protocol.","Plain gauze-and-tape weekly changes miss early site inspection and sterility."],
 s:"CLABSI bundle: hand hygiene, maximal sterile barrier (mask, sterile gloves, drape), CHG, transparent dressing q7 days, scrub the hub, remove lines as soon as unneeded."},
 ref:"Vascular access · central line maintenance"},

{id:"RRP-015", t:"multi", cn:"RRP", sys:"REN", topic:"Catheter-associated UTI prevention", d:1, b:-0.2, cj:"generate", tags:["safety","intervention"],
 stem:"Which practices prevent catheter-associated urinary tract infections (CAUTI)? Select all that apply.",
 opts:["Maintaining a closed drainage system","Keeping the collection bag below the level of the bladder","Routine instillation of antimicrobial irrigation into the catheter","Performing perineal care regularly and after bowel movements","Removing the catheter as soon as it is no longer needed"],
 ans:[0,1,3,4],
 rat:{c:"CAUTI prevention = closed system, bag below bladder (never on the floor), hygiene, and — most powerfully — early removal. Routine antimicrobial irrigation is NOT recommended (promotes resistance and reseeds the bladder).",
 o:["Correct — breaks in the system introduce bacteria.","Correct — prevents retrograde flow of urine.","Routine irrigation is explicitly not recommended.","Correct — hygiene reduces periurethral colonization.","Correct — the indwelling catheter itself is the risk factor."],
 s:"CAUTI hierarchy: avoid placing the catheter → remove early → closed system → bag below bladder → hygiene. Never clamp/drain retrograde; never routine irrigation."},
 ref:"Infection prevention · CAUTI bundle"},

{id:"RRP-016", t:"single", cn:"RRP", sys:"HEME", topic:"Transfusion reactions", d:1, b:-0.15, cj:"act", tags:["priority","safety","intervention"],
 stem:"Ten minutes after starting a unit of packed red blood cells, the client develops chills, back pain, and hypotension. Which action should the nurse take first?",
 opts:["Slow the transfusion to keep the vein open and recheck vital signs","Stop the transfusion immediately and maintain IV access with 0.9% sodium chloride","Administer prescribed antihistamine and continue the transfusion","Notify the blood bank and wait for guidance before acting"],
 ans:1,
 rat:{c:"Chills + back pain + hypotension early in a transfusion suggest an acute hemolytic reaction — stop the blood immediately, keep the line open with normal saline (new tubing), assess, then notify provider/blood bank. Never flush the reaction blood back in.",
 o:["Slowing (rather than stopping) allows ongoing hemolysis.","Correct — STOP, saline, save the unit and tubing for the blood bank, assess and escalate.","Antihistamine-first applies to mild urticaria; this picture is hemolytic.","Escalation follows the immediate stop — act first."],
 s:"Reaction playbook: STOP → NS to keep vein open (separate tubing) → VS + assess → notify provider + blood bank → return unit/tubing → document. Hemolytic signs: fever, chills, back pain, hypotension, dark urine."},
 ref:"Blood product administration · transfusion reactions"},

/* ── Physiological Adaptation ───────────────────────────────────── */
{id:"PAA-019", t:"single", cn:"PAA", sys:"ENDO", topic:"Adrenal crisis", d:2, b:0.85, cj:"act", tags:["priority","medication"],
 stem:"A client with Addison disease arrives with vomiting, confusion, and blood pressure 76/44 mm Hg. Which provider order should the nurse implement first?",
 opts:["Administer IV hydrocortisone and isotonic fluids","Administer oral fludrocortisone","Insert an indwelling urinary catheter","Restrict fluids to prevent overload"],
 ans:0,
 rat:{c:"This is addisonian (adrenal) crisis: cortisol deficiency → vascular collapse. Priority is IV glucocorticoid replacement (hydrocortisone) with isotonic fluid resuscitation; mineralocorticoids (fludrocortisone) are adjuncts and oral agents are useless in crisis.",
 o:["Correct — hydrocortisone + IV fluids first.","Fludrocortisone is secondary and not IV-available.","Monitoring follows stabilization.","Fluids are the therapy, not the threat."],
 s:"Adrenal crisis = hypotension + vomiting + confusion ± hypoglycemia/hyponatremia/hyperkalemia → steroids + saline immediately. Addison clients under stress need doubled steroids (sick-day rules)."},
 ref:"Endocrine emergencies · adrenal insufficiency"},

{id:"PAA-020", t:"single", cn:"PAA", sys:"ENDO", topic:"Hypocalcemia", d:1, b:-0.2, cj:"act", tags:["priority","medication","assessment"],
 stem:"Twelve hours after a thyroidectomy, a client reports tingling around the mouth and in the fingers. Trousseau sign is positive. Which action is most important?",
 opts:["Reassure the client that this is normal after anesthesia","Notify the provider and prepare to administer IV calcium gluconate","Encourage increased oral phosphorus intake","Assess for Chvostek sign only and document"],
 ans:1,
 rat:{c:"Perioral/digital paresthesia with positive Trousseau after thyroidectomy indicates acute hypocalcemia from parathyroid injury — notify the provider and prepare IV calcium gluconate (cardiac monitoring). Untreated, it progresses to tetany, laryngospasm, and seizures.",
 o:["These are classic hypocalcemia signs, not anesthesia effects.","Correct — urgent replacement with IV calcium.","Phosphorus worsens hypocalcemia (inverse relationship).","Further assessment delays treatment of a dangerous finding."],
 s:"Post-thyroid hypocalcemia: tingling lips/fingers, Chvostek (facial twitch), Trousseau (carpal spasm with BP cuff) → calcium gluconate IV, cardiac monitor, safety for seizures."},
 ref:"Postoperative endocrine complications"},

{id:"PAA-021", t:"single", cn:"PAA", sys:"ENDO", topic:"SIADH", d:2, b:0.75, cj:"act", tags:["priority","intervention"],
 stem:"A client with small-cell lung cancer has serum sodium 118 mEq/L, headache, and new confusion. Which intervention does the nurse anticipate first?",
 opts:["Infuse hypertonic (3%) saline as prescribed with seizure precautions","Encourage oral water intake","Administer desmopressin (DDAVP)","Restrict all sodium intake"],
 ans:0,
 rat:{c:"Na 118 with neurologic symptoms is severe hyponatremia from SIADH (water retention) — treated with hypertonic saline (carefully, with seizure precautions and frequent sodium checks because overcorrection causes osmotic demyelination). Water restriction applies to milder, asymptomatic cases.",
 o:["Correct — symptomatic severe hyponatremia gets 3% saline + monitoring.","Added water worsens dilutional hyponatremia.","DDAVP CAUSES this syndrome (it's used in diabetes insipidus, the opposite condition).","Sodium restriction is the opposite of treatment."],
 s:"SIADH = water retention → dilutional hypoNa. Mild: fluid restrict + treat cause. Severe/symptomatic: hypertonic saline ± tolvaptan, seizure precautions, correct slowly. DI (opposite): high Na, polyuria → DDAVP + fluids."},
 ref:"Fluid & electrolyte emergencies · SIADH"},

{id:"PAA-022", t:"single", cn:"PAA", sys:"NEURO", topic:"Status epilepticus", d:2, b:0.9, cj:"act", tags:["priority","safety","intervention"],
 stem:"A client has been having generalized seizure activity for 4 minutes without regaining consciousness between seizures. Which action is the priority?",
 opts:["Insert a padded tongue blade between the teeth","Ensure a patent airway, apply oxygen, and activate the seizure/response protocol (IV benzodiazepines)","Restrain the limbs to prevent injury","Wait for the seizure to self-resolve while documenting timing"],
 ans:1,
 rat:{c:"Seizures ≥5 minutes (or without recovery between them) = status epilepticus, a life-threatening emergency: airway positioning + oxygen first, then IV benzodiazepines (lorazepam/midazolam) per protocol. Nothing is ever placed in the mouth; restraint causes injury.",
 o:["Never insert anything into the mouth.","Correct — airway/O2 + protocol benzodiazepines.","Never restrain a seizing client.","Watching and waiting wastes the treatment window."],
 s:"Status: time it → airway + O2 + suction ready → IV benzo → follow with second-line AED → prepare for intubation if prolonged. Never tongue blade, never restraint."},
 ref:"Neurologic emergencies · status epilepticus"},

{id:"PAA-023", t:"single", cn:"PAA", sys:"NEURO", topic:"Spinal shock", d:2, b:0.8, cj:"analyze", tags:["assessment"],
 stem:"A client with a spinal cord injury at T4 suddenly develops hypotension (78/40), bradycardia (52/min), and warm dry skin below the injury. How should the nurse interpret these findings?",
 opts:["Hemorrhagic shock from internal bleeding","Neurogenic shock from loss of sympathetic tone","Anxiety response to the injury","Early sepsis"],
 ans:1,
 rat:{c:"Injury above ~T6 disrupts sympathetic pathways: vasodilation below the lesion → hypotension with WARM dry skin, plus unopposed vagal tone → bradycardia. Hemorrhagic shock presents cold, clammy, and tachycardic — the opposite pattern.",
 o:["Hemorrhage = tachycardia + cold/clammy.","Correct — hypotension + bradycardia + warm dry = neurogenic shock.","Anxiety produces tachycardia.","Early sepsis is warm but tachycardic and febrile."],
 s:"Shock differentiator: warm, dry, BRADY = neurogenic; cold, clammy, tachy = hypovolemic; warm, febrile, tachy = septic/vasodilatory. Treatment: fluids judiciously ± vasopressors, treat bradycardia, immobilize."},
 ref:"Spinal cord injury · neurogenic shock"},

{id:"PAA-024", t:"single", cn:"PAA", sys:"ENDO", topic:"Hypercalcemia", d:2, b:0.7, cj:"generate", tags:["intervention","priority"],
 stem:"A client with metastatic cancer has a serum calcium of 13.2 mg/dL with confusion, constipation, and polyuria. Which order does the nurse anticipate first?",
 opts:["IV normal saline hydration followed by a loop diuretic as prescribed","Oral calcium supplements with vitamin D","Administer prescribed thiazide diuretic","Initiate seizure precautions alone"],
 ans:0,
 rat:{c:"Symptomatic hypercalcemia is treated with aggressive isotonic saline hydration (restore volume, promote calciuresis) then loop diuretics (furosemide) once rehydrated; bisphosphonates follow. Thiazides and calcium/vitamin D worsen it.",
 o:["Correct — hydrate first, then loop diuretic.","Adding calcium is the opposite of treatment.","Thiazides retain calcium.","Seizures are not the hallmark; treat the cause."],
 s:"Hypercalcemia (“bones, stones, groans, psychiatric overtones”): confusion, constipation, polyuria/polydipsia, dysrhythmias (short QT). Tx: saline → loop (not thiazide) → bisphosphonate/calcitonin."},
 ref:"Oncologic emergencies · hypercalcemia"},

{id:"PAA-025", t:"single", cn:"PAA", sys:"CV", topic:"Acute coronary syndrome", d:1, b:-0.2, cj:"act", tags:["priority","assessment"],
 stem:"A client presents to the emergency department with chest pain. Which diagnostic action should the nurse anticipate FIRST?",
 opts:["Obtain a 12-lead electrocardiogram within 10 minutes","Schedule a stress treadmill test for tomorrow","Draw a troponin level and wait for results before acting","Obtain a chest x-ray to rule out pneumonia"],
 ans:0,
 rat:{c:"The 12-lead ECG within 10 minutes of arrival identifies ST-elevation MI and drives the reperfusion pathway (PCI ≤90 min). Troponins rise serially (drawn too, but don't gate the ECG); stress testing and imaging are not first-line for active chest pain.",
 o:["Correct — ECG immediately; it decides reperfusion.","Stress tests are for stable, risk-stratified clients.","Waiting on troponin delays ECG-driven decisions.","Chest x-ray does not rule ACS in or out first."],
 s:"Chest pain bundle: ECG ≤10 min → IV access + monitor → troponin serial → aspirin/NTG per protocol → risk-stratify. MONA is outdated as a mnemonic sequence — ECG decides."},
 ref:"Acute coronary syndrome · initial management"},

{id:"PAA-026", t:"single", cn:"PAA", sys:"RESP", topic:"Asthma exacerbation", d:1, b:-0.25, cj:"act", tags:["priority","intervention","medication"],
 stem:"An adolescent in the emergency department has an acute asthma exacerbation with wheezing, respiratory rate 30/min, SpO2 89%, and difficulty speaking in full sentences. Which action should the nurse take first?",
 opts:["Administer prescribed oxygen to keep SpO2 ≥ 90–94%","Teach trigger avoidance for future exacerbations","Schedule pulmonary function testing","Administer prescribed oral corticosteroid"],
 ans:0,
 rat:{c:"In an acute exacerbation with hypoxemia, oxygen comes first (ABC), immediately followed by short-acting β-agonist (albuterol) via nebulizer with ipratropium and systemic steroids. Education and PFTs are for the stable phase.",
 o:["Correct — oxygenation precedes and accompanies bronchodilation.","Education waits until the client can breathe comfortably.","PFTs are not performed during acute distress.","Steroids act in hours — not first."],
 s:"Acute asthma sequence: O2 → continuous/high-dose albuterol (+ ipratropium) → systemic steroid → magnesium if severe. Danger signs: silent chest, decreasing wheeze with rising CO2, single-word dyspnea → anticipate ICU."},
 ref:"Respiratory emergencies · asthma"},

{id:"PAA-027", t:"single", cn:"PAA", sys:"INTG", topic:"Burn management", d:2, b:0.8, cj:"evaluate", tags:["intervention","evaluation"],
 stem:"A 70-kg adult with 40% total body surface area burns is receiving fluid resuscitation. Which finding best indicates adequate fluid replacement during the first 24 hours?",
 opts:["Urine output of 35 mL/hr","Urine output of 10 mL/hr","Blood pressure 160/90 mm Hg","Heart rate 55/min"],
 ans:0,
 rat:{c:"In the first 24 hours of burn resuscitation, urine output is the key endpoint — target ~30–50 mL/hr in adults (0.5 mL/kg/hr). 10 mL/hr signals under-resuscitation; blood pressure and heart rate lag and are poor guides in this context.",
 o:["Correct — 30–50 mL/hr (adult) is the resuscitation target.","Under-resuscitation — increase fluids per protocol.","Hypertension is not the endpoint.","Bradycardia is irrelevant (and tachycardia is expected)."],
 s:"Parkland-ish logic: fluid by %TBSA × weight, titrated to UOP 30–50 mL/h adults (children 1 mL/kg/h). Second 24 h: colloids + maintenance. Watch for low-output → more fluid, high-output → reassess."},
 ref:"Burn care · fluid resuscitation endpoints"},

{id:"PAA-028", t:"cloze", cn:"PAA", sys:"ENDO", topic:"DKA interpretation", d:2, b:0.7, cj:"analyze", tags:["assessment","medication"],
 stem:"An adolescent with type 1 diabetes presents with polyuria, Kussmaul respirations, and abdominal pain. Labs: glucose 512 mg/dL, pH 7.18, HCO3 8 mEq/L, K+ 3.2 mEq/L. Complete the interpretation.",
 cloze:{lines:[
  {pre:"The blood glucose of 512 mg/dL is", post:"the expected reference range.", opts:["above","within","below"], ans:0},
  {pre:"The pH 7.18 with HCO3 8 mEq/L indicates", post:": a priority for fluid and insulin therapy.", opts:["metabolic acidosis","metabolic alkalosis","respiratory acidosis"], ans:0},
  {pre:"The potassium of 3.2 mEq/L means replacement must begin", post:"once urine output is confirmed.", opts:["promptly","never","after insulin only"], ans:0}]},
 rat:{c:"Marked hyperglycemia with low pH and severely depleted bicarbonate = diabetic ketoacidosis (metabolic acidosis with respiratory compensation — Kussmaul breathing). Total-body potassium is depleted even when serum K+ looks low-normal; replacement starts once output is established because insulin drives K+ intracellularly.",
 o:["512 mg/dL is far above euglycemia.","Correct — DKA is a high-anion-gap metabolic acidosis.","Potassium still needs replacement — hypokalemia plus insulin shift risks dysrhythmias."],
 s:"DKA trio: hyperglycemia + metabolic acidosis + ketonuria. Sequence: fluids → insulin drip → K+ when voiding → glucose checks hourly. Cerebral edema risk (headache, ↓LOC) is the classic pediatric complication."},
 ref:"Endocrine emergencies · DKA"},

{id:"PAA-029", t:"hotspot", cn:"PAA", sys:"GI", topic:"GI bleeding", d:2, b:0.65, cj:"recognize", tags:["assessment","priority"],
 stem:"Review the shift assessment of a client hospitalized with gastritis who vomited once. Tap to highlight each finding that suggests upper GI bleeding and requires immediate follow-up.",
 hotspot:{mode:"rows",
  rows:["Emesis described as “coffee-ground” material","Heart rate 118/min (baseline 74)","Blood pressure 96/54 mm Hg (baseline 132/80)","Hemoglobin 13.8 g/dL (baseline 14.0)","Soft, nontender abdomen with active bowel sounds","Melena — black tarry stool"],
  ans:[0,1,2,5]},
 rat:{c:"Coffee-ground emesis and melena are hallmark upper-GI bleeding signs; new tachycardia with narrowing pressures signals volume loss (early shock). Stable hemoglobin doesn't exclude acute bleeding (equilibration lags), and a benign abdominal exam is not reassuring.",
 o:["Partially digested blood: follow up.","Compensatory tachycardia: follow up.","Falling pressure with tachycardia: urgent.","Hemoglobin lags acute loss — a distractor.","Normal exam — expected distractor.","Melena = digested blood: follow up."],
 s:"GI bleed red flags: coffee-ground/melena/hematemesis + rising HR + falling BP + rising BUN. Priority actions: large-bore IVs, type & cross, NPO, notify — anticipate endoscopy and PPI infusion."},
 ref:"Gastrointestinal bleeding · assessment"},

{id:"PAA-030", t:"drag", cn:"PAA", sys:"INF", topic:"Sepsis bundle", d:1, b:-0.15, cj:"act", tags:["priority","intervention"],
 stem:"A client with fever, hypotension, and a suspected urinary source has lactate 4.4 mmol/L. Order the sepsis bundle actions from FIRST to LAST.",
 drag:{targets:["1 — First","2","3","4 — Last"],
  opts:["Obtain blood cultures (and urine culture) BEFORE antibiotics","Administer broad-spectrum antibiotics as prescribed","Begin IV crystalloid fluid resuscitation","Reassess lactate, perfusion, and response to therapy"],
  ans:[0,1,2,3]},
 rat:{c:"The hour-1 sepsis bundle: cultures first (so pathogens can be identified before antibiotics sterilize them), antibiotics promptly, 30 mL/kg crystalloid for hypotension/lactate ≥4, then reassess lactate and perfusion and escalate (vasopressors if fluids fail).",
 o:["Cultures before antibiotics — the classic sequencing test point.","Antibiotics within the first hour save lives.","Fluids for hypotension/elevated lactate.","Reassessment drives escalation decisions."],
 s:"Sepsis hour-1: measure lactate → cultures → antibiotics → fluids (30 mL/kg) → reassess → vasopressors (norepinephrine) if MAP <65 despite fluids. Never let cultures delay antibiotics beyond the first hour."},
 ref:"Sepsis · Surviving Sepsis hour-one bundle"}
);
