"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 38) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 37: MOC (17.7% vs 18),
 * SIC (12.9% vs 13), PSY (8.8% vs 9) and BCC (8.8% vs 9). Every
 * item is difficulty 2 or 3, and the clinical detail is written
 * to be defensible.
 *
 * MOC 6: duty of candour, apology and open disclosure, colleague
 * impairment and substance misuse, fitness to practise, reflective
 * practice, and clinical supervision.
 * SIC 6: verbal aggression de-escalation, environmental restraint,
 * seclusion room use, ligature check, contraband search, and
 * escorted leave.
 * PSY 4: dynamic risk assessment, static risk factors, moral injury,
 * and task assignment.
 * BCC 4: preceptorship, mentorship, continuing professional
 * development, and workplace violence prevention.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- MOC 6 */
{id:"MOC-192", t:"single", cn:"MOC", sys:"INTG", topic:"Duty of candour", d:3, b:0.55, cj:"act", tags:["management","duty of candour","safety","transparency","accountability"],
 stem:"A nurse realises that a medication error occurred on the previous shift. The client was not harmed, but the wrong dose was given. The error was not reported at the time. Which action by the nurse is most appropriate?",
 opts:["Report the error immediately to the line manager and complete an incident report, since the duty of candour requires transparency","Do not report the error, since the client was not harmed and no action is needed","Report the error only if the client or family asks about it","Wait to see if the client develops any adverse effects before reporting"],
 ans:0, rat:{c:"The duty of candour requires that errors be reported and disclosed, regardless of whether harm occurred. Reporting immediately allows for investigation, learning, and prevention of future errors. Not reporting, waiting for the client to ask, or delaying until harm appears all breach the duty of candour.", s:"Duty of candour is a professional and often legal obligation; the nurse must understand when and how to report errors."}},
{id:"MOC-193", t:"single", cn:"MOC", sys:"INTG", topic:"Apology and open disclosure", d:3, b:0.55, cj:"act", tags:["management","apology","open disclosure","duty of candour","communication"],
 stem:"A client has suffered harm due to a delay in diagnosis. The clinical team is preparing to disclose this to the client. The client asks the nurse, 'Should I have been diagnosed sooner?' Which response by the nurse is most appropriate?",
 opts:["Acknowledge the client's concerns, apologise for the distress caused, and explain that the matter is being investigated","Avoid answering the question, since the investigation is ongoing and the nurse should not comment","Tell the client that the delay was unavoidable and no apology is necessary","Deflect the question and change the subject to the client's current treatment"],
 ans:0, rat:{c:"Open disclosure requires acknowledging the client's concerns, offering a sincere apology for the distress caused, and explaining the investigation process. Avoiding the question, denying the delay, or deflecting all fail the duty of candour and damage trust.", s:"Apology and open disclosure are essential components of duty of candour; the nurse must be able to respond honestly and compassionately."}},
{id:"MOC-194", t:"single", cn:"MOC", sys:"INTG", topic:"Colleague impairment and substance misuse", d:3, b:0.55, cj:"act", tags:["management","colleague impairment","substance misuse","safeguarding","professional duty"],
 stem:"A nurse notices that a colleague appears to be under the influence of alcohol during a shift. The colleague's speech is slurred and they smell of alcohol. Which action by the nurse is most appropriate?",
 opts:["Report the concern immediately to the line manager or duty manager, since patient safety is at risk","Confront the colleague privately and ask them to stop working","Ignore the signs, since the colleague may have a legitimate explanation","Wait until the end of the shift and then report the concern"],
 ans:0, rat:{c:"A colleague who appears impaired poses an immediate risk to patient safety and must be reported immediately to the line manager or duty manager. Confronting the colleague privately may not be safe or effective. Ignoring the signs or waiting until the end of shift allows the risk to continue.", s:"Reporting colleague impairment is a professional duty; the nurse must act promptly to protect patients."}},
{id:"MOC-195", t:"single", cn:"MOC", sys:"INTG", topic:"Fitness to practise", d:3, b:0.55, cj:"analyze", tags:["management","fitness to practise","professional standards","health","impairment"],
 stem:"A nurse is experiencing symptoms of depression that are affecting their concentration and decision-making. The nurse is concerned about their fitness to practise. Which action by the nurse is most appropriate?",
 opts:["Seek occupational health advice and consider temporary adjustment or sick leave, since fitness to practise includes physical and mental health","Continue working without disclosure, since seeking help may affect their fitness to practise record","Resign immediately, since they are no longer fit to practise","Ignore the symptoms, since they will resolve with time"],
 ans:0, rat:{c:"Fitness to practise includes physical and mental health. A nurse experiencing symptoms that affect their practice should seek occupational health advice and consider temporary adjustment or sick leave. Continuing without disclosure risks patient safety. Resigning immediately or ignoring symptoms are not appropriate responses.", s:"Understanding fitness to practise and the importance of seeking help is essential for professional accountability."}},
{id:"MOC-196", t:"single", cn:"MOC", sys:"INTG", topic:"Reflective practice", d:2, b:0.45, cj:"evaluate", tags:["management","reflective practice","professional development","learning"],
 stem:"A nurse has been involved in a resuscitation that did not go as planned. The nurse feels distressed and uncertain about their actions. Which action by the nurse is most appropriate?",
 opts:["Engage in structured reflection, possibly with a supervisor or colleague, to process the experience and identify learning","Avoid thinking about the event, since dwelling on it is unhelpful","Blame others for the outcome, since this reduces personal distress","Resign from the role, since the experience shows they are not suited to nursing"],
 ans:0, rat:{c:"Structured reflection, possibly with a supervisor or colleague, helps process distressing experiences, identify learning, and improve future practice. Avoiding the event, blaming others, or resigning do not address the underlying issues and prevent learning.", s:"Reflective practice is a core professional skill; it supports learning, resilience, and continuous improvement."}},
{id:"MOC-197", t:"single", cn:"MOC", sys:"INTG", topic:"Clinical supervision", d:2, b:0.45, cj:"act", tags:["management","clinical supervision","support","professional development"],
 stem:"A newly qualified nurse is finding the transition to practice challenging and feels overwhelmed. The nurse's manager suggests clinical supervision. Which interpretation by the nurse is most accurate?",
 opts:["Clinical supervision provides a structured, confidential space to discuss practice, emotions, and professional development","Clinical supervision is a form of performance management that may lead to disciplinary action if practice standards are not met","Clinical supervision is only for nurses who are struggling and indicates poor performance","Clinical supervision is optional and can be declined without consequence"],
 ans:0, rat:{c:"Clinical supervision provides a structured, confidential space to discuss practice, emotions, and professional development. It is not performance management, not only for struggling nurses, and is a valuable support for all nurses. Engaging in supervision supports professional growth and resilience.", s:"Understanding the purpose and value of clinical supervision is essential for professional development and wellbeing."}},

/* ---------------------------------------------------------- SIC 6 */
{id:"SIC-144", t:"single", cn:"SIC", sys:"PSYCH", topic:"Verbal aggression de-escalation", d:3, b:0.55, cj:"act", tags:["safety","de-escalation","verbal aggression","psychiatric","communication"],
 stem:"A client on a psychiatric unit becomes verbally aggressive, shouting and making threats toward staff. The client is not physically aggressive. Which action by the nurse is the priority?",
 opts:["Use calm, non-confrontational verbal de-escalation techniques and give the client space","Restrain the client immediately, since threats indicate imminent danger","Leave the area and call security, since staff safety is the priority","Ignore the behaviour, since it will pass without intervention"],
 ans:0, rat:{c:"Verbal aggression without physical aggression should be managed with calm, non-confrontational verbal de-escalation and giving the client space. Restraint is not indicated without physical aggression. Leaving the area or ignoring the behaviour escalates the situation and fails the client.", s:"De-escalation is the first-line response to verbal aggression; the nurse must use calm communication to prevent escalation."}},
{id:"SIC-145", t:"single", cn:"SIC", sys:"PSYCH", topic:"Environmental restraint", d:3, b:0.55, cj:"act", tags:["safety","environmental restraint","psychiatric","least restrictive"],
 stem:"A client on a psychiatric unit is at risk of self-harm and requires increased observation. The clinical team is considering environmental restraint. Which interpretation by the nurse is most accurate?",
 opts:["Environmental restraint involves modifying the environment to reduce risk and should be the least restrictive option","Environmental restraint involves physical restraint and should be used only as a last resort","Environmental restraint involves seclusion and should be used only in emergencies","Environmental restraint is not a recognised intervention in psychiatric care"],
 ans:0, rat:{c:"Environmental restraint involves modifying the environment to reduce risk, such as removing ligature points or increasing observation. It should be the least restrictive option and is a recognised intervention in psychiatric care. Physical restraint and seclusion are different interventions with different indications.", s:"Understanding environmental restraint and the principle of least restrictive practice is essential for safe psychiatric care."}},
{id:"SIC-146", t:"single", cn:"SIC", sys:"PSYCH", topic:"Seclusion room use", d:3, b:0.55, cj:"act", tags:["safety","seclusion","psychiatric","least restrictive","monitoring"],
 stem:"A client on a psychiatric unit is placed in seclusion due to imminent risk of harm to others. Which action by the nurse is the priority?",
 opts:["Maintain continuous observation and monitor the client's physical and psychological state","Leave the client alone to calm down without interruption","Check the client every fifteen minutes","Administer rapid tranquillisation immediately"],
 ans:0, rat:{c:"A client in seclusion requires continuous observation and monitoring of their physical and psychological state. Leaving the client alone or checking intermittently fails to ensure safety. Rapid tranquillisation may be indicated but is not the priority over observation and monitoring.", s:"Seclusion requires continuous observation; the nurse must understand the monitoring requirements and documentation."}},
{id:"SIC-147", t:"single", cn:"SIC", sys:"PSYCH", topic:"Ligature check", d:2, b:0.45, cj:"act", tags:["safety","ligature check","psychiatric","environmental safety"],
 stem:"A client is admitted to a psychiatric unit following a suicide attempt by hanging. Which action by the nurse is the priority?",
 opts:["Conduct a ligature risk check of the room and remove any potential ligature points","Ask the client to identify any ligature points in the room","Place the client in a room without a ligature check, since the client is now safe","Wait for the next scheduled environmental check"],
 ans:0, rat:{c:"A client admitted following a suicide attempt by hanging requires an immediate ligature risk check and removal of potential ligature points. Asking the client to identify ligature points is not reliable. Assuming the client is now safe or waiting for the next check fails to address the immediate risk.", s:"Ligature risk assessment is a core safety intervention in psychiatric care; the nurse must conduct it promptly and thoroughly."}},
{id:"SIC-148", t:"single", cn:"SIC", sys:"PSYCH", topic:"Contraband search", d:2, b:0.45, cj:"act", tags:["safety","contraband","psychiatric","search","safety"],
 stem:"A client is admitted to a psychiatric unit. The unit policy requires a search for contraband items. The client refuses the search. Which action by the nurse is most appropriate?",
 opts:["Explain the purpose of the search and the consequences of refusal, and document the client's response","Proceed with the search regardless of the client's refusal","Allow the client to refuse, since they have the right to decline","Discharge the client, since they are not complying with unit policy"],
 ans:0, rat:{c:"When a client refuses a contraband search, the nurse should explain the purpose and consequences of refusal and document the client's response. Proceeding regardless of refusal may not be lawful. Allowing refusal without explanation or discharging the client are not appropriate responses.", s:"Contraband searches require clear communication and documentation; the nurse must balance safety with client rights."}},
{id:"SIC-149", t:"single", cn:"SIC", sys:"PSYCH", topic:"Escorted leave", d:2, b:0.45, cj:"act", tags:["safety","escorted leave","psychiatric","risk assessment","supervision"],
 stem:"A client on a psychiatric unit requests unescorted leave to visit family. The client's risk assessment indicates ongoing risk of self-harm. Which action by the nurse is most appropriate?",
 opts:["Explain that unescorted leave is not appropriate given the risk assessment, and discuss escorted leave as an alternative","Allow unescorted leave, since it is appropriate given the risk assessment and the client's right to request it","Allow unescorted leave with conditions, since the client is an adult","Refuse all leave, since the client is at risk"],
 ans:0, rat:{c:"Unescorted leave is not appropriate when the risk assessment indicates ongoing risk. The nurse should explain this and discuss escorted leave as an alternative. Allowing unescorted leave, with or without conditions, fails to manage the risk. Refusing all leave is overly restrictive.", s:"Leave decisions must be based on risk assessment; the nurse must balance client autonomy with safety."}},

/* ---------------------------------------------------------- PSY 4 */
{id:"PSY-093", t:"single", cn:"PSY", sys:"PSYCH", topic:"Dynamic risk assessment", d:3, b:0.55, cj:"analyze", tags:["psych","dynamic risk","risk assessment","monitoring","psychiatric"],
 stem:"A client on a psychiatric unit has a static risk assessment completed on admission. During the shift, the client becomes increasingly agitated and expresses hopelessness. Which action by the nurse is most appropriate?",
 opts:["Conduct a dynamic risk assessment, since risk can change and requires ongoing evaluation","Rely on the static risk assessment, since it was completed on admission","Increase observation without reassessing risk, since the client's behaviour is concerning","Discharge the client, since they are not responding to treatment"],
 ans:0, rat:{c:"Risk is dynamic and can change rapidly. A dynamic risk assessment is required when the client's presentation changes. Relying on a static assessment fails to capture current risk. Increasing observation without reassessment does not address the underlying risk. Discharging the client is not appropriate.", s:"Dynamic risk assessment is essential in psychiatric care; the nurse must recognise when reassessment is needed."}},
{id:"PSY-094", t:"single", cn:"PSY", sys:"PSYCH", topic:"Static risk factors", d:2, b:0.45, cj:"analyze", tags:["psych","static risk","risk factors","assessment","psychiatric"],
 stem:"A nurse is completing a risk assessment for a client with a history of suicide attempts. Which interpretation by the nurse is most accurate?",
 opts:["A history of suicide attempts is a static risk factor that cannot be changed but informs ongoing risk management","A history of suicide attempts is a dynamic risk factor that can be modified with treatment","A history of suicide attempts is not a significant risk factor","Static risk factors are more important than dynamic risk factors in risk assessment"],
 ans:0, rat:{c:"A history of suicide attempts is a static risk factor that cannot be changed but informs ongoing risk management. Dynamic risk factors can be modified with treatment. A history of suicide attempts is a significant risk factor. Both static and dynamic factors are important in risk assessment.", s:"Understanding static and dynamic risk factors is essential for comprehensive risk assessment in psychiatric care."}},
{id:"PSY-095", t:"single", cn:"PSY", sys:"PSYCH", topic:"Moral injury", d:3, b:0.55, cj:"analyze", tags:["psych","moral injury","professional wellbeing","ethics","trauma"],
 stem:"A nurse is distressed after being unable to provide the care they believed was necessary due to resource constraints. The nurse feels guilt and shame about the situation. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with moral injury, which occurs when actions conflict with deeply held moral beliefs","This is consistent with burnout, which is caused by excessive workload","This is consistent with compassion fatigue, which is caused by exposure to suffering","This is a normal reaction that will resolve without intervention"],
 ans:0, rat:{c:"Moral injury occurs when actions conflict with deeply held moral beliefs, causing guilt, shame, and distress. Burnout is caused by excessive workload and emotional exhaustion. Compassion fatigue is caused by exposure to suffering. Moral injury requires specific intervention and support.", s:"Recognising moral injury is essential for professional wellbeing; the nurse must understand its causes and seek appropriate support."}},
{id:"PSY-096", t:"single", cn:"PSY", sys:"PSYCH", topic:"Task assignment", d:2, b:0.45, cj:"act", tags:["psych","task assignment","delegation","teamwork","scope of practice"],
 stem:"A nurse is assigning tasks to a healthcare assistant for the shift. Which principle should guide the nurse's decision?",
 opts:["Assign tasks within the healthcare assistant's competence and scope of practice, and retain accountability for the overall care","Assign all tasks to the healthcare assistant, since this frees the nurse for more complex work","Assign only tasks the nurse has personally trained the healthcare assistant to do","Assign tasks based on the healthcare assistant's preference, regardless of competence"],
 ans:0, rat:{c:"Task assignment should be based on the healthcare assistant's competence and scope of practice. The nurse retains accountability for the overall care. Assigning all tasks, only personally trained tasks, or tasks based on preference regardless of competence are not appropriate approaches.", s:"Understanding task assignment and delegation is essential for safe and effective teamwork."}},

/* ---------------------------------------------------------- BCC 4 */
{id:"BCC-099", t:"single", cn:"BCC", sys:"INTG", topic:"Preceptorship", d:2, b:0.45, cj:"act", tags:["basic care","preceptorship","professional development","support","transition"],
 stem:"A newly qualified nurse is starting their first post and is assigned a preceptor. Which interpretation by the nurse is most accurate?",
 opts:["Preceptorship provides structured support and guidance during the transition to independent practice","Preceptorship is a form of assessment and may lead to failure if the nurse does not meet standards","Preceptorship is only for nurses who are struggling and indicates poor performance","Preceptorship is optional and can be declined without consequence"],
 ans:0, rat:{c:"Preceptorship provides structured support and guidance during the transition to independent practice. It is not a form of assessment, not only for struggling nurses, and is a valuable support for all newly qualified nurses. Engaging in preceptorship supports professional growth and confidence.", s:"Understanding the purpose and value of preceptorship is essential for professional development and transition to practice."}},
{id:"BCC-100", t:"single", cn:"BCC", sys:"INTG", topic:"Mentorship", d:2, b:0.45, cj:"act", tags:["basic care","mentorship","professional development","support","guidance"],
 stem:"A nurse is considering seeking a mentor for career development. Which interpretation by the nurse is most accurate?",
 opts:["Mentorship provides a supportive relationship for career guidance, development, and personal growth","Mentorship is a formal requirement for career development and must be completed within a specific timeframe","Mentorship is only for nurses in senior roles and is not relevant to junior staff","Mentorship is the same as preceptorship and provides no additional benefit"],
 ans:0, rat:{c:"Mentorship provides a supportive relationship for career guidance, development, and personal growth. It is not a formal requirement, not only for senior nurses, and is distinct from preceptorship. Seeking a mentor supports long-term professional development.", s:"Understanding the purpose and value of mentorship is essential for career development and professional growth."}},
{id:"BCC-101", t:"single", cn:"BCC", sys:"INTG", topic:"Continuing professional development", d:2, b:0.45, cj:"act", tags:["basic care","continuing professional development","learning","professional standards"],
 stem:"A nurse is required to complete continuing professional development (CPD) as part of revalidation. Which interpretation by the nurse is most accurate?",
 opts:["CPD maintains and enhances knowledge, skills, and competence throughout a nurse's career","CPD is a bureaucratic requirement that has no impact on practice","CPD is only required for nurses in specialist roles","CPD can be completed at any time and does not need to be planned"],
 ans:0, rat:{c:"CPD maintains and enhances knowledge, skills, and competence throughout a nurse's career. It is not a bureaucratic requirement, is required for all nurses, and should be planned and relevant to practice. Engaging in CPD supports safe and effective care.", s:"Understanding the purpose and value of CPD is essential for maintaining professional standards and competence."}},
{id:"BCC-102", t:"single", cn:"BCC", sys:"INTG", topic:"Workplace violence prevention", d:3, b:0.55, cj:"act", tags:["basic care","workplace violence","prevention","safety","risk management"],
 stem:"A nurse is working in an emergency department where incidents of violence toward staff are increasing. Which action by the nurse is most appropriate?",
 opts:["Participate in risk assessment and violence prevention training, and report incidents promptly","Avoid working in the emergency department, since the risk of violence is too high","Confront aggressive clients directly, since this may deter future incidents","Ignore the incidents, since they are part of the job"],
 ans:0, rat:{c:"Workplace violence prevention requires participation in risk assessment, violence prevention training, and prompt reporting of incidents. Avoiding the department, confronting clients directly, or ignoring incidents do not address the underlying risk and may increase danger.", s:"Workplace violence prevention is a shared responsibility; the nurse must understand their role in risk assessment, training, and reporting."}}

]);
