"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 41) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 40: MOC (17.7% vs 18),
 * HPM (8.8% vs 9) and PHA (15.8% vs 16). Every item is
 * difficulty 2 or 3, and the clinical detail is written to be
 * defensible.
 *
 * MOC 6: data protection, GDPR, consent to share information,
 * interoperability, structured data, and documentation burden.
 * HPM 8: learning styles, readiness to learn, transtheoretical
 * model, barriers to adherence, health beliefs, health locus of
 * control, perceived susceptibility, and perceived severity.
 * PHA 6: prescribing cascade, pill organiser, dosette box,
 * compliance aid, adherence aid, and reminder system.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- MOC 6 */
{id:"MOC-203", t:"single", cn:"MOC", sys:"INTG", topic:"Data protection", d:3, b:0.55, cj:"act", tags:["management","data protection","information governance","confidentiality","legal"],
 stem:"A nurse is asked to share a client's medical record with a family member who is not involved in the client's care. The client has not given consent. Which action by the nurse is most appropriate?",
 opts:["Refuse to share the information, since data protection law requires consent or a legal basis for sharing","Share the information, since family members have a right to know even without consent","Share only verbal information, since this is not covered by data protection law","Ask the family member to sign a confidentiality agreement, since this allows sharing"],
 ans:0, rat:{c:"Data protection law requires consent or a legal basis for sharing personal information. Family members do not automatically have a right to access records. Verbal information is also covered, and a confidentiality agreement does not replace consent.", s:"Understanding data protection is essential for lawful information sharing; the nurse must know when consent is required."}},
{id:"MOC-204", t:"single", cn:"MOC", sys:"INTG", topic:"GDPR", d:3, b:0.55, cj:"analyze", tags:["management","GDPR","data protection","privacy","legal"],
 stem:"A nurse is asked to explain the General Data Protection Regulation (GDPR) to a student nurse. Which explanation by the nurse is most accurate?",
 opts:["GDPR is a legal framework that protects personal data and gives individuals rights over their information","GDPR is a guideline that organisations can choose to follow","GDPR applies only to electronic records, not paper records","GDPR is the same as confidentiality and adds no additional requirements"],
 ans:0, rat:{c:"GDPR is a legal framework that protects personal data and gives individuals rights over their information. It is not optional, applies to all records including paper, and adds specific legal requirements beyond general confidentiality.", s:"Understanding GDPR is essential for lawful data handling; the nurse must know the key principles and individual rights."}},
{id:"MOC-205", t:"single", cn:"MOC", sys:"INTG", topic:"Consent to share information", d:3, b:0.55, cj:"act", tags:["management","consent","information sharing","confidentiality","autonomy"],
 stem:"A client with capacity asks the nurse not to share their diagnosis with their spouse. The spouse asks the nurse about the diagnosis. Which action by the nurse is most appropriate?",
 opts:["Respect the client's wishes and do not share the information, since the client has capacity and has refused consent","Share the information, since spouses have a right to know regardless of the client's capacity","Share only general information, since this is not a breach","Ask the spouse to speak to the client directly, since this avoids the nurse's involvement"],
 ans:0, rat:{c:"A client with capacity has the right to control who receives their personal information. The nurse must respect the client's refusal of consent. Spouses do not automatically have a right to access information. Sharing general information or deflecting to the client does not respect the client's wishes.", s:"Consent to share information is a fundamental right; the nurse must respect the client's autonomy."}},
{id:"MOC-206", t:"single", cn:"MOC", sys:"INTG", topic:"Interoperability", d:2, b:0.45, cj:"analyze", tags:["management","interoperability","health informatics","data sharing","systems"],
 stem:"A nurse is transferring a client to another hospital. The receiving hospital uses a different electronic health record system. Which interpretation by the nurse is most accurate?",
 opts:["Interoperability allows different systems to exchange and use information, improving continuity of care","Interoperability is not important, since paper records can be used instead","Interoperability is only relevant to IT staff and not to clinical practice","Interoperability means all hospitals must use the same system rather than different ones"],
 ans:0, rat:{c:"Interoperability allows different systems to exchange and use information, improving continuity of care. It is important for clinical practice, not just IT, and does not require all hospitals to use the same system.", s:"Understanding interoperability is essential for effective information sharing and continuity of care."}},
{id:"MOC-207", t:"single", cn:"MOC", sys:"INTG", topic:"Structured data", d:2, b:0.45, cj:"analyze", tags:["management","structured data","documentation","health informatics","quality"],
 stem:"A nurse is documenting client care in an electronic health record. The system uses structured templates with coded fields. Which interpretation by the nurse is most accurate?",
 opts:["Structured data allows consistent recording and easier retrieval for audit and quality improvement","Structured data is less flexible than free text and reduces the quality of documentation","Structured data is only useful for research and not for clinical care","Structured data is the same as free text documentation"],
 ans:0, rat:{c:"Structured data allows consistent recording and easier retrieval for audit and quality improvement. It is not less flexible or lower quality than free text, is useful for clinical care as well as research, and is different from free text.", s:"Understanding structured data is essential for effective documentation and quality improvement."}},
{id:"MOC-208", t:"single", cn:"MOC", sys:"INTG", topic:"Documentation burden", d:2, b:0.45, cj:"analyze", tags:["management","documentation burden","time","efficiency","quality"],
 stem:"A nurse reports spending more time on documentation than on direct client care. Which interpretation by the nurse is most accurate?",
 opts:["Documentation burden is a recognised issue that can affect care quality and nurse wellbeing and should be addressed","Documentation is always more important than direct care and should take priority","Documentation burden is not a real issue and nurses should manage their time better","Documentation can be reduced by not recording non-essential information"],
 ans:0, rat:{c:"Documentation burden is a recognised issue that can affect care quality and nurse wellbeing and should be addressed through system design and workflow optimisation. Documentation is important but should not take priority over direct care. Reducing documentation by not recording essential information is not appropriate.", s:"Understanding documentation burden is essential for balancing documentation requirements with direct care."}},

/* ---------------------------------------------------------- HPM 8 */
{id:"HPM-104", t:"single", cn:"HPM", sys:"INTG", topic:"Learning styles", d:2, b:0.45, cj:"act", tags:["health promotion","learning styles","education","teaching","individualisation"],
 stem:"A nurse is providing health education to a client. The client reports that they learn best by watching demonstrations rather than reading written information. Which action by the nurse is most appropriate?",
 opts:["Adapt the teaching approach to include demonstrations, since this matches the client's learning style","Provide written information only, since demonstrations are not the standard approach","Ask the client to read the information and ask questions if needed","Explain that learning styles are not important and the client should adapt"],
 ans:0, rat:{c:"Adapting the teaching approach to match the client's learning style improves understanding and retention. Providing written information only, asking the client to read, or dismissing learning styles all fail to individualise education.", s:"Understanding learning styles is essential for effective health education; the nurse must adapt teaching to the client's needs."}},
{id:"HPM-105", t:"single", cn:"HPM", sys:"INTG", topic:"Readiness to learn", d:3, b:0.55, cj:"analyze", tags:["health promotion","readiness to learn","education","assessment","timing"],
 stem:"A nurse is planning to provide discharge education to a client who is anxious and in pain. Which action by the nurse is most appropriate?",
 opts:["Assess readiness to learn and postpone education until the client is more comfortable","Provide the education immediately, since discharge is imminent","Provide the education and repeat it later, since repetition improves retention","Ask a family member to receive the education instead, since the client is not ready"],
 ans:0, rat:{c:"Readiness to learn should be assessed before providing education. An anxious or uncomfortable client is not ready to learn, and education should be postponed until they are more comfortable. Providing education immediately, repeating it, or involving family only do not address the client's readiness.", s:"Assessing readiness to learn is essential for effective education; the nurse must recognise when a client is not ready."}},
{id:"HPM-106", t:"single", cn:"HPM", sys:"INTG", topic:"Transtheoretical model", d:3, b:0.55, cj:"analyze", tags:["health promotion","transtheoretical","stages of change","behaviour change","motivational"],
 stem:"A client with diabetes says they are thinking about changing their diet but are not ready to commit. Which interpretation by the nurse is most accurate?",
 opts:["The client is in the contemplation stage of the transtheoretical model and is considering change but not ready to act","The client is in the precontemplation stage and is not considering change","The client is in the preparation stage and is ready to act","The client is in the action stage and is already making changes"],
 ans:0, rat:{c:"The contemplation stage involves considering change but not being ready to act. Precontemplation involves not considering change. Preparation involves being ready to act. Action involves already making changes.", s:"Understanding the transtheoretical model is essential for tailoring interventions to the client's stage of change."}},
{id:"HPM-107", t:"single", cn:"HPM", sys:"INTG", topic:"Barriers to adherence", d:3, b:0.55, cj:"analyze", tags:["health promotion","barriers to adherence","adherence","assessment","intervention"],
 stem:"A client with hypertension is not taking their medication as prescribed. The client reports that the medication makes them feel tired and they cannot afford the prescription cost. Which interpretation by the nurse is most accurate?",
 opts:["The client has identified barriers to adherence including side effects and cost, which should be addressed","The client is non-compliant and should be advised to take the medication as prescribed","The client does not understand the importance of the medication and requires further education","The client is intentionally avoiding treatment and should be referred to a specialist"],
 ans:0, rat:{c:"The client has identified specific barriers to adherence including side effects and cost. These should be addressed through medication review, cost assistance, or alternative treatments. Advising compliance, providing education only, or referring to a specialist do not address the identified barriers.", s:"Identifying and addressing barriers to adherence is essential for effective treatment; the nurse must assess for modifiable barriers."}},
{id:"HPM-108", t:"single", cn:"HPM", sys:"INTG", topic:"Health beliefs", d:2, b:0.45, cj:"analyze", tags:["health promotion","health beliefs","cultural competence","assessment","individualisation"],
 stem:"A client from a cultural background that uses traditional healing practices asks about combining these with prescribed medication. Which action by the nurse is most appropriate?",
 opts:["Explore the client's health beliefs, assess for interactions, and support safe integration where possible","Advise the client to stop traditional practices, since these are not evidence-based","Advise the client to stop prescribed medication, since traditional practices are preferred","Do not discuss traditional practices, since these are not relevant to nursing care"],
 ans:0, rat:{c:"Exploring health beliefs, assessing for interactions, and supporting safe integration where possible respects the client's cultural background while ensuring safety. Advising against traditional practices or medication, or not discussing them, all fail to provide individualised care.", s:"Understanding health beliefs is essential for culturally competent care; the nurse must respect and integrate beliefs where safe."}},
{id:"HPM-109", t:"single", cn:"HPM", sys:"INTG", topic:"Health locus of control", d:3, b:0.55, cj:"analyze", tags:["health promotion","health locus of control","self-efficacy","behaviour change","psychology"],
 stem:"A client with chronic obstructive pulmonary disease says, 'There's no point in trying to quit smoking; my health is out of my control.' Which interpretation by the nurse is most accurate?",
 opts:["The client has an external health locus of control and believes health outcomes are determined by external factors","The client has an internal health locus of control and believes they can influence their health","The client is in denial about their condition","The client is not motivated to change"],
 ans:0, rat:{c:"An external health locus of control involves believing health outcomes are determined by external factors rather than personal actions. An internal locus involves believing one can influence health. Denial and lack of motivation are not the most accurate interpretations.", s:"Understanding health locus of control is essential for tailoring interventions to enhance self-efficacy and behaviour change."}},
{id:"HPM-110", t:"single", cn:"HPM", sys:"INTG", topic:"Perceived susceptibility", d:2, b:0.45, cj:"analyze", tags:["health promotion","perceived susceptibility","health belief model","risk perception","behaviour change"],
 stem:"A client at high risk for type 2 diabetes says, 'I don't think I'm at risk; it runs in my family but I'm healthy.' Which interpretation by the nurse is most accurate?",
 opts:["The client has low perceived susceptibility and does not believe they are at risk","The client has high perceived susceptibility and is concerned about their risk","The client is in denial about their risk","The client is not motivated to change"],
 ans:0, rat:{c:"Low perceived susceptibility involves not believing one is at risk. High perceived susceptibility involves being concerned about risk. Denial and lack of motivation are not the most accurate interpretations.", s:"Understanding perceived susceptibility is essential for tailoring risk communication and behaviour change interventions."}},
{id:"HPM-111", t:"single", cn:"HPM", sys:"INTG", topic:"Perceived severity", d:2, b:0.45, cj:"analyze", tags:["health promotion","perceived severity","health belief model","risk perception","behaviour change"],
 stem:"A client with hypertension says, 'High blood pressure isn't serious; I don't have any symptoms.' Which interpretation by the nurse is most accurate?",
 opts:["The client has low perceived severity and does not believe the condition is serious","The client has high perceived severity and believes the condition is serious","The client is in denial about their condition","The client is not motivated to change"],
 ans:0, rat:{c:"Low perceived severity involves not believing a condition is serious. High perceived severity involves being concerned about the condition. Denial and lack of motivation are not the most accurate interpretations.", s:"Understanding perceived severity is essential for tailoring risk communication and behaviour change interventions."}},

/* ---------------------------------------------------------- PHA 6 */
{id:"PHA-189", t:"single", cn:"PHA", sys:"INTG", topic:"Prescribing cascade", d:3, b:0.55, cj:"analyze", tags:["pharmacology","prescribing cascade","polypharmacy","adverse effects","medication review"],
 stem:"A client taking an antihypertensive develops ankle swelling. A diuretic is prescribed to treat the swelling. Which interpretation by the nurse is most accurate?",
 opts:["This is a prescribing cascade, where a new medication is prescribed to treat an adverse effect of another medication","This is appropriate treatment to treat ankle swelling, since diuretics are indicated","This is not a prescribing cascade, since the medications are for different conditions","This is an example of polypharmacy, but not a prescribing cascade"],
 ans:0, rat:{c:"A prescribing cascade occurs when a new medication is prescribed to treat an adverse effect of another medication. This is not appropriate treatment, is a prescribing cascade, and is a specific type of polypharmacy.", s:"Understanding prescribing cascades is essential for medication review; the nurse must recognise when a new symptom may be an adverse effect."}},
{id:"PHA-190", t:"single", cn:"PHA", sys:"INTG", topic:"Pill organiser", d:2, b:0.45, cj:"act", tags:["pharmacology","pill organiser","adherence","compliance aid","medication management"],
 stem:"A client with multiple medications has difficulty remembering which tablets to take at which times. Which action by the nurse is most appropriate?",
 opts:["Suggest a pill organiser to help the client manage their medication schedule","Advise the client to stop taking the medications, since they are not adherent","Simplify the regimen by stopping all medications, since this is safer","Refer the client to a care home, since they cannot manage their medication"],
 ans:0, rat:{c:"A pill organiser helps clients manage complex medication schedules and improves adherence. Advising against medications, simplifying by stopping all, or referring to a care home are not appropriate responses to adherence difficulties.", s:"Understanding adherence aids is essential for supporting medication management; the nurse must be able to suggest appropriate tools."}},
{id:"PHA-191", t:"single", cn:"PHA", sys:"INTG", topic:"Dosette box", d:2, b:0.45, cj:"act", tags:["pharmacology","dosette box","adherence","compliance aid","medication management"],
 stem:"A client with cognitive impairment has difficulty managing their medication independently. Which action by the nurse is most appropriate?",
 opts:["Suggest a dosette box prepared by a pharmacy to support safe medication administration","Advise the client to stop taking the medications, since they are not able to manage","Simplify the regimen by stopping all medications, since this is safer","Refer the client to a care home, since they cannot manage their medication"],
 ans:0, rat:{c:"A dosette box prepared by a pharmacy supports safe medication administration for clients with cognitive impairment. Advising against medications, simplifying by stopping all, or referring to a care home are not appropriate responses.", s:"Understanding dosette boxes is essential for supporting medication management in clients with cognitive impairment."}},
{id:"PHA-192", t:"single", cn:"PHA", sys:"INTG", topic:"Compliance aid", d:2, b:0.45, cj:"act", tags:["pharmacology","compliance aid","adherence","medication management","support"],
 stem:"A client reports frequently missing doses of their medication. The client has a busy lifestyle and forgets to take tablets. Which action by the nurse is most appropriate?",
 opts:["Explore compliance aids such as alarms, apps, or pill organisers to support adherence","Advise the client to prioritise medication over other activities","Simplify the regimen by stopping all medications, since this is safer","Refer the client to a specialist, since they are not adherent"],
 ans:0, rat:{c:"Compliance aids such as alarms, apps, or pill organisers support adherence for clients with busy lifestyles. Advising prioritisation, simplifying by stopping all, or referring to a specialist are not appropriate first-line responses.", s:"Understanding compliance aids is essential for supporting adherence; the nurse must be able to suggest appropriate tools."}},
{id:"PHA-193", t:"single", cn:"PHA", sys:"INTG", topic:"Adherence aid", d:2, b:0.45, cj:"act", tags:["pharmacology","adherence aid","adherence","medication management","technology"],
 stem:"A client with multiple medications asks about using a smartphone app to help them remember doses. Which action by the nurse is most appropriate?",
 opts:["Support the use of an adherence aid app, since this may improve medication management","Advise against using an app, since this is not a reliable method","Simplify the regimen by stopping all medications, since this is safer","Refer the client to a specialist, since they need more support"],
 ans:0, rat:{c:"Adherence aid apps can improve medication management and should be supported. Advising against apps, simplifying by stopping all, or referring to a specialist are not appropriate responses.", s:"Understanding adherence aids including technology is essential for supporting medication management."}},
{id:"PHA-194", t:"single", cn:"PHA", sys:"INTG", topic:"Reminder system", d:2, b:0.45, cj:"act", tags:["pharmacology","reminder system","adherence","medication management","support"],
 stem:"A client reports missing doses of their medication because they forget. The client asks for suggestions. Which action by the nurse is most appropriate?",
 opts:["Suggest a reminder system such as alarms, calendar alerts, or linking doses to daily routines","Advise the client to try harder to remember their doses, since this is their responsibility","Simplify the regimen by stopping all medications, since this is safer","Refer the client to a specialist, since they are not adherent"],
 ans:0, rat:{c:"Reminder systems such as alarms, calendar alerts, or linking doses to daily routines support adherence. Advising the client to try harder, simplifying by stopping all, or referring to a specialist are not appropriate first-line responses.", s:"Understanding reminder systems is essential for supporting adherence; the nurse must be able to suggest practical strategies."}}

]);
