"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 39) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 38: MOC (17.9% vs 18),
 * PHA (15.9% vs 16) and PAA (13.8% vs 14). Every item is
 * difficulty 2 or 3, and the clinical detail is written to be
 * defensible.
 *
 * MOC 5: clinical governance, harm prevention, quality improvement
 * methodology, audit and feedback, and benchmarking.
 * SIC 6: falls prevention, pressure ulcer prevention, needle stick
 * injury, blood-borne virus exposure, sharps safety, and
 * environmental hazards.
 * PHA 5: anticoagulation monitoring, warfarin monitoring, anti-Xa
 * monitoring, platelet count monitoring, and haemoglobin monitoring.
 * PAA 4: immunisation, health surveillance, FFP3 respirator use,
 * and occupational health referral.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- MOC 5 */
{id:"MOC-198", t:"single", cn:"MOC", sys:"INTG", topic:"Clinical governance", d:3, b:0.55, cj:"analyze", tags:["management","clinical governance","quality","accountability","systems"],
 stem:"A nurse is asked to explain clinical governance to a student nurse. Which explanation by the nurse is most accurate?",
 opts:["Clinical governance is the framework through which organisations are accountable for continuously improving quality and safeguarding high standards of care","Clinical governance is a form of performance management that monitors individual nurse performance","Clinical governance is a bureaucratic requirement that has no impact on patient care","Clinical governance is only relevant to senior managers and not to frontline nurses"],
 ans:0, rat:{c:"Clinical governance is the framework through which organisations are accountable for continuously improving quality and safeguarding high standards of care. It is not performance management, not a bureaucratic requirement, and is relevant to all nurses, not just senior managers.", s:"Understanding clinical governance is essential for professional accountability and quality improvement."}},
{id:"MOC-199", t:"single", cn:"MOC", sys:"INTG", topic:"Harm prevention", d:3, b:0.55, cj:"act", tags:["management","harm prevention","safety","risk management","proactive"],
 stem:"A ward has experienced several medication errors in the past month. The clinical team wants to implement harm prevention strategies. Which action by the nurse is most appropriate?",
 opts:["Participate in root cause analysis and implement system changes to prevent future errors","Focus on individual accountability and implement stricter procedures for nurses to follow","Increase supervision of junior staff, since they are more likely to make errors","Do not report minor errors, since this will reduce the reported error rate"],
 ans:0, rat:{c:"Harm prevention requires a systems approach, including root cause analysis and system changes to prevent future errors. Focusing on individual accountability, increasing supervision, or not reporting errors all fail to address the underlying system issues and may increase risk.", s:"Harm prevention requires a just culture and systems thinking; the nurse must understand their role in identifying and addressing system failures."}},
{id:"MOC-200", t:"single", cn:"MOC", sys:"INTG", topic:"Quality improvement methodology", d:2, b:0.45, cj:"act", tags:["management","quality improvement","methodology","PDSA","change"],
 stem:"A nurse is leading a quality improvement project to reduce catheter-associated urinary tract infections. Which approach by the nurse is most appropriate?",
 opts:["Use a structured methodology such as Plan-Do-Study-Act cycles to test changes and measure improvement","Implement all changes at once for rapid improvement, since this is more efficient","Focus on education alone, since knowledge deficits are the main cause of infections","Wait for national guidelines to be published before making any changes"],
 ans:0, rat:{c:"Quality improvement requires a structured methodology such as Plan-Do-Study-Act cycles to test changes, measure improvement, and refine the approach. Implementing all changes at once, focusing on education alone, or waiting for guidelines are not effective quality improvement approaches.", s:"Understanding quality improvement methodology is essential for leading effective change and improving patient outcomes."}},
{id:"MOC-201", t:"single", cn:"MOC", sys:"INTG", topic:"Audit and feedback", d:2, b:0.45, cj:"evaluate", tags:["management","audit","feedback","quality","monitoring"],
 stem:"A nurse participates in a clinical audit of hand hygiene compliance. The results show compliance has fallen from 90% to 70%. Which action by the nurse is most appropriate?",
 opts:["Share the results with the team, discuss barriers, and implement targeted interventions","Keep the results confidential, since poor compliance may be embarrassing","Focus on individual nurses with low compliance, since this will improve overall rates","Repeat the audit in six months, since compliance may improve without intervention"],
 ans:0, rat:{c:"Audit and feedback require sharing results with the team, discussing barriers, and implementing targeted interventions. Keeping results confidential, focusing on individuals, or repeating the audit without intervention all fail to drive improvement.", s:"Audit and feedback is a core quality improvement tool; the nurse must understand how to use results to drive change."}},
{id:"MOC-202", t:"single", cn:"MOC", sys:"INTG", topic:"Benchmarking", d:2, b:0.45, cj:"analyze", tags:["management","benchmarking","comparison","standards","quality"],
 stem:"A nurse is comparing their ward's falls rate with national data. The ward's rate is higher than the national average. Which interpretation by the nurse is most accurate?",
 opts:["Benchmarking identifies areas for improvement by comparing local performance with external standards","Benchmarking is only useful if the local performance is better than the external standard","Benchmarking is a form of competition comparing wards and should be used to rank them","Benchmarking is not relevant to falls prevention"],
 ans:0, rat:{c:"Benchmarking identifies areas for improvement by comparing local performance with external standards. It is useful regardless of whether local performance is better or worse, is not a form of competition, and is relevant to falls prevention and other quality indicators.", s:"Understanding benchmarking is essential for quality improvement; the nurse must be able to interpret comparative data and identify areas for action."}},

/* ---------------------------------------------------------- SIC 6 */
{id:"SIC-150", t:"single", cn:"SIC", sys:"MSK", topic:"Falls prevention", d:3, b:0.55, cj:"act", tags:["safety","falls prevention","risk assessment","multifactorial","intervention"],
 stem:"An 82-year-old client is assessed as high risk for falls. The client is confused, takes multiple medications, and has poor mobility. Which action by the nurse is most appropriate?",
 opts:["Implement a multifactorial falls prevention plan addressing confusion, medication review, and mobility","Restrict the client to bed to limit mobility, since this will prevent falls","Increase observation only, since the client cannot be prevented from falling","Discharge the client, since the risk is too high to manage on the ward"],
 ans:0, rat:{c:"Falls prevention requires a multifactorial plan addressing all identified risk factors, including confusion, medication review, and mobility. Restricting to bed, increasing observation only, or discharging the client are not appropriate falls prevention strategies.", s:"Falls prevention is multifactorial; the nurse must understand how to assess risk and implement targeted interventions."}},
{id:"SIC-151", t:"single", cn:"SIC", sys:"INTG", topic:"Pressure ulcer prevention", d:3, b:0.55, cj:"act", tags:["safety","pressure ulcer prevention","risk assessment","repositioning","skin care"],
 stem:"A client is assessed as high risk for pressure ulcers. The client is immobile, has poor nutrition, and has moist skin. Which action by the nurse is most appropriate?",
 opts:["Implement a pressure ulcer prevention plan including repositioning, pressure-relieving equipment, skin care, and nutritional support","Reposition the client only when they request it, since this respects their autonomy","Apply barrier cream only, since this will protect the skin from pressure damage","Do not use pressure-relieving equipment, since it is uncomfortable"],
 ans:0, rat:{c:"Pressure ulcer prevention requires a comprehensive plan including repositioning, pressure-relieving equipment, skin care, and nutritional support. Repositioning only on request, applying barrier cream only, or avoiding pressure-relieving equipment all fail to address the multifactorial risk.", s:"Pressure ulcer prevention is multifactorial; the nurse must understand how to assess risk and implement targeted interventions."}},
{id:"SIC-152", t:"single", cn:"SIC", sys:"INTG", topic:"Needle stick injury", d:3, b:0.55, cj:"act", tags:["safety","needle stick","occupational exposure","post-exposure prophylaxis","reporting"],
 stem:"A nurse sustains a needle stick injury from a used needle. The source client's blood-borne virus status is unknown. Which action by the nurse is the priority?",
 opts:["Wash the wound, report the incident immediately, and seek occupational health assessment for post-exposure prophylaxis","Wait to see if any symptoms develop before seeking assessment","Report the incident but do not seek assessment, since the risk is low","Do not report the incident, since this may affect the nurse's record"],
 ans:0, rat:{c:"A needle stick injury requires immediate wound washing, incident reporting, and occupational health assessment for post-exposure prophylaxis. Waiting for symptoms, not seeking assessment, or not reporting all increase the risk of infection and breach occupational health requirements.", s:"Needle stick injury management requires prompt action; the nurse must understand the immediate steps and the importance of reporting."}},
{id:"SIC-153", t:"single", cn:"SIC", sys:"INTG", topic:"Blood-borne virus exposure", d:3, b:0.55, cj:"act", tags:["safety","blood-borne virus","occupational exposure","hepatitis B","HIV"],
 stem:"A nurse is exposed to a client's blood through a mucous membrane splash. The client is known to be hepatitis B positive. The nurse's hepatitis B vaccination status is unknown. Which action by the nurse is the priority?",
 opts:["Seek immediate occupational health assessment for hepatitis B immunoglobulin and vaccination","Wait to see if any hepatitis symptoms develop before seeking vaccination or assessment","Report the incident but do not seek assessment, since the risk is low","Do not report the incident, since this may affect the nurse's record"],
 ans:0, rat:{c:"Blood-borne virus exposure requires immediate occupational health assessment for post-exposure prophylaxis, including hepatitis B immunoglobulin and vaccination if indicated. Waiting for symptoms, not seeking assessment, or not reporting all increase the risk of infection and breach occupational health requirements.", s:"Blood-borne virus exposure management requires prompt action; the nurse must understand the immediate steps and the importance of seeking assessment."}},
{id:"SIC-154", t:"single", cn:"SIC", sys:"INTG", topic:"Sharps safety", d:2, b:0.45, cj:"act", tags:["safety","sharps","disposal","injury prevention","standard precautions"],
 stem:"A nurse has used a needle and syringe to administer an injection. Which action by the nurse is most appropriate for sharps disposal?",
 opts:["Dispose of the needle and syringe immediately into a sharps container at the point of use","Recap the needle before disposal, since this prevents injury","Place the sharps in general waste, since this is more convenient","Pass the needle and syringe to a colleague for disposal, since this is safer"],
 ans:0, rat:{c:"Sharps must be disposed of immediately into a sharps container at the point of use. Recapping, placing in general waste, or passing to a colleague all increase the risk of injury. Point-of-use disposal is the safest approach.", s:"Sharps safety is a core infection prevention requirement; the nurse must understand safe disposal practices."}},
{id:"SIC-155", t:"single", cn:"SIC", sys:"INTG", topic:"Environmental hazards", d:2, b:0.45, cj:"act", tags:["safety","environmental hazards","risk assessment","prevention","ward safety"],
 stem:"A nurse notices that a ward floor is wet following a spill. Which action by the nurse is the priority?",
 opts:["Place a wet floor sign, clean the spill immediately, and ensure the area is dry before allowing access","Leave the spill and inform the cleaning team, since this is their responsibility","Walk around the wet floor and continue with duties, since the risk is low","Inform clients to avoid the area, since this is sufficient"],
 ans:0, rat:{c:"A wet floor is an immediate environmental hazard requiring a wet floor sign, immediate cleaning, and ensuring the area is dry before allowing access. Leaving the spill, walking around it, or informing clients only all fail to address the immediate risk.", s:"Environmental hazard management requires prompt action; the nurse must understand their role in maintaining a safe environment."}},

/* ---------------------------------------------------------- PHA 5 */
{id:"PHA-184", t:"single", cn:"PHA", sys:"HEME", topic:"Anticoagulation monitoring", d:3, b:0.55, cj:"act", tags:["pharmacology","anticoagulation","monitoring","safety","bleeding risk"],
 stem:"A client is starting warfarin for atrial fibrillation. The client asks how often their international normalised ratio will be checked. Which response by the nurse is most appropriate?",
 opts:["Explain that monitoring is frequent initially and then less often once stable, but regular monitoring is required indefinitely","Explain that monitoring is often only needed for the first month","Explain that monitoring is not needed if the client feels well","Explain that monitoring can be stopped once the international normalised ratio is in range"],
 ans:0, rat:{c:"Warfarin requires frequent monitoring initially and then less often once stable, but regular monitoring is required indefinitely. Monitoring is not only needed for the first month, is needed regardless of how the client feels, and cannot be stopped once in range.", s:"Understanding anticoagulation monitoring is essential for safe warfarin administration; the nurse must be able to explain the monitoring requirements."}},
{id:"PHA-185", t:"single", cn:"PHA", sys:"HEME", topic:"Warfarin monitoring", d:3, b:0.55, cj:"act", tags:["pharmacology","warfarin","monitoring","INR","dose adjustment"],
 stem:"A client taking warfarin has an international normalised ratio of 5.2 (target 2-3). The client has no signs of bleeding. Which action by the nurse is most appropriate?",
 opts:["Withhold warfarin, monitor the international normalised ratio, and consider vitamin K if the international normalised ratio remains high or bleeding occurs","Continue warfarin at the current dose, since the client has no bleeding","Increase the warfarin dose, since the international normalised ratio may fall","Administer vitamin K immediately, since the international normalised ratio is high"],
 ans:0, rat:{c:"An international normalised ratio of 5.2 without bleeding requires withholding warfarin, monitoring, and considering vitamin K if the ratio remains high or bleeding occurs. Continuing or increasing the dose is unsafe. Administering vitamin K immediately may not be necessary without bleeding.", s:"Warfarin monitoring requires understanding of dose adjustment and management of high international normalised ratios."}},
{id:"PHA-186", t:"single", cn:"PHA", sys:"HEME", topic:"Anti-Xa monitoring", d:3, b:0.55, cj:"analyze", tags:["pharmacology","anti-Xa","monitoring","low molecular weight heparin","obesity"],
 stem:"A client with obesity is receiving low molecular weight heparin for treatment of deep vein thrombosis. The clinical team requests anti-Xa monitoring. Which interpretation by the nurse is most accurate?",
 opts:["Anti-Xa monitoring is indicated in obesity, since standard weight-based dosing may not achieve therapeutic levels","Anti-Xa monitoring is not indicated in obesity, since low molecular weight heparin does not require monitoring","Anti-Xa monitoring is indicated only for prophylactic doses, not treatment doses","Anti-Xa monitoring is the same as activated partial thromboplastin time monitoring"],
 ans:0, rat:{c:"Anti-Xa monitoring is indicated in obesity, renal impairment, and pregnancy, since standard weight-based dosing may not achieve therapeutic levels. Low molecular weight heparin does not require routine monitoring, but anti-Xa monitoring is indicated in specific situations. Anti-Xa monitoring is not the same as activated partial thromboplastin time monitoring.", s:"Understanding when anti-Xa monitoring is indicated is essential for safe low molecular weight heparin administration."}},
{id:"PHA-187", t:"single", cn:"PHA", sys:"HEME", topic:"Platelet count monitoring", d:2, b:0.45, cj:"act", tags:["pharmacology","platelet count","monitoring","heparin","HIT"],
 stem:"A client receiving unfractionated heparin has a platelet count that falls from 250,000 to 120,000 over five days. Which action by the nurse is most appropriate?",
 opts:["Report the fall immediately, since this may indicate heparin-induced thrombocytopenia and requires urgent assessment","Continue heparin, since the platelet count is still above 100,000","Repeat the platelet count in one week, since this may be a laboratory error","Administer a platelet transfusion, since the count has fallen significantly"],
 ans:0, rat:{c:"A fall in platelet count of more than 50% during heparin therapy may indicate heparin-induced thrombocytopenia and requires immediate reporting and urgent assessment. Continuing heparin, repeating in one week, or administering platelets all fail to address the potential diagnosis.", s:"Platelet count monitoring is essential during heparin therapy; the nurse must recognise the significance of a significant fall."}},
{id:"PHA-188", t:"single", cn:"PHA", sys:"HEME", topic:"Haemoglobin monitoring", d:2, b:0.45, cj:"act", tags:["pharmacology","haemoglobin","monitoring","anaemia","transfusion"],
 stem:"A client has a haemoglobin of 75 g/L and is symptomatic with fatigue and shortness of breath. The clinical team is considering transfusion. Which action by the nurse is most appropriate?",
 opts:["Monitor the client's symptoms and vital signs closely, and prepare for possible transfusion as prescribed","Administer iron supplements instead of transfusion, since this will raise the haemoglobin","Advise the client to rest, since this will improve symptoms","Do not monitor, since the haemoglobin is not critically low"],
 ans:0, rat:{c:"A symptomatic client with haemoglobin of 75 g/L requires close monitoring of symptoms and vital signs, and preparation for possible transfusion as prescribed. Iron supplements, rest alone, or not monitoring all fail to address the symptomatic anaemia.", s:"Haemoglobin monitoring is essential for managing anaemia; the nurse must understand the significance of symptoms and the indications for transfusion."}},

/* ---------------------------------------------------------- PAA 4 */
{id:"PAA-153", t:"single", cn:"PAA", sys:"INF", topic:"Immunisation", d:2, b:0.45, cj:"act", tags:["adaptation","immunisation","vaccination","prevention","occupational health"],
 stem:"A nurse is starting a new role in an emergency department. Occupational health advises that hepatitis B vaccination is recommended. Which action by the nurse is most appropriate?",
 opts:["Complete the hepatitis B vaccination course and have antibody titre checked to confirm immunity","Decline hepatitis B vaccination, since it is not mandatory","Complete vaccination but do not check antibody titre, since this is not necessary","Wait until exposure occurs before seeking vaccination"],
 ans:0, rat:{c:"Hepatitis B vaccination is recommended for healthcare workers at risk of exposure. Completing the course and checking antibody titre confirms immunity. Declining vaccination, not checking titre, or waiting for exposure all fail to ensure protection.", s:"Immunisation is a core occupational health requirement; the nurse must understand the importance of vaccination and titre checking."}},
{id:"PAA-154", t:"single", cn:"PAA", sys:"INTG", topic:"Health surveillance", d:2, b:0.45, cj:"act", tags:["adaptation","health surveillance","occupational health","monitoring","prevention"],
 stem:"A nurse works in a role with exposure to hazardous substances. Occupational health advises regular health surveillance. Which interpretation by the nurse is most accurate?",
 opts:["Health surveillance monitors for early signs of work-related ill health and allows early intervention","Health surveillance is a form of performance monitoring and may affect career progression","Health surveillance is only required if the nurse develops symptoms","Health surveillance is optional and can be declined without consequence"],
 ans:0, rat:{c:"Health surveillance monitors for early signs of work-related ill health and allows early intervention. It is not performance monitoring, is not only required if symptoms develop, and is a legal requirement for certain roles. Engaging in health surveillance protects the nurse's health.", s:"Understanding health surveillance is essential for occupational health; the nurse must recognise its purpose and importance."}},
{id:"PAA-155", t:"single", cn:"PAA", sys:"RESP", topic:"FFP3 respirator use", d:3, b:0.55, cj:"act", tags:["adaptation","FFP3","respirator","respiratory protection","fit testing"],
 stem:"A nurse is required to care for a client with suspected tuberculosis. The nurse is issued an FFP3 respirator. Which action by the nurse is most appropriate?",
 opts:["Ensure the respirator is fit-tested and perform a fit check before each use","Use the respirator without fit testing, since it will provide adequate protection","Use a surgical mask instead, since this is more comfortable","Do not use respiratory protection, since the risk is low"],
 ans:0, rat:{c:"FFP3 respirators require fit testing and a fit check before each use to ensure an adequate seal. Using without fit testing, using a surgical mask, or not using protection all fail to provide adequate respiratory protection.", s:"Respiratory protection requires fit testing and fit checking; the nurse must understand the importance of these steps."}},
{id:"PAA-156", t:"single", cn:"PAA", sys:"INTG", topic:"Occupational health referral", d:2, b:0.45, cj:"act", tags:["adaptation","occupational health","referral","support","workplace adjustment"],
 stem:"A nurse is experiencing back pain that is affecting their ability to perform manual handling tasks. Which action by the nurse is most appropriate?",
 opts:["Seek occupational health referral for assessment and possible workplace adjustment","Continue working without disclosure, since seeking help may affect their career","Resign from the role, since they are no longer fit to practise","Ignore the pain, since it will resolve with time"],
 ans:0, rat:{c:"Occupational health referral allows assessment and possible workplace adjustment to support the nurse's health and ability to work. Continuing without disclosure, resigning, or ignoring the pain all fail to address the underlying issue and may worsen the problem.", s:"Occupational health referral is a valuable resource; the nurse must understand when and how to seek support."}}

]);
