/* RN Ready — item bank v3i · part 9 (bank growth toward the 2026 blueprints).
   Census at 248 showed MSK 14 · INTG 14 · REPI 15 as the thinnest systems, so this
   batch is weighted there (MSK +9 · INTG +5 · REPI +4 · GI +3 · RESP +2 · NEURO +2 ·
   CV +1 · PSYCH +2 · ENDO +2) while keeping client-need balance (MOC +4 · SIC +4 ·
   HPM +3 · PSY +3 · BCC +3 · PHA +4 · RRP +4 · PAA +5) and format diversity
   (multi ×3, matrix ×2, cloze ×2, drag, hotspot). New variant group: cast-compartment
   (adult presentation + pediatric select-all).  */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Management of Care ────────────────────────────────────────────── */
{id:"MOC-045", t:"single", cn:"MOC", sys:"MSK", topic:"Restraints", d:2, b:0.3, cj:"evaluate", tags:["restraints","regulatory","safety"],
 stem:"A confused client with a hip fracture keeps attempting to climb over the bed rails, and the team has placed bilateral wrist restraints after alternatives failed. Which requirement for ongoing use must the nurse ensure?",
 opts:["A new provider evaluation and renewal order within the required time limit, plus documentation of the less-restrictive measures attempted",
  "A sitter at the bedside whenever restraints are in use, with no exceptions permitted",
  "Removal of the restraints for good once the client falls asleep for the night",
  "A family member's signed consent before each shift the restraints remain in place"],
 ans:0,
 rat:{c:"Restraints require a time-limited provider order (adult: renew per policy, e.g., q24h evaluation), ongoing behavioral monitoring, documented alternatives attempted first, and removal at the earliest safe moment. Sitters are an alternative to try — not a co-requirement — and neither sleep-based removal nor family consent per shift is a regulatory standard.",
  o:["Correct — time-limited orders with renewal and documented de-escalation attempts are the core requirements.",
    "A sitter is one alternative to attempt, not a mandatory companion to restraints.",
    "Removal is based on behavior and reassessment, not sleep timing.",
    "Family consent is good practice for transparency but is not the regulatory requirement asked about."],
  s:"Restraint rules in one line: alternatives documented → time-limited order → frequent monitoring → remove as soon as safe."},
 ref:"Restraints · regulatory standards"},

{id:"MOC-046", t:"single", cn:"MOC", sys:"GI", topic:"HIPAA", d:1, b:0.05, cj:"recognize", tags:["hipaa","confidentiality","disclosure"],
 stem:"Which use of a client's protected health information is permitted without the client's written authorization?",
 opts:["Discussion of the client's colitis flare with the covering provider who is assuming care tonight",
  "Sharing the client's laboratory results with an employer adjusting the work schedule",
  "Giving a phone update to a friend who calls and states the client would want them informed",
  "Posting a photograph of a wound on a professional social media account without identifiers visible"],
 ans:0,
 rat:{c:"Treatment, payment, and health-care operations (TPO) permit use and disclosure without written authorization — sharing with the covering provider is treatment. Employers, unverified friends, and public posting fall outside TPO and need authorization or verification.",
  o:["Correct — provider-to-provider handoff is treatment, permitted under TPO.",
    "Employers are outside TPO; disclosure requires the client's written authorization.",
    "Clients designate who may receive updates — staff must verify before sharing (or check a release on file).",
    "Public posting of client imagery is never routine practice, identifiers or not."],
  s:"No-authorization disclosures = TPO (treatment, payment, operations). Everyone else asks first."},
 ref:"HIPAA · permitted disclosures"},

{id:"MOC-047", t:"matrix", cn:"MOC", sys:"RESP", topic:"Quality improvement", d:2, b:0.25, cj:"analyze", tags:["qi","process-vs-outcome","measures"],
 stem:"A medical unit is launching a quality-improvement project to reduce postoperative pulmonary complications. For each potential measure, decide whether it is a PROCESS measure (did we do the right thing?) or an OUTCOME measure (did the client do better?).",
 matrix:{cols:["Process measure","Outcome measure"], rows:[
  "Percent of postoperative clients who used incentive spirometry 10 times each shift",
  "Postoperative pneumonia rate per 100 surgical discharges",
  "Percent of documented early-mobility orders completed on day one after surgery",
  "Rate of unplanned reintubation within 48 hours after surgery",
  "Percent of nurses completing the annual cough-and-deep-breathe competency"
 ], mode:"one", ans:[0,1,0,1,0]},
 rat:{c:"Process measures track whether the care we control actually happened (spirometry use, mobility orders, staff competency); outcome measures track what happened to clients (pneumonia, reintubation). QI teams improve process measures to move outcome measures.",
  s:"Ask: does this metric describe something the TEAM DOES (process) or something the CLIENT EXPERIENCED (outcome)?"},
 ref:"Quality improvement · measures"},

{id:"MOC-048", t:"drag", cn:"MOC", sys:"REPI", topic:"Verbal orders", d:2, b:0.2, cj:"generate", tags:["verbal-orders","read-back","communication"],
 stem:"A provider gives the nurse a verbal order over the phone for a postpartum client. Order the nurse's actions from FIRST to LAST.",
 drag:{targets:["1 — First","2","3","4 — Last"],
  opts:[
   "Write down the order with the client's identifiers, drug, dose, route, and rate as heard",
   "Read the complete order back to the provider, including drug spelling and numbers",
   "Confirm the provider's agreement with any correction, then transcribe the verified order",
   "Have the provider countersign the order within the required timeframe"
  ],
  ans:[0,1,2,3]},
 rat:{c:"Verbal-order safety is write → read back → confirm → countersign. Writing first captures exactly what was heard; read-back with number-and-drug spelling closes the loop; transcription follows verification; countersigning completes the regulatory record within the set window.",
  o:["Correct — record the order verbatim before anything else.",
    "Correct — read back numbers aloud digit-by-digit and spell look-alike drugs.",
    "Correct — only a provider-confirmed order enters the chart.",
    "Correct — the signature completes the verbal-order trail."],
  s:"Verbal orders: WRITE it, READ it back, GET agreement, GET the signature. Each step depends on the one before it."},
 ref:"Verbal orders · read-back protocol"},

/* ── Safety and Infection Control ──────────────────────────────────── */
{id:"SIC-033", t:"single", cn:"SIC", sys:"MSK", topic:"Compartment syndrome", d:2, b:0.3, cj:"recognize", tags:["compartment-syndrome","cast","neurovascular"], variantGroup:"cast-compartment",
 stem:"A young adult in a long leg cast for a tibial fracture reports increasing deep calf pain despite two doses of the prescribed opioid. Which finding makes the nurse suspect compartment syndrome most strongly?",
 opts:["Pain that intensifies when the nurse gently dorsiflexes the foot of the affected leg",
  "A pressure sore area of erythema where the cast edge rubs the heel",
  "Mild ankle swelling visible in the spaces around the cast margin",
  "Dark, dried blood staining less than a coin-sized area of the cast"],
 ans:0,
 rat:{c:"Early compartment syndrome = pain out of proportion, unrelieved by opioids, and sharply worsened by passive stretch of the muscles in the compartment (dorsiflexion stretches the calf). Cast-edge irritation, marginal swelling, and small dried drainage spots are routine cast findings.",
  o:["Correct — pain with passive stretch is the hallmark earliest sign.",
    "Cast-edge erythema is a skin issue, not a perfusion issue.",
    "Some swelling at the cast margin is expected after injury.",
    "Small spots of dried blood that do not enlarge are monitored, not alarmed over — but spot SPREAD is a different story."],
  s:"Compartment syndrome ears: pain out of proportion + pain on passive stretch + analgesia failure. Pulse changes come LATE — never wait for them."},
 ref:"Compartment syndrome · adult cast care"},

{id:"SIC-034", t:"single", cn:"SIC", sys:"INTG", topic:"Stevens-Johnson syndrome", d:2, b:0.35, cj:"analyze", tags:["sjs","adverse-drug-reaction","escalation"],
 stem:"A client started a new anticonvulsant two weeks ago and now has fever, painful mouth ulcers, and a spreading rash with target lesions and flaccid bullae. Which action should the nurse take first?",
 opts:["Stop further doses of the suspected medication with the provider and escalate for emergency evaluation",
  "Apply topical hydrocortisone cream to the rash and reevaluate in the morning",
  "Gently debride the loose bullae and cover them with a transparent film dressing",
  "Continue the medication and give an antihistamine for what appears to be a drug rash"],
 ans:0,
 rat:{c:"Fever + mucosal involvement + target lesions + Nikolsky-sign bullae two weeks after a new anticonvulsant is Stevens-Johnson syndrome / toxic epidermal necrolysis — a dermatologic emergency. The first move is stopping the culprit drug and escalating (burn-unit-level care). Steroid cream, debridement, and continuing the drug all delay the one intervention that changes outcomes.",
  o:["Correct — withdrawal of the causative agent plus emergency transfer is the priority.",
    "A topical steroid cannot alter a systemic keratinocyte necrosis process.",
    "Loose skin is left in place to protect underlying dermis — no debridement in SJS.",
    "Continuing the culprit drug drives further epidermal loss; antihistamines treat urticaria, not SJS."],
  s:"New anticonvulsant/sulfonamide + mucosal ulcers + bullae = SJS until proven otherwise. Stop the drug, escalate, treat like a burn."},
 ref:"Stevens-Johnson syndrome · dermatologic emergency"},

{id:"SIC-035", t:"multi", cn:"SIC", sys:"NEURO", topic:"Seizure precautions", d:1, b:0.0, cj:"generate", tags:["seizures","safety","precautions"],
 stem:"A client with a new seizure disorder is admitted for observation. Select every component the nurse should include in seizure precautions for this client.",
 opts:["Suction equipment and oxygen set up at the bedside",
  "Padded side rails or padding secured to the bed frame",
  "An oral bite block taped at the bedside for insertion at seizure onset",
  "Intravenous access maintained or a saline lock in place",
  "The bed kept in the lowest position with the call bell reachable"],
 ans:[0,1,3,4],
 rat:{c:"Seizure precautions prepare for safe management: functioning suction and oxygen (aspiration and hypoxia are the killers), rail padding, guaranteed IV access for benzodiazepines, and a low bed to reduce fall injury. Nothing is ever forced into the mouth — bite blocks are a dental and airway injury myth.",
  o:["Correct — suction clears the airway post-ictus; oxygen treats peri-ictal hypoxia.",
    "Correct — padding reduces injury from thrashing against rails.",
    "Never insert anything into a seizing client's mouth — broken teeth and airway obstruction follow.",
    "Correct — IV access means abortive therapy can start within seconds.",
    "Correct — lowest position and reachability minimize injury if a seizure begins while in bed."],
  s:"Seizure safety = protect, position, suction, O2, IV access, time it. The mouth stays EMPTY."},
 ref:"Seizure precautions · inpatient safety"},

{id:"SIC-036", t:"single", cn:"SIC", sys:"CV", topic:"Cardioversion vs defibrillation", d:2, b:0.25, cj:"analyze", tags:["dysrhythmia","cardioversion","defibrillation"],
 stem:"A client with a rapid irregular rhythm becomes hypotensive and unresponsive to voice, but a weak pulse is present. The monitor shows atrial fibrillation at 180/min. Which action should the rapid response team take?",
 opts:["Synchronized cardioversion because the client is unstable with an organized rhythm",
  "Immediate unsynchronized defibrillation at maximum energy",
  "A carotid sinus massage while continuing to monitor the rhythm",
  "Amiodarone infusion alone with reassessment in ten minutes"],
 ans:0,
 rat:{c:"Unstable (hypotension, altered mental status) tachydysrhythmia WITH a pulse = SYNCHRONIZED cardioversion — synchronization times the shock to the R wave so it never lands on the T wave. Unsynced defibrillation is for pulseless rhythms; vagal maneuvers and drug-only therapy are for stable clients.",
  o:["Correct — unstable client with an organized (perfusing) rhythm = synchronized shock.",
    "Unsynchronized shocks risk the R-on-T phenomenon when a pulse and organized rhythm exist.",
    "Vagal maneuvers suit stable, narrow regular tachycardias — not an unstable client.",
    "Antidysrhythmics alone delay definitive therapy in an unstable client."],
  s:"Two-question triage: PULSE? no → defibrillation. yes → STABLE? no → synchronized cardioversion; yes → drugs/vagal."},
 ref:"Tachydysrhythmias · synchronized cardioversion"},

/* ── Health Promotion and Maintenance ──────────────────────────────── */
{id:"HPM-024", t:"single", cn:"HPM", sys:"MSK", topic:"Osteoporosis screening", d:1, b:-0.05, cj:"evaluate", tags:["osteoporosis","dexa","calcium","teaching"],
 stem:"A 63-year-old postmenopausal client's DEXA scan shows a T-score of −2.6. The provider prescribes calcium, vitamin D, and a bisphosphonate. Which client statement indicates the teaching was understood?",
 opts:["I will take the weekly tablet with a full glass of water and stay upright for at least half an hour",
  "I will take the tablet with my breakfast and lie back down if I feel tired afterward",
  "I will split the weekly tablet in half so my body absorbs it slowly across the week",
  "I will take it with my calcium at the same time each evening with a light snack"],
 ans:0,
 rat:{c:"Oral bisphosphonates cause severe esophagitis if retained supine: take on an empty stomach with a full glass of water and remain upright 30 minutes (some products 60). Splitting sustained tablets, lying down after dosing, and co-administering calcium (which chelates and blocks absorption) are all teaching failures.",
  o:["Correct — water plus upright time protects the esophagus and drives absorption.",
    "Lying down after dosing invites pill esophagitis — the key counseling point.",
    "These tablets must never be split or chewed.",
    "Calcium and the bisphosphonate bind each other — separate them by at least half an hour to an hour."],
  s:"Bisphosphonate mantra: empty stomach, big glass of water, upright 30+ minutes, and never beside calcium."},
 ref:"Osteoporosis · bisphosphonate therapy"},

{id:"HPM-025", t:"single", cn:"HPM", sys:"INTG", topic:"Melanoma recognition", d:1, b:0.0, cj:"recognize", tags:["melanoma","abcde","skin-cancer"],
 stem:"During a skin examination, which mole finding should the nurse refer to a dermatologist most urgently using the ABCDE criteria?",
 opts:["A 9 mm lesion on the back with border notching and a mix of tan, dark brown, and black coloring",
  "A uniformly tan 4 mm raised mole on the forearm that the client says has looked identical for years",
  "A single soft, flesh-colored, doughy lump on the neck that dims when pressed sides together",
  "A cluster of tiny 1–2 mm round red-brown spots on the chest of a lifelong sunbather"],
 ans:0,
 rat:{c:"ABCDE: Asymmetry, Border irregularity, Color variation, Diameter over 6 mm, Evolution. The 9 mm lesion with notched borders and three colors trips border, color, and diameter simultaneously — refer now. Stable uniform moles, soft acrochordons (skin tags), and small uniform red-brown spots (angiomas or stable cherry spots) are low-risk.",
  o:["Correct — 3 of 5 ABCDE criteria in a single lesion is an urgent dermatology referral.",
    "Uniform, stable, small — none of the ABCDE alarm features.",
    "A flesh-colored doughy lesion that dimples with side pressure is a benign acrochordon.",
    "Multiple tiny uniform round spots behave like benign angiomas — monitor, not urgent."],
  s:"Any ONE of: Asymmetry, Border, Color variation, >6 mm, or Evolution = referral. This lesion has three."},
 ref:"Skin cancer · ABCDE criteria"},

{id:"HPM-026", t:"single", cn:"HPM", sys:"REPI", topic:"Testicular self-examination", d:1, b:-0.1, cj:"generate", tags:["tse","testicular-cancer","screening"],
 stem:"A 19-year-old asks how to perform testicular self-examination after reading that it is recommended for young men. Which guidance should the nurse give?",
 opts:["Roll each testicle gently between thumb and fingers during a warm shower monthly, feeling for lumps or heaviness",
  "Perform the exam right after vigorous exercise weekly, when sensation is sharpest",
  "Palpate only the front surface of each testicle where tumors arise, once yearly",
  "Skip self-exams entirely since clinical exams detect everything reliably"],
 ans:0,
 rat:{c:"TSE is monthly, best during or after a warm bath or shower when the scrotum is relaxed: gently roll each testicle between thumb and fingers, feeling the whole surface for lumps, and note heaviness or size change. The epididymis (soft, posterior) is a normal structure not to mistake for a lump.",
  o:["Correct — warm, relaxed scrotum, monthly, full-surface palpation.",
    "Exercise draws the scrotum tight — the worst timing for palpation.",
    "Tumors can arise anywhere; examine the full surface and monthly, not annually.",
    "Most testicular cancers are found by the client — self-awareness is the screening."],
  s:"TSE = monthly, warm shower, roll the whole testicle, and know the epididymis is the normal soft ridge behind."},
 ref:"Testicular self-examination · young adult screening"},

/* ── Psychosocial Integrity ────────────────────────────────────────── */
{id:"PSY-024", t:"single", cn:"PSY", sys:"PSYCH", topic:"Acute stress vs PTSD", d:2, b:0.2, cj:"analyze", tags:["trauma","ptsd","diagnosis-timing"],
 stem:"Three weeks after surviving a motor vehicle crash, a client describes flashbacks, avoids driving, and startles at horn sounds. Which interpretation guides the nurse's response?",
 opts:["The symptoms reflect acute stress disorder, which commonly appears in the first month after trauma",
  "The symptoms meet post-traumatic stress disorder criteria because any intrusion after trauma is PTSD",
  "The symptoms are an expected grief reaction and need no further assessment or follow-up",
  "The symptoms indicate malingering because most crash survivors have no lasting symptoms"],
 ans:0,
 rat:{c:"Trauma reactions within the first month (intrusion, avoidance, hyperarousal) are acute stress disorder; PTSD is diagnosed when symptoms persist beyond a month. Neither normalizing without follow-up nor assuming exaggeration serves the client — symptom monitoring and early support are the response.",
  o:["Correct — under 1 month = acute stress disorder; persisting past a month reclassifies as PTSD.",
    "PTSD requires >1 month of symptoms — duration matters.",
    "Distress this impairing deserves scheduled reassessment even if initially normal-appearing.",
    "Flashbacks and avoidance are genuine post-trauma phenomena, not credible faking."],
  s:"Trauma timeline is the discriminator: 0–30 days acute stress disorder, >30 days PTSD. Watch, support, and reassess."},
 ref:"Trauma responses · timing and classification"},

{id:"PSY-025", t:"single", cn:"PSY", sys:"PSYCH", topic:"Substance use screening", d:1, b:0.1, cj:"generate", tags:["sbirt","motivational-interviewing","substance-use"],
 stem:"A clinic client's screening questionnaire indicates risky alcohol use. Which response applies brief-intervention principles the nurse should use?",
 opts:["Express what the score means, ask about willingness to change, and explore the client's own reasons to cut back",
  "Show photographs of end-stage liver disease to make the consequences vivid and immediate",
  "Require a signed contract to stop drinking completely before the visit can continue",
  "Document the result and refer only after the client hits a legal consequence like a DUI"],
 ans:0,
 rat:{c:"Brief intervention = screening feedback + responsibility left with the client + advice in a nonjudgmental tone + menu of options + empathy + self-efficacy (FRAMES). Fear appeals, abstinence ultimatums, and waiting for consequences are confrontational or neglectful and reduce engagement.",
  o:["Correct — feedback on the score, ask permission, elicit change talk: core motivational style.",
    "Graphic fear appeals rarely change drinking and can rupture the alliance.",
    "Ultimatums push clients away; goals are negotiated, not contracted under threat.",
    "Waiting for legal consequences forfeits the teachable moment screening created."],
  s:"Brief intervention shape: share the score → ask openness → evoke THEIR reasons → offer options. The client argues for change, not the nurse."},
 ref:"SBIRT · brief intervention"},

{id:"PSY-026", t:"single", cn:"PSY", sys:"MSK", topic:"Chronic pain and mood", d:2, b:0.15, cj:"evaluate", tags:["chronic-pain","depression","screening"],
 stem:"A client with chronic low back pain for two years reports poor sleep, no enjoyment of hobbies, and feeling hopeless about ever recovering. Which action should the nurse take first?",
 opts:["Screen for depression with a validated tool and share the results with the provider",
  "Reassure the client that hopeless feelings fade once the pain fully resolves",
  "Suggest doubling the current opioid dose to treat the pain driving the mood",
  "Refer the client to a surgeon to revisit operative options for the spine"],
 ans:0,
 rat:{c:"Chronic pain with anhedonia, sleep disruption, and hopelessness is a depression picture requiring validated screening (e.g., PHQ-9) and provider engagement — untreated depression worsens pain outcomes. Reassurance without assessment dismisses risk; opioid escalation without a provider order is outside scope and worsens the cycle; leaping to surgery skips the modifiable mood driver.",
  o:["Correct — screen, quantify, and escalate: depression is diagnosable and treatable alongside pain.",
    "Reassurance without screening can miss a treatable — and potentially dangerous — condition.",
    "Nurses do not change opioid doses unilaterally, and escalation does not treat depression.",
    "Surgical re-referral may be discussed later; mood assessment comes first."],
  s:"Chronic pain triad screen: sleep, enjoyment, hope. Two or more hits = depression screen today, not someday."},
 ref:"Chronic pain · comorbid depression"},

/* ── Basic Care and Comfort ────────────────────────────────────────── */
{id:"BCC-024", t:"single", cn:"BCC", sys:"GI", topic:"Colostomy care", d:1, b:-0.05, cj:"evaluate", tags:["colostomy","stoma","teaching"],
 stem:"A client is learning to change a new sigmoid colostomy pouch. Which observation indicates the appliance is being applied correctly?",
 opts:["A skin barrier opening cut to fit about 2 mm larger than the stoma, pressed onto clean dry skin",
  "A barrier opening cut to the exact edge of the stoma so it fits like a second skin",
  "The pouch applied over skin still damp from cleansing so it seals in moisture",
  "The pouch positioned while the client sits upright immediately after a full meal"],
 ans:0,
 rat:{c:"Barrier openings are sized about 2 mm (⅛ inch) larger than the stoma — tight enough to protect peristomal skin from effluent, loose enough to avoid cutting the mucosa — and applied to clean, completely dry skin for adhesion. Exact-edge cutting abducts/stenoses risk, damp skin prevents sealing, and pouch changes are best on an empty stomach (before breakfast) when the bowel is quietest.",
  o:["Correct — the 2 mm rule balances protection against trauma.",
    "Exact-edge sizing traumatizes the stoma mucosa with every wear.",
    "Moisture defeats adhesive — dry the skin fully, use a barrier wipe if needed.",
    "Change appliances before eating, when output is least likely."],
  s:"Pouching math: stoma + 2 mm, dry skin, quiet bowel. Change before breakfast."},
 ref:"Colostomy · appliance fitting"},

{id:"BCC-025", t:"single", cn:"BCC", sys:"INTG", topic:"Scabies management", d:1, b:0.1, cj:"generate", tags:["scabies","household-treatment","skin"],
 stem:"A school-age child is diagnosed with scabies after two weeks of worsening nocturnal itching with burrow tracks between the fingers. Which instruction should the nurse give the family?",
 opts:["Treat every household member and close contacts at the same time, and launder bedding and worn clothing in hot water",
  "Treat only the child now and others only if they start scratching within the week",
  "Bag all stuffed animals and discard them permanently to remove mite reservoirs",
  "Expect the burrow tracks and itching to vanish within 24 hours of the first treatment"],
 ans:0,
 rat:{c:"Scabies spreads by prolonged skin-to-skin contact, and contacts can be asymptomatic while contagious — everyone in the household is treated simultaneously, plus hot-wash bedding and clothing worn in the last 3 days. Sealing items in a bag for 3+ days (not discarding) handles what cannot be washed, and pruritus often persists 1–2 weeks post-treatment (a hypersensitivity reaction, not failure).",
  o:["Correct — simultaneous treatment of contacts plus laundering breaks the relay cycle.",
    "Waiting for symptoms in others lets the mite shuttle back to the treated child.",
    "Sealing unwashables for 3 or more days suffices — throwing them away is unnecessary.",
    "Itching commonly continues up to two weeks after successful treatment — counsel families or they will re-treat excessively."],
  s:"Scabies rules: treat everybody at once, hot-wash the recent linens, bag what you cannot wash, and warn that itch outlives the mite."},
 ref:"Scabies · household protocol"},

{id:"BCC-026", t:"single", cn:"BCC", sys:"REPI", topic:"Pelvic inflammatory disease", d:1, b:0.0, cj:"generate", tags:["pid","partner-treatment","public-health"],
 stem:"A client is treated for pelvic inflammatory disease, and the nurse is planning follow-up education. Which instruction directly prevents reinfection?",
 opts:["All recent sexual partners need evaluation and treatment even when they have no symptoms",
  "The client should abstain from intercourse only until the antibiotic course runs out",
  "Using spermicide alone is adequate protection while the infection clears",
  "Partners need treatment only if they develop discharge or pain of their own"],
 ans:0,
 rat:{c:"Reinfection is the rule, not the exception, when partners go untreated — asymptomatically infected partners (especially with chlamydia/gonorrhea) reinfect the treated client. Abstinence until partners complete treatment (commonly 7 days) plus condom use is the standard; spermicide alone is not adequate STI protection.",
  o:["Correct — treating partners simultaneously is the single highest-yield reinfection prevention.",
    "Abstaining until only the CLIENT's antibiotics finish leaves symptomatic or silent partners contagious.",
    "Spermicides do not reliably prevent STI transmission.",
    "Waiting for partner symptoms misses the silent carriers who cause most reinfections."],
  s:"STI follow-through: treat the partners, not just the patient — silence in a partner is not evidence of health."},
 ref:"Pelvic inflammatory disease · partner therapy"},

/* ── Pharmacological and Parenteral Therapies ──────────────────────── */
{id:"PHA-049", t:"single", cn:"PHA", sys:"ENDO", topic:"Levothyroxine administration", d:1, b:0.05, cj:"evaluate", tags:["levothyroxine","hypothyroidism","absorption"],
 stem:"A client with hypothyroidism is starting levothyroxine and also takes calcium carbonate and a ferrous sulfate supplement. Which teaching prevents interactions?",
 opts:["Take the thyroid tablet first thing with water on an empty stomach, and the other two at least four hours later",
  "Take all three medications together with breakfast for the best combined absorption",
  "Take the thyroid tablet at bedtime when metabolism is slowest, and the others in the morning",
  "Crush the thyroid tablet into the calcium dose so they dissolve in the same stomach acid"],
 ans:0,
 rat:{c:"Levothyroxine absorption is notoriously blocked by calcium, iron, and food: take it alone, with water, 30–60 minutes before breakfast (or four hours apart from interacting supplements). Combining them guarantees underdosing; crushing into calcium is the exact interaction to avoid.",
  o:["Correct — empty stomach first thing, separation from calcium and iron by four hours.",
    "Co-administration with calcium and iron binds the drug and blocks absorption — the classic interaction.",
    "Bedtime dosing conflicts with dinner calcium and iron routines and is not the standard.",
    "Mixing the tablet into the calcium dose chemically guarantees the binding you are teaching to avoid."],
  s:"Levothyroxine is a lonely pill: water only, empty stomach, four hours away from calcium and iron."},
 ref:"Hypothyroidism · levothyroxine interactions"},

{id:"PHA-050", t:"single", cn:"PHA", sys:"RESP", topic:"Asthma action plan", d:1, b:0.0, cj:"analyze", tags:["asthma","peak-flow","zones"],
 stem:"A school-age child with asthma uses a peak flow meter as part of the written action plan. A reading in the yellow zone (50–79% of personal best) means the nurse should instruct the parent to:",
 opts:["Use the quick-relief medication as the action plan directs and watch closely for worsening",
  "Call for an ambulance immediately because hospitalization is now required",
  "Skip the next dose of controller medication to let the lungs rest",
  "Ignore the reading since yellow means the lungs are working normally"],
 ans:0,
 rat:{c:"Yellow zone = caution: airflow is 50–79% of personal best — step up per the written plan (typically quick-relief bronchodilator) and monitor. Red zone, not yellow, is the emergency trigger; controllers are never stopped for lung rest; and yellow is by definition below normal.",
  o:["Correct — yellow = quick-relief per plan plus heightened observation.",
    "Red-zone readings or severe symptoms bring the ambulance, not yellow alone.",
    "Controllers run on schedule regardless of zone — stopping them worsens inflammation.",
    "Green means normal; yellow is 20–50% of the way to trouble."],
  s:"Action-plan traffic light: green go, yellow step up + watch, red emergency. The written plan names exact drugs and doses."},
 ref:"Asthma · peak flow zones"},

{id:"PHA-051", t:"multi", cn:"PHA", sys:"NEURO", topic:"Myasthenic vs cholinergic crisis", d:3, b:0.4, cj:"analyze", tags:["myasthenia-gravis","cholinergic-crisis","edrophonium"],
 stem:"A client with myasthenia gravis on pyridostigmine develops sudden worsening muscle weakness. The nurse reviews findings to help distinguish cholinergic crisis (too much anticholinesterase) from myasthenic crisis (too little). Select every finding consistent with CHOLINERGIC crisis.",
 opts:["Salivation and sweating with abdominal cramping",
  "Improvement in strength after a withheld pyridostigmine dose",
  "Bronchoconstriction with excessive airway secretions",
  "Improvement in strength after an edrophonium test dose",
  "Blurred vision described as an increase in drooping of the eyelids"],
 ans:[0,1,2],
 rat:{c:"Cholinergic crisis is cholinergic OVERLOAD: muscarinic soup — salivation, sweating, cramps, bronchospasm, excessive secretions — and paradoxical improvement when the drug is withheld. Myasthenic crisis improves after edrophonium or an extra dose; increased ptosis alone accompanies weakness of either cause and does not discriminate.",
  o:["Correct — classic muscarinic overstimulation triad member.",
    "Correct — removing the excess drug improves a cholinergic crisis (the opposite happens in myasthenic crisis).",
    "Correct — bronchoconstriction and flooding secretions are dangerous cholinergic features.",
    "Edrophonium improvement indicates MYASTHENIC crisis (too little drug) — the opposite diagnosis.",
    "Worse ptosis accompanies weakness in both crises — nondiscriminating."],
  s:"Distinguish by direction: more-drug symptoms (salivation, cramps, secretions) = cholinergic; better-with-drug = myasthenic. Keep suction ready either way."},
 ref:"Myasthenia gravis · crisis differentiation"},

{id:"PHA-052", t:"cloze", cn:"PHA", sys:"ENDO", topic:"Adrenal insufficiency sick-day rules", d:2, b:0.25, cj:"generate", tags:["adrenal-insufficiency","steroids","sick-day-rules"],
 stem:"Complete the sick-day teaching for a client with primary adrenal insufficiency taking daily hydrocortisone.",
 cloze:{lines:[
  {pre:"When fever or significant illness develops, the client should ", post:" the daily corticosteroid dose as instructed by the provider.",
   opts:["increase","decrease","skip","halve"], ans:0},
  {pre:"If persistent vomiting makes oral doses impossible, the client should ", post:" and use the emergency injection if prescribed.",
   opts:["call the provider or emergency services immediately","wait 24 hours to see if it passes","double the next oral dose","switch to a lower dose"], ans:0},
  {pre:"At all times, the client should carry ", post:" so any responder recognizes the steroid dependency.",
   opts:["medical alert identification and an emergency steroid card","a copy of last year's laboratory results","a thermometer and a diary of doses","nothing, since the condition is invisible"], ans:0}
 ]},
 rat:{c:"Steroid-dependent clients cannot mount a stress cortisol response: illness demands a DOSE INCREASE, inability to keep pills down is an emergency (injectable glucocorticoid + immediate care), and medical alert identification protects them when they cannot advocate for themselves.",
  o:["Correct — stress dosing mirrors the missing cortisol surge.","Lowering steroids during illness risks adrenal crisis.","Skipping doses during illness is the classic path to crisis.","Halving does the same harm in a smaller package.",
    "Correct — vomiting plus adrenal insufficiency is an emergency, not a wait-and-see.","Waiting a day can be fatal in adrenal crisis.","A doubled oral dose that is vomited again helps nothing.","A lower dose moves the wrong direction entirely.",
    "Correct — alert identification plus the steroid card is standard counseling.","Old labs do not communicate emergency needs.","Monitoring tools help but protect no one in an emergency.","Invisible is exactly why identification matters."],
  s:"Sick-day steroid triplet: illness raises the dose, vomiting means inject and call, identification travels with the client always."},
 ref:"Adrenal insufficiency · stress dosing"},

/* ── Reduction of Risk Potential ───────────────────────────────────── */
{id:"RRP-036", t:"single", cn:"RRP", sys:"MSK", topic:"Femur fracture care", d:2, b:0.15, cj:"prioritize", tags:["fracture","neurovascular","traction"],
 stem:"A teenager arrives at the emergency department after a motor vehicle crash with a suspected femur fracture and Buck traction applied. Which assessment should the nurse perform most frequently?",
 opts:["Neurovascular checks of the affected leg — pulses, sensation, movement, and color",
  "Bowel sounds in all four quadrants every two hours",
  "Deep tendon reflexes of both upper extremities",
  "Pupillary responses to light and accommodation"],
 ans:0,
 rat:{c:"Femur fractures (and traction itself) threaten distal perfusion and nerves: compartment syndrome and neurovascular compromise are the monitored-for complications — pulses, pallor, paresthesia, paralysis, pressure. Bowel, upper-extremity reflexes, and pupils are not on the femur-fracture surveillance path.",
  o:["Correct — the 5 Ps (plus capillary refill) are the frequent-flier assessments.",
    "Bowel surveillance matters later for immobility, not acutely for the fracture.",
    "Femur traction does not threaten brachial reflex arcs.",
    "Pupils belong to head-injury surveillance, not isolated femur fracture monitoring."],
  s:"Any limb fracture + traction = neurovascular checks on a clock (often hourly at first). Compartment syndrome never announces itself twice."},
 ref:"Femur fracture · neurovascular monitoring"},

{id:"RRP-037", t:"hotspot", cn:"RRP", sys:"MSK", topic:"Rheumatoid arthritis assessment", d:2, b:0.2, cj:"recognize", tags:["rheumatoid-arthritis","assessment","differentiation"],
 stem:"A middle-aged client reports joint problems of three months' duration. Select every finding below that points toward rheumatoid arthritis rather than osteoarthritis.",
 hotspot:{mode:"rows", rows:[
  "Symmetric swelling of the metacarpophalangeal joints of both hands",
  "Morning stiffness lasting more than an hour that eases with activity",
  "Firm nodules along the extensor surface of the forearm",
  "Pain isolated to the right knee, worse at the end of the day",
  "Bony enlargement of the distal finger joints without warmth",
  "Fatigue and a low-grade temperature accompanying the joint symptoms"
 ], ans:[0,1,2,5]},
 rat:{c:"RA is a systemic, symmetric, inflammatory disease: MCP swelling, prolonged morning stiffness improving with use, rheumatoid nodules, and constitutional symptoms. Osteoarthritis is asymmetric, mechanical (worse with use, better with rest), features bony (Heberden/Bouchard) enlargements without warmth, and carries no systemic symptoms.",
  s:"Sort by pattern: symmetric + inflammatory + systemic = RA; asymmetric + mechanical + bony = OA. Time-of-day behavior is the fastest clue."},
 ref:"Rheumatoid arthritis · pattern recognition"},

{id:"RRP-038", t:"single", cn:"RRP", sys:"MSK", topic:"Phantom limb pain", d:1, b:0.1, cj:"evaluate", tags:["amputation","phantom-pain","neuropathic"],
 stem:"Two months after a below-knee amputation, a client tells the clinic nurse the missing foot itches and cramps and asks whether this means they are losing their mind. Which response is best?",
 opts:["This is phantom limb sensation, a real and common nerve signal — treatments exist, so let's talk about what has helped so far",
  "This is unexpected so long after surgery and warrants imaging of the stump today",
  "This happens because the stump dressing is too tight — loosening it will end the sensations",
  "The sensations will disappear permanently once the prosthesis is fitted"],
 ans:0,
 rat:{c:"Phantom limb sensations and pain are real neuropathic phenomena from cortical and peripheral nerve reorganization, common for months to years; they deserve validation and treatment discussion (desensitization, mirror therapy, gabapentin-type agents). They are expected (not imaging-worthy), not caused by dressing tightness, and often persist despite prosthetic fitting.",
  o:["Correct — validate, normalize, and move to management options.",
    "Phantom sensation is expected at two months; imaging hunts a problem that is not there.",
    "Tight dressings cause stump pain, not sensations perceived in a missing foot.",
    "Prostheses help function; they guarantee no such cure for phantom phenomena."],
  s:"Phantom pain = real neurologic signal. First intervention: validation. Then: desensitization, mirror therapy, neuropathic agents."},
 ref:"Amputation · phantom limb phenomena"},

{id:"RRP-039", t:"matrix", cn:"RRP", sys:"INTG", topic:"Pressure injury staging", d:2, b:0.3, cj:"analyze", tags:["pressure-injury","staging","classification"],
 stem:"For each wound finding from a head-to-toe skin examination, select the correct pressure injury classification.",
 matrix:{cols:["Stage 2","Stage 3","Unstageable","Deep tissue injury"], rows:[
  "A shallow open ulcer with a pink-red wound bed and no slough over the sacrum",
  "Full-thickness loss with visible subcutaneous fat but no exposed bone or tendon on the heel",
  "A sacral wound covered completely by firm, adherent brown-black eschar",
  "Intact purple-maroon skin over the heel that feels boggy compared with the other side"
 ], mode:"one", ans:[0,1,2,3]},
 rat:{c:"Stage 2 = partial thickness (pink-red bed, no slough); Stage 3 = full thickness into subcutaneous fat without bone/tendon exposure; unstageable = base obscured by eschar or slough (stable heel eschar is left in place and the wound is documented unstageable); deep tissue injury = intact or blood-filled blister skin in purple/maroon tones over a bony prominence.",
  s:"Staging ladder: how deep is visible? Partial = 2; fat = 3; muscle/bone = 4; cannot see the base = unstageable; intact discolored boggy skin = DTI. Reverse staging never happens as wounds heal."},
 ref:"Pressure injuries · NPIAP staging"},

/* ── Physiological Adaptation ──────────────────────────────────────── */
{id:"PAA-048", t:"multi", cn:"PAA", sys:"MSK", topic:"Pediatric cast complications", d:2, b:0.2, cj:"recognize", tags:["compartment-syndrome","pediatrics","cast"], variantGroup:"cast-compartment",
 stem:"A 7-year-old returned from cast application for a forearm fracture and the parent calls the clinic line. Select every report that requires the child to be seen immediately for possible compartment syndrome.",
 opts:["The child cries that the fingers are tingling and numb",
  "The fingers look pale and feel cool compared with the other hand",
  "The child reports itching inside the cast that improves with distraction",
  "Pain is escalating despite elevating the arm and giving the prescribed ibuprofen",
  "The child can wiggle all five fingers freely and the nails refill quickly"
 ], ans:[0,1,3],
 rat:{c:"Compartment syndrome red flags in a casted child: paresthesias, pallor with coolness, and analgesia-refractory escalating pain — any one demands immediate evaluation (splitting the cast, not phone reassurance). Itching inside a cast is near-universal and benign with intact circulation, and freely wiggling fingers with brisk refill are reassuring signs.",
  o:["Correct — new numbness or tingling is early neurovascular compromise.",
    "Correct — pale, cool digits signal falling perfusion.",
    "Superficial itching with good circulation is expected; teach safe distraction, never coat-hanger scratching.",
    "Correct — pain out of proportion and unrelieved is the cardinal complaint.",
    "Full movement with brisk refill is the reassuring finding — reinforce observation."],
  s:"Pediatric compartment screen by phone: numb, pale, cool, or pain that ibuprofen and elevation cannot touch = come now. Itch alone is noise; wiggle + refill is reassurance."},
 ref:"Pediatric fractures · compartment syndrome"},

{id:"PAA-049", t:"single", cn:"PAA", sys:"MSK", topic:"Muscular dystrophy", d:2, b:0.2, cj:"recognize", tags:["duchenne","gower-sign","pediatrics"],
 stem:"During a preschool screening, the nurse observes a 4-year-old push his upper legs with his hands to rise from the floor to standing. Which interpretation and action is correct?",
 opts:["This Gower sign suggests proximal muscle weakness and warrants prompt referral for neuromuscular evaluation",
  "This is a normal transitional movement pattern that preschoolers outgrow by age six",
  "This movement indicates a spinal deformity and requires an orthotic brace fitting at the screening",
  "This finding suggests juvenile arthritis and calls for an immediate inflammatory panel in clinic"],
 ans:0,
 rat:{c:"Using the hands to walk up the legs (Gower sign) reflects proximal hip-girdle weakness — the hallmark presentation of Duchenne muscular dystrophy in toddlers and preschoolers — and needs urgent neuromuscular referral (creatine kinase, genetics). It is not a normal variant, a brace problem, or arthritis.",
  o:["Correct — Gower sign = proximal weakness = refer for CK and neuromuscular workup.",
    "Typical preschoolers rise without climbing their legs; the sign is never a normal stage.",
    "Bracing addresses spinal curvature that may come LATER in Duchenne — not the sign itself.",
    "Inflammatory arthritis produces joint pain and stiffness, not this leg-climbing rise."],
  s:"Hands climbing the thighs to stand = Gower sign = proximal myopathy until proven otherwise. CK today beats reassurance tomorrow."},
 ref:"Duchenne muscular dystrophy · early recognition"},

{id:"PAA-050", t:"single", cn:"PAA", sys:"INTG", topic:"Tinea corporis", d:1, b:-0.05, cj:"evaluate", tags:["tinea","antifungal","pediatrics"],
 stem:"The parent of a school-age child with ringworm on the arm asks how to use the prescribed topical antifungal. Which instruction is correct?",
 opts:["Apply it to the lesion and 2 cm beyond its edge, continuing for the full course and one week after the rash clears",
  "Apply it only to the exact ring border and stop as soon as the center looks clear",
  "Use an over-the-counter hydrocortisone cream instead if the ring is very itchy",
  "Cover the lesion with an occlusive bandage after each application to keep it moist"],
 ans:0,
 rat:{c:"Topical antifungals cover the visible ring PLUS a margin (lesions clear center-first, luring early stopping) and continue one to two weeks past clearance to prevent recurrence. Steroid creams blunt inflammation while the fungus flourishes (and can produce tinea incognito), and occlusion macerates skin and spreads dermatophytes.",
  o:["Correct — edge-plus-margin and past-clearance duration is the complete instruction.",
    "Center clearing is the natural course and the classic trap; stopping early relapses.",
    "Steroids alone worsen dermatophyte infections — never substitute them.",
    "Occlusive dressings create the warm, moist environment fungi love."],
  s:"Ringworm rules: treat the edge plus 2 cm, keep going a week past clear, keep it dry, and never swap in a steroid."},
 ref:"Tinea corporis · topical therapy"},

{id:"PAA-051", t:"single", cn:"PAA", sys:"REPI", topic:"Ectopic pregnancy", d:2, b:0.25, cj:"analyze", tags:["ectopic-pregnancy","emergency","reproductive"],
 stem:"A client at seven weeks' gestation reports sudden sharp right lower abdominal pain with light vaginal spotting and shoulder-tip discomfort on the affected side. Which action should the nurse anticipate first?",
 opts:["Establish IV access and prepare for urgent ultrasound and provider evaluation",
  "Schedule a routine obstetric ultrasound for the following week",
  "Instruct the client to rest and monitor fetal movement patterns at home",
  "Send a urine sample for culture to rule out a urinary tract infection"],
 ans:0,
 rat:{c:"Unilateral sharp pain + spotting + referred shoulder pain in the first trimester is a presumed rupturing ectopic pregnancy — an obstetric emergency: IV access, typed crossmatch per orders, urgent ultrasound, and immediate provider escalation. Delayed imaging, home fetal monitoring (no viable intrauterine pregnancy to monitor at 7 weeks), or UTI workup squanders the window.",
  o:["Correct — access, imaging, and escalation in parallel; rupture can shock in minutes.",
    "Next-week imaging is not a plan for a possible rupture.",
    "Fetal movement is not assessable at seven weeks and misses the emergency entirely.",
    "A UTI does not explain shoulder-tip pain with spotting in early pregnancy."],
  s:"First-trimester triad — unilateral pain, spotting, shoulder pain = ectopic until scanned. Move at emergency speed."},
 ref:"Ectopic pregnancy · first-trimester emergency"},

{id:"PAA-052", t:"cloze", cn:"PAA", sys:"GI", topic:"Upper GI bleeding", d:2, b:0.3, cj:"analyze",
 stem:"Complete the assessment of a client who reports passing black, tarry, foul-smelling stools for two days.",
 tags:["gi-bleed","melena","assessment"],
 cloze:{lines:[
  {pre:"Black tarry stools most strongly suggest bleeding from the ", post:" gastrointestinal tract.",
   opts:["upper","lower","small appendiceal","entire colonic"], ans:0},
  {pre:"On arrival, the priority nursing assessment is ", post:" before any detailed history of diet or medications.",
   opts:["vital signs and orthostatic response to volume loss","the exact number of stools passed last week","a detailed list of foods eaten in 72 hours"], ans:0},
  {pre:"Because iron and bismuth salts can also darken stools, the nurse should ", post:" while still treating the finding as possible bleeding until ruled out.",
   opts:["review recent medications with the client","assume the cause is dietary and close the assessment","disregard the color and chart only the stool count"], ans:0}
 ]},
 rat:{c:"Melena — black, tarry, foul — indicates digested blood from an upper source. Volume status (vitals, orthostatics) comes before history detail because shock precedes certainty; medications like iron or bismuth can mimic the color, so reconcile the med list without ever dismissing the finding before evaluation.",
  o:["Correct — melena = upper GI source until proven otherwise.","Lower GI bleeding typically produces red or maroon stool.","The appendix does not explain melena patterns.","A diffuse colonic source is not the classic melena picture.",
    "Correct — perfusion first: the first assessment tests the circulatory system.","Counting stools documents; it does not assess stability.","Diet history matters later and never before hemodynamics.",
    "Correct — reconcile the med list while continuing to treat it as possible bleeding.","Assuming diet and closing the case is how upper GI bleeds walk out the door.","Color plus volume plus stability all belong in the record."],
  s:"Melena pathway: assume upper, assess volume status FIRST, then reconcile look-alike meds. Certainty is the endoscopy's job."},
 ref:"Upper GI bleeding · melena recognition"}
);
