/* ============================================================================
   bank16.js — hand-authored wave 6: 24 hard items, NCLEX-RN only

   WHY THIS FILE EXISTS
     Wave 5 took the bank from 5% to 11.6% max-difficulty. This wave keeps
     pushing on the same axis: high-acuity emergencies where the wrong choice is
     a plausible action rather than an obviously wrong one. Every topic below was
     checked against the rest of the bank (stem + options + topic + summary
     rationale) and appears nowhere else.

   DISTRIBUTION
     PAA 6 · RRP 5 · PHA 4 · SIC 3 · BCC 3 · HPM 3

   AUTHORING RULES OBSERVED
     · no stem token that occurs only in the key option
     · key is not systematically the longest option
     · distractors are correct actions in a different scenario
     · rationale explains the key and each distractor, plus a one-line takeaway
   ========================================================================== */
window.NC.BANK.push(
/* ── Physiological Adaptation (blueprint 14%) ─────────────────────── */
{id:"PAA-073", t:"single", cn:"PAA", sys:"CV", topic:"Superior vena cava syndrome", d:3, b:0.7, cj:"analyze", tags:["oncology","obstruction","emergency"],
 stem:"A client with small cell lung cancer develops facial and neck swelling, distended neck veins, and a sensation of fullness in the head that worsens when bending forward. The nurse interprets these findings as:",
 opts:["Obstruction of venous return from the upper body by the tumor",
  "Right-sided heart failure from chronic pulmonary hypertension",
  "An allergic reaction to the most recent chemotherapy dose",
  "Lymphedema from axillary node dissection"],
 ans:0,
 rat:{c:"Superior vena cava syndrome occurs when a mediastinal tumor compresses the great vein, blocking venous drainage from the head, neck and arms. The positional worsening on bending forward is characteristic, because that position further raises venous pressure above the obstruction.",
  o:["Correct — tumor compression of the superior vena cava explains the pattern.",
    "Heart failure causes dependent edema and jugular distention, not positional facial swelling.",
    "An allergic reaction does not produce distended neck veins with positional change.",
    "Lymphedema is limb-limited and does not cause neck vein distention."],
  s:"Facial and neck swelling plus positional head fullness in a cancer client is SVC syndrome."},
 ref:"Oncologic emergencies · superior vena cava syndrome"},

{id:"PAA-074", t:"single", cn:"PAA", sys:"CV", topic:"Cardiac tamponade", d:3, b:0.75, cj:"analyze", tags:["pericardial","hemodynamics","emergency"],
 stem:"Two days after cardiac surgery a client has a blood pressure of 84/52 mm Hg, muffled heart sounds, and jugular venous distention despite a falling chest tube output. The nurse recognizes these findings as:",
 opts:["Tamponade from fluid accumulating in the pericardial sac",
  "Hypovolemic shock from ongoing surgical bleeding",
  "Tension pneumothorax from an air leak",
  "Septic shock from a sternal wound infection"],
 ans:0,
 rat:{c:"Beck's triad — hypotension, muffled heart sounds, and jugular venous distention — indicates tamponade. Falling chest tube output alongside rising venous pressure means blood is collecting inside the pericardium rather than draining, which is what makes this dangerous rather than reassuring.",
  o:["Correct — Beck's triad with obstructed drainage points to tamponade.",
    "Hypovolemia causes flat neck veins, not distention.",
    "Tension pneumothorax produces absent breath sounds and tracheal deviation.",
    "Septic shock presents with warm flushed skin early, not muffled heart sounds."],
  s:"Beck's triad plus a suddenly quiet chest tube means tamponade, not improvement."},
 ref:"Cardiovascular · cardiac tamponade"},

{id:"PAA-075", t:"single", cn:"PAA", sys:"MSK", topic:"Malignant hyperthermia", d:3, b:0.8, cj:"prioritize", tags:["anesthesia","genetic","emergency"],
 stem:"Shortly after induction of general anesthesia, a client develops muscle rigidity, a heart rate of 148/min, and a rapidly rising end-tidal carbon dioxide. The temperature is 39.4 degrees C. The nurse's priority action is to:",
 opts:["Stop the triggering agents and prepare dantrolene for administration",
  "Apply cooling blankets and recheck the temperature in fifteen minutes",
  "Increase the fresh gas flow and continue the planned procedure",
  "Administer acetaminophen intravenously for the elevated temperature"],
 ans:0,
 rat:{c:"Malignant hyperthermia is a genetic hypermetabolic crisis triggered by volatile anesthetics and succinylcholine. Rising end-tidal carbon dioxide is the earliest and most sensitive sign. The trigger must stop immediately and dantrolene, the only specific antidote, is given. Antipyretics do not touch a hypermetabolic heat source.",
  o:["Correct — stop the trigger and give dantrolene immediately.",
    "Cooling is supportive; it does not stop the underlying hypermetabolism.",
    "Continuing exposure drives the crisis toward cardiac arrest.",
    "Acetaminophen acts centrally and cannot reduce metabolic heat production."],
  s:"Malignant hyperthermia: rising end-tidal CO2 first, then stop the trigger and give dantrolene."},
 ref:"Perioperative · malignant hyperthermia"},

{id:"PAA-076", t:"single", cn:"PAA", sys:"RESP", topic:"Status asthmaticus with silent chest", d:3, b:0.8, cj:"analyze", tags:["asthma","respiratory-failure","deterioration"],
 stem:"A client in status asthmaticus has been wheezing loudly. On reassessment the wheeze has disappeared, the client is speaking in single words, and the respiratory rate is 34/min. The nurse interprets the absent wheeze as:",
 opts:["Worsening airflow obstruction requiring immediate escalation",
  "Resolution of bronchospasm as the treatment takes effect",
  "A normal finding once the client is fatigued from the effort",
  "Evidence that the nebulizer dose was finally absorbed"],
 ans:0,
 rat:{c:"A silent chest in a client still working hard to breathe means airflow has fallen so low that wheeze can no longer be generated. It signals impending respiratory failure, not improvement. The trap is that quiet sounds reassuring while the client is actually deteriorating.",
  o:["Correct — a silent chest with ongoing distress means critical obstruction.",
    "Improvement would bring easier breathing and better speech, not single words.",
    "Fatigue with silence is a pre-arrest sign, never a normal finding.",
    "Absorption of medication would improve airflow and speech."],
  s:"Silent chest in a struggling asthmatic is impending failure, not improvement."},
 ref:"Respiratory · status asthmaticus"},

{id:"PAA-077", t:"single", cn:"PAA", sys:"CV", topic:"Aortic dissection", d:3, b:0.75, cj:"prioritize", tags:["vascular","hypertensive","emergency"],
 stem:"A client with long-standing hypertension reports sudden tearing chest pain radiating between the shoulder blades. Blood pressure is 206/118 mm Hg in the right arm and 148/84 mm Hg in the left. The nurse's priority action is to:",
 opts:["Notify the provider immediately and prepare for urgent antihypertensive therapy",
  "Recheck both arm pressures in thirty minutes to confirm the difference",
  "Administer sublingual nitroglycerin as for an acute coronary syndrome",
  "Obtain a twelve-lead electrocardiogram before taking any other action"],
 ans:0,
 rat:{c:"Tearing pain with an interarm blood pressure differential suggests aortic dissection, a surgical emergency in which every hypertensive minute extends the tear. Notification and rapid controlled lowering of pressure and shear stress come first. Waiting to recheck, or treating this as an infarct, delays the intervention that limits the dissection.",
  o:["Correct — report now and prepare for urgent blood pressure and shear control.",
    "A thirty-minute wait lets the dissection propagate.",
    "Nitroglycerin alone does not control the shear force driving the tear.",
    "An electrocardiogram is useful but must not delay notification."],
  s:"Tearing pain plus an interarm pressure gap is dissection until proven otherwise."},
 ref:"Cardiovascular · aortic dissection"},

{id:"PAA-078", t:"single", cn:"PAA", sys:"NEURO", topic:"Guillain-Barre syndrome", d:3, b:0.7, cj:"prioritize", tags:["neuromuscular","respiratory","monitoring"],
 stem:"A client with Guillain-Barre syndrome has ascending weakness that has reached the thighs. The nurse's priority assessment is:",
 opts:["Vital capacity and respiratory effort, measured serially",
  "Deep tendon reflexes in the lower extremities",
  "Swallowing ability before offering oral fluids",
  "Range of motion to prevent contractures of the legs"],
 ans:0,
 rat:{c:"The weakness ascends, and once it reaches the respiratory muscles the client can fail quickly and with little warning. Vital capacity tracks that trajectory objectively. Reflexes are already known to be absent, swallowing matters but follows airway risk, and range of motion is a later concern.",
  o:["Correct — serial vital capacity detects respiratory muscle involvement early.",
    "Areflexia is expected and does not change immediate management.",
    "Swallow assessment is important but ranks below ventilatory failure.",
    "Contracture prevention is not an emergent priority."],
  s:"Guillain-Barre ascends: watch vital capacity, because respiratory failure is the danger."},
 ref:"Neuro · Guillain-Barre syndrome"},

/* ── Reduction of Risk Potential (blueprint 12%) ──────────────────── */
{id:"RRP-058", t:"single", cn:"RRP", sys:"RESP", topic:"Tension pneumothorax decompression", d:3, b:0.8, cj:"prioritize", tags:["thoracic","emergency","decompression"],
 stem:"A ventilated client suddenly becomes hypotensive with absent breath sounds on the left, tracheal deviation to the right, and a distended neck. The nurse's first action is to:",
 opts:["Notify the provider immediately for emergency needle decompression",
  "Increase the oxygen concentration and reassess in five minutes",
  "Reposition the client onto the left side to reopen the lung",
  "Suction the endotracheal tube to clear a probable mucous plug"],
 ans:0,
 rat:{c:"Absent breath sounds with deviation away from that side plus obstructive shock is tension pneumothorax. Trapped air is compressing the mediastinum and blocking venous return, so pressure must be released now. Repositioning and suctioning treat a different problem while the client loses cardiac output.",
  o:["Correct — this is a decompression emergency; escalate immediately.",
    "More oxygen does not relieve the pressure compressing the heart.",
    "Lateral positioning cannot relieve a tension pneumothorax.",
    "A mucous plug would not shift the trachea or distend neck veins."],
  s:"Tension pneumothorax: deviated trachea plus shock means decompress now."},
 ref:"Thoracic · tension pneumothorax"},

{id:"RRP-059", t:"single", cn:"RRP", sys:"NEURO", topic:"Cauda equina syndrome", d:3, b:0.8, cj:"prioritize", tags:["spinal","neurologic","emergency"],
 stem:"A client with a known lumbar disc herniation reports new numbness in the groin and inner thighs and says he has not been able to urinate despite a full bladder. The nurse's priority action is to:",
 opts:["Notify the provider immediately as a surgical emergency",
  "Insert an indwelling urinary catheter and reassess in the morning",
  "Administer the prescribed analgesic and reposition for comfort",
  "Document the finding and report it during the next round"],
 ans:0,
 rat:{c:"Saddle anesthesia with urinary retention indicates cauda equina compression. Decompression must occur within hours or bladder, bowel and sexual function may be permanently lost. Relieving the bladder is necessary but treating it as the whole problem misses the neurologic emergency driving it.",
  o:["Correct — saddle anesthesia with retention is a surgical emergency.",
    "Catheterizing treats the symptom and delays the decompression clock.",
    "Analgesia masks the progression of a time-critical deficit.",
    "Deferring to rounds risks permanent neurologic loss."],
  s:"Saddle anesthesia plus retention is cauda equina syndrome — escalate within hours."},
 ref:"Neuro · cauda equina syndrome"},

{id:"RRP-060", t:"single", cn:"RRP", sys:"MSK", topic:"Compartment syndrome assessment", d:3, b:0.75, cj:"analyze", tags:["orthopedic","perfusion","emergency"],
 stem:"Six hours after tibial fracture repair a client reports pain out of proportion to the injury that is not relieved by opioid analgesia. The distal pulse is present and capillary refill is brisk. The nurse understands that:",
 opts:["Compartment syndrome is still likely, because pulse is a late finding",
  "Compartment syndrome is excluded because the distal pulse is intact",
  "The pain indicates inadequate analgesia rather than a complication",
  "Brisk capillary refill rules out any perfusion compromise"],
 ans:0,
 rat:{c:"Pain out of proportion and unrelieved by analgesia is the earliest and most reliable sign of compartment syndrome. Pulselessness is a late finding — waiting for it means waiting until tissue is already dying. Perfusion at the capillary level can persist while muscle and nerve are being destroyed.",
  o:["Correct — a present pulse does not exclude compartment syndrome.",
    "Pulse loss is late; excluding the diagnosis here risks irreversible damage.",
    "Pain unrelieved by opioids is a warning sign, not simple underdosing.",
    "Capillary refill can stay brisk while compartment pressure rises."],
  s:"Pain out of proportion is the earliest sign; pulselessness comes far too late."},
 ref:"Orthopedic · compartment syndrome"},

{id:"RRP-061", t:"single", cn:"RRP", sys:"MSK", topic:"Fat embolism syndrome", d:3, b:0.7, cj:"analyze", tags:["orthopedic","pulmonary","petechiae"],
 stem:"Thirty-six hours after a femur fracture a client becomes confused and short of breath, and the nurse notes a fine rash across the chest and axillae. The nurse suspects:",
 opts:["Fat embolism syndrome from marrow entering the circulation",
  "Pulmonary embolism from a deep vein thrombosis",
  "An allergic reaction to the analgesic infusion",
  "Early sepsis from the fracture site"],
 ans:0,
 rat:{c:"The triad of hypoxemia, neurologic change, and a petechial rash over the upper trunk after a long-bone fracture is classic fat embolism syndrome. The rash is what distinguishes it, since pulmonary embolism and sepsis can cause the other two findings without it.",
  o:["Correct — hypoxemia, confusion, and petechiae after a long-bone fracture.",
    "Pulmonary embolism does not produce a petechial upper-trunk rash.",
    "A drug reaction would not explain the timing and neurologic change together.",
    "Sepsis would be expected to show fever and a source of infection."],
  s:"Long-bone fracture plus confusion, hypoxemia, and petechiae is fat embolism."},
 ref:"Orthopedic · fat embolism syndrome"},

{id:"RRP-062", t:"single", cn:"RRP", sys:"NEURO", topic:"Retinal detachment", d:3, b:0.6, cj:"recognize", tags:["ophthalmic","emergency","referral"],
 stem:"A client reports a sudden shower of floaters, flashes of light in the peripheral vision, and a dark curtain spreading across the visual field. The nurse's priority action is to:",
 opts:["Arrange immediate ophthalmologic evaluation",
  "Reassure the client that floaters are a normal age-related change",
  "Schedule a routine vision check at the next clinic visit",
  "Instill lubricating drops and reassess the symptoms in a week"],
 ans:0,
 rat:{c:"Flashes, a shower of floaters, and a curtain-like field loss describe retinal detachment, in which outcomes depend on how quickly the retina is reattached. Reassurance or delay converts a salvageable vision loss into a permanent one.",
  o:["Correct — this presentation needs same-day specialist assessment.",
    "A curtain-like field loss is never a normal age-related finding.",
    "A routine visit loses the window for retinal salvage.",
    "Lubricating drops treat surface dryness, not a detached retina."],
  s:"Flashes, floaters, and a curtain over the field mean detached retina — refer now."},
 ref:"Sensory · retinal detachment"},

/* ── Pharmacological & Parenteral Therapies (blueprint 16%) ───────── */
{id:"PHA-078", t:"single", cn:"PHA", sys:"PSYCH", topic:"Neuroleptic malignant syndrome", d:3, b:0.8, cj:"prioritize", tags:["antipsychotic","hyperthermia","emergency"],
 stem:"A client started on haloperidol five days ago now has severe muscle rigidity, a temperature of 40.2 degrees C, altered mental status, and a creatine kinase of 18,000 units/L. The nurse's priority action is to:",
 opts:["Stop the antipsychotic and prepare for aggressive cooling and hydration",
  "Give the prescribed antipyretic and recheck the temperature hourly",
  "Administer benztropine for the muscle rigidity",
  "Reduce the antipsychotic dose and monitor for improvement"],
 ans:0,
 rat:{c:"Neuroleptic malignant syndrome is a life-threatening reaction to dopamine blockade, marked by rigidity, extreme hyperthermia, autonomic instability, and rhabdomyolysis. The offending drug must stop at once, and treatment is supportive — cooling, fluids, and often dantrolene or a dopamine agonist. A lower dose keeps the trigger in place.",
  o:["Correct — stop the drug and treat hyperthermia and rhabdomyolysis aggressively.",
    "Antipyretics do not counteract this centrally driven hyperthermia.",
    "Benztropine treats extrapyramidal stiffness, not this syndrome.",
    "Dose reduction continues exposure during a life-threatening reaction."],
  s:"NMS: rigidity plus extreme fever plus high CK — stop the antipsychotic now."},
 ref:"Pharmacology · neuroleptic malignant syndrome"},

{id:"PHA-079", t:"single", cn:"PHA", sys:"GI", topic:"Esophageal variceal bleeding", d:3, b:0.75, cj:"prioritize", tags:["cirrhosis","hemorrhage","airway"],
 stem:"A client with cirrhosis vomits a large volume of bright red blood. Blood pressure is 88/54 mm Hg and the heart rate is 126/min. The nurse's first action is to:",
 opts:["Protect the airway by positioning the client on the side and call for help",
  "Insert a nasogastric tube to assess the rate of bleeding",
  "Obtain a type and crossmatch before starting any intravenous access",
  "Administer the prescribed oral beta blocker to lower portal pressure"],
 ans:0,
 rat:{c:"Massive hematemesis threatens the airway before it threatens the circulation — aspiration of blood is what kills quickly. Lateral positioning protects the airway while help and access are mobilized. A nasogastric tube can provoke more bleeding, and an oral drug has no place in active hemorrhagic shock.",
  o:["Correct — airway protection comes first in massive upper bleeding.",
    "Nasogastric insertion risks worsening variceal bleeding.",
    "Crossmatching is essential but must not delay intravenous access.",
    "Oral medication is unsafe and useless in active shock."],
  s:"Massive hematemesis: protect the airway first, then volume and access."},
 ref:"Gastrointestinal · variceal hemorrhage"},

{id:"PHA-080", t:"single", cn:"PHA", sys:"GI", topic:"Octreotide in variceal hemorrhage", d:3, b:0.7, cj:"analyze", tags:["splanchnic","vasoconstriction","mechanism"],
 stem:"A client with bleeding esophageal varices is started on an octreotide infusion. The nurse understands that this drug helps primarily by:",
 opts:["Reducing splanchnic blood flow and therefore portal pressure",
  "Increasing the production of clotting factors by the liver",
  "Raising systemic blood pressure to perfuse vital organs",
  "Neutralizing gastric acid to stabilize the bleeding site"],
 ans:0,
 rat:{c:"Octreotide is a somatostatin analogue that selectively constricts splanchnic vessels, lowering portal inflow and pressure at the varix. It does not correct the coagulopathy of cirrhosis, and it is not a systemic pressor or an acid suppressant — those are separate parts of the same treatment bundle.",
  o:["Correct — splanchnic vasoconstriction lowers portal pressure at the varix.",
    "Clotting factor replacement is done with plasma or vitamin K, not octreotide.",
    "Systemic pressors are not the mechanism and may raise portal pressure.",
    "Acid suppression is a different drug class with a different target."],
  s:"Octreotide lowers portal inflow; it does not fix coagulopathy or acid."},
 ref:"Pharmacology · portal hypertension management"},

{id:"PHA-081", t:"single", cn:"PHA", sys:"CV", topic:"Patent ductus arteriosus pharmacologic closure", d:3, b:0.65, cj:"analyze", tags:["neonatal","prostaglandin","contraindication"],
 stem:"A premature infant with a hemodynamically significant patent ductus arteriosus is prescribed indomethacin. The nurse recognizes that this drug must be withheld if the infant also has:",
 opts:["Active gastrointestinal bleeding or thrombocytopenia",
  "A patent foramen ovale on echocardiography",
  "Mild jaundice with a bilirubin of 8 mg/dL",
  "Transient tachypnea that is already improving"],
 ans:0,
 rat:{c:"Indomethacin closes the ductus by inhibiting prostaglandin synthesis, but the same mechanism impairs platelet function and reduces renal and gut perfusion. Active bleeding, thrombocytopenia, or renal impairment are contraindications. The other findings are common in premature infants and do not preclude treatment.",
  o:["Correct — bleeding risk and low platelets contraindicate a prostaglandin inhibitor.",
    "A patent foramen ovale is common in prematurity and not a contraindication.",
    "Mild jaundice is unrelated to prostaglandin inhibition.",
    "Improving tachypnea is not a reason to withhold closure therapy."],
  s:"Indomethacin closes the ductus but is unsafe with bleeding, low platelets, or renal failure."},
 ref:"Pharmacology · patent ductus arteriosus"},

/* ── Safety and Infection Control (blueprint 13%) ─────────────────── */
{id:"SIC-058", t:"single", cn:"SIC", sys:"RESP", topic:"Epiglottitis airway risk", d:3, b:0.75, cj:"prioritize", tags:["pediatric","airway","droplet"],
 stem:"A child presents with a sudden high fever, drooling, muffled voice, and a forward-leaning posture, and has not been fully immunized. The nurse's priority action is to:",
 opts:["Keep the child calm and avoid any attempt to inspect the throat",
  "Use a tongue blade to visualize the throat and confirm the diagnosis",
  "Place the child supine to make breathing easier during assessment",
  "Send the child to radiology alone for a lateral neck film"],
 ans:0,
 rat:{c:"This presentation is classic epiglottitis, in which the swollen epiglottis can obstruct completely and without warning. Any agitation or instrumentation of the throat can trigger total obstruction, so the child is kept calm with the airway equipment and skilled personnel at the bedside. Supine positioning worsens the obstruction.",
  o:["Correct — keep the child calm and do not instrument the airway.",
    "A tongue blade can precipitate complete obstruction.",
    "The child instinctively leans forward because supine worsens obstruction.",
    "Sending the child unaccompanied risks losing the airway in transit."],
  s:"Suspected epiglottitis: never examine the throat, keep the child calm, secure the airway."},
 ref:"Infection control · epiglottitis"},

{id:"SIC-059", t:"single", cn:"SIC", sys:"RESP", topic:"Croup droplet precautions", d:3, b:0.55, cj:"recognize", tags:["pediatric","isolation","stridor"],
 stem:"A toddler is admitted with a barking cough, inspiratory stridor, and a low-grade fever consistent with viral croup. Which precaution does the nurse implement?",
 opts:["Droplet precautions in addition to standard precautions",
  "Airborne precautions in a negative-pressure room",
  "Contact precautions because the virus spreads by touch",
  "Standard precautions only, since croup is not contagious"],
 ans:0,
 rat:{c:"Croup is most often parainfluenza, spread in respiratory droplets over short distances. Droplet precautions with a mask within about three feet are appropriate. It is not airborne like measles or tuberculosis, and it is contagious, so standard precautions alone are insufficient.",
  o:["Correct — droplet precautions cover the parainfluenza transmission route.",
    "Airborne precautions are reserved for smaller nuclei that stay suspended.",
    "Contact precautions are not the primary route for croup.",
    "Croup is contagious; standard precautions alone do not contain it."],
  s:"Croup is droplet spread — mask within three feet, not airborne isolation."},
 ref:"Infection control · pediatric respiratory isolation"},

{id:"SIC-060", t:"single", cn:"SIC", sys:"GI", topic:"Reye syndrome and aspirin avoidance", d:3, b:0.6, cj:"recognize", tags:["pediatric","medication-safety","viral"],
 stem:"A parent asks what to give a seven-year-old with fever from a suspected influenza infection. The nurse's best response is to advise:",
 opts:["Acetaminophen or ibuprofen, and to avoid aspirin entirely",
  "Aspirin, because it reduces fever faster in children",
  "Aspirin only if the fever exceeds 39.5 degrees C",
  "Alternating aspirin and acetaminophen every four hours"],
 ans:0,
 rat:{c:"Aspirin given during a viral illness in a child is linked to Reye syndrome, a rapidly progressive encephalopathy with hepatic failure. The risk is why aspirin is avoided throughout childhood for fever, not limited to high temperatures or specific viruses.",
  o:["Correct — use acetaminophen or ibuprofen and avoid aspirin altogether.",
    "Aspirin is contraindicated for fever in children regardless of speed.",
    "There is no safe fever threshold for aspirin in this setting.",
    "Alternating still exposes the child to aspirin."],
  s:"Never give aspirin for fever in a child — the risk is Reye syndrome."},
 ref:"Safety · pediatric medication precautions"},

/* ── Basic Care and Comfort (blueprint 9%) ────────────────────────── */
{id:"BCC-040", t:"single", cn:"BCC", sys:"REN", topic:"Nephrotic syndrome corticosteroid therapy", d:3, b:0.55, cj:"analyze", tags:["pediatric","steroid","monitoring"],
 stem:"A child with nephrotic syndrome is started on high-dose prednisone. Which finding should the nurse report promptly to the provider?",
 opts:["A temperature of 38.6 degrees C with no other symptoms",
  "Weight gain of 0.4 kg since the previous day",
  "Mild periorbital edema in the morning",
  "Increased appetite and mild irritability"],
 ans:0,
 rat:{c:"High-dose corticosteroids blunt the inflammatory response and mask the usual signs of infection, so a fever without localizing symptoms may be the only clue to a serious infection in an immunosuppressed child. The other findings are expected effects of either the disease or the drug.",
  o:["Correct — fever during immunosuppression needs prompt evaluation.",
    "Small daily weight shifts are expected and monitored, not urgent alone.",
    "Morning periorbital edema is a known feature of the disease.",
    "Appetite change and irritability are expected steroid effects."],
  s:"On high-dose steroids, a fever with no source is a red flag, not a minor finding."},
 ref:"Basic care · corticosteroid monitoring"},

{id:"BCC-041", t:"single", cn:"BCC", sys:"GI", topic:"Abdominal compartment syndrome", d:3, b:0.75, cj:"analyze", tags:["postoperative","perfusion","monitoring"],
 stem:"A client after damage-control laparotomy has a tensely distended abdomen, a peak airway pressure rising on the ventilator, a urine output of 10 mL in the last hour, and a bladder pressure of 26 mm Hg. The nurse interprets this as:",
 opts:["Abdominal compartment syndrome requiring urgent surgical evaluation",
  "Expected postoperative ileus resolving with time",
  "Acute kidney injury from the contrast given earlier",
  "Atelectasis requiring more aggressive pulmonary toilet"],
 ans:0,
 rat:{c:"Intra-abdominal pressure above roughly 20 mm Hg with new organ dysfunction defines abdominal compartment syndrome. The pressure pushes up on the diaphragm, raising airway pressure, and compresses the renal vasculature, cutting urine output. Ileus does not produce this pressure or this degree of organ failure.",
  o:["Correct — raised bladder pressure with organ failure is a surgical emergency.",
    "Ileus does not raise airway pressure or abolish urine output this way.",
    "Contrast nephropathy would not explain the tense abdomen or airway pressure.",
    "Atelectasis does not cause oliguria with a bladder pressure of 26 mm Hg."],
  s:"Bladder pressure over 20 with organ failure is abdominal compartment syndrome."},
 ref:"Basic care · intra-abdominal hypertension"},

{id:"BCC-042", t:"single", cn:"BCC", sys:"GI", topic:"Cystic fibrosis pancreatic enzyme administration", d:3, b:0.6, cj:"act", tags:["pediatric","nutrition","timing"],
 stem:"A child with cystic fibrosis is prescribed pancreatic enzymes with meals. Which instruction does the nurse include?",
 opts:["Give the enzymes at the start of the meal, and with every snack",
  "Give the enzymes one hour after the meal is finished",
  "Give the enzymes only with meals that contain fat",
  "Crush the capsules and mix them into a glass of milk"],
 ans:0,
 rat:{c:"Pancreatic insufficiency in cystic fibrosis means enzymes must be present in the gut when food arrives, so they are given at the start of eating and with every feeding including snacks. Delayed dosing misses the food, restricting to fatty meals under-treats, and crushing damages the enteric coating.",
  o:["Correct — enzymes at the start of every meal and snack.",
    "Enzymes given after eating cannot mix with the food bolus.",
    "Enzymes are needed for all nutrients, not only fat.",
    "Crushing destroys the coating and inactivates the enzymes."],
  s:"Pancreatic enzymes: at the start of every meal and snack, never crushed."},
 ref:"Basic care · cystic fibrosis nutrition"},

/* ── Health Promotion and Maintenance (blueprint 9%) ──────────────── */
{id:"HPM-040", t:"single", cn:"HPM", sys:"REPI", topic:"Safe sleep and sudden infant death", d:3, b:-0.4, cj:"generate", tags:["infant","safety","teaching"],
 stem:"A parent of a two-month-old says the infant sleeps best on his stomach and that she has been placing him that way at night. The nurse's best response is to:",
 opts:["Explain that supine sleeping is required for every sleep until age one",
  "Agree that stomach sleeping is fine once the infant can roll over",
  "Suggest side sleeping as an equally safe compromise position",
  "Recommend propping the infant with a pillow to keep him supine"],
 ans:0,
 rat:{c:"Supine positioning for every sleep until the first birthday is the single strongest protective measure against sudden infant death. Side sleeping is unstable and infants roll prone; pillows and soft bedding are themselves a suffocation hazard and are excluded from the sleep space.",
  o:["Correct — supine for every sleep, including naps, through the first year.",
    "Prone sleeping is unsafe even if the infant can roll; he is still placed supine.",
    "Side sleeping is not a safe alternative because infants roll to prone.",
    "Pillows in the sleep space create a suffocation risk."],
  s:"Back to sleep for every sleep until age one, on a firm surface with nothing else in the bed."},
 ref:"Health promotion · infant safe sleep"},

{id:"HPM-041", t:"single", cn:"HPM", sys:"GI", topic:"Phenylketonuria dietary management", d:3, b:0.4, cj:"generate", tags:["newborn","metabolic","diet"],
 stem:"A newborn screening test confirms phenylketonuria. Which teaching point is most important for the parents?",
 opts:["A phenylalanine-restricted diet must begin promptly and continue for life",
  "Dietary restriction is needed only until the child reaches school age",
  "Breastfeeding must be stopped completely and replaced with formula",
  "The diet is needed only during periods of illness or rapid growth"],
 ans:0,
 rat:{c:"Untreated phenylalanine accumulation causes irreversible intellectual disability, so restriction must start within the first weeks of life. Current guidance is lifelong, because cognitive decline can follow relaxation in adulthood. Breast milk is low in phenylalanine and is often permitted in measured amounts alongside medical formula.",
  o:["Correct — start early and maintain the restriction for life.",
    "Stopping in childhood risks later cognitive decline.",
    "Measured breastfeeding is usually compatible with the diet.",
    "Intermittent restriction allows accumulation between periods."],
  s:"Phenylketonuria: restrict phenylalanine early and keep it lifelong."},
 ref:"Health promotion · newborn metabolic screening"},

{id:"HPM-042", t:"single", cn:"HPM", sys:"GI", topic:"Intussusception reduction", d:3, b:0.5, cj:"recognize", tags:["pediatric","emergency","procedure"],
 stem:"An eight-month-old has intermittent episodes of drawing the legs up and crying, with a currant-jelly stool. The nurse understands that the expected treatment is:",
 opts:["An air or contrast enema to reduce the telescoped segment",
  "Immediate surgical resection of the involved bowel",
  "Intravenous fluids and observation until symptoms resolve",
  "A high-fiber diet to relieve the obstruction"],
 ans:0,
 rat:{c:"The triad of intermittent colicky pain, drawing up of the legs, and currant-jelly stool indicates intussusception. Hydrostatic or pneumatic enema reduces the telescoped segment in most cases and is both diagnostic and therapeutic. Surgery is reserved for failed reduction or signs of perforation, and observation risks bowel necrosis.",
  o:["Correct — enema reduction is the first-line treatment in most cases.",
    "Surgery follows only if reduction fails or perforation is suspected.",
    "Observing an obstruction risks ischemia and perforation.",
    "Fiber does not relieve a mechanical telescoping of bowel."],
  s:"Intussusception: enema reduces it; surgery is the fallback, not the first step."},
 ref:"Health promotion · pediatric abdominal emergencies"}
);
