/* RN Ready — item bank v3c · part 4 (Maternity-Newborn, Pediatrics, Renal/Heme/Onc,
   plus VARIANT items for anti-memorization). variantGroup links an original to its
   alternates: the engine never serves two items of the same group in one exam,
   and re-tests rotate through the group.                                        */
NC.BANK = NC.BANK || [];
NC.BANK.push(

/* ── Maternity & Newborn ────────────────────────────────────────── */
{id:"PHA-027", t:"single", cn:"PHA", sys:"REPI", topic:"Magnesium sulfate", d:1, b:-0.25, cj:"act", tags:["medication","priority","safety"],
 stem:"A client receiving magnesium sulfate for severe preeclampsia has an absent deep tendon reflex patellar response, respiratory rate 10/min, and urine output 20 mL/hr. Which action is the priority?",
 opts:["Continue the infusion and recheck reflexes in 1 hour","Stop the infusion and prepare to administer calcium gluconate","Increase the infusion rate to control the preeclampsia","Administer a bolus of lactated Ringer's"],
 ans:1,
 rat:{c:"Absent reflexes with respiratory depression (RR<12) and oliguria indicate magnesium toxicity — stop the infusion immediately and prepare IV calcium gluconate (the antidote) while monitoring respirations and urine output.",
 o:["Waiting allows toxicity to progress to respiratory arrest.","Correct — stop magnesium, give calcium gluconate, support respirations.","Increasing a toxic infusion worsens respiratory depression.","Fluids do not reverse magnesium toxicity; the antidote does."],
 s:"Magnesium gates before EACH dose/assessment: DTRs present, RR ≥12, urine ≥30 mL/hr. Toxicity ladder: flushing → ↓reflexes → absent reflexs → respiratory depression → cardiac arrest. Antidote: calcium gluconate."},
 ref:"High-alert medications in obstetrics"},

{id:"PAA-031", t:"single", cn:"PAA", sys:"REPI", topic:"Severe preeclampsia", d:2, b:0.6, cj:"act", tags:["priority","assessment"],
 stem:"A client at 34 weeks' gestation with severe preeclampsia is receiving magnesium sulfate. Which assessment is most important before administering the next dose?",
 opts:["Deep tendon reflexes, respiratory rate, and urine output","Fetal heart rate pattern","Blood glucose level","Edema of the lower extremities"],
 ans:0,
 rat:{c:"Magnesium is excreted renally and depresses neuromuscular function — DTRs, RR ≥12, and urine ≥30 mL/hr must be verified before every dose to prevent toxicity.",
 o:["Correct — the three safety gates for magnesium.","FHR matters but does not detect maternal toxicity before dosing.","Glucose is unrelated to magnesium safety.","Edema reflects the disease, not magnesium clearance."],
 s:"Test-writers pair magnesium with “check reflexes, respirations, urine.” If those appear in options together, they are almost always the answer."},
 ref:"Obstetric complications · preeclampsia management"},

{id:"PAA-032", t:"matrix", cn:"PAA", sys:"REPI", topic:"Postpartum assessment", d:1, b:-0.2, cj:"analyze", tags:["assessment","priority"],
 stem:"The nurse assesses a client 24 hours after vaginal delivery. For each finding, indicate whether it is EXPECTED for this stage or ABNORMAL and requiring follow-up.",
 matrix:{cols:["Expected","Abnormal"], mode:"radio",
  rows:["Fundus firm at the level of the umbilicus","Lochia rubra, moderate amount, no clots larger than a grape","Blood pressure 152/96 mm Hg with new headache and visual spots","Saturating a perineal pad in 15 minutes"],
  ans:[0,0,1,1]},
 rat:{c:"A firm mid-umbilical fundus and moderate rubra lochia are normal on day 1. Hypertension with neurologic symptoms suggests severe preeclampsia/postpartum preeclampsia, and rapid pad saturation signals postpartum hemorrhage — both require immediate action.",
 o:["Firm fundus at umbilicus = expected involution.","Moderate rubra without large clots = expected.","BP 152/96 + headache/scotomata = abnormal (preeclampsia) — escalate.","Pad q15min = abnormal bleeding — massage fundus, notify, prepare oxytocin."],
 s:"Postpartum red flags: boggy fundus, pad/hour (or q15min), BP ≥140/90 with symptoms, fever ≥38 after 24h, calf pain, mood crash beyond blues."},
 ref:"Postpartum assessment & complications"},

{id:"PAA-033", t:"single", cn:"PAA", sys:"REPI", topic:"Labor decelerations", d:2, b:0.7, cj:"act", tags:["priority","intervention","safety"],
 stem:"During labor induction with oxytocin, the monitor shows recurrent late decelerations with minimal variability. Which action should the nurse take first?",
 opts:["Increase the oxytocin rate to shorten labor","Reposition the client to a side-lying position and apply oxygen","Perform a sterile vaginal examination","Encourage the client to walk in the hallway"],
 ans:1,
 rat:{c:"Late decelerations signal uteroplacental insufficiency. First-line intrauterine resuscitation: stop/reduce oxytocin, lateral positioning, IV fluid bolus, oxygen by face mask — then notify the provider.",
 o:["More oxytocin intensifies contractions and worsens placental insufficiency.","Correct — reposition + oxygen (and stop oxytocin/IV bolus) are the immediate response.","An examination does not address placental perfusion.","Walking is unsafe during active monitoring of an abnormal tracing."],
 s:"Deceleration first-aid: LATE (placenta) → side + O2 + stop oxytocin + fluids. VARIABLE (cord) → reposition off cord (knee-chest) ± fluid bolus. EARLY (head compression) → usually benign, monitor."},
 ref:"Fetal monitoring · intrauterine resuscitation"},

{id:"PHA-028", t:"single", cn:"PHA", sys:"REPI", topic:"Oxytocin induction", d:1, b:-0.15, cj:"act", tags:["medication","safety","priority"],
 stem:"During oxytocin induction, the nurse notes contractions every 90 seconds lasting 110 seconds with fetal heart rate decelerations. Which action is the priority?",
 opts:["Document the contraction pattern and reassess in 30 minutes","Stop the oxytocin infusion","Slow the oxytocin rate by half","Place the client in a high-Fowler position"],
 ans:1,
 rat:{c:"Contractions closer than every 2 minutes lasting >90 seconds (tachysystole) with FHR changes require immediately stopping oxytocin, then lateral positioning, IV fluids, and oxygen.",
 o:["Waiting 30 minutes risks fetal compromise.","Correct — stop the infusion; it is the causative agent and the fastest intervention.","Adjusting rates is a provider decision and slower than stopping.","Lateral position helps, but stopping the causative drug comes first."],
 s:"Oxytocin safety: tachysystole + FHR change = STOP first, then resuscitate (side-lying, fluids, O2). Never “wait and document” an abnormal tracing."},
 ref:"Labor induction · oxytocin complications"},

{id:"RRP-017", t:"single", cn:"RRP", sys:"REPI", topic:"Antepartum fetal testing", d:1, b:-0.3, cj:"evaluate", tags:["assessment","teaching"],
 stem:"A client at 38 weeks' gestation reports decreased fetal movement. A nonstress test (NST) shows two accelerations of 15 beats/min lasting 15 seconds with fetal movement in 20 minutes. How should the nurse interpret this result?",
 opts:["Nonreactive — the fetal tracing needs further testing","Reactive — reassuring fetal well-being","Equivocal — immediate delivery is indicated","Inconclusive — repeat in one week"],
 ans:1,
 rat:{c:"Two accelerations ≥15 bpm for ≥15 seconds in 20 minutes = a reactive NST, which indicates adequate fetal oxygenation and well-being at that time.",
 o:["Nonreactive means the criteria were NOT met — this test met them.","Correct — reactive NST (criteria met) is reassuring.","No finding here supports immediate delivery.","Reactive now → routine follow-up, not a one-week uncertainty."],
 s:"NST mnemonic: 2×15×15 (two accelerations, 15 bpm, 15 s) in 20 min = reactive = good. Nonreactive → extended monitoring/BPP/contraction stress test."},
 ref:"Antepartum fetal assessment"},

{id:"PSY-012", t:"single", cn:"PSY", sys:"REPI", topic:"Postpartum mood changes", d:1, b:-0.2, cj:"evaluate", tags:["assessment","teaching"],
 stem:"A client calls the clinic 10 days after delivery: “I cry for no reason, I can't sleep even when the baby sleeps, and I feel like I'm not a good mother.” Which response is most appropriate?",
 opts:["“That's the baby blues — it always passes on its own by six weeks.”","“Those feelings can be more than blues — I'd like to have you speak with a provider today. Are you having any thoughts of harming yourself?”","“Try to nap when the baby naps and accept help with housework.”","“Every new mother feels overwhelmed; give it time.”"],
 ans:1,
 rat:{c:"Crying plus insomnia despite the baby sleeping and feelings of inadequacy at 10 days postpartum exceed typical blues (which peak day 3–5 and resolve ≤2 weeks). Screen for postpartum depression and self-harm and arrange same-day provider contact.",
 o:["Dismissal without screening — insomnia out of proportion and timing suggest depression, and blues never justify skipping a suicide screen.","Correct — escalate with a direct, caring safety screen.","Sleep advice is fine but ignores red-flag symptoms.","Minimizing language closes the conversation."],
 s:"Blues: days 3–5, mild, resolves ≤2 weeks, intact function. Red flags: >2 weeks, worsening, insomnia despite baby sleeping, worthlessness, intrusive thoughts → screen + refer. Always ask about self-harm."},
 ref:"Postpartum mental health"},

{id:"BCC-010", t:"single", cn:"BCC", sys:"REPI", topic:"Newborn care", d:0, b:-1.1, cj:"evaluate", tags:["teaching"],
 stem:"The nurse teaches the parent of a 3-day-old newborn about sponge bathing. Which statement indicates correct understanding?",
 opts:["“I'll give a tub bath daily to keep the cord stump clean.”","“I'll sponge-bathe until the cord stump falls off and heals, and keep the stump dry.”","“I'll clean the cord stump with alcohol at every diaper change.”","“Bathing isn't needed until the umbilical cord falls off by 6 weeks.”"],
 ans:1,
 rat:{c:"Current guidance: sponge baths only until the cord stump detaches (typically 10–14 days); keep the stump clean and DRY (fold the diaper below it); alcohol swabbing is no longer recommended.",
 o:["Immersion tub bathing before cord detachment is discouraged.","Correct — dry cord care + sponge bathing until the stump is gone.","Alcohol care delays detachment and is outdated.","The cord usually falls off in 1–2 weeks — 6 weeks is abnormal; bathing is needed before then."],
 s:"Newborn cord care on the exam: keep dry, sponge-bathe only, no alcohol, fold diaper below stump, report redness/foul drainage (omphalitis)."},
 ref:"Newborn care teaching"},

/* ── Pediatrics ─────────────────────────────────────────────────── */
{id:"PAA-034", t:"single", cn:"PAA", sys:"RESP", topic:"Bronchiolitis", d:1, b:-0.35, cj:"act", tags:["intervention","priority"],
 stem:"A 6-month-old infant with bronchiolitis has copious nasal secretions and is having difficulty feeding. Which action should the nurse take before feedings?",
 opts:["Suction the nose with a bulb syringe before feeds","Offer the feeding through a straw cup","Increase oxygen to 100%","Place the infant prone after feeding"],
 ans:0,
 rat:{c:"Infants are obligate nose breathers — clearing nasal secretions with a bulb syringe immediately before feeds restores the airway and is the priority intervention for feeding difficulty in bronchiolitis.",
 o:["Correct — suction before feeds; saline drops can loosen secretions.","A 6-month-old cannot manage a straw cup and it doesn't fix the airway.","Oxygen is titrated to saturation — 100% is not a feeding fix and oxygen toxicity matters.","Prone positioning is a SIDS risk; elevate the head of the crib instead."],
 s:"Bronchiolitis care bundle: suction before feeds, small frequent feeds, monitor SpO2/Work of breathing, supportive care — most need no bronchodilators."},
 ref:"Pediatric respiratory illness"},

{id:"PHA-029", t:"single", cn:"PHA", sys:"INF", topic:"Acetaminophen overdose", d:2, b:0.75, cj:"act", tags:["medication","priority","safety"],
 stem:"A toddler is brought to the emergency department after ingesting a bottle of acetaminophen elixir 2 hours ago. Which antidote does the nurse anticipate administering?",
 opts:["Naloxone","N-acetylcysteine","Flumazenil","Deferoxamine"],
 ans:1,
 rat:{c:"Acetaminophen overdose depletes glutathione, producing hepatotoxicity; N-acetylcysteine replenishes glutathione and is most effective within 8–10 hours of ingestion.",
 o:["Naloxone reverses opioids.","Correct — NAC for acetaminophen.","Flumazenil reverses benzodiazepines.","Deferoxamine chelates iron."],
 s:"Antidote pairs to memorize: acetaminophen→NAC · opioids→naloxone · benzodiazepines→flumazenil · iron→deferoxamine · warfarin→vitamin K · heparin→protamine · magnesium→calcium gluconate."},
 ref:"Pediatric poisoning management"},

{id:"SIC-011", t:"single", cn:"SIC", sys:"INF", topic:"Poisoning prevention", d:0, b:-1.2, cj:"prioritize", tags:["safety","teaching"],
 stem:"The nurse teaches poisoning-prevention to parents of a 2-year-old. Which instruction is most important?",
 opts:["Store medications and cleaning products in locked cabinets, in original containers","Keep ipecac syrup on hand to induce vomiting","Store products under the sink for quick access","Rely on child-resistant caps alone"],
 ans:0,
 rat:{c:"Toddlers (1–3 y) are the peak poisoning age — the core prevention is locked, high, original-container storage. Ipecac is obsolete, under-sink storage invites access, and “child-resistant” is not childproof.",
 o:["Correct — locked + original containers + out of reach.","Ipecac is no longer recommended and can be harmful.","Under the sink is the most-accessed spot for a toddler.","Child-resistant packaging delays access ~minutes — not a strategy."],
 s:"Poison prevention = locked, high, original containers, never food containers; post poison control number. If ingested: call poison control; do NOT induce vomiting."},
 ref:"Injury prevention · toddler safety"},

{id:"PSY-013", t:"single", cn:"PSY", sys:"PSYCH", topic:"Autism spectrum", d:1, b:-0.1, cj:"recognize", tags:["assessment","teaching"],
 stem:"At an 18-month well-child visit, the parent reports the child does not respond to their name, avoids eye contact, and has not spoken any words. Which action is most appropriate?",
 opts:["Reassure the parent that boys talk late","Refer for a developmental/autism evaluation promptly","Wait until the 24-month visit to reassess","Suggest limiting screen time and reassess in 6 months"],
 ans:1,
 rat:{c:"No response to name, poor eye contact, and absent words at 18 months are autism-spectrum red flags — screening positives warrant prompt referral because early intervention measurably improves outcomes.",
 o:["Reassurance delays intervention — these are not normal variants at 18 months.","Correct — refer now; early intensive intervention works best before age 3.","Waiting 6 months loses critical intervention time.","Screen-time advice does not address red-flag symptoms."],
 s:"Autism flags at 18–24 months: no name response, no pointing/joint attention, no words, poor eye contact, repetitive play. On the exam: refer early — never “wait and see.”"},
 ref:"Pediatric developmental screening"},

{id:"PAA-035", t:"single", cn:"PAA", sys:"GI", topic:"Intussusception", d:2, b:0.7, cj:"act", tags:["priority","assessment"],
 stem:"A 14-month-old has intermittent severe abdominal pain with drawing up of the legs, vomiting, and a stool with blood and mucus (“currant jelly”). Which action is the priority?",
 opts:["Administer an antispasmodic as prescribed","Notify the provider immediately and keep the child NPO for a possible enema reduction","Encourage oral clear fluids to prevent dehydration","Apply a warm compress and observe for 1 hour"],
 ans:1,
 rat:{c:"Pain drawing up legs + currant-jelly stool suggests intussusception — an obstruction emergency risk (perforation, sepsis). Priority: NPO, notify, anticipate air/hydrostatic enema reduction or surgery.",
 o:["Medicating symptoms delays diagnosis.","Correct — NPO + immediate escalation; enema reduction is both diagnostic and therapeutic.","Fluids are contraindicated with obstruction; NPO is required.","Observation risks bowel ischemia and perforation."],
 s:"Triad: episodic colicky pain with knees drawn + sausage-shaped mass + red-currant-jelly stool. Treatment: pneumatic/hydrostatic enema; surgery if perforation. Keep NPO."},
 ref:"Pediatric gastrointestinal emergencies"},

{id:"RRP-018", t:"single", cn:"RRP", sys:"REN", topic:"Nephrotic syndrome", d:1, b:-0.25, cj:"analyze", tags:["assessment"],
 stem:"A 4-year-old is admitted with periorbital edema, dependent edema, frothy urine, and marked proteinuria with hypoalbuminemia. How should the nurse describe the cause of the edema?",
 opts:["Protein loss lowers plasma oncotic pressure, shifting fluid into the tissues","Excess sodium intake causes water retention","Heart failure is backing up fluid into the tissues","Kidney failure causes toxin accumulation and edema"],
 ans:0,
 rat:{c:"In nephrotic syndrome the damaged glomerulus leaks albumin; hypoalbuminemia drops plasma oncotic pressure, so fluid moves into interstitial space (edema) — the classic mechanism to teach families.",
 o:["Correct — albumin loss → low oncotic pressure → edema.","Dietary sodium is not the primary mechanism.","The cardiac system is not the driver here.","Nephrotic syndrome is not primarily an excretory (toxin) failure."],
 s:"Nephrotic vs nephritic: nephrotic = MASSIVE proteinuria, hypoalbuminemia, edema, hyperlipidemia (leaky filter). Nephritic = hematuria, hypertension, mild proteinuria (inflamed filter)."},
 ref:"Pediatric renal disorders"},

/* ── Renal / Hematologic / Oncologic ────────────────────────────── */
{id:"RRP-019", t:"single", cn:"RRP", sys:"REN", topic:"Acute kidney injury", d:1, b:-0.2, cj:"act", tags:["assessment","priority"],
 stem:"A client develops prerenal acute kidney injury after major surgery. Which parameters are most important for the nurse to monitor?",
 opts:["Daily weight, strict intake and output, and blood pressure","Serum glucose every 4 hours","Liver function tests weekly","Deep tendon reflexes hourly"],
 ans:0,
 rat:{c:"Prerenal AKI is driven by renal hypoperfusion — fluid balance is the therapy and the risk. Daily weight (same scale, same time), strict I&O, and BP guide volume management and detect deterioration earliest.",
 o:["Correct — weight/I&O/BP are the renal triad.","Glucose monitoring is unrelated.","LFTs do not track renal perfusion.","DTRs monitor magnesium toxicity, not AKI."],
 s:"AKI nursing core: daily weight, I&O, BP, potassium/phosphate/acid-base, nephrotoxin review (NSAIDs, contrast, aminoglycosides), and dose-adjusting renally cleared drugs."},
 ref:"Acute kidney injury · monitoring"},

{id:"BCC-011", t:"single", cn:"BCC", sys:"REN", topic:"Renal diet", d:1, b:-0.3, cj:"generate", tags:["teaching"],
 stem:"The nurse teaches a client with chronic kidney disease about the renal diet. Which food choice is most appropriate?",
 opts:["Bananas, potatoes, and orange juice","Grilled chicken, white rice, and apples","Bran cereal, nuts, and dark colas","Dairy with every meal"],
 ans:1,
 rat:{c:"Renal diets limit potassium, phosphorus, sodium, and often protein. Chicken (moderate protein), white rice, and apples are low-K/low-Phos choices. Bananas/potatoes/OJ are potassium-rich; bran/nuts/colas and dairy are phosphate-rich.",
 o:["High-potassium cluster — dysrhythmia risk in CKD.","Correct — low K, low Phos, controlled protein.","High-phosphorus cluster (bran, nuts, cola).","Dairy is high in phosphorus and protein."],
 s:"Renal diet quick map: potassium (bananas, potatoes, citrus, tomatoes, salt substitutes), phosphorus (dairy, nuts, colas, bran), sodium (processed foods). Apples, rice, peppers, and berries are safe staples."},
 ref:"Nutrition in chronic kidney disease"},

{id:"PAA-036", t:"multi", cn:"PAA", sys:"HEME", topic:"Sickle cell disease", d:1, b:-0.2, cj:"generate", tags:["teaching","intervention"],
 stem:"The nurse teaches a adolescent client with sickle cell disease how to prevent vaso-occlusive crises. Which instructions should be included? Select all that apply.",
 opts:["Drink 8–10 glasses of water daily","Avoid high altitudes and low-oxygen environments","Take prescribed folic acid","Use a tourniquet-style tight bandage on painful joints","Receive recommended vaccinations including pneumococcal"],
 ans:[0,1,2,4],
 rat:{c:"Crisis prevention targets triggers: dehydration, hypoxia (altitude), infection (vaccines, folic acid for rapid RBC turnover), extreme temperatures, and strenuous exertion. Constriction devices are never used — they impair circulation.",
 o:["Correct — hydration reduces viscosity.","Correct — hypoxia drives sickling.","Correct — folic acid supports heightened erythropoiesis.","Never constrict — worsens ischemia.","Correct — infection is a major crisis trigger; functional asplenia raises risk."],
 s:"Sickle crisis prevention = FLAT: Fluids, Low-altitude/oxygen, Avoid infection/extremes, Take folic acid. Crisis management: O2 + hydration + analgesia + treat triggers."},
 ref:"Hematologic disorders · sickle cell disease"},

{id:"RRP-020", t:"single", cn:"RRP", sys:"HEME", topic:"Hemophilia", d:1, b:-0.15, cj:"act", tags:["priority","safety"],
 stem:"A child with hemophilia A falls from a bike and reports knee pain with visible swelling. Which action is the priority?",
 opts:["Apply ice and elevate, then send home with instructions","Administer the missing clotting factor as prescribed and assess the joint","Encourage range-of-motion exercises immediately","Administer aspirin for pain"],
 ans:1,
 rat:{c:"Joint bleeding (hemarthrosis) in hemophilia requires prompt factor replacement to stop bleeding, alongside rest/ice/elevation — factor first, then supportive care. Aspirin worsens bleeding.",
 o:["Ice/elevation alone cannot stop the bleed — factor is definitive.","Correct — replace factor promptly to limit joint destruction.","Early ROM worsens an active hemarthrosis.","Aspirin inhibits platelets — contraindicated; use acetaminophen."],
 s:"Hemophilia rules: factor replacement FIRST for any bleeding episode; no IM injections, no aspirin/NSAIDs; protect joints (RICE after factor); screen for hidden head-trauma bleeds (any head bump = emergency)."},
 ref:"Hematologic disorders · hemophilia"},

{id:"SIC-012", t:"multi", cn:"SIC", sys:"INF", topic:"Neutropenic precautions", d:1, b:-0.25, cj:"generate", tags:["safety","intervention"],
 stem:"A client receiving chemotherapy has an absolute neutrophil count of 400/mm³. Which precautions should the nurse implement? Select all that apply.",
 opts:["No fresh flowers or plants in the room","Thorough hand hygiene before care and no staff with active infections","Eliminate fresh raw fruits and vegetables from the diet","Place the client in a negative-pressure room","Monitor temperature and report a single reading ≥38.0 °C"],
 ans:[0,1,2,4],
 rat:{c:"Neutropenic (protective) precautions minimize organisms: no flowers/standing water, meticulous hand hygiene, no ill visitors/staff, no raw fresh produce (bacteria/fungi), and fever ≥38.0 °C is an emergency requiring cultures and antibiotics. Negative-pressure rooms are for airborne-disease SOURCE control (e.g., TB), not neutropenia — protective environments use positive pressure with HEPA filtration.",
 o:["Correct — soil/water organisms (Pseudomonas, Aspergillus).","Correct — hand hygiene is the #1 measure; sick people stay away.","Correct — raw produce carries bacterial/fungal load.","Negative pressure is for isolating contagious clients, not protecting this one.","Correct — a single 38.0 °C in neutropenia = infection until proven otherwise; act within the hour."],
 s:"Neutropenia (ANC <500): protect from organisms (no flowers/raw produce/sick contacts), HEPA/positive pressure if available, low-bacterial diet, no rectal temps/suppositories. Fever ≥38 = sepsis workup NOW."},
 ref:"Oncology care · infection prevention"},

{id:"BCC-012", t:"multi", cn:"BCC", sys:"HEME", topic:"Iron deficiency anemia", d:0, b:-1.15, cj:"generate", tags:["teaching","medication"],
 stem:"The nurse teaches a client starting oral iron sulfate for iron deficiency anemia. Which instructions are correct? Select all that apply.",
 opts:["Take iron with vitamin C (e.g., orange juice) to boost absorption","Expect stools to turn dark green or black","Take with a glass of milk to prevent stomach upset","Use a straw if liquid preparations stain teeth","Space iron at least 2 hours from calcium, antacids, and tea"],
 ans:[0,1,3,4],
 rat:{c:"Vitamin C enhances absorption; dark stools are expected; liquid iron should be taken through a straw; calcium/antacids/tea/chocolate block absorption. Milk with the dose impairs absorption — take between meals with water or juice.",
 o:["Correct — vitamin C converts iron to the better-absorbed form.","Correct — expected, harmless, and worth pre-warning.","Milk (calcium) impairs absorption — separate it.","Correct — prevents staining.","Correct — separates iron from absorption competitors."],
 s:"Iron teaching set: vitamin C in, calcium/tea/antacids out, between-meal dosing, dark stools expected, straw for liquid, count residual capsules in children (overdose risk)."},
 ref:"Hematologic disorders · iron therapy"},

{id:"MOC-013", t:"multi", cn:"MOC", sys:"INF", topic:"Delegation to UAP", d:1, b:-0.3, cj:"generate", tags:["delegation"],
 stem:"The RN is working with an unlicensed assistive personnel (UAP) on a medical unit. Which tasks can be delegated to the UAP? Select all that apply.",
 opts:["Obtain routine vital signs on a stable client","Feed a client who is alert with an intact swallow","Ambulate a stable client to the bathroom","Reinforce teaching about a new diabetic diet","Perform the initial pain assessment on a new admission"],
 ans:[0,1,2],
 rat:{c:"Routine VS, feeding a stable client with an intact swallow, and ambulating a stable client are standard UAP tasks. Teaching and assessment (including initial pain assessment) are RN responsibilities.",
 o:["Correct — routine, standardized task on a stable client.","Correct — safety confirmed (alert, swallow intact).","Correct — stable mobility assistance.","Teaching may not be delegated to UAP.","Assessment is never delegated to UAP."],
 s:"Delegation filter: right task (routine/standardized) + right person (UAP scope) + right circumstance (stable client) + right direction + right supervision. Assessment, teaching, care planning, and evaluation stay with the RN."},
 ref:"Delegation framework"},

{id:"MOC-014", t:"single", cn:"MOC", sys:"INF", topic:"Chain of command", d:2, b:0.6, cj:"act", tags:["safety"],
 stem:"A nurse believes a provider's prescribed dose of a medication is unsafe for the client and the provider dismisses the concern on the phone. Which action should the nurse take next?",
 opts:["Administer the dose as prescribed since the provider insisted","Refuse silently and document nothing","Escalate through the chain of command (charge nurse/nursing supervisor) and document the communications","Ask a colleague to administer the dose instead"],
 ans:2,
 rat:{c:"Patient safety duty: when a nurse reasonably believes an order is unsafe, the concern is escalated up the chain of command until resolved — and each step is documented. Neither blind compliance nor quiet refusal protects the client or the nurse.",
 o:["Compliance against judgment abandons the client if the order is truly unsafe.","Silent refusal is unprofessional, undocumented, and abandons the client.","Correct — escalate + document; most policies allow withholding the dose pending resolution.","Transferring the task to a colleague does not resolve an unsafe order."],
 s:"Unsafe-order playbook: clarify with prescriber → if unresolved, escalate (charge → supervisor → medical chain) → document each step → do not administer until safe. Never “give it anyway.”"},
 ref:"Professional practice · client advocacy"},

{id:"SIC-013", t:"single", cn:"SIC", sys:"INF", topic:"Room assignment", d:1, b:-0.15, cj:"generate", tags:["safety"],
 stem:"The charge nurse must place a client admitted with pertussis (whooping cough). Which room assignment is most appropriate?",
 opts:["A private room at least, with a surgical mask worn by staff within 3–6 feet","A semi-private room with a client on contact precautions for C. difficile","A negative-pressure airborne isolation room","An open bay separated by curtains"],
 ans:0,
 rat:{c:"Pertussis requires DROPLET precautions: private room (preferred), staff in surgical masks within 3–6 feet; negative-pressure rooms are for airborne organisms (TB, measles). Cohorting with a different-precaution client spreads organisms.",
 o:["Correct — droplet precautions: private room + surgical mask.","Mixing precaution types risks cross-transmission.","Negative pressure is airborne-level and unnecessary for droplet spread.","Curtains do not block droplet transmission."],
 s:"Room-assignment questions = match the precaution tier: airborne → AIIR/negative pressure + N95; droplet → private + surgical mask; contact → private/gloves/gown, dedicated equipment."},
 ref:"Transmission-based precautions in practice"},

{id:"PAA-037", t:"cloze", cn:"PAA", sys:"HEME", topic:"Anemia interpretation", d:1, b:-0.2, cj:"analyze", tags:["assessment"],
 stem:"An older adult reports increasing fatigue and dyspnea on exertion. Labs are drawn. Complete the interpretation using the drop-down menus.",
 cloze:{lines:[
  {pre:"A hemoglobin of 7.9 g/dL is", post:"the expected reference range for an adult.", opts:["below","within","above"], ans:0},
  {pre:"A hematocrit of 24% is", post:"the expected reference range.", opts:["below","within","above"], ans:0},
  {pre:"The symptom cluster (fatigue, exertional dyspnea, pallor) is", post:"with the laboratory findings.", opts:["consistent","inconsistent"], ans:0}]},
 rat:{c:"Hgb 7.9 and Hct 24% are well below adult reference ranges (Hgb ♀12–16/♂14–18 g/dL, Hct 37–48%), and the fatigue/dyspnea/pallor cluster is the classic symptomatic-anemia presentation — evaluate cause (iron, B12, bleeding, renal) and tolerance.",
 o:["Marked anemia.","Marked anemia.","Classic matching symptom cluster."],
 s:"Anemia thresholds worth memorizing: Hgb <12 (♀)/<14 (♂); <8 usually triggers transfusion discussion if symptomatic. Symptoms track O2 delivery: fatigue, exertional dyspnea, pallor, tachycardia, orthostasis."},
 ref:"Laboratory interpretation · anemia"},

/* ── Variants (anti-memorization) — same concept, different presentation ── */
{id:"PHA-030", t:"multi", cn:"PHA", sys:"CV", topic:"Digoxin toxicity", d:1, b:-0.2, cj:"recognize", tags:["medication","assessment"], variantGroup:"digoxin-toxicity",
 stem:"An 84-year-old taking digoxin 0.25 mg daily and furosemide reports “no appetite for two days.” Heart rate is 52/min and irregular; potassium 3.1 mEq/L; digoxin level 2.9 ng/mL. Which findings indicate toxicity? Select all that apply.",
 opts:["Anorexia for two days","Heart rate 52/min irregular","Potassium 3.1 mEq/L","Blood pressure 142/78 mm Hg","Digoxin level 2.9 ng/mL"],
 ans:[0,1,2,4],
 rat:{c:"Anorexia, bradycardia with irregularity, hypokalemia (which potentiates toxicity), and a supratherapeutic level (2.9 > 2.0) together form the toxicity picture. BP 142/78 is not a toxicity marker.",
 o:["Classic GI toxicity sign.","Correct — cardiac toxicity.","Correct — amplifier, and itself dangerous.","Not a toxicity marker.","Correct — above the 0.5–2.0 reference range."],
 s:"Same core as any digoxin item: GI + eyes + slow pulse + level, with potassium as the multiplier. Different numbers, different client — the concept is what transfers."},
 ref:"High-alert medication · digoxin toxicity (variant)"},

{id:"PAA-038", t:"single", cn:"PAA", sys:"ENDO", topic:"DKA", d:2, b:0.85, cj:"act", tags:["priority","medication"], variantGroup:"dka",
 stem:"A 24-year-old with type 1 diabetes presents with vomiting, Kussmaul respirations, glucose 486 mg/dL, and ketones in the urine. The provider orders fluids, IV insulin, and potassium. Which order does the nurse implement first?",
 opts:["Begin the IV insulin infusion","Start the prescribed 0.9% sodium chloride infusion","Administer oral potassium","Obtain a chest x-ray"],
 ans:1,
 rat:{c:"As always in DKA, fluid resuscitation precedes insulin — restoring volume first prevents circulatory collapse when insulin shifts fluid/glucose intracellularly. Insulin follows immediately; potassium is added once output is confirmed.",
 o:["Insulin before volume risks vascular collapse.","Correct — fluids first, then insulin.","Oral potassium is inappropriate with vomiting; IV after urine output is confirmed.","Imaging is not the priority in a known DKA presentation."],
 s:"Recognize the same DKA sequence through any wrapper: FLUIDS → insulin → potassium (once voiding) → monitoring. If “fluids” is an option in DKA, it is first."},
 ref:"Endocrine emergencies · DKA (variant)"},

{id:"MOC-015", t:"single", cn:"MOC", sys:"MSK", topic:"Delegation", d:1, b:-0.3, cj:"act", tags:["delegation"], variantGroup:"delegation-uap",
 stem:"Which task is appropriate for the RN to delegate to unlicensed assistive personnel (UAP)?",
 opts:["Measure intake and output for a client with a urinary catheter","Assess a stage 3 pressure injury","Teach colostomy care to a new ostomy client","Develop a mobility plan for a client after stroke"],
 ans:0,
 rat:{c:"Measuring I&O on a catheterized client is routine data collection within the UAP scope. Assessment, teaching, and care planning are RN functions that cannot be delegated.",
 o:["Correct — standardized measurement, stable client, no judgment.","Wound assessment is nursing assessment — RN.","Teaching is RN responsibility.","Care planning is RN responsibility."],
 s:"Any delegation variant reduces to the same test: routine + standardized + stable = UAP; assessment/teaching/planning/evaluation = RN."},
 ref:"Delegation & assignment (variant)"},

{id:"RRP-021", t:"single", cn:"RRP", sys:"RESP", topic:"Postoperative complications", d:2, b:0.8, cj:"act", tags:["priority","assessment"], variantGroup:"pe-postop",
 stem:"On postoperative day 2 after knee arthroplasty, a client suddenly becomes short of breath with a respiratory rate of 32/min, heart rate 122/min, and SpO2 86% on room air. Which action should the nurse take first?",
 opts:["Apply oxygen and call the rapid response team","Assist the client to ambulate to improve circulation","Administer prescribed PRN ibuprofen for pain","Reassure the client and recheck vital signs in 30 minutes"],
 ans:0,
 rat:{c:"Sudden dyspnea + tachycardia + hypoxemia after joint surgery = pulmonary embolism until proven otherwise. Oxygen first (ABC), then rapid escalation while keeping the client calm and still.",
 o:["Correct — O2 immediately, then escalate.","Ambulating a hypoxic client with suspected PE is dangerous.","Analgesia does not address the ABC threat.","Waiting 30 minutes on 86% SpO2 is indefensible."],
 s:"The PE pattern (postop + sudden dyspnea + tachycardia + hypoxemia) always answers “oxygen first.” Recognition transfers; the surgery detail is dressing."},
 ref:"Postoperative complications · pulmonary embolism (variant)"}
);
