"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 42) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 41: MOC (17.9% vs 18),
 * RRP (11.8% vs 12) and PAA (13.8% vs 14). Every item is
 * difficulty 2 or 3, and the clinical detail is written to be
 * defensible.
 *
 * MOC 7: clinical decision support, copy and paste documentation,
 * record keeping, documentation standards, version control, access
 * control, and data breach reporting.
 * RRP 7: permissive hypercapnia, lung protective ventilation,
 * plateau pressure, driving pressure, auto-PEEP, alveolar-arterial
 * gradient, and the Berlin definition of ARDS.
 * PAA 6: refractory hypoxaemia, intra-aortic balloon pump, left
 * ventricular assist device, cardiac transplant, rejection
 * surveillance, and donor specific antibody.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- MOC 7 */
{id:"MOC-209", t:"single", cn:"MOC", sys:"INTG", topic:"Clinical decision support", d:3, b:0.55, cj:"analyze", tags:["management","clinical decision support","informatics","safety","decision-making"],
 stem:"A nurse is prescribing a medication and the electronic health record generates an alert warning of a potential drug interaction. The nurse believes the alert is not clinically relevant. Which action by the nurse is most appropriate?",
 opts:["Review the alert, consider the clinical context, and override only with a documented rationale","Override the alert without review, since alerts are often inaccurate","Ignore the alert, since clinical judgement takes priority","Contact the pharmacist before proceeding, since this is required for all alerts"],
 ans:0, rat:{c:"Clinical decision support alerts should be reviewed and considered in clinical context. Overriding requires a documented rationale. Overriding without review, ignoring alerts, or contacting pharmacy for all alerts are not appropriate approaches.", s:"Understanding clinical decision support is essential for safe prescribing; the nurse must balance alerts with clinical judgement and document overrides."}},
{id:"MOC-210", t:"single", cn:"MOC", sys:"INTG", topic:"Copy and paste documentation", d:3, b:0.55, cj:"analyze", tags:["management","copy and paste","documentation","accuracy","risk"],
 stem:"A nurse copies documentation from the previous shift into the current entry without updating it. Which interpretation by the nurse is most accurate?",
 opts:["Copy and paste can introduce inaccuracies and outdated information and should be used with caution and verification","Copy and paste is an efficient way to document and reduces errors","Copy and paste is prohibited and should never be used","Copy and paste is acceptable as long as the nurse signs the entry"],
 ans:0, rat:{c:"Copy and paste can introduce inaccuracies and outdated information and should be used with caution and verification. It is not inherently efficient or error-reducing, is not prohibited, and signing does not address accuracy concerns.", s:"Understanding the risks of copy and paste is essential for accurate documentation; the nurse must verify copied information."}},
{id:"MOC-211", t:"single", cn:"MOC", sys:"INTG", topic:"Record keeping", d:2, b:0.45, cj:"act", tags:["management","record keeping","documentation","legal","professional"],
 stem:"A nurse realises they have made an error in a client's record. Which action by the nurse is most appropriate?",
 opts:["Make a late entry or amendment following organisational policy, clearly identifying the correction and reason","Delete the incorrect entry and rewrite it","Write over the incorrect entry so it cannot be read","Leave the error, since correcting it may draw attention to it"],
 ans:0, rat:{c:"Errors in records should be corrected by late entry or amendment following organisational policy, clearly identifying the correction and reason. Deleting, writing over, or leaving errors all breach record keeping standards and legal requirements.", s:"Understanding record keeping standards is essential for legal and professional accountability; the nurse must know how to correct errors properly."}},
{id:"MOC-212", t:"single", cn:"MOC", sys:"INTG", topic:"Documentation standards", d:2, b:0.45, cj:"analyze", tags:["management","documentation standards","quality","accuracy","professional"],
 stem:"A nurse is asked to explain documentation standards to a student nurse. Which explanation by the nurse is most accurate?",
 opts:["Documentation should be accurate, contemporaneous, factual, and legible, following organisational policy","Documentation should be brief but accurate, and only include essential information","Documentation should be written at the end of the shift to ensure accuracy","Documentation standards vary between organisations and are not legally binding"],
 ans:0, rat:{c:"Documentation should be accurate, contemporaneous, factual, and legible, following organisational policy. Brief documentation may omit essential information. Writing at the end of shift is not contemporaneous. Documentation standards are legally binding.", s:"Understanding documentation standards is essential for legal and professional accountability."}},
{id:"MOC-213", t:"single", cn:"MOC", sys:"INTG", topic:"Version control", d:2, b:0.45, cj:"analyze", tags:["management","version control","documentation","audit trail","accuracy"],
 stem:"A client's care plan has been revised several times. The clinical team needs to identify which version was in use at a specific time. Which interpretation by the nurse is most accurate?",
 opts:["Version control allows tracking of changes over time and identification of the version in use at a specific point","Version control is not important, since the most recent version is always correct for any specific situation","Version control is only relevant to IT systems and not to clinical care","Version control means keeping multiple paper copies of the care plan"],
 ans:0, rat:{c:"Version control allows tracking of changes over time and identification of the version in use at a specific point. It is important for clinical care and audit, not just IT, and is not simply keeping paper copies.", s:"Understanding version control is essential for accurate record keeping and audit."}},
{id:"MOC-214", t:"single", cn:"MOC", sys:"INTG", topic:"Access control", d:3, b:0.55, cj:"act", tags:["management","access control","information governance","confidentiality","security"],
 stem:"A nurse's colleague asks to use the nurse's login credentials to access the electronic health record because they have forgotten their own password. Which action by the nurse is most appropriate?",
 opts:["Refuse to share credentials and advise the colleague to contact IT for password reset","Share the credentials, since this is a one-off situation","Share the credentials but ask the colleague to change them back afterwards","Log in on the colleague's behalf, since this avoids sharing the password"],
 ans:0, rat:{c:"Login credentials should never be shared, as this breaches access control and accountability. The colleague should contact IT for password reset. Sharing credentials or logging in on their behalf both breach security requirements.", s:"Understanding access control is essential for information governance; the nurse must never share credentials."}},
{id:"MOC-215", t:"single", cn:"MOC", sys:"INTG", topic:"Data breach reporting", d:3, b:0.55, cj:"act", tags:["management","data breach","reporting","GDPR","information governance"],
 stem:"A nurse discovers that a client's medical record has been emailed to the wrong recipient. Which action by the nurse is most appropriate?",
 opts:["Report the breach immediately to the information governance lead, since this may be a reportable data breach","Contact the recipient and ask them to delete the email, since this resolves the issue","Do not report the breach, since no harm has occurred","Wait to see if the recipient responds before taking action"],
 ans:0, rat:{c:"A data breach should be reported immediately to the information governance lead, as it may be reportable under GDPR. Contacting the recipient, not reporting, or waiting all fail to meet legal requirements.", s:"Understanding data breach reporting is essential for GDPR compliance; the nurse must report breaches immediately."}},

/* ---------------------------------------------------------- RRP 7 */
{id:"RRP-146", t:"single", cn:"RRP", sys:"RESP", topic:"Permissive hypercapnia", d:3, b:0.55, cj:"analyze", tags:["risk","permissive hypercapnia","ventilation","ARDS","lung protective"],
 stem:"A client with acute respiratory distress syndrome is ventilated with low tidal volumes. The arterial blood gas shows a pH of 7.28 and PaCO2 of 62 mmHg. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with permissive hypercapnia, which is accepted to achieve lung protective ventilation","This indicates ventilator failure and requires immediate intervention","This indicates the client is deteriorating and requires increased tidal volumes","This is not an acceptable blood gas and requires correction"],
 ans:0, rat:{c:"Permissive hypercapnia is accepted in lung protective ventilation for ARDS to minimise ventilator-induced lung injury. It does not indicate ventilator failure or deterioration, and increasing tidal volumes would be harmful.", s:"Understanding permissive hypercapnia is essential for managing ARDS; the nurse must recognise that mild acidosis is accepted."}},
{id:"RRP-147", t:"single", cn:"RRP", sys:"RESP", topic:"Lung protective ventilation", d:3, b:0.55, cj:"act", tags:["risk","lung protective","ventilation","ARDS","tidal volume"],
 stem:"A client with acute respiratory distress syndrome requires mechanical ventilation. Which action by the nurse is most appropriate?",
 opts:["Advocate for low tidal volume ventilation of 6 mL/kg predicted body weight to minimise ventilator-induced lung injury","Advocate for high tidal volume ventilation of 10-12 mL/kg to improve oxygenation","Advocate for pressure control ventilation, since this is always superior","Advocate for spontaneous ventilation, since this avoids ventilator-induced lung injury"],
 ans:0, rat:{c:"Lung protective ventilation with low tidal volumes of 6 mL/kg predicted body weight minimises ventilator-induced lung injury in ARDS. High tidal volumes are harmful. Pressure control is not always superior. Spontaneous ventilation may not be possible in severe ARDS.", s:"Understanding lung protective ventilation is essential for managing ARDS; the nurse must advocate for appropriate tidal volumes."}},
{id:"RRP-148", t:"single", cn:"RRP", sys:"RESP", topic:"Plateau pressure", d:3, b:0.55, cj:"analyze", tags:["risk","plateau pressure","ventilation","ARDS","safety"],
 stem:"A client with acute respiratory distress syndrome has a plateau pressure of 34 cmH2O. Which interpretation by the nurse is most accurate?",
 opts:["The plateau pressure is above the recommended target of 30 cmH2O and requires intervention to reduce it","The plateau pressure of 34 cmH2O is within the acceptable range and requires no action","The plateau pressure is not relevant to lung protective ventilation","The plateau pressure should be increased to improve oxygenation"],
 ans:0, rat:{c:"Plateau pressure should be maintained below 30 cmH2O to minimise ventilator-induced lung injury. A pressure of 34 cmH2O is above target and requires intervention. It is highly relevant to lung protective ventilation and should not be increased.", s:"Understanding plateau pressure is essential for safe mechanical ventilation in ARDS."}},
{id:"RRP-149", t:"single", cn:"RRP", sys:"RESP", topic:"Driving pressure", d:3, b:0.55, cj:"analyze", tags:["risk","driving pressure","ventilation","ARDS","lung mechanics"],
 stem:"A client with acute respiratory distress syndrome has a plateau pressure of 28 cmH2O and PEEP of 10 cmH2O. Which interpretation by the nurse is most accurate?",
 opts:["The driving pressure is 18 cmH2O, which is above the recommended target of 15 cmH2O and may require adjustment","The driving pressure is 28 cmH2O, which is within the acceptable range","The driving pressure is 10 cmH2O, which is below the recommended target","Driving pressure is not a relevant parameter in ARDS management"],
 ans:0, rat:{c:"Driving pressure is calculated as plateau pressure minus PEEP, which is 28 - 10 = 18 cmH2O. This is above the recommended target of 15 cmH2O and may require adjustment. Driving pressure is highly relevant to ARDS management.", s:"Understanding driving pressure is essential for optimising mechanical ventilation in ARDS."}},
{id:"RRP-150", t:"single", cn:"RRP", sys:"RESP", topic:"Auto-PEEP", d:3, b:0.55, cj:"analyze", tags:["risk","auto-PEEP","ventilation","air trapping","COPD"],
 stem:"A client with chronic obstructive pulmonary disease is mechanically ventilated. The ventilator waveform does not return to baseline before the next breath. Which interpretation by the nurse is most accurate?",
 opts:["This suggests auto-PEEP and air trapping, which may require increased expiratory time or reduced respiratory rate","This suggests the client is triggering the ventilator and requires increased support","This suggests ventilator malfunction and requires immediate intervention","This is a normal waveform finding and requires no action"],
 ans:0, rat:{c:"A waveform that does not return to baseline before the next breath suggests auto-PEEP and air trapping. This may require increased expiratory time or reduced respiratory rate. It is not normal ventilator triggering, malfunction, or a normal finding.", s:"Understanding auto-PEEP is essential for managing mechanically ventilated clients with obstructive lung disease."}},
{id:"RRP-151", t:"single", cn:"RRP", sys:"RESP", topic:"Alveolar-arterial gradient", d:3, b:0.55, cj:"analyze", tags:["risk","A-a gradient","oxygenation","assessment","respiratory"],
 stem:"A client has a PaO2 of 65 mmHg on room air. The calculated alveolar-arterial gradient is 35 mmHg. Which interpretation by the nurse is most accurate?",
 opts:["The elevated A-a gradient suggests a gas exchange abnormality such as shunt or V/Q mismatch","The elevated A-a gradient suggests hypoventilation as the cause of hypoxaemia","The A-a gradient is within normal limits and requires no further investigation","The A-a gradient is not a useful parameter in assessing oxygenation"],
 ans:0, rat:{c:"An elevated A-a gradient suggests a gas exchange abnormality such as shunt or V/Q mismatch. Hypoventilation causes hypoxaemia with a normal A-a gradient. A gradient of 35 mmHg is elevated and requires investigation.", s:"Understanding the A-a gradient is essential for differentiating causes of hypoxaemia."}},
{id:"RRP-152", t:"single", cn:"RRP", sys:"RESP", topic:"Berlin definition of ARDS", d:3, b:0.55, cj:"analyze", tags:["risk","Berlin definition","ARDS","diagnosis","criteria"],
 stem:"A client presents with acute onset bilateral infiltrates on chest X-ray, PaO2/FiO2 ratio of 180, and no evidence of heart failure. Which interpretation by the nurse is most accurate?",
 opts:["This meets the Berlin definition of moderate ARDS, since the PaO2/FiO2 ratio is between 100 and 200","This meets the Berlin definition of mild ARDS, since a ratio of 180 indicates only mild impairment","This meets the Berlin definition of severe ARDS, since the PaO2/FiO2 ratio is below 200","This does not meet the Berlin definition, since additional criteria are required"],
 ans:0, rat:{c:"The Berlin definition classifies ARDS by PaO2/FiO2 ratio: mild (200-300), moderate (100-200), and severe (<100). A ratio of 180 meets criteria for moderate ARDS. The client meets all Berlin criteria including acute onset, bilateral infiltrates, and no heart failure.", s:"Understanding the Berlin definition is essential for diagnosing and classifying ARDS."}},

/* ---------------------------------------------------------- PAA 6 */
{id:"PAA-161", t:"single", cn:"PAA", sys:"RESP", topic:"Refractory hypoxaemia", d:3, b:0.55, cj:"act", tags:["adaptation","refractory hypoxaemia","ARDS","prone positioning","ECMO"],
 stem:"A client with severe ARDS has a PaO2/FiO2 ratio of 80 despite optimised ventilator settings and high PEEP. Which action by the nurse is most appropriate?",
 opts:["Advocate for prone positioning or referral for ECMO assessment, since these are indicated for refractory hypoxaemia","Continue current management, since further intervention is unlikely to help","Increase FiO2 to 100%, since this will improve oxygenation","Administer neuromuscular blockade, since this is the only remaining option"],
 ans:0, rat:{c:"Refractory hypoxaemia in severe ARDS may require prone positioning or ECMO. Continuing current management, increasing FiO2 alone, or neuromuscular blockade alone are not sufficient for refractory hypoxaemia.", s:"Understanding refractory hypoxaemia is essential for managing severe ARDS; the nurse must advocate for advanced therapies."}},
{id:"PAA-162", t:"single", cn:"PAA", sys:"CV", topic:"Intra-aortic balloon pump", d:3, b:0.55, cj:"analyze", tags:["adaptation","IABP","counterpulsation","cardiogenic shock","mechanical support"],
 stem:"A client in cardiogenic shock has an intra-aortic balloon pump inserted. The client asks how the device works. Which explanation by the nurse is most accurate?",
 opts:["The balloon inflates during diastole to improve coronary perfusion and deflates before systole to reduce afterload","The balloon inflates during systole to increase cardiac output and deflates during diastole","The balloon provides continuous inflation to support the aorta","The balloon pumps blood directly from the left ventricle to the aorta"],
 ans:0, rat:{c:"The intra-aortic balloon pump inflates during diastole to improve coronary perfusion and deflates before systole to reduce afterload. It does not inflate during systole, provide continuous inflation, or pump blood directly.", s:"Understanding IABP function is essential for managing clients with cardiogenic shock."}},
{id:"PAA-163", t:"single", cn:"PAA", sys:"CV", topic:"Left ventricular assist device", d:3, b:0.55, cj:"act", tags:["adaptation","LVAD","mechanical support","heart failure","monitoring"],
 stem:"A client with a left ventricular assist device presents to the emergency department. The device alarm is sounding. Which action by the nurse is the priority?",
 opts:["Assess the client's haemodynamic status and check the device for malfunction, since device failure is life-threatening","Silence the alarm and document the event","Contact the client's specialist centre and await advice","Administer oxygen, since this is the standard response to device alarms"],
 ans:0, rat:{c:"A sounding LVAD alarm requires immediate assessment of the client's haemodynamic status and device function, since device failure is life-threatening. Silencing the alarm, contacting the centre without assessment, or administering oxygen alone all delay critical assessment.", s:"Understanding LVAD alarms is essential for managing clients with mechanical circulatory support."}},
{id:"PAA-164", t:"single", cn:"PAA", sys:"CV", topic:"Cardiac transplant", d:3, b:0.55, cj:"act", tags:["adaptation","cardiac transplant","immunosuppression","rejection","monitoring"],
 stem:"A client six months post cardiac transplant presents with fatigue, low-grade fever, and reduced exercise tolerance. Which action by the nurse is the priority?",
 opts:["Suspect acute rejection and arrange urgent assessment including echocardiography and possible biopsy","Advise rest and paracetamol, since these symptoms are common post-transplant","Increase immunosuppression empirically, since rejection is the most likely cause","Reassure the client, since these symptoms are expected at six months"],
 ans:0, rat:{c:"Fatigue, fever, and reduced exercise tolerance in a cardiac transplant recipient may indicate acute rejection and require urgent assessment. Advising rest, increasing immunosuppression empirically, or reassuring the client all delay diagnosis and treatment.", s:"Understanding rejection surveillance is essential for managing cardiac transplant recipients."}},
{id:"PAA-165", t:"single", cn:"PAA", sys:"CV", topic:"Rejection surveillance", d:3, b:0.55, cj:"act", tags:["adaptation","rejection surveillance","cardiac transplant","biopsy","monitoring"],
 stem:"A cardiac transplant recipient is scheduled for routine surveillance endomyocardial biopsy. The client asks why this is necessary when they feel well. Which response by the nurse is most appropriate?",
 opts:["Explain that surveillance biopsy detects early rejection before symptoms develop, allowing prompt treatment","Explain that surveillance biopsy is only needed if symptoms develop","Explain that the biopsy is a routine procedure with no specific purpose","Explain that the biopsy will confirm the transplant is working"],
 ans:0, rat:{c:"Surveillance endomyocardial biopsy detects early rejection before symptoms develop, allowing prompt treatment. It is not only needed if symptoms develop, is not without purpose, and does not simply confirm the transplant is working.", s:"Understanding rejection surveillance is essential for managing cardiac transplant recipients."}},
{id:"PAA-166", t:"single", cn:"PAA", sys:"CV", topic:"Donor specific antibody", d:3, b:0.55, cj:"analyze", tags:["adaptation","donor specific antibody","transplant","rejection","immunology"],
 stem:"A renal transplant recipient develops rising creatinine and is found to have donor specific antibodies. Which interpretation by the nurse is most accurate?",
 opts:["Donor specific antibodies suggest antibody-mediated rejection and require treatment","Donor specific antibodies are a normal finding and require no action","Donor specific antibodies suggest infection rather than rejection","Donor specific antibodies are only relevant before transplant, not after"],
 ans:0, rat:{c:"Donor specific antibodies after transplant suggest antibody-mediated rejection and require treatment. They are not a normal finding, do not suggest infection, and are relevant both before and after transplant.", s:"Understanding donor specific antibodies is essential for managing transplant rejection."}}

]);
