"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 37) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 36: PHA (15.8% vs 16),
 * RRP (11.8% vs 12) and PAA (13.8% vs 14). Every item is
 * difficulty 2 or 3, and the clinical detail is written to be
 * defensible.
 *
 * PHA 8: vancomycin trough monitoring, peak and trough levels,
 * loading dose versus maintenance dose, steady state, first-pass
 * metabolism, protein binding, CYP450 enzyme inducers, and
 * St John's wort interactions.
 * RRP 6: central venous pressure monitoring, mixed venous oxygen
 * saturation, lactate clearance in sepsis, base deficit, fractional
 * excretion of sodium, and creatinine clearance.
 * PAA 6: osmolar gap in toxic alcohol ingestion, delta ratio in
 * mixed acid-base disorders, urine osmolality in SIADH, estimated
 * GFR versus creatinine clearance, cystatin C as a renal marker,
 * and hepatic dosing in liver disease.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- PHA 8 */
{id:"PHA-176", t:"single", cn:"PHA", sys:"INF", topic:"Vancomycin trough monitoring", d:3, b:0.55, cj:"act", tags:["pharmacology","vancomycin","trough","therapeutic monitoring","antibiotic"],
 stem:"A client is receiving intravenous vancomycin for methicillin-resistant Staphylococcus aureus bacteraemia. The prescription requires a trough level to be drawn. When should the nurse draw the trough level?",
 opts:["Immediately before the next dose, since this reflects the lowest concentration and guides dosing","One hour after the infusion ends, since this reflects the peak concentration","Midway through the infusion, since this reflects the average concentration","At any time during the dosing interval, since the timing does not affect the result"],
 ans:0, rat:{c:"A trough level is drawn immediately before the next dose, when the drug concentration is at its lowest. This guides dosing to ensure the concentration remains above the minimum inhibitory concentration without causing toxicity. Drawing at other times does not reflect the trough and will lead to incorrect dosing decisions.", s:"Trough monitoring is essential for vancomycin; the nurse must understand the timing and its purpose to ensure therapeutic efficacy and safety."}},
{id:"PHA-177", t:"single", cn:"PHA", sys:"INF", topic:"Peak and trough levels", d:2, b:0.45, cj:"analyze", tags:["pharmacology","peak","trough","therapeutic monitoring","aminoglycoside"],
 stem:"A client is receiving gentamicin. The clinical team requests both peak and trough levels. Which interpretation by the nurse is most accurate?",
 opts:["The peak level reflects efficacy and the trough level reflects toxicity risk, so both are needed to guide dosing","Only the peak level is needed, since it reflects both efficacy and toxicity risk","Only the trough level is needed, since the peak level does not provide useful information","Only the peak level is needed, since the trough level does not provide useful information"],
 ans:0, rat:{c:"For aminoglycosides, the peak level correlates with efficacy (bacterial killing) and the trough level correlates with toxicity risk (nephrotoxicity and ototoxicity). Both are needed to guide dosing. Neither level alone provides sufficient information.", s:"Understanding the purpose of peak and trough levels is essential for safe aminoglycoside administration."}},
{id:"PHA-178", t:"single", cn:"PHA", sys:"INTG", topic:"Loading dose versus maintenance dose", d:2, b:0.45, cj:"analyze", tags:["pharmacology","loading dose","maintenance dose","pharmacokinetics"],
 stem:"A client requires digoxin for rate control in atrial fibrillation. The prescription includes a loading dose followed by a lower maintenance dose. Which interpretation by the nurse is most accurate?",
 opts:["The loading dose achieves therapeutic concentration rapidly, and the maintenance dose maintains it","The loading dose prevents toxicity, and the maintenance dose achieves therapeutic concentration","The loading dose is given only if the client is symptomatic, and the maintenance dose is routine","The loading dose and maintenance dose are the same and can be interchanged"],
 ans:0, rat:{c:"A loading dose is a larger initial dose given to achieve therapeutic concentration rapidly, while the maintenance dose is a smaller dose given to maintain that concentration. They serve different purposes and cannot be interchanged.", s:"Understanding loading and maintenance doses is essential for safe administration of drugs with narrow therapeutic indices."}},
{id:"PHA-179", t:"single", cn:"PHA", sys:"INTG", topic:"Steady state", d:2, b:0.45, cj:"analyze", tags:["pharmacology","steady state","pharmacokinetics","half-life"],
 stem:"A client starts a new medication with a half-life of 12 hours. The client asks how long it will take for the drug to reach steady state. Which response by the nurse is most appropriate?",
 opts:["Approximately two to three days, since steady state is reached after four to five half-lives","Approximately twelve hours, since this is the half-life","Approximately one week, since steady state takes this long for all drugs","Steady state is reached immediately after the first dose"],
 ans:0, rat:{c:"Steady state is reached after approximately four to five half-lives. For a drug with a 12-hour half-life, this is approximately 48 to 60 hours, or two to three days. The time to steady state depends on the half-life, not on a fixed duration for all drugs.", s:"Understanding steady state and its relationship to half-life is essential for predicting when a drug will reach therapeutic concentration."}},
{id:"PHA-180", t:"single", cn:"PHA", sys:"GI", topic:"First-pass metabolism", d:3, b:0.55, cj:"analyze", tags:["pharmacology","first-pass metabolism","bioavailability","hepatic","oral"],
 stem:"A client is prescribed a drug with high first-pass metabolism. The client asks why the oral dose is much higher than the intravenous dose. Which response by the nurse is most appropriate?",
 opts:["Explain that first-pass metabolism in the liver reduces the amount of drug reaching systemic circulation, so a higher oral dose is needed","Explain that first-pass metabolism in the gut wall reduces absorption, so a higher oral dose is needed","Explain that the oral dose is higher because the drug is less potent when given orally","Explain that the doses should be the same and the prescription may be incorrect"],
 ans:0, rat:{c:"First-pass metabolism occurs when a drug absorbed from the gut passes through the liver before reaching systemic circulation, where a significant proportion may be metabolised. This reduces bioavailability, so a higher oral dose is needed to achieve the same systemic concentration as an intravenous dose.", s:"First-pass metabolism explains why oral doses are often higher than intravenous doses for certain drugs."}},
{id:"PHA-181", t:"single", cn:"PHA", sys:"INTG", topic:"Protein binding", d:3, b:0.55, cj:"analyze", tags:["pharmacology","protein binding","drug interaction","hypoalbuminaemia"],
 stem:"A client with hypoalbuminaemia is receiving warfarin, which is highly protein-bound. Which interpretation by the nurse is most accurate?",
 opts:["The client is at increased risk of bleeding, since less warfarin is bound to albumin and more is free and active","The client is at decreased risk of bleeding, since less warfarin is available to exert its effect","The client's risk is unchanged, since protein binding does not affect drug activity","The client requires a higher dose of warfarin, since less drug is available"],
 ans:0, rat:{c:"Warfarin is highly protein-bound. In hypoalbuminaemia, less warfarin is bound to albumin, so more is free and pharmacologically active. This increases the risk of bleeding. The client may require a lower dose, not a higher dose.", s:"Protein binding affects the free (active) fraction of a drug; hypoalbuminaemia increases the risk of toxicity for highly protein-bound drugs."}},
{id:"PHA-182", t:"single", cn:"PHA", sys:"INTG", topic:"CYP450 enzyme inducers", d:3, b:0.55, cj:"analyze", tags:["pharmacology","CYP450","enzyme inducer","drug interaction","metabolism"],
 stem:"A client taking warfarin starts carbamazepine, which is a CYP450 enzyme inducer. Which interpretation by the nurse is most accurate?",
 opts:["The client's international normalised ratio may fall, since carbamazepine increases warfarin metabolism","The client's bleeding risk may increase, since carbamazepine enhances warfarin's anticoagulant effect","The client's international normalised ratio will not change, since carbamazepine does not interact with warfarin","The client requires a lower dose of warfarin, since carbamazepine enhances its effect"],
 ans:0, rat:{c:"Carbamazepine is a CYP450 enzyme inducer, which increases the metabolism of warfarin. This reduces warfarin concentration and effect, causing the international normalised ratio to fall. The client may require a higher dose of warfarin, not a lower dose.", s:"Enzyme inducers increase drug metabolism and reduce drug effect; the nurse must monitor for reduced efficacy and adjust dosing accordingly."}},
{id:"PHA-183", t:"single", cn:"PHA", sys:"PSYCH", topic:"St John's wort interactions", d:2, b:0.45, cj:"analyze", tags:["pharmacology","St John's wort","drug interaction","herbal","CYP450"],
 stem:"A client taking an oral contraceptive asks about taking St John's wort for low mood. Which response by the nurse is most appropriate?",
 opts:["Advise against it, since St John's wort induces CYP450 enzymes and may reduce contraceptive effectiveness","Advise that it is safe with an oral contraceptive, since St John's wort is a natural product","Advise that it is safe, since St John's wort does not interact with oral contraceptives","Advise that it may be taken, but the client should use additional contraception for one week"],
 ans:0, rat:{c:"St John's wort is a potent CYP450 enzyme inducer and can reduce the effectiveness of many drugs, including oral contraceptives. This increases the risk of unintended pregnancy. The client should be advised against taking it.", s:"Herbal products can have significant drug interactions; St John's wort is one of the most important to recognise."}},

/* ---------------------------------------------------------- RRP 6 */
{id:"RRP-135", t:"single", cn:"RRP", sys:"CV", topic:"Central venous pressure monitoring", d:3, b:0.55, cj:"analyze", tags:["risk","central venous pressure","monitoring","haemodynamics","fluid status"],
 stem:"A client in the intensive care unit has a central venous catheter. The central venous pressure reading falls from 8 mmHg to 3 mmHg over two hours. The client's blood pressure has fallen and heart rate has risen. Which interpretation by the nurse is most accurate?",
 opts:["The client is likely hypovolaemic and requires fluid resuscitation","The client is likely fluid overloaded and requires diuresis","The central venous pressure reading is unreliable and should be repeated","The client requires inotropic support, since the central venous pressure is normal"],
 ans:0, rat:{c:"A falling central venous pressure with hypotension and tachycardia suggests hypovolaemia. The client requires fluid resuscitation. A rising central venous pressure would suggest fluid overload. The reading is consistent with the clinical picture and does not need repeating before acting.", s:"Central venous pressure monitoring guides fluid management; the nurse must interpret trends alongside clinical findings."}},
{id:"RRP-136", t:"single", cn:"RRP", sys:"CV", topic:"Mixed venous oxygen saturation", d:3, b:0.55, cj:"analyze", tags:["risk","mixed venous oxygen","monitoring","haemodynamics","tissue perfusion"],
 stem:"A client in septic shock has a mixed venous oxygen saturation of 80% (normal 60-80%). The client's cardiac output is high and systemic vascular resistance is low. Which interpretation by the nurse is most accurate?",
 opts:["The high mixed venous oxygen saturation reflects impaired tissue oxygen extraction, which is characteristic of distributive shock","The high mixed venous oxygen saturation reflects adequate tissue perfusion and the client is improving","The high mixed venous oxygen saturation reflects low oxygen delivery and the client requires more oxygen","The mixed venous oxygen saturation is unreliable in septic shock and should not be used"],
 ans:0, rat:{c:"In distributive shock such as sepsis, tissue oxygen extraction is impaired, so mixed venous oxygen saturation is high despite inadequate tissue perfusion. This is a characteristic finding, not a sign of improvement. The reading is reliable and guides management.", s:"Mixed venous oxygen saturation reflects the balance between oxygen delivery and consumption; high values in distributive shock indicate impaired extraction."}},
{id:"RRP-137", t:"single", cn:"RRP", sys:"INTG", topic:"Lactate clearance in sepsis", d:3, b:0.55, cj:"evaluate", tags:["risk","lactate","sepsis","monitoring","perfusion"],
 stem:"A client with sepsis has an initial lactate of 5.2 mmol/L. After two hours of fluid resuscitation the lactate has fallen to 3.8 mmol/L. Which interpretation by the nurse is most accurate?",
 opts:["Lactate clearance is occurring, which is a positive response to resuscitation, but continued monitoring is required","Lactate clearance is complete and resuscitation can stop, since the lactate has fallen significantly","The lactate has not cleared, since it remains above 2 mmol/L","Lactate clearance is not a useful marker in sepsis"],
 ans:0, rat:{c:"Lactate clearance (a fall in lactate over time) is a positive response to resuscitation and indicates improving tissue perfusion. However, the lactate remains elevated, so continued monitoring and resuscitation are required. Lactate clearance is a well-validated marker in sepsis.", s:"Lactate clearance guides resuscitation in sepsis; the nurse must understand that clearance is a trend, not a single value."}},
{id:"RRP-138", t:"single", cn:"RRP", sys:"RESP", topic:"Base deficit", d:3, b:0.55, cj:"analyze", tags:["risk","base deficit","acid-base","monitoring","trauma"],
 stem:"A trauma client has a base deficit of -8 mEq/L on arterial blood gas analysis. Which interpretation by the nurse is most accurate?",
 opts:["The base deficit indicates significant metabolic acidosis, which may reflect tissue hypoperfusion and requires investigation","The base deficit indicates metabolic alkalosis, which is a compensatory response","The base deficit is within normal limits and requires no action","The base deficit indicates respiratory acidosis, which requires ventilatory support"],
 ans:0, rat:{c:"A base deficit of -8 mEq/L indicates significant metabolic acidosis. In trauma, this often reflects tissue hypoperfusion and anaerobic metabolism. It requires investigation and may indicate ongoing bleeding or shock. A base deficit is not a respiratory parameter.", s:"Base deficit is a sensitive marker of tissue hypoperfusion in trauma; the nurse must recognise its significance and escalate appropriately."}},
{id:"RRP-139", t:"single", cn:"RRP", sys:"REN", topic:"Fractional excretion of sodium", d:3, b:0.55, cj:"analyze", tags:["risk","fractional excretion","sodium","renal","acute kidney injury"],
 stem:"A client with acute kidney injury has a fractional excretion of sodium of 0.8%. Which interpretation by the nurse is most accurate?",
 opts:["This suggests prerenal acute kidney injury, since the kidneys are conserving sodium appropriately","This suggests intrinsic renal acute kidney injury, since the kidneys are unable to conserve sodium","This suggests postrenal acute kidney injury, since obstruction is causing sodium wasting","The fractional excretion of sodium is not useful in differentiating causes of acute kidney injury"],
 ans:0, rat:{c:"A fractional excretion of sodium less than 1% suggests prerenal acute kidney injury, where the kidneys are functioning normally and conserving sodium in response to reduced perfusion. A value greater than 2% suggests intrinsic renal injury where the kidneys cannot conserve sodium.", s:"Fractional excretion of sodium helps differentiate prerenal from intrinsic renal acute kidney injury and guides management."}},
{id:"RRP-140", t:"single", cn:"RRP", sys:"REN", topic:"Creatinine clearance", d:2, b:0.45, cj:"analyze", tags:["risk","creatinine clearance","renal function","monitoring","dosing"],
 stem:"A client requires a drug that is renally excreted. The prescription requires a creatinine clearance calculation before dosing. Which interpretation by the nurse is most accurate?",
 opts:["Creatinine clearance estimates glomerular filtration rate and guides dose adjustment to prevent toxicity","Creatinine clearance measures the amount of creatinine in the blood and indicates dehydration","Creatinine clearance is the same as serum creatinine and provides no additional information","Creatinine clearance is only used in research and is not relevant to clinical dosing"],
 ans:0, rat:{c:"Creatinine clearance estimates glomerular filtration rate and is used to guide dose adjustment for renally excreted drugs. It is calculated from a 24-hour urine collection or estimated from serum creatinine, age, weight, and sex. It provides more information than serum creatinine alone.", s:"Creatinine clearance is essential for safe dosing of renally excreted drugs; the nurse must understand its purpose and interpretation."}},

/* ---------------------------------------------------------- PAA 6 */
{id:"PAA-147", t:"single", cn:"PAA", sys:"INTG", topic:"Osmolar gap in toxic alcohol ingestion", d:3, b:0.55, cj:"analyze", tags:["adaptation","osmolar gap","toxic alcohol","methanol","ethylene glycol"],
 stem:"A client presents with altered consciousness and metabolic acidosis following suspected ingestion of an unknown substance. The measured serum osmolality is 340 mOsm/kg and the calculated osmolality is 290 mOsm/kg. Which interpretation by the nurse is most accurate?",
 opts:["The osmolar gap of 50 mOsm/kg suggests the presence of an unmeasured osmotically active substance such as methanol or ethylene glycol","The osmolar gap is within normal limits and does not suggest the presence of a toxic substance","The osmolar gap suggests dehydration and requires fluid resuscitation","The osmolar gap is not useful in toxic alcohol ingestion"],
 ans:0, rat:{c:"An osmolar gap greater than 10 mOsm/kg suggests the presence of an unmeasured osmotically active substance. In the context of altered consciousness and metabolic acidosis, this raises suspicion of toxic alcohol ingestion such as methanol or ethylene glycol. The gap is not normal and is clinically significant.", s:"Osmolar gap is a key diagnostic tool in suspected toxic alcohol ingestion; the nurse must recognise its significance and escalate urgently."}},
{id:"PAA-148", t:"single", cn:"PAA", sys:"REN", topic:"Delta ratio in mixed acid-base disorders", d:3, b:0.55, cj:"analyze", tags:["adaptation","delta ratio","acid-base","mixed disorder","metabolic acidosis"],
 stem:"A client has a high anion gap metabolic acidosis with a delta ratio of 0.4. Which interpretation by the nurse is most accurate?",
 opts:["The delta ratio suggests a mixed high anion gap metabolic acidosis and normal anion gap metabolic acidosis","A delta ratio of 0.4 is expected in isolated ketoacidosis without other acid-base disturbance","A delta ratio below 0.8 points to a concurrent metabolic alkalosis rather than a normal anion gap acidosis","The delta ratio is not useful in interpreting acid-base disorders"],
 ans:0, rat:{c:"A delta ratio less than 0.8 suggests a mixed high anion gap metabolic acidosis and normal anion gap metabolic acidosis. A ratio of 1 to 2 suggests a pure high anion gap metabolic acidosis, and a ratio greater than 2 suggests a mixed high anion gap metabolic acidosis and metabolic alkalosis.", s:"The delta ratio helps identify mixed acid-base disorders; the nurse must understand its interpretation to guide management."}},
{id:"PAA-149", t:"single", cn:"PAA", sys:"ENDO", topic:"Urine osmolality in SIADH", d:3, b:0.55, cj:"analyze", tags:["adaptation","SIADH","urine osmolality","hyponatraemia","endocrine"],
 stem:"A client has hyponatraemia with a serum sodium of 118 mmol/L. The urine osmolality is 450 mOsm/kg and the client is euvolaemic. Which interpretation by the nurse is most accurate?",
 opts:["These findings are consistent with syndrome of inappropriate antidiuretic hormone secretion, since the urine is inappropriately concentrated","These findings are consistent with primary polydipsia, since the client is drinking excess water","These findings are consistent with dehydration, since the urine is concentrated","Urine osmolality is not useful in diagnosing syndrome of inappropriate antidiuretic hormone secretion"],
 ans:0, rat:{c:"In syndrome of inappropriate antidiuretic hormone secretion, hyponatraemia occurs with inappropriately concentrated urine (urine osmolality greater than 100 mOsm/kg) in a euvolaemic client. Primary polydipsia would show dilute urine. Dehydration would show hypovolaemia.", s:"Urine osmolality is essential for diagnosing syndrome of inappropriate antidiuretic hormone secretion; the nurse must understand its interpretation."}},
{id:"PAA-150", t:"single", cn:"PAA", sys:"REN", topic:"Estimated GFR versus creatinine clearance", d:2, b:0.45, cj:"analyze", tags:["adaptation","estimated GFR","creatinine clearance","renal function","assessment"],
 stem:"A client's estimated glomerular filtration rate is 45 mL/min/1.73m². The clinical team is considering whether to perform a formal creatinine clearance measurement. Which interpretation by the nurse is most accurate?",
 opts:["Estimated GFR is usually sufficient, but formal creatinine clearance may be needed if the estimate is unreliable or precise dosing is required","Estimated GFR is always more accurate than creatinine clearance and formal measurement is never needed","Creatinine clearance is obsolete and estimated GFR should always be used","Formal creatinine clearance is required for all clients with reduced estimated GFR"],
 ans:0, rat:{c:"Estimated GFR is usually sufficient for clinical decision-making, but formal creatinine clearance may be needed if the estimate is unreliable (for example, in extreme body habitus or muscle mass) or if precise dosing is required for a narrow therapeutic index drug.", s:"Understanding when estimated GFR is sufficient versus when formal measurement is needed is essential for safe renal dosing."}},
{id:"PAA-151", t:"single", cn:"PAA", sys:"REN", topic:"Cystatin C as a renal marker", d:3, b:0.55, cj:"analyze", tags:["adaptation","cystatin C","renal function","marker","assessment"],
 stem:"A client has a normal serum creatinine but the clinical team suspects early renal impairment. They request a cystatin C level. Which interpretation by the nurse is most accurate?",
 opts:["Cystatin C is a more sensitive marker of early renal impairment than creatinine, since it is less affected by muscle mass","Cystatin C is less sensitive than creatinine for detecting early impairment and is used only for research","Cystatin C and creatinine provide the same information and either can be used","Cystatin C is used to diagnose liver disease, not renal impairment"],
 ans:0, rat:{c:"Cystatin C is a more sensitive marker of early renal impairment than creatinine, since it is produced at a constant rate by all nucleated cells and is less affected by muscle mass, age, and sex. It is particularly useful when creatinine may be unreliable.", s:"Cystatin C is increasingly used to detect early renal impairment; the nurse must understand its advantages over creatinine."}},
{id:"PAA-152", t:"single", cn:"PAA", sys:"GI", topic:"Hepatic dosing in liver disease", d:3, b:0.55, cj:"act", tags:["adaptation","hepatic dosing","liver disease","pharmacokinetics","drug metabolism"],
 stem:"A client with Child-Pugh class C cirrhosis requires a drug that is extensively metabolised by the liver. Which action by the nurse is most appropriate?",
 opts:["Anticipate a reduced dose or extended dosing interval, since hepatic metabolism is impaired and drug accumulation may occur","Administer the standard dose, since the drug is metabolised by the liver and this is not affected by cirrhosis","Administer a higher dose, since the liver is less efficient and more drug is needed","Withhold the drug entirely, since all drugs are contraindicated in liver disease"],
 ans:0, rat:{c:"In severe liver disease, hepatic metabolism is impaired, so drugs that are extensively metabolised by the liver may accumulate and cause toxicity. A reduced dose or extended dosing interval is usually required. Not all drugs are contraindicated, but dose adjustment is essential.", s:"Hepatic dosing is essential for safe drug administration in liver disease; the nurse must anticipate dose adjustments and monitor for toxicity."}}

]);
