"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 40) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 39: PSY (8.9% vs 9),
 * BCC (8.9% vs 9), RRP (11.7% vs 12) and PAA (13.9% vs 14).
 * Every item is difficulty 2 or 3, and the clinical detail is
 * written to be defensible.
 *
 * PSY 5: mourning and cultural practices, terminal care, anticipatory
 * grief, complicated grief, and spiritual distress.
 * BCC 6: incident pain, background pain, nociceptive pain, visceral
 * pain, somatic pain, and referred pain.
 * RRP 5: PICC line care, tunnelled catheter care, catheter occlusion,
 * catheter migration, and catheter bundle compliance.
 * PAA 4: allodynia, hyperalgesia, central sensitisation, and wind-up
 * phenomenon.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- PSY 5 */
{id:"PSY-097", t:"single", cn:"PSY", sys:"PSYCH", topic:"Mourning and cultural practices", d:2, b:0.45, cj:"act", tags:["psych","mourning","grief","cultural competence","bereavement"],
 stem:"A client from a cultural background that requires specific mourning rituals has experienced a bereavement. The client's family requests time and space to perform these rituals. Which action by the nurse is most appropriate?",
 opts:["Accommodate the rituals as far as possible, since cultural practices support the mourning process","Explain that hospital policy does not permit mourning rituals","Offer a standard bereavement service instead of cultural rituals, since this is more appropriate","Ask the family to perform the rituals at home, since the hospital is not suitable"],
 ans:0, rat:{c:"Cultural mourning rituals should be accommodated as far as possible, since they support the mourning process and are important to the client and family. Hospital policy should be flexible, and offering a standard service or asking the family to go home fails to respect cultural needs.", s:"Cultural competence in bereavement care requires understanding and accommodating diverse mourning practices."}},
{id:"PSY-098", t:"single", cn:"PSY", sys:"PSYCH", topic:"Terminal care", d:3, b:0.55, cj:"act", tags:["psych","terminal care","palliative","end of life","symptom control"],
 stem:"A client with advanced cancer is receiving terminal care. The client's pain is controlled, but they are experiencing increasing breathlessness and agitation. Which action by the nurse is most appropriate?",
 opts:["Assess and manage the breathlessness and agitation, since symptom control is the priority in terminal care","Increase the opioid dose to reduce terminal agitation, since this will sedate the client","Withhold treatment, since the client is dying and interventions are futile","Transfer the client to intensive care, since breathlessness requires urgent intervention"],
 ans:0, rat:{c:"Terminal care focuses on symptom control and comfort. Breathlessness and agitation should be assessed and managed appropriately. Increasing opioids solely for sedation, withholding treatment, or transferring to intensive care all fail to address the client's needs in terminal care.", s:"Terminal care requires skilled symptom management; the nurse must understand the goals of care and appropriate interventions."}},
{id:"PSY-099", t:"single", cn:"PSY", sys:"PSYCH", topic:"Anticipatory grief", d:3, b:0.55, cj:"analyze", tags:["psych","anticipatory grief","grief","loss","palliative"],
 stem:"A client with a terminal diagnosis is experiencing sadness, anger, and withdrawal before death occurs. The family is concerned that the client is giving up. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with anticipatory grief, which is a normal response to impending loss","This is consistent with clinical depression and requires antidepressant treatment","This is consistent with giving up and the client has stopped fighting","This is not a normal response and requires psychiatric referral"],
 ans:0, rat:{c:"Anticipatory grief is a normal response to impending loss and may include sadness, anger, and withdrawal. It is not clinical depression, giving up, or abnormal. Understanding anticipatory grief allows the nurse to provide appropriate support to the client and family.", s:"Anticipatory grief is a normal process; the nurse must be able to distinguish it from depression and provide appropriate support."}},
{id:"PSY-100", t:"single", cn:"PSY", sys:"PSYCH", topic:"Complicated grief", d:3, b:0.55, cj:"analyze", tags:["psych","complicated grief","grief","bereavement","prolonged"],
 stem:"A client has experienced a bereavement 18 months ago. The client continues to experience intense yearning, difficulty accepting the death, and inability to resume normal activities. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with complicated grief and requires specialist referral","This is consistent with normal grief, since everyone grieves at their own pace","This is consistent with clinical depression and requires antidepressant treatment","This is not a recognised condition and requires no intervention"],
 ans:0, rat:{c:"Complicated grief is characterised by prolonged, intense grief that impairs functioning beyond the expected timeframe. It requires specialist referral. Normal grief does not typically impair functioning at 18 months. While depression may coexist, the presentation is consistent with complicated grief.", s:"Complicated grief is a recognised condition requiring specialist intervention; the nurse must be able to identify it and refer appropriately."}},
{id:"PSY-101", t:"single", cn:"PSY", sys:"PSYCH", topic:"Spiritual distress", d:2, b:0.45, cj:"act", tags:["psych","spiritual distress","spiritual care","holistic","support"],
 stem:"A client with a terminal diagnosis expresses anger at God and questions why this is happening to them. The client appears distressed and asks the nurse to pray with them. Which action by the nurse is most appropriate?",
 opts:["Acknowledge the client's distress, offer to pray if comfortable, and consider referral to a chaplain","Explain that the nurse is not qualified to provide spiritual care","Change the subject, since spiritual discussions are not appropriate in nursing","Tell the client that their anger is normal and will pass"],
 ans:0, rat:{c:"Spiritual distress should be acknowledged, and the nurse should offer support within their competence, including prayer if comfortable and referral to a chaplain. Explaining lack of qualification, changing the subject, or dismissing the anger all fail to address the client's spiritual needs.", s:"Spiritual care is a component of holistic nursing; the nurse must understand their role and when to refer to a chaplain."}},

/* ---------------------------------------------------------- BCC 6 */
{id:"BCC-103", t:"single", cn:"BCC", sys:"INTG", topic:"Incident pain", d:3, b:0.55, cj:"act", tags:["basic care","incident pain","pain management","breakthrough","opioid"],
 stem:"A client with cancer pain controlled by regular morphine experiences severe pain on movement. Which action by the nurse is most appropriate?",
 opts:["Administer breakthrough opioid analgesia before movement, since this is incident pain requiring anticipatory dosing","Increase the regular morphine dose, since this will control the pain","Advise the client to avoid movement, since this will prevent pain","Administer a non-opioid analgesic, since this is not severe pain"],
 ans:0, rat:{c:"Incident pain is breakthrough pain triggered by movement or activity and requires anticipatory breakthrough opioid dosing before the triggering activity. Increasing regular morphine, avoiding movement, or using non-opioids all fail to address incident pain appropriately.", s:"Incident pain requires anticipatory management; the nurse must understand the difference between background and breakthrough pain."}},
{id:"BCC-104", t:"single", cn:"BCC", sys:"INTG", topic:"Background pain", d:2, b:0.45, cj:"act", tags:["basic care","background pain","pain management","regular analgesia","opioid"],
 stem:"A client with chronic cancer pain requires ongoing pain control. The pain is constant but manageable. Which action by the nurse is most appropriate?",
 opts:["Administer regular opioid analgesia at prescribed intervals, since this controls background pain","Administer opioid analgesia only when the client requests it, since this reduces opioid exposure","Administer non-opioid analgesia only, since opioids are not indicated for chronic pain","Withhold analgesia, since the client should tolerate the pain"],
 ans:0, rat:{c:"Background pain requires regular opioid analgesia at prescribed intervals to maintain pain control. Administering only on request, using non-opioids only, or withholding analgesia all fail to control background pain appropriately.", s:"Background pain requires regular dosing; the nurse must understand the importance of maintaining analgesia."}},
{id:"BCC-105", t:"single", cn:"BCC", sys:"INTG", topic:"Nociceptive pain", d:2, b:0.45, cj:"analyze", tags:["basic care","nociceptive pain","pain types","assessment","management"],
 stem:"A client presents with pain following a surgical incision. The pain is described as sharp and well-localised. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with nociceptive pain, which arises from tissue damage and responds well to opioid analgesia","This is consistent with neuropathic pain, which requires adjuvant analgesia","This is consistent with psychogenic pain, which requires psychological intervention","This is not a recognised pain type"],
 ans:0, rat:{c:"Nociceptive pain arises from tissue damage and is typically sharp, well-localised, and responds well to opioid analgesia. Neuropathic pain is typically burning or shooting and requires adjuvant analgesia. Psychogenic pain is not the most likely explanation for post-surgical pain.", s:"Understanding pain types is essential for appropriate management; the nurse must be able to distinguish nociceptive from neuropathic pain."}},
{id:"BCC-106", t:"single", cn:"BCC", sys:"GI", topic:"Visceral pain", d:2, b:0.45, cj:"analyze", tags:["basic care","visceral pain","pain types","assessment","abdominal"],
 stem:"A client presents with abdominal pain described as cramping and poorly localised. The client is restless and unable to find a comfortable position. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with visceral pain, which arises from internal organs and is typically poorly localised","This is consistent with somatic pain, which is poorly localised to the abdomen","This is consistent with referred pain, which is felt at a distant site","This is not a recognised pain type"],
 ans:0, rat:{c:"Visceral pain arises from internal organs and is typically cramping, poorly localised, and associated with restlessness. Somatic pain is well-localised. Referred pain is felt at a distant site from the source.", s:"Understanding visceral pain is essential for appropriate assessment and management of abdominal pain."}},
{id:"BCC-107", t:"single", cn:"BCC", sys:"MSK", topic:"Somatic pain", d:2, b:0.45, cj:"analyze", tags:["basic care","somatic pain","pain types","assessment","musculoskeletal"],
 stem:"A client presents with pain following a fracture. The pain is described as sharp and well-localised to the fracture site. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with somatic pain, which arises from skin, muscle, or bone and is well-localised","This is consistent with visceral pain, which is well-localised to the abdomen","This is consistent with neuropathic pain, which is burning or shooting","This is not a recognised pain type"],
 ans:0, rat:{c:"Somatic pain arises from skin, muscle, or bone and is typically sharp and well-localised. Visceral pain is poorly localised. Neuropathic pain is burning or shooting.", s:"Understanding somatic pain is essential for appropriate assessment and management of musculoskeletal pain."}},
{id:"BCC-108", t:"single", cn:"BCC", sys:"CV", topic:"Referred pain", d:3, b:0.55, cj:"analyze", tags:["basic care","referred pain","pain types","assessment","cardiac"],
 stem:"A client presents with pain in the left arm and jaw. The client has no injury to these areas. The client has a history of coronary artery disease. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with referred pain, which is felt at a site distant from the source and may indicate cardiac origin","This is consistent with somatic pain, which is well-localised to the arm and jaw","This is consistent with neuropathic pain, which affects the arm and jaw","This is not a recognised pain type"],
 ans:0, rat:{c:"Referred pain is felt at a site distant from the source. Left arm and jaw pain in a client with coronary artery disease may indicate cardiac origin and requires urgent assessment. Somatic pain is localised to the site. Neuropathic pain is burning or shooting.", s:"Understanding referred pain is essential for recognising serious underlying conditions such as cardiac pain."}},

/* ---------------------------------------------------------- RRP 5 */
{id:"RRP-141", t:"single", cn:"RRP", sys:"CV", topic:"PICC line care", d:3, b:0.55, cj:"act", tags:["risk","PICC","catheter care","dressing","infection prevention"],
 stem:"A client has a peripherally inserted central catheter (PICC) for long-term antibiotic therapy. The dressing is due for change. Which action by the nurse is most appropriate?",
 opts:["Use aseptic technique, clean the site with chlorhexidine, and apply a sterile transparent dressing","Use clean technique, since the site is not a surgical wound","Clean the site with alcohol only, since this is sufficient","Leave the dressing unchanged, since it is not soiled"],
 ans:0, rat:{c:"PICC line care requires aseptic technique, chlorhexidine cleaning, and a sterile transparent dressing. Clean technique, alcohol only, or leaving the dressing unchanged all increase infection risk and breach central line care standards.", s:"PICC line care requires strict aseptic technique; the nurse must understand the importance of infection prevention."}},
{id:"RRP-142", t:"single", cn:"RRP", sys:"CV", topic:"Tunnelled catheter care", d:3, b:0.55, cj:"act", tags:["risk","tunnelled catheter","catheter care","dressing","infection prevention"],
 stem:"A client has a tunnelled central venous catheter for chemotherapy. The client asks why the catheter is tunnelled under the skin. Which response by the nurse is most appropriate?",
 opts:["Explain that tunnelling reduces infection risk by creating a barrier between the skin exit site and the vein","Explain that tunnelling makes the catheter more comfortable","Explain that tunnelling prevents the catheter from moving","Explain that tunnelling is required for all central venous catheters"],
 ans:0, rat:{c:"Tunnelling reduces infection risk by creating a barrier between the skin exit site and the vein. It is not primarily for comfort, preventing movement, or required for all central venous catheters.", s:"Understanding the purpose of tunnelled catheters is essential for patient education and infection prevention."}},
{id:"RRP-143", t:"single", cn:"RRP", sys:"CV", topic:"Catheter occlusion", d:3, b:0.55, cj:"act", tags:["risk","catheter occlusion","central line","troubleshooting","patency"],
 stem:"A nurse is unable to flush a central venous catheter. The client is not in distress. Which action by the nurse is most appropriate?",
 opts:["Do not force the flush, check for kinks, reposition the client, and seek medical advice if the occlusion persists","Force the flush, since this will clear the occlusion","Remove the catheter, since it is no longer functional","Leave the catheter and use a peripheral line instead"],
 ans:0, rat:{c:"Catheter occlusion should not be forced, since this may cause embolism. The nurse should check for kinks, reposition the client, and seek medical advice if the occlusion persists. Forcing the flush, removing the catheter, or leaving it without action are not appropriate.", s:"Catheter occlusion requires careful troubleshooting; the nurse must understand the risks of forcing a flush."}},
{id:"RRP-144", t:"single", cn:"RRP", sys:"CV", topic:"Catheter migration", d:3, b:0.55, cj:"act", tags:["risk","catheter migration","central line","position","complications"],
 stem:"A client with a central venous catheter develops swelling in the neck and difficulty flushing the catheter. Which action by the nurse is most appropriate?",
 opts:["Suspect catheter migration, stop using the catheter, and seek urgent medical assessment","Continue using the catheter, since the swelling may resolve","Flush the catheter forcefully, since this will reposition it","Remove the catheter immediately, since it has migrated"],
 ans:0, rat:{c:"Catheter migration may cause swelling and difficulty flushing. The nurse should suspect migration, stop using the catheter, and seek urgent medical assessment. Continuing to use, flushing forcefully, or removing immediately are not appropriate without assessment.", s:"Catheter migration is a serious complication; the nurse must recognise the signs and escalate appropriately."}},
{id:"RRP-145", t:"single", cn:"RRP", sys:"CV", topic:"Catheter bundle compliance", d:2, b:0.45, cj:"act", tags:["risk","catheter bundle","infection prevention","central line","CLABSI"],
 stem:"A ward is implementing a central line care bundle to reduce catheter-related bloodstream infections. Which action by the nurse is most appropriate?",
 opts:["Comply with all bundle components, since partial compliance reduces effectiveness","Comply with the components the nurse considers most important","Comply only when reminded, since the bundle is not mandatory","Do not comply, since the bundle is a bureaucratic requirement"],
 ans:0, rat:{c:"Care bundles are most effective when all components are complied with. Partial compliance, complying only when reminded, or not complying all reduce effectiveness and increase infection risk.", s:"Care bundle compliance is essential for infection prevention; the nurse must understand the importance of full compliance."}},

/* ---------------------------------------------------------- PAA 4 */
{id:"PAA-157", t:"single", cn:"PAA", sys:"NEURO", topic:"Allodynia", d:3, b:0.55, cj:"analyze", tags:["adaptation","allodynia","neuropathic pain","pain assessment","central sensitisation"],
 stem:"A client with neuropathic pain reports severe pain when the bed sheets touch their skin. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with allodynia, which is pain from a normally non-painful stimulus","This is consistent with hyperalgesia, which is increased pain from a painful stimulus","This is consistent with referred pain, which is felt at a distant site","This is not a recognised pain phenomenon"],
 ans:0, rat:{c:"Allodynia is pain from a normally non-painful stimulus, such as light touch. Hyperalgesia is increased pain from a painful stimulus. Referred pain is felt at a distant site.", s:"Understanding allodynia is essential for assessing neuropathic pain and central sensitisation."}},
{id:"PAA-158", t:"single", cn:"PAA", sys:"NEURO", topic:"Hyperalgesia", d:3, b:0.55, cj:"analyze", tags:["adaptation","hyperalgesia","neuropathic pain","pain assessment","central sensitisation"],
 stem:"A client with chronic pain reports that a stimulus that previously caused mild pain now causes severe pain. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with hyperalgesia, which is increased pain from a painful stimulus","This is consistent with allodynia, which is pain from a non-painful stimulus","This is consistent with referred pain, which is felt at a distant site","This is not a recognised pain phenomenon"],
 ans:0, rat:{c:"Hyperalgesia is increased pain from a painful stimulus. Allodynia is pain from a non-painful stimulus. Referred pain is felt at a distant site.", s:"Understanding hyperalgesia is essential for assessing neuropathic pain and central sensitisation."}},
{id:"PAA-159", t:"single", cn:"PAA", sys:"NEURO", topic:"Central sensitisation", d:3, b:0.55, cj:"analyze", tags:["adaptation","central sensitisation","chronic pain","neuroplasticity","pain mechanism"],
 stem:"A client with chronic pain has widespread pain, allodynia, and hyperalgesia. The client's pain is disproportionate to any identifiable tissue damage. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with central sensitisation, which involves neuroplastic changes in the central nervous system","This is consistent with peripheral neuropathy, which affects the peripheral nerves","This is consistent with psychogenic pain, which has no physical basis","This is not a recognised pain mechanism"],
 ans:0, rat:{c:"Central sensitisation involves neuroplastic changes in the central nervous system, leading to widespread pain, allodynia, and hyperalgesia disproportionate to tissue damage. Peripheral neuropathy affects peripheral nerves. Psychogenic pain is not the most likely explanation.", s:"Understanding central sensitisation is essential for managing chronic pain; the nurse must recognise that the pain is real and has a neurobiological basis."}},
{id:"PAA-160", t:"single", cn:"PAA", sys:"NEURO", topic:"Wind-up phenomenon", d:3, b:0.55, cj:"analyze", tags:["adaptation","wind-up","chronic pain","central sensitisation","pain mechanism"],
 stem:"A client with chronic pain reports that repeated painful stimuli cause progressively increasing pain. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with wind-up phenomenon, which involves progressive amplification of pain with repeated stimuli","This is consistent with habituation, which involves decreasing pain with repeated stimuli","This is consistent with referred pain, which is felt at a distant site","This is not a recognised pain phenomenon"],
 ans:0, rat:{c:"Wind-up phenomenon involves progressive amplification of pain with repeated stimuli, a feature of central sensitisation. Habituation involves decreasing pain. Referred pain is felt at a distant site.", s:"Understanding wind-up phenomenon is essential for managing chronic pain and central sensitisation."}}

]);
