"use strict";
/* ============================================================
 * NCLEX-RN item bank (wave 46) — RN only
 * Hand-authored to the NCLEX-RN Test Plan blueprint, filling the
 * categories still under target after wave 45: PSY (8.8% vs 9),
 * BCC (8.9% vs 9) and PAA (13.9% vs 14). Every item is
 * difficulty 2 or 3, and the clinical detail is written to be
 * defensible.
 *
 * PSY 6: stoma acceptance and body image, amputation adjustment,
 * role change and loss of independence, maladaptive coping,
 * behavioural activation, and social prescribing.
 * BCC 7: incontinence-associated dermatitis, exudate-based
 * dressing selection, silver dressing, malodorous wound,
 * fungating wound, wound pain, and high output stoma.
 * PAA 5: the TIME wound bed framework, autolytic debridement,
 * negative pressure wound therapy, lymphangitis, and stoma
 * blockage.
 * SIC 2: preoperative stoma siting and parastomal hernia.
 * ============================================================ */

/*jshint -W098 */
NC.BANK = (NC.BANK || []).concat([

/* ---------------------------------------------------------- PSY 6 */
{id:"PSY-107", t:"single", cn:"PSY", sys:"PSYCH", topic:"Stoma acceptance and body image", d:3, b:0.55, cj:"act", tags:["psych","body image","stoma","adjustment","support"],
 stem:"A client two weeks post colostomy refuses to look at the stoma and asks the nurse to perform all stoma care. Which action by the nurse is most appropriate?",
 opts:["Accept the client's current readiness, continue care, and gradually encourage participation and viewing at the client's pace","Insist the client look at the stoma, since avoidance will delay recovery","Perform care behind a screen and avoid mentioning the stoma, since this reduces distress","Refer immediately to psychiatry, since this indicates a psychiatric disorder"],
 ans:0, rat:{c:"Adjustment to an altered body image takes time; the nurse should respect current readiness while gradually encouraging viewing and participation. Forcing exposure, avoiding the topic entirely, or pathologising a normal adjustment all fail the client.", s:"Stoma acceptance follows an adjustment trajectory; the nurse should pace involvement to the client's readiness."}},
{id:"PSY-108", t:"single", cn:"PSY", sys:"PSYCH", topic:"Amputation adjustment", d:3, b:0.55, cj:"act", tags:["psych","amputation","adjustment","grief","rehabilitation"],
 stem:"A client who underwent a below-knee amputation a week ago is tearful, expresses anger about the loss, and declines physiotherapy. Which action by the nurse is most appropriate?",
 opts:["Acknowledge the loss as a genuine grief response, allow expression, and revisit rehabilitation goals when the client is ready","Insist on physiotherapy participation, since early mobilisation is essential","Reassure the client that they are lucky to have survived, since this puts the loss in perspective","Document refusal and take no further action, since the client has the right to decline"],
 ans:0, rat:{c:"Limb loss is a genuine bereavement requiring acknowledgement and time; forcing participation, minimising the loss with comparisons, or passively documenting refusal all fail to support adjustment. Rehabilitation goals can be revisited as grief is processed.", s:"Amputation adjustment involves grief; the nurse must validate the loss before pushing rehabilitation."}},
{id:"PSY-109", t:"single", cn:"PSY", sys:"PSYCH", topic:"Role change and loss of independence", d:3, b:0.55, cj:"analyze", tags:["psych","role change","independence","identity","adjustment"],
 stem:"A previously independent client who was the main family breadwinner has become dependent on others for all personal care following a stroke. The client withdraws and refuses visits. Which interpretation by the nurse is most accurate?",
 opts:["The withdrawal reflects loss of role and identity as well as physical disability, and requires psychosocial as well as physical rehabilitation","The withdrawal indicates clinical depression requiring antidepressant medication","The withdrawal is attention-seeking and should be ignored until it resolves","The withdrawal indicates cognitive impairment requiring neurological review"],
 ans:0, rat:{c:"Loss of role and identity accompanies physical disability and requires psychosocial rehabilitation alongside physical therapy. Withdrawal is not automatically depression, attention-seeking, or cognitive impairment, though assessment for these is appropriate.", s:"Role change is a core psychosocial consequence of disability; the nurse must address identity as well as function."}},
{id:"PSY-110", t:"single", cn:"PSY", sys:"PSYCH", topic:"Maladaptive coping", d:2, b:0.45, cj:"analyze", tags:["psych","coping","maladaptive","assessment","intervention"],
 stem:"A client recently diagnosed with diabetes has stopped attending clinic, is not checking blood glucose, and says the diagnosis does not concern them. Which interpretation by the nurse is most accurate?",
 opts:["This is consistent with avoidant coping and requires exploration rather than confrontation","This is consistent with adaptive coping, since the client is managing their distress","This is consistent with denial that will resolve without intervention","This is consistent with lack of intelligence and requires simplified education"],
 ans:0, rat:{c:"Avoidance of appointments, monitoring, and acknowledgement is maladaptive coping that increases health risk and requires exploration. It is not adaptive, will not necessarily resolve alone, and is not a matter of intelligence.", s:"Recognising maladaptive coping allows the nurse to engage rather than lecture; avoidance signals unprocessed distress."}},
{id:"PSY-111", t:"single", cn:"PSY", sys:"PSYCH", topic:"Behavioural activation", d:3, b:0.55, cj:"act", tags:["psych","behavioural activation","depression","intervention","activity"],
 stem:"A client with depression has withdrawn from all activities and reports that they will resume once they feel better. Which action by the nurse is most appropriate?",
 opts:["Introduce graded activity scheduling, since activity precedes and drives mood improvement rather than following it","Agree to wait until mood improves, since activity is pointless without motivation","Advise the client to resume all previous activities immediately, since this restores routine","Refer for medication only, since behavioural approaches are ineffective in depression"],
 ans:0, rat:{c:"Behavioural activation is based on activity preceding mood improvement; graded scheduling breaks the withdrawal cycle. Waiting for motivation, demanding full resumption, or relying on medication alone all miss an evidence-based first-line intervention.", s:"Behavioural activation is an evidence-based treatment for depression; the nurse must understand that action precedes motivation."}},
{id:"PSY-112", t:"single", cn:"PSY", sys:"PSYCH", topic:"Social prescribing", d:2, b:0.45, cj:"act", tags:["psych","social prescribing","community","non-medical","support"],
 stem:"A client presents with low mood and isolation. Assessment identifies loneliness and no community connections as the main contributors. Which action by the nurse is most appropriate?",
 opts:["Consider referral to social prescribing or a community link worker to address non-medical needs","Prescribe an antidepressant, since this is the standard treatment for low mood","Advise the client to join a community club, since this is within their control","Explain that loneliness is not a health issue and cannot be addressed clinically"],
 ans:0, rat:{c:"Social prescribing addresses non-medical determinants such as loneliness through community link workers and is appropriate when these are the main contributors. Medication alone does not address isolation, generic advice is unhelpful, and loneliness is a recognised health determinant.", s:"Social prescribing recognises that many presentations have social rather than medical drivers."}},

/* ---------------------------------------------------------- BCC 7 */
{id:"BCC-114", t:"single", cn:"BCC", sys:"INTG", topic:"Incontinence-associated dermatitis", d:3, b:0.55, cj:"act", tags:["basic care","incontinence dermatitis","skin","prevention","moisture"],
 stem:"A client with faecal incontinence develops erythema and superficial skin loss in the perineal area. Which action by the nurse is most appropriate?",
 opts:["Implement a structured skin care regimen with gentle cleansing, moisturising, and a barrier product, and address the incontinence","Apply a pressure-relieving mattress, since this is a pressure ulcer","Leave the area exposed to air, since dressings will trap moisture","Wash with soap and water after each episode of incontinence, since this removes irritants"],
 ans:0, rat:{c:"Incontinence-associated dermatitis requires a structured regimen of gentle cleansing, moisturising, and barrier protection, alongside managing the incontinence itself. It is not a pressure ulcer. Soap and water are alkaline and worsen skin damage.", s:"Distinguishing incontinence-associated dermatitis from pressure damage drives correct prevention and treatment."}},
{id:"BCC-115", t:"single", cn:"BCC", sys:"INTG", topic:"Exudate-based dressing selection", d:3, b:0.55, cj:"act", tags:["basic care","dressing selection","exudate","wound","assessment"],
 stem:"A wound is producing a large volume of exudate that is striking through the current foam dressing within hours. Which action by the nurse is most appropriate?",
 opts:["Select a more absorbent dressing such as an alginate or hydrofibre, and reassess the cause of the high exudate","Apply two foam dressings, since this doubles absorbency of the exudate","Leave the dressing unchanged and change it more frequently","Apply a hydrocolloid, since this seals the wound"],
 ans:0, rat:{c:"Highly exudating wounds require highly absorbent dressings such as alginate or hydrofibre, and high exudate warrants assessment for underlying cause. Doubling foam, increasing change frequency without addressing absorbency, or sealing with hydrocolloid all worsen maceration.", s:"Dressing selection is driven by exudate level; the nurse must match absorbency to output."}},
{id:"BCC-116", t:"single", cn:"BCC", sys:"INTG", topic:"Silver dressing", d:2, b:0.45, cj:"act", tags:["basic care","silver dressing","antimicrobial","wound","infection"],
 stem:"A wound shows signs of local infection with increasing exudate and odour. The team prescribes a topical antimicrobial dressing. Which action by the nurse is most appropriate?",
 opts:["Apply the silver dressing as prescribed and set a review point, since indefinite use is not recommended","Continue the silver dressing indefinitely, since it prevents recurrence","Apply silver to every wound on the unit, since infection spreads easily","Stop all dressings, since antimicrobials delay healing"],
 ans:0, rat:{c:"Topical antimicrobials such as silver are used for a defined period with a review point, since indefinite use risks resistance and cytotoxicity. They are not for universal prophylactic use, and stopping all dressings is not appropriate.", s:"Antimicrobial dressings require time-limited use with review; the nurse must set and honour review points."}},
{id:"BCC-117", t:"single", cn:"BCC", sys:"INTG", topic:"Malodorous wound", d:3, b:0.55, cj:"act", tags:["basic care","malodorous wound","odour","palliative","dignity"],
 stem:"A client with a fungating malignant wound is distressed by the odour, which is affecting their willingness to receive visitors. Which action by the nurse is most appropriate?",
 opts:["Use odour-control measures such as charcoal or metronidazole gel, and address the psychosocial impact","Mask the odour with air freshener, since this is quickest","Advise the client to stop receiving visitors, since this avoids embarrassment","Change the dressing hourly, since odour is caused by dressing frequency"],
 ans:0, rat:{c:"Odour control uses charcoal dressings or topical metronidazole, and the psychosocial impact on the client's social life must be addressed. Air freshener masks rather than treats, isolating the client compounds distress, and hourly changes are unnecessary and traumatic.", s:"Malignant wound odour is a major source of distress; the nurse must treat both the odour and its social consequences."}},
{id:"BCC-118", t:"single", cn:"BCC", sys:"INTG", topic:"Fungating wound", d:3, b:0.55, cj:"act", tags:["basic care","fungating wound","malignant","palliative","bleeding"],
 stem:"A client has a fungating malignant wound that bleeds easily on dressing change. Which action by the nurse is most appropriate?",
 opts:["Use a non-adherent dressing, minimise disturbance, and keep a bleeding management plan in place","Debride the necrotic tissue, since this reduces bleeding","Change the dressing daily using firm pressure, since this removes debris","Apply a tight compression bandage, since this prevents bleeding"],
 ans:0, rat:{c:"Fungating malignant wounds are fragile and bleed easily, requiring non-adherent dressings, minimal disturbance, and a bleeding plan. Debridement and firm pressure precipitate haemorrhage, and compression is not appropriate for malignant wounds.", s:"Fungating wound care is palliative in intent; the nurse must avoid interventions that provoke bleeding."}},
{id:"BCC-119", t:"single", cn:"BCC", sys:"INTG", topic:"Wound pain", d:2, b:0.45, cj:"act", tags:["basic care","wound pain","dressing change","premedication","comfort"],
 stem:"A client reports severe pain on every dressing change and has begun to dread the procedure. Which action by the nurse is most appropriate?",
 opts:["Assess and pre-medicate before dressing changes, and review the dressing for a less traumatic option","Continue as before, since pain on dressing change is unavoidable","Give analgesia only after the dressing change, since this is when pain peaks","Advise the client to tolerate the pain, since wound healing requires dressing changes"],
 ans:0, rat:{c:"Procedure-related wound pain should be anticipated with pre-medication, and the dressing should be reviewed for a less traumatic option. Pain on dressing change is avoidable, post-procedure analgesia is too late, and asking the client to tolerate pain is unacceptable.", s:"Anticipatory pain management transforms the dressing change experience; the nurse should treat it as predictable pain."}},
{id:"BCC-120", t:"single", cn:"BCC", sys:"GI", topic:"High output stoma", d:3, b:0.55, cj:"act", tags:["basic care","high output stoma","ileostomy","dehydration","electrolytes"],
 stem:"A client with a new ileostomy has an output of 1800 mL in 24 hours and reports thirst and dizziness. Which action by the nurse is the priority?",
 opts:["Assess hydration and electrolytes, since high stoma output causes dehydration and sodium depletion, and notify the team","Increase oral fluid intake with water only, since this replaces the loss","Reduce the client's food intake, since this will reduce output","Reassure the client, since high output is expected in a new ileostomy"],
 ans:0, rat:{c:"High ileostomy output causes dehydration and sodium depletion requiring assessment and escalation. Plain water alone worsens sodium depletion, reducing food is not the priority, and 1800 mL is above the expected range for a new ileostomy.", s:"High output stoma is a common cause of readmission; the nurse must recognise the dehydration and electrolyte risk."}},

/* ---------------------------------------------------------- PAA 5 */
{id:"PAA-174", t:"single", cn:"PAA", sys:"INTG", topic:"TIME wound bed framework", d:3, b:0.55, cj:"analyze", tags:["adaptation","TIME framework","wound bed","assessment","debridement"],
 stem:"A wound has a moist but non-advancing edge with slough covering much of the wound bed. Which interpretation by the nurse is most accurate?",
 opts:["Using the TIME framework, the tissue is non-viable and requires debridement, and the edge is not advancing","The wound is healing normally and requires only continued dressing changes","The wound is infected and requires systemic antibiotics","The wound is dry and requires additional moisture"],
 ans:0, rat:{c:"The TIME framework (Tissue, Infection/inflammation, Moisture, Edge) guides assessment: non-viable tissue requires debridement and a non-advancing edge signals a stalled wound. It is not healing normally, and slough is not equivalent to infection.", s:"The TIME framework gives a structured way to identify why a wound is stalled and what to change."}},
{id:"PAA-175", t:"single", cn:"PAA", sys:"INTG", topic:"Autolytic debridement", d:2, b:0.45, cj:"act", tags:["adaptation","autolytic debridement","wound","slough","dressing"],
 stem:"A frail client has a wound covered in soft slough. The client cannot tolerate sharp debridement. Which action by the nurse is most appropriate?",
 opts:["Use autolytic debridement with a moisture-retentive dressing, since this uses the body's own enzymes","Use sharp debridement regardless, since it is the only effective method","Leave the slough in place, since debridement is not necessary","Apply a dry gauze dressing, since this draws out the slough"],
 ans:0, rat:{c:"Autolytic debridement uses a moisture-retentive dressing to let the body's own enzymes liquefy slough, and is suitable where sharp debridement is not tolerated. Sharp debridement is not the only method, leaving slough stalls healing, and dry gauze is traumatic and ineffective.", s:"Autolytic debridement is slower but appropriate for frail clients; the nurse must match method to tolerance."}},
{id:"PAA-176", t:"single", cn:"PAA", sys:"INTG", topic:"Negative pressure wound therapy", d:3, b:0.55, cj:"act", tags:["adaptation","negative pressure","wound VAC","therapy","monitoring"],
 stem:"A client has negative pressure wound therapy applied to a large surgical wound. Which action by the nurse is most appropriate?",
 opts:["Confirm an airtight seal, monitor output volume and character, and assess for pain and bleeding","Increase the pressure setting to speed healing, since higher pressure is more effective","Change the foam daily, since this reduces infection risk","Ignore the output volume, since only the seal matters"],
 ans:0, rat:{c:"Negative pressure therapy requires confirmation of an airtight seal, monitoring of output volume and character, and assessment for pain and bleeding. Higher pressure is not better, foam is not changed daily, and output volume is clinically significant.", s:"Negative pressure therapy monitoring focuses on seal, output, and complications; the nurse must track all three."}},
{id:"PAA-177", t:"single", cn:"PAA", sys:"INF", topic:"Lymphangitis", d:3, b:0.55, cj:"recognize", tags:["adaptation","lymphangitis","infection","spreading","emergency"],
 stem:"A client with an infected wound develops red streaking extending proximally up the limb with fever and malaise. Which interpretation by the nurse is most accurate?",
 opts:["These findings suggest lymphangitis indicating spreading infection and require urgent medical assessment and antibiotics","These findings suggest a normal inflammatory response and require observation only","These findings suggest an allergic reaction to the dressing and require dressing change","These findings suggest superficial thrombophlebitis and require warm compresses"],
 ans:0, rat:{c:"Red streaking extending proximally with systemic features indicates lymphangitis and spreading infection requiring urgent assessment and antibiotics. It is not a normal inflammatory response, allergy, or thrombophlebitis.", s:"Lymphangitis signals spreading infection; the nurse must recognise the streaking pattern and escalate urgently."}},
{id:"PAA-178", t:"single", cn:"PAA", sys:"GI", topic:"Stoma blockage", d:3, b:0.55, cj:"act", tags:["adaptation","stoma blockage","ileostomy","obstruction","emergency"],
 stem:"A client with an ileostomy reports abdominal cramps, no stoma output for twelve hours, and nausea. The abdomen is distended. Which action by the nurse is the priority?",
 opts:["Assess for obstruction, withhold oral intake, and escalate for urgent medical review","Encourage oral fluid and fibre, since this will relieve the blockage","Irrigate the stoma with a large volume of saline, since this clears obstruction","Administer a laxative, since this stimulates output"],
 ans:0, rat:{c:"Absent stoma output with cramps, nausea, and distension indicates possible obstruction requiring assessment, nil by mouth, and urgent escalation. Increasing fibre, high-volume irrigation, or laxatives all risk perforation and worsening obstruction.", s:"Stoma obstruction is an emergency; the nurse must recognise the presentation and avoid interventions that increase pressure."}},

/* ---------------------------------------------------------- SIC 2 */
{id:"SIC-167", t:"single", cn:"SIC", sys:"GI", topic:"Preoperative stoma siting", d:3, b:0.55, cj:"act", tags:["safety","stoma siting","preoperative","assessment","prevention"],
 stem:"A client is scheduled for surgery that will result in a colostomy. A stoma nurse is available preoperatively. Which action by the nurse is most appropriate?",
 opts:["Ensure the stoma site is marked preoperatively with the client sitting, standing, and lying, since this reduces postoperative complications","Allow the surgeon to choose the site rather than marking it preoperatively, since this is more accurate","Site the stoma in the skin crease, since this is most discreet","Site the stoma at the belt line, since this is most convenient for the client"],
 ans:0, rat:{c:"Preoperative stoma siting with the client in multiple positions avoids creases, scars, bony prominences, and the belt line, and reduces leakage and skin complications. Intraoperative siting misses positional assessment, and creases or the belt line cause appliance failure.", s:"Preoperative siting is a simple intervention with major impact on stoma outcomes; the nurse must ensure it happens."}},
{id:"SIC-168", t:"single", cn:"SIC", sys:"GI", topic:"Parastomal hernia", d:2, b:0.45, cj:"recognize", tags:["safety","parastomal hernia","stoma","complication","assessment"],
 stem:"A client with a long-standing colostomy reports a bulge around the stoma that is more noticeable on coughing, and the appliance now leaks frequently. Which interpretation by the nurse is most accurate?",
 opts:["These findings suggest a parastomal hernia and require assessment, since it compromises appliance fit","These findings suggest stomal prolapse and require urgent surgical referral","These findings suggest weight gain and require dietary advice","These findings suggest a normal change with appliance leakage that requires no action"],
 ans:0, rat:{c:"A bulge around the stoma that increases on coughing and causes appliance leakage suggests a parastomal hernia requiring assessment. Prolapse involves the stoma itself protruding, weight gain does not explain a localised bulge, and appliance failure requires action.", s:"Parastomal hernia is a common late stoma complication; the nurse must link the bulge to appliance failure."}}

]);
