/* RN Ready — case study v2 · anaphylaxis five minutes into an infusion.
   Twenty-fourth unfolding case: a 28-year-old given intravenous amoxicillin
   develops urticaria, lip and tongue swelling, stridor and a blood pressure of
   72/40 mm Hg within five minutes. Judgment unfolds from recognizing anaphylaxis
   as airway and circulatory collapse, through intramuscular adrenaline into the
   anterolateral thigh repeated every 5 minutes, to the biphasic reaction that
   makes early discharge unsafe.

   Wave 67 — RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-ANAPHYLAXIS-01", title:"Five Minutes In — Ms. Nwosu, 28",
 setting:"Medical day unit", sys:"INTG", cn:"PHA", d:3, b:0.55,
 summary:"28-year-old woman develops generalized urticaria, lip and tongue swelling, stridor, wheeze and a blood pressure of 72/40 mm Hg five minutes into an intravenous amoxicillin infusion. Judgment unfolds from recognizing anaphylaxis as airway and circulatory collapse, through intramuscular adrenaline into the anterolateral thigh repeated every 5 minutes, to the biphasic reaction that makes early discharge unsafe.",
 exhibits:{
  history:{name:"History", type:"text", body:"28-year-old woman admitted for cellulitis of the left leg. A documented amoxicillin allergy was recorded in an old clinic letter that had not been carried forward onto the current chart, and the first dose of intravenous amoxicillin was started. Five minutes into the infusion she reports itching of her palms and scalp, then a feeling that her 'throat is closing'. No previous anaphylaxis. She carries no autoinjector. Two other clients are in the bay."},
  vitals:{name:"Observations", type:"kv", rows:[["Airway","Audible inspiratory stridor; swelling of the lips and tongue"],["Respiratory rate","32/min with widespread wheeze and accessory muscle use"],["SpO2 (room air)","88%, rising to 94% on 15 L via a reservoir mask"],["Heart rate","128/min"],["Blood pressure","72/40 mm Hg"],["Capillary refill","5 seconds"],["Skin","Generalized urticarial rash, flushing, periorbital swelling"],["Neurological","Alert but extremely anxious, saying 'I am going to die'"]]},
  labs:{name:"Relevant Background", type:"kv", rows:[["Previous documented allergy","Amoxicillin — recorded in an old clinic letter, not carried forward"],["Time since infusion started","5 minutes"],["Infusion still running","Yes, at the time of first assessment"],["Autoinjector carried","None"],["Body weight","64 kg"]]},
  orders:{name:"Anaphylaxis Protocol", type:"text", body:"1. STOP the amoxicillin immediately and keep the cannula in place. 2. Adrenaline 500 micrograms (0.5 mL of 1 mg/mL, 1:1000) intramuscularly into the anterolateral thigh, repeat every 5 minutes if there is no improvement. 3. High-flow oxygen via a reservoir mask to keep saturation at or above 94%. 4. Lie flat with the legs raised; if breathing is the dominant problem, allow her to sit up — but do NOT allow her to stand or walk. 5. Rapid 0.9% sodium chloride 500–1000 mL. 6. Call for the resuscitation team and prepare for a difficult airway. 7. Chlorphenamine and hydrocortisone are second-line and follow adrenaline. 8. Consider an adrenaline infusion if there is no response to repeated intramuscular doses. 9. Observe for at least 6–12 hours for a biphasic reaction. 10. Prescribe an autoinjector and teach its use before discharge."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the observations. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals"],
   opts:["She is having an acute asthma attack and needs a nebulized bronchodilator",
    "Anxiety and a panic attack, since she says she is going to die",
    "An allergic rash with some wheeze, so an antihistamine and observation are appropriate",
    "Anaphylaxis with airway swelling and circulatory collapse, requiring adrenaline within seconds"],
   ans:3,
   rat:{c:"Anaphylaxis is a clinical diagnosis made on acute onset after exposure to a likely trigger with involvement of the airway, breathing or circulation — and she has all three within five minutes of a drug she is documented to be allergic to. Stridor means upper airway obstruction from lip and tongue swelling, the wheeze and saturation of 88% show lower airway involvement, and a blood pressure of 72/40 with a 5-second refill shows shock. An antihistamine does not reverse airway swelling or shock. Her sense of impending doom is a recognized feature of anaphylaxis, not a psychiatric presentation, and dismissing it is a classic fatal error.",
   o:["Wheeze alone would fit asthma, but stridor, urticaria and shock after a drug exposure do not.",
    "A sense of impending doom is a recognized feature of anaphylaxis, not a panic attack.",
    "An antihistamine does not reverse airway swelling or circulatory collapse.",
    "Correct — airway, breathing and circulation are all involved within five minutes of a known trigger."],
   s:"Anaphylaxis is diagnosed clinically: acute onset after a likely trigger with airway, breathing or circulation involvement. Stridor plus urticaria plus hypotension is never 'just an allergic reaction' — and a sense of impending doom is a symptom, not anxiety."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals"],
   hotspot:{mode:"rows", rows:[
    "Audible inspiratory stridor with swelling of the lips and tongue",
    "Oxygen saturation 88% on room air",
    "Blood pressure 72/40 mm Hg with a capillary refill of 5 seconds",
    "Generalized urticarial rash with periorbital swelling",
    "Heart rate 128/min",
    "The amoxicillin infusion is still running"
   ], ans:[0,1,2,3,4]},
   rat:{c:"Every observation listed is abnormal. Stridor with lip and tongue swelling is upper airway obstruction, the saturation of 88% on room air is hypoxia, a blood pressure of 72/40 with a 5-second refill is shock, the urticaria and periorbital swelling are the cutaneous manifestation, and a heart rate of 128/min is the compensatory tachycardia of that shock. The infusion still running is not an observation but a state — and it is the most important thing on the screen, because the trigger is still being delivered while the client deteriorates.",
   o:["Expected is a silent, patent airway; stridor with lip and tongue swelling indicates obstruction.",
    "Expected saturation is 95–100% on room air; 88% is hypoxia.",
    "Expected systolic pressure is above 100 mm Hg with refill under 2 seconds; 72/40 with 5 seconds is shock.",
    "Expected skin is intact without rash; urticaria and periorbital swelling are abnormal.",
    "Expected heart rate is 60–100/min; 128/min is the compensatory response to shock.",
    "The running infusion is the trigger still being delivered — not an observation, but the most urgent fact here."],
   s:"In anaphylaxis every observation is usually abnormal, and the trigger is often still running. Stopping the exposure is part of the assessment, not a step that comes later."}},
  {step:"prioritize", t:"single", stem:"Which action by the nurse takes priority?",
   reveal:["history","vitals","labs","orders"],
   opts:["Stop the infusion and give adrenaline 500 micrograms intramuscularly into the anterolateral thigh immediately",
    "Give intravenous chlorphenamine, since it is an antihistamine reaction",
    "Give intravenous hydrocortisone first, since steroids prevent the reaction progressing",
    "Transfer her to the resuscitation area before giving any medication"],
   ans:0,
   rat:{c:"Adrenaline is the only drug that reverses both airway obstruction and cardiovascular collapse — it is alpha-mediated vasoconstriction for the swelling and the blood pressure, and beta-mediated bronchodilation for the wheeze. Intramuscular injection into the anterolateral thigh gives faster and more reliable absorption than subcutaneous injection, and intravenous adrenaline is reserved for specialists because of the risk of fatal arrhythmia. Stopping the infusion takes one second and must happen at the same time. An antihistamine treats itching and nothing else; a steroid takes hours to work and neither reverses airway swelling nor supports the blood pressure. And moving her before treating wastes the seconds that decide the outcome — treat where she is.",
   o:["Correct — stop the infusion and give intramuscular adrenaline into the anterolateral thigh; it is the only drug that reverses both airway obstruction and shock.",
    "An antihistamine treats itching; it does not reverse airway swelling or hypotension.",
    "A steroid takes hours to act and reverses neither airway swelling nor shock.",
    "Moving her before treating wastes critical seconds; treat where she is."],
   s:"Adrenaline first, intramuscularly into the anterolateral thigh, at the same moment the trigger is stopped. Antihistamines and steroids are second-line and never a substitute — they act on nothing that is killing the client."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["vitals","labs","orders"],
   opts:["Adrenaline repeated every 5 minutes until there is improvement, since a single dose is often not enough",
    "High-flow oxygen via a reservoir mask and rapid intravenous crystalloid",
    "Lying her flat with the legs raised, or sitting her up if breathing is the dominant problem — but never letting her stand",
    "Chlorphenamine and hydrocortisone as second-line adjuncts after the adrenaline has been given",
    "Discharging her once she feels better, since the reaction has clearly settled"],
   ans:[0,1,2,3],
   rat:{c:"Adrenaline is repeated every 5 minutes because a single dose frequently wears off before the reaction resolves, and failure to repeat it is a recognized cause of death. Oxygen and fluid treat the hypoxia and the massive capillary leak that has emptied her circulation. Positioning is a safety intervention: she lies flat with the legs raised, or sits up if breathing dominates, but must never stand or walk — sudden upright posture in a client with an empty ventricle can cause abrupt cardiovascular collapse. The antihistamine and steroid are adjuncts given after adrenaline and have no role in the first minutes. And discharge once she feels better ignores the biphasic reaction, which can recur hours later with no warning.",
   o:["Correct — repeat every 5 minutes; a single dose is often insufficient.",
    "Correct — oxygen for hypoxia and rapid crystalloid for the capillary leak.",
    "Correct — flat with legs raised, or sitting up if breathing dominates; standing risks abrupt collapse.",
    "Correct — adjuncts only, and only after adrenaline.",
    "A biphasic reaction can recur hours later, so observation for 6–12 hours is required."],
   s:"Repeat adrenaline every 5 minutes, give oxygen and fluid, position carefully — never let the client stand — and observe for the biphasic reaction. Antihistamines and steroids come after, not instead."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","labs","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Stop the amoxicillin infusion and call for the resuscitation team",
     "Give adrenaline 500 micrograms intramuscularly into the anterolateral thigh",
     "Give high-flow oxygen, lie her flat with the legs raised and start rapid intravenous crystalloid",
     "Give the antihistamine and steroid, then observe for at least 6–12 hours and arrange autoinjector teaching"],
    ans:[0,1,2,3]},
   rat:{c:"Stopping the trigger and calling for help happen in the same breath — continuing the infusion while treating is self-defeating. Adrenaline follows within seconds because it is the only drug that reverses the two things that will kill her. Oxygen, positioning and fluid come immediately after, since the hypoxia and the capillary leak are both actively harmful. The antihistamine and steroid are adjuncts given once adrenaline is in, and the observation period and autoinjector teaching follow, because the biphasic reaction is a real risk and she leaves with no way of treating a recurrence.",
   o:["Stop the trigger and call for help — the infusion must not keep running.",
    "Adrenaline intramuscularly within seconds — the only drug that reverses airway obstruction and shock.",
    "Oxygen, positioning flat with legs raised, and rapid crystalloid.",
    "Adjunctive antihistamine and steroid, then 6–12 hours of observation and autoinjector teaching."],
   s:"Anaphylaxis sequence: stop the trigger and call for help → adrenaline IM → oxygen, position, fluid → adjuncts, observe 6–12 hours, prescribe and teach the autoinjector."}},
  {step:"evaluate", t:"cloze", stem:"Fifteen minutes and two doses of adrenaline later her stridor has resolved, her saturation is 97% on oxygen and her blood pressure is 104/62 mm Hg. She says she feels fine and wants to go home. Complete each evaluation statement.",
   reveal:["history","vitals","labs","orders"],
   cloze:{lines:[
    {pre:"She needed a second dose of adrenaline, so the nurse understands that ", post:".",
     opts:["the first dose was given incorrectly and the route should be changed","repeating adrenaline every 5 minutes until there is improvement is correct practice, since a single dose is frequently insufficient","adrenaline should be stopped now to avoid toxicity","an intravenous bolus of adrenaline should replace the intramuscular route"], ans:1},
    {pre:"Because she now feels well, the nurse recognizes that she must ", post:".",
     opts:["be discharged with advice to return if symptoms recur","be observed for at least 6–12 hours, since a biphasic reaction can recur after apparent resolution","be kept for 30 minutes only, since she has already responded","be given a sedative to help her rest"], ans:1},
    {pre:"Before discharge the nurse recognizes that she must be prescribed ", post:".",
     opts:["an adrenaline autoinjector with teaching on its use for her and her family, since a future reaction may occur outside a clinical setting","a supply of antihistamines only","a course of oral steroids only","a nebulizer for future wheeze"], ans:0},
    {pre:"Reviewing the incident, the nurse recognizes that the system failure was ", post:".",
     opts:["that she had no previous anaphylaxis to predict this","the failure to carry forward a documented amoxicillin allergy onto the current chart, so allergy reconciliation at every admission is essential","that the infusion was given too quickly","that the bay had two other clients in it"], ans:1}]},
   rat:{c:"A second dose was correct, not a sign of error — adrenaline is repeated every 5 minutes until improvement, and needing more than one dose is common rather than exceptional. She must still be observed for 6 to 12 hours because a biphasic reaction can recur after apparent full resolution, with no re-exposure and no warning, which is exactly why feeling well is not the discharge criterion. She needs an autoinjector with teaching for her and her family, because the next reaction may happen at home where the only treatment available is the one she carries. And the system failure was a documented amoxicillin allergy in an old letter that never reached the current chart — allergy reconciliation at every admission is the control that would have prevented this entirely.",
   o:["A second dose is correct practice, not evidence of an error in the first.",
    "Correct — repeat every 5 minutes until improvement; a single dose is frequently insufficient.",
    "Adrenaline is continued until the reaction resolves; stopping it invites recurrence.",
    "Intravenous adrenaline is reserved for specialists because of the risk of fatal arrhythmia.",
    "Feeling well is not the discharge criterion.",
    "Correct — 6–12 hours of observation, since a biphasic reaction can recur after apparent resolution.",
    "Thirty minutes is far too short to exclude a biphasic reaction.",
    "A sedative has no role and may mask deterioration.",
    "Correct — an autoinjector with teaching, because the next reaction may occur outside a clinical setting.",
    "Antihistamines alone do not treat anaphylaxis.",
    "Steroids alone do not treat anaphylaxis and take hours to act.",
    "A nebulizer does not treat upper airway swelling or shock.",
    "The absence of previous anaphylaxis does not prevent a first episode.",
    "Correct — a documented allergy failed to reach the chart; allergy reconciliation at every admission is the essential control.",
    "Infusion rate did not cause the reaction; the allergen did.",
    "Other clients in the bay did not cause the reaction."],
   s:"Four anaphylaxis safety points: repeat adrenaline every 5 minutes, observe 6–12 hours for the biphasic reaction, prescribe and teach the autoinjector, and reconcile allergies at every admission — that last control is what prevents the whole event."}}]})
;
