/* RN Ready — case study v2 · lithium toxicity precipitated by gastroenteritis.
   Nineteenth unfolding case: a 34-year-old on lithium develops vomiting and
   diarrhea, takes ibuprofen, and presents with a level of 2.4 mmol/L.
   Judgment unfolds from the two precipitants, through stopping the drug and
   hydrating rather than treating symptoms, to dialysis thresholds and the sick
   day rules that prevent recurrence.

   Wave 66 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-LITHIUM-01", title:"The Gastroenteritis — Ms. Adeyinka, 34",
 setting:"Emergency department / mental health unit", sys:"PSYCH", cn:"PHA", d:3, b:0.55,
 summary:"34-year-old woman with bipolar I disorder on lithium, four days of vomiting and diarrhea with reduced fluid intake plus self-started ibuprofen, now with a coarse tremor, ataxia, slurred speech and confusion; lithium 2.4 mmol/L against 0.7 three weeks earlier. Judgment unfolds from the two precipitants, through stopping the drug and hydrating, to dialysis thresholds and sick day rules.",
 exhibits:{
  history:{name:"History", type:"text", body:"34-year-old woman with bipolar I disorder, well controlled on lithium carbonate 400 mg twice daily for six years. Lithium level 0.7 mmol/L three weeks ago. Four days of vomiting and diarrhea after a family member's gastroenteritis, with markedly reduced fluid intake because drinking makes her vomit. She started over-the-counter ibuprofen two days ago for a headache. No other regular medicines. Family report increasing unsteadiness, slurred speech and confusion over the last 24 hours, and a tremor that has become much coarser than her usual fine tremor."},
  vitals:{name:"Observations", type:"kv", rows:[["Blood pressure","104/66 mm Hg, postural drop to 88/54 on standing"],["Heart rate","108/min"],["Respiratory rate","18/min"],["Core temperature","36.9 °C (98.4 °F)"],["SpO2 (room air)","97%"],["Capillary glucose","5.1 mmol/L (92 mg/dL)"],["Neurological","Coarse tremor of both hands, ataxic gait, slurred speech, confused but oriented to person"]]},
  labs:{name:"Laboratory Results", type:"kv", rows:[["Lithium","2.4 mmol/L (taken 12 hours after her last dose)"],["Sodium","146 mmol/L"],["Potassium","3.4 mmol/L"],["Creatinine","138 µmol/L (1.56 mg/dL) — baseline 78 µmol/L"],["Estimated glomerular filtration rate","38 mL/min/1.73 m² — baseline 92"],["Thyroid stimulating hormone","3.1 mU/L"],["Corrected calcium","2.35 mmol/L"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. STOP lithium immediately. 2. Intravenous 0.9% sodium chloride to restore volume and promote renal lithium clearance. 3. Repeat the lithium level every 6 to 12 hours until it is falling and below 1.0 mmol/L. 4. Continuous cardiac monitoring and a 12-lead electrocardiogram. 5. Hourly neurological observations including tremor, coordination, speech and conscious level. 6. Stop the ibuprofen; avoid all non-steroidal anti-inflammatory drugs. 7. Nephrology referral — hemodialysis is indicated for a level above 4.0 mmol/L, or above 2.5 mmol/L with severe symptoms or impaired kidney function, or for any level with deteriorating neurological status. 8. Strict fluid balance and daily weight. 9. Nil by mouth if vomiting continues. 10. Psychiatric liaison for onward management."}},
 items:[
  {step:"recognize", t:"single", stem:"Her level was 0.7 mmol/L three weeks ago and is now 2.4 mmol/L on the same dose. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","labs"],
   opts:["She must have been taking extra doses, since her prescribed dose has not changed",
    "Volume depletion from the vomiting and diarrhea plus the ibuprofen reduced her renal clearance of lithium, which has a very narrow therapeutic index",
    "Lithium levels rise unpredictably over time, so this was inevitable after six years of treatment",
    "The level of 2.4 mmol/L is only slightly above range and explains none of her neurological findings"],
   ans:1,
   rat:{c:"Lithium is handled almost entirely by the kidneys and is reabsorbed in the proximal tubule in competition with sodium, so anything that depletes sodium or volume — vomiting, diarrhea, poor intake, sweating — increases reabsorption and raises the level. Ibuprofen independently reduces the glomerular filtration rate and lithium clearance. Her creatinine has risen from 78 to 138 µmol/L and her estimated glomerular filtration rate has fallen from 92 to 38, so her clearance is roughly halved on the same dose. The therapeutic index is very narrow: 0.4 to 1.0 mmol/L is therapeutic, above 1.5 is toxic, and above 2.0 is severe. And her findings are textbook toxicity — a coarse tremor replacing a fine one, ataxia, slurred speech and confusion — not an incidental number.",
   o:["Extra doses are possible but the dehydration and ibuprofen fully explain it, and assuming non-adherence misses the reversible cause.",
    "Correct — volume depletion plus a non-steroidal anti-inflammatory drug in a drug with a very narrow therapeutic index.",
    "Levels do not drift upward on their own; something changed her clearance.",
    "A level of 2.4 mmol/L is severe toxicity and matches her coarse tremor, ataxia and confusion exactly."],
   s:"Lithium has a very narrow index and is renally cleared in competition with sodium. Dehydration, non-steroidal anti-inflammatory drugs, thiazides and ACE inhibitors all raise the level. A coarse tremor replacing a fine one is the classic early warning."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that indicates lithium toxicity or a reduced ability to clear it.",
   reveal:["vitals","labs"],
   hotspot:{mode:"rows", rows:[
    "Lithium 2.4 mmol/L",
    "Coarse tremor with an ataxic gait and slurred speech",
    "Creatinine 138 µmol/L against a baseline of 78 µmol/L",
    "A postural blood pressure drop with a heart rate of 108/min",
    "Thyroid stimulating hormone 3.1 mU/L",
    "Corrected calcium 2.35 mmol/L"
   ], ans:[0,1,2,3]},
   rat:{c:"The level, the neurological triad of coarse tremor with ataxia and dysarthria, the acute kidney injury and the postural hypotension with tachycardia showing volume depletion are all abnormal — and the last of these is the cause as well as a finding. The thyroid stimulating hormone and corrected calcium are both normal, and they are here for a reason beyond being planted values: long-term lithium causes hypothyroidism and hyperparathyroidism, so both are checked routinely, and knowing they are currently normal is part of the assessment rather than an afterthought. Two planted normals, both clinically meaningful in this drug.",
   o:["Therapeutic range is 0.4–1.0 mmol/L; 2.4 is severe toxicity.",
    "Coarse tremor, ataxia and dysarthria are the classic neurological triad of lithium toxicity.",
    "A creatinine rise from 78 to 138 µmol/L is acute kidney injury and roughly halves lithium clearance.",
    "A postural drop with tachycardia indicates volume depletion — the precipitant as well as a finding.",
    "Normal thyroid stimulating hormone is about 0.4–4.0 mU/L — within range, though lithium causes hypothyroidism long term.",
    "Normal corrected calcium is about 2.2–2.6 mmol/L — within range, though lithium causes hyperparathyroidism long term."],
   s:"Lithium toxicity assessment covers the level, the neurological triad, renal function and volume status — and always the thyroid and calcium, because long-term lithium damages both. Know that the thyroid and calcium checks are part of routine lithium monitoring."}},
  {step:"prioritize", t:"single", stem:"Which action by the nurse takes priority?",
   reveal:["history","vitals","labs","orders"],
   opts:["Stop the lithium, stop the ibuprofen and start intravenous 0.9% sodium chloride to restore volume and renal clearance",
    "Give an antiemetic and encourage oral fluids, since the gastroenteritis is the underlying problem",
    "Continue the lithium at the same dose until the level is confirmed on a repeat sample",
    "Arrange hemodialysis immediately, since her level is above 2.0 mmol/L"],
   ans:0,
   rat:{c:"Three actions happen at once and all three are in the first option: stop the drug that is causing the toxicity, stop the drug that is reducing its clearance, and restore the volume that will let her kidneys clear it — sodium chloride restores volume and reduces proximal tubular reabsorption of lithium. Antiemetics help but oral rehydration is not enough in a client with acute kidney injury and severe toxicity. Continuing lithium pending a repeat level continues the harm for no benefit, since the clinical picture already confirms toxicity. And dialysis is not automatic at 2.4 mmol/L — the thresholds are above 4.0, or above 2.5 with severe symptoms or renal impairment, or any level with neurological deterioration; she is a nephrology referral, not an immediate dialysis.",
   o:["Correct — stop lithium, stop the non-steroidal anti-inflammatory drug, and restore volume with sodium chloride.",
    "An antiemetic and oral fluids are insufficient in acute kidney injury with severe toxicity; she needs intravenous volume.",
    "Continuing a toxic drug pending confirmation continues the harm; the clinical picture already confirms toxicity.",
    "Dialysis thresholds are above 4.0, or above 2.5 with severe symptoms or renal impairment — she needs a nephrology referral first."],
   s:"Lithium toxicity: stop the drug, stop the interacting medicines, hydrate with sodium chloride, monitor serially — and know the dialysis thresholds rather than assuming any high level needs it."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["vitals","labs","orders"],
   opts:["Lithium levels repeated every 6 to 12 hours until falling and below 1.0 mmol/L, since the level continues to rise after the last dose",
    "Continuous cardiac monitoring with a 12-lead electrocardiogram, since toxicity causes arrhythmias and conduction changes",
    "Hourly neurological observations, since a deteriorating conscious level is a dialysis trigger",
    "Strict fluid balance with daily weight, since both under- and over-hydration cause harm",
    "Restarting lithium at half the dose once her vomiting settles, so that her mood stays stable"],
   ans:[0,1,2,3],
   rat:{c:"Levels are checked serially because absorption continues after the last dose and the level can still be rising when she arrives — a single level never guides management. Lithium toxicity causes sinus node dysfunction, T-wave changes and conduction abnormalities, so monitoring is mandatory. Neurological observation is the parameter that determines whether dialysis becomes necessary, because a deteriorating conscious level triggers it at any level. Fluid balance matters in both directions: too little prolongs toxicity and too much risks pulmonary edema. Restarting lithium at any dose before the level is falling and the cause is fixed is unsafe — the decision to restart belongs to psychiatry, often after a period off the drug.",
   o:["Correct — absorption continues after the last dose, so serial levels are essential and one level guides nothing.",
    "Correct — lithium toxicity causes sinus node dysfunction and conduction changes.",
    "Correct — a deteriorating conscious level triggers dialysis at any lithium level.",
    "Correct — too little fluid prolongs toxicity, too much risks pulmonary edema; balance in both directions.",
    "Restarting before the level is falling and the cause is fixed is unsafe; that decision belongs to psychiatry."],
   s:"Serial lithium levels, cardiac monitoring and hourly neurological observation — the neurological trend is what triggers dialysis. Never restart on a falling-but-still-toxic level."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","labs","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Stop the lithium and the ibuprofen, and secure intravenous access",
     "Start 0.9% sodium chloride to restore volume, and attach continuous cardiac monitoring",
     "Take the level for serial monitoring and begin hourly neurological observations",
     "Escalate to nephrology for dialysis assessment if the level stays high or the neurological status worsens"],
    ans:[0,1,2,3]},
   rat:{c:"Stopping both drugs comes first because every subsequent dose and every further ibuprofen tablet makes the toxicity worse, and access is needed for everything else. Volume restoration and cardiac monitoring follow immediately, since saline is the treatment that promotes clearance and toxicity causes arrhythmias. Serial levels and hourly neurological observation come next and then continue, because the trend — not a single value — determines whether dialysis is needed. Nephrology escalation comes last in this sequence but is conditional and anticipated: if the level fails to fall or the conscious level drops, dialysis becomes urgent.",
   o:["Stop both drugs and get access — every further dose worsens the toxicity.",
    "Sodium chloride restores volume and promotes clearance; monitoring covers the arrhythmia risk.",
    "Serial levels and hourly neurological observations establish the trend that guides everything.",
    "Nephrology escalation for dialysis if the level plateaus or the neurological status deteriorates."],
   s:"Lithium toxicity sequence: stop the drugs → hydrate and monitor the heart → serial levels and hourly neuro → nephrology if the trend is wrong. The trend decides dialysis, not one number."}},
  {step:"evaluate", t:"cloze", stem:"Twelve hours later her level is 1.6 mmol/L and falling, but her tremor and unsteadiness persist. Complete each evaluation statement.",
   reveal:["history","vitals","labs","orders"],
   cloze:{lines:[
    {pre:"The level is falling but her neurological signs persist, so the nurse recognizes that ", post:".",
     opts:["the falling level means she is recovering and monitoring can be reduced","neurological recovery lags well behind the level, so hourly observation and serial levels must continue until she is clinically normal","the persisting tremor indicates a separate neurological problem needing imaging first","she can be discharged once the level is below 1.5 mmol/L"], ans:1},
    {pre:"Her level rises again to 2.8 mmol/L and she becomes more drowsy, so the nurse ", post:".",
     opts:["increases the intravenous fluid rate and continues hourly observation","gives a diuretic to enhance lithium excretion","restarts lithium at a lower dose to stabilize her mood","escalates immediately for urgent hemodialysis, since a rising level with neurological deterioration meets the criteria"], ans:3},
    {pre:"Before discharge the nurse's teaching priority is the sick day rule, which is ", post:".",
     opts:["to double the lithium dose when unwell so that the level does not fall","to stop all her medicines whenever she feels unwell","to keep drinking fluids, stop lithium and seek urgent advice during any illness with vomiting, diarrhea or fever, and to avoid non-steroidal anti-inflammatory drugs","to reduce the dose by half during any illness and restart when better"], ans:2},
    {pre:"Because she has been on lithium for six years, the nurse recognizes that her routine monitoring must include ", post:".",
     opts:["lithium levels only, since that is the drug being monitored","liver function tests, since lithium is hepatotoxic","an annual chest radiograph, since lithium causes pulmonary fibrosis","lithium levels every three months plus thyroid function, calcium, and kidney function, since lithium affects all three"], ans:3}]},
   rat:{c:"Neurological recovery lags hours to days behind the level, and in severe cases a persistent encephalopathy can follow — so a falling level never means monitoring can stop, and clinical normality is the endpoint. A level rising to 2.8 with increasing drowsiness meets the dialysis criteria outright and needs immediate escalation; a diuretic would worsen the volume depletion that is driving the toxicity. The sick day rule is the single most important piece of teaching in lithium care: keep drinking, stop the lithium and get urgent advice in any illness with vomiting, diarrhea or fever, and avoid non-steroidal anti-inflammatory drugs — this admission happened precisely because that rule was not applied. And long-term monitoring covers the level every three months plus thyroid, calcium and kidney function, because lithium causes hypothyroidism, hyperparathyroidism and nephropathy.",
   o:["A falling level does not mean recovery; neurological signs lag well behind.",
    "Correct — neurological recovery lags the level, so hourly observation and serial levels continue until she is clinically normal.",
    "Persisting tremor and ataxia are expected in toxicity and do not require imaging first.",
    "Discharge depends on clinical recovery, not on a level threshold alone.",
    "Increasing fluids alone is not enough when the criteria for dialysis are met.",
    "A diuretic worsens the volume depletion that is driving the toxicity.",
    "Restarting lithium during acute toxicity is unsafe.",
    "Correct — a rising level with neurological deterioration meets the dialysis criteria; escalate immediately.",
    "Doubling the dose during illness would be dangerous.",
    "Stopping every medicine is not the rule; the specific instruction concerns lithium and fluid intake.",
    "Correct — keep drinking, stop lithium and seek urgent advice in any illness with vomiting, diarrhea or fever, and avoid non-steroidal anti-inflammatory drugs.",
    "Halving the dose during illness is not the taught rule and leaves her exposed either way.",
    "Levels alone miss the three organ systems lithium damages.",
    "Lithium is not hepatotoxic; liver function testing is not the monitoring requirement.",
    "Lithium does not cause pulmonary fibrosis.",
    "Correct — levels every three months plus thyroid, calcium and kidney function, since lithium affects all three."],
   s:"Two things to know cold: neurological recovery lags the lithium level, so treat the client not the number; and the sick day rule — keep drinking, stop lithium, get advice, avoid NSAIDs. Long-term monitoring is level plus thyroid, calcium and kidneys."}}]})
;
