/* RN Ready — case study v2 · inferior STEMI with right ventricular infarction.
   Eleventh unfolding case: a 58-year-old diabetic woman presents with
   epigastric pain. Judgment unfolds from recognizing an atypical inferior
   infarct, through the V4R finding that makes nitrates dangerous, to the
   metformin-and-contrast trap after PCI.

   Wave 62 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-MI-01", title:"The Indigestion That Wasn't — Mrs. Nwosu, 58",
 setting:"Emergency department", sys:"CV", cn:"PHA", d:3, b:0.55,
 summary:"58-year-old woman with type 2 diabetes and hypertension, two hours of epigastric pain radiating to the jaw with nausea and sweating. Judgment unfolds from an atypical inferior infarct presentation, through the V4R elevation that makes nitrates dangerous, to door-to-wire timing and metformin after iodinated contrast.",
 exhibits:{
  history:{name:"History & Presentation", type:"text", body:"58-year-old woman. Symptoms began at 0630 while making breakfast: central epigastric discomfort she describes as 'bad indigestion', radiating to the jaw and between the shoulder blades, with nausea and cold sweating. She took an antacid with no relief. Arrives by ambulance at 0820, so 110 minutes from symptom onset. Medical history: type 2 diabetes on metformin 1000 mg twice daily, hypertension on amlodipine, 20 pack-year smoking history. No previous cardiac history. No known drug allergies."},
  vitals:{name:"Vital Signs (on arrival)", type:"kv", rows:[["Temperature","36.5 °C (97.7 °F)"],["Heart rate","48/min, regular"],["Respiratory rate","20/min"],["Blood pressure","88/56 mm Hg"],["SpO2 (room air)","94%"],["Capillary glucose","12.8 mmol/L (230 mg/dL)"],["Pain","7/10 epigastric and jaw"]]},
  ecg:{name:"Electrocardiogram — obtained 0826, six minutes after arrival", type:"text", body:"Rate 48/min, regular. ST-segment elevation of 3 mm in leads II, III and aVF. Reciprocal ST-segment depression in leads I and aVL. No ST elevation in the precordial leads. A right-sided electrocardiogram is obtained at 0834: 2 mm ST elevation in V4R. No conduction block, QRS duration 92 ms."},
  labs:{name:"Laboratory Results", type:"kv", rows:[["High-sensitivity troponin I","340 ng/L (99th centile upper limit 26 ng/L) — single sample at 0840"],["Potassium","4.1 mmol/L"],["Magnesium","0.9 mmol/L"],["Creatinine","96 µmol/L (1.09 mg/dL)"],["Hemoglobin","12.1 g/dL"],["Glucose","12.8 mmol/L"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. Aspirin 300 mg chewed now. 2. Ticagrelor 180 mg oral loading dose. 3. Unfractionated heparin bolus and infusion per protocol. 4. Activate the catheterization laboratory for primary percutaneous coronary intervention; door-to-wire target under 90 minutes. 5. Continuous electrocardiographic monitoring with defibrillator pads applied. 6. Right-sided electrocardiogram — obtained, V4R elevated. 7. AVOID nitrates and diuretics while right ventricular involvement is present. 8. Sodium chloride 500 mL bolus for systolic blood pressure below 90 mm Hg. 9. Atropine 500 mcg IV if symptomatic bradycardia persists. 10. Morphine 2 to 4 mg IV with metoclopramide for pain and nausea if analgesia is required. 11. Hold metformin for 48 hours after iodinated contrast and recheck renal function."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the history, vital signs and electrocardiogram. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","ecg","labs"],
   opts:["Her epigastric pain and nausea indicate gastritis, since women commonly present with gastrointestinal symptoms",
    "ST elevation in leads II, III and aVF with reciprocal depression indicates an inferior ST-elevation myocardial infarction",
    "A single troponin of 340 ng/L excludes infarction, since it would be far higher after two hours of symptoms",
    "The heart rate of 48/min indicates a primary bradyarrhythmia unrelated to the electrocardiogram changes"],
   ans:1,
   rat:{c:"ST elevation in II, III and aVF with reciprocal depression in I and aVL is an inferior ST-elevation myocardial infarction, and the troponin of 340 ng/L against a 99th centile of 26 confirms myocardial injury. Women, older adults and people with diabetes frequently present with epigastric pain, nausea and sweating rather than crushing chest pain — the atypical presentation is why the diagnosis is missed, not a reason to dismiss it. A single troponin cannot exclude anything, because the curve rises over hours; the electrocardiogram makes the diagnosis here. And the bradycardia is a consequence, not a coincidence: the right coronary artery supplies the sinoatrial and atrioventricular nodes in most people, so an inferior infarct commonly causes bradycardia.",
   o:["Atypical presentation is characteristic of women and diabetics — it is the reason this diagnosis is delayed, not evidence against it.",
    "Correct — inferior leads with reciprocal change is a STEMI, and the troponin confirms myocardial injury.",
    "A single troponin cannot exclude infarction; it rises over hours, and the ST elevation is already diagnostic.",
    "The right coronary artery supplies the nodal tissue, so bradycardia is an expected consequence of an inferior infarct."],
   s:"Inferior STEMI = ST elevation in II, III, aVF with reciprocal depression in I and aVL. Expect bradycardia and hypotension, and never dismiss epigastric pain in a woman with diabetes."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals","ecg","labs"],
   hotspot:{mode:"rows", rows:[
    "Blood pressure 88/56 mm Hg",
    "Heart rate 48/min",
    "ST elevation of 3 mm in leads II, III and aVF",
    "ST elevation of 2 mm in V4R",
    "Potassium 4.1 mmol/L",
    "Oxygen saturation 94% on room air"
   ], ans:[0,1,2,3]},
   rat:{c:"Hypotension, bradycardia, inferior ST elevation and — most consequentially — V4R elevation are all abnormal. The V4R finding is the one that changes treatment: ST elevation of 1 mm or more in V4R identifies right ventricular involvement, which occurs in roughly a third of inferior infarcts and makes the right ventricle preload dependent. Potassium at 4.1 mmol/L sits inside 3.5 to 5.0 and a saturation of 94% is acceptable — the two planted normals.",
   o:["Expected systolic blood pressure is above 90 to 100 mm Hg; 88 is hypotensive and symptomatic here.",
    "Expected heart rate is 60–100/min; 48 is bradycardic and expected with nodal ischemia.",
    "ST elevation of 3 mm in the inferior leads is diagnostic of infarction.",
    "V4R elevation of 1 mm or more indicates right ventricular involvement — the finding that dictates the next hour of care.",
    "Normal potassium is 3.5–5.0 mmol/L — within range.",
    "A saturation of 94% on room air is acceptable — within range."],
   s:"Always get a right-sided electrocardiogram in an inferior infarct. V4R elevation changes the treatment completely: the client becomes preload dependent and nitrates become dangerous."}},
  {step:"prioritize", t:"single", stem:"Her blood pressure is 88/56 mm Hg, her heart rate is 48/min and the pain continues. Which action by the nurse takes priority?",
   reveal:["history","vitals","ecg","labs","orders"],
   opts:["Give sublingual glyceryl trinitrate for the ongoing ischemic pain",
    "Give an intravenous sodium chloride bolus, since the infarct has made her preload dependent and volume is the treatment for this hypotension",
    "Give intravenous furosemide to reduce the workload on the failing ventricle",
    "Give intravenous morphine first, since pain control reduces catecholamine drive"],
   ans:1,
   rat:{c:"The V4R elevation means the right ventricle is failing as a conduit and can only maintain left ventricular filling if preload is high, so hypotension is treated with volume. Glyceryl trinitrate venodilates and drops preload, which in a right ventricular infarct can produce profound, refractory hypotension — this is the single most examinable contraindication in acute coronary care. Furosemide does exactly the same thing by diuresis. Morphine is reasonable adjunctive analgesia but it is not the priority over restoring perfusion pressure, and it also venodilates.",
   o:["Nitrates reduce preload; in a right ventricular infarct that causes profound hypotension and is contraindicated.",
    "Correct — a preload-dependent right ventricle needs volume, and a fluid bolus is the treatment for this hypotension.",
    "Diuretics reduce preload exactly as nitrates do and are equally dangerous here.",
    "Analgesia is adjunctive; restoring perfusion pressure comes first, and morphine itself venodilates."],
   s:"Right ventricular infarction: hypotension is treated with fluids, and nitrates, diuretics and morphine are all avoided because they reduce preload. V4R elevation is the warning sign."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["history","vitals","ecg","labs","orders"],
   opts:["Aspirin 300 mg chewed together with the prescribed P2Y12 inhibitor loading dose",
    "Activation of the catheterization laboratory with a door-to-wire target under 90 minutes",
    "Withholding nitrates and diuretics while the hypotension is treated with volume",
    "Continuous electrocardiographic monitoring with defibrillator pads applied",
    "Sublingual glyceryl trinitrate every five minutes until the pain settles"],
   ans:[0,1,2,3],
   rat:{c:"Dual antiplatelet loading, rapid transfer for primary percutaneous coronary intervention, avoidance of preload-reducing drugs and continuous monitoring with pads applied are all core to this presentation — the bradycardia and inferior infarct put her at real risk of complete heart block and ventricular arrhythmia. Repeated nitrates would be actively dangerous with V4R elevation, and the reflex to give them every five minutes is precisely the habit this case is testing.",
   o:["Correct — aspirin plus a P2Y12 inhibitor loading dose is standard before intervention.",
    "Correct — primary PCI within 90 minutes of arrival is the reperfusion target and saves myocardium.",
    "Correct — nitrates and diuretics are withheld while volume restores preload.",
    "Correct — inferior infarcts risk complete heart block and ventricular arrhythmia; pads must already be on.",
    "Repeated nitrates with V4R elevation risk profound refractory hypotension."],
   s:"STEMI bundle: dual antiplatelets, anticoagulation, primary PCI under 90 minutes, monitoring with pads — and in an inferior infarct, no nitrates until right ventricular involvement is excluded."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","ecg","labs","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Obtain the 12-lead electrocardiogram within ten minutes of arrival and attach continuous monitoring with pads",
     "Give aspirin 300 mg chewed, secure intravenous access and send the bloods including a troponin",
     "Give a sodium chloride bolus for the hypotension rather than a nitrate, and obtain the right-sided leads",
     "Transfer to the catheterization laboratory for primary percutaneous coronary intervention"],
    ans:[0,1,2,3]},
   rat:{c:"The electrocardiogram within ten minutes is the action that starts everything, because reperfusion timing runs from it and the pattern dictates the drugs. Antiplatelet therapy and access follow immediately. The right-sided leads then determine whether nitrates are safe, and the fluid bolus treats the hypotension in the meantime. Transfer for intervention comes last in sequence but is activated in parallel from the moment the electrocardiogram shows ST elevation — the sequence of nursing actions is not the sequence in which the catheterization team is called.",
   o:["The 12-lead within ten minutes drives every subsequent decision and starts the reperfusion clock.",
    "Aspirin, access and bloods follow immediately.",
    "Right-sided leads decide nitrate safety; the fluid bolus treats the hypotension meanwhile.",
    "Transfer for primary PCI — activated in parallel, but the nursing sequence reaches it last."],
   s:"Electrocardiogram within ten minutes is the first nursing action in suspected acute coronary syndrome. Everything else — drugs, right-sided leads, transfer — depends on what it shows."}},
  {step:"evaluate", t:"cloze", stem:"Primary percutaneous coronary intervention is completed with a stent to the right coronary artery. Four hours later her heart rate is 72/min, her blood pressure is 118/72 mm Hg and her pain has settled. Complete each evaluation statement.",
   reveal:["history","vitals","ecg","labs","orders"],
   cloze:{lines:[
    {pre:"Her rate and blood pressure have normalized and the pain has settled, so the nurse understands that ", post:".",
     opts:["the coronary problem is resolved and monitoring can be stepped down","she can be discharged once she has mobilized once","the absence of pain means the stent is patent without further observation","continuous monitoring continues, since stent thrombosis and arrhythmia remain real risks in the first 24 hours"], ans:3},
    {pre:"Because dual antiplatelet therapy has been started, the nurse teaches her that ", post:".",
     opts:["any bleeding should be reported, and neither agent must be stopped without cardiology advice, since stopping early risks stent thrombosis","she may stop the second agent if she develops bruising","the aspirin can be replaced by paracetamol if it upsets her stomach","she needs the second agent until the wound in her wrist has healed, then it can be stopped"], ans:0},
    {pre:"She takes metformin and has just received iodinated contrast, so the nurse's priority is to ", post:".",
     opts:["continue the metformin unchanged, since contrast has no renal effect","double the metformin dose to cover the stress hyperglycemia","hold the metformin for 48 hours and recheck renal function, because contrast-induced kidney injury can precipitate lactic acidosis","switch her to a sulfonylurea immediately so that her glucose stays controlled"], ans:2},
    {pre:"At discharge the nurse recognizes that the medicines most likely to improve her long-term survival after this infarct are ", post:".",
     opts:["a statin, a beta blocker, an angiotensin-converting enzyme inhibitor and dual antiplatelet therapy as prescribed","a proton pump inhibitor and an antacid for the epigastric symptoms","her amlodipine alone, since her blood pressure is now controlled","oral nitrate therapy for symptom relief whenever the pain returns"], ans:0}]},
   rat:{c:"A successful stent does not end the risk: stent thrombosis and arrhythmia both peak early, so monitoring continues regardless of how well she looks. Dual antiplatelet therapy after stenting is non-negotiable, and premature discontinuation is the strongest predictor of stent thrombosis — bleeding gets reported, not self-treated by stopping. Metformin is held for 48 hours after iodinated contrast because if contrast-induced kidney injury develops, metformin accumulates and precipitates lactic acidosis. And the bundle that actually improves survival is a statin, a beta blocker, an angiotensin-converting enzyme inhibitor and dual antiplatelet therapy — not symptom relief.",
   o:["The risk window has not passed; stent thrombosis and arrhythmia both peak in the first 24 hours.",
    "Mobilization is part of recovery, not a discharge criterion this early.",
    "Freedom from pain does not demonstrate stent patency or exclude arrhythmia risk.",
    "Correct — monitoring continues because a settled client can still thrombose or deteriorate.",
    "Correct — report bleeding, never stop either agent without cardiology advice; early cessation risks stent thrombosis.",
    "Bruising is reported, not managed by stopping an antiplatelet agent unilaterally.",
    "Paracetamol is not an antiplatelet substitute and would leave the stent unprotected.",
    "The P2Y12 inhibitor is continued for months, far beyond arterial access site healing.",
    "Contrast carries a real risk of acute kidney injury.",
    "Doubling metformin increases the exact risk that holding it is meant to prevent.",
    "Correct — hold metformin for 48 hours and recheck renal function; accumulation causes lactic acidosis.",
    "A sulfonylurea is not the immediate answer and does not address the lactic acidosis risk.",
    "Correct — statin, beta blocker, ACE inhibitor and dual antiplatelet therapy are the survival-changing bundle.",
    "Symptom medicines do not improve survival after infarction.",
    "Amlodipine alone is blood pressure control, not post-infarction secondary prevention.",
    "Nitrates relieve symptoms; they do not improve survival, and she must not self-treat recurrent pain."],
   s:"Two post-PCI traps: stopping dual antiplatelet therapy early causes stent thrombosis, and continuing metformin after iodinated contrast risks lactic acidosis if the kidneys take a hit. Hold it for 48 hours and recheck."}}]})
;
