/* RN Ready — case study v2 · oxygen-induced hypercapnia in COPD.
   Seventeenth unfolding case: a 69-year-old with severe COPD is given 15 L of
   oxygen by the paramedic and deteriorates. Judgment unfolds from the three
   mechanisms of oxygen-induced hypercapnia, through the 88-92% target and
   non-invasive ventilation, to intubation criteria and long-term oxygen
   assessment.

   Wave 65 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-COPD-01", title:"The Winter Worsening — Mr. Ogun, 69",
 setting:"Emergency department / respiratory unit", sys:"RESP", cn:"PHA", d:3, b:0.55,
 summary:"69-year-old with severe chronic obstructive pulmonary disease, three admissions last year, given 15 L/min oxygen by the paramedic and becoming drowsy with a rising carbon dioxide. Judgment unfolds from the mechanisms of oxygen-induced hypercapnia, through the 88 to 92% target and non-invasive ventilation, to intubation criteria and long-term oxygen assessment.",
 exhibits:{
  history:{name:"History", type:"text", body:"69-year-old man with severe chronic obstructive pulmonary disease — forced expiratory volume in one second 38% of predicted. Three hospital admissions in the last year, one requiring non-invasive ventilation. Forty pack-year smoking history; quit eight months ago. Medicines: tiotropium daily, salmeterol and fluticasone inhaler twice daily, salbutamol as required. Three days of increasing breathlessness, sputum volume up and turned green, and he can no longer walk to the end of his garden. No chest pain, no fever. Paramedic applied a 15 L/min non-rebreather mask en route."},
  vitals:{name:"Vital Signs", type:"kv", rows:[["Respiratory rate","28/min, accessory muscle use"],["SpO2 on arrival","99% on 15 L/min non-rebreather"],["Heart rate","112/min"],["Blood pressure","146/84 mm Hg"],["Core temperature","37.4 °C (99.3 °F)"],["Conscious level","Drowsy, difficult to rouse — was alert when the ambulance was called"],["Speech","Two-word phrases"]]},
  abg:{name:"Arterial Blood Gases", type:"kv", rows:[["Room air, before ambulance","pH 7.29 · PaCO2 9.4 kPa · PaO2 6.9 kPa · bicarbonate 32 mmol/L · base excess +6"],["On 15 L/min non-rebreather","pH 7.21 · PaCO2 11.2 kPa · PaO2 18.0 kPa · bicarbonate 33 mmol/L"],["Interpretation","Acute-on-chronic type 2 respiratory failure, worsened by uncontrolled oxygen"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. Reduce oxygen immediately and titrate to a saturation target of 88 to 92% using a Venturi mask. 2. Start non-invasive ventilation if the pH remains below 7.35 with a carbon dioxide above 6.5 kPa despite 30 to 60 minutes of optimal medical treatment. 3. Repeat arterial blood gas one hour after starting non-invasive ventilation, and immediately for any deterioration. 4. Nebulized salbutamol and ipratropium, driven by air rather than oxygen where possible. 5. Prednisolone 40 mg orally daily for five days. 6. Amoxicillin 500 mg three times daily given the purulent sputum. 7. Continuous pulse oximetry and cardiorespiratory monitoring. 8. NO sedatives or opioids. 9. Intensive care referral if consciousness falls, the pH drops below 7.25 or non-invasive ventilation fails. 10. Chest radiograph."}},
 items:[
  {step:"recognize", t:"single", stem:"He was alert when the ambulance was called and is drowsy on arrival with a saturation of 99% on 15 L/min. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","abg"],
   opts:["The high-flow oxygen has worsened his hypercapnia through ventilation-perfusion mismatch, the Haldane effect and a reduced hypoxic drive",
    "His drowsiness is due to exhaustion from the work of breathing and is unrelated to the oxygen therapy",
    "A saturation of 99% shows that his oxygenation is now well controlled and he is improving",
    "The rising carbon dioxide indicates that his chronic obstructive pulmonary disease has simply progressed"],
   ans:0,
   rat:{c:"The blood gases tell the story: carbon dioxide rose from 9.4 to 11.2 kPa and the pH fell from 7.29 to 7.21 while the oxygen partial pressure climbed to 18.0 kPa — the deterioration happened because of the oxygen, not despite it. Three mechanisms combine: high alveolar oxygen reverses hypoxic pulmonary vasoconstriction and sends blood to poorly ventilated alveoli, oxygenated hemoglobin releases carbon dioxide more readily through the Haldane effect, and the hypoxic ventilatory drive falls. The drowsiness is carbon dioxide narcosis. A saturation of 99% in a client with chronic type 2 failure is a danger signal, not a success — his bicarbonate of 32 shows he retains carbon dioxide chronically and depends on a lower oxygen set point.",
   o:["Correct — the three mechanisms of oxygen-induced hypercapnia explain the rising carbon dioxide and the drowsiness.",
    "Exhaustion contributes, but the timing and the gases point to the oxygen as the driver.",
    "A saturation of 99% in chronic type 2 failure is dangerous; the target is 88 to 92%.",
    "The rise happened over minutes with the oxygen, not over days with disease progression."],
   s:"In chronic type 2 respiratory failure, a saturation above the 88-92% target is a warning sign. Oxygen-induced hypercapnia works through ventilation-perfusion mismatch, the Haldane effect and reduced hypoxic drive — and it presents as drowsiness."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals","abg"],
   hotspot:{mode:"rows", rows:[
    "pH 7.21",
    "PaCO2 11.2 kPa",
    "PaO2 18.0 kPa on 15 L/min oxygen",
    "Conscious level drowsy and difficult to rouse",
    "Bicarbonate 33 mmol/L",
    "Core temperature 37.4 °C"
   ], ans:[0,1,2,3]},
   rat:{c:"The acidaemia, the marked hypercapnia, the excessive oxygen partial pressure and the falling conscious level are all abnormal — and the PaO2 of 18.0 kPa is abnormal in the opposite direction, which is the point of this case. The bicarbonate of 33 mmol/L is raised, but that is expected chronic metabolic compensation for long-standing carbon dioxide retention; it is not an acute abnormality and it is what tells you he is a chronic retainer. A temperature of 37.4 °C is within the normal range. Note what the raised bicarbonate means for the pH: his compensated baseline pH sits near the low end of normal, so a small acute rise in carbon dioxide drops him into acidaemia quickly.",
   o:["Expected arterial pH is 7.35–7.45; 7.21 is significant acidaemia.",
    "Expected PaCO2 is 4.7–6.0 kPa; 11.2 is severe hypercapnia.",
    "Expected PaO2 on room air is 11–13 kPa; 18.0 on oxygen means he is being over-oxygenated.",
    "Drowsiness in this context is carbon dioxide narcosis — a critical finding.",
    "A raised bicarbonate is expected chronic compensation in a carbon dioxide retainer, not an acute abnormality.",
    "Normal core temperature is about 36.1–37.2 °C; 37.4 is borderline but effectively within range."],
   s:"Read the bicarbonate to identify a chronic retainer, then read the pH to see how acute the change is. A high bicarbonate means the client compensates by retaining carbon dioxide — which is exactly why over-oxygenation is so dangerous."}},
  {step:"prioritize", t:"single", stem:"He is drowsy with a saturation of 99% on 15 L/min. Which action by the nurse takes priority?",
   reveal:["vitals","abg","orders"],
   opts:["Reduce the inspired oxygen and titrate to a saturation of 88 to 92%, then escalate immediately for senior review and non-invasive ventilation assessment",
    "Continue the 15 L/min, since a high saturation protects the brain and heart",
    "Give a nebulized salbutamol treatment driven by oxygen and reassess in thirty minutes",
    "Give a small dose of a benzodiazepine to settle his air hunger and reduce his work of breathing"],
   ans:0,
   rat:{c:"The oxygen is the cause of the deterioration, so reducing it to the 88 to 92% target is the immediate corrective action, and it must be paired with escalation because he has acidaemic type 2 failure that needs non-invasive ventilation. Maintaining 99% continues the harm. Nebulizers driven by oxygen add to the problem and should be driven by air where possible; a thirty-minute wait is also too long in a drowsy client. A benzodiazepine suppresses respiratory drive in someone already retaining carbon dioxide and can precipitate arrest — it is one of the clearest contraindications in respiratory nursing.",
   o:["Correct — reduce the oxygen to target and escalate for non-invasive ventilation; both actions are needed now.",
    "Maintaining 99% continues the mechanism that is causing his deterioration.",
    "Nebulizers should be driven by air in type 2 failure, and thirty minutes is too long in a drowsy client.",
    "Benzodiazepines suppress respiratory drive in carbon dioxide retention and can precipitate arrest."],
   s:"Two simultaneous actions in oxygen-induced hypercapnia: turn the oxygen down to 88-92%, and escalate for non-invasive ventilation. And never sedate the hypercapnic client."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["history","vitals","abg","orders"],
   opts:["Controlled oxygen titrated to a saturation of 88 to 92%, using a Venturi mask so the delivered concentration is known",
    "A systemic corticosteroid for five days and an antibiotic given the purulent sputum and increased volume",
    "Nebulized bronchodilators driven by air rather than oxygen where it is safe to do so",
    "Non-invasive ventilation if the acidaemia and hypercapnia persist after 30 to 60 minutes of optimal medical treatment",
    "High-flow oxygen maintained to keep the saturation above 96% while he is monitored"],
   ans:[0,1,2,3],
   rat:{c:"A Venturi mask delivers a known oxygen concentration, which matters because a nasal cannula or a non-rebreather cannot be titrated precisely — and precision is the whole treatment. An infective exacerbation with purulent, increased sputum gets a five-day corticosteroid course and an antibiotic. Nebulizers driven by air avoid adding to the oxygen load. Non-invasive ventilation is the evidence-based intervention for persistent acidaemic hypercapnia and it reduces mortality and intubation rates. Maintaining a saturation above 96% is the error that brought him in drowsy.",
   o:["Correct — a Venturi mask gives a known, titratable concentration, which nasal cannulae and non-rebreathers cannot.",
    "Correct — an infective exacerbation with purulent sputum warrants a corticosteroid and an antibiotic.",
    "Correct — air-driven nebulizers avoid adding to the oxygen load in a carbon dioxide retainer.",
    "Correct — non-invasive ventilation after 30 to 60 minutes of optimal treatment reduces mortality and intubation.",
    "A saturation above 96% is above target in chronic type 2 failure and is what caused this deterioration."],
   s:"COPD exacerbation bundle: titrated oxygen 88-92% via Venturi, corticosteroid, antibiotic if infective, air-driven nebulizers, and non-invasive ventilation if still acidaemic at 30-60 minutes."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","abg","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Reduce the inspired oxygen and titrate to a saturation of 88 to 92% with continuous monitoring",
     "Escalate for senior review, obtain a repeat arterial blood gas and arrange non-invasive ventilation",
     "Give the corticosteroid, the antibiotic and the air-driven nebulizers",
     "Prepare for possible intubation and intensive care transfer if non-invasive ventilation fails"],
    ans:[0,1,2,3]},
   rat:{c:"Turning the oxygen down comes first because it is the intervention that stops the ongoing harm and it takes seconds. Escalation with a repeat blood gas and non-invasive ventilation comes immediately after, since the acidaemia needs ventilatory support rather than more oxygen. The medical treatment follows and runs in parallel. Airway preparation and intensive care referral come last in sequence but are anticipated from the start — non-invasive ventilation fails in a significant minority, and a drowsy client is at particular risk of failing it.",
   o:["Reduce the oxygen to target — it takes seconds and stops the harm.",
    "Escalate, repeat the gas and arrange non-invasive ventilation.",
    "Corticosteroid, antibiotic and air-driven nebulizers.",
    "Prepare for intubation and transfer — anticipated early, executed if non-invasive ventilation fails."],
   s:"In oxygen-induced hypercapnia the first action is the cheapest: turn the oxygen down. Then escalate for ventilation, treat medically, and prepare for the non-invasive ventilation failure that happens in a significant minority."}},
  {step:"evaluate", t:"cloze", stem:"One hour into non-invasive ventilation his pH is 7.33, his carbon dioxide is 8.6 kPa and he is fully alert. Complete each evaluation statement.",
   reveal:["history","vitals","abg","orders"],
   cloze:{lines:[
    {pre:"His pH has risen from 7.21 to 7.33 and he is alert, so the nurse understands that ", post:".",
     opts:["non-invasive ventilation can be stopped immediately because he has improved","the non-invasive ventilation is working and should continue with a repeat gas in one to two hours and continued monitoring","he can be transferred to a general ward without monitoring","the carbon dioxide of 8.6 kPa means the ventilation settings should be increased aggressively"], ans:1},
    {pre:"Two hours later he becomes drowsy again with a pH of 7.22, so the nurse ", post:".",
     opts:["increases the oxygen to improve his conscious level","continues the current settings and rechecks in an hour, since drowsiness fluctuates","gives a sedative so that he tolerates the mask","escalates immediately, since a reduced conscious level with worsening acidaemia is a non-invasive ventilation failure criterion requiring intubation assessment"], ans:3},
    {pre:"Because his forced expiratory volume is 38% with three admissions in a year, the nurse recognizes that he should be assessed for ", post:".",
     opts:["long-term oxygen therapy and pulmonary rehabilitation, since both improve outcome in severe disease","nocturnal sedation to reduce his night-time breathlessness","permanent oral corticosteroids to prevent further admissions","complete avoidance of all physical activity"], ans:0},
    {pre:"Before discharge the nurse's teaching priority is ", post:".",
     opts:["checking his inhaler technique and providing a written exacerbation action plan, including when to start rescue medicines and seek help","stopping all inhalers once he feels well","using his reliever inhaler only when he cannot breathe at all","advice to resume smoking in moderation, since complete abstinence is unrealistic"], ans:0}]},
   rat:{c:"Improvement on non-invasive ventilation means continue and recheck — stopping as soon as the numbers look better invites relapse, and the blood gas is repeated in one to two hours. A reduced conscious level with worsening acidaemia is an explicit failure criterion and needs immediate escalation for intubation assessment; increasing oxygen or sedating him are both actively dangerous. A forced expiratory volume of 38% with three admissions is severe disease, and long-term oxygen therapy assessment for persistent hypoxaemia plus pulmonary rehabilitation are the two interventions with real outcome benefit. And at discharge, inhaler technique and a written action plan are the highest-yield teaching — most exacerbation deaths involve poor technique and late presentation.",
   o:["Stopping as soon as the gas improves invites relapse; weaning is gradual.",
    "Correct — continue non-invasive ventilation, repeat the gas in one to two hours and keep monitoring.",
    "A client on non-invasive ventilation for acidaemic failure needs monitored care, not a general ward.",
    "Aggressive increases are not indicated by one improving gas; settings are titrated to the trend.",
    "Increasing oxygen worsens the hypercapnia that is causing the drowsiness.",
    "Fluctuating drowsiness with a falling pH is deterioration, not normal variation.",
    "Sedation suppresses respiratory drive and is contraindicated in carbon dioxide retention.",
    "Correct — reduced consciousness with worsening acidaemia is a failure criterion; escalate for intubation assessment.",
    "Correct — long-term oxygen therapy for persistent hypoxaemia and pulmonary rehabilitation both improve outcome.",
    "Nocturnal sedation suppresses respiratory drive and is dangerous in type 2 failure.",
    "Permanent oral corticosteroids carry severe cumulative harm and are a last resort.",
    "Activity avoidance causes deconditioning and worsens outcome; rehabilitation is the opposite approach.",
    "Correct — inhaler technique and a written action plan are the highest-yield discharge teaching.",
    "Stopping inhalers when well is the commonest cause of the next exacerbation.",
    "Waiting until severe breathlessness delays treatment, which worsens outcome.",
    "He quit eight months ago; resuming smoking reverses the single most important thing he has done."],
   s:"Non-invasive ventilation failure criteria: reduced consciousness, pH under 7.25, worsening gases, or intolerance. Escalate for intubation — do not turn up the oxygen and do not sedate. At discharge it is inhaler technique, an action plan, rehabilitation and oxygen assessment."}}]})
;
