/* RN Ready — case study v2 · psychosocial (adolescent mental health). */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-PSY-01", title:"The Silent Withdrawal — Miss D., 16",
 setting:"Emergency department", sys:"PSYCH", cn:"PSY", d:2, b:0.4,
 summary:"16-year-old girl brought to the ED by her sister after being found with superficial wrist lacerations; assessment unfolds from cues to safety planning.",
 exhibits:{
  history:{name:"Triage Note", type:"text", body:"16-year-old girl, brought in by older sister. Found in her bedroom with superficial lacerations to the left wrist; sister reports a bullying situation at school that has escalated over 2 months. No prior psychiatric history, no medical problems. Parents work evenings and are on their way."},
  vitals:{name:"Vital Signs", type:"kv", rows:[["Temperature","36.8 °C"],["Heart rate","104/min"],["Blood pressure","108/66 mm Hg"],["Respiratory rate","18/min"],["SpO2 (room air)","99%"]]},
  notes:{name:"Nurse's Observations", type:"text", body:"2200: Sits with knees drawn up, avoids eye contact, answers in single words. Wrist dressed with sterile strips. When asked how she is doing, shrugs and says “it doesn't matter anymore.” Sister reports the client gave away her guitar last week and has been sleeping 11–12 hours but says she is still exhausted. 2230: Client states, “The stuff in my head says I'm a burden.” Denies pain."},
  labs:{name:"Screening Results", type:"kv", rows:[["Urine drug screen","Negative"],["Serum ethanol","Negative"],["Electrolytes","Within reference range"],["Pregnancy test","Negative"]]},
  psych:{name:"Mental Status", type:"text", body:"Alert and oriented. Mood “numb,” affect flat. Speech slow, low volume. Denies hearing voices speaking aloud but describes an internal critical “voice-like” thought. Thought content: “I'm a burden; they'd be fine without me.” Judgement limited by current state. Insight partial."}},
 items:[
  {step:"recognize", t:"single", stem:"Which reported finding most strongly indicates risk for self-directed violence and must guide the plan of care?",
   reveal:["history","notes"],
   opts:["Superficial lacerations with the statement “it doesn't matter anymore”","Mild tachycardia of 104/min","The bullying situation at school","Sleeping 11–12 hours per night"],
   ans:0,
   rat:{c:"Self-injury (even superficial) combined with a passive death-wish statement is the highest-yield risk cue — it demands immediate suicide-risk assessment and safety precautions. The others are context or contributing factors, not the sentinel finding.",
   o:["Correct — self-harm + hopelessness language is the priority cue.","Explained by pain/anxiety — nonspecific.","Important context but not the sentinel risk marker.","A neurovegetative sign — relevant, secondary."],
   s:"Recognize: separate the LIFE-THREAT cue (self-harm + death statements) from context (bullying) and physiologic noise (mild tachycardia)."}},
  {step:"analyze", t:"hotspot", stem:"Tap to highlight each finding in the notes that elevates this client's suicide risk.",
   reveal:["notes","labs"],
   hotspot:{mode:"rows", rows:["Gave away a prized possession (guitar) last week","States “it doesn't matter anymore”","Describes internal “voice-like” thoughts calling her a burden","Urine drug screen negative","Sleeping 11–12 hours but still exhausted","Parents work evenings; client is frequently alone in the evening"], ans:[0,1,2,4,5]},
   rat:{c:"Preparatory behavior (giving away possessions), hopelessness, self-critical internal voice, hypersomnia with fatigue, and evening isolation all raise risk. A negative drug screen neither raises nor lowers suicide risk.",
   o:["Preparatory/bye behavior: risk.","Hopelessness: risk.","Pathologic self-critical cognition: risk.","Irrelevant to risk: distractor.","Neurovegetative depression change: risk.","Access to means + isolation window: risk."],
   s:"Risk analyzers: ideation + plan + means + intent + preparatory acts + isolation + substance use + recent loss. Negatives (clean UDS) are distractors."}},
  {step:"prioritize", t:"single", stem:"Which nursing problem is the priority for this client right now?",
   reveal:["history","notes","psych"],
   opts:["Risk for self-directed violence","Ineffective coping","Social isolation","Chronic low self-esteem"],
   ans:0,
   rat:{c:"Safety outranks all psychosocial alternatives: until self-harm risk is assessed and controlled, every other intervention is premature (Maslow: safety first).",
   o:["Correct — life and safety take precedence.","Real, but downstream of safety.","Real, but downstream.","Real, but downstream."],
   s:"When “risk for self-harm” is an option for a client who has just self-injured, it is the priority — full stop."}},
  {step:"generate", t:"multi", stem:"Which interventions should be part of the immediate safety plan? Select all that apply.",
   reveal:["notes","psych"],
   opts:["Initiate 1:1 observation with the client kept within arm's reach","Remove or secure sharps, cords, belts, and medications from the care area","Complete a validated suicide risk assessment (ideation, plan, means, intent)","Agree to keep everything the client says confidential from her parents","Leave the room door closed and lights off to reduce stimulation"],
   ans:[0,1,2],
   rat:{c:"Observation within reach, environmental removal of means, and formal risk assessment are the evidence-based immediate steps. Promising secrecy from guardians is impossible to keep in self-harm cases, and an isolated dark room removes observation precisely when supervision matters.",
   o:["Correct — line-of-sight/arm's-reach supervision prevents self-harm.","Correct — means restriction is the strongest environmental protection.","Correct — a structured assessment (e.g., Columbia scale) drives disposition.","Never promise secrecy about self-harm — explain the limits of confidentiality honestly.","Isolation reduces exactly the supervision the client needs."],
   s:"Safety plan = observe + remove means + assess + honest confidentiality limits. Distractors play on privacy instincts that are unsafe here."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["notes","psych"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Ensure immediate safety: initiate suicide precautions and 1:1 observation","Complete the formal suicide risk assessment (plan, means, intent, protective factors)","Notify the provider and request behavioral health consultation","Support the client and family: honest communication and preparation for the care plan"],
    ans:[0,1,2,3]},
   rat:{c:"Safety precedes assessment; structured assessment informs escalation (provider/psych consult); family support and planning follow the acute controls.",
   o:["Supervision and means control come before anything else.","Assessment drives level of care and disposition.","Escalation mobilizes definitive mental health care.","Engagement and education come once safety is controlled."],
   s:"Mental health emergencies follow the same logic as medical ones: secure safety → assess → escalate → communicate."}},
  {step:"evaluate", t:"cloze", stem:"At 0600 the client is conversing with her sister, made eye contact during the assessment, states she does not want to die, and agrees to work on a safety plan. Complete the evaluation.",
   reveal:["notes","psych"],
   cloze:{lines:[
    {pre:"The client's stated intent has", post:"compared with arrival.", opts:["improved","worsened"], ans:0},
    {pre:"Her engagement (eye contact, conversation) has", post:".", opts:["improved","worsened"], ans:0},
    {pre:"Before any discharge decision, the team must", post:".", opts:["complete a safety plan and arrange mental health follow-up","send her home with printed information","wait to see if symptoms return"], ans:0}]},
   rat:{c:"Reduced intent and improved engagement indicate positive response, but evaluation in suicide care is procedural: a formal safety plan (warning signs, coping steps, contacts, means restriction) plus scheduled mental health follow-up must exist before discharge.",
   o:["“Doesn't want to die” = decreased intent.","Observable behavioral improvement.","Correct — safety plan + follow-up are the discharge gate; information alone or watchful waiting is insufficient."],
   s:"Evaluate against the plan you set: safety maintained → risk assessed → supports arranged. Improvement never skips the safety-planning step."}}]}
);
