/* RN Ready — case study v2 · long-term care (PN-scope).
   Sixth unfolding case, authored for PN depth: an assisted-living resident's
   subtle deterioration (delirium from urinary source + dehydration) is caught,
   escalated to the supervising RN, managed within practical-nurse scope, and
   prevented from recurring. fam:"PN" makes PN simulations prefer this case;
   it remains fully usable by any exam.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-LTC-01", title:"The Quiet Resident — Mr. B., 84",
 setting:"Assisted living / long-term care", sys:"NEURO", cn:"MOC", d:2, b:0.25, fam:"PN",
 summary:"84-year-old retired teacher, normally a chatty walker-of-the-halls, becomes quietly confused and starts falling; judgment unfolds from noticing the change to escalating within scope and preventing the next episode.",
 exhibits:{
  history:{name:"Care Team Note", type:"text", body:"84-year-old man, assisted living for 3 years after his wife's death. Mild baseline forgetfulness (“loses his glasses, not his way”), walks the halls daily, leads the morning crossword group. History: benign prostatic hyperplasia, hypertension, osteoarthritis. Medications: lisinopril 10 mg daily, tamsulosin 0.4 mg nightly, acetaminophen 650 mg as needed. Advance directive on file; daughter is emergency contact. Over the last two days, staff note he has skipped the crossword group, napped through lunch, and twice been found at the wrong apartment door after sundown."},
  vitals:{name:"Vital Signs (today vs. usual)", type:"kv", rows:[["Temperature","37.7 °C (99.9 °F) — usually 36.4"],["Heart rate","96/min — usually 68"],["Blood pressure","106/64 mm Hg — usually 138/82"],["Respiratory rate","18/min"],["SpO2 (room air)","96%"],["Weight","Down 1.8 kg in 5 days"]]},
  focused:{name:"Focused Findings", type:"text", body:"States the year as “nineteen seventy-something.” Holds a conversation but drifts to sleep mid-sentence. Mucous membranes dry; urine in the collection bottle is dark amber with a strong odor; he says passing water “burns lately.” Report from the medication record: acetaminophen taken 3 days running for “ache all over.” No cough, no chest pain, no new limb weakness. Gait slower than baseline; one near-fall this morning when he stood to greet the nurse."},
  orders:{name:"Supervising RN Directions", type:"text", body:"After the practical nurse reports, the supervising RN issues directions pending provider callback: 1. Encourage oral fluids to 1500 mL today unless the provider limits intake. 2. Offer a commode and scheduled toileting every 2 hours while awake. 3. Report a morning urine sample for urinalysis and culture when the courier arrives. 4. Continue acetaminophen 650 mg as needed for the aches. 5. Move the resident closer to the nursing station for this shift. 6. Check blood pressure and mental status every 4 hours. 7. Apply a fall-prevention wristband and low-bed position. 8. Hold tonight's tamsulosin dose pending provider review. 9. Family contact: daughter to be called by the RN."},
  reassess:{name:"Reassessment — Next Morning", type:"kv", rows:[["Temperature","36.9 °C (98.4 °F)"],["Heart rate","74/min"],["Blood pressure","128/78 mm Hg"],["Urine","Lighter yellow; burns less; voiding every 3 hours"],["Mental status","States the year correctly; attended crossword group"],["Oral intake","1350 mL yesterday; 400 mL so far today"],["Weight","Up 0.6 kg from yesterday"]]}},
 items:[
  {step:"recognize", t:"single", stem:"Which cluster of findings in this resident most strongly signals an acute change of condition requiring same-day escalation?",
   reveal:["history","vitals","focused"],
   opts:["New confusion with low-grade fever, dark malodorous urine, dysuria, and a 1.8 kg weight drop",
    "Skipping crossword group and napping, after three years of the same routine",
    "Mild baseline forgetfulness such as misplacing his glasses",
    "Slower gait with one near-fall in the morning"],
   ans:0,
   rat:{c:"The sentinel cluster is acute: mental-status change + fever + concentrated malodorous urine with dysuria + weight loss pointing to dehydration and a urinary source. Routine-pattern changes, lifelong baseline forgetfulness, and slowing gait are context — each alone might warrant watching, but together with the others they form the picture the practical nurse reports now.",
   o:["Correct — infection picture plus dehydration plus delirium is a report-now combination.",
    "Behavioral drift is the earliest soft sign — it matters because it is NEW, but it is not the strongest cluster alone.",
    "Stable baseline forgetfulness is his normal, not a change.",
    "A single near-fall joins the cluster; isolated, it triggers fall protocol rather than urgent escalation."],
   s:"Change-of-condition eyes: compare everything to THIS resident's baseline. New + multiple systems = report today, not trend for a week."}},
  {step:"analyze", t:"hotspot", stem:"The supervising RN asks the practical nurse to gather focused data before the provider callback. Highlight every item below that belongs in that report.",
   reveal:["focused","vitals"],
   hotspot:{mode:"rows", rows:[
    "Baseline mental status versus today's (year, alertness, drifting to sleep)",
    "Hydration data: dry membranes, intake, urine color and output",
    "Urinary symptoms: burning on urination and malodorous dark urine",
    "The resident's preferred crossword puzzle difficulty",
    "Medication record acetaminophen use pattern and 'ache all over' report",
    "Which television programs the resident watches in the evening"
   ], ans:[0,1,2,4]},
   rat:{c:"The report to the RN carries decision-driving data: mental-status trajectory, hydration markers, urinary symptoms, and the antipyretic-use pattern that corroborates feeling unwell. Entertainment preferences are person-centered care details — valuable for care planning, not for an acute callback.",
   o:["Correct — cognitive trajectory against baseline is the core datum.",
    "Correct — volume status shapes the urgency and the fluid plan.",
    "Correct — localizing symptoms point the workup.",
    "Preference details do not change acute decision-making.",
    "Correct — self-medicated acetaminophen documents three days of feeling unwell.",
    "Evenings-viewing habits are routine-life data, not escalation data."],
   s:"Escalation reports carry CHANGE + TRAJECTORY + LOCALIZING data. Person-centered details prove you know the resident — they do not page a provider."}},
  {step:"generate", t:"multi", stem:"While awaiting the provider callback, which actions are within the practical nurse's scope for this resident? Select all that apply.",
   reveal:["history","focused","orders"],
   opts:["Encouraging oral fluids toward the RN's 1500 mL goal and offering the commode on a 2-hour schedule",
    "Checking blood pressure and mental status every 4 hours and reporting readings outside the parameters given",
    "Starting an antibiotic left in the emergency kit so treatment is not delayed",
    "Applying the fall-prevention wristband and keeping the bed in the low position",
    "Calling the daughter to explain the working diagnosis and the plan"],
   ans:[0,1,3],
   rat:{c:"Scope during escalation: implement the RN's supportive directions (fluids, toileting, scheduled monitoring with defined report parameters, fall precautions). Starting antibiotics requires a provider order — emergency kits do not create independent prescribing authority — and family notification about diagnosis belongs to the RN, who the plan assigns that call.",
   o:["Correct — carrying out the hydration and toileting plan is practical-nurse practice.",
    "Correct — monitoring with parameter-based reporting is a core delegated surveillance role.",
    "No order, no antibiotic — kit availability does not enlarge scope.",
    "Correct — fall-prevention measures are standard protective care.",
    "The daughter call and diagnosis discussion belong to the RN per the plan — practical nurses reinforce afterward."],
   s:"Scope during a sick resident: carry out, monitor, protect, report. Prescribing and diagnosis disclosure stay upstream."}},
  {step:"act", t:"emr", stem:"Review the RN's directions. Open each panel and select the items to carry out during this shift, the item needing clarification before acting, and the item that is the RN's own responsibility.",
   reveal:["orders"],
   groups:[
    {h:"Carry out this shift", opts:["Fluid goal 1500 mL with encouragement and intake tracking","Scheduled toileting every 2 hours with commode access","Collect and report the morning urine sample","Blood pressure and mental status checks every 4 hours","Fall-prevention wristband and low bed"], ans:[0,1,2,3,4]},
    {h:"Clarify before acting", opts:["Hold tonight's tamsulosin pending provider review"], ans:[0]},
    {h:"RN's own responsibility", opts:["Calling the daughter to discuss the situation"], ans:[0]}],
   rat:{c:"Hydration, toileting, specimen handling, scheduled monitoring with parameters, and fall precautions are all executable this shift. 'Hold tonight's tamsulosin pending review' deserves one clarifying question — why this drug is held (the hypotension contribution) documents rationale and confirms timing — while the family call is explicitly retained by the RN in the written directions.",
   o:["Correct — the fluid plan is the treatment backbone here.","Correct — scheduled elimination supports both comfort and assessment.","Correct — the specimen anchors the diagnosis.","Correct — surveillance with report parameters is delegated monitoring.","Correct — fall mitigation is basic protective care.",
    "Correct — clarifying the hold's rationale and timing is professional communication, not insubordination.",
    "Correct — the plan assigns family contact to the RN; the practical nurse reinforces later."],
   s:"Order triage: execute the supportive set now, clarify orders whose rationale or timing is unclear, and hand the communication tasks to their owner."}},
  {step:"evaluate", t:"single", stem:"The next morning, review the reassessment panel. Which conclusion is best supported?",
   reveal:["reassess","orders"],
   opts:["Improved mentation with cooling temperature, rising pressure, lighter urine, and weight recovery indicates the plan is working",
    "A blood pressure of 128/78 proves the infection has fully resolved and monitoring can stop",
    "Attendance at crossword group means mental-status checks are no longer needed",
    "The 0.6 kg weight gain signals fluid overload and the fluid goal should stop immediately"],
   ans:0,
   rat:{c:"Every tracked measure moved toward baseline together — orientation returning, temperature and heart rate normalizing, blood pressure recovering (his hypotension was volume-driven), urine clearing, and weight rebounding toward his dry norm. That vector says the dehydration-and-infection plan is working. Full resolution awaits culture results and sustained trend; one good morning does not retire mental-status checks; and a 0.6 kg gain toward baseline is recovery, not overload.",
   o:["Correct — the whole vector, not one number, supports the conclusion.",
    "Normal pressure reflects volume restoration — the culture decides the infection question.",
    "One oriented morning is encouraging; monitoring continues per the plan until directed otherwise.",
    "Weight rising toward his usual range with clear lungs is rehydration, not overload."],
   s:"Evaluation reads the TREND ACROSS PARAMETERS against the resident's baseline — orientation, temperature, pressure, urine, weight — before any single number is trusted."}},
  {step:"reflect", t:"cloze", stem:"The resident stabilizes, and the team plans prevention with the family. Complete each teaching point.",
   reveal:["history","reassess"],
   cloze:{lines:[
    {pre:"To protect against another dehydration episode, the family should ", post:" during visits and warm weather.",
     opts:["offer drinks regularly and watch for darker urine","limit fluids to prevent bathroom falls","rely on thirst alone as the trigger to drink","serve salty broth instead of water"], ans:0},
    {pre:"The earliest signal to report next time is ", post:" — before falls or fever appear.",
     opts:["a change in thinking or behavior from his normal","a full day of refusing all fluids","a completed fall with injury","a fever above 39 °C"], ans:0},
    {pre:"Infection prevention for this resident includes ", post:" related to his prostate condition.",
     opts:["reporting new burning or urine changes promptly","restricting bathroom access overnight","stopping his prescribed medications during good weeks","avoiding all reporting until symptoms worsen"], ans:0}]},
   rat:{c:"Prevention teaching: scheduled offering of fluids (thirst fails in age) with urine color as the family's gauge; the earliest reportable change is any departure from HIS cognitive and behavioral baseline; and urinary symptoms in a man with prostate disease are reported early — retention and infection travel together in this population.",
   o:["Correct — routine offering plus a simple visual gauge beats relying on thirst.","Fluid restriction to prevent falls trades a fall risk for a crisis risk.","Aged thirst perception lags behind need — waiting on it courts dehydration.","Salty broth adds sodium load without plain-water hydration.",
    "Correct — in older adults, quiet confusion IS the early fever.","Total refusal for a full day is late, not early.","A completed fall is the failure of early reporting, not the trigger.","High fever is hours-to-days late — cognition changes first.",
    "Correct — early urinary reporting intercepts infection and retention early.","Bathroom restriction overnight worsens retention and fall risk.","Good weeks do not pause prescribed therapy.","Waiting for worsening guarantees a worse handoff."],
   s:"Prevention triplet for the family: offer fluids on a schedule (never wait on thirst), report any thinking-or-behavior drift from normal, and never sit on urinary symptoms."}}]}
);
