/* RN Ready — case study v2 · major flame burn with inhalation injury.
   Fifteenth unfolding case: a 31-year-old with a 36% flame burn, soot in the
   sputum and a circumferential arm burn. Judgment unfolds from recognizing
   that the airway outranks both the fluid calculation and the pulseless limb,
   through Parkland timing and the urine output endpoint, to fluid creep.

   Wave 64 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-BURN-01", title:"The Kitchen Fire — Amaka, 31",
 setting:"Emergency department / burns centre", sys:"INTG", cn:"PAA", d:3, b:0.55,
 summary:"31-year-old woman, 60 kg, flame burns from a gas flare-up 90 minutes ago covering 36% of total body surface area, with singed nasal hair, hoarseness, soot in the sputum and a circumferential right arm burn with no palpable radial pulse. Judgment unfolds from airway priority over fluid and limb, through Parkland timing and the urine output endpoint, to fluid creep.",
 exhibits:{
  history:{name:"History", type:"text", body:"31-year-old woman, 60 kg. A gas flare-up in an enclosed kitchen 90 minutes ago. Flame burns to the anterior chest and abdomen, both anterior arms and the anterior right thigh. Singed nasal hair, hoarse voice, and she has coughed up soot-stained sputum. No loss of consciousness. Cooled the burns under a tap for about five minutes, then applied a clean sheet. No known allergies; tetanus status uncertain. Non-smoker, no regular medicines."},
  vitals:{name:"Vital Signs (on arrival)", type:"kv", rows:[["Heart rate","128/min"],["Blood pressure","96/60 mm Hg"],["Respiratory rate","26/min"],["SpO2","94% on 15 L/min via non-rebreather mask"],["Core temperature","36.1 °C (97.0 °F)"],["Glasgow Coma Scale","15 (E4 V5 M6)"],["Pain","9/10"],["Capillary refill","2 seconds"]]},
  assessment:{name:"Burn Assessment", type:"text", body:"Using the rule of nines: anterior chest 9%, abdomen 9%, both anterior arms 4.5% each = 9%, anterior right thigh 9% — total 36% of body surface area. Mostly partial thickness, with deeper areas over the anterior chest. The right arm burn is circumferential; the radial pulse is not palpable and is absent on handheld Doppler, with increasing pain and paraesthesia in the hand. Voice hoarse but she is speaking in full sentences. Stridor not yet present. Carboxyhemoglobin level sent."},
  orders:{name:"Provider Orders", type:"text", body:"1. 100% oxygen via non-rebreather; carboxyhemoglobin level. 2. Urgent anaesthetic review — early intubation for suspected inhalation injury. 3. Nil by mouth. 4. Parkland formula: 4 mL x weight in kg x % total body surface area over 24 hours, with HALF given in the first 8 hours calculated FROM THE TIME OF THE BURN. 5. Urinary catheter; target urine output 0.5 to 1 mL/kg/hour as the resuscitation endpoint. 6. Two large-bore cannulae through unburned skin where possible. 7. Intravenous analgesia titrated — not intramuscular. 8. Tetanus prophylaxis. 9. Keep the client warm; do not apply ice. 10. Urgent surgical review of the circumferential arm burn for escharotomy."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the assessment. Which finding requires the most immediate escalation?",
   reveal:["history","vitals","assessment"],
   opts:["Singed nasal hair, hoarseness and soot in the sputum, indicating an inhalation injury with airway swelling that is still progressing",
    "A total burn surface area of 36%, which requires calculated fluid resuscitation",
    "The absent radial pulse in the circumferentially burned right arm",
    "A pain score of 9/10 that requires titrated intravenous analgesia"],
   ans:0,
   rat:{c:"All four findings matter, and this is a genuine ordering problem rather than a recognition one — but the airway wins. Upper airway edema after inhalation injury progresses over hours, and a client who is speaking comfortably now can become un-intubatable within a short time, so early intubation while the anatomy is still recognizable is the intervention that cannot be recovered later. The 36% burn drives the fluid calculation, which is urgent but measured in hours. The pulseless circumferential arm needs an escharotomy urgently to save the limb, but a limb is not a life. Analgesia is essential and is given alongside, not before.",
   o:["Correct — airway edema progresses and a client who is comfortable now can become un-intubatable; this cannot wait.",
    "The fluid calculation is urgent but runs over hours; the airway closes in minutes to a few hours.",
    "An escharotomy is needed urgently to save the limb, but a limb does not outrank an airway.",
    "Analgesia is essential and given in parallel; it is never the reason to delay airway management."],
   s:"In burns, rank by airway, then breathing and circulation, then limb. Inhalation injury signs — singed nasal hair, hoarseness, soot in sputum, enclosed-space exposure — mean intubate early, because waiting costs you the airway."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that indicates an inhalation injury or an airway at risk.",
   reveal:["history","vitals","assessment"],
   hotspot:{mode:"rows", rows:[
    "Singed nasal hair",
    "Hoarse voice",
    "Soot in the sputum",
    "Respiratory rate 26/min with a saturation of 94% on 15 L/min oxygen",
    "Glasgow Coma Scale 15",
    "Capillary refill 2 seconds"
   ], ans:[0,1,2,3]},
   rat:{c:"Singed nasal hair, hoarseness and soot in the sputum are the classic triad of inhalation injury, and a respiratory rate of 26/min with a saturation of only 94% on 15 litres of oxygen shows that gas exchange is already impaired — she is hypoxemic despite near-maximal inspired oxygen. Exposure in an enclosed kitchen compounds the risk of carbon monoxide poisoning. A Glasgow Coma Scale of 15 and a capillary refill of 2 seconds are both normal, and are there to remind you that a client can look entirely well while the airway is closing. Two planted normals.",
   o:["Singed nasal hair indicates heat and particulate exposure to the upper airway.",
    "Hoarseness indicates laryngeal involvement and swelling — an early warning of obstruction.",
    "Soot in the sputum means particulate matter has reached below the vocal cords.",
    "A saturation of 94% on 15 L/min is impaired gas exchange, not a normal result.",
    "A Glasgow Coma Scale of 15 is normal — and a normal score does not mean a safe airway.",
    "Normal capillary refill is 2 seconds or less — within range."],
   s:"The inhalation injury triad is singed nasal hair, hoarseness and sooty sputum — add enclosed-space exposure and any hypoxemia despite high inspired oxygen. A normal conscious level does not mean a safe airway."}},
  {step:"prioritize", t:"single", stem:"The anaesthetist is en route and she is still speaking in full sentences. Which action by the nurse takes priority?",
   reveal:["history","vitals","assessment","orders"],
   opts:["Prepare for early intubation and keep her nil by mouth, since airway swelling progresses and intubation becomes far harder later",
    "Calculate and start the fluid resuscitation first, since a 36% burn causes rapid hypovolaemia",
    "Give a salbutamol nebulizer to treat the wheeze caused by the smoke inhalation",
    "Arrange transfer to the burns centre before doing anything else"],
   ans:0,
   rat:{c:"Preparing the airway now, while she is still easy to intubate, is the priority — the swelling does not wait for the anaesthetist, and a failed airway in an edematous burn patient is one of the hardest emergencies in medicine. Nil by mouth supports safe intubation. Fluid resuscitation is the second priority and is started in parallel, but it cannot rescue an obstructed airway. Salbutamol treats bronchospasm and may be needed, but it does nothing for upper airway edema and it delays the real intervention. Transfer to a burns centre is required but only after the airway is secure — you do not put an unstable airway in an ambulance.",
   o:["Correct — secure the airway while it is still secureable; swelling progresses and later attempts may fail.",
    "Fluid resuscitation runs in parallel, but it cannot rescue an obstructed airway.",
    "Salbutamol treats bronchospasm, not upper airway edema, and must not delay airway preparation.",
    "Transfer happens after the airway is secure; an unstable airway does not travel in an ambulance."],
   s:"Intubate the inhalation injury early. Once the airway is swollen, intubation becomes a surgical problem. Fluids matter, but they are the second priority and they run alongside."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["history","vitals","assessment","orders"],
   opts:["Fluid calculated as 4 mL x 60 kg x 36%, with half delivered in the first 8 hours counted from the time of the burn rather than from arrival",
    "A urinary catheter with an hourly urine output target of 0.5 to 1 mL/kg/hour as the resuscitation endpoint",
    "Continuing 100% oxygen and reviewing the carboxyhemoglobin level, since pulse oximetry reads falsely normal in carbon monoxide poisoning",
    "Titrated intravenous analgesia rather than intramuscular, since muscle absorption is unreliable in a shocked client",
    "Applying ice packs to the burned areas to limit the depth of injury"],
   ans:[0,1,2,3],
   rat:{c:"The Parkland calculation is 4 x 60 x 36 = 8640 mL over 24 hours, half of which — 4320 mL — goes in the first 8 hours, and those 8 hours run from the time of the burn, not from arrival; she arrived 90 minutes after injury, so 6.5 hours of that window remain. Urine output is the endpoint that guides rate, not a fixed volume. Pulse oximetry cannot distinguish carboxyhemoglobin from oxyhemoglobin, so the saturation of 94% is falsely reassuring and the level must be measured. Intramuscular injections are absorbed erratically once perfusion is compromised. Ice causes vasoconstriction that deepens the burn and adds hypothermia — cool running water for 20 minutes is the correct first aid, and she only managed five.",
   o:["Correct — the 8-hour half runs from the time of the burn, so arrival time must be subtracted.",
    "Correct — hourly urine output, not a fixed volume, is the endpoint that titrates resuscitation.",
    "Correct — pulse oximetry cannot detect carboxyhemoglobin, so the reading is falsely reassuring.",
    "Correct — intramuscular absorption is unreliable in shock; intravenous titration is safe and effective.",
    "Ice causes vasoconstriction that deepens the injury and adds hypothermia; cool running water for 20 minutes is correct."],
   s:"Parkland timing runs from the time of the burn, not from arrival — subtract the prehospital delay. Urine output titrates the rate. And never ice a burn: 20 minutes of cool running water is the only first aid that helps."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","assessment","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Give 100% oxygen, assess the airway and prepare the equipment for early intubation",
     "Site two large-bore cannulae through unburned skin and start the calculated fluid resuscitation",
     "Catheterize, set the hourly urine output target and send the carboxyhemoglobin level",
     "Escalate the absent radial pulse for urgent escharotomy review"],
    ans:[0,1,2,3]},
   rat:{c:"Oxygen and airway preparation come first because inhalation injury is the immediate threat to life and the window to intubate electively is closing. Access and fluid follow immediately, using unburned skin where possible because cannulation through burned tissue infects easily. The catheter and carboxyhemoglobin level come next, since the urine output is the endpoint that guides the fluid and the level determines how long 100% oxygen continues. The pulseless limb is escalated last in this sequence but is not forgotten — an escharotomy is time-critical for the limb, and it is requested early even though the airway and circulation are managed first.",
   o:["Oxygen, airway assessment and intubation preparation — the threat to life comes first.",
    "Access through unburned skin and the calculated fluid resuscitation.",
    "Catheter for the endpoint, and the carboxyhemoglobin level to guide oxygen therapy.",
    "Escharotomy review for the pulseless circumferential burn — time-critical for the limb."],
   s:"Burn sequence: airway and oxygen → access and calculated fluid → catheter and carboxyhemoglobin → limb. Request the escharotomy early even though it comes last."}},
  {step:"evaluate", t:"cloze", stem:"Four hours into resuscitation her urine output is 15 mL/hour. Her carboxyhemoglobin returns at 18%. The right arm remains pulseless on Doppler with increasing pain. Complete each evaluation statement.",
   reveal:["history","vitals","assessment","orders"],
   cloze:{lines:[
    {pre:"Her urine output is 15 mL/hour against a target of 30 to 60 mL/hour, so the nurse ", post:".",
     opts:["gives an intravenous diuretic to increase the output","increases the fluid rate according to the protocol and rechecks the output hourly, since urine output is the endpoint that titrates resuscitation","reduces the rate, since she is at risk of fluid overload","documents it as acceptable for the first 24 hours after a burn"], ans:1},
    {pre:"Her carboxyhemoglobin is 18%, so the nurse recognizes that ", post:".",
     opts:["the level is insignificant and oxygen can be reduced to air","100% oxygen continues, because it shortens the half-life of carboxyhemoglobin from several hours to well under one","hyperbaric oxygen is never indicated at any level","the pulse oximeter reading of 94% confirms adequate oxygenation"], ans:1},
    {pre:"The right arm remains pulseless on Doppler with increasing pain and paraesthesia, so the nurse ", post:".",
     opts:["escalates immediately for escharotomy, since the circumferential burn is acting like a tourniquet and the limb is at risk","elevates the limb and reassesses in four hours","applies a compression bandage to reduce the swelling","documents it, since pulses are often absent in burned limbs"], ans:0},
    {pre:"Over the following 48 hours the nurse monitors specifically for ", post:".",
     opts:["nothing further, since the first 24 hours are the only risk period","hypokalemia, since burns deplete potassium","infection alone, since fluid balance is now stable","fluid creep with pulmonary edema and abdominal compartment syndrome, alongside hourly urine output and respiratory status"], ans:3}]},
   rat:{c:"Urine output is the resuscitation endpoint, so 15 mL/hour means the rate increases per protocol — a diuretic produces urine without restoring perfusion and worsens the outcome. Carbon monoxide has a half-life of roughly four to five hours on air and well under an hour on 100% oxygen, so high-flow oxygen continues and the pulse oximeter is meaningless because it cannot distinguish carboxyhemoglobin. A circumferential burn with an absent Doppler pulse, rising pain and paraesthesia is a tourniquet effect requiring escharotomy now, not elevation and delay. And the second 24 hours bring the opposite problem: fluid creep, pulmonary edema and abdominal compartment syndrome from the volumes given.",
   o:["A diuretic makes urine without restoring perfusion and worsens the injury.",
    "Correct — urine output titrates the rate, so the rate increases and the output is rechecked hourly.",
    "Reducing the rate when the endpoint is unmet under-resuscitates her.",
    "15 mL/hour is below target at any point in burn resuscitation.",
    "Correct — 100% oxygen shortens the carboxyhemoglobin half-life dramatically and must continue.",
    "A level of 18% with symptoms is significant, particularly after enclosed-space exposure.",
    "Hyperbaric oxygen has defined indications; saying it is never indicated is wrong.",
    "The pulse oximeter cannot distinguish carboxyhemoglobin, so its reading is unreliable.",
    "Correct — a circumferential burn with no Doppler pulse and rising pain is a tourniquet effect needing escharotomy now.",
    "Elevation and delay risks irreversible limb ischemia.",
    "Compression worsens the ischemia in an already compromised limb.",
    "Absent pulses in a circumferential burn are never an expected finding to simply document.",
    "The second 24 hours carry their own serious risks.",
    "Potassium is usually released from damaged cells, so hyperkalemia is the early concern.",
    "Infection matters, but fluid balance does not become stable at 24 hours.",
    "Correct — fluid creep, pulmonary edema and abdominal compartment syndrome are the second-phase risks."],
   s:"Burn resuscitation has two failure modes: too little in the first 24 hours, judged by urine output, and too much in the second, judged by respiratory status and abdominal pressure. Urine output titrates the rate — never use a diuretic to hit the target."}}]})
;
