/* RN Ready — case study v2 · raised intracranial pressure after head injury.
   Sixteenth unfolding case: a 47-year-old falls from a ladder, has a lucid
   interval and then deteriorates with a unilateral fixed pupil and Cushing's
   triad. Judgment unfolds from recognizing uncal herniation, through why the
   blood pressure must NOT be lowered, to cerebral perfusion pressure
   arithmetic and hypotonic fluid.

   Wave 64 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-ICP-01", title:"The Fall From the Ladder — Mr. Danladi, 47",
 setting:"Emergency department / neurosurgical intensive care", sys:"NEURO", cn:"PAA", d:3, b:0.55,
 summary:"47-year-old man who fell 3 metres, was lucid on arrival at a Glasgow Coma Scale of 13 and has now fallen to 9 with a right fixed dilated pupil and Cushing's triad; computed tomography shows a right extradural hematoma with midline shift. Judgment unfolds from recognizing uncal herniation, through why the blood pressure must not be lowered, to cerebral perfusion pressure arithmetic and hypotonic fluid.",
 exhibits:{
  history:{name:"History", type:"text", body:"47-year-old man, fell approximately 3 metres from a ladder onto concrete three hours ago. Brief loss of consciousness at the scene, then fully lucid and conversant — he declined ambulance attendance and was brought in by a colleague when he became confused. Not on any anticoagulant or antiplatelet medicine. No known bleeding disorder. Drinks approximately 40 units of alcohol weekly. No regular medicines, no known allergies. Wearing no helmet; struck the right side of his head."},
  vitals:{name:"Vital Signs (now, versus on arrival)", type:"kv", rows:[["Glasgow Coma Scale","9 (E2 V3 M4) — was 13 on arrival"],["Heart rate","52/min — was 84/min"],["Blood pressure","178/96 mm Hg — was 132/80 mm Hg"],["Respiratory rate","10/min and irregular — was 16/min regular"],["SpO2 (room air)","94%"],["Core temperature","37.8 °C (100.0 °F)"],["Capillary glucose","6.2 mmol/L (112 mg/dL)"]]},
  findings:{name:"Neurological Findings", type:"text", body:"Drowsy and disoriented; opens eyes to voice, confused conversation, withdraws from pain. Right pupil 6 mm and fixed; left pupil 3 mm and reactive to light. Weakness of the left arm and leg, power 3/5. No neck stiffness. No external bleeding from the ears or nose, no raccoon eyes. Computed tomography of the head: right extradural hematoma with a maximum depth of 22 mm and 9 mm of midline shift; no skull fracture identified; basal cisterns partially effaced. Neurosurgery consulted."},
  orders:{name:"Provider Orders", type:"text", body:"1. Immediate neurosurgical review for urgent evacuation. 2. Head of bed elevated to 30 degrees, head kept midline, no neck or hip flexion. 3. Target cerebral perfusion pressure 60 to 70 mm Hg (cerebral perfusion pressure = mean arterial pressure minus intracranial pressure). 4. Do NOT lower the blood pressure — the raised pressure is maintaining cerebral perfusion. 5. Target PaCO2 4.5 to 5.0 kPa; brief hyperventilation only as a temporizing rescue measure. 6. 0.9% sodium chloride for maintenance; NO hypotonic fluids and no 5% dextrose. 7. Hypertonic saline 3% as prescribed for rising intracranial pressure. 8. Treat fever with paracetamol and active cooling. 9. Continuous monitoring; treat seizures promptly. 10. Nil by mouth; airway equipment at the bedside."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the history, vital signs and findings. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","findings"],
   opts:["A lucid interval followed by deterioration, with a unilateral fixed dilated pupil and Cushing's triad, indicates an expanding extradural hematoma with uncal herniation",
    "The blood pressure of 178/96 mm Hg indicates a hypertensive emergency that needs rapid reduction",
    "The heart rate of 52/min indicates a primary cardiac event requiring cardiology referral",
    "His alcohol intake explains the reduced conscious level as early withdrawal"],
   ans:0,
   rat:{c:"The sequence is textbook: brief loss of consciousness, a lucid interval, then rapid deterioration as the hematoma expands — and the right fixed dilated pupil with left-sided weakness localizes it to right uncal herniation compressing the third cranial nerve and the cerebral peduncle. Cushing's triad of bradycardia, hypertension and irregular respiration is a late, pre-terminal sign of raised intracranial pressure. The hypertension is not a separate problem — it is the body's compensatory response to keep blood flowing into a compressed brain, and lowering it causes ischemia. The bradycardia is reflex, not cardiac. And withdrawal does not produce a unilateral fixed pupil or a 9 mm midline shift.",
   o:["Correct — lucid interval, unilateral fixed dilated pupil and Cushing's triad mean expanding hematoma with uncal herniation.",
    "The hypertension is compensatory, maintaining cerebral perfusion; lowering it causes ischemia and is dangerous.",
    "The bradycardia is a reflex response to raised intracranial pressure, part of Cushing's triad.",
    "Alcohol withdrawal does not cause a unilateral fixed pupil or a 9 mm midline shift."],
   s:"Lucid interval then deterioration = extradural hematoma until proven otherwise. Ipsilateral fixed dilated pupil plus contralateral weakness = uncal herniation. Cushing's triad is bradycardia, hypertension and irregular breathing — and it is a LATE sign."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals","findings"],
   hotspot:{mode:"rows", rows:[
    "Glasgow Coma Scale 9, having been 13 on arrival",
    "Right pupil 6 mm and fixed, left pupil 3 mm and reactive",
    "Heart rate 52/min with a blood pressure of 178/96 mm Hg",
    "Respiratory rate 10/min and irregular",
    "Oxygen saturation 94% on room air",
    "Capillary glucose 6.2 mmol/L"
   ], ans:[0,1,2,3]},
   rat:{c:"The falling Glasgow Coma Scale, the unilateral fixed dilated pupil, the bradycardia paired with hypertension, and the slow irregular respiration are all abnormal — and together they are Cushing's triad plus herniation, which is the picture that demands immediate theatre. A saturation of 94% on room air and a glucose of 6.2 mmol/L are both within expected limits and are there to reward you for knowing the ranges rather than highlighting everything. Two planted normals.",
   o:["Expected Glasgow Coma Scale is 15; a fall from 13 to 9 is a two-hour deterioration and is the single most important trend.",
    "Pupils should be equal and reactive; a unilateral fixed dilated pupil indicates third cranial nerve compression from herniation.",
    "Expected heart rate is 60–100/min and systolic pressure under about 140 mm Hg; the pairing is Cushing's response.",
    "Expected respiratory rate is 12–20/min and regular; 10/min and irregular indicates brainstem compression.",
    "Normal saturation is 95% and above on room air, and 94% is marginally low but not the driver here — treat as borderline.",
    "Normal capillary glucose is roughly 4–7.8 mmol/L — within range."],
   s:"In head injury, the trend matters more than any single value. A Glasgow Coma Scale falling by two or more points is a neurosurgical emergency whatever the absolute number."}},
  {step:"prioritize", t:"single", stem:"His blood pressure is 178/96 mm Hg and his conscious level is falling. Which action by the nurse takes priority?",
   reveal:["history","vitals","findings","orders"],
   opts:["Escalate immediately for urgent neurosurgical evacuation while protecting the airway and maintaining cerebral perfusion",
    "Lower the blood pressure to below 140/90 mm Hg to reduce the risk of further bleeding into the hematoma",
    "Hyperventilate him to a carbon dioxide of 3.0 kPa to reduce the intracranial pressure",
    "Start 5% dextrose intravenously to maintain his glucose while he is nil by mouth"],
   ans:0,
   rat:{c:"An extradural hematoma of 22 mm with 9 mm of midline shift and a falling conscious level is a surgical emergency, and the priority is evacuation while the airway is protected and perfusion maintained — cerebral perfusion pressure equals mean arterial pressure minus intracranial pressure, so with a high intracranial pressure he needs that high mean arterial pressure. Lowering the blood pressure removes the compensation and causes ischemia in the compressed brain. Hyperventilating to 3.0 kPa causes cerebral vasoconstriction and worsens ischemia; the target is 4.5 to 5.0 kPa, and brief hyperventilation is a temporizing rescue only. And 5% dextrose is effectively hypotonic once the glucose is metabolized, which worsens cerebral edema.",
   o:["Correct — evacuation is the definitive treatment; protect the airway and maintain perfusion while it is arranged.",
    "Lowering the pressure removes the compensation maintaining cerebral perfusion and causes ischemia.",
    "A carbon dioxide of 3.0 kPa causes cerebral vasoconstriction and ischemia; the target is 4.5 to 5.0 kPa.",
    "5% dextrose becomes hypotonic once metabolized and worsens cerebral edema; use 0.9% sodium chloride."],
   s:"Cerebral perfusion pressure = mean arterial pressure minus intracranial pressure. In raised intracranial pressure, the high blood pressure is the client's lifeline — never normalize it. Hypotonic fluid worsens edema."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["vitals","findings","orders"],
   opts:["Head of bed elevated to 30 degrees with the head kept midline and no neck flexion, to support venous drainage from the skull",
    "Targeting a calculated cerebral perfusion pressure of 60 to 70 mm Hg rather than a blood pressure number alone",
    "0.9% sodium chloride as the maintenance fluid, with hypotonic solutions avoided",
    "Treating fever, seizures and hypoxia, since each raises cerebral metabolic demand or intracranial pressure",
    "Rapidly normalizing the blood pressure to reduce the risk of hematoma expansion"],
   ans:[0,1,2,3],
   rat:{c:"Elevating the head 30 degrees with the head midline improves jugular venous drainage and lowers intracranial pressure at no cost; neck flexion and hip flexion both obstruct that drainage and raise it. Cerebral perfusion pressure, not blood pressure, is the target — a normal-looking blood pressure can be inadequate when intracranial pressure is high. Hypotonic fluid moves water into brain tissue and worsens edema, so 0.9% sodium chloride is used. Fever, seizures and hypoxia each increase cerebral metabolic demand or intracranial pressure and are treated aggressively. Normalizing the blood pressure is the one action here that actively harms him.",
   o:["Correct — 30 degrees head-up with the head midline supports venous drainage and lowers intracranial pressure.",
    "Correct — cerebral perfusion pressure is the target, because a normal blood pressure can be inadequate when intracranial pressure is high.",
    "Correct — hypotonic fluid worsens cerebral edema; 0.9% sodium chloride is the fluid of choice.",
    "Correct — fever, seizures and hypoxia all increase metabolic demand or pressure and must be treated.",
    "Lowering the blood pressure reduces cerebral perfusion pressure and causes ischemia in the compressed brain."],
   s:"Neuroprotective basics: 30 degrees head-up, head midline, no hypotonic fluid, target cerebral perfusion pressure not blood pressure, and treat every fever, seizure and hypoxic episode."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","findings","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Recognize the deterioration and escalate immediately for neurosurgical review",
     "Protect the airway with oxygen, and prepare to intubate if the Glasgow Coma Scale reaches 8 or less",
     "Position the head of bed at 30 degrees with the head midline and give the prescribed osmotherapy",
     "Transfer to theatre for evacuation while maintaining cerebral perfusion pressure"],
    ans:[0,1,2,3]},
   rat:{c:"Recognition and escalation come first because the definitive treatment is surgical and every minute of compression costs brain tissue. The airway comes next — the rule is to intubate at a Glasgow Coma Scale of 8 or less, and he is at 9 and falling, so equipment must be at the bedside and the threshold anticipated rather than waited for. Positioning and osmotherapy are the immediate medical measures that lower intracranial pressure while theatre is prepared. Transfer comes last in sequence but is arranged from the moment the escalation is made, with perfusion pressure maintained throughout the move.",
   o:["Recognition and escalation — the definitive treatment is surgical and time is brain.",
    "Airway protection, intubating at a Glasgow Coma Scale of 8 or less; he is at 9 and falling.",
    "Positioning and osmotherapy lower intracranial pressure while theatre is prepared.",
    "Transfer for evacuation with cerebral perfusion pressure maintained throughout."],
   s:"Head injury sequence: escalate → airway → position and osmotherapy → theatre. Intubate at a Glasgow Coma Scale of 8 or less, and prepare before he gets there rather than after."}},
  {step:"evaluate", t:"cloze", stem:"The hematoma is evacuated. Afterwards his intracranial pressure is 14 mm Hg and his mean arterial pressure is 84 mm Hg. He is nil by mouth and needs maintenance fluid. Complete each evaluation statement.",
   reveal:["history","vitals","findings","orders"],
   cloze:{lines:[
    {pre:"With an intracranial pressure of 14 mm Hg and a mean arterial pressure of 84 mm Hg, the nurse calculates his cerebral perfusion pressure as ", post:".",
     opts:["98 mm Hg, since the two values are added together","70 mm Hg, calculated as the mean arterial pressure minus the intracranial pressure","14 mm Hg, since that is the pressure inside the skull","84 mm Hg, since the mean arterial pressure is itself the perfusion pressure"], ans:1},
    {pre:"His carbon dioxide is 4.2 kPa and his intracranial pressure begins to rise again, so the nurse recognizes that brief hyperventilation ", post:".",
     opts:["is the standard continuous treatment for raised intracranial pressure","should be maintained for 24 hours to keep the pressure low","has no measurable effect on intracranial pressure","may be used as a short-term rescue measure while definitive treatment is arranged, because sustained hypocapnia causes cerebral ischemia"], ans:3},
    {pre:"He is nil by mouth and needs maintenance fluid, so the nurse chooses ", post:".",
     opts:["5% dextrose, since he needs a glucose supply","0.45% sodium chloride, since it is more physiological than a full-strength solution","0.9% sodium chloride, because hypotonic fluid moves water into brain tissue and worsens edema","a colloid, since it remains in the circulation longer"], ans:2},
    {pre:"Two days later he develops a temperature of 38.6 °C, so the nurse ", post:".",
     opts:["investigates the source and treats the fever, since fever raises cerebral metabolic demand and intracranial pressure","treats it as expected after craniotomy and takes no action","cools him only if the temperature exceeds 40 °C","gives paracetamol without looking for a cause"], ans:0}]},
   rat:{c:"Cerebral perfusion pressure is mean arterial pressure minus intracranial pressure, so 84 minus 14 gives 70 mm Hg — the top of the target range, and the arithmetic matters because it explains why his blood pressure must stay high while his intracranial pressure is raised. Hyperventilation lowers intracranial pressure by vasoconstriction, but sustained hypocapnia starves the brain, so it is a short-term rescue while definitive treatment is arranged and the usual target is 4.5 to 5.0 kPa. Hypotonic fluid moves water into brain tissue, which is why 0.9% sodium chloride is used and 5% dextrose and 0.45% sodium chloride are both avoided. And fever raises cerebral metabolic demand and intracranial pressure, so it is investigated and treated rather than accepted.",
   o:["Adding the two values has no physiological basis.",
    "Correct — cerebral perfusion pressure is mean arterial pressure minus intracranial pressure, giving 70 mm Hg here.",
    "The intracranial pressure is the pressure to subtract, not the perfusion pressure itself.",
    "Mean arterial pressure alone ignores the opposing intracranial pressure.",
    "Continuous hyperventilation causes sustained cerebral vasoconstriction and ischemia.",
    "Maintaining hypocapnia for 24 hours starves the brain of blood flow.",
    "Hyperventilation does lower intracranial pressure — the problem is the ischemia it causes.",
    "Correct — brief hyperventilation is a rescue measure only, because sustained hypocapnia causes cerebral ischemia.",
    "5% dextrose becomes hypotonic once the glucose is metabolized and worsens cerebral edema.",
    "0.45% sodium chloride is hypotonic and has the same problem.",
    "Correct — 0.9% sodium chloride is isotonic and avoids shifting water into brain tissue.",
    "Colloids offer no advantage here and do not address the edema risk.",
    "Correct — fever raises cerebral metabolic demand and intracranial pressure, so it is investigated and treated.",
    "Fever after craniotomy is common but is never accepted without investigation.",
    "Waiting for 40 °C allows hours of raised metabolic demand and pressure.",
    "Treating the number without seeking the source misses infection, which is the commonest cause."],
   s:"Cerebral perfusion pressure = mean arterial pressure minus intracranial pressure — learn the arithmetic, because it explains why you must not lower the blood pressure. Hyperventilate briefly to rescue, never to maintain."}}]})
;
