/* RN Ready — case study v2 · severe hyperkalemia in a dialysis patient.
   Fourteenth unfolding case: a 61-year-old on hemodialysis misses two
   sessions and presents with a potassium of 7.6 and a widening QRS.
   Judgment unfolds from recognizing the electrocardiogram as the emergency,
   through calcium gluconate as membrane stabilization rather than treatment,
   to rebound hyperkalemia and delayed hypoglycemia.

   Wave 63 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-HYPERK-01", title:"The Missed Sessions — Mr. Bello, 61",
 setting:"Emergency department / renal unit", sys:"REN", cn:"PHA", d:3, b:0.55,
 summary:"61-year-old on hemodialysis who missed his last two sessions, presenting with weakness, palpitations, a potassium of 7.6 mmol/L, tented T waves and a QRS of 138 ms. Judgment unfolds from the electrocardiogram as the emergency, through membrane stabilization versus potassium lowering, to rebound hyperkalemia and delayed hypoglycemia.",
 exhibits:{
  history:{name:"History", type:"text", body:"61-year-old man with end-stage kidney disease secondary to diabetic nephropathy, on thrice-weekly hemodialysis via an arteriovenous fistula. He missed his last two sessions because he could not arrange transport. Presents with two days of generalized weakness, heaviness in his legs and palpitations. Other history: type 2 diabetes, hypertension. Medicines: ramipril 10 mg daily, spironolactone 25 mg daily, insulin, atorvastatin. He reports eating a large portion of plantain and drinking a coconut-water-based drink over the weekend, believing both to be healthy. Weight is up 3.2 kg since his last dialysis session."},
  vitals:{name:"Vital Signs (on arrival)", type:"kv", rows:[["Heart rate","44/min, irregular"],["Blood pressure","168/92 mm Hg"],["Respiratory rate","18/min"],["SpO2 (room air)","97%"],["Core temperature","36.4 °C (97.5 °F)"],["Power","Reduced in both legs, 3/5 proximally"],["Access site","Fistula thrill and bruit present"]]},
  ecg:{name:"Electrocardiogram — 12-lead on arrival", type:"text", body:"Rate 44/min, irregular. Tall tented T waves in V2 to V5. P waves flattened and difficult to identify. QRS duration 138 ms, widened from a previous tracing of 96 ms. Early sine-wave morphology beginning to appear. No previous bundle branch block documented."},
  labs:{name:"Laboratory Results", type:"kv", rows:[["Potassium","7.6 mmol/L (repeat venous sample confirms)"],["Sodium","132 mmol/L"],["Bicarbonate","16 mmol/L"],["Venous pH","7.24"],["Urea","32 mmol/L"],["Creatinine","980 µmol/L (11.1 mg/dL)"],["Glucose","9.4 mmol/L (169 mg/dL)"],["Corrected calcium","1.9 mmol/L"],["Phosphate","2.4 mmol/L"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. Continuous cardiac monitoring and defibrillator pads applied. 2. Calcium gluconate 10% 10 mL IV over 5 minutes; repeat if electrocardiogram changes persist. 3. Soluble insulin 10 units with 25 g glucose IV, then a 10% glucose infusion; check glucose hourly for at least 6 hours. 4. Salbutamol 10 mg nebulized as an adjunct. 5. Sodium bicarbonate 8.4% 50 mL IV given the acidaemia. 6. STOP ramipril and spironolactone. 7. No potassium-containing fluids, no lactated Ringer's, no potassium-sparing agents. 8. Urgent nephrology referral for hemodialysis — this is the definitive treatment. 9. Repeat potassium one hour after treatment and then every 2 hours. 10. Dialysis transport arranged with the renal unit."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the electrocardiogram and laboratory results. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","ecg","labs"],
   opts:["Tented T waves with a widened QRS and a potassium of 7.6 mmol/L indicate imminent risk of a fatal arrhythmia and require membrane stabilization now",
    "The widened QRS indicates a new bundle branch block unrelated to the potassium level",
    "The heart rate of 44/min is a side effect of his ramipril and needs no urgent action",
    "A potassium of 7.6 mmol/L is common in dialysis patients and can wait for his next scheduled session"],
   ans:0,
   rat:{c:"The electrocardiogram is the emergency: tented T waves, flattened P waves and a QRS widened from 96 to 138 ms with early sine-wave morphology mean the myocardium is on the verge of ventricular fibrillation or asystole, and treatment is measured in minutes. The QRS widening is caused by the potassium, not by a new conduction lesion — the previous tracing at 96 ms proves it. Ramipril contributes to a raised potassium by reducing aldosterone, but it does not cause bradycardia of this degree and is not the explanation. And a potassium of 7.6 with these changes is never an observation; it is the level at which people die.",
   o:["Correct — the electrocardiogram changes with a potassium of 7.6 mean imminent fatal arrhythmia; stabilize the membrane now.",
    "The QRS widened from a documented 96 ms; hyperkalemia is the cause, and calling it a bundle branch block delays treatment.",
    "Ramipril raises potassium by reducing aldosterone; it does not explain this degree of bradycardia, and the emergency is the potassium.",
    "A potassium of 7.6 with a widened QRS is a lethal combination, not a routine pre-dialysis number."],
   s:"In hyperkalemia, treat the electrocardiogram, not just the number. Peaked T waves → flattened P waves → widened QRS → sine wave → arrest. QRS widening means you have minutes."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range or the expected change since his last dialysis session.",
   reveal:["vitals","ecg","labs"],
   hotspot:{mode:"rows", rows:[
    "Potassium 7.6 mmol/L",
    "QRS duration 138 ms with tented T waves",
    "pH 7.24 with a bicarbonate of 16 mmol/L",
    "Weight up 3.2 kg since the last dialysis session",
    "Oxygen saturation 97% on room air",
    "Core temperature 36.4 °C"
   ], ans:[0,1,2,3]},
   rat:{c:"The potassium, the electrocardiogram changes, the metabolic acidosis and the fluid overload from two missed sessions are all abnormal, and they reinforce each other — acidosis drives potassium out of cells, so the pH of 7.24 is actively worsening the level. A saturation of 97% on room air and a temperature of 36.4 °C are both normal. Two planted values, and the acidosis is the one worth thinking about because correcting it is part of the treatment.",
   o:["Expected potassium is 3.5–5.0 mmol/L; 7.6 is severe and immediately life-threatening.",
    "Expected QRS duration is under 120 ms; 138 ms with tented T waves is a pre-arrest pattern.",
    "Expected venous pH is 7.31–7.41 and bicarbonate 22–26 mmol/L; both are low and the acidosis shifts potassium extracellularly.",
    "A 3.2 kg gain between sessions is significant interdialytic fluid accumulation.",
    "Normal saturation is 95% and above — within range.",
    "Normal core temperature is about 36.1–37.2 °C — within range."],
   s:"Hyperkalemia and acidosis are a vicious pair: acidosis shifts potassium out of cells, so correcting the pH is part of lowering the potassium. Read them together."}},
  {step:"prioritize", t:"single", stem:"Which action by the nurse takes priority?",
   reveal:["history","ecg","labs","orders"],
   opts:["Give 10% calcium gluconate intravenously with continuous cardiac monitoring, since it stabilizes the myocardial membrane within minutes",
    "Give soluble insulin with glucose first, since that is the treatment that lowers the potassium",
    "Give the salbutamol nebulizer first, since it shifts potassium into the cells quickly",
    "Arrange hemodialysis first, since that is the definitive treatment"],
   ans:0,
   rat:{c:"Calcium gluconate works in one to three minutes by raising the threshold potential and stabilizing the myocardial membrane — it buys the time everything else needs. Insulin with glucose takes 15 to 30 minutes to shift potassium, salbutamol takes about 30 minutes and is an adjunct, and hemodialysis is definitive but takes hours to set up. With a QRS of 138 ms and early sine-wave morphology he can arrest before any of those work, which is why membrane stabilization is first. The critical point: calcium gluconate does not lower the potassium at all. It only prevents the arrest while the potassium-lowering treatments catch up.",
   o:["Correct — calcium gluconate stabilizes the membrane in one to three minutes; it is the only treatment fast enough for these electrocardiogram changes.",
    "Insulin and glucose take 15 to 30 minutes; he may arrest before they act, so membrane stabilization comes first.",
    "Salbutamol takes around 30 minutes and is an adjunct, never the first action in a pre-arrest tracing.",
    "Dialysis is definitive but takes hours to arrange; it cannot protect him in the next ten minutes."],
   s:"Hyperkalemia has three separate jobs: stabilize the membrane (calcium), shift potassium into cells (insulin, salbutamol, bicarbonate), and remove it from the body (dialysis, binders). Calcium gluconate lowers nothing — do not mistake it for treatment."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["history","ecg","labs","orders"],
   opts:["Insulin with glucose to shift potassium intracellularly, with hourly glucose checks afterwards",
    "Stopping the ramipril and spironolactone, since both raise potassium",
    "Sodium bicarbonate given the acidaemia, since correcting the pH helps shift potassium into cells",
    "Arranging urgent hemodialysis, since it is the only treatment here that removes potassium from the body",
    "A potassium-binding resin as the fastest available route to remove potassium"],
   ans:[0,1,2,3],
   rat:{c:"Insulin with glucose is the most reliable shift agent but must be followed by hourly glucose checks, because hypoglycemia is common and is delayed in kidney failure. Ramipril and spironolactone both raise potassium and must be stopped — continuing them sabotages everything else. Bicarbonate helps because the acidosis is driving potassium out of cells. Dialysis is the only intervention here that actually removes potassium from the body; every other treatment just moves it around temporarily. Resin binders take many hours and have no place in the emergency phase.",
   o:["Correct — insulin with glucose is the most reliable shift agent, and hourly glucose monitoring is mandatory.",
    "Correct — both drugs raise potassium; continuing them undermines every other measure.",
    "Correct — the acidosis is shifting potassium extracellularly, so correcting the pH helps.",
    "Correct — dialysis is the only measure listed that removes potassium from the body rather than redistributing it.",
    "Resin binders take many hours and are for chronic control, not for a potassium of 7.6 with a widened QRS."],
   s:"Only dialysis and binders remove potassium from the body; insulin, salbutamol and bicarbonate just move it into cells temporarily. That is why rebound hyperkalemia happens and why dialysis is never optional here."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","ecg","labs","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Attach continuous cardiac monitoring with defibrillator pads and obtain the 12-lead electrocardiogram",
     "Give 10% calcium gluconate intravenously to stabilize the myocardial membrane",
     "Give insulin with glucose, the salbutamol nebulizer and the sodium bicarbonate to shift potassium intracellularly",
     "Arrange urgent hemodialysis to remove the potassium from the body definitively"],
    ans:[0,1,2,3]},
   rat:{c:"Monitoring and the electrocardiogram come first, because the tracing determines the urgency and he needs pads on before any drug is given. Calcium gluconate follows immediately to stabilize the membrane — it is the only intervention fast enough. The shifting agents come next and run in parallel. Dialysis is arranged last in the nursing sequence but is requested from the first minute, because it is the definitive treatment and access, staffing and machine availability all take time.",
   o:["Monitoring, pads and the 12-lead — the tracing sets the urgency and the pads must be on before anything else.",
    "Calcium gluconate stabilizes the membrane within minutes.",
    "Insulin with glucose, salbutamol and bicarbonate shift potassium intracellularly.",
    "Dialysis removes the potassium — requested from minute one, but it is the last to be delivered."],
   s:"Hyperkalemia sequence: monitor and trace → calcium to stabilize → shift agents → dialysis to remove. Request dialysis immediately even though it arrives last."}},
  {step:"evaluate", t:"cloze", stem:"Two hours after treatment his potassium is 5.6 mmol/L, his QRS has narrowed to 104 ms and his heart rate is 68/min. Complete each evaluation statement.",
   reveal:["history","ecg","labs","orders"],
   cloze:{lines:[
    {pre:"The potassium has fallen to 5.6 mmol/L and the electrocardiogram has improved, so the nurse understands that ", post:".",
     opts:["the emergency is over and monitoring can be stepped down","the shift agents have removed the excess potassium from his body","he still needs hemodialysis, because the shift agents only moved potassium into cells and the effect reverses within hours","the ramipril and spironolactone can be restarted now that the level is safer"], ans:2},
    {pre:"Six hours after the insulin and glucose the nurse monitors specifically for ", post:".",
     opts:["hyperglycemia, since the glucose infusion raises the level","hypoglycemia, which is common and delayed in kidney failure, so glucose checks continue for at least six hours","hyperkalemia only, since the glucose has no effect on the insulin","fluid overload from the glucose infusion alone"], ans:1},
    {pre:"Because calcium gluconate was given, the nurse recognizes that ", post:".",
     opts:["it lowered the potassium by driving it into the cells","it removed potassium through the kidneys","it increased urinary potassium excretion","it did not lower the potassium at all — it only stabilized the myocardial membrane while other treatments worked"], ans:3},
    {pre:"Before discharge the nurse's teaching priority is ", post:".",
     opts:["that dialysis attendance is non-negotiable, with a low-potassium diet review and transport arranged so sessions are not missed again","that he should increase coconut water and plantain because they are natural","that his blood pressure medicine is the main cause and should be stopped on his own initiative","that a potassium level above 6.0 is acceptable between sessions"], ans:0}]},
   rat:{c:"The shift agents redistribute potassium for four to six hours and then it comes back out of the cells — rebound hyperkalemia is expected, so dialysis is still required and monitoring continues. Hypoglycemia after insulin and glucose is common and is delayed in kidney failure because insulin clearance falls, so glucose checks continue for at least six hours. Calcium gluconate has no effect on the potassium level whatsoever; it stabilizes the membrane and nothing else, which is why the potassium-lowering treatments must all still be given. And the cause here was two missed sessions with a high-potassium diet, so transport and diet are the teaching that prevents the next admission — he must not stop prescribed medicines himself, and coconut water is one of the highest-potassium drinks there is.",
   o:["The emergency is not over; rebound hyperkalemia is expected as the shift wears off.",
    "Shift agents move potassium into cells; they do not remove it from the body.",
    "Correct — dialysis is still needed because the shift is temporary and reverses within hours.",
    "Restarting a potassium-raising drug before dialysis and before the level is stable is unsafe.",
    "The glucose infusion is there to prevent hypoglycemia, not to cause hyperglycemia.",
    "Correct — hypoglycemia is common and delayed in kidney failure; continue glucose checks for at least six hours.",
    "The glucose infusion has a direct effect via the insulin given with it.",
    "Fluid balance matters, but hypoglycemia is the specific risk to watch.",
    "Calcium gluconate does not shift potassium intracellularly.",
    "He is anuric in end-stage kidney disease; there is no renal excretion to increase.",
    "Calcium gluconate does not act through the kidneys.",
    "Correct — calcium gluconate stabilizes the membrane only and lowers nothing.",
    "Correct — the cause was missed sessions plus a high-potassium diet; transport and diet prevent the next admission.",
    "Coconut water is one of the highest-potassium drinks available and must be avoided.",
    "Medicines are reviewed by the prescriber; self-discontinuation is unsafe.",
    "A potassium above 6.0 between sessions is not acceptable and needs review."],
   s:"Three hyperkalemia traps: rebound hyperkalemia after the shift wears off, delayed hypoglycemia after insulin in kidney failure, and believing calcium gluconate lowered the potassium. It did not — it only bought the time."}}]})
;
