/* RN Ready — case study v2 · opioid overdose with re-narcotization.
   Tenth unfolding case: a 34-year-old found down reverses after one dose of
   naloxone and then deteriorates again in the ambulance. Judgment unfolds from
   the pharmacokinetic reason for re-narcotization, through ventilating rather
   than waking, to the xylazine adulterant problem and take-home naloxone.

   Wave 62 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-OD-01", title:"Found Down — Mr. K., 34",
 setting:"Emergency department", sys:"RESP", cn:"PHA", d:3, b:0.55,
 summary:"34-year-old man found unresponsive with a tourniquet in place, reverses after 0.4 mg naloxone intramuscularly and then becomes unresponsive again in the ambulance. Judgment unfolds from re-narcotization, through ventilating rather than waking, to the alpha-2 adulterant problem and take-home naloxone at discharge.",
 exhibits:{
  history:{name:"Prehospital Report", type:"text", body:"34-year-old male, found unresponsive in a stairwell by a cleaner at 0710. No identification. A tourniquet was in place on the left upper arm and a small bag of brown powder was nearby. Emergency medical services found him apneic with a pulse. Naloxone 0.4 mg given intramuscularly at 0722; he began breathing spontaneously and opened his eyes. He became unresponsive again during transport at 0748. No bystander witnessed the ingestion or injection. No known medical history, no known allergies, no regular medicines."},
  vitals:{name:"Vital Signs (on arrival 0755)", type:"kv", rows:[["Respiratory rate","6/min, shallow"],["SpO2 (room air)","82%"],["Heart rate","52/min"],["Blood pressure","88/54 mm Hg"],["Core temperature","36.6 °C (97.9 °F)"],["Capillary glucose","5.6 mmol/L (101 mg/dL)"],["Glasgow Coma Scale","6 (E2 V1 M3)"],["Pupils","1 mm bilaterally, poorly reactive"]]},
  findings:{name:"Focused Findings", type:"text", body:"Unresponsive to voice, localizes to pain. No gag reflex; pooled secretions in the oropharynx. Fine frothy secretions at the lips. Multiple old needle tracks on both forearms and the left antecubital fossa; fresh track with a tourniquet mark. No head injury, no chest wall injury, no limb deformity. Skin cool and dry. Bladder not palpable. Urine toxicology sent; result pending. Paramedic reports the powder is consistent with street heroin, which in this area is frequently adulterated with xylazine."},
  orders:{name:"Provider Orders", type:"text", body:"1. Bag-valve-mask ventilation with high-flow oxygen; definitive airway if ventilation is inadequate. 2. Naloxone 0.4 mg IV, titrated to a respiratory rate above 12/min — not to full consciousness. 3. Repeat doses every 2 to 3 minutes as needed. 4. Consider a naloxone infusion at two thirds of the effective waking dose per hour if repeated boluses are required. 5. Continuous cardiorespiratory monitoring and pulse oximetry. 6. Suction available at the bedside; nil by mouth. 7. Observe for at least 4 to 6 hours after the last naloxone dose — longer if a long-acting opioid is suspected. 8. Capillary glucose hourly while sedated. 9. Do not discharge while any naloxone effect could still be wearing off. 10. Toxicology and addiction service referral; take-home naloxone kit to be offered."},
  notes:{name:"Nurse's Notes", type:"text", body:"0800: Bag-valve-mask ventilation started. Respiratory rate 6/min and saturation 82% before intervention. 0804: Naloxone 0.4 mg IV given. 0807: Respiratory rate 14/min, saturation 94% on oxygen, eyes open, able to state his name. 0812: Becomes agitated, pulls at the mask, states he needs to leave. 0840: Becomes drowsy again; respiratory rate 8/min. Charge nurse asks whether he can be discharged now that he has reversed once."}},
 items:[
  {step:"recognize", t:"single", stem:"He responded to the first dose of naloxone at 0722 and was unresponsive again by 0748. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","findings"],
   opts:["The intramuscular naloxone never achieves an effective concentration, so the initial response was coincidental",
    "Naloxone's duration of action is shorter than that of most opioids, so the opioid effect re-emerges as it wears off",
    "He must have taken a further dose of opioid while being transported",
    "Pinpoint pupils indicate a brainstem injury rather than an opioid effect"],
   ans:1,
   rat:{c:"Naloxone lasts roughly 30 to 90 minutes while heroin, its active metabolites, fentanyl and methadone all last far longer, so re-narcotization is the expected pharmacology rather than a complication — this is the single reason observation after reversal is mandatory. An intramuscular dose clearly worked, since he responded. He was in the ambulance under supervision, so a second dose is unlikely. And pinpoint pupils are the classic opioid sign, not evidence of brainstem injury.",
   o:["He responded to the intramuscular dose, which proves it was effective; the route is not the problem.",
    "Correct — naloxone outlives nothing; most opioids outlast it, so the effect returns when it wears off.",
    "He was supervised in the ambulance; re-dosing does not explain a predictable pharmacokinetic pattern.",
    "Pinpoint pupils with respiratory depression and reduced consciousness are the opioid triad, not a brainstem sign."],
   s:"Naloxone is short and opioids are long. Re-narcotization is expected pharmacology, which is exactly why every reversed client needs hours of observation and not a discharge."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals","findings"],
   hotspot:{mode:"rows", rows:[
    "Respiratory rate 6/min",
    "Oxygen saturation 82% on room air",
    "Glasgow Coma Scale 6 with an absent gag reflex",
    "Pupils 1 mm and poorly reactive",
    "Capillary glucose 5.6 mmol/L",
    "Core temperature 36.6 °C"
   ], ans:[0,1,2,3]},
   rat:{c:"A respiratory rate of 6/min is the defining abnormality, the saturation of 82% is the consequence, a Glasgow Coma Scale of 6 with no gag reflex means the airway is unprotected, and 1 mm poorly reactive pupils complete the opioid triad. The glucose of 5.6 mmol/L is normal — and checking it mattered, because hypoglycemia mimics this entire picture and is reversed by something else entirely. A core temperature of 36.6 °C is also normal. Two planted values, one of them there to reward you for having checked it.",
   o:["Expected respiratory rate is 12–20/min; 6/min is life-threatening hypoventilation.",
    "Expected saturation is 95% and above; 82% is severe hypoxemia.",
    "A Glasgow Coma Scale of 8 or less means the airway is not protected; 6 with no gag reflex is critical.",
    "Expected pupils are 2–5 mm and reactive; 1 mm and poorly reactive is the opioid sign.",
    "Normal capillary glucose is roughly 4–7.8 mmol/L — within range, and worth having checked.",
    "Normal core temperature is about 36.1–37.2 °C — within range."],
   s:"The opioid triad is respiratory depression, reduced consciousness and pinpoint pupils. Always check the glucose in any reduced-consciousness client — hypoglycemia is the reversible mimic."}},
  {step:"prioritize", t:"single", stem:"Which action by the nurse takes priority before any further naloxone is given?",
   reveal:["vitals","findings","orders","notes"],
   opts:["Ventilate with a bag-valve-mask and protect the airway, since the immediate threat is hypoventilation rather than reduced consciousness",
    "Give a 4 mg naloxone bolus intravenously to restore full consciousness as quickly as possible",
    "Obtain a computed tomography scan of the head to exclude intracranial hemorrhage",
    "Insert a nasopharyngeal airway and wait for the urine toxicology result before treating"],
   ans:0,
   rat:{c:"At a respiratory rate of 6/min with a saturation of 82% and no gag reflex, the client is dying of hypoventilation, and ventilation is what fixes that in seconds. Naloxone is the antidote but it takes minutes to work and its target is adequate spontaneous breathing, not wakefulness — a large bolus precipitates acute withdrawal with vomiting into an unprotected airway, agitation, and flash pulmonary edema. Imaging is reasonable later but he cannot be sent to the scanner breathing six times a minute. And waiting for a toxicology result that will not change immediate management is not a plan.",
   o:["Correct — ventilation is the life-saving step; naloxone supports it but does not replace it.",
    "A large bolus causes acute withdrawal, vomiting into an unprotected airway and flash pulmonary edema; titrate to breathing, not to wakefulness.",
    "He cannot be transported to the scanner while breathing 6 times a minute; ventilate first.",
    "Waiting on a toxicology result that will not change immediate care delays the intervention that keeps him alive."],
   s:"Titrate naloxone to a respiratory rate above 12/min, never to full consciousness. Waking an opioid-dependent client abruptly buys you vomiting, agitation and pulmonary edema — and no better airway."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["history","vitals","findings","orders","notes"],
   opts:["Titrating naloxone to a respiratory rate above 12/min rather than to full alertness",
    "Continuous cardiorespiratory monitoring for at least four to six hours after the last dose",
    "Suction at the bedside with side-lying positioning while the gag reflex is absent",
    "Capillary glucose monitoring while he remains sedated",
    "Discharging him once he is fully awake, since he has already reversed once"],
   ans:[0,1,2,3],
   rat:{c:"All four of the first statements are the standard of care: dose to breathing, watch long enough for the naloxone to wear off, protect an airway with no gag reflex, and keep checking the glucose because hypoglycemia both mimics and coexists with overdose. Discharging a client who has reversed once is the error this whole case exists to expose — he has already re-narcotized once in the ambulance, and the observation period is the only thing standing between him and a second, unwitnessed episode.",
   o:["Correct — the endpoint is spontaneous ventilation, not consciousness.",
    "Correct — naloxone wears off in 30 to 90 minutes; observation must outlast the opioid.",
    "Correct — no gag reflex means an unprotected airway and real aspiration risk.",
    "Correct — hypoglycemia mimics overdose and sedated clients cannot report its symptoms.",
    "He has already re-narcotized once; discharging after a single reversal risks an unwitnessed fatal second episode."],
   s:"The observation period after naloxone is not bureaucracy — it is the treatment. He reversed, then re-narcotized in the ambulance, which is the case proving why he cannot go home."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","findings","orders","notes"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Open the airway, suction the secretions and ventilate with a bag-valve-mask on high-flow oxygen",
     "Check a capillary glucose, attach continuous monitoring and pulse oximetry, and secure intravenous access",
     "Titrate naloxone to spontaneous ventilation above 12 breaths per minute",
     "Continue observation for re-sedation and prepare a naloxone infusion if repeated boluses are needed"],
    ans:[0,1,2,3]},
   rat:{c:"Ventilation comes first because it is the intervention that reverses the hypoxia killing him, and it works immediately. Glucose, monitoring and access come next, since the glucose excludes the reversible mimic and access is needed for titration. Naloxone is then titrated against the respiratory rate. Ongoing observation and infusion preparation come last in sequence but never stop — they are what catch the second episode he has already demonstrated he is prone to.",
   o:["Airway, suction and ventilation reverse the hypoxia immediately — before any drug can act.",
    "Glucose excludes the mimic; monitoring and access enable safe titration.",
    "Naloxone is then titrated against the respiratory rate, not against alertness.",
    "Observation and infusion preparation catch the re-narcotization he has already shown once."],
   s:"Overdose sequence: ventilate → exclude the mimic and get access → titrate the antidote → keep watching. Ventilation is never second to the antidote."}},
  {step:"evaluate", t:"cloze", stem:"At 0812 he is awake, agitated and insisting on leaving. At 0840 he becomes drowsy again with a respiratory rate of 8/min. Complete each evaluation statement.",
   reveal:["history","vitals","findings","orders","notes"],
   cloze:{lines:[
    {pre:"He is awake and insists on leaving. The nurse understands that discharge depends on ", post:".",
     opts:["the fact that he has already reversed, so no further observation is required","detaining him under mental health legislation because he has taken drugs","observation long enough after the last naloxone dose to exclude re-sedation, and if he still leaves, a capacity assessment and documented refusal","applying restraint, since agitation after naloxone is always acute withdrawal"], ans:2},
    {pre:"Given that xylazine is a common adulterant in this area, the nurse recognizes that ", post:".",
     opts:["xylazine is reversed by a second dose of naloxone","xylazine causes severe hypertension that must be treated first","xylazine is an alpha-2 agonist that naloxone does not reverse, so sedation can persist and airway support must continue","xylazine is a stimulant, so this presentation is atypical and needs another explanation"], ans:2},
    {pre:"Before any discharge the nurse offers ", post:".",
     opts:["a take-home naloxone kit with overdose education and referral to treatment","a short course of a benzodiazepine for the agitation","nothing further, since he has survived this overdose","advice to halve his usual dose so that the next overdose is smaller"], ans:0},
    {pre:"At 0840 his respiratory rate falls again to 8/min, so the nurse ", post:".",
     opts:["documents it as an expected fluctuation and continues hourly checks","re-ventilates, gives further naloxone and starts an infusion while escalating to the team","gives flumazenil in case a benzodiazepine was co-ingested","waits thirty minutes to see whether it settles on its own"], ans:1}]},
   rat:{c:"A client who took drugs voluntarily is not automatically deprived of capacity, so the answer is not detention: he needs the full observation period, and if he still refuses, a capacity assessment with documented advice and refusal. Xylazine is an alpha-2 agonist sedative with no opioid receptor activity, so naloxone does nothing for it — which is why people keep needing airway support after an apparently adequate reversal. Take-home naloxone with education and a treatment referral is the single intervention with the strongest evidence for preventing a subsequent fatal overdose. And a falling respiratory rate at 0840 is re-narcotization happening in real time: ventilate, redose, start the infusion and escalate now.",
   o:["He has already re-narcotized once, which is precisely why the observation period cannot be skipped.",
    "Taking drugs does not remove capacity; detention without a capacity assessment is unlawful.",
    "Correct — observe past the naloxone, and if he still refuses, assess capacity and document properly.",
    "Restraint needs a clinical and legal basis; agitation alone after naloxone does not provide one.",
    "Naloxone has no effect on xylazine because it is not an opioid.",
    "Xylazine causes hypotension and bradycardia, not hypertension.",
    "Correct — xylazine is an alpha-2 agonist; naloxone does not reverse it, so airway support continues.",
    "Xylazine is a sedative, and this presentation is entirely typical of an adulterated supply.",
    "Correct — take-home naloxone with education is the highest-yield intervention before he leaves.",
    "A benzodiazepine in a client who has just re-narcotized risks further respiratory depression.",
    "Surviving one overdose is the strongest predictor of the next; silence is not care.",
    "Dose reduction advice is not a substitute for naloxone and does not address adulteration.",
    "A respiratory rate of 8/min in a client who reversed 40 minutes ago is re-narcotization, not fluctuation.",
    "Correct — re-ventilate, redose, start an infusion and escalate; this is the second episode already.",
    "Flumazenil is not indicated and carries seizure risk in mixed or unknown ingestions.",
    "Waiting thirty minutes in a client who is hypoventilating risks arrest."],
   s:"Three things kill after a successful reversal: discharging too early, assuming naloxone covers every adulterant, and failing to send the client out with naloxone of his own. Xylazine is not reversed by naloxone — the airway support continues regardless."}}]})
;
