/* RN Ready — case study v2 · pediatric life-threatening asthma.
   Thirteenth unfolding case: an 8-year-old with a previous intensive care
   admission deteriorates during treatment. Judgment unfolds from recognizing
   that a FALLING respiratory rate and a quiet chest are the danger signs, not
   improvement, through the oxygen-driven nebulizer and magnesium sequence, to
   discharge teaching.

   Wave 63 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-ASTHMA-01", title:"The Saturday Match — Tobi, 8",
 setting:"Pediatric emergency department", sys:"RESP", cn:"PAA", d:3, b:0.55,
 summary:"8-year-old boy with a previous intensive care admission for asthma, 24 hours of worsening wheeze, now speaking in single words with a saturation of 89% on room air. Judgment unfolds from recognizing that a falling rate and a quiet chest signal impending arrest, through the oxygen-driven nebulizer and magnesium sequence, to discharge teaching.",
 exhibits:{
  history:{name:"History", type:"text", body:"8-year-old boy, 26 kg. Twenty-four hours of worsening wheeze and cough after a cold. His mother has been giving salbutamol through a spacer every three hours with progressively less relief. Regular medicines: beclometasone inhaler twice daily and montelukast at night — his mother says he has not used the preventer reliably for about a month. Previous intensive care admission for asthma at age 5, including a period of ventilation. No fever. Up to date with immunizations. Attends a Saturday football match most weeks."},
  vitals:{name:"Vital Signs (on arrival)", type:"kv", rows:[["Respiratory rate","44/min"],["SpO2 (room air)","89%"],["Heart rate","148/min"],["Temperature","37.0 °C (98.6 °F)"],["Speech","Single words only"],["Work of breathing","Accessory muscle use, nasal flaring, tracheal tug"],["Auscultation","Widespread wheeze, with quiet areas in the right lower zone"]]},
  assessment:{name:"Assessment & Course", type:"text", body:"Peak expiratory flow 81 L/min against a predicted 180 L/min — 45% of predicted. Capillary refill 2 seconds. Alert and anxious. 0 min: high-flow oxygen applied, first nebulizer started. 20 min: wheeze quieter, respiratory rate 40/min, saturation 92% on oxygen. 40 min: respiratory rate 34/min, saturation 93% on 40% oxygen, but he is speaking even less and the chest sounds quieter on both sides. 60 min: respiratory rate 22/min and falling, saturation 90% on 60% oxygen, chest almost silent on auscultation, and he is drowsy and difficult to rouse. His mother says, 'But he is breathing slower now, surely that means he is getting better?'"},
  orders:{name:"Provider Orders", type:"text", body:"1. Oxygen to maintain saturation 94 to 98%. 2. Salbutamol 5 mg nebulized, driven by oxygen, every 20 minutes for three doses. 3. Ipratropium 500 mcg added to the nebulizer for a severe episode. 4. Prednisolone 40 mg orally, or hydrocortisone intravenously if he cannot swallow safely. 5. Magnesium sulfate 40 mg/kg IV over 20 minutes for a severe or life-threatening episode. 6. Venous blood gas. 7. Chest radiograph not routine. 8. Continuous pulse oximetry and cardiorespiratory monitoring. 9. Immediate senior pediatric review and intensive care referral for drowsiness, a silent chest, exhaustion or saturation below 92% despite treatment. 10. Prepare for intubation and ventilation."}},
 items:[
  {step:"recognize", t:"single", stem:"At 60 minutes his respiratory rate has fallen to 22/min, his chest is almost silent and he is drowsy. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","assessment"],
   opts:["A falling respiratory rate with a quiet chest and increasing drowsiness indicates life-threatening asthma and impending respiratory arrest",
    "The falling respiratory rate indicates that the nebulizers are working and he is settling",
    "A saturation of 90% on oxygen is acceptable in a child with known asthma",
    "The absence of wheeze over the chest means that the bronchospasm has resolved"],
   ans:0,
   rat:{c:"This is the classic trap in pediatric asthma: the numbers that look like improvement are the ones that precede arrest. A respiratory rate falling from 44 to 22/min in a child who is becoming drowsier means he is exhausting, not recovering — normal for his age is roughly 20 to 25/min, and a tiring child drifts toward that figure from above as the muscles fail. A silent chest means airflow has become too small to generate wheeze. Carbon dioxide retention causes the drowsiness. And a saturation of 90% on 60% oxygen is severe, refractory hypoxemia — the target in asthma is 94 to 98%, not the 88 to 92% used in adult chronic obstructive pulmonary disease.",
   o:["Correct — a falling rate, a silent chest and drowsiness together mean exhaustion and impending arrest, not recovery.",
    "A falling rate accompanied by drowsiness and a quieter chest is muscle failure, not improvement.",
    "The asthma target is 94 to 98%; 90% on 60% oxygen is refractory hypoxemia.",
    "A silent chest means too little airflow to wheeze — it is the worst auscultatory finding, not the best."],
   s:"In pediatric asthma, improvement means a falling rate with a child who is MORE alert and breathing more easily. A falling rate in a drowsy child with a silent chest is exhaustion — escalate immediately."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that indicates a severe or life-threatening episode.",
   reveal:["vitals","assessment"],
   hotspot:{mode:"rows", rows:[
    "Oxygen saturation 89% on room air",
    "Peak expiratory flow 45% of predicted",
    "Speaking in single words with accessory muscle use and tracheal tug",
    "Quiet areas on auscultation that progress to a silent chest",
    "Temperature 37.0 °C",
    "Capillary refill 2 seconds"
   ], ans:[0,1,2,3]},
   rat:{c:"A saturation below 92%, a peak flow at or below 50% of predicted, an inability to complete sentences with marked work of breathing, and a silent chest are all severity markers — the last is the gravest, because it reflects critically reduced airflow. A temperature of 37.0 °C is normal and argues against a bacterial cause, and a capillary refill of 2 seconds is normal, showing he is not yet in shock — which is precisely why the respiratory signs carry all the weight. Two planted normals.",
   o:["A saturation below 92% on presentation marks a severe episode.",
    "Peak flow at or below 50% of predicted is a recognized severity threshold.",
    "Inability to complete sentences with accessory muscle use and tracheal tug indicates severe obstruction.",
    "A silent chest is the most serious auscultatory finding in asthma.",
    "Normal temperature is about 36.1–37.2 °C — within range.",
    "Normal capillary refill is 2 seconds or less — within range."],
   s:"Asthma severity markers: saturation below 92%, peak flow under 50% predicted, cannot complete sentences, silent chest, exhaustion, and any altered conscious level. The last two mean intensive care."}},
  {step:"prioritize", t:"single", stem:"His mother asks whether the slower breathing means he is getting better. Which action by the nurse takes priority?",
   reveal:["history","vitals","assessment","orders"],
   opts:["Escalate immediately for senior and intensive care review and prepare for intubation and ventilation, since he is exhausting",
    "Give a further salbutamol nebulizer and reassess him in twenty minutes",
    "Encourage him to use his own inhaler with a spacer so that he takes part in his care",
    "Start an intravenous aminophylline infusion as the next step in escalation"],
   ans:0,
   rat:{c:"Drowsiness with a silent chest and a falling respiratory rate is the explicit intensive care referral trigger, and the priority is to escalate now and prepare the airway — a child in this state can arrest within minutes. Another nebulizer and a twenty-minute wait is exactly the delay that turns a tired child into an arrested one. A metered-dose inhaler with a spacer is appropriate for mild to moderate episodes, not for a child who cannot stay awake. Aminophylline is a later specialist option, not a substitute for escalation and airway preparation.",
   o:["Correct — drowsiness, silent chest and exhaustion are the referral triggers; escalate and prepare the airway now.",
    "Waiting twenty minutes in an exhausting child risks arrest; escalation cannot wait for another reassessment.",
    "A spacer device is for mild to moderate episodes; he cannot cooperate and is not moving enough air.",
    "Aminophylline is a specialist option considered later, not an alternative to escalation and airway preparation."],
   s:"The asthma escalation triggers are exhaustion, altered consciousness, a silent chest and refractory hypoxemia. When any appear, the answer is senior help and a prepared airway, not another nebulizer."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care for this episode? Select all that apply.",
   reveal:["history","vitals","assessment","orders"],
   opts:["Salbutamol nebulized and driven by oxygen, with ipratropium added because the episode is severe",
    "A systemic corticosteroid given early and continued, since its effect takes several hours",
    "Intravenous magnesium sulfate as adjunct therapy for a severe or life-threatening episode",
    "An oxygen saturation target of 94 to 98%",
    "A benzodiazepine to settle him so that he tolerates the nebulizer"],
   ans:[0,1,2,3],
   rat:{c:"Nebulizers are driven by oxygen rather than air because he is hypoxemic, and ipratropium is added in severe episodes. Corticosteroids are the treatment that actually reverses the inflammatory component, but they take hours, which is why they are given early and not relied on for rescue. Magnesium sulfate is the established adjunct in severe and life-threatening asthma. The target saturation is 94 to 98%. Sedation is dangerous: it suppresses respiratory drive in a child already retaining carbon dioxide, and a calm, drowsy child with asthma is a child about to arrest.",
   o:["Correct — oxygen-driven salbutamol with ipratropium added for a severe episode.",
    "Correct — corticosteroids take hours to work, so they are given early and continued.",
    "Correct — intravenous magnesium sulfate is the established adjunct in severe and life-threatening asthma.",
    "Correct — the pediatric asthma target is 94 to 98%, not a permissive lower range.",
    "Sedation suppresses respiratory drive in a child already retaining carbon dioxide and is dangerous."],
   s:"Severe pediatric asthma: oxygen-driven nebulizers, early corticosteroid, magnesium as adjunct, target 94 to 98% — and never sedate. The calm drowsy asthmatic is the one about to arrest."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","assessment","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Apply high-flow oxygen, attach continuous monitoring and call for immediate senior review",
     "Give oxygen-driven nebulized salbutamol with ipratropium",
     "Give the systemic corticosteroid and the intravenous magnesium sulfate",
     "Prepare for intubation and ventilation and arrange intensive care transfer"],
    ans:[0,1,2,3]},
   rat:{c:"Oxygen, monitoring and senior review come first because hypoxemia is the immediate threat and escalation must start before the child arrests rather than after. Bronchodilation follows immediately, driven by oxygen rather than air. The corticosteroid and magnesium come next — the steroid is essential but slow, and magnesium buys time. Airway preparation and intensive care transfer come last in sequence but are prepared in parallel from the moment the deterioration is recognized, never started only when the child stops breathing.",
   o:["Oxygen, monitoring and senior review — hypoxemia first, escalation started immediately.",
    "Bronchodilation driven by oxygen, with ipratropium for a severe episode.",
    "Corticosteroid for the inflammation and magnesium as the adjunct.",
    "Airway preparation and transfer — prepared in parallel, executed if he continues to deteriorate."],
   s:"Asthma sequence: oxygen and escalation → oxygen-driven bronchodilators → corticosteroid and magnesium → airway preparation. Start the last step early; do not wait to need it."}},
  {step:"evaluate", t:"cloze", stem:"He improves after the magnesium and is discharged two days later on his preventer with a written action plan. Complete each evaluation statement.",
   reveal:["history","vitals","assessment","orders"],
   cloze:{lines:[
    {pre:"Before discharge the nurse recognizes that the most important element is ", post:".",
     opts:["a prescription for a nebulizer to use at home","a written personal asthma action plan with preventer adherence addressed, since his mother reports a month of missed preventer doses","a course of oral antibiotics for the preceding cold","advice to stop playing football until the winter is over"], ans:1},
    {pre:"He is using a pressurized metered-dose inhaler without a spacer, so the nurse ", post:".",
     opts:["reassures the family that this is the correct technique for his age","switches him to a dry powder device, which is easier for a child","demonstrates and checks the technique, and provides a spacer, since a device without a spacer delivers far less drug to the lungs in a child","tells him to take two puffs in quick succession to make up for it"], ans:2},
    {pre:"Because he has had a previous intensive care admission for asthma, the nurse recognizes that ", post:".",
     opts:["he is at increased risk of a fatal attack, so follow-up must be prompt and his risk documented","his previous admission means he has outgrown the severity","his risk is unchanged, since each attack is independent","he should be kept on oral corticosteroids permanently to prevent any further admission"], ans:0},
    {pre:"The nurse teaches his parents that the sign requiring emergency help immediately is ", post:".",
     opts:["a cough that wakes him at night once a week","needing his reliever more than twice a week","a cold with a runny nose in the winter months","being unable to speak in full sentences, or his reliever not lasting three hours"], ans:3}]},
   rat:{c:"A month of missed preventer doses is the modifiable cause of this admission, so a written action plan with adherence support is the intervention that prevents the next one — a home nebulizer delays presentation rather than helping. Children of this age need a spacer with a metered-dose inhaler, and technique must be demonstrated and checked rather than assumed. A previous intensive care admission is one of the strongest known risk factors for a fatal attack and must be documented and followed up promptly. And the parents need hard rules: inability to speak in full sentences, or a reliever that stops lasting three hours, means emergency help now — not a weekly night cough or a runny nose.",
   o:["A home nebulizer delays presentation and is not a substitute for an action plan.",
    "Correct — a written action plan plus preventer adherence addresses the actual cause of this admission.",
    "A preceding viral cold is the trigger, not a bacterial infection; antibiotics are not indicated.",
    "Exercise is encouraged with good control; withdrawal from sport is not the answer.",
    "Without a spacer, most of the dose impacts the oropharynx rather than reaching the lungs.",
    "Dry powder devices require an inspiratory effort most 8-year-olds cannot generate reliably.",
    "Correct — demonstrate and check technique, and provide a spacer; delivery without one is far poorer in a child.",
    "Two puffs in quick succession deposit in the mouth and throat rather than the lungs.",
    "Correct — a previous intensive care admission is a major risk factor for fatal asthma and must be documented and followed up.",
    "Severity does not resolve because one admission is behind him.",
    "A previous intensive care admission is one of the strongest predictors of a fatal attack.",
    "Permanent oral corticosteroids carry severe long-term harm and are a last resort, not routine prevention.",
    "A weekly night cough indicates poor control and needs review, not an emergency call.",
    "Reliever use more than twice a week indicates poor control and needs a preventer review.",
    "Colds trigger attacks but are not themselves an emergency.",
    "Correct — inability to speak in full sentences, or a reliever lasting under three hours, means emergency help immediately."],
   s:"Asthma discharge is won on three things: a written action plan, a spacer with checked technique, and hard emergency rules. A previous intensive care admission is the single strongest risk factor for a fatal attack — document it."}}]})
;
