/* RN Ready — case study v2 · variceal hemorrhage in cirrhosis.
   Twentieth unfolding case: a 54-year-old with alcohol-related cirrhosis
   vomits 400 mL of blood. Judgment unfolds from the counter-intuitive
   restrictive transfusion target, through antibiotics as the intervention with
   a mortality benefit, to why the INR must not be corrected and how encephal-
   opathy is precipitated by blood in the gut.

   Wave 66 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-VARIX-01", title:"The Hematemesis — Mr. Chukwu, 54",
 setting:"Emergency department / endoscopy unit", sys:"GI", cn:"PAA", d:3, b:0.55,
 summary:"54-year-old man with alcohol-related cirrhosis and known esophageal varices vomits 400 mL of fresh blood with melena, a hemoglobin of 6.8 g/dL and an INR of 1.7. Judgment unfolds from the counter-intuitive restrictive transfusion target, through antibiotics as the intervention with a mortality benefit, to why the INR must not be corrected and how blood in the gut precipitates encephalopathy.",
 exhibits:{
  history:{name:"History", type:"text", body:"54-year-old man with alcohol-related cirrhosis, Child-Pugh class B. Known esophageal varices last banded 14 months ago; he has not attended his last two surveillance endoscopies. Vomited approximately 400 mL of fresh red blood at home and has passed black tarry stools for two days. Currently drinking approximately 60 units of alcohol weekly; last drink yesterday evening. No non-steroidal anti-inflammatory drugs, no anticoagulants. Previous admissions for ascites. Reports two days of increasing drowsiness and reversed sleep pattern before the bleeding started."},
  vitals:{name:"Observations", type:"kv", rows:[["Heart rate","118/min"],["Blood pressure","94/58 mm Hg, postural drop to 78/48 on standing"],["Respiratory rate","22/min"],["SpO2 (room air)","96%"],["Core temperature","36.4 °C (97.5 °F)"],["Glasgow Coma Scale","14 — slow to respond, mild asterixis present"],["Capillary refill","3 seconds"]]},
  labs:{name:"Laboratory Results", type:"kv", rows:[["Hemoglobin","6.8 g/dL — was 11.2 g/dL three months ago"],["Platelets","78 x 10⁹/L"],["International normalized ratio","1.7"],["Bilirubin","42 µmol/L (2.5 mg/dL)"],["Albumin","26 g/L"],["Creatinine","96 µmol/L (1.09 mg/dL)"],["Sodium","131 mmol/L"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. Two large-bore intravenous cannulae; group and save, crossmatch 4 units. 2. RESTRICTIVE transfusion strategy — target hemoglobin 7 to 8 g/dL. Do NOT over-transfuse: raising the hemoglobin above target increases portal pressure and rebleeding. 3. Terlipressin 2 mg IV every 4 hours, started before endoscopy. 4. Ceftriaxone 1 g IV daily as antibiotic prophylaxis. 5. Urgent endoscopy within 12 hours for band ligation. 6. Airway protection considered before endoscopy if there is ongoing massive hematemesis or a reduced conscious level. 7. Do NOT give fresh frozen plasma to correct the international normalized ratio, and do not give platelets routinely. 8. Lactulose for encephalopathy. 9. Vitamin K 10 mg IV daily for three days. 10. Sengstaken-Blakemore tube and interventional radiology referral for a transjugular intrahepatic portosystemic shunt available if bleeding is refractory."}},
 items:[
  {step:"recognize", t:"single", stem:"His hemoglobin is 6.8 g/dL, down from 11.2 g/dL, and he is still bleeding. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","labs"],
   opts:["He needs transfusion to a hemoglobin above 10 g/dL, since normal values protect the organs during active bleeding",
    "A restrictive strategy targeting a hemoglobin of 7 to 8 g/dL is indicated, because over-transfusion raises portal pressure and increases rebleeding and mortality",
    "His international normalized ratio of 1.7 is the main problem, so fresh frozen plasma should be given before any transfusion",
    "The platelet count of 78 x 10⁹/L must be corrected to above 100 before endoscopy can proceed"],
   ans:1,
   rat:{c:"This is the counter-intuitive finding that the whole case turns on. In variceal bleeding, transfusing toward a normal hemoglobin increases portal venous pressure, dislodges clots at the varix and significantly increases rebleeding and death — so the target is deliberately 7 to 8 g/dL, not normal. Correcting the international normalized ratio with fresh frozen plasma is wrong for two reasons: the ratio does not reflect bleeding risk in cirrhosis, where pro- and anti-coagulant factors are both reduced and hemostasis is rebalanced, and the volume load raises portal pressure further. A platelet count of 78 is not a barrier to emergency endoscopy and routine correction is not indicated.",
   o:["Transfusing to a normal hemoglobin raises portal pressure and increases rebleeding and mortality.",
    "Correct — a restrictive target of 7 to 8 g/dL is the evidence-based strategy in variceal bleeding.",
    "The international normalized ratio does not reflect bleeding risk in cirrhosis, and fresh frozen plasma adds volume that raises portal pressure.",
    "A platelet count of 78 is not a barrier to emergency endoscopy; routine correction is not indicated."],
   s:"Variceal bleeding is the one hemorrhage where you deliberately under-transfuse: target hemoglobin 7-8 g/dL. Over-transfusion raises portal pressure, dislodges the clot and kills. And do not correct the INR with plasma."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals","labs"],
   hotspot:{mode:"rows", rows:[
    "Hemoglobin 6.8 g/dL, having been 11.2 g/dL",
    "Blood pressure 94/58 mm Hg with a postural drop to 78/48 mm Hg",
    "Platelets 78 x 10⁹/L",
    "Glasgow Coma Scale 14 with asterixis present",
    "Albumin 26 g/L",
    "Oxygen saturation 96% on room air"
   ], ans:[0,1,2,3,4]},
   rat:{c:"Five of the six are abnormal and each carries a different meaning: acute blood loss anemia, hypovolemic shock with a postural drop, thrombocytopenia from portal hypertension and hypersplenism, asterixis with a reduced conscious level indicating hepatic encephalopathy, and hypoalbuminemia reflecting synthetic liver failure. The asterixis is the finding to think hardest about, because blood in the gastrointestinal tract is digested into a large nitrogen load and is one of the commonest precipitants of encephalopathy — so the bleeding and the confusion are the same problem, not two. A saturation of 96% on room air is the single normal value.",
   o:["Expected hemoglobin is about 13–17 g/dL in men; a fall from 11.2 to 6.8 indicates major acute loss.",
    "Expected systolic pressure is above 100 mm Hg; 94/58 with a postural drop indicates hypovolemia.",
    "Expected platelets are 150–400 x 10⁹/L; 78 reflects portal hypertension and hypersplenism.",
    "Expected Glasgow Coma Scale is 15 with no asterixis; both indicate hepatic encephalopathy.",
    "Expected albumin is about 35–50 g/L; 26 indicates impaired hepatic synthesis.",
    "Normal saturation is 95% and above — within range."],
   s:"Asterixis in a bleeding cirrhotic is not a separate problem: blood in the gut is digested into nitrogen and precipitates encephalopathy. That is why lactulose is part of the bleeding plan, not an afterthought."}},
  {step:"prioritize", t:"single", stem:"He is still bleeding, hypotensive and drowsy. Which action by the nurse takes priority?",
   reveal:["history","vitals","labs","orders"],
   opts:["Send him for endoscopy immediately, since band ligation is the definitive treatment",
    "Give fresh frozen plasma to correct the international normalized ratio before any other treatment",
    "Resuscitate with large-bore access and a restrictive transfusion, start the terlipressin and the antibiotic, and protect the airway given his reduced conscious level",
    "Insert a Sengstaken-Blakemore tube, since balloon tamponade will stop the bleeding definitively"],
   ans:2,
   rat:{c:"Resuscitation comes first — access, a restrictive transfusion, and the two drugs started before endoscopy: terlipressin reduces portal pressure, and the antibiotic prophylaxis is the intervention with the clearest mortality benefit in this whole presentation. His reduced conscious level with ongoing hematemesis puts his airway at risk, so protection must be planned before he is laid flat for endoscopy. Sending him to endoscopy unresuscitated and with an unprotected airway is how arrests happen in the endoscopy suite. Fresh frozen plasma corrects a number rather than the bleeding and adds harmful volume. Balloon tamponade is a temporary bridge for refractory bleeding with a strict time limit, not a definitive treatment and never a first step.",
   o:["Endoscopy is definitive but he must be resuscitated and his airway protected before he is laid flat.",
    "Fresh frozen plasma corrects a number, not the bleeding, and the volume raises portal pressure.",
    "Correct — resuscitate with a restrictive transfusion, start terlipressin and the antibiotic, and protect the airway.",
    "Balloon tamponade is a temporary bridge for refractory bleeding with a strict time limit, never a first-line treatment."],
   s:"Before endoscopy in a variceal bleed: resuscitate to a hemoglobin of 7-8, start terlipressin AND the antibiotic, and protect the airway if consciousness is reduced. The antibiotic prophylaxis is the step most often missed and it saves lives."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["history","vitals","labs","orders"],
   opts:["Prophylactic antibiotics, since they reduce infection, rebleeding and mortality in cirrhotic upper gastrointestinal bleeding",
    "A vasoactive drug started before endoscopy to reduce portal venous pressure",
    "Lactulose, since blood in the gastrointestinal tract is digested into nitrogen and precipitates encephalopathy",
    "A restrictive transfusion target of 7 to 8 g/dL rather than correction to a normal hemoglobin",
    "Fresh frozen plasma to normalize the international normalized ratio before endoscopy"],
   ans:[0,1,2,3],
   rat:{c:"Antibiotic prophylaxis is the intervention with the strongest mortality evidence in cirrhotic gastrointestinal bleeding, and omitting it is a common and consequential error. A vasoactive drug started before endoscopy reduces portal pressure and improves the conditions for banding. Lactulose treats the encephalopathy that the bleeding itself has precipitated, since a gut full of blood is a large nitrogen load. The restrictive transfusion target is the strategy that avoids raising portal pressure. Normalizing the international normalized ratio with plasma is wrong: the ratio does not predict bleeding in cirrhosis, and the volume load is actively harmful.",
   o:["Correct — antibiotic prophylaxis reduces infection, rebleeding and mortality, and is easy to overlook.",
    "Correct — terlipressin started before endoscopy reduces portal pressure and improves banding conditions.",
    "Correct — blood in the gut is a nitrogen load, so lactulose treats the encephalopathy the bleeding caused.",
    "Correct — a target of 7 to 8 g/dL avoids the rise in portal pressure that causes rebleeding.",
    "The international normalized ratio does not predict bleeding in cirrhosis, and the plasma volume raises portal pressure."],
   s:"Variceal bleed bundle: restrictive transfusion, vasoactive drug, PROPHYLACTIC ANTIBIOTICS, lactulose, urgent banding. The antibiotics are the step that gets missed and they have a mortality benefit."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","labs","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Site two large-bore cannulae, send the group and save, and begin restrictive resuscitation",
     "Start the terlipressin and the prophylactic antibiotic, and give the lactulose",
     "Assess and protect the airway given the reduced conscious level and ongoing hematemesis",
     "Transfer for urgent endoscopy and band ligation, with balloon tamponade and interventional radiology available if it fails"],
    ans:[0,1,2,3]},
   rat:{c:"Access and resuscitation come first because everything else depends on circulation, and the transfusion is deliberately restricted to 7 to 8 g/dL rather than to normal. The vasoactive drug, the antibiotic and the lactulose follow immediately — all three are given before endoscopy, and the antibiotic is the one with the mortality benefit. Airway assessment and protection come next and must be resolved before he is positioned flat for the procedure, because a drowsy client vomiting blood will aspirate. Endoscopy comes last in the nursing sequence, with the rescue options — balloon tamponade as a strict time-limited bridge and a transjugular intrahepatic portosystemic shunt — arranged in advance rather than improvised.",
   o:["Access, group and save, and restrictive resuscitation — circulation first.",
    "Terlipressin, prophylactic antibiotic and lactulose, all before endoscopy.",
    "Airway protection before he is laid flat — a drowsy client vomiting blood will aspirate.",
    "Urgent endoscopy and banding, with tamponade and shunt arranged as the rescue."],
   s:"Variceal bleed sequence: access and restrictive resuscitation → vasoactive drug, antibiotic and lactulose → airway → endoscopy. Arrange the rescue options in advance; balloon tamponade is a time-limited bridge only."}},
  {step:"evaluate", t:"cloze", stem:"Banding achieves hemostasis. His hemoglobin is 7.6 g/dL on one unit. Twenty-four hours later he vomits fresh blood again and becomes more confused. Complete each evaluation statement.",
   reveal:["history","vitals","labs","orders"],
   cloze:{lines:[
    {pre:"He rebleeds 24 hours after banding, so the nurse ", post:".",
     opts:["reassures the team, since some oozing after banding is expected","transfuses him to a hemoglobin above 10 g/dL to compensate for the loss","escalates immediately for repeat endoscopy, restarts the vasoactive drug and prepares for balloon tamponade or a shunt if it continues","gives fresh frozen plasma, since rebleeding indicates a clotting problem"], ans:2},
    {pre:"His confusion has worsened since the bleed, so the nurse recognizes that ", post:".",
     opts:["blood in the gastrointestinal tract is digested into nitrogen and precipitates encephalopathy, so lactulose is continued and his conscious level is monitored closely","the confusion is caused by the anemia and will resolve with transfusion alone","he needs a sedative so that he settles and does not disturb his cannulae","encephalopathy is irreversible at this stage and requires no intervention"], ans:0},
    {pre:"Before discharge the nurse recognizes that secondary prevention must include ", post:".",
     opts:["nothing further, since the varices have been banded","a proton pump inhibitor alone, since acid suppression prevents rebleeding","routine fresh frozen plasma before every future procedure","a non-selective beta blocker plus repeated band ligation until the varices are eradicated, and alcohol cessation support"], ans:3},
    {pre:"Because he missed his last two surveillance endoscopies, the nurse's discharge teaching emphasizes that ", post:".",
     opts:["surveillance endoscopy is optional once varices have been banded","surveillance endoscopy is the reason this bleed was not prevented, so attendance is essential and he must know the signs that mean emergency attendance","he should attend only if he notices blood again","varices do not recur once they have been eradicated"], ans:1}]},
   rat:{c:"Rebleeding after banding occurs in a significant minority and is a genuine emergency: escalate for repeat endoscopy, restart the vasoactive drug, and have balloon tamponade and shunt options ready — while still transfusing restrictively to 7 to 8 g/dL rather than to normal. The worsening confusion is the encephalopathy that the bleeding precipitated, since a gut full of blood is a large nitrogen load, so lactulose continues and the conscious level is monitored; sedating him would both mask the encephalopathy and add to it. Secondary prevention is a non-selective beta blocker combined with band ligation until eradication, and alcohol cessation is the intervention that addresses the underlying cause. And his missed surveillance appointments are precisely why this happened — that history makes attendance the central teaching point.",
   o:["Oozing may occur, but fresh hematemesis 24 hours after banding is rebleeding and is an emergency.",
    "Transfusing above target raises portal pressure and increases further rebleeding.",
    "Correct — escalate for repeat endoscopy, restart the vasoactive drug, and prepare tamponade or shunt if it continues.",
    "The international normalized ratio does not explain or treat variceal rebleeding.",
    "Correct — blood in the gut is a nitrogen load that precipitates encephalopathy; continue lactulose and monitor.",
    "Anemia contributes, but the nitrogen load from the blood is the driver of the encephalopathy.",
    "Sedation masks and worsens encephalopathy and is contraindicated.",
    "Encephalopathy is usually reversible once the precipitant is treated.",
    "Banding treats this episode; it is not by itself long-term prevention.",
    "Acid suppression does not prevent variceal rebleeding.",
    "Routine plasma before procedures is not indicated and adds harmful volume.",
    "Correct — a non-selective beta blocker plus repeated banding until eradication, with alcohol cessation support.",
    "Surveillance is not optional; it is how recurrence is detected before it bleeds.",
    "Correct — his missed appointments are why this bleed was not prevented, so attendance and emergency signs are the teaching.",
    "Waiting for visible blood means waiting for a life-threatening rebleed.",
    "Varices recur, which is exactly why surveillance endoscopy continues."],
   s:"After a variceal bleed: rebleeding is an emergency needing repeat endoscopy, secondary prevention is a beta blocker plus banding until eradication, alcohol cessation addresses the cause — and surveillance endoscopy is what stops the next one."}}]})
;
