/* RN Ready — case study v2 · autonomic dysreflexia after spinal cord injury.
   Twenty-third unfolding case: a 34-year-old man with a T4 complete spinal cord
   injury develops a pounding headache, a blood pressure of 214/118 mm Hg and a
   heart rate of 48/min while sitting in his wheelchair with a blocked catheter.
   Judgment unfolds from the paradox of severe hypertension with bradycardia,
   through sitting him upright rather than flat, to finding and removing the
   noxious trigger.

   Wave 67 — RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-DYSREFLEXIA-01", title:"The Pounding Headache — Mr. Adeyemi, 34",
 setting:"Spinal injuries unit", sys:"NEURO", cn:"PAA", d:3, b:0.55,
 summary:"34-year-old man with a T4 complete spinal cord injury develops a pounding headache, a blood pressure of 214/118 mm Hg, a heart rate of 48/min, a flushed sweating face and a blocked urinary catheter. Judgment unfolds from the paradox of severe hypertension with bradycardia, through sitting him upright rather than flat, to finding and removing the noxious trigger.",
 exhibits:{
  history:{name:"History", type:"text", body:"34-year-old man with a T4 complete spinal cord injury sustained three years ago in a road traffic collision. Long-term indwelling urinary catheter, changed 14 days ago. Independent in his own care at home; admitted yesterday for a planned urological review. He calls the nurse to say his head is 'pounding like nothing I have had before' and that his vision is blurred. He also reports nasal congestion and says his skin feels hot above his chest. He has not opened his bowels for three days."},
  vitals:{name:"Observations", type:"kv", rows:[["Blood pressure (sitting)","214/118 mm Hg — his usual baseline is 96/58 mm Hg"],["Heart rate","48/min"],["Respiratory rate","16/min"],["Core temperature","36.8 °C (98.2 °F)"],["SpO2 (room air)","98%"],["Head and neck","Flushed, sweating profusely above the nipple line"],["Below the injury level","Pale, cool and dry with piloerection"],["Neurological","Alert, anxious, complains of a severe pounding headache and blurred vision"]]},
  assessment:{name:"Focused Assessment", type:"text", body:"Catheter drainage bag contains only 40 mL of dark, cloudy urine collected over the last 4 hours. The tubing is kinked under his thigh where he has been sitting on it, and there is visible sediment in the tube. Suprapubic region is dull to percussion and firm. Abdomen is distended. No pressure areas found on the sacrum, heels or ischial tuberosities. No ingrown toenails, no tight clothing, no constrictive abdominal binder. Last bowel action three days ago."},
  orders:{name:"Protocol", type:"text", body:"Autonomic dysreflexia pathway. 1. Sit the client upright immediately and lower the legs if possible — do NOT lay flat. 2. Loosen all tight clothing, socks, binders and compression stockings. 3. Check the bladder FIRST: unkink or change a blocked catheter, or catheterize using lidocaine gel. 4. If the bladder is dealt with and the blood pressure remains elevated, check the bowel for impaction using lidocaine gel. 5. Search for any other noxious stimulus below the level of injury. 6. Recheck the blood pressure every 5 minutes until it returns toward baseline. 7. If the systolic pressure remains above 150 mm Hg after the trigger is removed, give a rapid-onset short-acting antihypertensive as prescribed. 8. Document the episode and review the bowel and bladder regimen."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the observations and the focused assessment. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","assessment"],
   opts:["The blood pressure of 214/118 mm Hg with a heart rate of 48/min is a hypertensive emergency of essential hypertension and needs an intravenous antihypertensive at once",
    "The bradycardia shows he is deteriorating toward shock, so he should be laid flat and given fluid",
    "The headache and blurred vision indicate a stroke, so he needs an urgent computed tomography scan",
    "A noxious stimulus below his T4 injury is driving autonomic dysreflexia, and the blocked catheter is the likely trigger"],
   ans:3,
   rat:{c:"This is autonomic dysreflexia: an injury at T6 or above, a sudden rise in blood pressure far above his own baseline, a pounding headache, sweating and flushing above the level of injury with pale cool skin below it, nasal congestion, and a reflex bradycardia. A noxious stimulus below the lesion — here a kinked, blocked catheter with only 40 mL drained in four hours and a distended bladder — triggers an unopposed sympathetic surge below the injury that the brain cannot modulate. It is not essential hypertension; his baseline is 96/58 and the bradycardia is the baroreceptor reflex, not shock. And laying him flat would worsen the hypertension by increasing venous return.",
   o:["This is not essential hypertension — the rise is far above his own baseline and is driven by a stimulus below the lesion.",
    "The bradycardia is a baroreceptor reflex, not shock, and laying him flat would raise his blood pressure further.",
    "Headache and blurred vision here are features of the hypertensive surge, not a stroke.",
    "Correct — a noxious stimulus below T4 is driving autonomic dysreflexia, with the blocked catheter the likely trigger."],
   s:"Autonomic dysreflexia: injury at T6 or above, blood pressure far above the client's own baseline, pounding headache, sweating above the level with pale cool skin below, and reflex bradycardia. It is a true emergency — but the fix is removing the trigger."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals","assessment"],
   hotspot:{mode:"rows", rows:[
    "Blood pressure 214/118 mm Hg against a usual baseline of 96/58 mm Hg",
    "Heart rate 48/min",
    "Catheter bag containing only 40 mL of urine in 4 hours with kinked tubing",
    "Flushed sweating skin above the injury level with pale cool skin below it",
    "Oxygen saturation 98% on room air",
    "Core temperature 36.8 °C"
   ], ans:[0,1,2,3]},
   rat:{c:"The blood pressure rise against his own baseline is the defining abnormality — for a person with a high spinal cord injury a systolic pressure 20 to 40 mm Hg above baseline is already significant, so 214 mm Hg is extreme. The bradycardia is the reflex response to that surge. The kinked catheter with 40 mL in four hours and a distended bladder is the trigger. And the split skin picture — flushed and sweating above the injury, pale, cool and dry with piloerection below — is the physical sign of an unopposed sympathetic discharge that the brain cannot modulate below the lesion. A saturation of 98% and a temperature of 36.8 °C are both normal.",
   o:["Expected is his own baseline of around 96/58 mm Hg; 214/118 is far above it.",
    "Expected heart rate is 60–100/min; 48/min is the baroreceptor reflex to the surge.",
    "Expected is roughly 120–200 mL drained in 4 hours with free-flowing tubing; 40 mL with kinking indicates obstruction.",
    "Expected skin is uniform in colour, temperature and moisture above and below the injury.",
    "Normal saturation is 95% and above — within range.",
    "Expected core temperature is 36.5–37.5 °C — within range."],
   s:"In high spinal cord injury, judge blood pressure against the client's own baseline, not a population norm. Flushing and sweating above the level with pale cool skin below it is the signature of autonomic dysreflexia."}},
  {step:"prioritize", t:"single", stem:"Which action by the nurse takes priority?",
   reveal:["history","vitals","assessment","orders"],
   opts:["Lay him flat and raise his legs to improve cerebral perfusion",
    "Sit him upright, loosen tight clothing and relieve the bladder obstruction immediately",
    "Give an intravenous antihypertensive before anything else, since the blood pressure is the danger",
    "Call for an urgent computed tomography scan of the head before moving him"],
   ans:1,
   rat:{c:"Sitting upright drops the blood pressure by orthostatic pooling of blood in the legs, which is exactly the effect needed — laying flat does the opposite and increases venous return, raising intracranial pressure and the risk of a hemorrhagic stroke. Removing the trigger is the definitive treatment: unkinking or changing the blocked catheter, using lidocaine gel because sensation is absent but the reflex arc is not. An intravenous antihypertensive before the trigger is removed is wrong because once the stimulus is gone the blood pressure can fall rapidly and unpredictably; drugs are reserved for a systolic pressure still above 150 mm Hg after the trigger has been dealt with. And imaging before removing an obvious trigger wastes the critical minutes.",
   o:["Laying flat increases venous return and raises intracranial pressure — the opposite of what is needed.",
    "Correct — sit upright, loosen clothing, relieve the bladder obstruction: this is the definitive treatment.",
    "An antihypertensive before the trigger is removed risks a sudden fall once the stimulus is gone.",
    "Imaging before removing an obvious trigger wastes the critical minutes."],
   s:"In autonomic dysreflexia, sit the client UP — never flat — and remove the trigger. Laying flat is the instinct that causes harm. Antihypertensives are for a systolic pressure still above 150 after the trigger is gone."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["vitals","assessment","orders"],
   opts:["Sit him upright with the legs dependent and recheck the blood pressure every 5 minutes",
    "Relieve the bladder obstruction first, then check the bowel for impaction if the pressure remains raised",
    "Search systematically for any other noxious stimulus below the level of injury",
    "Keep a rapid-onset short-acting antihypertensive available for a systolic pressure above 150 mm Hg after the trigger is removed",
    "Restrict his fluids, since his urine output is low"],
   ans:[0,1,2,3],
   rat:{c:"Upright positioning with dependent legs and five-minute blood pressure checks continues until he is back toward his own baseline. Bladder comes before bowel because distension of the bladder is the commonest trigger by a wide margin; bowel impaction is checked next, and he has not opened his bowels for three days. A systematic search for other stimuli matters because episodes recur while any trigger remains — pressure areas, ingrown toenails, tight clothing and fractures are all causes. A short-acting agent must be to hand for a pressure that stays above 150 mm Hg after the trigger is removed, and short-acting is deliberate: a long-acting drug outlasts the resolved stimulus and causes hypotension. Fluid restriction is wrong — his output is low because the catheter is blocked, not because he is overloaded.",
   o:["Correct — upright with dependent legs, rechecking every 5 minutes until he returns toward baseline.",
    "Correct — bladder first as the commonest trigger, then bowel, especially with three days without a bowel action.",
    "Correct — a systematic search matters because any remaining stimulus will keep the episodes coming.",
    "Correct — a short-acting agent for a systolic pressure above 150 after trigger removal; short-acting is deliberate.",
    "His output is low because the catheter is blocked, not because he is fluid overloaded."],
   s:"Dysreflexia management: upright positioning, bladder then bowel, systematic search for other triggers, and a short-acting antihypertensive if needed. Short-acting is chosen deliberately — a long-acting drug outlasts the resolved stimulus."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","assessment","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Sit him upright with the legs dependent and loosen all tight clothing",
     "Unkink and, if needed, change the blocked catheter to relieve the bladder obstruction",
     "Recheck the blood pressure every 5 minutes and check the bowel for impaction if it remains raised",
     "Give a short-acting antihypertensive if the systolic pressure stays above 150 mm Hg, then review his bowel and bladder regimen"],
    ans:[0,1,2,3]},
   rat:{c:"Positioning comes first because it begins lowering the blood pressure within seconds and costs nothing. Removing the bladder obstruction follows immediately, since that is the definitive treatment and the trigger is sitting in plain sight. Rechecking every 5 minutes determines whether the pressure is settling; if it is not, the bowel is the next most likely trigger, and he has not opened his bowels for three days. A short-acting antihypertensive is used only for a pressure that stays above 150 mm Hg once the trigger has been removed, and the regimen review that follows is what prevents recurrence — a blocked catheter and three days of constipation are both preventable.",
   o:["Sit upright with dependent legs and loosen clothing — lowers pressure within seconds.",
    "Relieve the bladder obstruction — the definitive treatment.",
    "Recheck every 5 minutes; check the bowel if the pressure remains raised.",
    "Short-acting antihypertensive only if needed, then review the bowel and bladder regimen."],
   s:"Dysreflexia sequence: sit upright → relieve the bladder → reassess and check the bowel → antihypertensive only if still above 150 → review the regimen to prevent recurrence."}},
  {step:"evaluate", t:"cloze", stem:"After the catheter is changed, 600 mL of urine drains and his blood pressure falls to 108/64 mm Hg within ten minutes. Complete each evaluation statement.",
   reveal:["history","vitals","assessment","orders"],
   cloze:{lines:[
    {pre:"His blood pressure has returned close to his own baseline, so the nurse understands that ", post:".",
     opts:["the episode is over and no further monitoring is needed","the trigger has been removed and the response confirms the diagnosis, but monitoring continues because episodes can recur while any stimulus remains","his baseline blood pressure has permanently changed and a new target should be set","the antihypertensive worked and should be continued"], ans:1},
    {pre:"He is taught that a sudden pounding headache and flushing should make him ", post:".",
     opts:["lie down and wait for it to pass","take an analgesic and continue his usual activities","check his bladder and bowel immediately and sit upright, and call for help if the symptoms persist","reduce his fluid intake for the rest of the day"], ans:2},
    {pre:"Reviewing the cause, the nurse recognizes that prevention depends on ", post:".",
     opts:["a reliable catheter care and bowel regimen, since obstruction and constipation are the commonest triggers","a daily antihypertensive tablet","avoiding all physical activity","keeping his legs elevated whenever he sits out"], ans:0},
    {pre:"Before he goes home the nurse also recognizes that he needs ", post:".",
     opts:["no further information, since he has managed his own care for three years","written information on dysreflexia triggers and symptoms to share with any clinician who sees him, since not every clinician recognizes it","a prescription for a long-acting antihypertensive to keep on hand","advice to avoid catheterization in future"], ans:1}]},
   rat:{c:"The rapid fall after 600 mL drained confirms the diagnosis retrospectively and confirms that the trigger has been removed — but monitoring continues because episodes recur while any stimulus remains, and he is still three days constipated. He must be taught to sit upright and check bladder and bowel at the first pounding headache, because early self-management is what prevents a crisis. Prevention is a reliable catheter and bowel regimen, since obstruction and constipation are the commonest triggers; a daily antihypertensive treats the number and not the cause. And written information to share with any clinician matters because dysreflexia is frequently unrecognized by staff who do not work in spinal injury, and a raised blood pressure in this population is often misread as ordinary hypertension.",
   o:["Monitoring continues — episodes recur while any stimulus remains, and he is still constipated.",
    "Correct — the trigger is removed and the response confirms the diagnosis, but monitoring continues.",
    "His baseline is unchanged; this was an episode, not a new set point.",
    "No antihypertensive was given, and one is not indicated now that the pressure has fallen.",
    "Lying down raises blood pressure further and would worsen the episode.",
    "An analgesic treats the symptom and delays removal of the trigger.",
    "Correct — sit upright, check bladder and bowel immediately, and call for help if symptoms persist.",
    "Reducing fluids concentrates urine and increases the risk of catheter blockage.",
    "Correct — a reliable catheter care and bowel regimen addresses the commonest triggers.",
    "A daily antihypertensive treats the number, not the cause.",
    "Avoiding activity does not prevent obstruction or constipation.",
    "Elevated legs increase venous return and would raise blood pressure further.",
    "Three years of self-care did not prevent this episode, and not every clinician recognizes dysreflexia.",
    "Correct — written information to share with any clinician, because dysreflexia is often misread as ordinary hypertension.",
    "A long-acting agent is dangerous here; it outlasts a resolved stimulus and causes hypotension.",
    "Catheterization is often necessary; the answer is reliable care, not avoidance."],
   s:"Dysreflexia teaching: sit up and check bladder then bowel at the first pounding headache. Prevention is a reliable catheter and bowel regimen. Carry written information — a raised pressure in spinal cord injury is frequently misread as ordinary hypertension."}}]})
;
