/* RN Ready — case study v2 · suspected meningococcal meningitis.
   Twenty-sixth unfolding case: a 19-year-old university student presents with
   fever, severe headache, neck stiffness, photophobia and a non-blanching
   petechial rash. Judgment unfolds from recognizing meningococcal disease,
   through droplet precautions and antibiotics inside the hour without waiting
   for the lumbar puncture, to contact chemoprophylaxis and public health
   notification.

   Wave 67 — RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-MENING-01", title:"The Flatmate's Phone Call — Mr. Danjuma, 19",
 setting:"Emergency department", sys:"NEURO", cn:"SIC", d:3, b:0.55,
 summary:"19-year-old university student presents with fever, a severe headache, neck stiffness, photophobia and a non-blanching petechial rash, having shared a dormitory with a friend who has been unwell for two days. Judgment unfolds from recognizing meningococcal disease, through droplet precautions and antibiotics inside the hour without waiting for the lumbar puncture, to contact chemoprophylaxis and public health notification.",
 exhibits:{
  history:{name:"History", type:"text", body:"19-year-old male university student, brought in by his flatmate who says he was well yesterday evening and has deteriorated overnight. Symptoms: severe generalized headache, vomiting three times, intolerance of light, and increasing drowsiness. He mentions a rash that 'came up fast'. He shares a small dormitory with five other students, one of whom has been off with a fever and sore throat for two days. No significant past medical history, no immunocompromise, no recent travel. Fully vaccinated in childhood but he is not sure which vaccines."},
  vitals:{name:"Observations", type:"kv", rows:[["Core temperature","39.4 °C (102.9 °F)"],["Heart rate","118/min"],["Blood pressure","96/58 mm Hg"],["Respiratory rate","22/min"],["SpO2 (room air)","97%"],["Glasgow Coma Scale","14 — confused, opens eyes to voice, localizes to pain"],["Neck","Marked stiffness; unable to flex chin to chest"],["Skin","Non-blanching petechial rash over the trunk and both legs, spreading during the assessment"],["Limbs","Hands and feet cold; capillary refill 3 seconds"]]},
  labs:{name:"Laboratory Results", type:"kv", rows:[["White cell count","21,400/mm³ with a left shift"],["C-reactive protein","180 mg/L"],["Lactate","2.9 mmol/L"],["Glucose","4.1 mmol/L"],["Platelets","96 x 10⁹/L"],["Blood cultures","sent before the first antibiotic dose"],["Lumbar puncture","deferred pending review, since he is confused and deteriorating"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. Droplet precautions IMMEDIATELY: single room, door closed, mask for anyone entering — before any further assessment or transfer. 2. Blood cultures, then intravenous ceftriaxone within one hour. 3. Do NOT delay antibiotics for the lumbar puncture or for imaging. 4. Dexamethasone before or with the first antibiotic dose. 5. Careful intravenous fluids — enough for perfusion, but avoid overload given the risk of cerebral edema and the syndrome of inappropriate antidiuretic hormone secretion. 6. Hourly neurological observations; watch for raised intracranial pressure and seizures. 7. Lumbar puncture is deferred while he is confused and deteriorating — antibiotics are not held for it. 8. Notify public health immediately. 9. Identify close contacts, including the five dormitory flatmates, for chemoprophylaxis. 10. Intensive care referral if the Glasgow Coma Scale falls or the blood pressure drops."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the history and observations. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","labs"],
   opts:["A viral illness with a heat rash, so supportive care and discharge with safety-netting advice are appropriate",
    "Migraine with a concurrent fever, so an analgesic and an antiemetic are the priority",
    "Suspected meningococcal meningitis with meningococcaemia, which is an emergency requiring immediate isolation and antibiotics",
    "Influenza, since his flatmate has had a fever and sore throat, so he needs droplet precautions only if he becomes more unwell"],
   ans:2,
   rat:{c:"Fever with severe headache, neck stiffness, photophobia, vomiting and reduced consciousness is meningitis, and the non-blanching petechial rash that is spreading during the assessment adds meningococcaemia — the rash is the sign that this is invasive meningococcal disease rather than a self-limiting illness. The cold peripheries, a capillary refill of 3 seconds, a falling platelet count and a raised lactate show early septic shock. Discharge with safety-netting in a deteriorating, confused client with a spreading non-blanching rash is unsafe. And isolation is not conditional on deterioration: it is required from the moment the diagnosis is suspected.",
   o:["A non-blanching spreading rash with neck stiffness and confusion is not a heat rash, and discharge would be unsafe.",
    "Migraine does not cause fever, neck stiffness or a non-blanching rash.",
    "Correct — meningitis with meningococcaemia is an emergency needing immediate isolation and antibiotics.",
    "Isolation is required from the moment the diagnosis is suspected, not conditional on deterioration."],
   s:"A non-blanching rash with fever, neck stiffness and altered consciousness is meningococcal disease until proven otherwise. Isolate immediately and treat inside the hour — the rash spreading during your assessment is the sign to move fastest."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals","labs"],
   hotspot:{mode:"rows", rows:[
    "Neck stiffness with inability to flex the chin to the chest",
    "Non-blanching petechial rash spreading over the trunk and legs",
    "Glasgow Coma Scale 14 with confusion",
    "Platelets 96 x 10⁹/L and a lactate of 2.9 mmol/L",
    "Oxygen saturation 97% on room air",
    "Core temperature 39.4 °C"
   ], ans:[0,1,2,3]},
   rat:{c:"Neck stiffness is meningeal irritation, the non-blanching rash is vasculitis from meningococcaemia, a Glasgow Coma Scale of 14 with confusion shows the brain is affected, and the falling platelets with a raised lactate show early disseminated intravascular coagulation and hypoperfusion. Those four are the abnormal findings that make this an emergency. A saturation of 97% on room air is normal. A temperature of 39.4 °C is abnormal but is the least specific finding of the six — on its own a high fever tells you very little, and the reason it is included is to make the point that the meningism, the rash and the reduced consciousness are what carry the diagnosis.",
   o:["Expected is full neck flexion without pain; stiffness indicates meningeal irritation.",
    "Expected skin blanches under pressure; a non-blanching petechial rash indicates meningococcaemia.",
    "Expected Glasgow Coma Scale is 15; 14 with confusion indicates cerebral involvement.",
    "Expected platelets are 150–400 x 10⁹/L and lactate under 2.0 mmol/L; both are abnormal, indicating coagulopathy and hypoperfusion.",
    "Normal saturation is 95% and above — within range.",
    "39.4 °C is abnormal but the least specific of the six; the meningism, rash and reduced consciousness carry the diagnosis."],
   s:"Meningitis is recognized by the combination, not the fever: meningism, a non-blanching rash, and altered consciousness. Falling platelets with a raised lactate tell you meningococcaemia has already become systemic."}},
  {step:"prioritize", t:"single", stem:"The lumbar puncture cannot be performed for at least two hours because he is confused and imaging has been requested. Which action by the nurse takes priority?",
   reveal:["history","vitals","labs","orders"],
   opts:["Place him in droplet precautions and give intravenous ceftriaxone within the hour, without waiting for the lumbar puncture",
    "Wait for the lumbar puncture so the cerebrospinal fluid is not sterilized before sampling",
    "Give intravenous dexamethasone alone and reassess, since steroids reduce the inflammation",
    "Arrange transfer to the intensive care unit before giving any medication"],
   ans:0,
   rat:{c:"Isolation comes first because meningococcal disease spreads by respiratory droplets and every unprotected contact in a busy department is at risk — the room and the mask take a minute and protect everyone else. Antibiotics follow inside the hour, because delay is the strongest modifiable predictor of death and a lumbar puncture must never hold them up; blood cultures taken beforehand preserve most of the diagnostic yield, and the cerebrospinal fluid can still be interpreted after antibiotics have started. Dexamethasone is given before or with the first antibiotic dose, but alone it treats nothing. And transfer before treatment wastes the critical hour — he is treated where he is.",
   o:["Correct — isolate immediately and give ceftriaxone within the hour; the lumbar puncture must never delay antibiotics.",
    "Waiting for a lumbar puncture trades the strongest modifiable survival factor for a cleaner sample.",
    "Dexamethasone is adjunctive and is given with the antibiotic, not instead of it.",
    "Transfer before treatment wastes the critical hour; treat where he is."],
   s:"In suspected meningitis: isolate first, then antibiotics within the hour. Never delay antibiotics for a lumbar puncture or for imaging — blood cultures first preserve most of the yield, and delay kills."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["history","vitals","labs","orders"],
   opts:["Droplet precautions with a single room, the door closed and a mask for anyone entering",
    "Dexamethasone before or with the first antibiotic dose, to reduce neurological complications",
    "Careful intravenous fluids, avoiding overload given the risk of cerebral edema and the syndrome of inappropriate antidiuretic hormone secretion",
    "Notification of public health and chemoprophylaxis for the five dormitory flatmates",
    "Withholding antibiotics until the rash has been photographed and documented"],
   ans:[0,1,2,3],
   rat:{c:"Droplet precautions are required from the moment the diagnosis is suspected. Dexamethasone given before or with the first antibiotic dose reduces hearing loss and neurological sequelae, which is why the timing matters rather than the drug being given at some point later. Fluids are genuinely difficult here: he needs perfusion because of the septic physiology, but cerebral edema and the syndrome of inappropriate antidiuretic hormone secretion both make overload dangerous, so the volume is titrated against perfusion endpoints rather than given to a fixed protocol. Public health notification and chemoprophylaxis for close contacts are essential — his five flatmates share a small dormitory and are at real risk. Documentation of the rash is useful but never delays treatment.",
   o:["Correct — droplet precautions from the moment the diagnosis is suspected.",
    "Correct — before or with the first dose, which is what reduces hearing loss and neurological sequelae.",
    "Correct — perfusion is needed, but cerebral edema and inappropriate antidiuretic hormone secretion make overload dangerous.",
    "Correct — notification and chemoprophylaxis protect close contacts sharing a small dormitory.",
    "Documentation never delays antibiotics; photograph the rash only if it can be done at the same time."],
   s:"Meningitis bundle: droplet precautions, antibiotics within the hour, dexamethasone with the first dose, fluids titrated carefully, and contact chemoprophylaxis with public health notification. The contacts are part of the treatment plan, not an afterthought."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","labs","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Place him in a single room on droplet precautions with the door closed",
     "Take blood cultures and give intravenous ceftriaxone within the hour, with dexamethasone before or alongside it",
     "Start hourly neurological observations and titrate fluids against perfusion, avoiding overload",
     "Notify public health and arrange chemoprophylaxis for the dormitory flatmates"],
    ans:[0,1,2,3]},
   rat:{c:"Isolation comes first, because protecting everyone else in the department takes a minute and the risk to them begins immediately. Cultures and antibiotics follow within the hour with dexamethasone timed before or alongside the first dose. Hourly neurological observations and careful fluid titration come next, since a falling Glasgow Coma Scale is the warning that intracranial pressure is rising and fluids must be balanced against both septic physiology and cerebral edema. Notification and contact prophylaxis come last in this sequence, but they are not optional — his five flatmates are at risk from the same exposure that made him ill.",
   o:["Droplet precautions in a single room first — the risk to others begins immediately.",
    "Blood cultures, then ceftriaxone within the hour, with dexamethasone timed before or alongside.",
    "Hourly neurological observations and fluids titrated against perfusion.",
    "Notify public health and arrange chemoprophylaxis for the dormitory contacts."],
   s:"Meningitis sequence: isolate → cultures and antibiotics with dexamethasone → hourly neurology and careful fluids → public health and contact prophylaxis. Isolation is first because it protects everyone else."}},
  {step:"evaluate", t:"cloze", stem:"Eight hours later his Glasgow Coma Scale is 15, his temperature is 37.8 °C and the rash is fading. His flatmate calls to ask whether the other students in the dormitory need any treatment. Complete each evaluation statement.",
   reveal:["history","vitals","labs","orders"],
   cloze:{lines:[
    {pre:"The flatmate asks whether the other students need treatment, so the nurse explains that ", post:".",
     opts:["close contacts need chemoprophylaxis and public health will coordinate it, since household and close residential contacts are at increased risk of the same infection","only he needs treatment, since the others are currently well","they should all be vaccinated and nothing else is required","they need antibiotics only if they develop a rash"], ans:0},
    {pre:"He is now afebrile and his Glasgow Coma Scale is 15, so the nurse understands that ", post:".",
     opts:["antibiotics can be stopped, since he has clearly responded","the course is completed as prescribed, since early discontinuation risks relapse and the cerebrospinal fluid may still be infected","he can be discharged today with oral antibiotics","he only needs treatment until his rash has fully cleared"], ans:1},
    {pre:"Throughout his admission the nurse performed hourly neurological observations because ", post:".",
     opts:["they are required for every emergency admission","a falling Glasgow Coma Scale is the earliest warning of rising intracranial pressure, which can develop rapidly in meningitis","they detect the spread of the rash","they monitor his response to the dexamethasone alone"], ans:1},
    {pre:"Reviewing his fluid balance, the nurse recognizes that care was needed because ", post:".",
     opts:["he was at risk of dehydration from vomiting, so large volumes were essential","cerebral edema and the syndrome of inappropriate antidiuretic hormone secretion make fluid overload dangerous, so volume is titrated against perfusion rather than given freely","fluid restriction is always required in meningitis","his platelet count made fluid administration unsafe"], ans:1}]},
   rat:{c:"Close contacts need chemoprophylaxis, and public health coordinates it — household and close residential contacts are at increased risk of the same infection, which is why the five flatmates are part of the plan. The antibiotic course is completed as prescribed, because an afebrile client with a normal Glasgow Coma Scale has not been cured by eight hours of treatment and early discontinuation risks relapse. Hourly neurological observations matter because a falling Glasgow Coma Scale is the earliest warning of rising intracranial pressure, which can develop rapidly and changes the whole management. And fluids are genuinely difficult: cerebral edema and inappropriate antidiuretic hormone secretion both make overload dangerous, so volume is titrated against perfusion endpoints rather than given freely or withheld altogether.",
   o:["Being well now does not remove the risk carried by close contacts.",
    "Correct — close contacts need chemoprophylaxis, coordinated by public health.",
    "Vaccination may be advised, but chemoprophylaxis is what protects contacts immediately.",
    "Waiting for a rash means waiting for invasive disease.",
    "Response to treatment is not a reason to stop the course.",
    "Correct — complete the course as prescribed; early discontinuation risks relapse.",
    "Same-day discharge with oral antibiotics is unsafe after meningococcaemia.",
    "Rash clearance is not the endpoint of treatment.",
    "Hourly neurology is driven by the risk of raised intracranial pressure, not by routine.",
    "Correct — a falling Glasgow Coma Scale is the earliest warning of rising intracranial pressure.",
    "Neurological observations do not track the rash.",
    "They monitor intracranial pressure, not the steroid response alone.",
    "Large fixed volumes are dangerous with cerebral edema and inappropriate antidiuretic hormone secretion.",
    "Correct — cerebral edema and inappropriate antidiuretic hormone secretion make overload dangerous, so volume is titrated against perfusion.",
    "Fluid is needed for perfusion; blanket restriction is also unsafe.",
    "The platelet count does not contraindicate fluid administration."],
   s:"Meningitis endgame: complete the antibiotic course, keep hourly neurological observations for raised intracranial pressure, titrate fluids against perfusion, and treat the close contacts with chemoprophylaxis — protecting the contacts is part of the treatment."}}]})
;
