/* RN Ready — case study v2 · neutropenic sepsis.
   Twelfth unfolding case: a 22-year-old on day nine of induction chemotherapy
   for acute lymphoblastic leukemia develops a fever. Judgment unfolds from
   recognizing that a single temperature with no localizing signs IS the
   emergency, through the 60-minute antibiotic rule, to the platelet-driven
   precautions and what to teach at discharge.

   Wave 62 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-NEUTRO-01", title:"Day Nine — Daniel, 22",
 setting:"Oncology unit / emergency department", sys:"HEME", cn:"SIC", d:3, b:0.55,
 summary:"22-year-old on day nine of induction chemotherapy for acute lymphoblastic leukemia presents with a temperature of 38.4 °C and no localizing symptoms, neutrophils 0.2 x 10^9/L and a central venous catheter in situ. Judgment unfolds from recognizing fever alone as the emergency, through the 60-minute antibiotic rule, to thrombocytopenia precautions and discharge teaching.",
 exhibits:{
  history:{name:"History & Presentation", type:"text", body:"22-year-old man with acute lymphoblastic leukemia, day nine after the start of induction chemotherapy. Called in by the oncology triage line after recording 38.4 °C at home this morning. Reports feeling 'achy and washed out' with a mild sore throat. No cough, no shortness of breath, no urinary symptoms, no diarrhea, no vomiting. Central venous catheter inserted before chemotherapy; the exit site looks clean and is not tender. Lives with his mother, who is well. No recent travel. Prophylactic aciclovir and co-trimoxazole as prescribed."},
  vitals:{name:"Vital Signs (on arrival)", type:"kv", rows:[["Temperature","38.4 °C (101.1 °F)"],["Heart rate","112/min"],["Respiratory rate","24/min"],["Blood pressure","100/62 mm Hg"],["SpO2 (room air)","96%"],["Pain","2/10 sore throat"],["Capillary refill","2 seconds"]]},
  labs:{name:"Laboratory Results", type:"kv", rows:[["Neutrophils","0.2 x 10⁹/L (0.2 x 10³/µL)"],["White cell count","0.8 x 10⁹/L"],["Hemoglobin","8.9 g/dL"],["Platelets","42 x 10⁹/L"],["Lactate","2.4 mmol/L"],["C-reactive protein","68 mg/L"],["Creatinine","92 µmol/L (1.04 mg/dL)"],["Blood cultures","Two sets requested — from the catheter lumen and peripherally"]]},
  protocol:{name:"Neutropenic Sepsis Pathway", type:"text", body:"Definition: neutrophils below 0.5 x 10⁹/L with a single temperature of 38.3 °C or above, or 38.0 °C or above sustained over one hour. 1. Treat as sepsis immediately — do not wait for a source. 2. Intravenous broad-spectrum antibiotics (piperacillin-tazobactam 4.5 g) within 60 minutes of arrival. 3. Blood cultures from the catheter lumen AND peripherally before antibiotics, but never delay the antibiotic to obtain them. 4. Full sepsis screen: chest radiograph, urine culture, throat swab, catheter exit-site swab if indicated. 5. Intravenous fluids and repeat lactate. 6. Protective isolation with meticulous hand hygiene; the client wears a mask when off the unit. 7. NO rectal temperatures, suppositories or digital rectal examination. 8. Non-alcohol mouthwash and oral assessment every shift. 9. Escalate immediately for any deterioration. 10. Review antibiotic choice against culture results and neutrophil recovery."},
  notes:{name:"Nurse's Notes", type:"text", body:"1120: Arrives with his mother. States 'I know I should come in for a temperature, but I have no idea where an infection would even be.' Catheter exit site inspected — clean, dry, not tender, no tracking erythema. Oropharynx mildly erythematous without exudate; no mucositis scored yet. 1135: Blood cultures taken from the catheter lumen and peripherally. Antibiotic drawn up. 1340: Temperature 37.8 °C, heart rate 98/min, blood pressure 108/68 mm Hg, repeat lactate 1.6 mmol/L. Mother asks whether he can go home now that the fever has come down."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the presentation. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","labs","notes"],
   opts:["A single temperature of 38.4 °C with neutrophils below 0.5 x 10⁹/L meets the definition of neutropenic sepsis and requires treatment within the hour",
    "The clean catheter exit site and the absence of localizing symptoms make sepsis unlikely",
    "The raised C-reactive protein confirms a viral infection, so observation is appropriate rather than antibiotics",
    "His blood pressure of 100/62 mm Hg means he is not septic, since sepsis requires hypotension"],
   ans:0,
   rat:{c:"Neutrophils of 0.2 x 10⁹/L with a single temperature of 38.4 °C meets the pathway definition exactly, and treatment is required within 60 minutes. Neutropenic clients cannot mount an inflammatory response, so they frequently have no localizing signs, no exudate and no consolidation even with overwhelming infection — the absence of a source is the expected picture, not reassuring evidence. C-reactive protein cannot distinguish bacterial from viral, and a raised value in a neutropenic client with fever is an argument for antibiotics, not against them. Hypotension is a late sign; waiting for it means waiting for the client to be near death.",
   o:["Correct — neutrophils below 0.5 with a single temperature above 38.3 °C is neutropenic sepsis until proven otherwise.",
    "Neutropenic clients cannot mount a localizing response; a clean site and no focal symptoms are the expected picture, not reassurance.",
    "C-reactive protein does not distinguish bacterial from viral infection and never justifies withholding antibiotics here.",
    "Hypotension is a late sign of septic shock; blood pressure is the last thing to fall, especially in a young client."],
   s:"In neutropenia, fever alone is the emergency. No source will be found, no pus will form, and hypotension arrives late — the single temperature is the whole trigger."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals","labs"],
   hotspot:{mode:"rows", rows:[
    "Neutrophils 0.2 x 10⁹/L",
    "Temperature 38.4 °C",
    "Lactate 2.4 mmol/L",
    "Platelets 42 x 10⁹/L",
    "Oxygen saturation 96% on room air",
    "Creatinine 92 µmol/L"
   ], ans:[0,1,2,3]},
   rat:{c:"Severe neutropenia, fever, a raised lactate indicating impaired perfusion and thrombocytopenia are all abnormal, and together they define both the emergency and the precautions. The neutrophil count is the number that makes a temperature a life-threatening event, and the platelet count of 42 x 10⁹/L is what makes rectal interventions and intramuscular injections dangerous. A saturation of 96% on room air and a creatinine of 92 µmol/L are both within expected limits — two planted normals.",
   o:["Expected neutrophils are 2.0–7.5 x 10⁹/L; below 0.5 is severe neutropenia and defines the pathway.",
    "A single temperature above 38.3 °C in this context is the trigger for the whole pathway.",
    "Expected lactate is under 2.0 mmol/L; 2.4 indicates impaired tissue perfusion.",
    "Expected platelets are 150–400 x 10⁹/L; 42 is thrombocytopenia and changes every invasive precaution.",
    "Normal saturation is 95% and above — within range.",
    "Normal creatinine is roughly 60–110 µmol/L — within range."],
   s:"In the neutropenic client, read the neutrophil count and the platelet count together: the first tells you a fever is an emergency, the second tells you which routine procedures are now dangerous."}},
  {step:"prioritize", t:"single", stem:"Which action by the nurse takes priority?",
   reveal:["history","vitals","labs","protocol","notes"],
   opts:["Wait for the blood culture result so that the antibiotic chosen is targeted",
    "Give intravenous broad-spectrum antibiotics within 60 minutes, taking blood cultures first provided that does not delay the dose",
    "Give an antipyretic and recheck the temperature in four hours to see whether it persists",
    "Remove the central venous catheter immediately, since it is the most likely source"],
   ans:1,
   rat:{c:"Delay in antibiotics is the strongest modifiable predictor of death in neutropenic sepsis, so the 60-minute target governs everything; cultures are taken first because they guide later de-escalation, but never at the cost of the hour. Waiting for a culture result means waiting 24 to 48 hours while an untreated infection progresses. An antipyretic masks the only sign this client produces and four hours of observation is a window in which he can die. Catheter removal is a team decision based on culture results and exit-site findings, and removing it now would destroy venous access he needs — a clean, non-tender site does not justify it.",
   o:["Culture results take 24 to 48 hours; waiting is not compatible with survival.",
    "Correct — antibiotics within 60 minutes, with cultures taken first only where that does not delay the dose.",
    "An antipyretic suppresses the single sign this client produces, and four hours is long enough to deteriorate irreversibly.",
    "Catheter removal is a team decision guided by cultures and site findings; a clean site does not justify it, and he needs the access."],
   s:"The 60-minute antibiotic rule is the single most examinable number in neutropenic sepsis. Cultures first, but never at the cost of the hour — and never mask the fever."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["history","vitals","labs","protocol","notes"],
   opts:["Blood cultures from the catheter lumen and peripherally, plus a chest radiograph, urine culture and throat swab",
    "Protective isolation with meticulous hand hygiene, and a mask for the client whenever he leaves the unit",
    "Avoiding rectal temperatures, suppositories and digital rectal examination",
    "Non-alcohol mouthwash with oral assessment every shift, since mucositis is a common portal of entry",
    "Withholding the antibiotic until a repeat neutrophil count confirms the first result"],
   ans:[0,1,2,3],
   rat:{c:"A full sepsis screen including catheter and peripheral cultures establishes the source and allows de-escalation later. Protective isolation and hand hygiene reduce exposure in a client with essentially no neutrophil defense. Rectal interventions are avoided because the mucosa is fragile and the platelet count of 42 x 10⁹/L makes bleeding and bacterial translocation a real risk. Meticulous mouth care matters because mucositis is one of the commonest portals of entry in chemotherapy patients. Repeating the count delays antibiotics for a result that will not change the immediate decision.",
   o:["Correct — catheter and peripheral cultures plus a full screen identify the source and allow later de-escalation.",
    "Correct — protective isolation and hand hygiene limit exposure in a client with almost no neutrophil defense.",
    "Correct — rectal procedures risk mucosal trauma, bleeding and bacterial translocation with a platelet count of 42.",
    "Correct — mucositis is a common portal of entry, and alcohol mouthwash further damages the mucosa.",
    "Repeating the count delays the antibiotic for a result that will not change the immediate management."],
   s:"Neutropenic precautions are driven by two counts: the neutrophils mean isolate and treat fast, the platelets mean no rectal anything and no intramuscular injections."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","labs","protocol","notes"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Recognize neutropenic sepsis, activate the pathway and call for senior review",
     "Take blood cultures from the catheter lumen and peripherally and complete the rest of the sepsis screen",
     "Give intravenous broad-spectrum antibiotics within 60 minutes of arrival",
     "Give intravenous fluids, repeat the lactate and monitor continuously for deterioration"],
    ans:[0,1,2,3]},
   rat:{c:"Recognition and activation come first because the clock starts at the temperature, not at the diagnosis, and senior review brings the escalation route into play early. Cultures and the screen follow immediately so that the antibiotic is not given blind if it can be avoided in seconds. The antibiotic then goes in within the hour. Fluids, lactate clearance and continuous monitoring run afterwards and continue, because deterioration in a neutropenic client can be swift and without the usual warning signs.",
   o:["Recognition and pathway activation start the clock; senior review brings escalation into play early.",
    "Cultures and screen are taken next — seconds, not at the cost of the hour.",
    "The antibiotic goes in within 60 minutes of arrival.",
    "Fluids, lactate clearance and continuous monitoring follow and continue throughout."],
   s:"Neutropenic sepsis sequence: recognize and activate → cultures and screen → antibiotic within the hour → fluids and relentless monitoring. The clock starts at the temperature."}},
  {step:"evaluate", t:"cloze", stem:"At 1340 his temperature is 37.8 °C, his heart rate is 98/min, his blood pressure is 108/68 mm Hg and the repeat lactate is 1.6 mmol/L. His mother asks whether he can go home. Complete each evaluation statement.",
   reveal:["history","vitals","labs","protocol","notes"],
   cloze:{lines:[
    {pre:"His observations have improved after the first antibiotic dose, so the nurse understands that ", post:".",
     opts:["the antibiotic can be stopped because he is clearly improving","the fever was not clinically significant after all","antibiotics continue until neutrophil recovery and clinical resolution, regardless of this early improvement","he can be discharged on oral antibiotics to finish the course at home"], ans:2},
    {pre:"With a platelet count of 42 x 10⁹/L, the nurse ", post:".",
     opts:["gives aspirin for his headache","performs a digital rectal examination to check for occult blood","encourages vigorous flossing to prevent mucositis","avoids intramuscular injections and uses a soft toothbrush and an electric razor"], ans:3},
    {pre:"On day three he spikes to 38.6 °C again with a new erythematous, tender area around the catheter exit site, so the nurse ", post:".",
     opts:["documents it as an expected reaction to chemotherapy","escalates immediately, because an exit-site or tunnel infection may require catheter removal and a change of antibiotic","applies a warm compress and continues the current plan","removes the catheter herself and sends the tip to the laboratory"], ans:1},
    {pre:"Before discharge once his count has recovered, the nurse teaches him to ", post:".",
     opts:["present immediately for any temperature above 38 °C or for feeling unwell even without a fever, and to keep taking his temperature regularly","avoid all contact with other people permanently","stop his prophylactic medicines as soon as he feels well","treat a fever at home with paracetamol and rest"], ans:0}]},
   rat:{c:"Early improvement after the first dose says nothing about clearance: antibiotics continue until the neutrophils recover and the client is clinically resolved, which is usually a matter of days, not hours. A platelet count of 42 x 10⁹/L dictates bleeding precautions — no intramuscular injections, a soft toothbrush and an electric razor — and makes rectal examination and aspirin actively dangerous. A second fever with a tender, erythematous exit site on day three is a new and specific problem suggesting catheter-related infection, which changes both the antibiotic and possibly the catheter, so it is escalated immediately rather than absorbed into the current plan. And the discharge teaching that saves lives is the rule about temperature and feeling unwell, because the next episode will look exactly like this one.",
   o:["Early improvement does not mean clearance; stopping now invites relapse and resistance.",
    "A fever with neutrophils of 0.2 was significant by definition, whatever happens next.",
    "Correct — antibiotics continue until neutrophil recovery and clinical resolution.",
    "Discharge on oral antibiotics requires count recovery, clinical stability and a clear team decision.",
    "Aspirin inhibits platelet function and is dangerous at a platelet count of 42.",
    "Rectal examination is specifically contraindicated — mucosal trauma, bleeding and bacterial translocation.",
    "Vigorous flossing causes gingival bleeding at this platelet count; gentle cleaning only.",
    "Correct — bleeding precautions follow the platelet count: no IM injections, soft toothbrush, electric razor.",
    "Chemotherapy reactions do not present as a focal tender erythematous exit site with a new fever.",
    "Correct — a new exit-site infection changes the antibiotic and may require catheter removal; escalate now.",
    "A warm compress delays the escalation that a suspected catheter infection requires.",
    "Catheter removal is a medical decision performed under specific conditions, not an independent nursing action.",
    "Correct — the temperature rule and the 'feeling unwell' rule are the discharge teaching that prevents the next death.",
    "Permanent isolation is neither achievable nor indicated once the count recovers.",
    "Prophylactic antimicrobials are prescribed for a defined period, not stopped on how the client feels.",
    "Treating a fever at home is exactly the delay that makes neutropenic sepsis fatal."],
   s:"Three rules for the neutropenic client: antibiotics run to count recovery, not to the first normal temperature; the platelet count dictates every invasive precaution; and a new fever with a focal sign on day three is a new problem, not the old one settling."}}]})
;
