/* RN Ready — case study v2 · acute ischemic stroke.
   Eighth unfolding case: a 62-year-old with untreated atrial fibrillation is
   found with right-sided weakness. Judgment unfolds from the last-known-well
   time that governs thrombolysis, through the blood pressure threshold and the
   24-hour antiplatelet ban, to swallow screening and secondary prevention.

   Wave 61 — case studies are the exclusive focus for waves 61-66.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-STROKE-01", title:"Last Known Well — Mr. Adeyemi, 62",
 setting:"Emergency department", sys:"NEURO", cn:"PAA", d:3, b:0.55,
 summary:"62-year-old man with atrial fibrillation off anticoagulation, last known well 07:15 and found at 09:40 with right-sided weakness and dysarthria. Judgment unfolds from establishing the treatment window, through the blood pressure threshold before thrombolysis and the 24-hour antiplatelet ban, to swallow screening and secondary prevention.",
 exhibits:{
  history:{name:"History & Presentation", type:"text", body:"62-year-old man. His wife left for work at 07:15 when he was completely well, having breakfast and reading the paper. A neighbour found him at 09:40 sitting slumped in the same chair, unable to hold a cup in his right hand and speaking indistinctly. Ambulance called immediately; arrives in the emergency department at 10:05. History: hypertension, atrial fibrillation, type 2 diabetes. He stopped taking apixaban three weeks ago because it 'upset his stomach' and has taken nothing since. No recent surgery, no head injury, no previous stroke, no active bleeding, no known bleeding disorder."},
  vitals:{name:"Vital Signs (on arrival)", type:"kv", rows:[["Temperature","36.8 °C (98.2 °F)"],["Heart rate","96/min, irregularly irregular"],["Respiratory rate","16/min"],["Blood pressure","188/104 mm Hg"],["SpO2 (room air)","95%"],["Capillary glucose","14.2 mmol/L (256 mg/dL)"],["Glasgow Coma Scale","15 (E4 V5 M6)"]]},
  findings:{name:"Focused Neurological Findings", type:"text", body:"Alert and oriented to person and place, uncertain of the date. Right lower facial droop. Right arm drifts down within five seconds of being raised; right leg weak but antigravity. Speech dysarthric with word-finding difficulty, but comprehension intact and no neglect. No gaze deviation. Visual fields full to confrontation. National Institute of Health Stroke Scale score 14. Swallow screen not yet performed; nothing taken by mouth. No headache, no vomiting, no seizure activity."},
  imaging:{name:"Imaging — 10:25", type:"text", body:"Non-contrast CT head: no intracranial hemorrhage, no established infarct, no early ischemic change, no mass effect. CT angiography: occlusion of the M1 segment of the left middle cerebral artery. CT perfusion: salvageable penumbra in the left middle cerebral artery territory with a small core."},
  protocol:{name:"Stroke Pathway Directions", type:"text", body:"1. Treatment window for intravenous thrombolysis is 4.5 hours from last known well, not from the time the client was found. 2. Blood pressure must be below 185/110 mm Hg before thrombolysis and kept below 180/105 mm Hg for 24 hours afterwards. 3. Anticoagulant taken within the last 48 hours is a contraindication; beyond 48 hours it is not. 4. Give the weight-based alteplase bolus, then the one-hour infusion. 5. No antiplatelet or anticoagulant medicine for 24 hours after thrombolysis. 6. Neurological observations and blood pressure every 15 minutes for 2 hours, then every 30 minutes for 6 hours, then hourly until 24 hours. 7. Nil by mouth until a swallow screen is completed. 8. Stop the infusion and obtain an urgent CT head for severe headache, vomiting, a fall in conscious level or a sudden rise in blood pressure. 9. Refer large vessel occlusion for mechanical thrombectomy assessment. 10. Stroke team and speech and language therapy notified."}},
 items:[
  {step:"recognize", t:"single", stem:"The team is deciding whether he is a candidate for intravenous thrombolysis. Which piece of information is most critical to that decision?",
   reveal:["history","vitals","findings"],
   opts:["His National Early Warning Score on arrival, since it measures how unwell he is",
    "The time he was last known well at 07:15, not the 09:40 at which he was found",
    "His history of type 2 diabetes, since diabetes predicts a poorer thrombolysis outcome",
    "The left middle cerebral artery occlusion on angiography, since only large vessel occlusions are treated"],
   ans:1,
   rat:{c:"Eligibility runs from the last moment he was witnessed to be well — 07:15 — which puts him at 3 hours 10 minutes on arrival and inside the 4.5-hour window. Using the discovery time of 09:40 would wrongly suggest he is barely eligible, and using the ambulance time would be worse still; in a client found collapsed, the clock starts at last known well, not at discovery. An early warning score measures physiological derangement, not eligibility. Diabetes does not exclude treatment. And small vessel strokes are thrombolysed too — the large vessel occlusion governs thrombectomy referral, not thrombolysis eligibility.",
   o:["An early warning score tracks physiology; it does not determine thrombolysis eligibility.",
    "Correct — the 4.5-hour window runs from last known well, so 07:15 is the number that matters.",
    "Diabetes affects prognosis but is not an exclusion criterion.",
    "Thrombolysis is not restricted to large vessel occlusions; the occlusion drives thrombectomy referral instead."],
   s:"In stroke, 'last known well' starts the clock — never the time the client was found. Document it explicitly, because every subsequent decision depends on it."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals","findings"],
   hotspot:{mode:"rows", rows:[
    "Blood pressure 188/104 mm Hg",
    "Heart rate 96/min, irregularly irregular",
    "Capillary glucose 14.2 mmol/L",
    "Oxygen saturation 95% on room air",
    "Respiratory rate 16/min",
    "Temperature 36.8 °C"
   ], ans:[0,1,2]},
   rat:{c:"The blood pressure is above the 185/110 mm Hg threshold that must be met before thrombolysis, the irregularly irregular rhythm reflects the untreated atrial fibrillation that caused the embolus, and a glucose of 14.2 mmol/L is hyperglycemic and worsens ischemic injury if untreated. An oxygen saturation of 95% on room air, a respiratory rate of 16/min and a temperature of 36.8 °C are all within expected limits — three planted normals to tempt a hasty highlight.",
   o:["Above the 185/110 mm Hg pre-thrombolysis threshold — must be lowered first.",
    "Expected rate is 60–100/min, but an irregularly irregular rhythm is abnormal and points to atrial fibrillation.",
    "Expected random glucose is roughly 4–11 mmol/L; 14.2 is high and needs treatment.",
    "Normal saturation on room air is 95% and above — within range.",
    "Expected respiratory rate is 12–20/min — within range.",
    "Normal temperature is about 36.1–37.2 °C — within range."],
   s:"In a stroke the numbers that change management are the blood pressure against the thrombolysis threshold, the rhythm that reveals the cause, and the glucose. The oxygen and temperature are usually normal and are there to slow you down."}},
  {step:"prioritize", t:"single", stem:"The CT head shows no hemorrhage and he is within the treatment window. Which action takes priority before alteplase is given?",
   reveal:["history","vitals","findings","imaging","protocol"],
   opts:["Lower the blood pressure below 185/110 mm Hg with the prescribed intravenous antihypertensive",
    "Give 300 mg aspirin to reduce the risk of further clot formation",
    "Restart apixaban to treat the atrial fibrillation that caused the embolus",
    "Repeat the CT head in two hours to confirm that no early ischemic change has appeared"],
   ans:0,
   rat:{c:"A blood pressure above 185/110 mm Hg is an absolute barrier to thrombolysis because of the risk of hemorrhagic transformation, so it must be lowered below that threshold before the drug is given and then held below 180/105 mm Hg for 24 hours. Aspirin and anticoagulants are both withheld for 24 hours after thrombolysis — giving either now converts an ischemic stroke into a hemorrhage. And repeating the CT wastes the window: a clean scan within the window is sufficient, and time is brain.",
   o:["Correct — the blood pressure threshold must be met before alteplase can be given.",
    "Antiplatelets are withheld for 24 hours after thrombolysis; giving aspirin now risks hemorrhagic transformation.",
    "Anticoagulation is also withheld for 24 hours, and restarting apixaban acutely risks intracranial bleeding.",
    "A repeat CT delays treatment without adding decision-relevant information — the window is closing."],
   s:"Before thrombolysis: blood pressure under 185/110, a scan that excludes hemorrhage, and no antiplatelet or anticoagulant for 24 hours afterwards. Aspirin is the reflex answer and the wrong one here."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care for the first 24 hours after thrombolysis? Select all that apply.",
   reveal:["findings","imaging","protocol"],
   opts:["Neurological observations and blood pressure every 15 minutes for the first two hours",
    "Withholding antiplatelet and anticoagulant medicines for 24 hours",
    "Nil by mouth until a swallow screen is completed",
    "Stopping the infusion and obtaining an urgent CT head if severe headache, vomiting or a fall in conscious level occurs",
    "Commencing aspirin 300 mg within one hour to reduce early recurrence"],
   ans:[0,1,2,3],
   rat:{c:"The first two hours carry the highest risk of hemorrhagic transformation, so 15-minute neurological and blood pressure observations are mandatory, antiplatelets and anticoagulants stay off for 24 hours, and nothing is given by mouth until swallowing is assessed because roughly half of stroke clients dysphagic and aspiration pneumonia is a leading cause of post-stroke death. Severe headache, vomiting or reduced consciousness means the infusion stops and an urgent CT is obtained. Aspirin at one hour is the one action here that turns a treated stroke into a bleed.",
   o:["Correct — 15-minute observations for the first two hours detect hemorrhagic transformation early.",
    "Correct — a 24-hour antiplatelet and anticoagulant ban follows thrombolysis.",
    "Correct — dysphagia is common after stroke and nothing goes by mouth before the screen.",
    "Correct — those signs mean stop the infusion and scan immediately.",
    "Aspirin within 24 hours of thrombolysis significantly increases intracranial hemorrhage risk."],
   s:"The first 24 hours after thrombolysis are defined by what you withhold: no antiplatelets, no anticoagulants, nothing by mouth — while watching the neurological observations every 15 minutes."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","findings","imaging","protocol"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Secure intravenous access, take bloods including coagulation studies, and confirm the capillary glucose",
     "Lower the blood pressure below 185/110 mm Hg with the prescribed intravenous antihypertensive",
     "Give the weight-based alteplase bolus followed by the one-hour infusion",
     "Arrange transfer for mechanical thrombectomy given the M1 occlusion"],
    ans:[0,1,2,3]},
   rat:{c:"Access and bloods come first because a hypoglycemic mimic must be excluded and a coagulopathy identified before a thrombolytic is given. The blood pressure threshold must then be met, since alteplase given above 185/110 mm Hg risks hemorrhagic transformation. Thrombolysis follows, and thrombectomy comes after or alongside it as bridging therapy for the large vessel occlusion — it does not replace thrombolysis when the client is eligible.",
   o:["Access, coagulation studies and glucose first — hypoglycemia mimics stroke and coagulopathy contraindicates treatment.",
    "The blood pressure threshold is an absolute gate before the drug is given.",
    "Alteplase is given once the scan excludes hemorrhage and the blood pressure is controlled.",
    "Thrombectomy follows as bridging therapy for the M1 occlusion."],
   s:"Thrombolysis sequence: exclude the mimic and the coagulopathy → control the blood pressure → treat → then pursue thrombectomy. Skipping the glucose check is the classic error, because hypoglycemia is fully reversible."}},
  {step:"evaluate", t:"cloze", stem:"Twenty-four hours later he has had no hemorrhagic transformation, his weakness is improving, and the speech and language therapist has assessed him. Complete each evaluation statement.",
   reveal:["history","findings","imaging","protocol"],
   cloze:{lines:[
    {pre:"The repeat CT head at 24 hours shows no hemorrhage, so the nurse understands that antiplatelet therapy ", post:".",
     opts:["must still be withheld for a further week","is never indicated after an ischemic stroke","should be replaced immediately by full-dose anticoagulation","may now be started as prescribed"], ans:3},
    {pre:"He is cleared for IDDSI level 5 food with level 2 fluids, so the nurse's next action is to ", post:".",
     opts:["start oral intake at the prescribed consistency with him sitting fully upright","offer a normal diet and unrestricted fluids","keep him nil by mouth until review in a week","give all fluids through a nasogastric tube"], ans:0},
    {pre:"Because the stroke was cardioembolic from atrial fibrillation, the nurse expects the team to plan ", post:".",
     opts:["lifelong aspirin alone","long-term anticoagulation once it is safe to start","no further prevention because the clot has been dissolved","carotid endarterectomy"], ans:1},
    {pre:"Right-sided weakness with dysarthria and preserved comprehension most often indicates ", post:".",
     opts:["a right hemisphere lesion","a brainstem lesion only","a left hemisphere lesion","no localizing value"], ans:2}]},
   rat:{c:"The 24-hour ban ends once the scan excludes hemorrhage, so antiplatelet or anticoagulant therapy is started as prescribed at that point — not withheld arbitrarily and not started early. A dysphagia diet prescription means feeding at exactly the prescribed consistency with the client upright, since thin fluids are what aspirate and posture does not make an unsafe consistency safe. A cardioembolic stroke from atrial fibrillation needs anticoagulation rather than aspirin alone, timed to when bleeding risk allows. And in a right-handed client, left hemisphere involvement produces right-sided motor loss with language disturbance, which matches his dysarthria and word-finding difficulty.",
   o:["An extra week of withholding has no basis once the 24-hour scan is clear.",
    "Antiplatelet or anticoagulant therapy is central to secondary prevention.",
    "Full-dose anticoagulation is a timed decision based on infarct size and bleeding risk, not an immediate swap.",
    "Correct — the 24-hour ban ends with a clear scan, and prescribed therapy starts then.",
    "Correct — the prescribed IDDSI consistency with full upright positioning is what prevents aspiration.",
    "A normal diet and thin fluids are precisely what a level 5 and level 2 prescription excludes.",
    "Prolonged nil by mouth risks dehydration and malnutrition without any assessment basis.",
    "A nasogastric tube is unnecessary when he has been cleared for oral intake at a modified consistency.",
    "Aspirin alone is inferior to anticoagulation for cardioembolic stroke from atrial fibrillation.",
    "Correct — anticoagulation is the indicated secondary prevention once bleeding risk permits.",
    "A dissolved clot leaves the underlying atrial fibrillation untreated and the recurrence risk high.",
    "Carotid endarterectomy treats large artery atherosclerotic stenosis, not a cardioembolic source.",
    "A right hemisphere lesion would produce left-sided weakness and often neglect.",
    "A brainstem lesion produces crossed signs and cranial nerve findings, not this pattern.",
    "Correct — left hemisphere involvement gives right-sided weakness with language disturbance.",
    "The pattern localizes clearly and predicts the rehabilitation needs."],
   s:"Two discharge decisions dominate stroke nursing: start the right secondary prevention at the right time — anticoagulation, not aspirin, for atrial fibrillation — and feed at exactly the prescribed IDDSI consistency upright, because thin fluids are what cause the aspiration pneumonia that kills post-stroke clients."}}]})
;
