/* RN Ready — case study v2 · septic shock on a surgical ward.
   Twenty-first unfolding case: a 71-year-old on day three after hip
   replacement becomes confused and hypotensive from an infected wound.
   Judgment unfolds from recognizing sepsis in a post-operative client,
   through cultures-before-antibiotics without breaching the hour, to why the
   vasopressor comes after the fluid and not instead of it.

   Wave 67 — RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-SEPSIS-01", title:"The Quiet Shift — Mrs. Ibrahim, 71",
 setting:"Orthopaedic surgical ward", sys:"INTG", cn:"PAA", d:3, b:0.55,
 summary:"71-year-old on day three after hip replacement becomes newly confused with a heart rate of 116/min, a blood pressure of 84/48 mm Hg, a lactate of 4.8 mmol/L and purulent wound discharge. Judgment unfolds from recognizing sepsis behind ordinary post-operative signs, through cultures before antibiotics without breaching the hour, to why the vasopressor follows the fluid rather than replacing it.",
 exhibits:{
  history:{name:"History", type:"text", body:"71-year-old woman, day three after elective right total hip replacement. Surgery was uncomplicated. History: type 2 diabetes on metformin, hypertension, body mass index 36. On prophylactic enoxaparin. Overnight the night nurse records that she was 'a bit muddled' and asked twice what day it was. This morning she is disoriented to time and place, which her daughter says is completely unlike her. No cough, no dysuria reported, but she has been incontinent of urine twice overnight."},
  vitals:{name:"Observations", type:"kv", rows:[["Temperature","38.6 °C (101.5 °F)"],["Heart rate","116/min"],["Respiratory rate","26/min"],["Blood pressure","84/48 mm Hg — mean arterial pressure 60 mm Hg"],["SpO2 (room air)","93%"],["Urine output","20 mL in the last hour"],["National Early Warning Score","13"],["Capillary refill","4 seconds"]]},
  labs:{name:"Laboratory Results", type:"kv", rows:[["Lactate","4.8 mmol/L"],["White cell count","19,200/mm³ with a left shift"],["Creatinine","148 µmol/L (1.67 mg/dL) — baseline 82 µmol/L"],["Bilirubin","28 µmol/L"],["Platelets","118 x 10⁹/L"],["C-reactive protein","240 mg/L"],["Blood glucose","11.4 mmol/L (205 mg/dL)"]]},
  wound:{name:"Wound & Source Assessment", type:"text", body:"Right hip dressing struck through with seropurulent fluid. On removal the incision is erythematous for 4 cm around it, warm, tender, with purulent discharge at the lateral third. No crepitus, no skin necrosis. Swab and a deep specimen sent. Chest clear on auscultation. Urine dipstick positive for nitrites and leukocytes but she has a catheter-free post-operative course, so this may be colonization. No calf swelling."},
  orders:{name:"Provider Orders", type:"text", body:"1. Sepsis pathway activated — all six elements within one hour. 2. Blood cultures from two sites BEFORE the first antibiotic dose, but do not let sampling delay it past the hour. 3. Piperacillin-tazobactam 4.5 g IV. 4. 0.9% sodium chloride 30 mL/kg — approximately 2.1 L — as a fluid challenge with reassessment. 5. Oxygen to keep saturation at or above 94%. 6. Urinary catheter to measure hourly output. 7. Repeat lactate at 2 and 4 hours; lactate clearance is the resuscitation endpoint. 8. Noradrenaline via a central line if the mean arterial pressure stays below 65 mm Hg AFTER adequate fluid resuscitation. 9. Urgent surgical review for source control. 10. Intensive care referral."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the observations, laboratory results and wound assessment. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","labs","wound"],
   opts:["Her confusion is post-operative delirium and the wound changes are expected inflammation with dehydration, so fluids and reassurance are enough",
    "A purulent wound with new confusion, a mean arterial pressure of 60 mm Hg and a lactate of 4.8 mmol/L is sepsis with hypoperfusion, and the clock starts now",
    "The positive urine dipstick is the source, so a urinary antibiotic is all that is needed",
    "A temperature of 38.6 °C on day three is an expected post-operative finding and needs no escalation"],
   ans:1,
   rat:{c:"She meets sepsis with hypoperfusion: a presumed source in the wound, organ dysfunction shown by new confusion, a creatinine that has nearly doubled and a falling platelet count, and shock shown by a mean arterial pressure of 60 mm Hg with a lactate of 4.8 mmol/L. Post-operative delirium is a diagnosis of exclusion and never explains a lactate of 4.8. The dipstick is a distractor — nitrites in a catheter-free post-operative client may reflect colonization, and anchoring on it delays broad-spectrum cover for the obvious wound. And fever on day three after arthroplasty with a struck-through purulent dressing is a prosthetic joint infection until proven otherwise, which is a surgical emergency.",
   o:["Delirium is a diagnosis of exclusion and cannot explain a lactate of 4.8 mmol/L with a mean arterial pressure of 60.",
    "Correct — source, organ dysfunction and hypoperfusion together are septic shock, and the one-hour clock starts now.",
    "Nitrites may reflect colonization, and a urinary-only antibiotic misses the purulent prosthetic joint.",
    "Fever on day three with purulent discharge after arthroplasty is a prosthetic joint infection until proven otherwise."],
   s:"Sepsis is a presumed source plus organ dysfunction; add a lactate above 2 with hypotension and it is septic shock. New confusion in a post-operative client is sepsis until excluded, never assumed to be delirium."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that indicates organ dysfunction or impaired perfusion.",
   reveal:["vitals","labs"],
   hotspot:{mode:"rows", rows:[
    "Lactate 4.8 mmol/L",
    "Mean arterial pressure 60 mm Hg with a capillary refill of 4 seconds",
    "Creatinine 148 µmol/L against a baseline of 82 µmol/L",
    "Urine output 20 mL in the last hour",
    "Blood glucose 11.4 mmol/L",
    "Temperature 38.6 °C"
   ], ans:[0,1,2,3]},
   rat:{c:"The lactate is the perfusion marker, the mean arterial pressure with a 4-second refill shows the circulation is failing, the creatinine has nearly doubled indicating acute kidney injury, and an output of 20 mL/hour confirms the kidneys are not being perfused. Those four are the organ dysfunction that turns infection into sepsis. A glucose of 11.4 mmol/L is raised but is a stress and diabetic response rather than a marker of organ failure, and a temperature of 38.6 °C indicates infection but not organ dysfunction — the distinction matters because it is hypoperfusion, not fever, that drives the urgency. Two planted values that are abnormal in a different sense.",
   o:["Expected lactate is under 2.0 mmol/L; 4.8 indicates tissue hypoperfusion.",
    "Expected mean arterial pressure is 65 mm Hg or above, and capillary refill under 2 seconds; both are abnormal.",
    "A near doubling of creatinine indicates acute kidney injury from hypoperfusion.",
    "Expected output is at least 30 mL/hour; 20 mL/hour confirms renal hypoperfusion.",
    "Raised glucose reflects stress and diabetes — abnormal, but not a marker of organ dysfunction.",
    "Fever indicates infection, not organ dysfunction; hypoperfusion is what drives the urgency."],
   s:"Distinguish the findings that show infection from the findings that show organ dysfunction. Fever and a raised white count are infection; lactate, mean arterial pressure, creatinine and urine output are the organ dysfunction that makes it sepsis."}},
  {step:"prioritize", t:"single", stem:"The blood culture bottles are on the ward but the laboratory courier is not due for 40 minutes. Which action by the nurse takes priority?",
   reveal:["history","vitals","labs","wound","orders"],
   opts:["Give the antibiotic now and take the cultures when the courier arrives, since the one-hour antibiotic target outranks sampling",
    "Wait for the courier so the cultures are taken first, even if this pushes the antibiotic beyond the hour",
    "Give the antibiotic and skip the cultures entirely, since the wound swab already identifies the source",
    "Send her for a computed tomography scan first to confirm the source before any treatment"],
   ans:0,
   rat:{c:"Cultures should be taken before antibiotics because they guide de-escalation — but never at the cost of the hour, and delay in antibiotics is the strongest modifiable predictor of death in septic shock. Two blood culture sets are drawn from separate sites at the bedside in a couple of minutes and do not require a courier; the courier is for transport, not for sampling, so this delay is entirely avoidable. Skipping cultures loses the microbiology that allows narrowing later. Imaging must never delay the bundle, and a source is already visible on the wound.",
   o:["Correct — give the antibiotic now; bedside cultures take minutes and the courier is for transport, not sampling.",
    "Waiting past the hour for a courier trades the strongest modifiable survival factor for convenience.",
    "Skipping cultures loses the microbiology needed to de-escalate; wound swabs are not blood cultures.",
    "Imaging must not delay the bundle, and the source is already visible on the dressing."],
   s:"Cultures before antibiotics, but never beyond the hour — and bedside blood culture sets do not need a courier. Confusing sampling with transport is how the hour gets breached for nothing."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["vitals","labs","wound","orders"],
   opts:["The full sepsis bundle within one hour: cultures, lactate, antibiotics, fluid, oxygen and hourly urine output",
    "A 30 mL/kg crystalloid challenge with reassessment, before any vasopressor is started",
    "Urgent surgical review for source control, since antibiotics alone cannot sterilize an infected prosthesis",
    "Repeat lactate at 2 and 4 hours, since lactate clearance is the endpoint that shows resuscitation is working",
    "Starting noradrenaline immediately instead of fluid, since the blood pressure is the most abnormal number"],
   ans:[0,1,2,3],
   rat:{c:"The bundle within the hour is non-negotiable. A 30 mL/kg crystalloid challenge with reassessment comes before any vasopressor, because a vasopressor on an empty circulation clamps down on vessels that have nothing in them and worsens tissue perfusion. Source control is the step that is most often overlooked: antibiotics cannot penetrate and sterilize an infected prosthesis, and an undrained focus will outlast any drug. Serial lactate is how you know whether resuscitation is actually working. Starting noradrenaline instead of fluid is the classic error — vasopressors are for hypotension that persists after adequate volume, not a substitute for it.",
   o:["Correct — all six bundle elements within one hour.",
    "Correct — 30 mL/kg crystalloid with reassessment precedes any vasopressor.",
    "Correct — antibiotics cannot sterilize an infected prosthesis; drainage or removal is definitive.",
    "Correct — serial lactate is the endpoint that demonstrates resuscitation is working.",
    "A vasopressor on an unresuscitated circulation worsens tissue perfusion; fluid comes first."],
   s:"Sepsis bundle within the hour, then fluid before vasopressor, and never forget source control — an undrained infected prosthesis will beat any antibiotic. Lactate clearance tells you whether it is working."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","labs","wound","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Take two sets of blood cultures at the bedside and give the antibiotic, both within the hour",
     "Give oxygen, catheterize for hourly output and start the 30 mL/kg crystalloid challenge",
     "Reassess perfusion after the fluid and start noradrenaline if the mean arterial pressure is still below 65 mm Hg",
     "Escalate for urgent surgical source control and intensive care review"],
    ans:[0,1,2,3]},
   rat:{c:"Cultures and antibiotics inside the hour come first, because antibiotic delay is the strongest modifiable predictor of death. Oxygen, hourly output and the fluid challenge follow immediately, since the output is the endpoint and the volume is what the circulation needs. Reassessment after the fluid determines whether a vasopressor is genuinely needed — starting one before knowing the fluid response is treating a number rather than the client. Source control and intensive care review come last in this sequence but are requested from the first minute, because an infected prosthesis is definitive surgery and the delay is in theatre availability, not in the decision.",
   o:["Cultures and antibiotic within the hour — delay kills more than anything else here.",
    "Oxygen, hourly output and the 30 mL/kg fluid challenge.",
    "Reassess after fluid, then vasopressor only if the mean arterial pressure stays below 65.",
    "Surgical source control and intensive care review — requested from minute one."],
   s:"Sepsis sequence: cultures and antibiotic within the hour → oxygen, output, fluid challenge → reassess then vasopressor → source control. Request surgery early; the delay is theatre availability, not your decision."}},
  {step:"evaluate", t:"cloze", stem:"Two hours later the lactate has fallen from 4.8 to 2.6 mmol/L, the mean arterial pressure is 72 mm Hg on noradrenaline, and her urine output is 45 mL/hour. Complete each evaluation statement.",
   reveal:["history","vitals","labs","wound","orders"],
   cloze:{lines:[
    {pre:"The lactate has fallen from 4.8 to 2.6 mmol/L, so the nurse understands that ", post:".",
     opts:["resuscitation is complete and the vasopressor can be stopped","the falling lactate indicates improving perfusion, so the current strategy is working and is continued with serial monitoring","the lactate is no longer relevant once antibiotics have been given","the result is a laboratory artifact, since lactate never falls that quickly"], ans:1},
    {pre:"Her crackles are increasing and her oxygen requirement is rising during the fluid challenge, so the nurse ", post:".",
     opts:["continues the full 30 mL/kg regardless, since the protocol volume must be given","gives a diuretic and continues the fluid at the same rate","stops the vasopressor, since the crackles indicate fluid overload is correcting itself","pauses and reassesses, since she may be fluid intolerant and needs smaller boluses with escalation for inotropic or vasopressor support"], ans:3},
    {pre:"Because the prosthesis is infected, the nurse recognizes that ", post:".",
     opts:["source control is essential, since antibiotics alone cannot sterilize an infected implant and surgical drainage or removal is definitive","antibiotics for six weeks will resolve it without surgery","the wound should be left closed to prevent further contamination","removing the prosthesis is never an option in an older client"], ans:0},
    {pre:"Once cultures identify a sensitive organism and she is improving, the nurse expects the team to ", post:".",
     opts:["continue broad-spectrum antibiotics for the full course regardless of the result","stop all antibiotics as soon as she is afebrile","switch to oral antibiotics immediately without regard to the source","narrow the antibiotic to the identified organism, since de-escalation reduces resistance and adverse effects"], ans:3}]},
   rat:{c:"A lactate falling from 4.8 to 2.6 mmol/L is lactate clearance — the endpoint that shows perfusion is being restored — so the strategy continues with serial monitoring rather than stopping. Rising crackles and oxygen requirement during a fluid challenge mean she may be fluid intolerant, so the fluid is paused and reassessed with smaller boluses and escalation; continuing to a protocol volume regardless is how pulmonary edema happens. Source control is definitive: antibiotics cannot sterilize an infected implant, and leaving it in guarantees failure. And once the organism is known, de-escalation to a narrow agent reduces resistance and adverse effects — which is exactly why the cultures taken in the first hour matter.",
   o:["Resuscitation is not complete while she still needs a vasopressor.",
    "Correct — a falling lactate shows improving perfusion; continue the strategy and monitor serially.",
    "Lactate remains the resuscitation endpoint throughout.",
    "A fall from 4.8 to 2.6 in two hours is an expected response to effective resuscitation.",
    "A fixed protocol volume given despite pulmonary edema causes harm.",
    "A diuretic while continuing the same fluid rate is contradictory and unsafe.",
    "Crackles indicate worsening, not self-correction.",
    "Correct — pause and reassess; fluid intolerance needs smaller boluses and escalation for inotropic or vasopressor support.",
    "Correct — antibiotics cannot sterilize an infected implant; surgical drainage or removal is definitive.",
    "Six weeks of antibiotics without source control will fail with an infected prosthesis in situ.",
    "Closing an infected wound traps the infection.",
    "Age is not a contraindication to source control; the decision is individual and often involves a spacer.",
    "Broad-spectrum cover continues only until the organism is known.",
    "Stopping at the first afebrile reading risks relapse, especially with an undrained focus.",
    "The oral switch depends on the source, the organism and bioavailability — not on timing alone.",
    "Correct — de-escalation to a narrow agent reduces resistance and adverse effects."],
   s:"Three sepsis endgame points: lactate clearance is the resuscitation endpoint, fluid intolerance means pause and reassess rather than finish the protocol, and an infected implant needs surgery — antibiotics alone will fail. De-escalate once you have the organism."}}]})
;
