/* RN Ready — case study v2 · renal (acute kidney injury).
   Fifth unfolding case: an older adult whose oliguric AKI emerges from a classic
   stack — dehydration, NSAIDs, and iodinated contrast. Judgment unfolds across
   all six NCJMM steps, from recognizing the urine cue to prevention teaching.
   Later exhibits are only revealed at later steps — the case unfolds.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-REN-01", title:"The Tea-Colored Turn — Mrs. R., 78",
 setting:"Progressive care unit", sys:"REN", cn:"PAA", d:2, b:0.3,
 summary:"78-year-old woman on day 2 after cardiac catheterization develops falling urine output and rising creatinine; judgment unfolds from recognizing oliguria to protecting the kidneys and preventing the next episode.",
 exhibits:{
  history:{name:"History & Admission Note", type:"text", body:"78-year-old woman admitted after a non-urgent cardiac catheterization with coronary stenting (groin access, iodinated contrast). Home meds: ibuprofen 400 mg 2–3×/day for knee arthritis (self-titrated for years), lisinopril 20 mg daily, atorvastatin. She was mildly queasy and eating little the day before the procedure and “didn't want to bother anyone” so she drank sparingly. Procedure uneventful; she received 120 mL of contrast. Baseline creatinine at last month's clinic visit: 0.9 mg/dL. No dialysis history, no known kidney disease."},
  vitals:{name:"Vital Signs", type:"kv", rows:[["Temperature","37.1 °C (98.8 °F)"],["Heart rate","98/min"],["Blood pressure","132/78 mm Hg"],["Respiratory rate","18/min"],["SpO2 (room air)","97%"],["Weight","Admission 61.2 kg → today 63.1 kg"]]},
  io:{name:"Intake & Output (last 24 h)", type:"text", body:"IV fluids: none running since procedure (saline-lock maintained). Oral intake: ~600 mL. Output: 240 mL total across the day — dark, concentrated, and “only a little each time.” Patient states her “kidneys feel slow” but denies pain on urination. Bladder scan after a missed void: 45 mL residual. Mucous membranes dry; skin tenting lightly over the sternum; no peripheral edema reported at admission — now 1+ pitting at the ankles."},
  labs:{name:"Laboratory Results (this morning)", type:"kv", rows:[["Serum creatinine","2.4 mg/dL (baseline 0.9)"],["Blood urea nitrogen","58 mg/dL"],["Serum potassium","5.6 mEq/L"],["Serum sodium","137 mEq/L"],["BUN:creatinine ratio","> 20:1"],["Urine sodium","12 mEq/L (low)"],["Urine specific gravity","1.032 (high)"],["Complete blood count","White cells 9.1, hemoglobin stable"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. Hold lisinopril and ibuprofen. 2. Stop the scheduled CT abdomen with IV contrast for now. 3. Start normal saline 75 mL/hr continuous. 4. Strict intake and output with an hourly-voiding diary; bladder scan after any missed void. 5. Daily weight on the same scale each morning. 6. Serum creatinine, BUN, and electrolytes every morning; potassium above 5.9 call immediately. 7. Low-potassium diet consult. 8. Cardiac monitor — continue. 9. If urine output remains below 0.5 mL/kg/hr for 6 more hours, notify the provider."},
  reassess:{name:"Reassessment — 24 Hours Later", type:"kv", rows:[["Urine output","1,050 mL/24 h, lighter in color"],["Serum creatinine","2.0 mg/dL"],["Blood urea nitrogen","44 mg/dL"],["Serum potassium","4.9 mEq/L"],["Weight","62.2 kg (down 0.9)"],["Blood pressure","128/76 mm Hg"],["Lungs","Clear; no crackles"]]}},
 items:[
  {step:"recognize", t:"single", stem:"Reviewing the history, intake-output record, and vitals, which cluster of cues most strongly signals a threat to this client's renal function?",
   reveal:["history","io","vitals"],
   opts:["Urine output of 240 mL/24 h with dry mucous membranes after contrast plus a skipped ibuprofen-quet stomach",
    "Temperature of 37.1 °C with a heart rate of 98/min on the second hospital day",
    "Blood pressure of 132/78 mm Hg measured in the unaffected arm",
    "A bladder-scan residual of 45 mL after one missed void"],
   ans:0,
   rat:{c:"The renal threat is the AKI triad stack: prerenal volume depletion (poor intake ~600 mL, dry membranes, tenting, concentrated high-SG urine), nephrotoxic exposure (daily NSAIDs + 120 mL iodinated contrast), and now falling output (<0.5 mL/kg/hr ≈ <30 mL/hr for her weight) with a 1.9 kg weight shift. Low-grade vitals and a one-time small residual are not the sentinel cluster.",
   o:["Correct — dehydration + NSAID + contrast + oliguria is the classic renal-hit stack.",
    "Afebrile with mild tachycardia is consistent with mild volume loss, not the defining threat.",
    "This blood pressure is acceptable and is not part of the renal alarm.",
    "A single 45 mL residual is normal-to-borderline and does not explain 240 mL/day."],
   s:"Recognize the AKI stack: dry + nephrotoxins + oliguria. Weight UP while urine is DOWN is the paradox that says kidney, not bladder."}},
  {step:"analyze", t:"hotspot", stem:"The team suspects acute kidney injury. Highlight every laboratory finding in this morning's panel that supports a PRERENAL cause rather than intrinsic kidney damage.",
   reveal:["labs","io"],
   hotspot:{mode:"rows", rows:["Blood urea nitrogen rising faster than creatinine (BUN:Cr > 20:1)","Urine sodium of 12 mEq/L (low)","Serum potassium of 5.6 mEq/L","Urine specific gravity of 1.032 (high)","Serum creatinine 2.4 mg/dL, up from baseline 0.9","Serum sodium of 137 mEq/L (normal)"], ans:[0,1,3]},
   rat:{c:"Prerenal AKI = a perfused-starved but structurally intact kidney conserving sodium and water: BUN:Cr > 20:1, urine sodium low (< 20), and urine maximally concentrated (SG ≥ 1.025). The creatinine rise confirms injury but not its mechanism; hyperkalemia marks failing excretion in either mechanism; and normal serum sodium does not discriminate.",
   o:["Correct — the kidney reabsorbs urea with water when volume is low: ratio climbs.",
    "Correct — a sodium-avid tubule is the prerenal signature.",
    "Hyperkalemia flags impaired excretion and risk — it does not localize the mechanism.",
    "Correct — concentrated urine means the tubules still respond to volume loss.",
    "The creatinine trajectory measures severity, not prerenal versus intrinsic.",
    "Normal serum sodium neither supports nor excludes prerenal physiology."],
   s:"Prerenal fingerprint: BUN:Cr high, urine Na low, urine maximally concentrated. The tubules are FINE — the plumbing upstream is dry."}},
  {step:"generate", t:"multi", stem:"Which orders and actions should the nurse anticipate for this prerenal picture with a contrast-NSADI hit? Select all that apply.",
   reveal:["history","labs"],
   opts:["Holding the lisinopril and the ibuprofen while the kidney recovers",
    "Canceling or postponing further iodinated-contrast imaging for now",
    "Starting a maintenance crystalloid infusion to restore perfusion",
    "Encouraging an oral fluid challenge of 3 liters in 3 hours",
    "Tracking strict intake-output, daily weights, and a potassium call threshold"],
   ans:[0,1,2,4],
   rat:{c:"Renal protection in prerenal AKI: remove the vasoconstrictive/nephrotoxic hits (NSAID, ACE-inhibitor), avoid repeat contrast, restore volume with a controlled maintenance infusion (not a bolus chase in an older adult), and monitor with I&O, daily same-scale weights, and a hard potassium escalation threshold. A 3-liter oral challenge risks volume overload in a 78-year-old who is already 1.9 kg up.",
   o:["Correct — both drugs drop glomerular perfusion pressure; pause them.",
    "Correct — no elective contrast while creatinine is climbing.",
    "Correct — steady rehydration is the treatment of the mechanism.",
    "Aggressive oral loading in an older adult invites pulmonary edema — replaced by controlled IV rates.",
    "Correct — the safety net is measurement plus a defined escalation trigger."],
   s:"Generate the renal-protection bundle: stop the offenders, skip the contrast, fill the tank gently, and measure everything. Speed of correction is NOT the goal — safety is."}},
  {step:"act", t:"emr", stem:"Review each provider order for this client. Open each panel and select the orders to implement now, the orders to question or clarify first, and the order that is correct but routine rather than urgent.",
   reveal:["orders"],
   groups:[
    {h:"Implement now", opts:["Hold lisinopril and ibuprofen","Cancel the scheduled IV-contrast CT","Normal saline 75 mL/hr continuous","Strict I&O with bladder scan after missed voids","Daily creatinine-BUN-electrolytes with a potassium call threshold of 5.9"], ans:[0,1,2,3,4]},
    {h:"Question or clarify first", opts:["Continue the cardiac monitor with telemetry alarms at maximum volume overnight"], ans:[0]},
    {h:"Correct but routine", opts:["Low-potassium diet consult for tomorrow"], ans:[0]}],
   rat:{c:"Everything targeting the kidney goes live now: drug holds, contrast cancellation, gentle volume, measurement infrastructure, and lab surveillance with its escalation number. The cardiac monitor itself is reasonable post-catheterization, but 'alarms at maximum volume overnight' for a stable-rhythm client on a progressive care unit deserves a question — alarm fatigue harms the whole unit. The diet consult is worthwhile care, just not 0300 care.",
   o:["Correct — the nephrotoxic pair stops now.","Correct — elective contrast waits for a recovering kidney.","Correct — controlled rehydration starts on the clock.","Correct — the measurement system is the safety net.","Correct — surveillance labs carry a defined call number.",
    "Correct — reasonable monitoring, questionable alarm setting; clarify with the provider.",
    "Correct — potassium-limited diet matters tomorrow, not tonight."],
   s:"Act on mechanism now (holds, no contrast, gentle fluids, measurement, surveillance labs), question settings that create alarm fatigue, and park routine items in business hours."}},
  {step:"evaluate", t:"single", stem:"Twenty-four hours into treatment, review the reassessment panel. Which conclusion is best supported?",
   reveal:["reassess","orders"],
   opts:["Rising urine output with falling creatinine, BUN, and weight indicates the prerenal injury is reversing",
    "A creatinine of 2.0 mg/dL proves the episode has fully resolved and monitoring can stop",
    "Clear lungs mean the saline infusion should be stopped immediately to protect the kidneys",
    "A potassium of 4.9 mEq/L indicates the low-potassium diet has failed"],
   ans:0,
   rat:{c:"Every tracked variable moved the right way together: output above 0.5 mL/kg/hr, creatinine and BUN falling, potassium normalizing, and weight drifting down as overload resolves — the signature of a rehydrated kidney. A still-elevated creatinine of 2.0 is recovery, not resolution (baseline was 0.9); clear lungs support continuing the current rate, not stopping it; and 4.9 is a diet SUCCESS, not failure.",
   o:["Correct — direction and pace of all parameters align with prerenal recovery.",
    "Resolution means creatinine back toward HER baseline of 0.9 — keep watching.",
    "Clear lungs are reassurance about the rate, not an indication to withdraw fluids prematurely.",
    "Potassium landing in range is exactly what the diet and recovering excretion were meant to do."],
   s:"Evaluate the whole vector — urine, creatinine, potassium, weight, lungs — not one number. Reversal is a trend, and the trend here points the right way."}},
  {step:"reflect", t:"cloze", stem:"Before discharge, the nurse completes prevention teaching with Mrs. R. and her daughter. Complete each teaching point.",
   reveal:["history","orders"],
   cloze:{lines:[
    {pre:"For knee pain after discharge, the safest plan the nurse should negotiate with the provider is ", post:" rather than resuming her old ibuprofen habit.",
     opts:["acetaminophen scheduled doses with non-drug measures","resuming ibuprofen but only on bad days","alternating ibuprofen with naproxen","doubling the lisinopril dose instead"], ans:0},
    {pre:"Before any future imaging or procedure, the client should tell every clinician that ", post:" so contrast decisions account for it.",
     opts:["she had contrast-associated kidney injury this admission","she dislikes the taste of contrast agents","her father had gout","she once fainted giving blood"], ans:0},
    {pre:"On sick days when she is vomiting or eating little, she should ", post:" and hold designated medications per her sick-day plan.",
     opts:["contact the clinic early and focus on fluids","wait three days to see if it passes","take extra ibuprofen for body aches","restrict all fluids to rest the kidneys"], ans:0}]},
   rat:{c:"Post-AKI prevention: switch chronic analgesia to acetaminophen plus nonpharmacologic measures (heat, pacing, PT), declare the contrast-associated injury to every future provider (kidney-aware imaging decisions), and adopt a sick-day plan — call early, maintain fluids, and temporarily hold ACE inhibitors/NSAIDs/diuretics per the prescriber when intake is poor.",
   o:["Correct — acetaminophen plus non-drug strategies protects perfusion.","Ibuprofen on bad days is still recurrent nephrotoxin exposure.","Naproxen is the same NSAID class — swapping is not a plan.","An ACE-inhibitor is not an analgesic and adds renal risk when dry.",
    "Correct — this history changes future contrast decisions.","Taste is irrelevant to safety; kidney history is not.","Family gout history does not change her contrast risk.","A remote faint is not the operative history here.",
    "Correct — early contact plus fluid focus is the sick-day core.","Waiting three days is how prerenal becomes intrinsic.","Extra NSAIDs during illness is the exact trigger to avoid.","Restricting fluids when dry drives the kidney toward another hit."],
   s:"AKI discharge trio: trade the NSAID for acetaminophen + non-drug care, announce the contrast history forever, and live by a sick-day plan (call early, keep drinking, hold the risky pills)."}}]}
);
