/* RN Ready — case study v2 · postpartum hemorrhage.
   Ninth unfolding case: a 29-year-old bleeds in the fourth stage after a
   vacuum-assisted delivery. Judgment unfolds from distinguishing uterine atony
   from a genital tract laceration, through quantitative blood loss and shock
   index, to the uterotonic contraindications and the massive transfusion
   response.

   Wave 62 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-PPH-01", title:"The Fourth Stage — Blessing, 29",
 setting:"Labor and delivery / postpartum unit", sys:"HEME", cn:"PAA", d:3, b:0.55,
 summary:"29-year-old G3P3 forty minutes after a vacuum-assisted delivery of a 4.1 kg infant, bleeding heavily with a boggy fundus displaced to the right. Judgment unfolds from separating atony from a laceration, through shock index and quantitative loss, to uterotonic contraindications and massive transfusion.",
 exhibits:{
  history:{name:"Obstetric History", type:"text", body:"29-year-old G3P3, 39+2 weeks. Spontaneous vaginal delivery 45 minutes ago after a prolonged second stage of 2 hours 40 minutes, assisted with a vacuum extractor. Infant 4.1 kg. Third stage managed actively, lasted 22 minutes; oxytocin infusion started per protocol. No previous postpartum hemorrhage. Body mass index 34. Medical history: mild asthma, well controlled on an as-needed salbutamol inhaler, no steroid use. Group and save done in pregnancy; no known antibodies. Partner present."},
  vitals:{name:"Vital Signs (40 minutes after birth)", type:"kv", rows:[["Temperature","36.9 °C (98.4 °F)"],["Heart rate","118/min"],["Respiratory rate","22/min"],["Blood pressure","92/58 mm Hg (was 118/74 in labor)"],["SpO2 (room air)","96%"],["Pain","4/10, lower abdominal cramping"],["Pad weight","One pad fully saturated in 10 minutes"]]},
  bloodloss:{name:"Quantitative Blood Loss & Shock Index", type:"kv", rows:[["Cumulative blood loss","1250 mL (weighed swabs plus calibrated drape)"],["Shock index","1.28 (heart rate 118 ÷ systolic 92)"],["Baseline shock index in labor","0.62"],["Estimated loss at delivery of placenta","350 mL"],["Time of first heavy bleed","0950"],["Fundal height","2 cm above the umbilicus, displaced to the right"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. Bimanual uterine compression and fundal massage. 2. Oxytocin 40 units in 1000 mL sodium chloride at 250 mL/hr. 3. Tranexamic acid 1 g IV within 3 hours of birth. 4. Methylergonovine 0.2 mg IM if atony persists. 5. Carboprost 250 mcg IM if atony persists. 6. Misoprostol 1000 mcg rectally. 7. Urinary catheter to empty the bladder and measure output. 8. Group and crossmatch 4 units; activate the massive transfusion protocol if loss exceeds 1500 mL or the client is unstable. 9. Two 14-gauge IV cannulae. 10. Notify obstetric and anesthesia teams; prepare for Bakri balloon and theatre."},
  notes:{name:"Nurse's Notes", type:"text", body:"0950: Client states 'I feel like I am flooding.' Large clots passed. Fundus palpated boggy and soft, displaced to the right and above the umbilicus. Suprapubic fullness on palpation; client says she has not passed urine since 0500. 0955: Bimanual compression started, second IV cannula sited, obstetric team called. Partner asks whether she is losing 'too much'. 1005: Fundus firms briefly with massage then relaxes again."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the findings. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","bloodloss","notes"],
   opts:["A boggy fundus displaced to the right and above the umbilicus with clot passage indicates uterine atony aggravated by a full bladder",
    "A cumulative loss of 1250 mL after a vacuum delivery indicates a genital tract laceration as the source",
    "The heart rate of 118/min with a blood pressure of 92/58 mm Hg is the finding that identifies the cause",
    "Continuous bright red bleeding despite a firm, central fundus would indicate atony"],
   ans:0,
   rat:{c:"A soft, boggy fundus that firms with massage and then relaxes, sitting high and displaced right by a distended bladder, is the signature of uterine atony — the cause of roughly 70% of postpartum hemorrhage, and the full bladder is actively preventing contraction. A laceration is suggested by the opposite picture: steady bright red bleeding with a firm, well-contracted uterus. Tachycardia and hypotension tell you she is bleeding, not why. The volume of 1250 mL confirms the severity but does not localize the source.",
   o:["Correct — a boggy, high, right-displaced fundus that firms then relaxes is atony, and the full bladder is the aggravating cause.",
    "A laceration presents with ongoing bleeding and a FIRM uterus; a vacuum delivery raises that risk but the fundal findings point elsewhere.",
    "These signs quantify the physiological insult; they cannot distinguish atony from trauma, coagulopathy or retained tissue.",
    "Backwards — steady bleeding with a firm fundus is the hallmark of a genital tract laceration, not atony."],
   s:"The four T's: Tone, Trauma, Tissue, Thrombin. Palpate the fundus first — boggy means Tone, firm with ongoing bleeding means Trauma, and a full bladder is a reversible cause of atony that is fixed in seconds."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected range for this client at 40 minutes postpartum.",
   reveal:["vitals","bloodloss"],
   hotspot:{mode:"rows", rows:[
    "Heart rate 118/min",
    "Blood pressure 92/58 mm Hg, down from 118/74 mm Hg",
    "Shock index 1.28",
    "Fundus 2 cm above the umbilicus and displaced to the right",
    "Oxygen saturation 96% on room air",
    "Temperature 36.9 °C"
   ], ans:[0,1,2,3]},
   rat:{c:"Tachycardia, a systolic drop of 26 mm Hg from her own baseline, a shock index of 1.28 and a malpositioned boggy fundus are all abnormal. The shock index is the sharpest number here: it is 118 ÷ 92 = 1.28 against a baseline of 0.62, and an index of 0.9 or above signals significant blood loss earlier than the blood pressure alone, because young healthy women compensate and maintain pressure until they suddenly do not. A saturation of 96% and a temperature of 36.9 °C are normal — two planted values.",
   o:["Expected postpartum heart rate is 60–100/min; 118 is a compensation sign.",
    "Her own baseline was 118/74; a systolic of 92 is a fall of 26 mm Hg and is abnormal for her.",
    "A shock index of 0.9 or above indicates significant loss; 1.28 is markedly abnormal and precedes frank hypotension.",
    "The fundus should be firm, at or below the umbilicus and central — high, soft and right-displaced is abnormal.",
    "Normal saturation is 95% and above — within range.",
    "Normal temperature is about 36.1–37.2 °C — within range."],
   s:"In obstetric hemorrhage, use the shock index and the change from the client's own baseline. Young women compensate well and the blood pressure is the last thing to fall, so relying on it alone kills."}},
  {step:"prioritize", t:"single", stem:"The fundus firms briefly with massage and then relaxes again. Which action by the nurse takes priority?",
   reveal:["history","vitals","bloodloss","orders","notes"],
   opts:["Give carboprost 250 mcg intramuscularly, since it is the most reliable second-line uterotonic",
    "Perform bimanual uterine compression and catheterize to empty the bladder, since the distended bladder is preventing contraction",
    "Take her straight to theatre for examination under anesthesia",
    "Give a 500 mL fluid bolus and wait for the crossmatched blood to arrive before acting further"],
   ans:1,
   rat:{c:"Mechanical control comes first and it is immediately available: bimanual compression plus massage, and catheterizing the bladder, which is displacing the uterus and mechanically preventing it from contracting. Carboprost is contraindicated here because she has asthma — it is a prostaglandin F2-alpha analogue that causes bronchoconstriction — and no drug should precede the mechanical measures anyway. Theatre is the escalation step if first-line measures fail, not the first step. And waiting for blood while she continues to bleed wastes the minutes that determine outcome.",
   o:["Carboprost is contraindicated in asthma because it causes bronchoconstriction, and drugs follow mechanical control regardless.",
    "Correct — bimanual compression, massage and emptying the bladder address the reversible mechanical cause within seconds.",
    "Examination under anesthesia is the next step if first-line measures fail, not the priority while simple measures remain untried.",
    "Fluid resuscitation runs alongside, not instead; waiting for blood while she bleeds is not an option."],
   s:"Atony first line is mechanical: bimanual compression, massage, empty the bladder, oxytocin. Then check the contraindications before the second-line drugs — carboprost not in asthma, methylergonovine not in hypertension."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care for the next hour? Select all that apply.",
   reveal:["history","vitals","bloodloss","orders","notes"],
   opts:["Continuing the oxytocin infusion and adding methylergonovine if atony persists, since she is hypotensive rather than hypertensive",
    "Tranexamic acid 1 g intravenously, given within three hours of birth",
    "Two large-bore cannulae, crossmatching 4 units and activating the massive transfusion protocol as the loss approaches 1500 mL",
    "Continuous fundal assessment with documented quantitative blood loss rather than visual estimation",
    "Withholding further uterine massage to avoid trauma to the recently delivered uterus"],
   ans:[0,1,2,3],
   rat:{c:"Oxytocin continues; methylergonovine is appropriate here because her blood pressure is low rather than high, which is the contraindication to avoid. Tranexamic acid within three hours reduces death from obstetric bleeding and should never be delayed. Loss is heading past 1500 mL with a shock index of 1.28, so blood availability and the massive transfusion protocol must be live now. Quantitative measurement by weighing catches ongoing loss that visual estimation routinely understates by half. Massage is therapeutic, not harmful, and stopping it removes the cheapest effective intervention available.",
   o:["Correct — oxytocin continues, and methylergonovine is safe because her blood pressure is low; hypertension is the contraindication.",
    "Correct — tranexamic acid within 3 hours reduces death from obstetric hemorrhage.",
    "Correct — large-bore access, crossmatch and an activated protocol before she needs them, not after.",
    "Correct — weighing undercatches far less than visual estimation, which understates loss by roughly half.",
    "Massage is the primary treatment for atony; withholding it removes the most effective first-line measure."],
   s:"Uterotonic contraindications are examinable every time: carboprost not in asthma, methylergonovine not in hypertension, misoprostol safe in both. And always weigh the loss — visual estimation understates it."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","bloodloss","orders","notes"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Call for help, apply oxygen, secure two large-bore cannulae and send the group and crossmatch",
     "Perform bimanual uterine compression with fundal massage and catheterize the bladder",
     "Give tranexamic acid 1 g intravenously and escalate the uterotonics within their contraindication limits",
     "Prepare for the Bakri balloon and theatre while activating the massive transfusion protocol"],
    ans:[0,1,2,3]},
   rat:{c:"Calling for help and establishing access comes first because a hemorrhaging client needs a team and the ability to give blood and drugs before anything else can work. Mechanical control of the atony follows immediately, since it is the fastest way to stop the bleeding and it fixes the reversible bladder cause. Pharmacological escalation and tranexamic acid come next, chosen around her asthma. Surgical and device escalation is the last resort once first- and second-line measures have been given a fair trial — but prepared for in parallel, never started late.",
   o:["Team, oxygen, access and blood availability — the platform everything else depends on.",
    "Mechanical control and emptying the bladder stop atony faster than any drug.",
    "Tranexamic acid and uterotonics follow, selected around her asthma.",
    "Balloon and theatre are the escalation, prepared early but used if first-line measures fail."],
   s:"Obstetric hemorrhage sequence: team and access → mechanical control → drugs within their contraindication limits → device or surgical escalation. Prepare the last step early; do not wait to need it."}},
  {step:"evaluate", t:"cloze", stem:"Two hours later the fundus is firm and central, bleeding has stopped and the total loss reached 1800 mL. She received 2 units of red cells and fresh frozen plasma. Her hemoglobin is 7.2 g/dL and her heart rate is 104/min. Complete each evaluation statement.",
   reveal:["history","vitals","bloodloss","orders","notes"],
   cloze:{lines:[
    {pre:"The bleeding has stopped and the fundus is firm, so the nurse understands that observation should continue because ", post:".",
     opts:["the hemorrhage is over and routine postpartum care can resume","atony can recur within the first 24 hours, so fundal checks and quantitative loss continue at the prescribed frequency","recurrence is impossible once tranexamic acid has been given","observation is only needed while the oxytocin infusion runs"], ans:1},
    {pre:"With a hemoglobin of 7.2 g/dL and a heart rate of 104/min, the nurse's priority is to ", post:".",
     opts:["encourage oral iron and mobilize her as soon as possible","give the remaining crossmatched blood without reassessment","assess for ongoing bleeding and symptoms of impaired oxygen delivery, and escalate the hemoglobin result for transfusion review","document it as an expected postpartum finding"], ans:2},
    {pre:"Because she has received red cells and fresh frozen plasma, the nurse monitors specifically for ", post:".",
     opts:["a rising temperature with rigors, breathlessness and falling saturation suggesting a transfusion reaction or transfusion-associated circulatory overload","increased urine output suggesting fluid overload only","a falling platelet count suggesting dilution alone","no specific monitoring, since the products were crossmatched"], ans:0},
    {pre:"Before discharge the nurse recognizes that this client's future pregnancies carry ", post:".",
     opts:["no additional risk, since the cause has been treated","a reduced risk, because the uterus has now contracted once","an increased risk of recurrence, so the plan for her next delivery must be documented and discussed with the obstetric team","a requirement for elective cesarean section in every future pregnancy"], ans:2}]},
   rat:{c:"Atony recurs — most secondary hemorrhages happen within the first 24 hours — so fundal checks and quantitative loss continue on schedule even when everything looks settled. A hemoglobin of 7.2 g/dL with ongoing tachycardia is not a benign postpartum number: the nurse assesses for continued bleeding and symptoms of impaired oxygen delivery and escalates for transfusion review rather than accepting it or transfusing unilaterally. Blood products carry reaction and overload risk that needs active monitoring, not routine observation. And a previous postpartum hemorrhage is one of the strongest predictors of another, so the recurrence risk must be documented for the next pregnancy.",
   o:["Routine care resumes only when the risk window has passed; observation continues on schedule until then.",
    "Correct — atony recurs, most secondary hemorrhage occurs within 24 hours, so scheduled fundal checks and quantified loss continue.",
    "Tranexamic acid reduces loss; it does not abolish the risk of recurrent atony.",
    "The oxytocin infusion is part of the treatment, not the boundary of the observation period.",
    "Oral iron alone ignores ongoing tachycardia and possible continued bleeding.",
    "Transfusion is a prescriber decision based on the whole picture, not an automatic response to one result.",
    "Correct — assess for ongoing loss and impaired oxygen delivery, and escalate the result for transfusion review.",
    "A hemoglobin of 7.2 g/dL with tachycardia is never an 'expected' finding to simply document.",
    "Correct — fever with rigors, breathlessness and falling saturation signal a reaction or circulatory overload.",
    "Urine output alone misses a hemolytic or febrile reaction entirely.",
    "Dilutional thrombocytopenia is real but is not the risk that needs watching first.",
    "Crossmatching prevents hemolytic reactions; it does not prevent febrile reactions or circulatory overload.",
    "Risk is not removed by treating one episode.",
    "One contracted uterus confers no protection on the next pregnancy.",
    "Correct — previous postpartum hemorrhage is a major predictor of recurrence and must be documented and planned for.",
    "Mode of delivery is decided individually; a previous hemorrhage is not by itself an indication for cesarean section."],
   s:"After a postpartum hemorrhage, the two things that get missed are continued observation past the point the bleeding looks controlled, and counseling about recurrence risk. Atony recurs, and a previous hemorrhage is the single strongest predictor of the next one."}}]})
;
