/* RN Ready — case study v2 · diabetic ketoacidosis.
   Seventh unfolding case: a 17-year-old in new-onset type 1 diabetes presents
   in DKA. Judgment unfolds from distinguishing DKA from a hyperosmolar state,
   through the fluid-before-insulin logic and potassium replacement, to the
   cerebral-edema surveillance that dominates adolescent DKA nursing.

   Wave 61 — case studies are the exclusive focus for waves 61-66.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-DKA-01", title:"The Thirsty Teenager — Amara, 17",
 setting:"Emergency department", sys:"ENDO", cn:"PHA", d:3, b:0.55,
 summary:"17-year-old with three days of polyuria, vomiting and abdominal pain, no previous diabetes diagnosis; capillary glucose 28.4 mmol/L, pH 7.14, ketones 4.8 mmol/L. Judgment unfolds from recognizing ketoacidosis through fluid and insulin sequencing to adolescent cerebral-edema surveillance.",
 exhibits:{
  history:{name:"History & Presentation", type:"text", body:"17-year-old female, brought in by her mother. No previous diagnosis of diabetes. Three days of passing large volumes of urine, drinking constantly, and waking several times each night. Vomiting since yesterday, generalized abdominal pain, no diarrhea, no fever. Two kilograms of weight loss over two weeks. Previously well; no regular medicines; no allergies. Menarche at 12, cycles regular. School exam stress reported. Weight 52 kg."},
  vitals:{name:"Vital Signs (on arrival)", type:"kv", rows:[["Temperature","37.2 °C (99.0 °F)"],["Heart rate","124/min"],["Respiratory rate","32/min, deep and sighing"],["Blood pressure","96/58 mm Hg"],["SpO2 (room air)","98%"],["Capillary glucose","28.4 mmol/L (512 mg/dL)"],["Glasgow Coma Scale","14 (E4 V4 M6) — rousable, slow to answer"],["Capillary refill","3 seconds"]]},
  labs:{name:"Venous Blood Gas & Laboratory Results", type:"kv", rows:[["pH","7.14"],["PaCO2","22 mm Hg"],["Bicarbonate","9 mEq/L"],["Sodium","131 mEq/L"],["Potassium","5.4 mEq/L"],["Chloride","98 mEq/L"],["Blood ketones","4.8 mmol/L"],["Urea","9.2 mmol/L"],["Creatinine","1.1 mg/dL"],["White cell count","15,800/mm³"],["HbA1c","11.8%"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. 0.9% sodium chloride 10 mL/kg over the first hour, then 250 mL/hr. 2. Fixed-rate intravenous insulin infusion 0.1 unit/kg/hr (5.2 units/hr) — start after the fluid bolus. 3. Add potassium chloride 40 mEq/L to the maintenance fluid once urine output is confirmed and potassium is below 5.2 mEq/L. 4. Capillary glucose hourly. 5. Venous blood gas and ketones every 2 hours. 6. Potassium every 2 hours. 7. Strict hourly intake and output; urinary catheter only if output cannot be measured. 8. Nil by mouth. 9. Neurological observations including Glasgow Coma Scale every 30 minutes. 10. Pediatric diabetes team notified."},
  notes:{name:"Nurse's Notes", type:"text", body:"0930: Alert but slow to respond, asks for water repeatedly. Breath has a sweet, pear-drop odor. Mucous membranes dry, skin turgor reduced. Abdomen soft, generalized tenderness, no guarding. Mother states: “She has been drinking the whole bottle of juice and still says she is thirsty.” 1015: Fluid bolus running. Mother asks whether the insulin can be started at the same time so her daughter improves faster."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the presentation and laboratory results. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","labs"],
   opts:["The ketonemia with a high anion gap metabolic acidosis identifies diabetic ketoacidosis rather than a hyperosmolar state",
    "The glucose above 28 mmol/L confirms a hyperosmolar hyperglycemic state, since ketones are not part of that picture",
    "The vomiting and abdominal pain indicate gastroenteritis with dehydration in a client who happens to have high glucose",
    "The potassium of 5.4 mEq/L shows that her total body potassium is elevated and needs no replacement"],
   ans:0,
   rat:{c:"The anion gap is 131 − 98 − 9 = 24 with ketones of 4.8 mmol/L and a pH of 7.14, which is ketoacidosis; a hyperosmolar state is defined by osmolality above 320 mOsm/kg with only trace ketones and no significant acidosis, which this picture is not. Abdominal pain and vomiting are consequences of the acidosis, not a separate gastroenteritis. The serum potassium of 5.4 is misleading: acidosis and insulin deficiency shift potassium out of cells, so total body potassium is profoundly depleted even though the level reads high.",
   o:["Correct — anion gap 24 plus ketones 4.8 plus pH 7.14 is DKA.",
    "A glucose above 28 mmol/L occurs in both states; osmolality and ketones discriminate, and glucose alone proves nothing.",
    "Vomiting and abdominal pain are classic DKA features caused by the acidosis — anchoring on them delays the diagnosis.",
    "Serum potassium overstates total body stores in DKA; the level falls sharply once insulin starts."],
   s:"DKA versus hyperosmolar state: compute the anion gap and look at ketones. And never trust a normal or high potassium in DKA — total body potassium is always depleted."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every laboratory value below that falls outside the expected reference range.",
   reveal:["labs","vitals"],
   hotspot:{mode:"rows", rows:[
    "pH 7.14",
    "Bicarbonate 9 mEq/L",
    "Potassium 5.4 mEq/L",
    "Sodium 131 mEq/L",
    "Chloride 98 mEq/L",
    "Creatinine 1.1 mg/dL"
   ], ans:[0,1,2,3]},
   rat:{c:"Acidemia, bicarbonate consumed by buffering, potassium shifted extracellularly, and a low measured sodium are all abnormal. Chloride 98 mEq/L sits inside 96–106 and creatinine 1.1 mg/dL inside the adult range — two planted normals. The low sodium is partly dilutional: correcting for the glucose of 512 mg/dL adds roughly 1.6 mEq/L per 100 mg/dL above 100, giving a corrected sodium near 138 mEq/L, so the hyponatremia is not a true sodium deficit.",
   o:["Normal arterial pH is 7.35–7.45; 7.14 is severe acidemia.",
    "Expected bicarbonate is 22–26 mEq/L; 9 shows buffering is exhausted.",
    "Expected potassium is 3.5–5.0 mEq/L; 5.4 is high — but see the rationale.",
    "Expected sodium is 135–145 mEq/L; 131 is low, largely dilutional from hyperglycemia.",
    "Normal chloride is 96–106 mEq/L — within range.",
    "Normal adult creatinine is about 0.6–1.2 mg/dL — within range."],
   s:"Know the reference ranges cold so the planted normals fall away instantly, and remember that the measured sodium in DKA must be corrected for the glucose before you judge volume status."}},
  {step:"prioritize", t:"single", stem:"The mother asks whether the insulin can be started immediately alongside the fluid so her daughter improves faster. Which problem does the nurse identify as the priority in the first hour?",
   reveal:["history","vitals","labs","orders","notes"],
   opts:["Severe volume deficit, so isotonic sodium chloride resuscitation precedes the insulin infusion",
    "Hyperglycemia, so an intravenous insulin bolus should be given to bring the glucose down quickly",
    "Hyperkalemia at 5.4 mEq/L, so calcium gluconate is needed to protect the myocardium",
    "Metabolic acidosis, so sodium bicarbonate should be added because the pH is below 7.30"],
   ans:0,
   rat:{c:"She has lost several liters of fluid osmotically, with a heart rate of 124/min, a blood pressure of 96/58 mm Hg and a capillary refill of 3 seconds, so restoring circulating volume comes first — it also improves perfusion and begins to lower glucose and ketones on its own. An insulin bolus is not recommended in adolescents because it is associated with cerebral edema and with a faster fall in potassium. Calcium gluconate treats life-threatening hyperkalemia with ECG change, not a potassium of 5.4 that is about to fall. Bicarbonate is reserved for a pH below 6.9 and worsens intracellular acidosis and cerebral outcomes when used above that threshold.",
   o:["Correct — volume restoration is the first hour's priority and it precedes insulin.",
    "Bolus insulin is not recommended in adolescent DKA; it is linked to cerebral edema and accelerates hypokalemia.",
    "Potassium 5.4 mEq/L with no ECG change does not warrant calcium gluconate, and the level will fall with insulin.",
    "Bicarbonate is indicated only below pH 6.9; at 7.14 it worsens intracellular acidosis and cerebral risk."],
   s:"DKA first hour = volume. Fluids before insulin, no bolus in adolescents, no bicarbonate above pH 6.9, and a potassium of 5.4 is a falling value not a treatment target."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care for the next several hours? Select all that apply.",
   reveal:["history","vitals","labs","orders","notes"],
   opts:["0.9% sodium chloride at the prescribed rate with strict hourly intake and output",
    "Fixed-rate intravenous insulin infusion at 0.1 unit/kg/hour",
    "Potassium chloride added to the fluid once urine output is confirmed and the level falls below 5.2 mEq/L",
    "Sodium bicarbonate added to the fluid because the pH is below 7.30",
    "Stopping the insulin infusion once the capillary glucose falls below 14 mmol/L"],
   ans:[0,1,2],
   rat:{c:"Volume replacement, a fixed-rate insulin infusion, and protocol-driven potassium replacement are the three pillars of DKA management. Bicarbonate at a pH of 7.14 causes harm rather than benefit. Stopping insulin when the glucose normalizes is the classic error: the acidosis outlasts the hyperglycemia, so the infusion continues and dextrose is added to the fluid instead, allowing ketone clearance to finish.",
   o:["Correct — isotonic saline with hourly balance monitoring restores perfusion.",
    "Correct — a fixed-rate infusion at 0.1 unit/kg/hr, started after the fluid bolus.",
    "Correct — potassium is added once output is confirmed and the level drops below the protocol threshold.",
    "Bicarbonate is reserved for pH below 6.9 and worsens intracellular acidosis.",
    "Insulin must continue until ketones and the anion gap resolve; dextrose is added, the infusion is not stopped."],
   s:"The insulin infusion treats the ketoacidosis, not the number on the glucose meter. When glucose falls below about 14 mmol/L, add dextrose and keep the insulin running."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","labs","orders","notes"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Obtain intravenous access, take baseline bloods and start the 0.9% sodium chloride bolus",
     "Attach cardiac monitoring and commence hourly glucose with 2-hourly ketones, venous blood gas and potassium",
     "Start the fixed-rate intravenous insulin infusion at 0.1 unit/kg/hour",
     "Add potassium chloride to the maintenance fluid once output is confirmed and the level falls below 5.2 mEq/L"],
    ans:[0,1,2,3]},
   rat:{c:"Access and volume come first because insulin given into an unresuscitated, potassium-depleted client precipitates circulatory collapse and dangerous hypokalemia. Monitoring must be in place before the insulin starts, since the infusion drives glucose and potassium down on a fixed schedule that needs checking. Potassium replacement follows, because adding potassium before confirming urine output and a falling level risks iatrogenic hyperkalemia in an oliguric client.",
   o:["Access, baseline bloods and volume resuscitation — the prerequisite for everything else.",
    "Monitoring must precede the infusion so the rate of fall in glucose and potassium is visible.",
    "Insulin starts after the fluid bolus, once monitoring is running.",
    "Potassium follows confirmed output and a level below the protocol threshold."],
   s:"DKA sequence: volume → monitoring → insulin → potassium. Insulin before volume and before monitoring is how DKA kills."}},
  {step:"evaluate", t:"cloze", stem:"Six hours later the glucose is 11.2 mmol/L, ketones 0.8 mmol/L, pH 7.31 and potassium 3.4 mEq/L. She is awake, asking for food, and her headache has come on over the last hour. Complete each evaluation statement.",
   reveal:["vitals","labs","orders","notes"],
   cloze:{lines:[
    {pre:"Because the glucose has fallen but the acidosis is still resolving, the nurse continues the insulin infusion and ", post:".",
     opts:["stops the infusion since the glucose is approaching normal","adds dextrose to the intravenous fluid so the infusion can continue","doubles the insulin rate to clear the remaining ketones","replaces the infusion with subcutaneous insulin immediately"], ans:1},
    {pre:"The potassium of 3.4 mEq/L means the nurse should ", post:".",
     opts:["withhold potassium until the level rises above 4.0 mEq/L","document it as an expected finding requiring no action","give calcium gluconate to stabilize the myocardium","increase the potassium replacement and inform the prescriber"], ans:3},
    {pre:"Given her age and the new headache, the nurse watches most urgently for ", post:".",
     opts:["a rising temperature suggesting an underlying infection","increased urine output suggesting fluid overload","a falling conscious level with bradycardia and rising blood pressure suggesting cerebral edema","abdominal guarding suggesting appendicitis"], ans:2},
    {pre:"Before the switch to subcutaneous insulin, the nurse ensures that ", post:".",
     opts:["the infusion is stopped first and the subcutaneous dose given two hours later","the venous pH has risen above 7.45","she has eaten a full meal before any injection","the subcutaneous dose is given 30 to 60 minutes before the infusion is stopped"], ans:3}]},
   rat:{c:"Glucose normalizes hours before the ketoacidosis resolves, so dextrose is added and the infusion continues rather than stopped. A potassium of 3.4 mEq/L in a client still on insulin is an urgent replacement need, not a benign trend. In an adolescent, a new headache during DKA treatment is cerebral edema until proven otherwise — the triad is falling conscious level with bradycardia and hypertension, and it needs immediate escalation. And an overlap of 30 to 60 minutes prevents rebound hyperglycemia and recurrent ketosis when the infusion stops.",
   o:["Stopping the infusion restarts ketosis — the acidosis has not resolved at pH 7.31.",
    "Correct — dextrose lets the insulin continue while protecting against hypoglycemia.",
    "Doubling the rate risks hypoglycemia and a faster potassium fall without clearing ketones sooner.",
    "Subcutaneous insulin alone cannot be relied on until the overlap is planned.",
    "Withholding potassium while insulin continues drives the level down further.",
    "A potassium of 3.4 mEq/L during insulin therapy is never a no-action finding.",
    "Calcium gluconate treats hyperkalemia with ECG change; this client is hypokalemic.",
    "Correct — increase replacement and escalate; the level will keep falling while insulin runs.",
    "Fever would matter, but a new headache in adolescent DKA points somewhere more urgent.",
    "Fluid overload presents with respiratory signs, not headache.",
    "Correct — headache with falling conscious level, bradycardia and hypertension is cerebral edema and needs immediate treatment.",
    "Abdominal pain in DKA resolves as the acidosis corrects; guarding would change the picture, but headache comes first here.",
    "Stopping first leaves a gap with no circulating insulin and invites rebound ketosis.",
    "A pH above 7.45 is not a switching criterion and would represent overcorrection.",
    "Eating is not required before the overlap dose and she is still nil by mouth.",
    "Correct — a 30 to 60 minute overlap prevents rebound hyperglycemia and recurrent ketosis."],
   s:"Adolescent DKA has two traps that kill: stopping insulin when the glucose looks fine, and missing the new headache. Cerebral edema is the leading cause of death in pediatric DKA — a headache during treatment is an emergency, not a symptom to document."}}]})
;
