/* RN Ready — case study v2 · hematologic (sickle cell vaso-occlusive crisis).
   Fourth unfolding case: a young adult pain crisis that spans all six NCJMM steps,
   from recognizing cues in a noisy triage to evaluation and discharge teaching.
   Later exhibits are only revealed at later steps — the case unfolds.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-SCD-01", title:"The 8/10 Backache — Mr. J., 19",
 setting:"Emergency department", sys:"HEME", cn:"PAA", d:2, b:0.25,
 summary:"19-year-old college student with sickle cell disease arrives with severe back and thigh pain that began after cold-water swim tryouts; judgment unfolds from cues to hydration-analgesia management and prevention teaching.",
 exhibits:{
  history:{name:"Triage Note", type:"text", body:"19-year-old man with sickle cell disease (HbSS), followed at the hematology clinic since childhood. Brought to the ED by a roommate at 0300: lower back and both thighs aching, started yesterday evening after fraternity swim tryouts in a cool pool, now 8/10 and unrelieved by two doses of his home pain medication. Last dose this morning. No fever or cough. Home meds: hydroxyurea 1000 mg daily (missed the last 2 days), folic acid. Baseline hemoglobin 8.4 g/dL per clinic card. No prior intensive-care admissions; 2–3 prior pain episodes treated with IV fluids and IV opioids."},
  vitals:{name:"Vital Signs", type:"kv", rows:[["Temperature","37.0 °C (98.6 °F)"],["Heart rate","114/min"],["Blood pressure","122/74 mm Hg"],["Respiratory rate","22/min"],["SpO2 (room air)","94%"],["Pain (client-stated)","8/10"]]},
  assess:{name:"Nurse's Assessment", type:"text", body:"Alert, restless, constantly shifting position on the stretcher. Sclerae mildly icteric — unchanged from baseline per client. Lungs clear with even breath sounds; no chest pain reported. Abdomen soft, no tenderness. No focal leg swelling or warmth; thighs and lumbar back are diffusely tender to palpation without erythema. Grips strong, capillary refill <2 seconds. Urine dark amber; last void 9 hours ago at home. Has drunk only a bottle of water since morning."},
  labs:{name:"Laboratory Results", type:"kv", rows:[["Hemoglobin","7.1 g/dL (baseline 8.4)"],["Reticulocytes","14%"],["White blood cells","13,600/mm³"],["Platelets","410,000/mm³"],["Total bilirubin","3.4 mg/dL (baseline ~2.8)"],["Lactate dehydrogenase","620 U/L (elevated)"],["Serum creatinine","1.1 mg/dL (baseline)"],["Urinalysis","Concentrated; no blood, no nitrites"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. Admit to medical unit for vaso-occlusive pain episode. 2. Normal saline 125 mL/hr continuous. 3. Morphine 4 mg IV every 3 hours as needed for pain >4/10, with naloxone available. 4. Incentive spirometry 10 breaths every 2 hours while awake. 5. Encourage oral fluids to 2 L/day. 6. Hydroxyurea 1000 mg by mouth daily. 7. Folic acid 1 mg by mouth daily. 8. Pulse oximetry continuous; notify if SpO2 below 92%. 9. Complete blood count and reticulocytes every morning."},
  reassess:{name:"Reassessment — 12 Hours Later", type:"kv", rows:[["Heart rate","92/min"],["Respiratory rate","16/min"],["SpO2 (room air)","96%"],["Pain (client-stated)","4/10, achy, not sharp"],["Urine color","Pale yellow; voiding every 2–3 hours"],["Oral intake","1400 mL since admission"],["Temperature","36.9 °C (98.4 °F)"]]}},
 items:[
  {step:"recognize", t:"single", stem:"Reviewing the triage note and the nurse's assessment, which cluster of cues best explains this client's severe pain?",
   reveal:["history","vitals","assess"],
   opts:["Cold exposure and dehydration followed by diffuse bone pain in a man with HbSS",
    "New fever with unilateral leg swelling and warmth suggesting a deep vein thrombosis",
    "Progressive weakness with dark urine after strenuous exercise suggesting rhabdomyolysis",
    "Focal back tenderness with morning stiffness suggesting a mechanical lumbar strain"],
   ans:0,
   rat:{c:"The classic trigger pattern for a vaso-occlusive crisis is present: cold-water exposure, hours since oral intake (one bottle), urine dark and concentrated with a 9-hour void gap, plus symmetric back/thigh bone pain in HbSS. There is no fever, no unilateral swelling, and no focal mechanical pattern.",
   o:["Correct — cold + dehydration + symmetric marrow-bone pain = vaso-occlusion.",
    "No fever, no calf findings, symmetric pain — thrombosis is not suggested.",
    "Pain pattern is marrow/diffuse, not muscle-bulk pain; urinalysis shows concentration, not myoglobin.",
    "No injury, no morning stiffness pattern; diffuse symmetric involvement fits marrow, not mechanical strain."],
   s:"Recognize the trigger trio — cold, dehydration, exertion — behind bone pain in HbSS. Things that are ABSENT (fever, swelling, trauma) are just as diagnostic."}},
  {step:"analyze", t:"hotspot", stem:"The client asks why he feels so much worse than his usual flares. Highlight every laboratory or assessment finding that indicates this episode involves increased hemolysis compared with his baseline.",
   reveal:["labs","assess"],
   hotspot:{mode:"rows", rows:["Hemoglobin 7.1 g/dL, down from a baseline of 8.4 g/dL","Reticulocytes 14%","White blood cells 13,600/mm³","Total bilirubin 3.4 mg/dL, above his baseline of 2.8","Lactate dehydrogenase 620 U/L (elevated)","Serum creatinine 1.1 mg/dL (at his baseline)","Sclerae mildly icteric, unchanged from baseline"], ans:[0,1,3,4]},
   rat:{c:"Increased hemolysis shows as a falling hemoglobin, a rising reticulocyte count (marrow compensating), rising bilirubin and LDH from broken-down cells. The leukocytosis reflects stress/inflammation in SCD rather than hemolysis, creatinine is at baseline, and icterus explicitly unchanged is baseline, not new.",
   o:["Correct — a 1.3 g/dL drop from baseline signals active destruction.",
    "Correct — reticulocytosis is the marrow's response to hemolysis.",
    "Leukocytosis is common in SCD crises (stress/inflammation) and not a hemolysis marker.",
    "Correct — bilirubin released from broken cells is climbing above HIS baseline.",
    "Correct — LDH released from lysed red cells is elevated.",
    "Renal function at baseline does not track hemolysis.",
    "Explicitly unchanged from baseline — jaundice that is not new is not increased hemolysis."],
   s:"Analyze hemolysis as a pathway: drop in Hgb + rise in retics, bilirubin, LDH. Compare every value to the client's OWN baseline, not the lab sheet."}},
  {step:"generate", t:"multi", stem:"Which elements of the plan should the nurse expect for this acute painful episode? Select all that apply.",
   reveal:["history","vitals","labs"],
   opts:["Intravenous opioid analgesia on a regular schedule, not only on demand",
    "Aggressive IV fluid boluses of normal saline 500 mL every hour to force diuresis",
    "Incentive spirometry to prevent atelectasis and acute chest syndrome",
    "Continuous pulse oximetry with a threshold for notification",
    "Placing the client on strict bedrest with all activity eliminated"],
   ans:[0,2,3],
   rat:{c:"Acute pain episodes are treated with scheduled IV opioids (preventing pain cycling), judicious maintenance-rate fluids (not boluses — overload risks pulmonary complications), incentive spirometry against acute chest syndrome, and oximetry monitoring. Eliminating all activity is unnecessary; gentle movement is encouraged.",
   o:["Correct — scheduled dosing keeps pain ahead of the cycle; PRN-only is undertreatment.",
    "Fluid BOLUSES are not routine — euvolemic maintenance replaces deficits; overload worsens lung physiology.",
    "Correct — stasis atelectasis is the gateway to acute chest syndrome; breathing exercises are standard.",
    "Correct — a defined SpO2 threshold (e.g., below 92%) triggers evaluation.",
    "Rest is relative: comfort positioning and gentle activity, not enforced immobilization."],
   s:"Generate the crisis bundle: scheduled opioids + maintenance fluids + spirometry + monitoring. Watch for the two classic distractors: fluid boluses and total immobilization."}},
  {step:"act", t:"emr", stem:"Review each provider order for this admitted client. Open each panel and select the orders to implement now, the orders to clarify with the provider first, and the order that is routine but time-deferrable.",
   reveal:["orders"],
   groups:[
    {h:"Implement now", opts:["Normal saline 125 mL/hr continuous","Morphine 4 mg IV every 3 hours PRN pain >4/10","Incentive spirometry 10 breaths every 2 hours","Continuous pulse oximetry with SpO2 below 92% notification"], ans:[0,1,2,3]},
    {h:"Clarify with provider first", opts:["Hydroxyurea 1000 mg daily while the pain episode is active","Repeat complete blood count with the hemoglobin now 7.1 g/dL"], ans:[0,1]},
    {h:"Routine, time-deferrable", opts:["Folic acid 1 mg daily"], ans:[0]}],
   rat:{c:"Fluids, analgesia, spirometry, and monitoring are the immediate crisis orders. Hydroxyurea is a chronic disease-modifier — during an acute painful episode with falling hemoglobin, restarting it merits a provider conversation, as does the anemia threshold for transfusion. Folic acid is important but not time-critical tonight.",
   o:["Correct — euvolemic maintenance hydration starts now.","Correct — the pain must be controlled on schedule.","Correct — spirometry prevents acute chest syndrome from the first night.","Correct — monitoring for hypoxia is continuous from arrival.",
    "Correct — myelosuppressive chronic therapy during an acute episode with Hgb 7.1 deserves a same-day conversation.","Correct — the drop from baseline raises the transfusion-threshold question for the provider.",
    "Correct — supplementation continues, but nothing about 0300 makes it urgent."],
   s:"Act by urgency: crisis therapy now, decisions that depend on new data (Hgb trajectory, cytopenic therapy) get clarified, and routine supplements wait for morning."}},
  {step:"evaluate", t:"single", stem:"Twelve hours into treatment, review the reassessment panel. Which interpretation is most accurate?",
   reveal:["reassess","orders"],
   opts:["Heart rate and pain improving with pale urine indicates the vaso-occlusive episode is resolving as intended",
    "Pain at 4/10 means the client is over-sedated and opioids should be halved immediately",
    "SpO2 of 96% signals it is time to wean all monitoring to once-per-shift spot checks",
    "Oral intake of 1400 mL in 12 hours is inadequate and requires a feeding-tube discussion"],
   ans:0,
   rat:{c:"Falling heart rate (114→92), falling pain score, improving urine color and voiding pattern, and stable temperature are exactly the expected trajectory: hemodilution of sickled cells, perfusion restored, pain cycling interrupted. Evaluation should CONFIRM the plan, not dismantle it.",
   o:["Correct — every tracked parameter moved the right way; continue the plan.",
    "4/10 is controlled, not over-sedated — sedation is assessed by arousability and respirations, not pain score.",
    "No chest signs + good saturation is reassuring, but continuous monitoring during opioid therapy continues.",
    "1400 mL orally in 12 hours is on pace for the 2 L/day goal — intake is adequate."],
   s:"Evaluate against the plan's OWN targets: rate, pain, urine, temperature. Improvement means continuation, not de-escalation of monitoring."}},
  {step:"reflect", t:"cloze", stem:"Before discharge the next day, the nurse completes prevention teaching with Mr. J. Complete each teaching point.",
   reveal:["history","orders"],
   cloze:{lines:[
    {pre:"To lower the chance of another pain episode after swim activities, the client should ", post:" after leaving the water.",
     opts:["warm up and change into dry clothing promptly","stay in the cold pool as long as possible","skip fluids until the next meal","avoid all swimming permanently"], ans:0},
    {pre:"Taking hydroxyurea ", post:" keeps its protection against pain episodes working best.",
     opts:["daily as prescribed, without skipping doses","only on days when pain is present","as two extra doses before swim practice","until the last prescription runs out"], ans:0},
    {pre:"He should seek urgent care right away if he develops ", post:" along with cough or chest pain.",
     opts:["fever, new cough, or trouble breathing","mild muscle soreness after exercise","a headache that resolves with rest","an occasional skipped home dose"], ans:0}]},
   rat:{c:"Prevention teaching has three pillars: rewarm and dry immediately after cold-water exposure (remove the trigger), take hydroxyurea consistently (its benefit is cumulative on fetal hemoglobin), and recognize acute chest syndrome early — fever with respiratory symptoms in SCD is an emergency.",
   o:["Correct — remove the cold trigger: warm up, dry off, dress warmly.","Cold prolongs vasoconstriction — the opposite of prevention.","Dehydration is a primary trigger; fluids continue.","Swimming is encouraged with precautions — avoidance is unnecessary.",
    "Correct — daily adherence maintains fetal hemoglobin reduction of crises.","PRN hydroxyurea has no mechanism and no evidence.","Extra doses add myelosuppression risk without benefit.","Stopping when the bottle empties abandons therapy silently.",
    "Correct — fever + respiratory symptoms = suspected acute chest syndrome, an emergency.","Post-exercise soreness is expected muscle recovery.","A resolving headache is not a sickle emergency.","One missed dose warrants resumption and counseling, not the ED."],
   s:"Discharge teaching for SCD: control the triggers (cold, dehydration), keep the chronic medicine chronic, and give the family a hard rule for fever plus breathing = return immediately."}}]}
);
