/* RN Ready — case study v2 · adrenal crisis after abrupt steroid withdrawal.
   Twenty-second unfolding case: a 45-year-old with Addison's disease stops his
   hydrocortisone, then develops gastroenteritis and cannot keep tablets down.
   Judgment unfolds from the classic electrolyte triad, through giving
   hydrocortisone before any confirmatory test, to the sick day rules and the
   emergency injection kit that prevent the next crisis.

   Wave 67 — RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-ADRENAL-01", title:"The Stopped Tablets — Mr. Kalu, 45",
 setting:"Emergency department", sys:"ENDO", cn:"PHA", d:3, b:0.55,
 summary:"45-year-old man with Addison's disease who stopped his hydrocortisone five days ago and now has vomiting, a blood pressure of 78/44 mm Hg, sodium 126 mmol/L, potassium 6.1 mmol/L and glucose 2.9 mmol/L. Judgment unfolds from the electrolyte triad, through giving hydrocortisone before any confirmatory test, to sick day rules and the emergency injection kit.",
 exhibits:{
  history:{name:"History", type:"text", body:"45-year-old man with primary adrenal insufficiency (Addison's disease) diagnosed four years ago, on hydrocortisone 20 mg each morning and 10 mg each afternoon plus fludrocortisone 100 micrograms daily. He stopped all of it five days ago after reading online that steroids are harmful, saying he 'felt fine without them'. For the last 36 hours he has had vomiting and diarrhea and cannot keep anything down, including his tablets when he tried to restart them. Brought in by his partner, who reports increasing drowsiness and abdominal pain. No emergency injection kit at home."},
  vitals:{name:"Observations", type:"kv", rows:[["Blood pressure","78/44 mm Hg lying, 62/38 sitting"],["Heart rate","122/min"],["Respiratory rate","24/min"],["Core temperature","37.9 °C (100.2 °F)"],["SpO2 (room air)","96%"],["Capillary glucose","2.9 mmol/L (52 mg/dL)"],["Neurological","Drowsy, slow to answer, oriented to person only"],["Skin","Tanned, with pigmentation of the palmar creases and gums"]]},
  labs:{name:"Laboratory Results", type:"kv", rows:[["Sodium","126 mmol/L"],["Potassium","6.1 mmol/L"],["Urea","18.4 mmol/L"],["Creatinine","156 µmol/L (1.76 mg/dL) — baseline 84 µmol/L"],["Glucose","2.9 mmol/L"],["Cortisol","sent, result pending"],["Adrenocorticotropic hormone","sent, result pending"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. Hydrocortisone 100 mg IV immediately, then 50 mg IV every 6 hours or a 200 mg/24 hour infusion. 2. Do NOT wait for the cortisol or adrenocorticotropic hormone result before giving the first dose. 3. 0.9% sodium chloride 1 L rapidly, then guided by reassessment. 4. Treat the hypoglycemia; check glucose hourly. 5. Fludrocortisone is NOT needed while receiving stress-dose hydrocortisone. 6. Continuous cardiac monitoring for the potassium of 6.1 mmol/L. 7. Identify and treat the precipitant — infection screen, chest radiograph, urine culture. 8. Strict fluid balance and daily weight. 9. Endocrine referral. 10. Do not discharge without an emergency injection kit and sick day teaching."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the history, observations and laboratory results. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","labs"],
   opts:["He has gastroenteritis with dehydration, so intravenous fluids alone will correct the picture",
    "Abrupt steroid withdrawal with vomiting has precipitated an adrenal crisis, and the hydrocortisone must be given before any confirmatory test",
    "The potassium of 6.1 mmol/L is the emergency, so calcium gluconate is the priority and the steroid can wait",
    "The low sodium indicates over-hydration, so fluid restriction is the correct treatment"],
   ans:1,
   rat:{c:"This is an adrenal crisis: five days without replacement, a gastrointestinal illness that removed even the possibility of oral dosing, and the classic picture of refractory hypotension with postural collapse, hyponatremia, hyperkalemia and hypoglycemia. Aldosterone deficiency causes sodium loss and potassium retention, while cortisol deficiency causes hypoglycemia and loss of vascular tone — which is why the hypotension will not respond to fluids alone and needs glucocorticoid. Fluids are essential but are not sufficient on their own. The potassium is dangerous but the steroid is the definitive treatment and the hydrocortisone has mineralocorticoid activity at this dose. And restricting fluid in a client who is profoundly volume depleted would be catastrophic.",
   o:["Fluids alone cannot correct cortisol deficiency; the hypotension is refractory without glucocorticoid.",
    "Correct — abrupt withdrawal plus vomiting precipitated the crisis, and hydrocortisone comes before any test.",
    "The potassium is dangerous, but hydrocortisone is the definitive treatment and must not wait; monitoring covers the potassium meanwhile.",
    "The low sodium is from aldosterone-deficient sodium wasting with volume depletion, not over-hydration."],
   s:"Adrenal crisis triad: hyponatremia, hyperkalemia, hypoglycemia with refractory hypotension. Abrupt steroid withdrawal plus any illness is the classic setup — and fluids alone will not fix it."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected reference range.",
   reveal:["vitals","labs"],
   hotspot:{mode:"rows", rows:[
    "Sodium 126 mmol/L",
    "Potassium 6.1 mmol/L",
    "Glucose 2.9 mmol/L",
    "Blood pressure 78/44 mm Hg with a postural drop to 62/38 mm Hg",
    "Oxygen saturation 96% on room air",
    "Core temperature 37.9 °C"
   ], ans:[0,1,2,3]},
   rat:{c:"The hyponatremia, hyperkalemia, hypoglycemia and refractory hypotension with a postural drop are the four abnormal findings, and together they are pathognomonic — the electrolyte pattern specifically points at aldosterone deficiency rather than generic dehydration. A saturation of 96% on room air is normal. A temperature of 37.9 °C is mildly raised and matters clinically as a likely precipitant, but it is not part of the diagnostic pattern; the point of including it is that the precipitant must be found and treated, because steroid replacement alone leaves the trigger in place.",
   o:["Expected sodium is 135–145 mmol/L; 126 reflects aldosterone-deficient sodium wasting.",
    "Expected potassium is 3.5–5.0 mmol/L; 6.1 reflects aldosterone-deficient potassium retention.",
    "Expected glucose is 4–7.8 mmol/L; 2.9 reflects cortisol deficiency.",
    "Expected systolic pressure is above 100 mm Hg; 78/44 with a postural drop is refractory hypotension.",
    "Normal saturation is 95% and above — within range.",
    "37.9 °C is mildly raised and important as a likely precipitant, but is not part of the diagnostic pattern."],
   s:"Read the electrolytes as a pattern: low sodium plus high potassium plus low glucose is aldosterone and cortisol deficiency. A generic dehydration picture does not produce that combination — and always hunt for the precipitant."}},
  {step:"prioritize", t:"single", stem:"The cortisol and adrenocorticotropic hormone samples have been sent but the results will take hours. Which action by the nurse takes priority?",
   reveal:["history","vitals","labs","orders"],
   opts:["Give hydrocortisone 100 mg intravenously immediately without waiting for the cortisol result",
    "Wait for the cortisol result so the diagnosis is confirmed before giving a steroid",
    "Give fludrocortisone orally, since that is the mineralocorticoid he has been missing",
    "Give an antihypertensive, since his blood pressure is unstable"],
   ans:0,
   rat:{c:"Adrenal crisis is a clinical diagnosis and treatment must never wait for biochemical confirmation — the cortisol level is drawn for the record, but an untreated crisis is fatal within hours while a mistakenly given dose of hydrocortisone is harmless. Blood should be sent before the first dose where it can be done in seconds, but the dose is not held for it. Oral fludrocortisone is useless here: he is vomiting, cannot absorb it, and stress-dose hydrocortisone already has ample mineralocorticoid activity, so fludrocortisone is not given during a crisis. And his blood pressure is low, not high — an antihypertensive would be dangerous.",
   o:["Correct — treat on the clinical picture; an untreated crisis is fatal within hours while a dose given in error is harmless.",
    "Waiting for a confirmatory level in a hypotensive, hypoglycemic client risks death for no benefit.",
    "He is vomiting and cannot absorb oral medication, and stress-dose hydrocortisone already provides mineralocorticoid activity.",
    "His blood pressure is 78/44 mm Hg; an antihypertensive would be dangerous."],
   s:"Treat adrenal crisis on the clinical picture and never wait for the cortisol. Draw the sample if it takes seconds, but the dose is not held for it — and no fludrocortisone during a crisis, because stress-dose hydrocortisone covers it."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["history","vitals","labs","orders"],
   opts:["Hydrocortisone 100 mg intravenously now, then 50 mg every 6 hours or a continuous infusion",
    "Rapid 0.9% sodium chloride with reassessment, since he is profoundly volume depleted",
    "Hourly glucose checks with treatment of the hypoglycemia",
    "An infection screen to identify and treat the precipitant",
    "Withholding the fludrocortisone, since stress-dose hydrocortisone already provides mineralocorticoid activity"],
   ans:[0,1,2,3,4],
   rat:{c:"All five are correct, and the fifth is the one that catches people out: fludrocortisone is deliberately withheld during a crisis because hydrocortisone at 50 mg or more has sufficient mineralocorticoid activity, so adding it risks sodium retention and hypertension as he recovers. The steroid replaces what is missing, the saline replaces the volume the aldosterone deficiency has wasted, the hourly glucose covers cortisol-deficient hypoglycemia which can recur, and the infection screen matters because replacing steroid without treating the precipitant leaves the driver in place — the crisis will simply recur.",
   o:["Correct — 100 mg then 50 mg every 6 hours, or a continuous infusion.",
    "Correct — rapid saline for profound volume depletion, with reassessment.",
    "Correct — cortisol-deficient hypoglycemia can recur, so glucose is checked hourly.",
    "Correct — the precipitant must be found and treated or the crisis will recur.",
    "Correct — fludrocortisone is withheld during a crisis because stress-dose hydrocortisone covers mineralocorticoid need."],
   s:"Adrenal crisis management: stress-dose hydrocortisone, rapid saline, hourly glucose, find the precipitant — and withhold fludrocortisone, because high-dose hydrocortisone already has the mineralocorticoid effect."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["history","vitals","labs","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Give hydrocortisone 100 mg intravenously and secure access for fluid",
     "Start rapid 0.9% sodium chloride and treat the hypoglycemia",
     "Attach cardiac monitoring, catheterize for hourly output and take the infection screen",
     "Arrange the emergency injection kit, medical alert identification and sick day teaching before discharge"],
    ans:[0,1,2,3]},
   rat:{c:"The steroid comes first because it is the definitive treatment and the crisis is immediately life-threatening. Volume and glucose follow within the same minutes, since both are critically deranged. Monitoring, hourly output and the infection screen come next — the output is the resuscitation endpoint and the screen finds the driver. Discharge preparation comes last in sequence but is the intervention that prevents the next crisis: this man stopped his steroids, has no injection kit, and no teaching about doubling his dose when ill, which is exactly how he arrived.",
   o:["Hydrocortisone first — the definitive treatment for an immediately life-threatening crisis.",
    "Rapid saline and glucose correction within the same minutes.",
    "Cardiac monitoring, hourly output and the infection screen.",
    "Injection kit, medical alert identification and sick day teaching — the intervention that prevents the next crisis."],
   s:"Adrenal crisis sequence: steroid → volume and glucose → monitoring and precipitant screen → kit, alert ID and sick day rules. The last step is what stops him coming back the same way."}},
  {step:"evaluate", t:"cloze", stem:"Six hours later his blood pressure is 112/70 mm Hg, his sodium is 131 mmol/L, his potassium is 5.2 mmol/L and his glucose is 5.4 mmol/L. He asks why he cannot just go back to no tablets. Complete each evaluation statement.",
   reveal:["history","vitals","labs","orders"],
   cloze:{lines:[
    {pre:"He asks why he cannot stop his steroids again when he feels well, so the nurse explains that ", post:".",
     opts:["he can stop them whenever he feels well, as long as he restarts them if he feels unwell","they can be reduced to alternate-day dosing, which is safer","abrupt withdrawal removes the cortisol his body cannot make, which is what caused this crisis, so they must never be stopped without medical advice","he should halve the dose gradually on his own initiative"], ans:2},
    {pre:"Because he has had vomiting and could not take his tablets, the nurse recognizes that he must be given ", post:".",
     opts:["an emergency hydrocortisone injection kit with training for him and his partner, since vomiting makes oral replacement impossible","a larger supply of oral tablets only","an antiemetic to use instead of injecting","advice to attend the emergency department only if he loses consciousness"], ans:0},
    {pre:"The nurse teaches him the sick day rules, which are ", post:".",
     opts:["to keep the same dose regardless of illness, since the body adapts","to stop the steroids if he develops a fever","to take extra fluids and reduce the dose when he is unwell","to double or triple the oral dose during illness, use the injection if vomiting, and carry medical alert identification"], ans:3},
    {pre:"Before discharge the nurse also recognizes that he needs ", post:".",
     opts:["no further follow-up, since the crisis has resolved","a steroid card or medical alert bracelet, and endocrine follow-up to restart his maintenance regimen safely","a prescription for an antihypertensive, since his blood pressure has risen","fludrocortisone doubled, to make up for the days he missed"], ans:1}]},
   rat:{c:"He cannot make cortisol, so stopping replacement removes a hormone he has no way of producing — that is what caused this crisis, and no amount of feeling well changes it. An emergency injection kit with training for him and his partner is essential because vomiting makes oral replacement impossible, which is precisely the situation that brought him in. The sick day rules are double or triple the oral dose during illness, inject if vomiting, and carry alert identification — illness increases cortisol demand, so the dose goes up rather than down. And a steroid card or bracelet tells an unconscious patient's clinicians what he needs, alongside endocrine follow-up to restart maintenance safely; missed fludrocortisone days are simply restarted, not doubled.",
   o:["Stopping when he feels well is exactly what caused this admission.",
    "Alternate-day dosing is not appropriate for replacement in primary adrenal insufficiency.",
    "Correct — abrupt withdrawal removes a hormone he cannot produce; steroids are never stopped without medical advice.",
    "Self-directed dose reduction is unsafe and has no physiological basis.",
    "Correct — an injection kit with training, because vomiting makes oral replacement impossible.",
    "More tablets do not help when he cannot keep them down.",
    "An antiemetic is adjunctive; it does not replace the cortisol he cannot absorb.",
    "Waiting for unconsciousness means waiting for a fatal crisis.",
    "A fixed dose ignores the increased cortisol demand during illness.",
    "Stopping during a fever removes the hormone when demand is highest.",
    "The dose goes up during illness, not down.",
    "Correct — double or triple during illness, inject if vomiting, and carry medical alert identification.",
    "Follow-up is essential after a crisis.",
    "Correct — a steroid card or bracelet plus endocrine follow-up to restart maintenance safely.",
    "His blood pressure has recovered to normal; there is no indication for an antihypertensive.",
    "Missed fludrocortisone days are restarted at the usual dose, not doubled."],
   s:"Adrenal insufficiency teaching that saves lives: never stop the steroid, double or triple the dose when ill, inject if vomiting, and carry alert identification. The injection kit exists because vomiting removes the oral route entirely."}}]})
;
