/* RN Ready — case study v2 · acute hemolytic transfusion reaction.
   Twenty-fifth unfolding case: a 45-year-old receiving the second unit of packed
   red cells develops fever, rigors, loin pain, dark red-brown urine, a blood
   pressure of 84/50 mm Hg and oozing from the cannula site. Judgment unfolds
   from recognizing ABO incompatibility, through stopping the transfusion and
   keeping the line open with NEW tubing rather than flushing the existing set,
   to preserving the bag and monitoring for renal failure and disseminated
   intravascular coagulation.

   Wave 67 — RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-TRANSFUSION-01", title:"Forty Minutes Into the Second Unit — Mr. Bello, 45",
 setting:"Acute medical ward", sys:"HEME", cn:"PAA", d:3, b:0.55,
 summary:"45-year-old man receiving the second unit of packed red cells for post-operative anemia develops fever, rigors, loin pain, dark red-brown urine, a blood pressure of 84/50 mm Hg and oozing from the cannula site. Judgment unfolds from recognizing ABO incompatibility, through stopping the transfusion and keeping the line open with new tubing rather than flushing the existing set, to preserving the bag and watching for renal failure and coagulopathy.",
 exhibits:{
  history:{name:"History", type:"text", body:"45-year-old man, day two after emergency laparotomy for a perforated diverticulum. Blood group O positive. Haemoglobin fell to 6.8 g/dL and two units of packed red cells were prescribed. The first unit transfused uneventfully over 2 hours. Forty minutes into the second unit he reports severe loin and back pain, says he feels hot and shivery, and the nurse notices dark red-brown urine in the catheter bag. He also mentions itching at the cannula site, which is now oozing. The second nurse who checked the bag against his identity band is off duty."},
  vitals:{name:"Observations", type:"kv", rows:[["Core temperature","39.2 °C (102.6 °F), from 36.9 °C before the unit started"],["Heart rate","124/min"],["Blood pressure","84/50 mm Hg"],["Respiratory rate","26/min"],["SpO2 (room air)","94%"],["Urine","Dark red-brown; 30 mL drained in the last hour"],["Cannula site","Oozing blood that is not clotting"],["Skin","Flushed, with rigors"]]},
  labs:{name:"Laboratory Results", type:"kv", rows:[["Haemoglobin","7.1 g/dL — no rise despite one full unit"],["Platelets","74 x 10⁹/L, from 190 x 10⁹/L this morning"],["International normalised ratio","2.1, from 1.1 this morning"],["Potassium","5.9 mmol/L"],["Creatinine","142 µmol/L (1.61 mg/dL), from 78 µmol/L this morning"],["Blood cultures","sent"],["Post-reaction samples","clotted and anticoagulated samples required for repeat crossmatch, direct antiglobulin test and plasma free haemoglobin"]]},
  orders:{name:"Provider Orders", type:"text", body:"1. STOP the transfusion immediately. 2. Keep the intravenous line open with 0.9% sodium chloride using NEW administration tubing — do NOT flush the existing blood-filled set. 3. Do NOT discard the blood bag or the tubing; return both to the transfusion laboratory with the client's identity details. 4. Recheck the identity band against the bag labels at the bedside. 5. Notify the provider and the transfusion laboratory immediately. 6. Send the post-reaction blood samples and a urine specimen. 7. Rapid 0.9% sodium chloride to maintain urine output above 100 mL/hour; vasopressors if the blood pressure does not respond. 8. Continuous monitoring for acute kidney injury, disseminated intravascular coagulation and hyperkalaemia. 9. Complete a serious incident report. 10. Do not transfuse any further product until the investigation is complete."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the observations and laboratory results. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","labs"],
   opts:["A febrile non-hemolytic reaction, so an antipyretic and a slower rate are appropriate",
    "An acute hemolytic transfusion reaction from ABO incompatibility, with intravascular hemolysis already causing renal injury and coagulopathy",
    "Sepsis from contaminated blood, so blood cultures and antibiotics are the priority",
    "Post-operative bleeding, since his haemoglobin has not risen and the cannula is oozing"],
   ans:1,
   rat:{c:"Fever and rigors with severe loin pain, dark red-brown urine, hypotension and oozing that will not clot, forty minutes into a unit, is an acute hemolytic reaction until proven otherwise. The laboratory picture confirms it: a haemoglobin that has not risen despite a full unit, a platelet count that has collapsed from 190 to 74, an international normalised ratio that has doubled, potassium released from lysed cells and a creatinine that has nearly doubled — free haemoglobin is directly toxic to the renal tubules. Slowing the rate for a presumed febrile reaction continues to deliver incompatible red cells. Sepsis from a contaminated unit is possible and cultures are correct, but it does not explain the coagulopathy or the haemoglobinuria.",
   o:["A febrile non-hemolytic reaction does not cause loin pain, haemoglobinuria or coagulopathy.",
    "Correct — ABO incompatibility with intravascular hemolysis already causing renal injury and coagulopathy.",
    "Cultures are correct, but contamination does not explain the coagulopathy or the haemoglobinuria.",
    "The falling haemoglobin is from hemolysis, and the oozing is from coagulopathy, not surgical bleeding."],
   s:"Acute hemolytic reaction triad: fever and rigors with loin or back pain, haemoglobinuria, and hypotension — usually from ABO incompatibility and wrong-blood-in-error. The coagulopathy and rising creatinine show it is already systemic."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that indicates active intravascular hemolysis or its complications.",
   reveal:["vitals","labs"],
   hotspot:{mode:"rows", rows:[
    "Dark red-brown urine with an output of 30 mL in the last hour",
    "Platelets 74 x 10⁹/L and an international normalised ratio of 2.1",
    "Potassium 5.9 mmol/L",
    "Creatinine 142 µmol/L against a baseline of 78 µmol/L",
    "Haemoglobin 7.1 g/dL with no rise despite a full unit",
    "Oxygen saturation 94% on room air"
   ], ans:[0,1,2,3,4]},
   rat:{c:"The haemoglobinuria with falling output shows free haemoglobin in the urine and the start of renal failure. The collapsing platelets and doubled international normalised ratio show disseminated intravascular coagulation, which is what makes the cannula ooze. The potassium of 5.9 mmol/L is released directly from lysed red cells and is an immediate arrhythmia risk. The creatinine has nearly doubled, confirming acute kidney injury from haemoglobin toxicity and hypotension. And a haemoglobin that fails to rise despite a full unit is the signature of ongoing hemolysis rather than under-transfusion. A saturation of 94% on room air is mildly low but is not itself a marker of hemolysis.",
   o:["Expected urine is straw-coloured with output above 30 mL/hour; red-brown urine with a falling output indicates haemoglobinuria and renal injury.",
    "Expected platelets are 150–400 x 10⁹/L and an international normalised ratio under 1.2; both are grossly deranged, indicating coagulopathy.",
    "Expected potassium is 3.5–5.0 mmol/L; 5.9 is released from lysed red cells.",
    "A near doubling of creatinine indicates acute kidney injury.",
    "Expected is a rise of roughly 1 g/dL per unit; no rise indicates ongoing hemolysis.",
    "Mildly low, but not a marker of hemolysis — the other five are."],
   s:"Hemolysis has three systemic consequences to look for: haemoglobinuric renal failure, disseminated intravascular coagulation, and hyperkalaemia from lysed cells. A haemoglobin that fails to rise after a full unit is the quietest and most telling sign."}},
  {step:"prioritize", t:"single", stem:"Which action by the nurse takes priority?",
   reveal:["history","vitals","labs","orders"],
   opts:["Slow the infusion and give an antipyretic, then reassess in 15 minutes",
    "Stop the transfusion and keep the line open with 0.9% sodium chloride through NEW tubing, without flushing the existing set",
    "Stop the transfusion and flush the existing tubing so the remaining blood reaches the client",
    "Stop the transfusion, discard the bag and tubing, and start a fresh unit from a different donor"],
   ans:1,
   rat:{c:"Stopping the transfusion is the single most important action, and how the line is then managed is what separates a competent response from a harmful one. New tubing with saline keeps the access open for resuscitation without pushing the blood still sitting in the existing set into the client — flushing that set delivers a further bolus of incompatible cells directly into the circulation. The bag and tubing must never be discarded: they are the evidence for the investigation, they allow the laboratory to identify the error, and discarding them also destroys the only way to confirm what was given. And starting another unit before the investigation is complete risks a second incompatible transfusion.",
   o:["Slowing the rate continues to deliver incompatible red cells and delays the definitive response.",
    "Correct — stop the transfusion, then keep the line open with new tubing; never flush the blood-filled set.",
    "Flushing the existing set delivers a further bolus of incompatible cells into the circulation.",
    "Discarding the bag and tubing destroys the evidence, and a second unit before investigation risks another incompatible transfusion."],
   s:"Stop the transfusion first. Then: keep the line open with NEW tubing and saline — never flush the blood-filled set — and never discard the bag, which is the evidence for the investigation."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care? Select all that apply.",
   reveal:["vitals","labs","orders"],
   opts:["Recheck the identity band against the bag labels at the bedside and notify the transfusion laboratory",
    "Send the post-reaction blood samples and a urine specimen for repeat crossmatch, direct antiglobulin test and plasma free haemoglobin",
    "Give rapid saline to maintain urine output above 100 mL/hour, protecting the renal tubules from free haemoglobin",
    "Monitor continuously for hyperkalaemia, acute kidney injury and coagulopathy",
    "Give the remaining unit slowly once his temperature settles, since he still needs the haemoglobin"],
   ans:[0,1,2,3],
   rat:{c:"Bedside rechecking and immediate notification of the laboratory start the investigation, which in a wrong-blood-in-error event protects every other client who may be affected by the same mix-up. The post-reaction samples confirm hemolysis and identify the antibody involved. Maintaining a high urine output with saline flushes free haemoglobin through the tubules and is the main renal protection available. Continuous monitoring covers the three systemic threats — potassium released from lysed cells, tubular injury and coagulopathy. Giving the remaining unit once his temperature settles is dangerous: a febrile response is not the criterion for safety, and the unit involved must be quarantined until the investigation concludes.",
   o:["Correct — bedside rechecking and immediate laboratory notification start the investigation.",
    "Correct — post-reaction samples confirm hemolysis and identify the antibody.",
    "Correct — a high urine output flushes free haemoglobin through the tubules.",
    "Correct — hyperkalaemia, acute kidney injury and coagulopathy are the three systemic threats.",
    "A settled temperature is not a safety criterion; the unit must be quarantined until the investigation concludes."],
   s:"After stopping the transfusion: recheck identity and notify the laboratory, send the post-reaction samples, force a diuresis with saline, and monitor for the three systemic threats. Never restart until the investigation is complete."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","labs","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Stop the transfusion immediately and leave the bag and tubing attached for return",
     "Keep the line open with 0.9% sodium chloride through new tubing and call for help",
     "Recheck the identity band against the bag, notify the transfusion laboratory and send the post-reaction samples",
     "Start rapid saline to maintain urine output and monitor for hyperkalaemia, renal failure and coagulopathy"],
    ans:[0,1,2,3]},
   rat:{c:"Stopping the transfusion is first, because every additional millilitre of incompatible blood increases the hemolysis. Maintaining access with new tubing and calling for help follows within seconds — she needs volume and the situation needs a second clinician. Rechecking the identity band, notifying the laboratory and sending the post-reaction samples come next, and the recheck is not a formality: it is how a wrong-blood-in-error is identified, which protects every other client potentially affected by the same mix-up. Resuscitation and monitoring come last in this ordering but run in parallel from the moment the transfusion stops.",
   o:["Stop the transfusion — every additional millilitre increases the hemolysis.",
    "Keep access open with new tubing and call for help.",
    "Recheck the identity band, notify the laboratory and send the post-reaction samples.",
    "Rapid saline for urine output, and monitor for hyperkalaemia, renal failure and coagulopathy."],
   s:"Transfusion reaction sequence: stop the transfusion → new tubing with saline and call for help → recheck identity, notify the laboratory, send samples → resuscitate and monitor for the three systemic threats."}},
  {step:"evaluate", t:"cloze", stem:"Two hours later his blood pressure is 106/64 mm Hg on saline, his urine is clearing and his output is 120 mL/hour, but his potassium is 6.3 mmol/L and his platelets are 58 x 10⁹/L. Complete each evaluation statement.",
   reveal:["history","vitals","labs","orders"],
   cloze:{lines:[
    {pre:"His potassium has risen to 6.3 mmol/L, so the nurse understands that ", post:".",
     opts:["this is expected and needs no action","it reflects potassium released from lysed red cells and needs urgent treatment with cardiac monitoring, since it is an arrhythmia risk","it indicates renal failure alone and will correct with fluids","it should be rechecked next morning"], ans:1},
    {pre:"His platelets are 58 x 10⁹/L and he is oozing from the cannula, so the nurse recognizes that ", post:".",
     opts:["the oozing is from the cannula being poorly secured","he needs a platelet transfusion only, with no other intervention","disseminated intravascular coagulation is developing, so coagulation monitoring and prescribed replacement products are needed","anticoagulation should be started to treat the clotting problem"], ans:2},
    {pre:"The nurse maintains his urine output above 100 mL/hour because ", post:".",
     opts:["free haemoglobin is directly toxic to the renal tubules, and a high flow reduces the risk of acute kidney injury","it prevents further hemolysis from occurring","it corrects the international normalised ratio","it lowers his potassium directly"], ans:0},
    {pre:"Because the bag and tubing were preserved and returned, the nurse recognizes that ", post:".",
     opts:["the laboratory can identify whether this was wrong blood in error, which protects other clients who may be affected by the same mix-up","the bag can be reused for another client after testing","the incident need not be reported as serious","the investigation can be closed without a report"], ans:0}]},
   rat:{c:"The potassium of 6.3 mmol/L comes from lysed red cells and needs urgent treatment with cardiac monitoring, because hyperkalaemia at that level is an arrhythmia risk independent of renal function. The falling platelets with oozing indicate disseminated intravascular coagulation, which needs coagulation monitoring and prescribed replacement — and the oozing is a systemic coagulopathy, not a loose cannula. A high urine output matters because free haemoglobin is directly toxic to the renal tubules, so a brisk flow is the main renal protection available; it does not stop hemolysis or correct the coagulopathy. And preserving the bag allows the laboratory to establish whether this was wrong blood in error, which is the finding that protects every other client potentially exposed to the same mix-up.",
   o:["A potassium of 6.3 mmol/L is never an expected finding.",
    "Correct — potassium from lysed red cells needs urgent treatment with cardiac monitoring as an arrhythmia risk.",
    "Hyperkalaemia at this level is dangerous regardless of renal function.",
    "Deferring the recheck leaves a lethal arrhythmia risk untreated.",
    "The oozing is systemic coagulopathy, not a poorly secured cannula.",
    "Platelets alone do not treat the coagulopathy driving it.",
    "Correct — falling platelets with oozing indicate disseminated intravascular coagulation needing monitoring and replacement products.",
    "Anticoagulation in an actively bleeding, coagulopathic client is dangerous.",
    "Correct — free haemoglobin is directly toxic to the tubules, and a high flow reduces the risk of acute kidney injury.",
    "A diuresis does not stop hemolysis; only stopping the transfusion does.",
    "Urine output does not correct the international normalised ratio.",
    "A diuresis lowers potassium only marginally; it is not the treatment for 6.3 mmol/L.",
    "Correct — the preserved bag lets the laboratory identify wrong blood in error, protecting others exposed to the same mix-up.",
    "Blood products are never reused for another client after a reaction.",
    "A hemolytic reaction is always a serious incident.",
    "The investigation requires a formal report and root cause analysis."],
   s:"Three complications of a hemolytic reaction to watch: hyperkalaemia from lysed cells, disseminated intravascular coagulation, and haemoglobinuric renal failure. Force a diuresis for the kidneys, and preserve the bag — it may protect other clients from the same error."}}]})
;
