/* RN Ready — unfolding clinical-judgment case studies (NCJMM: 6 items per case).
   Information UNFOLDS: each item lists which exhibits are visible ("reveal").
   Later evidence is never shown with earlier items.                          */
window.NC = window.NC || {};
NC.CASES = [

{id:"CASE-RESP-01", title:"The Deteriorating Patient — Mr. Okafor, 68",
 setting:"Medical-surgical unit", sys:"RESP", cn:"PAA", d:2, b:0.6,
 summary:"68-year-old man admitted with community-acquired pneumonia; on day 2 he is deteriorating.",
 exhibits:{
  history:{name:"History & Physical", type:"text", body:"68-year-old man admitted yesterday with community-acquired pneumonia. History: COPD (40 pack-year smoker), hypertension. Home medications: lisinopril, ipratropium/albuterol inhalers. Lives alone; daughter visiting daily. Admission weight 71 kg."},
  vitals:{name:"Vital Signs (now)", type:"kv", rows:[["Temperature","38.9 °C (102.0 °F)"],["Heart rate","118/min"],["Respiratory rate","30/min"],["Blood pressure","104/62 mm Hg"],["SpO2 (room air)","87%"],["Pain","3/10 chest soreness with coughing"]]},
  labs:{name:"Laboratory Results", type:"kv", rows:[["WBC","17,800/mm³"],["Lactate","4.2 mmol/L"],["BUN","18 mg/dL"],["Creatinine","1.4 mg/mL (baseline 1.0)"],["pH","7.31"],["PaCO2","52 mm Hg"],["PaO2","58 mm Hg"]]},
  mar:{name:"Medication Record", type:"kv", rows:[["Levofloxacin","500 mg IV every 24 h (day 2)"],["Albuterol nebulizer","2.5 mg q4h PRN dyspnea"],["Metoprolol","25 mg PO BID"],["Acetaminophen","650 mg PO q6h PRN T ≥ 38.3 °C"]]},
  notes:{name:"Nurse's Notes", type:"text", body:"1200: Restless, sitting forward, using accessory muscles, speaking in short phrases. Capillary refill 3 s. Daughter states: “He was answering normally yesterday; today he keeps dozing off.” 1400: Repeat lactate pending."}},
 items:[
  {step:"recognize", t:"emr", stem:"Review the client's findings. Select the 4 findings that require immediate follow-up.",
   reveal:["history","vitals","labs"],
   groups:[{h:"Findings", opts:["Respiratory rate 30/min","SpO2 87% on room air","Lactate 4.2 mmol/L","Blood pressure 104/62 mm Hg","Pain 3/10 with coughing","Lives alone"], ans:[0,1,2,3]}],
   rat:{c:"Tachypnea, hypoxemia, elevated lactate (hypoperfusion), and relative hypotension are the cues signaling respiratory deterioration with possible early sepsis. Pain with coughing and social history are not priority cues.",
   o:["RR 30 → work of breathing rising: follow up.","SpO2 87% → hypoxemia: follow up.","Lactate 4.2 → tissue hypoperfusion: follow up.","BP 104/62 with refill 3 s → perfusion falling: follow up.","Expected soreness with cough — distractor.","Context, not a clinical cue."],
   s:"Scan for the deadly trio: airway/breathing numbers, perfusion markers (BP, lactate, refill), and mental-status change."}},
  {step:"analyze", t:"hotspot", stem:"Tap to highlight each abnormal (out of expected reference) finding in the table below.",
   reveal:["vitals","labs"],
   hotspot:{mode:"rows", rows:["Temperature 38.9 °C","Respiratory rate 30/min","SpO2 87%","Heart rate 118/min","Serum sodium 137 mEq/L","Hematocrit 42%"], ans:[0,1,2,3]},
   rat:{c:"Fever, tachypnea, hypoxemia, and tachycardia are all outside expected ranges. Sodium 137 and Hct 42% are normal — classic NGN “normal value” distractors.",
   o:[">37.5 °C = febrile.","Expected RR 12–20.","Expected SpO2 ≥95% (and this client is COPD — 88–92 target, still low).","Expected HR 60–100.","Normal (135–145).","Normal adult range."],
   s:"NGN highlight items usually plant ~2 normals. Know reference ranges so you can strike them instantly."}},
  {step:"prioritize", t:"single", stem:"After analyzing the cues, which client problem is the priority?",
   reveal:["history","vitals","labs","notes"],
   opts:["Impaired gas exchange","Acute pain","Risk for deficient knowledge","Anxiety"],
   ans:0,
   rat:{c:"Hypoxemia (87%), rising RR, falling PaO2, and CO2 retention with new lethargy make impaired gas exchange the life-threatening priority (ABCs) — pain, knowledge, and anxiety are lower on Maslow/hierarchy.",
   o:["Correct — oxygenation is the immediate threat to life.","3/10 pain does not outrank gas exchange.","Important for discharge planning, not now.","Restlessness here is more likely hypoxia than anxiety."],
   s:"Priority = ABC + most life-threatening. In unfolding cases, carry your data forward: the numbers you analyzed ARE the justification."}},
  {step:"generate", t:"multi", stem:"Which interventions should the nurse include in the plan right now? Select all that apply.",
   reveal:["history","vitals","labs","notes","mar"],
   opts:["Apply prescribed titrated oxygen","Notify the provider / rapid response team of the deterioration","Place the client in a high-Fowler position","Encourage 3 L/day of oral fluids immediately","Administer a PRN anxiolytic for restlessness"],
   ans:[0,1,2],
   rat:{c:"Oxygen, escalation, and upright positioning directly address impaired gas exchange. Forcing oral fluids in a tiring client risks aspiration; sedating a possibly hypercapnic, lethargic client risks respiratory depression.",
   o:["Correct — oxygenation first (keep COPD target 88–92%).","Correct — sepsis-screen + escalation is mandatory for this trend.","Correct — upright position reduces work of breathing.","Aspiration risk in a lethargic, tiring client — not now (IV fluids per orders are different).","Sedation can worsen hypercapnia and mask deterioration — contraindicated."],
   s:"Every option must be judged against the priority problem (gas exchange). “Calm the restless client” reflexes are traps when restlessness = hypoxia."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","labs","notes","mar"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Apply oxygen and position upright","Notify the rapid response team / provider","Increase monitoring: continuous SpO2, hourly vitals, repeat lactate","Prepare for possible transfer to intensive care"],
    ans:[0,1,2,3]},
   rat:{c:"Treat the ABC threat (oxygen + position) before escalating; escalation precedes logistics of transfer; increased monitoring bridges the gap while awaiting response.",
   o:["Oxygen/position is the immediate life-support action.","Rapid response mobilizes decisive help.","Closer surveillance detects further deterioration.","Transfer preparation follows clinical stabilization and escalation."],
   s:"Ordering items: ask “what keeps this patient alive in the next 5 minutes?” first, then communication, then monitoring, then logistics."}},
  {step:"evaluate", t:"cloze", stem:"One hour later: SpO2 is 93% on oxygen 4 L/min, RR 24, BP 112/68, and the client is alert. Complete the evaluation statements.",
   reveal:["vitals","labs","notes"],
   cloze:{lines:[
    {pre:"The client's oxygen saturation has", post:"in response to intervention.", opts:["improved","declined"], ans:0},
    {pre:"The client's respiratory rate has", post:"from 30 to 24/min.", opts:["decreased","increased"], ans:0},
    {pre:"The nurse's next step is to", post:"and continue to monitor the response.", opts:["maintain current therapy","stop the oxygen","increase fluids by mouth"], ans:0}]},
   rat:{c:"SpO2 87→93% and RR 30→24 with improved alertness indicate the interventions are working: maintain therapy (do not stop oxygen in a hypoxemic COPD client) and keep monitoring closely.",
   o:["87%→93% = improved.","30→24 = decreased.","Improving but still fragile: maintain and monitor — stopping O2 would risk relapse; oral fluids remain an aspiration consideration."],
   s:"Evaluate against the target you set when you acted. Weaning oxygen happens gradually and only against stable saturation."}}]},

{id:"CASE-CV-01", title:"The Yellow Halos — Mrs. Adeyemi, 74",
 setting:"Telemetry unit", sys:"CV", cn:"PHA", d:2, b:0.5,
 summary:"74-year-old woman with heart failure on digoxin and furosemide develops nausea, anorexia, and visual changes.",
 exhibits:{
  history:{name:"History & Physical", type:"text", body:"74-year-old woman with heart failure (EF 35%) and atrial fibrillation, admitted 2 days ago for volume overload. Also has chronic kidney disease stage 3. Lives with her daughter. Reports today: “I feel sick to my stomach, I can't eat, and I see yellow rings around the streetlights.”"},
  vitals:{name:"Vital Signs (0800)", type:"kv", rows:[["Heart rate","56/min, irregular"],["Blood pressure","108/64 mm Hg"],["Respiratory rate","24/min"],["SpO2 (2 L nasal cannula)","92%"],["Weight","+1.8 kg since admission"]]},
  labs:{name:"Laboratory Results (0600)", type:"kv", rows:[["Potassium","3.0 mEq/L"],["Serum digoxin level","2.6 ng/mL"],["BNP","890 pg/mL"],["Creatinine","1.6 mg/dL (baseline 1.2)"]]},
  mar:{name:"Medication Record", type:"kv", rows:[["Digoxin","0.25 mg PO daily — next dose 0900"],["Furosemide","40 mg IV BID"],["Metoprolol succinate","25 mg PO daily"],["Acetaminophen","650 mg PO q6h PRN"]]},
  notes:{name:"Nurse's Notes", type:"text", body:"0700: Client reports nausea and no appetite since last evening. States lights have “yellow rings around them.” Alert and oriented. Lungs: crackles in lower lobes bilaterally. +2 pitting edema to mid-calf. Daughter asks: “Is she just tired, or is something wrong with her medicines?”"}},
 items:[
  {step:"recognize", t:"single", stem:"Which cluster of findings from 0600–0800 requires immediate follow-up?",
   reveal:["history","vitals","labs"],
   opts:["Nausea, anorexia, visual halos, and a heart rate of 56/min","Weight gain of 1.8 kg with +2 pitting edema","Blood pressure 108/64 mm Hg","Crackles in the lower lobes"],
   ans:0,
   rat:{c:"GI symptoms + visual changes + bradycardia in a client on digoxin (level 2.6, above the 0.5–2.0 ng/mL reference) is the classic toxicity cluster — the most immediately dangerous finding pattern because it threatens lethal dysrhythmias.",
   o:["Correct — this is the digoxin toxicity syndrome; it can precipitate dangerous dysrhythmias.","Also important (volume overload) but subacute compared with toxicity.","Low-normal BP — acceptable for this client.","Chronic HF finding — expected on admission, monitor."],
   s:"Group cues into syndromes: GI + eyes + slow pulse on digoxin = toxicity, full stop. That cluster beats chronic findings every time."}},
  {step:"analyze", t:"cloze", stem:"Interpret the 0600 laboratory values using the drop-down menus.",
   reveal:["labs","history"],
   cloze:{lines:[
    {pre:"The serum potassium of 3.0 mEq/L is", post:"the expected reference range.", opts:["below","within","above"], ans:0},
    {pre:"The serum digoxin level of 2.6 ng/mL is", post:"the expected reference range (0.5–2.0 ng/mL).", opts:["below","within","above"], ans:2},
    {pre:"This potassium imbalance", post:"the risk of digoxin-induced dysrhythmias.", opts:["increases","decreases","does not affect"], ans:0}]},
   rat:{c:"K+ 3.0 is below 3.5; digoxin 2.6 is above 2.0. Hypokalemia potentiates digoxin toxicity and dysrhythmias — the two findings multiply each other's danger (worsened by furosemide-induced potassium losses and rising creatinine).",
   o:["3.0 < 3.5 = below.","2.6 > 2.0 = above.","Hypokalemia is the classic amplifier of digoxin toxicity."],
   s:"Never read a drug level without its partner labs: digoxin ↔ potassium; lithium ↔ sodium; warfarin ↔ platelets/INR; heparin ↔ aPTT."}},
  {step:"prioritize", t:"single", stem:"Which hypothesis is the priority for this client right now?",
   reveal:["vitals","labs","notes"],
   opts:["Digoxin toxicity with risk of dysrhythmia","Fluid volume overload","Activity intolerance","Caregiver strain"],
   ans:0,
   rat:{c:"Toxicity with bradycardia and hypokalemia carries immediate risk of life-threatening dysrhythmias — it outranks the subacute volume overload and the psychosocial/functional hypotheses.",
   o:["Correct — immediate, life-threatening, and treatable.","Real (weight +1.8 kg, crackles) but not the most urgent.","A concern for later planning.","A psychosocial need — lowest priority here."],
   s:"Two competing physiologic hypotheses? Choose the one that can kill fastest and is changing now."}},
  {step:"generate", t:"multi", stem:"Which actions should the nurse anticipate including in the plan? Select all that apply.",
   reveal:["labs","mar","notes"],
   opts:["Hold the 0900 digoxin dose and notify the provider","Place the client on continuous cardiac monitoring","Administer prescribed potassium replacement","Administer the next digoxin dose with food to reduce nausea","Check an ECG for dysrhythmias"],
   ans:[0,1,2,4],
   rat:{c:"Hold-and-notify, telemetry, potassium replacement (once output/renal function confirm safety), and a 12-lead ECG address the dysrhythmia threat. Giving the next dose of a toxic drug is the one action that must be avoided.",
   o:["Correct — standard hold parameter breached (HR <60 + toxic level + symptoms).","Correct — detect dysrhythmias early.","Correct — correcting hypokalemia reduces dysrhythmia risk (verify renal function/output first).","Never continue the suspected toxic drug.","Correct — bradycardic/ectopic patterns need documenting now."],
   s:"When the hypothesis is toxicity: STOP the drug, MONITOR the heart, FIX the amplifier (K+), ESCALATE. Continuing the drug is always the trap option."}},
  {step:"act", t:"matrix", stem:"For each nursing action, indicate whether the nurse should DO it now or AVOID it.",
   reveal:["mar","labs","vitals"],
   matrix:{cols:["Do now","Avoid"], mode:"radio",
    rows:["Hold the 0900 digoxin dose and notify the provider","Obtain a 12-lead ECG and apply telemetry","Administer prescribed potassium replacement","Administer the scheduled digoxin dose as ordered","Reassess apical pulse before any future digoxin doses"],
    ans:[0,0,0,1,0]},
   rat:{c:"Everything that stops or monitors the toxic exposure is a “Do”; administering the next dose of the toxic drug is the “Avoid.”",
   o:["Do — hold parameters are met (HR 56, symptoms, level 2.6).","Do — dysrhythmia surveillance.","Do — replace potassium per order (confirm renal/output).","Avoid — the drug is the problem.","Do — apical pulse (full 60 s) before every digoxin dose."],
   s:"Matrix items reward decisive classification. Toxicity framework: stop source → protect target organ → correct amplifier → escalate."}},
  {step:"evaluate", t:"emr", stem:"The next morning: HR 66/min regular, K+ 3.6 mEq/L, digoxin held for 2 doses, lungs clearer, weight −0.9 kg. Select the 3 findings that indicate improvement.",
   reveal:["vitals","labs"],
   groups:[{h:"Findings", opts:["Heart rate 66/min and regular","Potassium 3.6 mEq/L","Crackles diminished, weight −0.9 kg","Client still reports mild nausea at breakfast","Serum digoxin level result pending"], ans:[0,1,2]}],
   rat:{c:"Rate normalized to 66 regular, potassium corrected to 3.6, and volume responding (clearer lungs, diuresis) = improvement. Persistent nausea means incomplete resolution, and a pending level provides no evaluative information.",
   o:["Rate recovered from 56 irregular → improving.","K+ 3.0→3.6 → correcting.","Volume down, lungs clearer → improving.","Ongoing symptom — not yet improved (may lag as level falls).","Pending data cannot evaluate anything."],
   s:"Evaluation needs before/after pairs: pick findings you can compare against the baseline established earlier in the case."}}]}
];
