/* RN Ready — case study v2 · severe pre-eclampsia and magnesium toxicity.
   Eighteenth unfolding case: a 27-year-old at 32+4 weeks presents with severe
   pre-eclampsia and features of HELLP. Judgment unfolds from recognizing
   impending eclampsia, through the three monitoring parameters that detect
   magnesium toxicity, to renal dosing, the antidote and postnatal follow-up.

   Wave 65 — case studies only, RN only, maximum difficulty.  */
NC.CASES = NC.CASES || [];
NC.CASES.push(

{id:"CASE-PREECL-01", title:"Thirty-Two Weeks — Mrs. Eze, 27",
 setting:"Maternal assessment unit / delivery suite", sys:"CV", cn:"PHA", d:3, b:0.55,
 summary:"27-year-old primigravida at 32+4 weeks with a blood pressure of 172/112 mm Hg, headache, visual disturbance, epigastric pain, four beats of clonus, platelets 88 and a raised alanine transaminase. Judgment unfolds from recognizing impending eclampsia, through the three parameters that detect magnesium toxicity, to renal dosing, the antidote and postnatal follow-up.",
 exhibits:{
  history:{name:"History", type:"text", body:"27-year-old woman, first pregnancy, 32+4 weeks by dating scan. Attends the maternal assessment unit with a two-day headache unrelieved by paracetamol, blurred vision with flashing lights, and pain under her right ribs. No vomiting, no bleeding, no reduced fetal movements. Booking blood pressure 118/74 mm Hg. Body mass index 33. No previous medical history, no regular medicines, no known allergies. Family history: her mother had pre-eclampsia."},
  vitals:{name:"Observations", type:"kv", rows:[["Blood pressure","172/112 mm Hg (repeat 168/110 after 15 minutes rest)"],["Heart rate","96/min"],["Respiratory rate","18/min"],["SpO2 (room air)","98%"],["Temperature","36.7 °C (98.1 °F)"],["Urine output","28 mL in the last hour"],["Reflexes","Patellar reflexes brisk with four beats of clonus"]]},
  labs:{name:"Laboratory Results", type:"kv", rows:[["Platelets","88 x 10⁹/L"],["Alanine transaminase","142 U/L"],["Creatinine","104 µmol/L (1.18 mg/dL) — was 62 µmol/L at 28 weeks"],["Urate","0.42 mmol/L"],["Protein:creatinine ratio","180 mg/mmol"],["Hemoglobin","11.4 g/dL"],["Lactate dehydrogenase","raised, with schistocytes on the film"]]},
  fetal:{name:"Fetal Assessment", type:"text", body:"Symphysis-fundal height 30 cm. Cardiotocography: baseline 145/min, reduced variability, no accelerations, two late decelerations in 30 minutes — a pathological trace. Ultrasound: estimated fetal weight on the 4th centile, umbilical artery Doppler with absent end-diastolic flow. Antenatal corticosteroid course started for fetal lung maturity."},
  orders:{name:"Provider Orders", type:"text", body:"1. Magnesium sulfate 4 g IV loading dose over 20 minutes, then 1 g/hour maintenance for seizure prophylaxis. 2. Monitor hourly: respiratory rate must stay at or above 16/min, patellar reflexes must be present, urine output must stay at or above 30 mL/hour. 3. Calcium gluconate 10% 10 mL IV over 10 minutes kept drawn up at the bedside as the antidote. 4. Reduce the magnesium rate if the creatinine is rising — it is renally excreted. 5. Labetalol IV titrated, or nifedipine; do NOT use an angiotensin-converting enzyme inhibitor or an angiotensin receptor blocker. 6. Continuous fetal monitoring. 7. Senior obstetric, anaesthetic and neonatal team review; delivery is the definitive treatment. 8. Strict fluid balance — risk of pulmonary edema. 9. Nil by mouth; group and save. 10. Continue magnesium for 24 hours after delivery."}},
 items:[
  {step:"recognize", t:"single", stem:"Review the observations, laboratory results and fetal assessment. Which interpretation by the nurse is most accurate?",
   reveal:["history","vitals","labs","fetal"],
   opts:["This is gestational hypertension requiring blood pressure control and routine midwifery care",
    "The epigastric pain and raised alanine transaminase indicate a gallbladder problem needing an ultrasound first",
    "Severe pre-eclampsia with features of HELLP syndrome and a pathological fetal trace, requiring magnesium sulfate, blood pressure control and urgent delivery planning",
    "Her blood pressure has settled after rest and the fetal trace will settle too, so this can be managed with antenatal day assessment"],
   ans:2,
   rat:{c:"A blood pressure above 160/110 on a repeat reading, new headache unrelieved by analgesia, visual disturbance, epigastric pain and four beats of clonus are the severe features, and the platelets of 88, alanine transaminase of 142, raised lactate dehydrogenase with schistocytes make this HELLP syndrome — hemolysis, elevated liver enzymes, low platelets. The creatinine has risen from 62 to 104 µmol/L, and the pathological cardiotocography with absent end-diastolic flow means the fetus is not coping. Headache with visual disturbance and clonus signals central nervous system irritability and impending eclampsia. Gallbladder disease does not cause clonus, thrombocytopenia or a pathological fetal trace, and a second blood pressure of 168/110 after rest has not settled at all.",
   o:["Gestational hypertension has no proteinuria and none of the severe features or laboratory derangement seen here.",
    "Gallbladder disease does not cause clonus, a platelet count of 88 or a pathological fetal trace.",
    "Correct — severe pre-eclampsia with HELLP features, a rising creatinine and a pathological fetal trace: magnesium, blood pressure control and urgent delivery.",
    "168/110 after rest is still severe; the severe features and the fetal trace make day assessment unsafe."],
   s:"HELLP = Hemolysis, Elevated Liver enzymes, Low Platelets. Epigastric or right upper quadrant pain in pregnancy with raised transaminases is pre-eclampsia until proven otherwise — and clonus with headache means seizure risk."}},
  {step:"analyze", t:"hotspot", stem:"Highlight every finding below that falls outside the expected range for this pregnancy.",
   reveal:["vitals","labs","fetal"],
   hotspot:{mode:"rows", rows:[
    "Blood pressure 168/110 mm Hg after 15 minutes of rest",
    "Platelets 88 x 10⁹/L",
    "Patellar reflexes brisk with four beats of clonus",
    "Creatinine 104 µmol/L, having been 62 µmol/L at 28 weeks",
    "Urine output 28 mL in the last hour",
    "Core temperature 36.7 °C"
   ], ans:[0,1,2,3,4]},
   rat:{c:"All five of the first group are abnormal and each one matters: severe hypertension on a rested repeat, thrombocytopenia, clonus indicating central nervous system irritability, a creatinine that has nearly doubled, and a urine output of 28 mL/hour which is both a marker of renal involvement and — critically — the parameter that governs magnesium dosing, because magnesium is excreted renally and oliguria causes it to accumulate. A temperature of 36.7 °C is normal and is the single planted value. The urine output is the one worth thinking hardest about, since it is simultaneously a sign of disease and a determinant of drug safety.",
   o:["Expected blood pressure in pregnancy is under 140/90; 168/110 after rest is severe hypertension.",
    "Expected platelets are 150–400 x 10⁹/L; 88 is thrombocytopenia and part of HELLP.",
    "Three or more beats of clonus with brisk reflexes indicates central nervous system irritability and seizure risk.",
    "A creatinine rise from 62 to 104 µmol/L indicates acute kidney injury from pre-eclampsia.",
    "Expected output is at least 30 mL/hour; 28 mL/hour is oliguria and means magnesium will accumulate.",
    "Normal core temperature is about 36.1–37.2 °C — within range."],
   s:"In pre-eclampsia on magnesium, urine output does double duty: it shows renal involvement AND it determines whether the magnesium dose is safe. Magnesium is renally excreted, so oliguria means toxicity."}},
  {step:"prioritize", t:"single", stem:"She has a headache, visual disturbance and four beats of clonus. Which action by the nurse takes priority?",
   reveal:["history","vitals","labs","orders"],
   opts:["Give oral paracetamol and codeine for the headache and recheck her observations in an hour",
    "Start the magnesium sulfate loading dose for seizure prophylaxis and escalate for urgent obstetric and anaesthetic review",
    "Arrange a computed tomography scan of the head to exclude another cause of the headache",
    "Give an angiotensin-converting enzyme inhibitor to bring the blood pressure down quickly"],
   ans:1,
   rat:{c:"Headache with visual disturbance and clonus means she is at imminent risk of an eclamptic seizure, and magnesium sulfate is the agent that prevents it — it halves the risk of eclampsia and is not an antihypertensive, which is the distinction that catches people out. Escalation must happen in parallel because delivery is the definitive treatment and the fetus is not coping. Analgesia and an hourly recheck delay the intervention that prevents a seizure. Imaging is not the first step when the whole picture is classic pre-eclampsia. And angiotensin-converting enzyme inhibitors and angiotensin receptor blockers are contraindicated throughout pregnancy because they cause fetal renal failure and are associated with fetal death.",
   o:["Analgesia does not prevent a seizure and an hourly recheck delays the intervention she needs now.",
    "Correct — magnesium sulfate prevents eclamptic seizures, and escalation for delivery must happen in parallel.",
    "The picture is classic severe pre-eclampsia; imaging delays definitive treatment.",
    "Angiotensin-converting enzyme inhibitors and angiotensin receptor blockers are contraindicated in pregnancy — they cause fetal renal failure."],
   s:"Magnesium sulfate is seizure prophylaxis, not blood pressure control. Headache, visual disturbance and clonus mean give it now. And never use an ACE inhibitor or ARB in pregnancy."}},
  {step:"generate", t:"multi", stem:"Which interventions belong in the plan of care while she is on magnesium sulfate? Select all that apply.",
   reveal:["vitals","labs","orders"],
   opts:["Hourly checks of respiratory rate, patellar reflexes and urine output, since these three detect magnesium toxicity",
    "Calcium gluconate drawn up and kept at the bedside as the antidote",
    "A reduced magnesium infusion rate given her rising creatinine, since magnesium is excreted renally",
    "A strict fluid balance, since pre-eclampsia carries a real risk of pulmonary edema",
    "Stopping the magnesium once she delivers, since the seizure risk ends with the placenta"],
   ans:[0,1,2,3],
   rat:{c:"Respiratory rate at or above 16/min, present patellar reflexes and urine output at or above 30 mL/hour are the three bedside parameters that detect toxicity, and the order in which they go is instructive: reflexes are lost first, then respiratory rate falls, then arrest follows. Calcium gluconate is the antidote and must already be at the bedside rather than in the drug cupboard. Her creatinine has nearly doubled, so the infusion rate must be reduced — magnesium is cleared by the kidneys and accumulates in renal impairment. Fluid restriction matters because pulmonary edema is a leading cause of maternal death in pre-eclampsia. And eclamptic seizures occur after delivery in a substantial proportion of cases, so magnesium continues for 24 hours.",
   o:["Correct — respiratory rate, reflexes and urine output are the three toxicity checks, done hourly.",
    "Correct — calcium gluconate is the antidote and must be at the bedside before it is needed.",
    "Correct — magnesium is renally excreted, so a rising creatinine means the rate must be reduced.",
    "Correct — pulmonary edema is a leading cause of maternal death in pre-eclampsia, so balance is strict.",
    "Seizure risk persists after delivery; magnesium continues for 24 hours postpartum."],
   s:"Magnesium toxicity: reflexes are lost FIRST, then respiratory depression, then arrest. Check rate, reflexes and urine hourly, keep calcium gluconate at the bedside, reduce the dose in renal impairment, and continue for 24 hours after birth."}},
  {step:"act", t:"drag", stem:"Order the nurse's actions from FIRST to LAST.",
   reveal:["vitals","labs","fetal","orders"],
   drag:{targets:["1 — First","2","3","4 — Last"],
    opts:["Escalate for immediate obstetric, anaesthetic and neonatal review, and secure intravenous access with bloods",
     "Start the magnesium sulfate loading dose and titrate the antihypertensive to the target",
     "Set up hourly monitoring of respiratory rate, reflexes and urine output, with calcium gluconate at the bedside",
     "Prepare for delivery with continuous fetal monitoring and the neonatal team present"],
    ans:[0,1,2,3]},
   rat:{c:"Escalation and access come first because this is a multi-team emergency with a pathological fetal trace and delivery may be needed within minutes. Magnesium and blood pressure control follow immediately, since seizure prophylaxis and reducing the risk of intracranial hemorrhage are time-critical. The monitoring and the antidote at the bedside come next — they must be in place before toxicity could develop, not arranged after it appears. Delivery preparation comes last in this sequence but is organized from the moment the escalation is made, because delivery is the definitive treatment and the fetus is showing absent end-diastolic flow.",
   o:["Escalation, access and bloods — a multi-team emergency with a pathological fetal trace.",
    "Magnesium for seizure prophylaxis and antihypertensive titration.",
    "Hourly toxicity monitoring with the antidote at the bedside.",
    "Delivery preparation with continuous fetal monitoring and the neonatal team present."],
   s:"Severe pre-eclampsia sequence: escalate and get access → magnesium and blood pressure control → toxicity monitoring with the antidote ready → deliver. Delivery is the definitive treatment and is planned from the first minute."}},
  {step:"evaluate", t:"cloze", stem:"Six hours into the magnesium infusion, before delivery, her respiratory rate is 12/min, her patellar reflexes are absent and her urine output is 18 mL/hour. Complete each evaluation statement.",
   reveal:["vitals","labs","orders"],
   cloze:{lines:[
    {pre:"Her respiratory rate has fallen to 12/min with absent reflexes, so the nurse's immediate action is to ", post:".",
     opts:["continue the infusion and recheck in an hour, since the parameters fluctuate","stop the magnesium infusion, give the calcium gluconate, support her breathing and escalate immediately","reduce the rate by half and continue hourly monitoring","give an antihypertensive, since the respiratory depression is caused by the blood pressure treatment"], ans:1},
    {pre:"Her creatinine has risen and her urine output is 18 mL/hour, so the nurse recognizes that ", post:".",
     opts:["magnesium is excreted renally, so impaired kidney function caused it to accumulate and the dose must be reduced and levels checked","the magnesium level is unaffected by kidney function","her oliguria is caused by the magnesium and will resolve on its own","no dose change is needed, since the infusion rate is standard"], ans:0},
    {pre:"Because calcium gluconate is given, the nurse understands that it ", post:".",
     opts:["lowers the blood pressure and treats the pre-eclampsia","reverses the pre-eclampsia so that delivery can be delayed","increases renal excretion of magnesium","antagonizes the effects of magnesium at the neuromuscular junction but does not remove it, so the infusion must still be stopped"], ans:3},
    {pre:"After delivery the nurse recognizes that ", post:".",
     opts:["all monitoring can stop because the placenta has been delivered","magnesium and blood pressure monitoring continue for at least 24 hours, since eclampsia and pulmonary edema can occur after delivery","she can be discharged on the first day if her blood pressure is normal at 12 hours","breastfeeding is contraindicated after magnesium sulfate"], ans:1}]},
   rat:{c:"A respiratory rate of 12/min with absent reflexes is established magnesium toxicity, and the response is simultaneous: stop the infusion, give calcium gluconate, support the airway and breathing, and escalate — waiting for the next hourly check is how arrests happen. The cause here is her worsening kidney function, because magnesium is cleared renally, so oliguria caused accumulation and the dose must be reduced with a level checked. Calcium gluconate antagonizes magnesium at the neuromuscular junction and buys the time, but it does not remove magnesium from the body, which is why stopping the infusion is not optional. And the postnatal period carries real risk: a significant proportion of eclamptic seizures and cases of pulmonary edema occur after delivery, so magnesium and blood pressure monitoring continue for at least 24 hours. Breastfeeding is safe on magnesium.",
   o:["Parameters do not fluctuate into toxicity; a rate of 12 with absent reflexes is established toxicity.",
    "Correct — stop the infusion, give calcium gluconate, support breathing and escalate immediately.",
    "Halving the rate leaves a toxic client on a toxic drug.",
    "Antihypertensives do not cause this pattern; magnesium does.",
    "Correct — magnesium is renally excreted, so impaired kidney function causes accumulation and the dose must be reduced.",
    "Kidney function is the main determinant of magnesium clearance.",
    "Oliguria is caused by the pre-eclampsia, not by the magnesium.",
    "A standard rate in a client with acute kidney injury guarantees accumulation.",
    "Calcium gluconate is not an antihypertensive and does not treat the underlying disease.",
    "It does not reverse pre-eclampsia; delivery is the definitive treatment.",
    "It does not increase magnesium excretion — it antagonizes the effect.",
    "Correct — calcium antagonizes magnesium at the neuromuscular junction but does not remove it, so the infusion must still be stopped.",
    "Monitoring does not stop at delivery; the postnatal risk period is real.",
    "Correct — continue magnesium and blood pressure monitoring for at least 24 hours after delivery.",
    "First-day discharge ignores the postnatal seizure and pulmonary edema risk.",
    "Breastfeeding is safe on magnesium sulfate."],
   s:"Magnesium toxicity triad at the bedside: absent reflexes, respiratory rate under 16/min, oliguria. Stop the infusion, give calcium gluconate, support breathing, escalate — and remember calcium antagonizes the effect but does not remove the drug."}}]})
;
