/* Emits vercel-content.cjs — every server-side content file as a string map.
   Vercel's Node builder compiles required modules into the serverless function
   but does NOT copy files that are only read with fs at runtime. Rather than
   relying on includeFiles globs (fragile across builders/versions), the Vercel
   buildCommand runs this first, and the bundler inlines the generated module.
   content.js falls back to it whenever js/ is missing on disk (i.e. inside the
   lambda). Run manually with: node scripts/vercel-content.mjs               */
import fs from "fs"; import path from "path"; import url from "url";
const root = path.dirname(new URL(".", import.meta.url).pathname); // repo root (script lives in scripts/)
const { contentFiles } = await import(path.join(root, "content.js") + "");

const files = ["js/taxonomy.js", ...contentFiles(root).all, "js/engine.js"];
const map = {};
for (const f of files) map[f] = fs.readFileSync(path.join(root, f), "utf8");

const out = path.join(root, "vercel-content.cjs");
fs.writeFileSync(out,
  "/* AUTO-GENERATED by scripts/vercel-content.mjs — do not edit.\n" +
  "   Embedded content bundle for serverless deploys (see content.js). */\n" +
  "module.exports = " + JSON.stringify(map, null, 1) + ";\n");
console.log(`generated ${path.basename(out)}: ${files.length} files, ` +
  `${(fs.statSync(out).size / 1024).toFixed(0)} KB embedded`);
