/* RN Ready — DEMO / PRACTICE question set (case-study portion).
   Unfolding case studies, the bow-tie item, and the stand-alone trend item
   from the user-supplied practice document, transcribed into the app's case
   format (exhibits + reveal schedule, one item per clinical-judgment step).
   The source document provides NO answer key — all `ans`/`rat` fields are
   authored practice content (see demo/bank.demo.js header).

   Served only when DEMO_BANK is truthy; ids use the CASE-DEMO- prefix so the
   switch can filter them reliably. Screen numbering follows the document.  */
module.exports = [

/* ── Document items 7–12 · Case Study (6 screens) ─────────────────── */
{id:"CASE-DEMO-01", title:"Abdominal Pain in the ED — Male, 41", setting:"Emergency department → medical-surgical unit", sys:"GI", cn:"PAA", d:2, b:0.5,
 summary:"41-year-old man with 2 weeks of fever, vomiting, constipation, and escalating abdominal pain after minor abdominal trauma.",
 exhibits:{
  notes:{name:"Nurses’ Notes 1100", type:"text", body:"1100: Client reports nausea, loss of appetite, vomiting, fever, and constipation for the past 2 weeks and abdominal pain rated 7/10 on the Numerical Rating Scale for 1 week. Client states, “The abdominal pain started after my 7-year-old child accidentally kicked me in the stomach.” Client plays soccer with the child once a week. Vital signs: T 103.4° F (39.7° C), P 92, RR 22, BP 130/86, pulse oximetry 98% on room air. No significant past medical or surgical history. Body mass index (BMI) 32. Drinks alcohol only during social occasions, usually 3 beverages. Smokes cigarettes during social occasions."},
  notes2:{name:"Nurses’ Notes 1130", type:"text", body:"1130: Notified primary health care provider about client status. Awaiting orders."},
  notes3:{name:"Nurses’ Notes 1230–1415", type:"text", body:"1230: Client transported to radiology for abdominal computed tomography (CT) scan.\n1245: 20-gauge peripheral venous access device (VAD) inserted into the left hand. Site patent without signs of infiltration. 0.9% sodium chloride (normal saline) infusing at 75 mL/hr.\n1400: Client reports sudden relief of abdominal pain. Vital signs: T 102.5° F (39.2° C), P 110, RR 20, BP 125/86.\n1415: Provider notified. Order received for an additional abdominal CT scan. Client transported to radiology."},
  dx:{name:"Diagnostic Results", type:"text", body:"Abdominal CT 1230: acute gangrenous appendix with calcified appendicolith.\nAbdominal CT 1445: free intraperitoneal fluid noted, consistent with a ruptured appendix."},
  postop:{name:"Nurses’ Notes 1800–2230", type:"text", body:"1800: Client transported to the operating room for an open appendectomy.\n2030: Client transported back to the medical-surgical unit.\n2230: Client performing coughing and deep-breathing exercises every hour while awake with the incentive spirometer. Performing postoperative leg exercises every hour while awake. Nasogastric (NG) tube removed. Drinking clear liquids. Abdomen boardlike with diminished bowel sounds in all quadrants. Rebound tenderness present."}},
 items:[
  {step:"recognize", t:"hotspot", stem:"Click to highlight the findings below that would require follow-up.",
   reveal:["notes"],
   hotspot:{mode:"rows", rows:["Temperature 103.4° F (39.7° C)","Pulse 92/min","Respiratory rate 22/min","Blood pressure 130/86 mm Hg","Pulse oximetry 98% on room air","Nausea, vomiting, and loss of appetite for 2 weeks","Constipation for 2 weeks","Abdominal pain rated 7/10 for 1 week","Plays soccer with 7-year-old child once a week","Body mass index (BMI) 32"], ans:[0,5,6,7]},
   rat:{c:"Fever of 103.4° F, the 2-week GI symptom cluster (nausea, vomiting, anorexia), constipation, and 7/10 abdominal pain are the abnormal findings requiring follow-up. The other vital signs are acceptable, and social history/BMI are context, not acute cues.",
   o:["Fever this high signals infection/inflammation: follow up.","Normal adult pulse: distractor.","Mildly elevated but not the acute cue set: distractor.","Acceptable blood pressure: distractor.","Normal oxygenation: distractor.","Two weeks of GI symptoms is abnormal: follow up.","Persistent constipation is abnormal: follow up.","Severe pain (7/10) for a week: follow up.","Recreational context, not a clinical cue.","Chronic risk factor, not an acute finding."],
   s:"Highlight tasks flag CHANGE and abnormal values; acceptable vitals and social context are the planted distractors."}},
  {step:"analyze", t:"matrix", stem:"For each assessment finding below, click to specify if the finding is consistent with the disease process of bowel obstruction, appendicitis, or ruptured spleen. Each finding may support more than 1 disease process.",
   reveal:["notes"],
   matrix:{cols:["Bowel Obstruction","Appendicitis","Ruptured Spleen"], mode:"check",
    rows:["appetite (loss of appetite)","pain level (7/10)","bowel pattern (constipation)","gastrointestinal symptoms (nausea and vomiting)"],
    ans:[[0,1],[0,1,2],[0,1],[0,1]]},
   rat:{c:"Anorexia, severe pain, constipation, and nausea/vomiting are shared by bowel obstruction and appendicitis. Severe abdominal pain (especially after trauma, with guarding) is the one finding that also supports a ruptured spleen.",
   o:["Loss of appetite: obstruction and appendicitis (not typical for splenic rupture).","Severe 7/10 pain: consistent with all three processes.","Constipation: obstructive and appendiceal patterns (splenic rupture does not cause constipation).","Nausea/vomiting: obstructive and appendiceal patterns."],
   s:"Match each finding to EVERY process it supports — severe pain is the broadest row; GI-specific findings stay with the GI diagnoses."}},
  {step:"prioritize", t:"multi", stem:"Select the 3 complications the client is at risk for developing.",
   reveal:["notes"],
   opts:["anemia","peritonitis","septic shock","hypovolemia","dysrhythmias","cardiac arrest"],
   ans:[1,2,3],
   rat:{c:"A likely ruptured appendix spills contaminated contents into the peritoneum: peritonitis, septic shock, and hypovolemia (fever, vomiting, third-spacing) are the three complications to anticipate.",
   o:["Anemia is not a expected complication of this presentation.","Correct — peritonitis follows rupture.","Correct — septic shock can follow peritonitis.","Correct — fluid losses and third-spacing cause hypovolemia.","Dysrhythmias are not an expected complication.","Cardiac arrest is not an anticipated complication at this stage."],
   s:"Think downstream from the pathology: rupture → peritonitis → sepsis/septic shock + fluid losses. Cardiac causes don’t follow."}},
  {step:"generate", t:"matrix", stem:"For each potential intervention, click to specify whether the intervention is indicated or not indicated for the client.",
   reveal:["notes","notes2"],
   matrix:{cols:["Indicated","Not indicated"], mode:"radio",
    rows:["clear liquid diet","soapsuds enema","heating pad to abdomen","abdominal girth measurements","abdominal computed tomography (CT) scan"],
    ans:[1,1,1,0,0]},
   rat:{c:"With suspected appendicitis (and probable rupture) the stomach stays empty (NPO) and the bowel is left alone: no enemas, no heat (risk of rupture/worsened inflammation). Monitoring girth and CT imaging ARE indicated.",
   o:["Clear liquids are NOT indicated — potential surgery means NPO.","Soapsuds enema is NOT indicated — could precipitate perforation.","Heating pad is NOT indicated — heat worsens inflammatory abdominal emergencies.","Abdominal girth measurements ARE indicated — track progression.","Abdominal CT IS indicated — confirm the diagnosis."],
   s:"Suspected appendicitis rules: NPO, no heat, no enemas, diagnostics + monitoring yes."}},
  {step:"act", t:"cloze", stem:"The nurse has reviewed the Nurses’ Notes from 1230, 1245, 1400, and 1415 and the Diagnostic Results from 1230 and 1445. Complete the following sentences by choosing from the lists of options.",
   reveal:["notes","notes2","notes3","dx"],
   cloze:{lines:[
    {pre:"The nurse should insert", post:".", opts:["a rectal tube","a nasogastric (NG) tube","an indwelling urethral catheter"], ans:1},
    {pre:"It would be a priority for the nurse to request a prescription for an", post:".", opts:["analgesic medication","antipyretic medication","anti-infective medication"], ans:2},
    {pre:"The nurse should prepare the client for surgery within", post:".", opts:["6 hours","8 hours","24 hours"], ans:1}]},
   rat:{c:"A ruptured appendix with free fluid means peritonitis: an NG tube decompresses the obstructed/ileus bowel, anti-infective therapy addresses the spreading infection first, and surgery is prepared urgently (within 8 hours) after stabilization.",
   o:["A rectal tube does not decompress upper-GI obstruction/peritonitis.","Correct — NG tube for ileus/decompression with peritonitis.","An indwelling catheter is not the priority device here.","Analgesia is needed but does not treat the infectious emergency.","Antipyretics treat the temperature, not the source.","Correct — anti-infectives (plus source control) address sepsis risk first.","6 hours is sooner than typical stabilization permits; the expected target is urgent surgery within 8 hours.","Correct — urgent (within 8 hours) once resuscitated.","24 hours is too slow for ruptured appendix with peritonitis."],
   s:"Ruptured appendix = peritonitis: NGT + antibiotics + urgent surgery. Treat the lethal process first (infection), comfort second."}},
  {step:"evaluate", t:"multi", stem:"The nurse is caring for the client on the medical-surgical unit and has reviewed the Nurses’ Notes from 1800, 2030, and 2230. Which of the following findings would indicate the client is progressing as expected? Select all that apply.",
   reveal:["postop"],
   opts:["clear liquid diet","boardlike abdomen","rebound tenderness","incentive spirometry use","diminished bowel sounds","performance of leg exercises"],
   ans:[0,3,5],
   rat:{c:"Tolerating oral clear liquids, hourly incentive spirometry, and hourly leg exercises are expected, beneficial postoperative findings. A boardlike abdomen with rebound tenderness and diminished bowel sounds suggests continuing peritonitis/ileus — complications, not progression.",
   o:["Correct — tolerating fluids after NG removal is expected progress.","A boardlike abdomen suggests peritonitis — abnormal.","Rebound tenderness indicates peritoneal irritation — abnormal.","Correct — pulmonary hygiene prevents atelectasis/pneumonia.","Diminished bowel sounds with a rigid abdomen signal ileus/peritonitis — abnormal.","Correct — leg exercises prevent venous thromboembolism."],
   s:"Postop “progressing as expected” = what you TAUGHT them to do (breathing exercises, leg exercises, diet advance). Guarding/boardlike findings are red flags."}}]},

/* ── Document items 32–37 · Case Study (6 screens) ────────────────── */
{id:"CASE-DEMO-02", title:"Baseball Injury, Left Torso — Male, 17", setting:"Emergency department", sys:"INF", cn:"PAA", d:2, b:0.55,
 summary:"17-year-old hit by a mechanically pitched baseball a week ago; now pale and diaphoretic with LUQ tenderness and diminished left breath sounds.",
 exhibits:{
  hnp:{name:"History and Physical", type:"text", body:"Pulmonary: denies shortness of breath; reports discomfort in the lower left side of chest when taking a deep breath.\nGastrointestinal: reports feeling abdominal fullness and is occasionally nauseated.\nMusculoskeletal: injury to the left rib cage after being struck by a mechanically pitched baseball in a batting cage last week; intermittent left shoulder pain 6/10; feels light-headed; significant bruising to the shoulder; history of arthroscopic repair of the left shoulder for a torn rotator cuff last year.\nPsychosocial: has not felt well enough to attend baseball practice since the injury."},
  vitals:{name:"Vital Signs (Day 1, 0900)", type:"kv", rows:[["Temperature","97.8° F (36.6° C)"],["Pulse","116/min"],["Respirations","24/min"],["Blood pressure","90/50 mm Hg"],["Pulse oximetry","98% on room air"]]},
  labs:{name:"Laboratory Results (Day 1, 0900)", type:"kv", rows:[["WBC (ref 5,000–10,000/mm³)","19,000/mm³ (19 × 10⁹/L)"],["Hemoglobin, male (ref 14–18 g/dL)","9 g/dL (90 g/L)"],["Hematocrit, male (ref 42%–52%)","27% (0.27)"]]},
  notes:{name:"Nurses’ Notes (ED)", type:"text", body:"0900: Client appears pale and slightly diaphoretic. Large amount of bruising along the left torso and over the left upper quadrant (LUQ) of the abdomen. Tenderness, guarding, and dullness to percussion on abdominal assessment. Slightly diminished breath sounds in the left lung fields; client has a productive cough. ECG shows normal sinus rhythm.\n1000: Client diagnosed with a splenic laceration and a left-sided hemothorax per the physician.\n1030: Client referred for immediate surgery."},
  progress:{name:"Progress Notes (Day 3)", type:"text", body:"0800: Client is postoperative day 3 after a splenectomy and is able to ambulate in the corridor 3 or 4 times daily with minimal assistance. Clear breath sounds. Left-sided chest tube attached to a closed-chest drainage system; tidaling of the water chamber noted on deep inspiration. Client refuses to use the incentive spirometer, stating it causes left-sided chest pain. Client is using the prescribed patient-controlled analgesia (PCA) device maximally every hour and continues to have intermittent nausea and vomiting. Adequate urine output. Abdominal surgical incision dressing clean, dry, and intact with no erythema, edema, or drainage."}},
 items:[
  {step:"recognize", t:"multi", stem:"Which of the following assessment findings require immediate follow-up? Select all that apply.",
   reveal:["hnp","notes","vitals","labs"],
   opts:["lung sounds","shoulder pain","laboratory results","productive cough","abdominal assessment findings","pulse, respirations, and blood pressure","temperature and pulse oximetry reading"],
   ans:[0,2,4,5,6],
   rat:{c:"Diminished left breath sounds (hemothorax), leaking labs (Hgb 9/Hct 27, WBC 19k), the guarded LUQ abdomen (splenic injury), the shock-pattern vitals (P 116, RR 24, BP 90/50), and temperature/oximetry surveillance all demand immediate follow-up.",
   o:["Correct — diminished left breath sounds suggest hemothorax: follow up now.","Shoulder pain (Kehr sign) is meaningful context but the hemodynamic findings outrank it for immediate follow-up.","Correct — Hgb 9 with Hct 27 indicates active blood loss.","A productive cough with otherwise normal oxygenation is a lower-priority finding.","Correct — tenderness/guarding/dullness in the LUQ signals splenic injury.","Correct — tachycardia with hypotension is a shock pattern.","Correct — temperature trend and oximetry must be watched (98% now, but a hemothorax can drop it fast)."],
   s:"Cluster the threats: breathing (lung sounds), bleeding (labs + abdomen), and perfusion (P/RR/BP). Context pain and a stable cough are lower tier."}},
  {step:"analyze", t:"multi", stem:"Which of the following issues is the client at risk of developing? Select all that apply.",
   reveal:["hnp","notes","vitals","labs"],
   opts:["stroke","hemothorax","bowel perforation","splenic laceration","pulmonary embolism","abdominal aortic aneurysm"],
   ans:[1,3],
   rat:{c:"Left rib-cage trauma with LUQ guarding, falling hemoglobin, and referred shoulder pain puts hemothorax (chest injury) and splenic laceration at the top of the risk list.",
   o:["Stroke has no mechanism in this blunt torso trauma.","Correct — rib injury with diminished breath sounds risks hemothorax.","Bowel perforation is not the pattern for this injury (no peritoneal signs pointing there).","Correct — LUQ tenderness/guarding with dropping Hgb is splenic injury until imaging says otherwise.","Pulmonary embolism is not an immediate trauma mechanism here (no long travel/immobility story).","AAA is a disease of older adults with a different presentation."],
   s:"Match mechanism → injury: left ribs + LUQ blow = spleen + lung. Vascular/degenerative diagnoses (stroke, AAA, PE) don’t fit the mechanism."}},
  {step:"prioritize", t:"cloze", stem:"Complete the following sentence by choosing from the list of options.",
   reveal:["hnp","notes","vitals","labs"],
   cloze:{lines:[
    {pre:"The nurse should first address the client’s", post:".", opts:["abdominal pain","respiratory status","laboratory results"], ans:1}]},
   rat:{c:"Diminished left breath sounds mean the threatened airway/breathing compartment comes first — ABCs precede pain control and lab trending.",
   o:["Abdominal pain matters, but breathing outranks pain.","Correct — respiratory status is the ABC priority.","Labs guide the bleeding picture but breathing comes first."],
   s:"When one dropdown is “respiratory status” and the client has diminished breath sounds, ABC wins the “first” slot."}},
  {step:"generate", t:"matrix", stem:"The nurse has reviewed the Nurses’ Notes from 1000. For each potential order, click to specify whether the potential order is indicated or not indicated for the client.",
   reveal:["notes","vitals","labs"],
   matrix:{cols:["Indicated","Not indicated"], mode:"radio",
    rows:["intravenous fluids","serum type and screen","chest percussion therapy","insertion of a nasogastric (NG) tube","administration of prescribed pain medication"],
    ans:[0,0,1,1,0]},
   rat:{c:"Splenic laceration with hemothorax heading to surgery: IV access/fluids, type and screen (transfusion readiness), and analgesia are indicated. Chest percussion is contraindicated over injured tissue, and an NG tube has no role in this blunt-trauma pathway.",
   o:["Indicated — restore volume and keep access for surgery/transfusion.","Indicated — blood must be ready for possible transfusion.","Not indicated — percussion over a hemothorax/rib injury worsens it.","Not indicated — no obstructive or peritonitis process to decompress.","Indicated — pain control supports breathing mechanics."],
   s:"Trauma orders: fluids + type & screen + analgesia yes; anything that shakes the chest (percussion) or addresses the wrong pathology (NGT) no."}},
  {step:"act", t:"multi", stem:"The nurse has reviewed the Nurses’ Notes from 1030 (client referred for immediate surgery). Which of the following actions should the nurse take? Select all that apply.",
   reveal:["notes"],
   opts:["Mark the surgical site.","Provide the client with ice chips.","Perform a medication reconciliation.","Obtain consent for surgery from the client.","Insert a peripheral venous access device (VAD).","Inform the client about the risks and benefits of the surgery.","Assess the client’s previous experience with surgery and anesthesia.","Ask the client’s parents to wait in the waiting room while the plan of care is discussed with the client."],
   ans:[2,4,6],
   rat:{c:"Preoperative nursing: reconcile medications, secure IV access, and assess prior surgery/anesthesia experience. Site marking, consent (a minor — parents sign), risk/benefit disclosure (provider duty), and excluding parents are NOT the nurse’s actions here.",
   o:["Site marking is the surgeon’s responsibility.","Ice chips violate NPO status before surgery.","Correct — medication reconciliation prevents perioperative errors.","The 17-year-old is a minor — the parents provide consent; the nurse witnesses at most.","Correct — a VAD is needed for fluids, drugs, and anesthesia.","Risks/benefits are explained by the provider/surgeon — that IS the informed-consent conversation.","Correct — prior anesthesia experience (e.g., malignant hyperthermia, PONV) changes the plan.","Parents should be included — they consent for the minor."],
   s:"Preop checklist split: nurse does reconciliation, IV access, history/assessment, teaching; surgeon does site marking + risk disclosure; consent comes from the parents of a minor."}},
  {step:"evaluate", t:"hotspot", stem:"The nurse has reviewed the Progress Notes from 0800 (postoperative day 3 after splenectomy). Click to highlight the findings below that indicate a worsening of the client’s status.",
   reveal:["progress"],
   hotspot:{mode:"rows", rows:["Ambulates in the corridor 3–4 times daily with minimal assistance","Clear breath sounds","Chest tube in place with tidaling of the water chamber on deep inspiration","Refuses to use the incentive spirometer, stating it causes left-sided chest pain","Using the patient-controlled analgesia (PCA) device maximally every hour","Continues to have intermittent nausea and vomiting","Adequate urine output","Abdominal incision dressing clean, dry, and intact"], ans:[3,4,5]},
   rat:{c:"Refusing the incentive spirometer (atelectasis risk with a chest tube in place), maximal hourly PCA use (uncontrolled pain), and continued nausea/vomiting are the worsening markers. Ambulation, clear lungs, tidaling, urine output, and a clean incision are reassuring.",
   o:["Good mobility — improving.","Clear lungs — expected/reassuring.","Tidaling is NORMAL chest-tube function — reassuring.","Worsening — refusing airway hygiene postoperatively risks atelectasis/pneumonia.","Worsening — maximal PCA use means pain is not controlled.","Worsening — ongoing nausea/vomiting on postop day 3 is not expected.","Adequate output — reassuring.","Clean incision — reassuring."],
   s:"“Worsening” = new problems or uncontrolled symptoms: refused therapies, maxed analgesia, persistent vomiting. Normal findings (tidaling!) are the planted distractors."}}]},

/* ── Document items 65–70 · Case Study (6 screens) ────────────────── */
{id:"CASE-DEMO-03", title:"Fever and Breathlessness — Female, 78", setting:"Emergency department", sys:"RESP", cn:"RRP", d:2, b:0.5,
 summary:"78-year-old woman with atrial fibrillation and hypertension returns 6 days after hospitalization with fever, productive cough, and worsening shortness of breath.",
 exhibits:{
  notes:{name:"Nurses’ Notes", type:"text", body:"1000: Brought to the ED by the client’s adult child due to increased shortness of breath this morning. Adult child reports the client has been running a fever for the past few days, has started to cough up greenish mucus, and complains of soreness throughout the body. Hospitalized 6 days ago for atrial fibrillation; history of hypertension. Vital signs: T 101.1° F (38.4° C), P 92, RR 22, BP 152/86, pulse oximetry 94% on oxygen at 2 L/min via nasal cannula. Breathing slightly labored; coarse crackles (rales) in bilateral lung bases. Skin slightly cool to touch, pale pink; pulses 3+ and irregular; capillary refill 3 seconds. Alert and oriented to person, place, and time. Adult child states, “Sometimes it seems like my parent is confused.” Peripheral VAD placed in right forearm.\n1200: Called to bedside by the adult child, who states the client “isn’t acting right.” On assessment, client is difficult to arouse, pale, and diaphoretic. Vital signs: P 112, RR 32, BP 90/62, pulse oximetry 91% on 2 L/min via nasal cannula."},
  orders:{name:"Orders (1215)", type:"text", body:"• insert an indwelling urethral catheter\n• vancomycin 1 g, IV, every 12 hours\n• computed tomography (CT) scan of the chest\n• 0.9% sodium chloride (normal saline) 500 mL, IV, once\n• laboratory tests: blood culture and sensitivity (C & S), complete blood count (CBC), arterial blood gas (ABG)"}},
 items:[
  {step:"recognize", t:"multi", stem:"Select the 4 client findings that require immediate follow-up.",
   reveal:["notes"],
   opts:["vital signs","lung sounds","capillary refill","client orientation","radial pulse characteristics","characteristics of the cough"],
   ans:[0,1,2,4],
   rat:{c:"Fever/hypoxia/rising BP (vital signs), crackles with labored breathing (lung sounds), 3-second capillary refill (perfusion), and 3+ irregular pulses (atrial fibrillation) are the four immediate follow-up areas. Orientation is intact, and the cough is already being evaluated.",
   o:["Correct — fever, tachypnea, hypoxemia, and hypertension demand follow-up.","Correct — crackles with labored breathing signal fluid/infection in the lungs.","Correct — 3-second refill suggests sluggish perfusion.","Orientation is currently intact — the confusion comment is historical.","Correct — 3+ and irregular pulses reflect the dysrhythmia and need follow-up.","The greenish cough is part of the presenting picture but less urgent than the other four."],
   s:"Pick the physiologic threat areas: vitals, lungs, perfusion, pulse. Intact orientation and an already-characterized cough are the distractors."}},
  {step:"analyze", t:"matrix", stem:"For each client finding below, click to specify if the finding is consistent with the disease process of pneumonia, a urinary tract infection (UTI), or influenza. Each finding may support more than 1 disease process.",
   reveal:["notes"],
   matrix:{cols:["Pneumonia","Urinary Tract Infection","Influenza"], mode:"check",
    rows:["fever","confusion","body soreness","cough and sputum","shortness of breath"],
    ans:[[0,1,2],[0,1],[2],[0],[0,2]]},
   rat:{c:"Fever fits all three. Confusion in an older adult is classic for both pneumonia and UTI. Body (muscle) soreness points to influenza. Cough with greenish sputum fits pneumonia. Shortness of breath fits pneumonia and influenza.",
   o:["Fever: all three processes.","Confusion: pneumonia and UTI (atypical presentation in older adults).","Body soreness: influenza myalgias.","Cough and sputum: pneumonia.","Shortness of breath: pneumonia and influenza."],
   s:"In older adults, infection presents atypically: confusion weighs heavily for pneumonia AND UTI; myalgia is the influenza signature."}},
  {step:"prioritize", t:"cloze", stem:"Complete the following sentence by choosing from the list of options.",
   reveal:["notes"],
   cloze:{lines:[
    {pre:"The client is at highest risk for developing", post:".", opts:["stroke","hypoxia","dysrhythmias","a pulmonary embolism"], ans:2}]},
   rat:{c:"With atrial fibrillation, hypoxemia, fever, and dehydration, the highest-risk complication is a dysrhythmia — AF with RVR can degenerate rapidly and the client is already showing irregular 3+ pulses and tachycardia.",
   o:["Stroke risk exists with AF but is not the acute instability driver here.","Hypoxia is present (91–94%) and being treated with oxygen — real, but the rhythm is the wildest card.","Correct — dysrhythmias: AF + hypoxia + infection + electrolyte shifts is the dangerous combination.","PE is possible with immobility but nothing in the data points to it specifically."],
   s:"When the history hands you atrial fibrillation plus physiologic stress, the complication the exam wants is the dysrhythmia."}},
  {step:"generate", t:"matrix", stem:"The nurse has reviewed the Nurses’ Notes from 1200. For each potential nursing intervention, click to specify whether the intervention is indicated or not indicated for the care of the client.",
   reveal:["notes"],
   matrix:{cols:["Indicated","Not indicated"], mode:"radio",
    rows:["Prepare the client for defibrillation.","Place the client in a semi-Fowler’s position.","Request an order to increase the oxygen flow rate.","Request an order to insert an additional peripheral VAD.","Request an order to administer an intravenous fluid bolus."],
    ans:[1,0,0,0,0]},
   rat:{c:"The client is deteriorating (difficult to arouse, RR 32, BP 90/62, 91%) but has a pulse and is not in arrest — defibrillation is not indicated. Positioning, more oxygen, additional IV access, and a fluid bolus are all indicated.",
   o:["Not indicated — the client has a pulse; defibrillation is for pulseless VT/VF.","Indicated — semi-Fowler’s eases the work of breathing.","Indicated — 91% on 2 L/min demands escalation.","Indicated — a second VAD supports fluids and medications.","Indicated — hypotension with infection needs volume."],
   s:"Defibrillation = pulseless VT/VF (or unstable wide-complex tachycardia with a pulse decision made by the team) — a difficult-to-arouse client with a pulse gets positioning, oxygen, access, and fluids."}},
  {step:"act", t:"hotspot", stem:"The nurse has reviewed the Orders from 1215. Click to highlight the orders that the nurse should consider a priority.",
   reveal:["notes","orders"],
   hotspot:{mode:"rows", rows:["Insert an indwelling urethral catheter","Vancomycin 1 g, IV, every 12 hours","Computed tomography (CT) scan of the chest","0.9% sodium chloride (normal saline) 500 mL, IV, once","Laboratory tests: blood culture and sensitivity (C & S), CBC, ABG"], ans:[1,3,4]},
   rat:{c:"Priority orders: obtain the blood cultures (then antibiotics), start the antibiotic, give the fluid bolus, and check the CBC/ABG — cultures-before-antibiotics and perfusion/oxygenation come first. The catheter and CT are necessary but not priorities.",
   o:["A catheter is monitoring/comfort — not a priority order.","Priority — antibiotics treat the source; drawn after cultures.","CT is diagnostic follow-through — important, not the priority.","Priority — the client is hypotensive and needs volume.","Priority — cultures before antibiotics; CBC/ABG track infection and gas exchange."],
   s:"Sepsis-style order triage: cultures → antibiotics → fluids/labs. Imaging and catheters wait."}},
  {step:"evaluate", t:"matrix", stem:"For each assessment finding, click to specify if the finding indicates that the client’s condition has improved, not changed, or worsened.",
   reveal:["notes","orders"],
   matrix:{cols:["Improved","Not Changed","Worsened"], mode:"radio",
    rows:["pale skin tone","respirations, 36","blood pressure, 118/68","pulse oximetry reading 91%","client interacting with adult child at bedside"],
    ans:[2,2,0,1,0]},
   rat:{c:"Pale skin persists (worsened compared with her baseline pink tone), respirations rose from 32 to 36 (worsened), blood pressure recovered from 90/62 to 118/68 (improved), oxygen saturation is still 91% (unchanged), and interacting with family replaces “difficult to arouse” (improved).",
   o:["Pale skin tone: worse than baseline — worsened.","Respirations up from 32 to 36 — worsened.","Blood pressure 118/68 from 90/62 — improved.","91% is where it was — not changed.","Alert and interacting versus difficult to arouse — improved."],
   s:"Evaluate against each finding’s own baseline. BP and mentation improved; skin, respiratory rate worsened; SpO2 flat."}}]},

/* ── Document item 112 · Bow-Tie ──────────────────────────────────── */
{id:"CASE-DEMO-04", title:"Focal Deficits After Influenza — Female, 79 (Bow-Tie)", setting:"Emergency department", sys:"NEURO", cn:"PAA", d:3, b:0.9,
 summary:"79-year-old with atrial fibrillation presents with right-sided ptosis, facial drooping, hemiparesis, and expressive aphasia.",
 exhibits:{
  notes:{name:"Nurses’ Notes 1215", type:"text", body:"1215: Client presents with right-sided ptosis and facial drooping, right-sided hemiparesis, and expressive aphasia. Adult child reports the client recently had influenza. Skin warm and dry. Lung sounds clear; apical pulse irregular. Bowel sounds active in all quadrants. Incontinent of urine 2 times in the ED; adult child reports the client is typically continent of urine. Capillary refill 3 seconds. Peripheral pulses palpable, 2+. Vital signs: T 97.5° F (36.4° C), P 126, RR 18, BP 188/90, pulse oximetry 90% on room air."},
  hnp:{name:"History and Physical", type:"text", body:"Neurological: history of a stroke 2 years ago.\nCardiovascular: history of hypertension; atrial fibrillation; hyperlipidemia.\nGastrointestinal: history of gastrointestinal bleeding 2 months ago.\nEndocrine: diabetes mellitus (type 2) for 30 years.\nImmunological: influenza 3 weeks ago."},
  labs:{name:"Laboratory Results 1215", type:"kv", rows:[["Random serum glucose (ref 82–115 mg/dL)","76 mg/dL (4.2 mmol/L)"]]}},
 items:[
  {step:"analyze", t:"emr", stem:"The nurse is reviewing the client’s assessment data to prepare the client’s plan of care. Complete the diagram by choosing from the choices below to specify what condition the client is most likely experiencing, 2 actions the nurse should take to address that condition, and 2 parameters the nurse should monitor to assess the client’s progress.",
   reveal:["notes","hnp","labs"],
   groups:[
    {h:"Condition most likely experiencing (select 1)", opts:["Bell’s palsy","hypoglycemia","ischemic stroke","urinary tract infection (UTI)"], ans:[2]},
    {h:"Actions to take (select 2)", opts:["Administer oxygen at 2 L/min via nasal cannula","Request a prescription for an oral corticosteroid","Insert a peripheral venous access device (VAD)","Obtain a urine specimen for urinalysis and culture and sensitivity (C & S)","Request an order for 50% dextrose in water intravenously"], ans:[0,2]},
    {h:"Parameters to monitor (select 2)", opts:["urine output","temperature","neurologic status","electrocardiogram (ECG) rhythm","serum glucose level"], ans:[2,3]}],
   rat:{c:"Acute focal deficits (right ptosis, droop, hemiparesis, expressive aphasia) with atrial fibrillation and BP 188/90 indicate an ischemic stroke (glucose 76 rules out the mimic hypoglycemia; Bell’s palsy spares the arm and speech). Actions: oxygen for the 90% saturation and a peripheral VAD for the stroke pathway. Monitor neurologic status and the ECG (the AF that caused it).",
   o:["Bell’s palsy is a peripheral facial weakness — it does not cause hemiparesis or aphasia.","Glucose is 76 mg/dL — below-mimic hypoglycemia is excluded.","Correct — sudden focal deficits + AF + severe hypertension = ischemic stroke.","UTI can cause confusion in elders, not unilateral focal motor deficits.","Correct — oxygen supports the 90% saturation during the stroke pathway.","Corticosteroids treat Bell’s palsy, not stroke.","Correct — IV access is needed for labs, imaging pathway, and medications.","Urinalysis addresses a UTI hypothesis that does not fit.","Dextrose treats hypoglycemia — the glucose is 76, not low enough to cause this.","Urine output relates to the UTI/volume question, not stroke progression.","Temperature monitors infection, not the stroke.","Correct — serial neuro checks track progression/response.","Correct — the irregular apical pulse (AF) is the embolic source: monitor the rhythm.","Glucose is already measured and not the driver."],
   s:"Bow-tie logic: pick the condition that explains the MOST findings, then choose actions/parameters that act on THAT condition and its cause."}}]},

/* ── Document item 120 · Stand-Alone Trend ────────────────────────── */
{id:"CASE-DEMO-05", title:"Projectile Vomiting in a Newborn — 10 Days Old", setting:"Emergency department", sys:"GI", cn:"RRP", d:2, b:0.55,
 summary:"10-day-old with progressive post-feeding vomiting becoming projectile, with a soft fontanel and hyperactive bowel sounds progressing to distention.",
 exhibits:{
  flow:{name:"Flow Sheet", type:"kv", rows:[["Intake 1000","480 mL (formula)"],["Output 1000","3 small yellow stools"],["Intake 1400","60 mL (formula)"],["Output 1400","40 mL (emesis)"],["Intake 1800","60 mL (formula)"],["Output 1800","40 mL (emesis)"]]},
  notes:{name:"Nurses’ Notes", type:"text", body:"1000: Parent reports the client has been vomiting after drinking each bottle of formula; parent estimates the client vomits half of each bottle with each feeding. Client triaged. Vital signs: T 97.7° F (36.5° C), P 124, RR 30.\n1400: Client experienced projectile vomiting 30 minutes after drinking 60 mL of formula. Anterior fontanel soft and flat. Bowel sounds hyperactive.\n1800: Client experienced projectile vomiting 30 minutes after drinking 60 mL of formula. Abdomen distended. Client crying and inconsolable."}},
 items:[
  {step:"analyze", t:"multi", stem:"Which of the following diagnostic procedures should the nurse anticipate the physician would order? Select all that apply.",
   reveal:["flow","notes"],
   opts:["barium enema","abdominal x-ray","abdominal ultrasound","complete metabolic panel","esophagogastroduodenoscopy (EGD)"],
   ans:[1,2,3],
   rat:{c:"Progressive projectile vomiting in a 2–3-week-old is hypertrophic pyloric stenosis until proven otherwise: abdominal ultrasound is the diagnostic standard, abdominal x-ray supports evaluation, and a complete metabolic panel tracks the classic hypochloremic hypokalemic metabolic alkalosis and dehydration.",
   o:["A barium enema evaluates lower-GI pathology (e.g., intussusception) — not pyloric stenosis.","Correct — abdominal x-ray contributes to the initial evaluation.","Correct — ultrasound confirms the hypertrophied pylorus.","Correct — CMP quantifies the alkalosis, hypokalemia, and dehydration.","EGD is an invasive upper endoscopy — not the anticipated first-line study in an infant."],
   s:"Projectile vomiting + hungry infant ≈ pyloric stenosis: think ultrasound + electrolytes (alkalosis!). Save the contrast enemas for intussusception (red-currant-jelly stools)."}}]},

/* ── Document item 98 · Stand-Alone Multiple-Screen Item ──────────── */
{id:"CASE-DEMO-06", title:"Morning Assessment, Psychiatric Unit", setting:"Inpatient psychiatric unit", sys:"PSYCH", cn:"PSY", d:1, b:0.1,
 summary:"Day-2 morning assessment of a client hospitalized with acute schizophrenia: withdrawn, blunted affect, disorganized speech, hallucinations, and paranoid delusions.",
 exhibits:{
  hnp:{name:"History and Physical", type:"text", body:"Psychiatric: third admission this year for acute signs and symptoms of schizophrenia; family history of mental illness."},
  progress:{name:"Progress Notes", type:"text", body:"Day 2, 0830: Withdrawn. Remains in assigned client room. Exhibiting blunted affect and jumbled, illogical speech. Experiencing auditory hallucinations and paranoid delusions."},
  orders:{name:"Orders", type:"text", body:"Day 2, 0830: • attend group sessions when stabilized • risperidone 4 mg, p.o., daily"}},
 items:[
  {step:"act", t:"single", stem:"The nurse in the psychiatric unit has completed the morning assessment of the client. Which of the following interventions should the nurse take next?",
   reveal:["progress","orders","hnp"],
   opts:["Encourage the client to attend 1 group session today.","Teach the client’s family members about how to prevent a relapse.","Administer the prescribed dose of risperidone.","Prepare to discharge the client to a community treatment program."],
   ans:2,
   rat:{c:"The client is in an acute psychotic episode (active hallucinations and delusions). The next intervention is the prescribed antipsychotic — stabilization precedes group work, family teaching, or discharge planning.",
   o:["The order itself says group sessions come when stabilized — active psychosis first.","Family relapse-prevention teaching is valuable later in the stay.","Correct — treat the acute psychosis with the prescribed risperidone before anything else.","Discharge planning on day 2 of a third admission for acute psychosis is premature."],
   s:"Sequence psychiatric care by acuity: medicate active psychosis → stabilize → group/teaching → discharge planning. The orders often tell you the order."}}]}
];
